### ISSUE TITLE
Autoplay adding unaired episodes to playlist

### ISSUE THREAD

**Issue by RagnarLothbrok-Odin** [nixgates/plugin.video.seren#10]
I use Seren with Trakt, I do not have the official Trakt addon. I also use the up-next addon.

I noticed that around 50% of the time, unaired episodes are adding to the playlist, due to idiots mislabeling episodes they actually end up playing. This would not be an issue as I just stop it when it starts, but my issue is that Trakt is marking it as watched. Adding a percentage needed to watch before marking as watched would fix this, or find a way to stop adding unaired episodes to the playlist.
I can honestly live with stopping the unaired episode, but the marking it as watched is annoying as I have to go into my history and unmark them.

**Comment by nixgates** [comment]
Apologise, fat finger closed the issue.

It's a known issue, should be fixed for 0.1.19

**Comment by nixgates** [comment]
Development git is now at 0.1.22 and the issue should be fixed.

Update to repo should happen within the next 24 hours.
