### ISSUE TITLE
Trakt double authorization

### ISSUE THREAD

**Issue by farmaher** [nixgates/plugin.video.seren#100]
Whenever I have to give Trakt authorization to Seren, I should do it twice to get it working. After first authorization, even by restarting kodi, I am still unable to see my watchlists and should re-authorize Trakt to be able to open my watchlists under My Movies / My TV Shows. The first authorization is given to **Seren** but on second try, the authorization is given to **Trakt API KEY**!

I am experiencing this issue since I started using Seren ( from v.1.xx).

**Comment by drinfernoo** [comment]
Are you using a custom Trakt key in the "API Keys" section of settings?

**Comment by farmaher** [comment]
Yes, I use personal Trakt API key but I think it shouldn't aks for authorization twice.

**Comment by drinfernoo** [comment]
Try removing your keys and see if it still asks twice. I'm just trying to find the source of the bug.

**Comment by farmaher** [comment]
I removed the key and I can confirm that it was authorized on first try. So, this only happens when the user input Trakt API keys.

**Comment by denimnani** [comment]
This also happened to me a some time ago,
I have restarted seren:
Then in first place put my API and only then authorized trakt, for me solved the issue.
If you authorize trakt first and after use a personal API, it will cause this.

**Comment by nixgates** [comment]
@farmaher The issue you faced is likely as @denimnani advised

The first authorization is provided for Seren's default Trakt ID.

When you attempt to use a different Trakt API key with Seren, you must authorize again with this new key.
