### ISSUE TITLE
[Feature request] Set text color

### ISSUE THREAD

**Issue by Baardmans** [nixgates/plugin.video.seren#103]
Since the 0.2.2 update the text color has changed from white to red. I would like to be able to set this myself. (I'd prefer red text only for unaired episodes.)

**Comment by drinfernoo** [comment]
Only unaired epsiodes *should be* showing up in red italics.

**Comment by nixgates** [comment]
This is a bug that is currently affecting some users where Seren is unable to identify release dates.

Could you please provide a clean debug log or try to clear your cached meta in the trakt sync tools menu.

**Comment by nixgates** [comment]
Issue fixed in version 0.2.23
