### ISSUE TITLE
Next Up has stopped updating after watched episode since 2.22

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#108]
Before the big update of .22 the Next Up list would update after watching an episode and return to the next up list.

This happened on two seperate devices. 

I am using AuraMod.

After watching an episode from the Next Up widget after closing the episode and returning to Next Up widget after about 30 seconds the widget would update and teh episode would disappear.

This does not happen in the latest version .24 something has broken it. 

I have not updated my version of AuraMod in a month and the only thing that has changed with my setup is Seren updating in the last week.

**Comment by denimnani** [comment]
Same issue here...

**Comment by nixgates** [comment]
@lukehansford 

Seren does not control any refreshing of widgets. The addon that would have taken care of refreshing your widgets after playback would have likely been the Skin Helper Widget.

**Comment by denimnani** [comment]
@nixgates 
I think the issue is not in the Skin Helper Widget.
I have tried directly on seren and after watch an episode the next up won't update,  only after a few minutes or force syncing.
Before was working instantaneously.
This is not a deal breaker but will be nice to work as once before.
Thanks for your hard work :)

**Comment by lukehansford** [comment]
I totally agree. the issue is not related to the skin helper widget. it stopped working straight after the .22 update and I haven't had any updates to the skin helper widget for ages.

only clearing the cache is updating the list for me. even a kodi restart and the widgets reloading doesnt update the next up list.

I posted this issue on reddit and straight away SerpentDrago replied and said the issue has been identified and will be fixed in the next update and he confirmed it is a bug with Seren.

https://www.reddit.com/r/Addons4Kodi/comments/bi5kdl/seren_next_up_has_stopped_updating_after_an/elzcukd?utm_source=share&utm_medium=web2x

Before it was working instantaneously. after you closed an episode and returned to your widgets on AuraMod it would updated within 30 or so seconds. it got broken in the .22 update.

Lets hope the fix is in the next Seren Update as confirmed.

**Comment by drinfernoo** [comment]
@lukehansford Fortunately, @nixgates has a much better idea of what is "confirmed" to be in the next versions than @SerpentDrago does 😂
