### ISSUE TITLE
Can't configure the settings menu

### ISSUE THREAD

**Issue by saba1970** [nixgates/plugin.video.seren#109]
Hello,
after the latest update I had lost my RD settings. So I want to fill these settings in the settings menu. But when I opened the settings menu I couldn't do anything. I had just a black screen.

Is this a problem in the new update?

**Comment by denimnani** [comment]
At least for me this never happen,
Try wipe the addon date and redo all settings, this maybe solve your issue.
Otherwise only Nix can help you...

**Comment by nixgates** [comment]
Sounds like an odd issue, @saba1970 could you please provide a debug log for me to investigate the cause of the issue. 

Thank you.

**Comment by saba1970** [comment]
@denimnani . Thanks. After the wipe addon everything works fine again.
