### ISSUE TITLE
Movie Watchlist sort order permanently stuck at recently added or rank.

### ISSUE THREAD

**Issue by mophawka** [nixgates/plugin.video.seren#11]
When changing the default order of any "personal" list and clearing cache the list ordered changed in seren with no issues.
However, Trakt movie watchlist always defaults to rank or recently added within seren no matter what sort order i choose in trakt.tv. I upgraded to latest developmental build, cleared cache, reauth trakt and still am having the same issue.  This is occurring on 3 different trakt accounts and 3 different devices, Windows, RPi running LIBREelec and a nVidia Shield. 
Scanning thru the seren megathread i've read few others mention the very same issue.
Thank you,

**Comment by nixgates** [comment]
Cool sounds like I've missed something. I'll dig into it and hopefully get 0.1.23 up in a few hours

**Comment by mophawka** [comment]
@nixgates Thanks for putting up the new version to fix Trakt movie watchlist. upon testing the sorting is only partially working for me. I set the watchlist to title, cleared cache, and it worked! Watchlist sorted by title. Then i attempted to sort by "Release Date" and then "Percentage". neither sorted and it defaulted to rank/recently added. Not sure what to make of it.

Thank you

**Comment by nixgates** [comment]
Ok I've dug through all the sorts manually and checked that they all should work come 0.1.25
If this issue persists after the update please let me know.

**Comment by mophawka** [comment]
looking forward to it. will update this post shortly after update is available and tested. cheers

**Comment by mophawka** [comment]
Movie Watchlist sorting is now fixed with 0.1.25 update. Thank you!
