### ISSUE TITLE
Trakt sync

### ISSUE THREAD

**Issue by Fuckuptheworld13** [nixgates/plugin.video.seren#114]
how long do i have to wait for trakt sync to done i been waiting for more then 3hr now and why is it slowing down the whole nvidia shield tv i cant do nothing in the background is going slow mode in kodi and the out side of kodi while doing this trakt sync stuff i cant multi task slowing down my shield tv

**Comment by Fuckuptheworld13** [comment]
5hrs later the trakt sync is done and no more slow down on the shield

**Comment by denimnani** [comment]
Hey men be pacient the addon is in beta stage, you must expect bugs...
I use seren in 2 shield tv and for now the sync is working for me.
I don´t now if you have a lot of content or not, but for me the full syncing process take about 4 to 5 minutes and i have a lot to sync.
Try to rebuild yor database it may solve your issue.

**Comment by nixgates** [comment]
Can you please provide a debug log in case something has gone wrong.

Is the sync still progressing? How old is your trakt account? Is there a lot of data to process?

There are many factors here. Personally I have over 200 shows I have watched that I track and over 2000 episodes/movies I have marked watched in my trakt account.

The entire sync takes for my account takes about 15 minutes for me. Thats rather fast considering the amount of data to be processed.

It will slow things down because there is a lot to be done. I actually throttled it before I pushed out the update but perhaps I may need to throttle it more. If you could provide more information I would be very appreciative.

**Comment by Fuckuptheworld13** [comment]
Please! dont take this as an attack im a "Big Fan!" of your work @nixgates i really Appreciate! what you do SEREN is my "Number" one addon the problem is that i never had no issues with seren at all the thing is that i did a reinstall of seren because of the update of seren being slower so when the trakt sync start it doing it thing thats when i was having problems like taking 3hr or so to be done i did the trakt sync before i know it doesnt take that long and the slow down of the shield and kodi never happened to me before but now it seem like it slower navigating sometime then the old seren and scraping for links take longer then before i thing is because of the checking local database it stay there for a few i would love to help where can i upload my logs and theres two log kodi or kodi.old which one and dose my log got my personal info like password etc.     

Thank you

**Comment by denimnani** [comment]
@Fuckuptheworld13 check on google "how to upload kodi log" there are many tuturials on this.
(example: https://www.youtube.com/watch?v=WA5xkTIpdTk)
The file you need is Kodi.log not kodi.log.old, the log doesn't show your passowords..

**Comment by nixgates** [comment]
@Fuckuptheworld13 No it's fine, no attack taken 😂 

Is the progress of the initial trakt sync moving? Can you see the percentage still rising?

Would you also mind answering the other questions I put forward in the last message?

**Comment by Fuckuptheworld13** [comment]
ok your questions
Is the sync still progressing? if you asking if is doing the trakt sync then yes but took hrs 
How old is your trakt account?i really dont remember i think 2 maybe 3years
Is there a lot of data to process?182 tv shows
i recently did a trakt sync again because i was getting an error trying to open liked lists on my trakt it wasnt opening the trakt liked list in movies and tv showes the error start it with movie liked list first but now it seem to be working for now but while doing the trakt sync thing again i was running in to the same problem with the sync taking 3hrs or more to be done it stay loading here [https://drive.google.com/file/d/1y5OsWkE5mAUrGL81bPRIF13-etZ4-wqE/view?usp=sharing](url) and the slow down o the shield tv  

i also have logs
https://paste.kodi.tv/movicaxici.kodi
anther site logs site
https://paste.ubuntu.com/p/mmq6GgQyPV/

THANKS @nixgates

**Comment by Fuckuptheworld13** [comment]
i got the same error i had before today i cant open nothing in my trakt the only thing i could open is my collection error message : https://drive.google.com/file/d/1EA-sBwcuxjdk-pOsfvBUevMBnHqZbzYc/view?usp=sharing 

new logs 
https://paste.kodi.tv/yebopuvadu.kodi

**Comment by Fuckuptheworld13** [comment]
@nixgates how can i rollback to the old ver. im to much problems with the new ver. is to much every time im having a problem/errors i have to start all over and reset seren and i have to want 3hrs for the trakt sync stuff to be done

**Comment by nixgates** [comment]
https://github.com/nixgates/nixgates/raw/master/packages/plugin.video.seren/plugin.video.seren-0.1.35.zip

That's a link to manually revert to pre-trakt sync

**Comment by nixgates** [comment]
@Fuckuptheworld13 that error you sent through though was because your device was having issues connecting to Trakt though, nothing to do with the Trakt Sync Database

**Comment by Fuckuptheworld13** [comment]
@nixgates you right about that all this shi** going on is probably my trakt because when the trakt sync is loading is thinking too hard on the collected episodes part im give it one more go with this trakt account if not is over for this trakt stuff and now something cross my mind i think is maybe because i added a few trakt liked links from other trakt users smh im sorry about all this 

Thanks @nixgates

**Comment by Fuckuptheworld13** [comment]
@nixgates if u want u could close this issue i did a new trakt that fix my problem i was having

**Comment by nixgates** [comment]
@Fuckuptheworld13 shame we don't know what caused it but I'm glad you're back up and running 👍
