### ISSUE TITLE
Unaired episodes getting added to playlists

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#115]
This happened a few updates ago and was fixed and seems to be back again in version .30.

If you watch a weekly episode where it's just one that is available you get an error message near the end of the episode when it tries to pre scrape for links.

It states cannot find sources clearly playlist.

Obviously it can't find sources for the next episode because it hasn't aired yet. 

Thankyou

**Comment by nixgates** [comment]
This is addressed and ready for next update, cheers for the information.

**Comment by lukehansford** [comment]
You are welcome and I must say thankyou for all you hard work on Seren :)

**Comment by nixgates** [comment]
@lukehansford no worries :) 

Latest update should resolve the issue, if you could confirm and let me know that would be great 👍
