### ISSUE TITLE
Only play Cached Premium Links

### ISSUE THREAD

**Issue by nafr1** [nixgates/plugin.video.seren#119]
Hello,

I have a Premiumize Account. I would like to ONLY play TORRENT LINKS that are Cached on Premiumize. Is it possible to do that using Seren addon?

Thanks

**Comment by nixgates** [comment]
In the accounts section there is an option to enable/disable hosters per premium account.

Uncheck the hosters option in the premiumize settings and it will not attempt to play them through that account.
