### ISSUE TITLE
[FeatureRequest] Cache Assist for TVShow Season

### ISSUE THREAD

**Issue by ventsislav-georgiev** [nixgates/plugin.video.seren#12]
Currently the cache assist will trigger debrid service download only after no cached sources are found. It will be great if we can trigger cache assist on a whole season. It doesn’t have to check if episodes already have cached sources. Just find torrents with appropriate resolution and add them for  debrid download. This may be used to improve the cached sources, if the current ones are not good.

**Comment by nixgates** [comment]
You can set Seren to ask you to select what source you would like to cache. This sounds like it is appropriate for what you want.
