### ISSUE TITLE
Feature Request: AutoPlay with rules defined

### ISSUE THREAD

**Issue by nafr1** [nixgates/plugin.video.seren#120]
Hello,

I really like the Auto Play option in the Seren addon. One thing I would suggest is the creation of rules (based on settings) to auto select the source. So in the settings, if we can define something like... Autoplay the first Video that has {4k, 1080p etc} resolution, {7.1, 5.1 } Audio, File size between 5gb and 10gb. and Autoplay option looks for something that's closet to that rule and play that video, that would be really good...

**Comment by nixgates** [comment]
Rather than putting a hard and fast rule, Seren uses sort options.

Is there something the sort options aren't fulfilling?

**Comment by nafr1** [comment]
Ummmm it is fulfilling to some extend... so here is how I am using the sorting... I am first sorting by Resolution and than by size. I have also restricted the size to 20GB Max. Now what I hope is the Autoplay is going to try to play a 4K movie with 5.1 or 7.1 audio.... but sometimes it starts playing 2.0 audio movie, although a 5.1 is available.
Also sometimes it starts playing a movie that is suppose to be in English, but it plays the movie in some other language....

So it would be really good if there is a way we can sort/filter based on Audio preference. Same goes for Pre-Emptive termination.... currently it just looks for Resolution.... I think it would be better if you add the option for filtering based on Language, Audio channels etc.

**Comment by babz1989** [comment]
Maybe you could add a tag filter in sorting so that it  would prefer files that have AMZN tag in them for example.
