### ISSUE TITLE
[Feature request] Filter sources

### ISSUE THREAD

**Issue by mLgz0rn** [nixgates/plugin.video.seren#121]
Hey!

Would it be possible to add to the filters so you can like blacklist sources that has certain words in them.
Right now I'm getting an episode of vikings that has french language dubbed over it. So being able to filter out "FR,ES,GER" and so on from the source title would be great.
This is only an issue when using autoplay mostly though.

Kind regards

**Comment by nixgates** [comment]
This sort of filtering isn't likely something that I will be investing into. I think it's going to be a bit beyond most users to implement and will likely cause to many adverse effects.

I would suggest setting your Kodi language settings to force the English audio track if you haven't already and barring that, falling back to Source Select from the context menu
