### ISSUE TITLE
Clicking on a show triggers scraping instead of browsing the show

### ISSUE THREAD

**Issue by babz1989** [nixgates/plugin.video.seren#122]
For some reason, when I click on a show, it triggers scraping instead of allowing me to browse the show. I don't know whether there's a setting for it because I can't find anything. It was working normal for me yesterday until I updated the addon and this has started happening since.

[This is it happening with a homescreen widget](https://streamja.com/zA9q)

[This is it happening directly in the addon](https://streamja.com/9k59)

**Comment by drinfernoo** [comment]
Turn off "Auto Episode Resume" from Seren's settings.

**Comment by babz1989** [comment]
Perfect, that worked! Thank you.
