### ISSUE TITLE
"Next Up" widget caching bug

### ISSUE THREAD

**Issue by Mastacc** [nixgates/plugin.video.seren#123]
The first time I open Kodi every day it is missing things I haven't watched. It seems to reset back to what it was when I first set up the addon, but I can't be entirely sure because I have to wait a day to even check it. The skin loads the "Next Up" widget and shows the wrong TV shows/episodes, but if I reload the skin or go to the "Next Up" section in the addon it now shows up correctly. Once it shows correctly it's fine until the next day.

If I mark an episode watched on the Trakt website, it doesn't show up watched in the addon until the next day. Is that how it's supposed to work? The "Next Up" widget also used to update after an episode was played, but now it takes an entire day.  I know you've said the addon has nothing to do with widgets refreshing, but whatever happened broke the widgets recognizing things have been watched/shouldn't be shown anymore.

Everything was perfect before the big caching update. Ever since then it's been driving me crazy

**Comment by babz1989** [comment]
I've noticed this delay, it's not as extreme as your situation but it does take a while for next up to refresh. I usually have to force a Trakt update then reload the skin for it to show correctly.

**Comment by nixgates** [comment]
The issue with widgets not updating is really not to do with Seren. 

Widgets are updated by the Skin Helper Widgets addon. This update is only triggered in the event an update has been requested by playback stopping and then the home window is opened and only when the home window is opened. Then you must wait again for the actual widgets to be refreshed from that point in time. 

So in short the process is, you play an item, playback ends, you return to the main screen. Skin Helper widgets will then start the refreshing of the widgets and once the widget call is finished, the widget is updated. 

I've done multiple tests from multiple platforms to try to identify what is causing this and ever test I have done and including the tests you've performed @Mastacc by opening the next up menu inside Seren confirms that the data on Seren's side is all correct.

The only thing I can do is set the window to be refreshed after a playback reaches 90% of the video. This in turn will still have all of the current drawbacks that currently exist and will only help to give the Skin Helper Widgets addon a kick should it fail on it's side.
