### ISSUE TITLE
Please stop the Trakt Error. LOL

### ISSUE THREAD

**Issue by JayDigg** [nixgates/plugin.video.seren#124]
Geez, the Failed to authorize Trakt error is wayy to persistent. Every 5 seconds it keeps poping up. I dont even have a second to try to authorize again because everytime i try the error popup comes up and cancels the authorization. Not sure why if fails. Im already synced and Trakt is showing everything. One the error starts its impossible to navigate anywhere. I only have 3 tv shows and 2 movies in my Trakt, so its not a large library.  I did see the other bug report about Trakt losing auth, but the persistant popup is impossible.

**Comment by JayDigg** [comment]
Had to delete data and reinstall. If it comes back ill post a log. Thanks!

**Comment by nixgates** [comment]
The failed to authorize notification is only set to show during the initial authentication process and shouldn't show multiple times unless you have gone through the process multiple times?

Was the Trakt error the following?:

> "Error: Trakt is not authorized \nPlease authorise Trakt in the settings menu to use this feature" 

This will show multiple times over itself if you have widgets connected to Trakt lists but no Trakt Authorised

**Comment by JayDigg** [comment]
Well, i do have widgets, but only to Discover Movies/Discover tv Shows popular sections. I do have submenu shortcuts to Trakt but i wouldnt think that causes any action until clicking on them.

**Comment by drinfernoo** [comment]
@JayDigg What about widgets inside of any hubs or something like that?

**Comment by nixgates** [comment]
@JayDigg what did the text in the dialog say? Was it the text I mentioned above? 

It's hard to identify the issued dialog if I don't know which dialog it is, but in saying that I think I've found the culprit and have fixed what I believe to be the issue for the next release.

If you could still confirm what the text said so I can be sure that would be great.

**Comment by nixgates** [comment]
Closing the issue due to inactivity, if you want to re-open it just let me know
