### ISSUE TITLE
Wrong order of episodes in multi file torrents

### ISSUE THREAD

**Issue by kartana** [nixgates/plugin.video.seren#126]
So I assume Seren just checks for the episode I want to play and assuming it's episode 3 plays the third item in the multi file torrent but this is sometimes wrong. Take Attack on Titan Season 2 for example. There are multiple torrents (bd 1080p) where if you select episode 1 of season 2 it doesn't actually play episode 2 but a different one. If you search for that torrent and add it to Real-Debrid you can see this (seemingly) random order of episodes which is probably causing the confusion for Seren.

**Comment by nixgates** [comment]
Are we talking about the display of titles on the my files section?

The scraping of files uses title comparisons to identify the correct file to play so I would highly doubt that would be the case.

**Comment by kartana** [comment]
Not sure what you mean. I'll try to explain myself better since it's a bit hard to explain, I added a way to reproduce this issue at the bottom:
I am only talking about cached Torrents. I want to watch a certain TV Show, I search for it, it brings up multiple season and I choose season 01 and click on episode 01. (my settings are "Source Select" (no auto play) and "no Pre-emptive termination" btw) 
It starts scraping and brings up the list of available content. In this list there are Torrents containing that one episode, they are named something like with "s01e01" but there are also multi file Torrents (containing the whole season) that don't have a episode in the name. They are often called something like "Great TV Show Season 1 Bluray" or something. If I click on this to play the episode, it doesn't always play the selected episode for reasons I don't know. 

Here is a way to reproduce this problem:

- Enable source select in settings
- Search for TV Show "Attack on Titan". 
- Select Season 2 and select episode 1 called "Beast Titan". 
- It brings up the list of available sources
- Select the source "Attack on Titan Season 2 [bd 1080p][hi10][dual-audio]"
(this name will come up for all the episodes in season 2 since it contains all the episodes in the Torrent)

What you would expect is episode 1 now starts streaming but it's actually episode 8 that starts playing. I checked this Torrent in Real-Debrid and episode 1 is actually episode 1. So this isn't a problem with the Torrent or numbering of the episodes.
I hope this helps.

**Comment by nixgates** [comment]
@kartana There's been a bit of work on the title identification side of things in Seren with the latest release that I believe should have solved this for most items.

Only issue I have is your example there uses attack on titan which is an anime item. The current norm for meta databases doesn't coincide with the general naming conventions of anime titles. While I've added a small amount of work to try and work around this a bit, Seren really isn't built to handle anime titles and I wouldn't suggest counting on it.

I do know that someone is working on a fork of Seren specifically for anime titles but other than that I have no more information on it.

If you feel like the episode selection of standard shows is still failing feel free to let me know and we can re-investigate it.

**Comment by kartana** [comment]
@nixgates Ok, thanks. If they don't use standard naming conventions there is nothing you can do. I didn't know that. But I'll keep that in mind when I am trying to watch Anime. Thanks for all the work you do!
