### ISSUE TITLE
Next Up out of sync when Kodi not used on several days

### ISSUE THREAD

**Issue by baruchin** [nixgates/plugin.video.seren#129]
I have three Kodi setups. Only one of them is the one I use on a daily basis, the other two not that much. The thing is, everytime I launch Kodi on these other two setups, my Next Up section on Seren seems out of sync and I have to go to Seren Trakt tools and force sync. This does not happen on the device I use on a daily basis. So it seems that if Kodi is not used daily, Trakt sync gets messed up on Seren.

**Comment by nixgates** [comment]
Yes this is normal behavior, Next up will use the local data and this will take a minute or so to update after turning the device on.

Not using the local data results in a next up list that takes twice as long to pull and for some older Trakt accounts it becomes an unreasonable amount of time.

You will need to allow a minute or two for the background sync to be processed.
