### ISSUE TITLE
Losing settings

### ISSUE THREAD

**Issue by Lala1976** [nixgates/plugin.video.seren#130]
Every day Seren loses it's settings. When I put my settings in and reboot Kodi it's fine, when I put in the settings and shutdown kodi for a moment it's also fine, but when I shutdown Kodi for the night, the next day al settings are gone. This happens on all my devices (Androidbox and Rpi3b+).

**Comment by denimnani** [comment]
Never had this issue :(

**Comment by nixgates** [comment]
This is actually an issue with Kodi clearing the settings for the addon and some other addons experience the same issue.

I've done a fair amount on Seren's side of things to help reduce this but the best thing you can do is update your Kodi version to 18 and reduce the amount of widgets on your home screen.
