### ISSUE TITLE
Hiding shows from next up on trakt not working

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#131]
If you hide show on the trakt website they are not being hidden in Seren. 

I had to wipe added settings and resync trakt for them to disappear

**Comment by drinfernoo** [comment]
Have you tried hiding it from the Trakt Manager?

**Comment by lukehansford** [comment]
Yes that also didn't work

**Comment by nixgates** [comment]
Making changes like this on the Trakt website will take up to 10 minutes to replicate down to your local device. 

Making the changes using Seren should be applied instantly though so I'll check this now.

**Comment by nixgates** [comment]
Fixed pending update

**Comment by nixgates** [comment]
@lukehansford could you check and confirm this issue is resolved please

**Comment by nixgates** [comment]
Without a reply and having confirm that the hide feature works on my end with the latest release I'm going to close the incident, if you would like you can let me know if the issue persists
