### ISSUE TITLE
Sporadic "No playable sources" on all streams

### ISSUE THREAD

**Issue by Retucex** [nixgates/plugin.video.seren#132]
I have an issue where selecting a source will always show the message "No playable sources found".
This happens randomly and will affect all shows/movies for a period of time.

Coming back after a while sometimes fixes the issue. I still haven't found a way to reliably reproduce the error, nor a way to fix it consistently.

Here is my log file after trying to play a source and it failed:
https://pastebin.com/Qn3kJP1J

**Comment by nixgates** [comment]
Real debrid have been having server issues so this is the likely culprit. Sorry I can't be more help
