### ISSUE TITLE
Resume episode from Openmeta plugin

### ISSUE THREAD

**Issue by zolijosat** [nixgates/plugin.video.seren#133]
I use the Openmeta plugin to add my trakt collection to the kodi library and then use the Seren to actually play the episode. This all works fine, the only issue I have is that the episode progress is not saved to the kodi database and when stopping and restarting the episode, it starts from the beginning.

When stopping and restarting the episode from within Seren, resuming works fine. Is this something that can be fixed in Seren or is this an Openmeta issue? I think this can be handled in Seren automatically (maybe by adding a new parameter to the play url like `resume=1` or even default to resuming just like in the addon itself).

For reference, Openmeta starts the episode by invoking:
```
plugin://plugin.video.seren/?action=getSources&source_select=false&actionArgs=%7B%22episodeInfo%22%3A%20%7B%22art%22%3A%20%7B%22banner%22%3A%20%22{banner}%22%2C%20%22fanart%22%3A%20%22{fanart}%22%2C%20%22landscape%22%3A%20%22{fanart}%22%2C%20%22poster%22%3A%20%22{poster}%22%2C%20%22thumb%22%3A%20%22{thumbnail}%22%7D%2C%20%22ids%22%3A%20%7B%22imdb%22%3A%20%22{epimdb}%22%2C%20%22tmdb%22%3A%20{eptmdb}%2C%20%22trakt%22%3A%20{eptrakt}%2C%20%22tvdb%22%3A%20{epid}%2C%20%22tvrage%22%3A%200%7D%2C%20%22info%22%3A%20%7B%22castandrole%22%3A%20%5B%5D%2C%20%22duration%22%3A%20{duration}%2C%20%22episode%22%3A%20{episode}%2C%20%22genre%22%3A%20%5B%22{genres}%22%5D%2C%20%22imdbnumber%22%3A%20%22{epimdb}%22%2C%20%22mediatype%22%3A%20%22episode%22%2C%20%22mpaa%22%3A%20%22{mpaa}%22%2C%20%22originaltitle%22%3A%20%22{title}%22%2C%20%22plot%22%3A%20%22{plot}%22%2C%20%22premiered%22%3A%20%22{firstaired}%22%2C%20%22rating%22%3A%20{rating}%2C%20%22season%22%3A%20{season}%2C%20%22sortepisode%22%3A%20{episode}%2C%20%22sortseason%22%3A%20{season}%2C%20%22studio%22%3A%20%22{network_clean}%22%2C%20%22title%22%3A%20%22{title}%22%2C%20%22trailer%22%3A%20%22%22%2C%20%22tvshowtitle%22%3A%20%22{clearname}%22%2C%20%22year%22%3A%20{epyear}%7D%7D%2C%20%22showInfo%22%3A%20%7B%22art%22%3A%20%7B%22banner%22%3A%20%22{banner}%22%2C%20%22fanart%22%3A%20%22{fanart}%22%2C%20%22landscape%22%3A%20%22{fanart}%22%2C%20%22poster%22%3A%20%22{poster}%22%2C%20%22thumb%22%3A%20%22{thumbnail}%22%7D%2C%20%22ids%22%3A%20%7B%22imdb%22%3A%20%22tt5614844%22%2C%20%22slug%22%3A%20%22{slug}%22%2C%20%22tmdb%22%3A%20{tmdb}%2C%20%22trakt%22%3A%20{trakt}%2C%20%22tvdb%22%3A%20{id}%2C%20%22tvrage%22%3A%20null%7D%2C%20%22info%22%3A%20%7B%22castandrole%22%3A%20%5B%5D%2C%20%22country%22%3A%20%22%22%2C%20%22duration%22%3A%20{duration}%2C%20%22episode_count%22%3A%20%22{episodes}%22%2C%20%22genre%22%3A%20%5B%22{genres}%22%5D%2C%20%22imdbnumber%22%3A%20%22{imdb}%22%2C%20%22mediatype%22%3A%20%22tvshow%22%2C%20%22mpaa%22%3A%20%22{mpaa}%22%2C%20%22no_seasons%22%3A%20{seasons}%2C%20%22originaltitle%22%3A%20%22{clearname}%22%2C%20%22playcount%22%3A%200%2C%20%22plot%22%3A%20%22{plot}%22%2C%20%22premiered%22%3A%20%22{series_firstaired}%22%2C%20%22rating%22%3A%20{rating}%2C%20%22season_count%22%3A%20{seasons_no_specials}%2C%20%22showaliases%22%3A%20%5B%5D%2C%20%22status%22%3A%20%22{status}%22%2C%20%22studio%22%3A%20%22{network_clean}%22%2C%20%22trailer%22%3A%20%22%22%2C%20%22tvshowtitle%22%3A%20%22{clearname}%22%2C%20%22year%22%3A%20%22{year}%22%7D%7D%7D
```

**Comment by carpathicus** [comment]
I second this. I noticed that if you play the episode through the "standard" seren player, the resume doesn't work, but if you play via seren-smartplay, then resume works fine. Which means movies will never resume when started via openmeta (or wako, etc), since there is no smart play option.

**Comment by nixgates** [comment]
@zolijosat saving progress to the local kodi database has never been a feature nor a goal for Seren as I've always found it to be more cumbersome than it was worth.

I would suggest you utilize Trakt for this purpose, there was a few changes to how the resuming works with Trakt which makes it much more efficient and reliable in the latest release.

If you are still having issues with resuming using Trakt, feel free to raise a new issue here specifically for it so I can work on it.
