### ISSUE TITLE
 Wrong language Seren LibreELEC 9.0.2 (Kodi 18.2) 

### ISSUE THREAD

**Issue by fracmo2000** [nixgates/plugin.video.seren#134]
I have installed Seren on LibreELEC 9.0.2 (Kodi 18.2) working very well, video quality is superb, but I'm getting wrong language on several movies & TV shows, should be English, as I'm in UK.

I've searched settings but can't seem to find anywhere I can specify my preferred language.

**Comment by drinfernoo** [comment]
That's actually in Kodi's settings:

`Settings -> Player -> Language -> Preferred Audio Language`

I usually set it to "User Interface Language".

This likely isn't really much of a Seren issue 👍

**Comment by fracmo2000** [comment]
Thank you "drinfernoo" for your post. I checked my settings. 

The Kodi "Preferred audio language" was set to "Media default".  So I changed it to  "User interface language" as you suggested. 

This fixed the problem of foreign language playing in Movies and TV Shows.

You have been very helpful so thank you for taking the time to reply.

**Comment by nixgates** [comment]
Thanks @drinfernoo closing issue

**Comment by mrXoo** [comment]
I’ve just noticed lately that Seren seems to be pulling more foreign links. 
mom getting links with Spanish Italian an Russian in the titles and they only have 1 audio stream. 
is there any fix for filtering out links that are labeled as foreign in the little?

**Comment by cg00001** [comment]
If you pick a lot of foreign movies, but prefer them in English, try this:
![disable default](https://user-images.githubusercontent.com/38960370/198982369-dc72502c-0325-4d81-8602-a28a9d8097b0.png)
