### ISSUE TITLE
Next Up delay in updating after show is watched in Kodi

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#135]
The Next up list is not updating as it should after a show is watched. There is a delay. After finishing episodes I have checked on the trakt website and Seren has sent the watched status instantly so that part is working great.

This is making skins such as AuraMod and titan Bingie broken because after watching an episode and returning back to the main skin screen they force a reload of the next up widget.  Because of the delay for Seren to update the Next Up list it is not updating to show the correct next episode. Several updates ago of Seren this worked perfectly.

Is it possible to make the Next up update instantly when it marks an episode watched from you finishing the episode?. 

The strange thing is if you Mark episodes as watched from the trakt manager context menu the list updates instantly all the time when you re-load it so surely this can be fixed to be the same. Hope that explains the issuse better. I have tested this with a brand new install of Kodi without a skin and also with the Titan Bingie latest version.

Thankyou

**Comment by denimnani** [comment]
Same here, i think this start happening when the local database was implemented.

**Comment by denimnani** [comment]
This is weird as hell, today in all the episodes I watched the up next was updated immediately.

**Comment by cporter123** [comment]
I’m having this issue too. Seems to be happening randomly. Sometimes it updates straight away, sometimes not. Reloading the skin doesn’t change anything when this issue occurs

**Comment by lukehansford** [comment]
I am still getting this issue. 

The same issue does not happen with add-ons such as realizer or Gaia so it must be able to be fixed in Seren. 

I am also getting shows disappear from the list entirely during an update.

**Comment by lukehansford** [comment]
I just checked realizer and it actually forces a refresh of the trakt progress list itself and the list updates in about 20 seconds. 

I think it works better because it is the add-on requests the list to be updated after an episode from it has been watched. 

could this be added to Seren?

**Comment by cporter123** [comment]
This might be related to this issue, the trakt website used to display a “now playing” banner when watching something through seren, I just noticed it’s no longer doing this. Trakt history is still being updated as normal on completion of episode though

**Comment by lukehansford** [comment]
I have a theory. 

Could it be due to Seren set to currently to only update from trakt every 10 minutes from changes we make elsewhere on the trakt site for example.

Is this also affecting the next up list when Seren marks the episode as watched?

Could this be solved by removing the 10 minute update time and make it instant.

We need it to update the next up list from trakt each time we load the list so we can watch the next episode. This is especially needed if you use a skin with widgets which most people do.

**Comment by lukehansford** [comment]
I have been using Realizer the last week and found after you finish an episode and close it and get returned back to the trakt progress list there is a visible loading icon you have to wait for to finish which results in the list being updated correctly everytime.

If you test Realizer from its trakt - Progress list you will see. maybe the dev of that add-on would be happy to share it so it can be implemented into Seren.

**Comment by drinfernoo** [comment]
@lukehansford If you seem to know what's wrong and how to fix it, why not open up a pull request with a fix instead of incessantly whining about it?

Obviously it hasn't been "fixed", as there hasn't been an update to Seren since the last time you commented.

**Comment by nixgates** [comment]
Issue is confirmed and fixed for next update.

Please wait while testing is happening to confirm no more major issues are identified as this update included a fair amount of changes to Seren.

**Comment by lukehansford** [comment]
Sounds great. Thankyou to you and all the testers :)

**Comment by denimnani** [comment]
Is working great with last update :)

**Comment by nixgates** [comment]
@denimnani Thanks for the feedback!

:joy:

**Comment by lukehansford** [comment]
Can confirm it's all working great now and fixed. Thankyou
