### ISSUE TITLE
[Request] Different file size limits for movies and tv shows

### ISSUE THREAD

**Issue by cporter123** [nixgates/plugin.video.seren#136]
I can watch 10GB movies without buffering but that is far too big for TV shows, which I can usually only get to about 4GB without buffering. Is it possible to have a setting each for tv and movies to limit file sizes independently of each other?

**Comment by FliesWithWind** [comment]
I wanted to post the same request here. This would be very useful.

**Comment by nixgates** [comment]
This has been added in the new update :+1:
