### ISSUE TITLE
Seren Errors when Loading Kodi (attached log)

### ISSUE THREAD

**Issue by icpryde** [nixgates/plugin.video.seren#14]
Hey Nix, 

I wanted to share some errors I'm getting and not sure why I even installed from a back up that was working and still getting errors all over the place with Seren.

Here is my log file starting on line 586 you will see all the Seren errors I'm getting.

http://paste.kodi.tv/basuvixaju

**Comment by icpryde** [comment]
I installed a fresh copy of Kodi 18 RC1 and installed Seren, everything installed beautifaully and everything seeeeems to be working yet when I look at the log file I still see errors which you can see on line 272 and below.

https://paste.kodi.tv/oyeruwocej

**Comment by nixgates** [comment]
The sort errors in your third log should be solved with 0.1.25.
