### ISSUE TITLE
Newest official build of Kodi crashing when trying to Run Shows as playlist (smartplay)

### ISSUE THREAD

**Issue by nafr1** [nixgates/plugin.video.seren#140]
After the update of kodi couple of days ago, the smartplay feature is not working anymore. It crashes the kodi. Can anyone else verify if it's working for them? I have tried that in Android and Windows and both crashing.

**Comment by nixgates** [comment]
@nafr1 

Can you please confirm your issue has been rectified with the latest update?

**Comment by nixgates** [comment]
I think I've found the issue that the Kodi devs have introduced and I've added a workaround. 

I'll hopefully have an update within the next few days

**Comment by nixgates** [comment]
For those that are interested, it appears Kodi is causing some form of crashing with dialogs. 

I've introduced fallbacks to most functions that call a dialog to ensure that any dialogs open are closed first.

**Comment by drinfernoo** [comment]
@nafr1 Can you verify that this is fixed as of 1.4.6?

**Comment by nixgates** [comment]
This issue should be long fixed. Closing.
