### ISSUE TITLE
Search suggestions crash kodi on xbox one

### ISSUE THREAD

**Issue by snperry85** [nixgates/plugin.video.seren#143]
When doing a search, both movies and tv shows, if you select one of the suggestions that pop up below the on screen keyboard, it will crash out of kodi.

Selecting DONE works perfectly as intended.

Xbox One
Kodi 18.3
Seren 1.0.23

**Comment by drinfernoo** [comment]
This is a known bug with the autocompletion add-on, and isn't something to do with Seren.

**Comment by snperry85** [comment]
My apologies. Thanks.
