### ISSUE TITLE
Possible to hide building list items?

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#145]
Is it possible to hide the full screen building list message.

Either as a standalone option or when we select background scraper task display. 

It would be good when we select the background task scraper display option that the building list message is displayed in the same small top right scraper display if possible.

**Comment by nixgates** [comment]
This was looked into before the major release 1.0.0 and while Seren was able to actually do away with the entire building playlist screen when playing from within the addon menus, the feature broke when playing from a widget.

Seren got rolled back a few version after this was identified and the idea put on the back burner. Not to say it won't be looked at again, I just need to identify the differences that playing from a widget causes compared to playing from a menu item.

**Comment by lukehansford** [comment]
I'm not asking if the screen can be removed or the function.

What I am asking is can the message be added to the background task text if we select scraper display layout to background task so it's not full screen just the same as scraping is not during this setting change. If you select this option the building list is still displayed full screen even though the scraping is small and compact at the top right of Kodi. for autoplay it kind of makes it less streamlined. 

For the future feature -

The option to hide all scraping and budinf list from the user and just show the default Kodi loading icon whilst Seren is building the playlist and scraping or a special Seren hourglass loadin icon after you click an item then play when Seren is ready would be amazing if possible. This would make it like netflix and users who use autoplay and pre termination don't really need or wish to see the scraping dialog information. 

This way you click an item and all the working info is hidden from the user and the item plays when Seren is ready.

**Comment by nixgates** [comment]
Ah ok, yes this can be done, I'll mark this as a feature request :+1:

**Comment by nixgates** [comment]
This has been performed for the general playback of items. As we continue a long this should hopefully be removed for most other forms of playback
