### ISSUE TITLE
Seren failing to play video from widgets

### ISSUE THREAD

**Issue by SoulTV** [nixgates/plugin.video.seren#146]
When using Seren to populate widgets in Titan Bingie, if "show information" is set as the default action, Seren starts the video and then stops the video after a few seconds. Sometimes an error dialog pops up and says "one or more items failed to play". When this happens, the video will play until you click "ok" on the dialog and then video stops. If you change the default action to "play", videos work fine. Never had this issue before the recent releases. Hope it's a simple fix. Btw thx for all your hard work on Seren!

**Comment by nixgates** [comment]
Hey and thanks! 

Could you do me a small favor and just let me know what your smartplay settings are set to?

**Comment by nixgates** [comment]
Actually, it appears I can replicate the issue and I believe I have a fix.

Thanks for reporting the issue, I'll hopefully have an update in the next few days.

**Comment by SoulTV** [comment]
Awesome! Just in case, my smart play settings are enabled, 60 second count down, auto playlist enabled, auto episode resume disabled, pre emptive scraping enabled

**Comment by nixgates** [comment]
Yea, it was caused by the skin attempting to play a non-playable item, I've set Seren to always cancel anyway playback requests when building the initial playlist. 

Appears to fixed the issue.

**Comment by SoulTV** [comment]
cool, ill check it out when the update is ready. Ive got one more feature request for you but I'll post it in another issue. sorry in advance lol

**Comment by drinfernoo** [comment]
Can you verify that this is working in 1.4.6?

**Comment by SoulTV** [comment]
Thx for the update, this is working correctly on 1.4.6
