### ISSUE TITLE
New Episode Tag in Titan Bingie

### ISSUE THREAD

**Issue by SoulTV** [nixgates/plugin.video.seren#147]
This one isn't really a bug, maybe just an improvement suggestion

Seren isn't providing info for "new episodes" tag in Titan Bingie. Here are a couple labeled screen shots of Trakt TV Collection being used in widgets from different addons as well as Seren:

https://imgur.com/a/u0JO528

Venom and OpenMeta are able to provide info so that Titan Bingie can mark shows with "new episode tag". I'm wondering if that's possible with Seren too?

Thx, in advance

**Comment by nixgates** [comment]
Do you know what property tag they are looking for? 

Seren currently sets the following properties on the items:

UnWatchedEpisodes
TotalEpisodes
WatchedEpisodes
TotalSeasons

If there is another that should be covered, I'll be happy to add it in.

**Comment by SoulTV** [comment]
Just asked, I'll post back when he tells me

**Comment by SoulTV** [comment]
Hey so Titan Bingie dev never got back to me but I noticed the tags appear on my watchlist but not my collection. Not sure if that helps narrow it down. Here's a pic    https://imgur.com/a/zzzbQD0

**Comment by SoulTV** [comment]
Someone mentioned the tag might be "NewEpisodes", not sure if that's an actual tag or not.

**Comment by SoulTV** [comment]
The new episode tag already works unless you did something in an update I missed? Sorry about that if nothings changed. I'll close this
