### ISSUE TITLE
Please consider adding support for Alldebrid

### ISSUE THREAD

**Issue by cgcgcgcgcg** [nixgates/plugin.video.seren#149]
I've been using Seren with Real Debrid for a while but Real Debrid started to be problematic.

Please consider adding support for Alldebrid since it's more stable for us that are tired of RD issues.

**Comment by nixgates** [comment]
Hi just realized I haven't replied to this yet. I'm happy to look into it, I'll hopefully have the integration done soon.

**Comment by symiancanine** [comment]
Have been using Seren for a while and love it, probably best addon for kodi, but Real-Debrid is ruining it with slow server speeds, also been using Alldebrid alot more, they are alot more stable

**Comment by Wilson-Magic** [comment]
@symiancanine alldebrid support is ready and will likely be in the next public release.

**Comment by cgcgcgcgcg** [comment]
I've been using Premiumize, and just saw in settings the option to use AllDebrid. :)
Thanks on behalf of my friends that use AllDebrid.
