### ISSUE TITLE
Nextup is showing episodes a day early, ver 0.1.24

### ISSUE THREAD

**Issue by JackDinn** [nixgates/plugin.video.seren#15]
"Nextup" is showing episodes a day early. The aired date of episodes on Seren are a day ahead of the Trakt aired date.  (i have mentioned this on reddit but wanted to put this issue in the correct place).
Screen shots using Seren Ver 0.1.24

https://i.imgur.com/Y9DQDgf.png
https://i.imgur.com/p3egIoy.png

**Comment by RavRob** [comment]
Yes, same thing here.  Not sure if it's a full day early but at least 12 or more hours early for sure.

**Comment by cojoMan** [comment]
> "Nextup" is showing episodes a day early. The aired date of episodes on Seren are a day ahead of the Trakt aired date. (i have mentioned this on reddit but wanted to put this issue in the correct place).
> Screen shots using Seren Ver 0.1.24
> 
> https://i.imgur.com/Y9DQDgf.png
> https://i.imgur.com/p3egIoy.png


Hey, what skin are you using and how did you manage to set it up like that - I'd like to have smth similar set-up  for my fire tv... Top row is in progress tvshows I assume and lower side is a custom list ?...
thanks :)

**Comment by JackDinn** [comment]
Its just the Aura skin, there are several skins you can setup with custom widget bars like Aura, Titan & Aeon nox silvo etc but you would probably find them heavy for fire TV.

Aura:-
https://forum.kodi.tv/showthread.php?tid=328558
Other skins:-
https://forum.kodi.tv/forumdisplay.php?fid=160


Regarding the main subject, i created an alteration to the "next up" code to only show episodes that are actually on the correct date if anyone is interested. Its been working for me for a couple of months.

https://gist.github.com/JackDinn/3b4e5a8d3b8d77c858bcd0605128f56d

My alteration is at line 158  - 168 , you would need to find the relevant part to replace in the latest version of 
.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py

I would advise backing up any file you attempt to try changing first!

**Comment by cojoMan** [comment]
Will try it out, thanks for the info, I might have another question or two if it's too difficult to setup :)

**Comment by JackDinn** [comment]
> Will try it out, thanks for the info, I might have another question or two if it's too difficult to setup :)

sure , any time :)

**Comment by JackDinn** [comment]
Looks like version 0.1.25 has fixed the episodes being displayed a day early.

Great work @nixgates
