### ISSUE TITLE
Episodes after the first aren't scrobbled when using Up Next

### ISSUE THREAD

**Issue by RingGenie** [nixgates/plugin.video.seren#150]
When using Up Next it will mark the first episode as watched, but after that none of episodes are scrobbled at all. For some reason the variable isn't getting reset to false in __init__. (I fixed it for myself by just adding  `self.scrobbled = False` to the start_playback function). Thanks for all the work you've done by the way. Everything else in this update has been perfect.

**Comment by nixgates** [comment]
Love your work, thanks for catching this one.

Added awaiting next public update
