### ISSUE TITLE
ClearLogos and fallback text inconsistent between TV and Movie menues

### ISSUE THREAD

**Issue by baxter300** [nixgates/plugin.video.seren#152]
I currently have two widgets set up on my home page, both to my watchlist. One via the My Movies section, the other My Shows. The watchlist widget and menu are both able to show ClearLogos for movies (although they’re populated in very few instances, I believe this is due to a know bug), and will use the fallback text of the Movie title. However the TV series will show no ClearLogos, and uses the generic fallback text of just “TV”.

Initially I was leaning toward this being a skin issue, but now that’s it’s partially working for one menu type I’m wondering if it’s possible that the title of the TV series isn’t there to be displayed by the skin

**Comment by nixgates** [comment]
@baxter300 could you identify some titles that this issue is occurring on?

**Comment by baxter300** [comment]
It’s all TV titles, I have two tv widgets (Next Up, and Watchlist), both just say TV at the top (where ClearLogos or Location Label would be) rather than the title of the one that is selected

**Comment by SoulTV** [comment]
@nixgates I have the same issue. I mentioned it in issue #153 , although TVDB had issues, the clear logo issue has been present since before that. Here are some labeled comparison pictures between Seren and OpenMeta

https://imgur.com/a/SzJUXFm

In the pictures, the top clear logo isn't populated by the addons. For me, it's coming from Artwork Beef settings in advanced.xml so ignore that one. The landscape tile in Bingie is actually 2 separate images, a landscape fanart with a clear logo layered on top. Both of these images Seren should pull but it isn't. I've noticed this with all TV titles for quite a bit now

**Comment by baxter300** [comment]
@soulTV @nixgates apologies if I explained my issue poorly but I think mines a little different, this is not about individual titles missing artwork but rather the entire section in the addon. 

For example if I have ClearLogos or Folder Labels switched on in the Seren settings, then when I’m in a movies menu or on a widget linked to that menu then highlighting a title will either give the Logo or text displaying g the name of the title at the very top of the screen. However, it seems to be working a little differently for TV shows. With a widget, the top of the screen will just say “TV” or what ever I have named that widget, and in the menus themselves it will just be blank. 

So Seren>Discover Movies>Trending>”Avengers: Endgame” will either show “Avengers: Endgame” or the logo at the top 
Seren>Discover Shows>Trending>”The Boys” there is nothing displayed at the top

At first I thought this was a Trakt issue, or possibly related to the above mentioned TVDB issues, but it’s on all menus under either of the TV sections in Seren. This makes me think either something inconsistent is being passed back to the skin, for movies than tv shows, or my skin (Arctic Zephyr 2) is reacting differently to them

**Comment by SoulTV** [comment]
@baxter300 Pretty sure this is the same issue. I forgot to mention that this behavior only affects TV shows. For a movie (Avengers) it will show clear logo or the the title in plain text. For TV shows, (The Boys), my skin shows neither clear logo or the title in plain text. 

https://imgur.com/a/ZXzwGj4

In the pictures I posted make sure you ignore the top large clear logo and landscape as they are handled by another plugin. Focus on the widgets and compare what's missing on mine to yours and you'll see we have the same issue

**Comment by nixgates** [comment]
Apologies guys, I'm having some trouble identifying what we are referencing here.

Could we maybe get some screenshots of the issues so I can visibly see what we are talking about? (Please make sure you censor any personal information)

**Comment by baxter300** [comment]
Yeah sure, apologies I didn’t just do this in the first place I wasn’t at home. And further apologies that these are photos rather than screen shots. 

But you can see from the below that as well as all ClearLogos not pulling through for me (which as I’ve mentioned is probably a TVDB issue), the text at the top is different for widgets or the menus themselves when ClearLogos are unavailable

https://imgur.com/a/IUTKEVs

**Comment by nixgates** [comment]
@baxter300 @SoulTV thanks guys, I think I can see what you are mentioning here.

I've had a look and I can't find the fault in the current development version so it may be that it's fixed but I don't believe there has been any changes to that side of the addon so I just want to check a few things first.

Could we do a quick and ensure you both have your Fanart API keys added to Seren?

**Comment by baxter300** [comment]
@nixgates I’ve just created a new FanArt API, added it into Seren, cleared metadata, cleared Seren cache, purged Kodi cache packages and thumbnails. Still seeing no ClearLogos for movies but getting the top label, and still getting nothing for TV shows

**Comment by SerpentDrago** [comment]
Nix i believe you fixed this in the dev build , by having fanart.tv lookup clearlogo by TMDB ID instead of imdb id

**Comment by SerpentDrago** [comment]
I'm also confirming both in Movies and Shows Trakt watchlist , i'm getting titles AND clear logos , all view types i choose in my skin auramod , are showing pritty much everything . On dev build , so it very well could be fixed .

**Comment by baxter300** [comment]
@SerpentDrago thanks mate, don’t think the dev build is available to me so I’ll check on the next public

**Comment by SoulTV** [comment]
@nixgates my bad, haven't checked back in a few days. I've checked my Fanart API key and everything looks good. Is there any way I could get access to the dev version?

**Comment by SerpentDrago** [comment]
Theres no "dev" version per say , just some updates sometimes , when things are being worked on , in the future nix may just update the github one and not the repo a bit before release onto repo

**Comment by nixgates** [comment]
Ok cool, we can put a pin in this one until next public release

**Comment by baxter300** [comment]
@nixgates Works for me, having seen @SoulTV ‘s screen shots I’ve actually install Titan Bingie almost all of the ClearArt for movies is now there so half of my issue seems to be resolved and must have been a skin problem. For the TV side of things I’ll hang fire and wait for the update

**Comment by drinfernoo** [comment]
@baxter300 Can you confirm that these are working now?

**Comment by baxter300** [comment]
@drinfernoo strangely, all ClearArt seems to be missing now

**Comment by drinfernoo** [comment]
@baxter300 You'll have to be using Fanart.tv as your preferred artwork provider, and have a Fanart.tv API key entered in settings for them to work now.

**Comment by baxter300** [comment]
@drinfernoo I’ve just tried that, set it to FanArt and double checked that my API key was still there, still no luck

**Comment by SoulTV** [comment]
Thx for the update, this is still a problem with 1.4.6. It seems like some clear art that wasn't working before is. But the fallback text does not work for tv shows that don't have clear art. Here's a pic https://imgur.com/a/JOOT4Dn

**Comment by baxter300** [comment]
@soulTV interesting to see we appear to have adopted each others’ skins... have you tried with Bingie?

**Comment by SoulTV** [comment]
@baxter300 lol, guess so. No I haven't tried with Bingie but I assume the large text at the top is working for you but the fallback text on the actual widget isn't. I'll check out Bingie later and see

**Comment by SerpentDrago** [comment]
Still Absolutely no issues here , full meta clear and using default primary artwork providers and settings , just fanart api key entered . 

I'm using Latest github version of Auramod

**Comment by SoulTV** [comment]
@SerpentDrago Can you try AZ2 and see if your fallback text works for TV shows and take a screen shot of a TV show widget on your home page and inside of Seren that does NOT have clear art? Screen shot would really help. I've fresh installed Seren and AZ2 and still have the issue

**Comment by SoulTV** [comment]
Also doc seemed to agree that it isn't working so I'm wondering if we're all missing something

**Comment by SerpentDrago** [comment]
Yeh seems that my Skin auarmod was helping out . 

I can't do any real testing right now , because either my isp / or metadata providers for me are all jacked to hell in general , on a full clear . not even my skin is not getting timeouts and issues . 

I've tested current build / version of all things yesterday with auramod and it was working . 

For now , i'd suggest switching everything to fanart , enter a key , and  Clear all cache / trakt meta data / do a total cleanup with a wizard , delete textures.db / clear kodi thumbnails / etc 

then let it fully load . it should all work . make sure you enable clearart and clearlogs in serens settings . 


If its not just on my end , then meta data providers could be having issues as well . 

Sit tight we will figure it out , i just can't do much of anything at this time

**Comment by SerpentDrago** [comment]
Please be aware , as of right now , FANART servers are having massive issue s. so not a good time to be doing testing

**Comment by SoulTV** [comment]
All good I already made the switch to fanart and entered my key cleared cache and meta data in Seren, did full cleanup with aftermath and restarted. I don't think art is missing. I think where art doesn't exist/ is unavailable Seren or AZ2 isn't providing a title. Because with movies, the fallback text is there even if there is no art for an item whatsoever. I tested both TMDB/TVDB and fanart.tv after clearing everything and the fallback issue is present using both

**Comment by baxter300** [comment]
Strangely I’m getting 0 ClearArt. In Titan Bingie you get the labels on the widgets when the ClearArt is unavailable, previously I was only seeing this on TV shows now I’m seeing it on everything. I’ve cleared the cache in Seren, and I’ve used EZ Maintenance to clear packages/cache/thumbs, restarted the machine and still no ClearArt which was available when using the previous version of Seren.

**Comment by baxter300** [comment]
Quick update - I bit the bullet and did a fresh install of Kodi, I’m seeing the same issue. Although now as well as the ClearArt not displaying for widgets, it has now gone from the top too. Here’s the screen shot @SoulTv provided when this issue was first created
https://imgur.com/a/SzJUXFm
I’m now not only missing it over the widget, it’s also gone from the very top left hand side where you can see “Harlot” in the above example

**Comment by nixgates** [comment]
A few of us have been looking into this a bit and have noticed massive timeouts with Fanart.tv's service

I think what's really going on here is the fact that the skin can see the URL for the image provided by Seren so it doesn't fallback to text. Kodi attempts to acquire the image set by the skin through a curl request but hits a timeout to Fanart.tv.

Everything down the chain is doing the right thing up until the transaction between Kodi and Fanart.tv where it falls over. Unfortunately this is a point where neither the skin or Seren can do anything about it.

@SoulTV if you wouldn't mind, could I ask you to provide a log or at the very least, check your log for the timeouts for the images to confirm this theory?

**Comment by baxter300** [comment]
Thanks, appreciate you looking into it. Maybe it’s an 18.4 specific issue and that’s why I only saw it this week. I’ve just tried switching labels (fallback text) back on and you’re right, it’s displaying no labels for moves, as if the skin “thinks” the ClearArt is being displayed. Still displaying the labels for my NextUp widget though so I think my original issue is still open, although let’s cross that bridge when we come to it. 

This might be a daft question, but in the advanced artwork settings for Seren, Clear Logos is an option under movies when TMDd is set as the provider, is there a way to pull them from there?

**Comment by nixgates** [comment]
@baxter300  In regards to clear logos if that was the case with the current public it's already fixed for the next update. 

In regards to the text labels, if you searched for the show does it display the artwork correctly? If not then the episode will also not display it. The artwork from the show is populated down through to the episode and then the episode specific artwork is populated onto that.

**Comment by baxter300** [comment]
@Nixgates currently still an issue with 1.4.8. If it’s fixed in a version after that I’ll wait and test it when it is released. 

As for the Next Up issue though, it seems as if the issue only effects that particular menu. All other widgets pointing to TV menus have their ClearArt. I’ve added some screenshots below to try and illustrate what I’m seeing a little better

https://imgur.com/a/iXucAVb

**Comment by nixgates** [comment]
@baxter300 could I request to see if you have the issue currently?

There was a fair whack of meta work completed in 1.6.0.

**Comment by baxter300** [comment]
@nixgates yep the newer part to my issue is fixed as of 1.6.2, ClearArt now showing layered over the landscape images on tv and movies watchlist.

For the original reason for the issue though (ClearArt not showing on the Next Up widgets) I think this may be because the items in that list aren’t actually shows, they’re episodes, and the artwork pulled through is for the episode and the season as opposed to the show (which you’d see on trending etc.). Either way I’m happy for this to be closed now as I think looking to pull the show artwork through to each episode would be more effort than it’s worth, and given Netflix’ decision to switch to a poster based view I imagine Bingie will be following suit soon enough

**Comment by nixgates** [comment]
@baxter300 good to hear. All the best!
