### ISSUE TITLE
Mssing Artwork

### ISSUE THREAD

**Issue by SoulTV** [nixgates/plugin.video.seren#153]
I've noticed that there's missing artwork whenever using a liked trakt list. For example, this list https://trakt.tv/users/enormoz/lists/netflix?sort=added,asc in OpenMeta has artwork for pretty much everything but when using Seren it's missing artwork for quite a few titles. I know that @diddy81 and @drinfernoo used a lot of your artwork code to beef up OpenMeta https://github.com/diddy81/plugin.video.openmeta/commits/master but it seems like OpenMeta is now pulling more artwork than Seren. Maybe it's something small. Just wanted to point it out so that you're aware. Thx for all your hard work man!

**Comment by nixgates** [comment]
This is likely to do with the semi-permanent caching by Seren and the fact that TVDB shit the bed the other day. 

Could you try and clear the stored metadata from the device and see if that works.

Seren > Tools > Trakt Sync > Clear All Metadata

**Comment by SoulTV** [comment]
I responded to this in #152 because I think we're experiencing the same thing. May be good to close this one and continue on that thread?

**Comment by nixgates** [comment]
Cool I'll close this off and have a look at #152
