### ISSUE TITLE
Imdb ratings completely wrong

### ISSUE THREAD

**Issue by Shokaze** [nixgates/plugin.video.seren#154]
Hello,
I just notice that the imdb ratings for all movies and TV shows are completely out of place. I have checked the IMDb website and each time the rating is off for each items in Seren. Since IMDb doesn't provide API key, where does seren pull it's ratings from ? Or is it just an isolated behavior in my end in which case is there any way to reset the ratings ? (I tried clearing cache but no change unfor).
Thank you for the continuous support of the add-on.

**Comment by drinfernoo** [comment]
This is typically handled by whatever skin you're using... do you get correct ratings from other sources?

**Comment by Shokaze** [comment]
Yes I get correct IMDb ratings from Exodus redux. I didn't mention but I do have a omdb API key registered in my skin which gives me proper ratings for imdb/rt/tmdb/metacritic, its just that it takes some time to load. I did my research and installed seren in my phone and same behavior, wrong IMDb ratings which after some research seems to be tmdb ratings (btw for a lot of movies seren display me IMDb & tmdb ratings with the same score)

**Comment by nixgates** [comment]
Seren doesn't pull IMDB ratings at all. Ratings are supplied from the relevant meta provider (TVDB/TMDB).

While Seren applies this information to the items "rating" it does not indicate at all that this is a IMDB rating. 

If your skin is displaying this an IMDB rating, it's doing so without actually knowing where the rating comes from.
