### ISSUE TITLE
Trakt Not Working In Movies/Trending

### ISSUE THREAD

**Issue by Baubascat** [nixgates/plugin.video.seren#155]
When you select Trakt an error message pops up.

**Comment by SerpentDrago** [comment]
You should describe your exact issue in detail , think "how to teach a 5 year old how to make a pb&j sandwich" , 

And provide a Full debug log . 

Otherwise this issue will be closed . thanks

**Comment by nixgates** [comment]
@Baubascat as per Serpents instructions. Could you please provide more details such as the text in the error, a full debug log would be most helpful as well.

**Comment by drinfernoo** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by Baubascat** [comment]
I have this installed on a Shield TV and I have connect to it for files in the past but currently I can not so I can't post a log but I am attaching a photo of the log. When I start Seren in Kodi on my Shield TV (newest 16GB) and go to Movies-Trending and then open the Context Menu to and a movie to my Trakt Collection, when I select Trakt Manager from the Context Menu the notification chimes and says Seren error check log for more information. When I do this same process for Shows-Trending-Context Menu-Trakt Manager, the Seren: Trakt Manager opens and I can select to and it to Trakt.

![IMG_20190808_114751](https://user-images.githubusercontent.com/9766236/62718244-7abdae00-b9d3-11e9-96b6-158f969cf790.jpg)

**Comment by nixgates** [comment]
Could you please confirm the version of the context menu addon and the version of your Seren addon and if available please update to the latest released version.

Looks like you have an older version for the context menu addon.

**Comment by Baubascat** [comment]
You were right. The context menu was old.
