### ISSUE TITLE
Source Selection cause wrong cache or select the wrong item

### ISSUE THREAD

**Issue by sraedler** [nixgates/plugin.video.seren#159]
If I configure the plugin to manual source selection, the cache or any other behavior is strange.
If I have for example 10 sources in the list. If I click on the 5th, it resolves not just the 5th. The resolve method is called with different list positions, which cause wrong cache.

How-To-Reproduce:
1. Configure manual Source Selection
2. Select any source and wait until it is running
3. Stop the stream and select a different source

retry this a few times and you will see, that the inserted cache is sometimes wrong and you will not really get the selected source, you will get any other.

Certainly all the sources in the list are online.

**Comment by drinfernoo** [comment]
Have you tried turning off "Auto try next link on resolve failure (Source Select)"?

**Comment by sraedler** [comment]
yes I tried it, but even there, I can see multiple threads resolving the following links.

I think it might lead to concurrency problems through the resolving threads
I debugged with Pycharm and I can see different self.Postition in source selection and additionally multiple threads running concurrent against the resolving.

**Comment by drinfernoo** [comment]
This should be fixed as of 1.4.6. Would you be able to check into it for me?

**Comment by sraedler** [comment]
I will check it next week, because I don‘t have access to a Computer.

**Comment by nixgates** [comment]
The position in the resolver is actually different to the position in the source select list so if you are comparing them together you will notice a difference. Seren will not hand the whole list to the resolver module, rather it hands over a chunk of the list from the selection down. 

Are you seeing the wrong source provided to the resolver module? Is that the issue?

**Comment by sraedler** [comment]
Sorry for the real late reply!
just for your information, it was not about the different list position. It was about running a different stream than selected.

I checked it once and now it works like expected. 

thanks a lot!
