### ISSUE TITLE
Episode Custm View not working

### ISSUE THREAD

**Issue by loggio** [nixgates/plugin.video.seren#16]
Using Leia 

As title suggests... 

Something weird going on... I'm using the Arctic Zephyr skin, i can set custom view types for all views... But no matter what i set for Episode View in Seren settings, Seren will always default to a standard list view for episodes.

and when in the episode view, pressing backspace to go back to "season" , the season view changes to what the ''episode" view should be in the custom settings.

weird behaviour

**Comment by nixgates** [comment]
Can you please let me know what version of Kodi you are running?

**Comment by loggio** [comment]
Hi

I did, it says "using leia".

I use leia on 4 rpi's and 1 Nvidia shield.
All experiencing the same issue.

**Comment by nixgates** [comment]
This seems to be a bug in Leia and I can replicate this, can you let me know what version of Leia you are running? 

Have you attempted to update to the latest RC4.

It's almost as if Kodi is refusing or failing to accept the requested view type.

**Comment by loggio** [comment]
I use the latests nighties, so always bleeding edge for me up until stable release. Then I normally wait 6 months before starting on nighties again.

**Comment by nixgates** [comment]
Using nightlies isn't recommended for everyday use but either way I can replicate the issue on RC1.

As I did mention, this does seem to be a Kodi issue at this point but I'll dig down into it a bit further and see if I can find the cause and/or a workaround.

**Comment by nixgates** [comment]
I've had a look and found that the SetViewType call is occurring to fast and it's being applied to the previous menu. 
This is why when you go back to the previous menu the view has been applied. I've added a small sleep to the closeDirectory function for 0.1.27 which should help in most cases but isn't a permanent fix as it may not be enough on some slower devices.

**Comment by nixgates** [comment]
Now that 0.1.27 has been released you have the option to disable the set view and the set view has been fixed. 

If you still have issues please let me know!
