### ISSUE TITLE
Default Next Up action 

### ISSUE THREAD

**Issue by SoulTV** [nixgates/plugin.video.seren#160]
Is it possible to add the default select action for Next Up widget to be the "Browse Show" context menu item? It would really help for older people who don't really understand using the context menu. My parents don't really get why it just starts playing an episode especially if they fell asleep and its like 2 episodes ahead. If they could navigate from Next Up widget to the right episode using only "select" and "back" buttons and not long pressing or using the menu button, it'd be a lot easier for them. 

Hope that makes sense. Anyway, thx for the awesome addon!

**Comment by drinfernoo** [comment]
It's confusing that when you click on an episode... it plays that episode? 🤣

**Comment by nixgates** [comment]
I can't control the info screen as that's created by the skin.

I'm kind of on the fence about this, while I see what you are saying I feel like educating the user is the correct method here rather than them being used to old practices. Seren already includes the context menu button to "Browse Season" and I feel that is sufficient to match the needs when considering how fast it is to open a context menu.

**Comment by SoulTV** [comment]
I hear you and I agree the context menu is sufficient but OLD people are making me losing my marbles lol.

Here's an idea. Would it be easier, since the info window is skin dependent, to make the default select action the context menu itself? That would basically accomplish the same thing. If it's an easy edit I can make to Seren on my end, I'd be more than happy to add it myself on each update. Just not sure where to start

**Comment by SerpentDrago** [comment]
![image](https://user-images.githubusercontent.com/21133858/65374618-e4c7a500-dc59-11e9-836b-37aa4dd9d012.png)

![image](https://user-images.githubusercontent.com/21133858/65374636-23f5f600-dc5a-11e9-9411-a2ee544a34b0.png)

AuraMod skin , now has this option  in its "netflix information screen" only valid for seren items . it also has a trakt manager button .  I have auramod set to  default to information on click on any home screen item . Netflix info enabled . and widgets pointed to seren . 

So you are free to check out the latest auramod on github  and comments to see how you could add this to whatever skin your using

**Comment by SerpentDrago** [comment]
![image](https://user-images.githubusercontent.com/21133858/65374694-b0081d80-dc5a-11e9-8386-d0d8ca4b5f67.png)

and from a show information screen (not specific episode)  Quick play was added , which will jump you right into the last episode unwatched (uses serens quick play , auto episode resume function )

**Comment by SoulTV** [comment]
That's exactly what I was asking for lol. I asked jurialmunkey to take a look for AZ2. Hopefully he can implement it. If not, might be time to switch over auramod. I really like AZ2 tho so I'd rather not

**Comment by SerpentDrago** [comment]
@SoulTV you will NEVER get Jurialmonkey to implement that , That feature is a direct feature supporting Seren Only , and only appears for Seren items in auramod . Its a Addon Specific added feature for Auramod

**Comment by SoulTV** [comment]
Ah ok, ill five auramod a shot today and I'll close this now
