### ISSUE TITLE
Next up not up to date when loaded

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#164]
I have been using the TVZion app the last week or so.

When I watch a episode the app sends the watched status to Trakt. I have checked this on the trakt website. 

Seren is not showing the correct up to date next up list which is on the Trakt website. 

This is even after a day has passed. Other apps do update it just seems to be Seren. 

The only fix is to clear cache from the tools menu and reload the next up section of the add-on. 

Also is there any idea when the fix for only the first episode being marked as watched an not the rest using the up next addon?

**Comment by drinfernoo** [comment]
What inconsistencies are you seeing? Are you missing entries, or are they in the wrong order?

If they're in the wrong order, there is a setting in Seren:

![](https://i.imgur.com/lvyBgZv.jpg)

**Comment by lukehansford** [comment]
Items you watch outside of Seren but are marked as watched on the trakt website are still stuck in the next up list. Episodes are ones you watched days ago. 

I am talking about if you use another app or manually mark items as watched on the trakt website. 

Even after a day the next up list in Seren is still in this outdated state. 

The only thing that seems to force an update is to clear cache under tools.
