### ISSUE TITLE
German Language string.po Problems

### ISSUE THREAD

**Issue by lukkie112** [nixgates/plugin.video.seren#165]
Hi Nixgate!
I have translated the booth strings.po into German Language

But If I copie the folders (German & recources.language.de_de) to ....kodi/addons/plugin.video.seren/recources/language, onyl some Menue Points are in German. The most menue points are still in englisch and when I open a menue point i get some errors.

The Errors are, because in german we use special characters like Ö, Ü, Ä and so on, and seren don't work with this

Please can you fix this

**Comment by drinfernoo** [comment]
The 1.4.6 update added translation support to most of the add-on. Go ahead and give it another try.

Currently, accented characters (Ö, Ü, Ä) will be automatically deaccented, but that may be changed in the future.

I'm gonna close your two issues, but feel free to open another if you have issues with translation, or a PR with changes when you're done 👍
