### ISSUE TITLE
Seren Error

### ISSUE THREAD

**Issue by Gchinchino** [nixgates/plugin.video.seren#172]
Hi, i’m faced with this error on seren. Hope u can help me out :)
![96F1BDB1-F153-41DF-97A0-BABC24764494](https://user-images.githubusercontent.com/28182762/64707766-1025f380-d4e6-11e9-87f9-3ddeaf0027e5.jpeg)

**Comment by nixgates** [comment]
@Gchinchino may I ask what version of Kodi you are running? 

That error shows that the character encoder package for Kodi failed so it's likely it got some text it didn't like so could I also ask what menu you were trying to open?

**Comment by SerpentDrago** [comment]
If you could provide a FULL debug log that would give all the answers we need ! to help you

**Comment by Gchinchino** [comment]
@nixgates i was on 18.2 leia and already had this issue. I updated it to 18.4 leia the issue still persists. The error occurs on launch of kodi. The notifications on the bottom right said that seren has an error and go to the log to see for more info.

**Comment by Gchinchino** [comment]
You can find my logs here at https://pastebin.com/436xCfMc

Thanks so much guys! :)

**Comment by Gchinchino** [comment]
@nixgates i reinstalled libre elec and everything is working now :)

**Comment by nixgates** [comment]
Sorry for the delay! Thanks for letting me know @Gchinchino !
