### ISSUE TITLE
Watched History

### ISSUE THREAD

**Issue by trowieuk** [nixgates/plugin.video.seren#175]
Would really like ths feature. I fall asleep watching tv so when things are marked as watched, I might not have actually watched it. Currently using exodus redux watched history as a widget but yeah I 'd prefer to use seren.

**Comment by SerpentDrago** [comment]
consider it requested , also fyi the next version of seren released should have "still watching " feature . 

I to fall asleep watching stuff sometimes :0 i know how it is

**Comment by trowieuk** [comment]
Haven't noticed this popup feature yet... any news on this?
