### ISSUE TITLE
1080p tag in torrents season packs triggers eighth episode

### ISSUE THREAD

**Issue by powei94** [nixgates/plugin.video.seren#176]
So I just noticed that when seren searches for the eighth episode in 1080p torrents season packs it plays the first episode instead, I'm pretty sure this is because it's detecting the 1080p tag as season 01 episode 08 for some reason because this doesn't happen with 720p or other resolution season packs.

**Comment by drinfernoo** [comment]
@powei94 Can you give any examples of what shows this is happening with? I've never had this happen.

**Comment by powei94** [comment]
@drinfernoo It just happened with Undone, I think it happened with the boys too but I just confirmed it with Undone

**Comment by SerpentDrago** [comment]
I'll check when I get home but this may only happen with rd. do you use rd or pm?

**Comment by powei94** [comment]
@SerpentDrago I didn't think about that but yeah I use rd.

**Comment by drinfernoo** [comment]
I've confirmed this issue is only happening with RD, but it is definitely a valid one.

**Comment by SerpentDrago** [comment]
@powei94 Thanks to your issue post and detailed description . the issue has been identified and should be fixed in next public release , may be a bit though . but its being fixed , thanks for the report !

**Comment by powei94** [comment]
No problem, glad I could help, thank you for looking into this!

**Comment by nixgates** [comment]
Issue should be fixed as of 1.6.0

Please let me know if this is not the case.
