### ISSUE TITLE
Syncing Trakt lists (for example Next Up episodes) to libray

### ISSUE THREAD

**Issue by sevospl** [nixgates/plugin.video.seren#177]
It would be really cool if I were able to sync everything to libray. That way I could use a smartplaylist and push everything to Android TV Leanback recommendations.

**Comment by drinfernoo** [comment]
This almost certainly won't ever happen. Nix has been very clear that he isn't interested in adding any sort of library integration, and has instead opted for pseudo-library "caching" in the form of his Trakt database.
