### ISSUE TITLE
Search for content using translated title from IMDB

### ISSUE THREAD

**Issue by guglicap** [nixgates/plugin.video.seren#178]
Hello, I was thinking that in order to make this addon more international it would be useful to something akin to Elementum where it searches for content using the translated title from IMDB.
I tried to implement this myself and open a pull request but unfortunately my python knowledge isn't adequate for this task.

**Comment by nixgates** [comment]
I would think this would fall under the issue #87 

While I'm slowly making progress with integrating other languages, I don't have the necessary skill set to do the translations and need a lot of help from the community. Keep an eye on this issue as we move forward with it though.

If you know another language, you can always lend us a hand by translating the language files in Seren!
