### ISSUE TITLE
Search quite slow 

### ISSUE THREAD

**Issue by sraedler** [nixgates/plugin.video.seren#179]
Seren is quite slow at searching a movie or tvshow.

Is there any plan to improve it?

I haben‘t change anything in the settings.

**Comment by nixgates** [comment]
The search actually uses the same methods as the menus. We could actually shrink down the results to remove some of the clutter of shit that gets pulled sometimes. 

That should in turn speed up the effectiveness. 

I'll look into it :)

**Comment by nixgates** [comment]
@sraedler is this still an issue?

**Comment by sraedler** [comment]
I'm not really using seren anymore...

But it looks like the issue is resolved.

thanks
