### ISSUE TITLE
Kodi 19 (alpha) is on python 3 now..

### ISSUE THREAD

**Issue by pogarek** [nixgates/plugin.video.seren#181]
Hi
Alpha build of Kodi are on Python 3 now (https://github.com/xbmc/xbmc/pull/16116 ).. 
I have installed a build on tvOS and Seren doesn't work at all. 

Just reporting it ; I will use older build in the meantime, but the time to switch is now..
Regards.

**Comment by nixgates** [comment]
I'm in the process of getting some of the smaller issues ironed out.

Seren should work with Kodi 19 for the better part (minus the easy fixes that are causing show stoppers) but won't take to much to get done.

**Comment by pogarek** [comment]
Thanks. I've just installed Seren in my test build of Kodi 19. I cannot add scrappers package, authorize RD etc. :-) Happy to test when new release will be out.

**Comment by sheen73** [comment]
Nixgates, you rock! Ty for great add on. I tried Kodi 19 for the UHD player support and couldn’t get Seren to work due to python3 issues. Happy to help test as well when ever you find time to work on this. Thanks again.

**Comment by nixgates** [comment]
Had a look over it today, looks like we are about 90% of the way there. I was able to load all my menus and view movies/episodes.

I'll probably release the ability for people to test it out on 19 on the next update

**Comment by sheen73** [comment]
You are the best, ty. Happy to donate but not sure how?

**Comment by pogarek** [comment]
Thank you. I'm glad to read this. 👍

**Comment by marly402** [comment]
Looking forward to testing the Seren addon.  Do have a date for release yet thanks so much!

**Comment by brentonv** [comment]
Thankyou. What will happen with users still on 18.6 python 2x?

**Comment by drinfernoo** [comment]
Seren 2.0 should be compatible with both Python 2 and 3, for the time being, when it's released. No idea when that'll be.

**Comment by brentonv** [comment]
Thanks guys

**Comment by nixgates** [comment]
As of a couple of hours ago 19 support was added.

Closing it off  :)
