### ISSUE TITLE
provider manager on Kodi 17.6

### ISSUE THREAD

**Issue by ShlomiD83** [nixgates/plugin.video.seren#183]
In Kodi 17.6 the provider manager section is kinda messed up (see picture).
https://imgur.com/a/rJ81yBH

In Kodi 18.5 it looks as it should.

so no backwards compatibility anymore?

**Comment by SerpentDrago** [comment]
what skin are you using?

**Comment by ShlomiD83** [comment]
Xonfluence.

**Comment by ShlomiD83** [comment]
this also happens with the default Kodi skin & with Confluence.

**Comment by nixgates** [comment]
To be honest, I'm not really looking to support Kodi 17 at the moment, the bugs with Seren on it are likely endless not to mention the issue around setting resets and we spent a lot of time encouraging the move to 18.

I believe 18.5 is now at a very stable level and should be the recommended install, so in short. Probably no backwards compatibility lol. 

You might have more luck with a different theme for Seren though so maybe try spinning up @SerpentDrago or @drinfernoo themes and give it a whirl.
