### ISSUE TITLE
On Maxytec device kodi crashes when using seren.

### ISSUE THREAD

**Issue by winnekeu** [nixgates/plugin.video.seren#185]
It is basicly just like it is in the subject. everytime i user seren in kodi on maxytec infinity device kodi crashes. This happends everytime.
I already fully resetted the device (factory defaults) and i do not have any issues with other add-on like gaia, IT and a few other ones.

The older seren did work before the animation changed.

**Comment by drinfernoo** [comment]
We'll need to know much more information... What version of Kodi? It's there any error? In addition to this, a log file would be an immense help.

**Comment by winnekeu** [comment]
> We'll need to know much more information... What version of Kodi? It's there any error? In addition to this, a log file would be an immense help.

It is running the latest version of Kodi(18.4) and it the android box is running 7.1.
Since kodi really crashes i do not think there is a logfile.

But i will see if i can find a logfile anywhere.

**Comment by drinfernoo** [comment]
Kodi creates a log file on every startup, and updates it all the way until Kodi closes, one way or another.

Instructions for retrieving it are outlined [on the Kodi wiki](https://kodi.wiki/view/Log_file/Easy).

**Comment by nixgates** [comment]
@winnekeu could you please re-open this issue if and when you manage to gather a log of the issue. 

I don't own this device and won't be able to test it without further information
