### ISSUE TITLE
It won’t let me pair too Trakt

### ISSUE THREAD

**Issue by xyzfre** [nixgates/plugin.video.seren#186]
Started yesterday for some reason when I go pair to Trakt and put the code in it just stays frozen right there with the code on the screen,, I love this addon lots of  respect for all the work,, Just wish I can sort this out I tried deleting and reinstalling and the same issue occurs

**Comment by nixgates** [comment]
@xyzfre could you confirm if you are still having this issue?

**Comment by xyzfre** [comment]
No it’s all good now 👍🏼thank you for your response and all your hard work Seren is the BEST

**Comment by xyzfre** [comment]
Everything is running smooth specially after this new update GREAT WORK

**Comment by xyzfre** [comment]
Today I notice it takes very long to open up Trakt Collections or watchlist but everything was fine yesterday I think Trakt is having issues
