### ISSUE TITLE
Missing Sources

### ISSUE THREAD

**Issue by Baubascat** [nixgates/plugin.video.seren#187]
Some of the TV show I have been watching with Seren have stopped working. Some no longer find sources at all, even for past episodes I have already seen. Other shows have sources but they don't work. It's not all my shows but the ones that this is happening with work in Gaia but I really don't like Gaia nearly as much as Seren. Is this TVDB related?

**Comment by nixgates** [comment]
Seren doesn't handle the gathering of sources for any items. 

You will need to contact the developer for your provider package and investigate the issue with them. 

Apologies.
