### ISSUE TITLE
RD - Cache Assist (No Sources) Failure - runaway caching

### ISSUE THREAD

**Issue by mgonzales71** [nixgates/plugin.video.seren#19]
Seems as if for instance I am trying to watch Episode 2 of Season 3 of The Flash 
I will get a no playable sources found and then the addon appears to be looking for shows again after saying it is attempting to build a cache.... in fact it seems that if that episode fails then it will jump right to the next and if that fails to the next and so on (until I back out of add on)

I've heard that the folks over at RD are kinda asshats to customers and that slamming the API for torrents could get you banned for (a day?) or something unhappy.

I know for a fact that the one time I posted something to their forum that they didn't like they deleted the post and when I asked why they would do something like that my access to the forums was gone and it took me 2 months to gain access again.

Like I said - asshats (or expletive of your choice)

below you can see the cascading of episode torrent cache attempts and ones in progess.

Also what appears to be a duplicate in progress too (?)

maybe when a playable episode is not available, don't jump to attempting a new one automatically or ask or set a kodi bg task (or alarm etc) to update progress and then send a notification episode it ready or IDK - I defer to you on what you want to do.

I am just pleased you are writing this awesome add on and was more worried about the implications of RD and their irrational temper.

Thanks!!
M

![kodi_2018-12-23_04-26-51](https://user-images.githubusercontent.com/6510026/50383598-2e07ab80-066c-11e9-9b3e-a20cfe8452fe.png)
![2018-12-23_04-25-56](https://user-images.githubusercontent.com/6510026/50383599-306a0580-066c-11e9-8aa9-c875d10c3552.png)

**Comment by nixgates** [comment]
Come 0.1.25 I have added a fallback to clear the playlist if no sources are found.
This will stop Kodi from automatically attempting to play the next in the list.

**Comment by mgonzales71** [comment]
you're awesome - thanks again
