### ISSUE TITLE
Seren filesize sort option should be ascending 

### ISSUE THREAD

**Issue by eengert** [nixgates/plugin.video.seren#190]
The filesize sort option should be ascending order. Or another option should be added to allow a choice of sort order for filesize.

**Comment by abbaskip** [comment]
I believe it's descending to ensure higher res, more audio channels etc - i.e. The best quality.

If you sort by x265 first, then

**Comment by drinfernoo** [comment]
As @abbaskip mentioned, given that filesize is typically a pretty reliable indicator of overall quality, on what situation would it be advantageous to sort smaller files higher?

**Comment by nikolajbak** [comment]
> As @abbaskip mentioned, given that filesize is typically a pretty reliable indicator of overall quality, on what situation would it be advantageous to sort smaller files higher?

I would love the possibility to sort by audio quality (number of channels), since this seems to be more coherent with actual quality of the general copy and since I always look for Atmos or DTS:X anyway.
Any chance that audio sorting can be implemented?

**Comment by drinfernoo** [comment]
@nikolajbak At this point, it would be very difficult, since all of the metadata that Seren uses to sort is all parsed from the filename of the stream in question.

**Comment by nixgates** [comment]
@nikolajbak While we can sort by any audio information we can gleam from the filename, it's not likely you are going to have a good time doing it. Not to mention that kind of sort would be much more deterministic to a users preferences. 

I do have a ticket in my personal git to look at implementing a more robust sort. Once we settle a bit after this last large update, we can look at implementing a battle plan for that.

**Comment by nixgates** [comment]
I'm going to close this ticket off, sorting by ascending file size will actually cause more issues.

I will open a new ticket to cover @nikolajbak suggestion of more sort options
