### ISSUE TITLE
Tv show posters not loading 

### ISSUE THREAD

**Issue by symiancanine** [nixgates/plugin.video.seren#191]
After theTVdb updated their new API, no tv posters are showing

**Comment by gattomatto69** [comment]
Same issue for me. I know there have been some issue with TVDB but all my other addons are now working properly (OpenMeta, The Crew). In my case TV shows posters and fanart are missing, all I see is the white folder icon. I've tried clearing Trakt metadata and Seren cache but nothing changed.

**Comment by fiddelsticks** [comment]
There us a new update.  All working fine.

**Comment by nixgates** [comment]
Closing issue! :)
