### ISSUE TITLE
Addon Neglect??

### ISSUE THREAD

**Issue by JayDee696969** [nixgates/plugin.video.seren#192]
So have you given up on the project? Seems strange that basic stuff like section icons are non existent, and api keys are not up to date. No posters/art for TV Shows, etc. Too bad. Its a nice addon, but it seems like its being neglected. The guys over at a4k scrapers are still updating the scrapers,but the actual addon has no support?

**Comment by drinfernoo** [comment]
The API keys included in the add-on are still current, and artwork issues should be fixable by rebuilding your Trakt database. Icons are common issue that's requested, but @nixgates has been focusing on add-on development.

There should an update soon, don't worry.
