### ISSUE TITLE
Please consider adding a sort by feature for Trakt list

### ISSUE THREAD

**Issue by raujaku** [nixgates/plugin.video.seren#193]
Trakt list are only currently being sorted by the list creator. For those of us who use others' Trakt list, It would be a most welcome addition to add sort by date, release, year, etc when viewing others' Trakt list.

**Comment by nixgates** [comment]
Let me think of a plan of attack for this, I'll add it to the current list of Feature Requests though. I like the idea, just need to think of a nice way to implement it.
