### ISSUE TITLE
Myflix view. How to rating to episodename.

### ISSUE THREAD

**Issue by snijdelwijk** [nixgates/plugin.video.seren#194]
I use myflix viewtype.
I see rating above. But mostly its empty. I dont want to see rating anyway is there a possibility that i can replace it with the episode number+name?

Episode name and number is more appreciated

**Comment by drinfernoo** [comment]
This likely has to do with your skin. Seren provides all the information, and it's up to the skin to display it.

**Comment by snijdelwijk** [comment]
Well in other add-ons it does display it at the same place. skin = aon nox silvo

**Comment by snijdelwijk** [comment]
![15760094075071189330002650221007](https://user-images.githubusercontent.com/26495002/70565943-695bfc80-1b93-11ea-9457-21888b92a239.jpg)
Seren

![1576009461320860701687291594159](https://user-images.githubusercontent.com/26495002/70565978-7973dc00-1b93-11ea-896a-3c9f5b15bf22.jpg)
Other addon

**Comment by snijdelwijk** [comment]
@drinfernoo i see you labeled it as a bug now. Does this means this is not how it has to been shown?

**Comment by snijdelwijk** [comment]
I dont know what happened today. It gave an error. Had I all reset. Now the name of the episode is there. 
I only see the name of the series now. No more logo. But very happy. The most important thing is there.

**Comment by nixgates** [comment]
@snijdelwijk is this issue still present in 1.6.0?

**Comment by snijdelwijk** [comment]
@nixgates 
i can see the name of the episode now.
I only dont see the logo of the show.
Before the name fix I saw a logo of the show (shown in previous picture)

**Comment by snijdelwijk** [comment]
![70565943-695bfc80-1b93-11ea-9457-21888b92a239](https://user-images.githubusercontent.com/26495002/71038423-17325280-2122-11ea-833c-7da9a6f1daca.jpg)
This Is what i saw before update.

![15766205038382251825576307701504](https://user-images.githubusercontent.com/26495002/71038454-26190500-2122-11ea-8573-bc430f1ebe10.jpg)
This is what I see now. (Spanish episode name only with this show and did not choose spanish language. I use english)

**Comment by snijdelwijk** [comment]
In 1.6.2 still only the name is fixee. Logo still not showing.

**Comment by nixgates** [comment]
@snijdelwijk it's possible that the meta information for the item was acquired durin a period where Fanart was having an issue. 

Could you make sure you have your fanart account setup and then open the trakt manager menu on the Batwoman show, then hit refresh Item meta. 

This should hopefully poll for the information again and retrieve the clear logo.

**Comment by nixgates** [comment]
Also, please check your advanced artwork settings and make sure you have the artwork you want enabled.

**Comment by snijdelwijk** [comment]
Will try again tonight.
Will show settings if dont work.

**Comment by snijdelwijk** [comment]
![15790374668481734148641368667734](https://user-images.githubusercontent.com/26495002/72384368-9e70e700-371d-11ea-9648-0066d3c615a7.jpg)
![1579037497505208974363070853930](https://user-images.githubusercontent.com/26495002/72384391-a92b7c00-371d-11ea-9bd9-139f978b9911.jpg)

**Comment by snijdelwijk** [comment]
Tried your steps. Still no logo.
What can i try to get that awesome look back?

**Comment by drinfernoo** [comment]
@snijdelwijk Have you updated to 1.6.6?

**Comment by snijdelwijk** [comment]
Yes i am on 1.6.6

**Comment by snijdelwijk** [comment]
When i go to populair series i do see the logo now.
Its only not updated in next up.

**Comment by nixgates** [comment]
Looks like the episode item's meta is not being populated with the fanart alternatives. I'll look into it and get back to you

**Comment by snijdelwijk** [comment]
@nixgates 
if you want me to try something. Let me know. I will be home in 5h.
Its strange that it does work in the whole discover tv show section. And not in the whole my tv show section.

**Comment by snijdelwijk** [comment]
I never saw this fixed in updates. Is there a way to solve it?

**Comment by drinfernoo** [comment]
@snijdelwijk I don't understand the issue? Is it still present in the current version?

**Comment by snijdelwijk** [comment]
> ![70565943-695bfc80-1b93-11ea-9457-21888b92a239](https://user-images.githubusercontent.com/26495002/71038423-17325280-2122-11ea-833c-7da9a6f1daca.jpg)
> This Is what i saw before update.
> 
> ![15766205038382251825576307701504](https://user-images.githubusercontent.com/26495002/71038454-26190500-2122-11ea-8573-bc430f1ebe10.jpg)
> This is what I see now. (Spanish episode name only with this show and did not choose spanish language. I use english)

Still like this. I dont see fanart logo when i hit my trakt progress.

**Comment by drinfernoo** [comment]
That is a skin issue. Seren correctly fills the proper InfoLabels to show this information.

Unless this is *only* happening with certain titles, this isn't a Seren issue.

**Comment by snijdelwijk** [comment]
Thats strange. Because it does work in all tv shows section. Only the trakt progress its not showing.
Have any tip to try to fix it?

**Comment by drinfernoo** [comment]
You can't see clearlogo for *any* shows inside the "Next Up" menu?
