### ISSUE TITLE
trakt list not syncing

### ISSUE THREAD

**Issue by Chup123** [nixgates/plugin.video.seren#197]
When i try to rebuild my trakt database it gives an error with the list. This is the log file:
[log_kodi_seren_broke.log](https://github.com/nixgates/plugin.video.seren/files/3965168/log_kodi_seren_broke.log)

**Comment by nixgates** [comment]
Please hold out for 1.6.1, should be available in a couple of hours.

**Comment by Chup123** [comment]
alright, when i try to sync the trakt db, it work till 25% off syncing trakt list, then it just stops, no error or something.

Here's the debug: https://pastebin.com/tALQcntc

**Comment by Chup123** [comment]
Alright, i've narrowed down the problem. Everything loads except my liked lists. And that are the lists i used the most. Can you do something with that?

**Comment by Chup123** [comment]
Sorry, it was a trakt list that didn't sync. That was the issue. Now everything works great again
