### ISSUE TITLE
Weird conflict between smoothstreams addon and Seren after 1.6.2 upgrade

### ISSUE THREAD

**Issue by sultanofswag** [nixgates/plugin.video.seren#199]
If both addons are enabled, both hang while starting either of them. If I disable one addon, the other starts working. This issue started only after Seren 1.6.2 upgrade. Smoothstreams addon has not changed in months. Looks like some resource contention between the two when kodi starts up.

Tried with fresh install of both (did not fresh install Kodi). Happening on windows 10 laptop (Kodi 18.5) and also on Apple TV 4K (Kodi 17.6).

Logs at https://paste.ubuntu.com/p/wgjn3tW7Z7/

Logs show Windows 10 scenario of both Smoothstreams addon and Seren enabled and i try to open Seren addon. Seren just shows the spinning wheel and eventually i press escape and exit kodi.

I have downgraded Seren to 1.4.8 and things are working fine with both addons enabled.

Please Help. Both addons are critical for me.

**Comment by sindrig** [comment]
Hey @sultanofswag have you found a workaround? I just started running into this on my new Nvidia shield (Kodi 18.5).

**Comment by sultanofswag** [comment]
> Hey @sultanofswag have you found a workaround? I just started running into this on my new Nvidia shield (Kodi 18.5).

Hi @sindrig, Only workaround I have is to downgrade Seren to 1.4.8 for now. Nixgates has released a couple of new versions after 1.6.2 but I did not get the chance to try them out to see if they resolve the issue with SmoothStreams.

**Comment by nixgates** [comment]
I'm looking into it now, hopefully I'll have some sort of solution soon. Thanks for highlighting it :)

**Comment by SerpentDrago** [comment]
@sultanofswag  , Can you wipe SS and NOT sign in . and never open it .. do you still have issues ? 

We are having a hard time replicating , but we don't have a SS account . I have both installed right now with no issues running seren

**Comment by sultanofswag** [comment]
If i simply disabled the SS addon, Seren (1.6.2) would work just fine. I believe uninstall of SS also worked fine but will need to try it again.

Have not tried anything with 1.6.3 or 1.6.4.

Let me know if you need me to try your scenario.

**Comment by SerpentDrago** [comment]
I can install SS addon , and everything is fine , if i ever touch / enable the "enable proxy" setting of ss is when shit goes to hell .

we are on the case . but it appears to be caused by having ss addon installed and haveing EVER TOUCHED the proxy setting in it . If you uninstall SS and wipe it / restart kodi and just install ss NEVER touching the proxy setting .. its should in theory work fine . 

Again we are still investigating

**Comment by SerpentDrago** [comment]
Upon farther testing it does appear just having ss installed screws up the system , after restarting kodi , and fresh installing ss dev addon . Doing NOTHING to SS addon . at all . never running it manually or going into its settings. 

Nothing will launch ,  Seren / Youtube / venom / nixtoons2 .. nothing loads . 

Something about SS dev addon is really fucking with kodi BAD

**Comment by nixgates** [comment]
Serpent is right here that it seems that SS is actually locking up the Python interpreter Kodi. Not sure at the exact issue, but it does involve a very old and weird Python 2 issue so it could honestly be anything. 

You can get it working again by going to the following file inside the SmoothStreams addon:

> Kodi\addons\script.smoothstreams-dev\lib\smoothstreams\compat.py

Replace the following code:
```
try:
    datetime.datetime.strptime('0','%H')
except TypeError:
    # Fix for datetime issues with XBMC/Kodi
    class new_datetime(datetime.datetime):
        @classmethod
        def strptime(cls,dstring,dformat):
            return datetime.datetime(*(time.strptime(dstring, dformat)[0:6]))

    datetime.datetime = new_datetime
```
With this code:
`import _strptime`

things should go back to normal

**Comment by SerpentDrago** [comment]
@sultanofswag @sindrig  

Wish you guys luck ,  see nix's fix above

**Comment by sultanofswag** [comment]
Any idea as to why Seren 1.6.2 triggered this bug with SS? Rolling back Seren to 1.4.8 fixes the issue. 

It is the same behavior with the dev and non-dev SS addon.

Thank you

**Comment by SerpentDrago** [comment]
seren didnt' trigger anything , SS for me and nix on testing fucked up the entire system lol . 

the addons messed up . causes the entire system to hang to hell .

**Comment by smoothstreams** [comment]
SS has not updated its addon for some time.
So lets not blame SS to start.
That said, we appreciate any improvements to the code base.

Our dev. and Staff has been alerted to this thread, and have made a "fix" in our dev. branch (v82).
So install that along side this Seren, and lets see.

**Comment by drinfernoo** [comment]
@smoothstreams Where is that dev branch available?

**Comment by SerpentDrago** [comment]
@smoothstreams Could you please make a announcement in addons4kodi , I'll be welcome to remove my "fix" repo if you guys have implemented a "fix" officially , after all that was the point is to get your attention !

**Comment by nixgates** [comment]
@smoothstreams my apologies if it came across negatively as that was not my intention at all. 

While I accept it was conflict between our addons, I was unable to identify the cause of the deadlock on Seren's side but did manage to find it in SS. This is not to say that SS was in anyway at fault, just that this resolution was the first to be identified.

**Comment by smoothstreams** [comment]
> @smoothstreams Could you please make a announcement in addons4kodi subreddit , I'll be welcome to remove my "fix" repo if you guys have implemented a "fix" officially , after all that was the point is to get your attention !

Our users are generally somewhat smart, and installing some 3rd party random repo fix, would probably not be follewed.  Anyone who did/does install it, is a ***** idiot.

SS has a IRC Chatroom to discuss things (EfNet) and Public Reddit as well.

**Comment by smoothstreams** [comment]
> @smoothstreams Where is that dev branch available?

Within the SS Repo of course.  We have it for reasons like this.  Try that alongside Seren and see if all good.

If so, we can push to regular channel.
IRC would be best way to tell us, Reddit next best.

**Comment by drinfernoo** [comment]
@smoothstreams Anybody who installs a closed-source add-on in this day and age is not even "somewhat smart".

**Comment by SerpentDrago** [comment]
> > @smoothstreams Could you please make a announcement in addons4kodi subreddit , I'll be welcome to remove my "fix" repo if you guys have implemented a "fix" officially , after all that was the point is to get your attention !
> 
> Our users are generally somewhat smart, and installing some 3rd party random repo fix, would probably not be follewed. Anyone who did/does install it, is a ***** idiot.
> 
> SS has a IRC Chatroom to discuss things (EfNet) and Public Reddit as well.
> 
> Please dont post random patch fixes for SS or any repo, let the idiots fix it, or let em die.

appears everyone is saying the new patch you guys pushed is doing fine. so yeh id say push to main version 

this all would have been much cleaner if you guys had the addon source on github.

thanks for looking into it and fixing the  conflict.
