### ISSUE TITLE
Discover TV Shows -> Networks not up2date (Disney+)?

### ISSUE THREAD

**Issue by stuoningur** [nixgates/plugin.video.seren#203]
Hi,
when selecting Disney+ in the Networks category it's empty. I realize it's something from trakt, so not sure if anything can be done about it, but it I figured asking doesn't hurt.

Thanks!

**Comment by drinfernoo** [comment]
As you stated, these come from Trakt, so there's not much to be done.

I would recommend liking the following (or similar) Trakt lists as a workaround:

https://trakt.tv/users/drew-casteo/lists/disney-movies
https://trakt.tv/users/drew-casteo/lists/disney-tv-shows

A number of other networks have dedicated Trakt lists, most notably the ones curated by [ACLO_Networks](https://trakt.tv/users/aclo_networks/lists)
