### ISSUE TITLE
Cant playing videos from Current real debrid transfers

### ISSUE THREAD

**Issue by kitaarist** [nixgates/plugin.video.seren#204]
Already downloaded torrents from my rd account i cant start to watch from under option current real debrid transfers.Please help

**Comment by drinfernoo** [comment]
That would be because there isn't a "current transfers" section. Seren's "My Files" section shows everything that is currently finished downloading into your cloud.

**Comment by kitaarist** [comment]
Ok , I just start to use seren today, I did not see my files section, realised to under my files section i can open videos, no problem
