### ISSUE TITLE
Player.json

### ISSUE THREAD

**Issue by djdirty60** [nixgates/plugin.video.seren#205]
can you make a player.json for the moviedb helper?

**Comment by drinfernoo** [comment]
There already is one. Use the following URL to install players: https://bit.ly/tmdbplayers/

**Comment by djdirty60** [comment]
Link is not working

**Comment by drinfernoo** [comment]
Fixed, the trailing `/` messed it up.

**Comment by djdirty60** [comment]
Thnx
