### ISSUE TITLE
[Request] Disable fanart option

### ISSUE THREAD

**Issue by brentonv** [nixgates/plugin.video.seren#206]
Thanks again for all the work that goes into this great add-on. Just a simple request could you please add option to disable fanart. I'm running on a low end device and Seren is the only player without this option. Minimum fanart is 1. Could you please enable 0 or an option to disable all. Cheers

**Comment by drinfernoo** [comment]
If you don't enter a Fanart.tv API key, then no art will (or even can) be requested.

**Comment by brentonv** [comment]
Ok cool. I'll clear my key. Thanks for that!
