### ISSUE TITLE
[Request] Disable fanart option #206

### ISSUE THREAD

**Issue by brentonv** [nixgates/plugin.video.seren#207]
Sorry I couldn't re-open the pr. #206 response seems incorrect. I'm not talking about fanart.tv I'm requesting to disable all fanart ie large backgrounds. There seems no option to disable this.

**Comment by drinfernoo** [comment]
That sounds like something you would need to do in your skin.

**Comment by nixgates** [comment]
@brentonv as @drinfernoo has suggested, this is something your skin should handle. Seren simply supplies the information about it, your skin handles what to show/not to show. 

I'm sorry I couldn't be of more help.

**Comment by brentonv** [comment]
All good it's no big deal. I'm just trying to filter out all fanart and Seren is the only one that shows it. It only happens when Seren scrapes for tv or movie which is odd.

**Comment by drinfernoo** [comment]
If you're talking about the fanart backdrop on Seren's custom windows, you'll need a theme Wich disables them.

**Comment by brentonv** [comment]
So yeah that's what I was talking about!

**Comment by brentonv** [comment]
So yeah that's what I was talking about. Arctic Zephyr 2 Theme for Seren fixed it! Thanks Drinfernoo
