### ISSUE TITLE
Request feature to filter min file size for movies and show

### ISSUE THREAD

**Issue by minhgi** [nixgates/plugin.video.seren#208]
Request feature to filter min torrent file size for movies and Show. Reason to filter out fake video.

**Comment by brentonv** [comment]
I was going to request the same thing. When filtering out uncached sources and sorting by resolution this seems to catch a lot of 0kb files lately. Changing sorting from resolution to torrents works ok but minimum file size option would be best.

**Comment by nixgates** [comment]
I can implement it not a problem, you will loose some sources that come from providers that don't supply the size information though? 

All cool with that?

**Comment by brentonv** [comment]
What about just a checkbox to "include unknown filesize" and rather than set minimums you could maybe include another checkbox to filter out zero returns?

**Comment by minhgi** [comment]
Hi Nixgate.

I have no problem with it.  Gaia had that feature and have work well filtering out the fake xvid video.
Appreciate for looking at it.

**Comment by nixgates** [comment]
Ok I'll look at implementing it over the coming updates
