### ISSUE TITLE
Settings menu blank

### ISSUE THREAD

**Issue by Grant8585** [nixgates/plugin.video.seren#209]
When I click to open the settings menu the box pops up but there is nothing there. Any idea how to fix this?
I have updated kodi and reinstalled Seren from scratch. Problem still persists.
Thanks!

**Comment by Grant8585** [comment]
I tried wiping addon data and now the settings menu is accessible. F knows lol

**Comment by YIRMASTER** [comment]
same issue here I wiped the add-on data and then menu came back
