### ISSUE TITLE
Finish Watching doesn't continue from where you left off

### ISSUE THREAD

**Issue by icpryde** [nixgates/plugin.video.seren#21]
When you stop a movie, it will pop up in the "Finish Watching" category but when you click the movie from there it will start from the beginning, I notice if I click the same movie from within my trakt list the movie will play at the proper time but in the "finish watching" section it just always starts from the beginning.

This is on 0.24

**Comment by nixgates** [comment]
I'm not able to re-produce this issue. Can you please provide a log

**Comment by icpryde** [comment]
Hey @nixgates , so here’s my log I just tried it again and it does the same thing. I also provided a short video so you can see what it’s doing.

Here’s the log:

https://paste.kodi.tv/akomukakiv

Here’s the video:

https://streamable.com/ocybd

**Comment by nixgates** [comment]
It's odd, would you mind holding out for 0.1.25 and testing that again for me? 
There's a few changes in that coming release that may hopefully help this situation. 

I'll let you know once it's live

**Comment by mophawka** [comment]
this seems to be an user error.  i've spoken to icpryde and we determined his trakt bookmark prompt was unchecked causing videos to start over instead of prompting for a resume.

**Comment by mophawka** [comment]
Working here without flaw https://streamable.com/9wbqy resume prompt pops up and starts from one device to the next to the next where i left off. unclear if its a seren issue or skin suppressing the prompt?

**Comment by SerpentDrago** [comment]
What version of kodi are you both using ? 

What skin ?

**Comment by icpryde** [comment]
I’m using Aura skin on 18 RC1

**Comment by mophawka** [comment]
17.6 Eminence 2.0

**Comment by nixgates** [comment]
@icpryde can you please manually install 0.1.25 and see if your issue still persists?

**Comment by icpryde** [comment]
@nixgates I’ll try it out today and report back

**Comment by icpryde** [comment]
@nixgates Hey I have good news! 0.1.25 fixed the issue I can now resume under "finish watching" It works as intended now :)

**Comment by nixgates** [comment]
Beautiful, closing issue 🙏
