### ISSUE TITLE
RD cloud/My files folder. Playback error.

### ISSUE THREAD

**Issue by qwertyuiopBB10** [nixgates/plugin.video.seren#210]
Having issues with playback from the RD cloud under the my files section in Seren. Was working without issues for me previously in 1.6.3 of Seren, since 1.6.4 it doesn’t seem to let me playback any of the files however on multiple of my devices. Throws me a error when attempting to playback any of the files under the My files > Real Debrid. I will grab the error that it prompts from the log and post it here shortly, currently away from my devices with Kodi.

**Comment by qwertyuiopBB10** [comment]
Log errors: 
![C9DD851C-F26C-421C-93E5-4377CB3EC635](https://user-images.githubusercontent.com/29876839/72008556-18870480-3222-11ea-88a2-39fad3718bbd.jpeg)
![357F108B-2FB4-4605-BDE3-381AFA07E327](https://user-images.githubusercontent.com/29876839/72008557-18870480-3222-11ea-81cc-2e29d1bdf818.jpeg)

**Comment by drinfernoo** [comment]
We'll probably need the full log file. That doesn't really show what's happening.

**Comment by qwertyuiopBB10** [comment]
Full log from my iPhone running kodi: https://pastebin.com/Z76GHd73

Throws an error when attempting to play any of my real Debrid cloud/torrent files from the my files folder. Tested on my pc/Firestick/iPad/iPhone. Same issue on all devices.
Bug is not present on the 1.6.3 version of seren as I’ve downgraded back on a few of my devices and the RD Cloud files play without any issue. Seems to only give me this error with the latest release.

**Comment by nixgates** [comment]
@qwertyuiopBB10 this issue is fixed in version 1.6.6, my apologies for such a silly mistake.
