### ISSUE TITLE
Setting resetting after kodi left unused for a period of time.

### ISSUE THREAD

**Issue by ap00123** [nixgates/plugin.video.seren#212]
Have come across an issue which I seem to be able to replicate.

Essentially if kodi is left open and unused for a period of time, and is then used with Seren.

The initial scraping starts and says it was unable to find a source (even if they do exist). It will then provide the dialog box asking if you want to cache a torrent. If you select no and try to restart the search, Seren will say that no debrid account was identified. Upon going back into Seren's setting after this has happened, they appear completely reset.

Currently I've experience this one Mac OS on 10.14 and 10.15, and also on Android (specifically the 4K Firesticks)

**Comment by nixgates** [comment]
Could you let me know what version of Kodi you are running? 

v17 is notorious for this issue and if you are using it, I would suggest upgrading to one of the v18 releases

**Comment by nixgates** [comment]
Without any reply I can't investigate this issue any further, closing issue.

If you want you can let me know later on and we can continue to look into it
