### ISSUE TITLE
Error Trakt lists

### ISSUE THREAD

**Issue by kitaarist** [nixgates/plugin.video.seren#213]
When try to open a my trakt list app stucks like picture
![IMG_20200110_135107](https://user-images.githubusercontent.com/59301198/72147941-b3ade480-33b0-11ea-9204-2db4b35b9435.jpg)

**Comment by brentonv** [comment]
Currently, there are Trakt API and server issues. If you use Trakt in Seren, then there will be all kinds of erratic behavior to do with watched statuses, loading of Trakt lists, occasional slow loading of ANY lists.

**Comment by drinfernoo** [comment]
Yes, this is an issue with Trakt.

**Comment by kitaarist** [comment]
But why trakt apps working?

**Comment by kitaarist** [comment]
I saw post below
![Screenshot_2020-01-10-21-23-42-396_com twitter android](https://user-images.githubusercontent.com/59301198/72186793-17fb9300-3407-11ea-94a3-6a62bac4be2d.jpg)

**Comment by kitaarist** [comment]
I saw powt below about this
![Screenshot_2020-01-11-00-11-52-590_com reddit frontpage](https://user-images.githubusercontent.com/59301198/72186863-41b4ba00-3407-11ea-95ec-caa7f833d42e.jpg)
