### ISSUE TITLE
Database issues on Xbox.

### ISSUE THREAD

**Issue by Cwoo0** [nixgates/plugin.video.seren#214]
I have been experiencing database issues with Seren on Xbox since the release of version 1.6.0. Previous versions work ok. 

When the latest version is installed it works fine for 1-2 days then all items stop updating. The database shortcuts in Seren settings also don't work and gives the following error.

ERROR: OperationalError: database is locked

https://paste.kodi.tv/anixoyasab

**Comment by nixgates** [comment]
Thanks, I'm looking into it right now :+1:

**Comment by nixgates** [comment]
Ok looks like the database is locking up somewhere.

What version are you rolling back to in order for it to work again?

I need to look at the code differences for the database to try and pinpoint the issue.

**Comment by nixgates** [comment]
I believe I may have found a way that the database could become locked and cause this issue. Your log was the key, many thanks for that.

I'll hopefully have an update soon, just have to touch a few other smaller issues first.

**Comment by Cwoo0** [comment]
Great news, thanks for the quick reply! I rolled back to version 1.4.8 and it works fine. Thanks again for all the work you have put into Seren.

**Comment by nixgates** [comment]
@Cwoo0 I've pushed 1.6.5.

This should hopefully stop the database locking up on XBOX devices, could I ask you to give it a test for me when you get the chance?

**Comment by Cwoo0** [comment]
@nixgates I just installed version 1.6.6 and it seems to be working ok for now but I won't know for sure until I have been running it for a few days.  I'll post here again in a couple days and let you know if I start having database issues again.

**Comment by nixgates** [comment]
@Cwoo0 sounds good, keep me posted :)

**Comment by Cwoo0** [comment]
@nixgates That seems to have done the trick. I have been running the latest version for a few days now and I have not had any more database lockups. Thanks for you help, I appreciate it.
