### ISSUE TITLE
tv show seasons posters issue (see examples)

### ISSUE THREAD

**Issue by mgonzales71** [nixgates/plugin.video.seren#215]
Not sure why but... weird stuff :)

Can't even figure out the pattern

I've tried clear metadata and rebuild database in Trakt Tools

![kodi_2020-01-16_05-37-28](https://user-images.githubusercontent.com/6510026/72529547-5e475c80-3822-11ea-8c9a-afa13baff6d4.png)

![kodi_2020-01-16_05-34-44](https://user-images.githubusercontent.com/6510026/72529362-06105a80-3822-11ea-992f-5ee882f9b49a.png)

![kodi_2020-01-16_05-33-37](https://user-images.githubusercontent.com/6510026/72529363-06105a80-3822-11ea-9ff9-b9526cb3def3.png)

**Comment by drinfernoo** [comment]
You'll need to have a Fanart.tv key, Fanart.tv as the preferred source, and season posters enabled. Is this the case?

**Comment by mgonzales71** [comment]
i do have one set... and assume it is working since I get clearlogo and characterart in the info screen of the tv show in trakt.tv / my shows collection menu of seren

![kodi_2020-01-16_06-16-57](https://user-images.githubusercontent.com/6510026/72532433-3fe45f80-3828-11ea-88f1-9bd31d93f71b.png)

**Comment by mgonzales71** [comment]
Do let me know if I can provide and more info, logs, test anything etc.  I have an API key from fanart.tv and it’s entered in settings.  Is there is anything I can specifically do to test the key in Seren?  

This issue is not urgent at all.... 

I love this addon and please know that I greatly appreciate your work.

Thank you

**Comment by nixgates** [comment]
@mgonzales71 It might be that you have season posters disabled in the artworks settings.

The setting is in:

Settings > Artwork > Show Advanced TV Artwork Settings > Season.Poster

Make sure this is enabled, clear your metadata (not a rebuild) and then browse to a season list again. 

Hopefully this should rectify your issue.

**Comment by mgonzales71** [comment]
Already had that settings set so I tried just clear meta and same issue.

I am going to delete all addon_data for seren and re-configure from scratch and see if that resolves the issue.

**Comment by mgonzales71** [comment]
ok - so doing a full reconfigure did not solve the issue.

![screenshot000](https://user-images.githubusercontent.com/6510026/72909996-bc75b300-3cec-11ea-92fb-c10a56e82a04.png)

oddly future seasons don't seem to have the "repeated" artwork for seasons.

right now I have seasons -> posters enabled but not season banner, etc - i guess I will try with those enabled and see if that makes any difference,

**Comment by mgonzales71** [comment]
ok - well still same thing... I am at a loss.
Any other suggestions?
I gather this is not an issue for you?

I am pretty sure - fanart.tv has API 3 Keys being issued - Seren uses v3 API keys?

**Comment by mgonzales71** [comment]
Ok think I may have found something.

If I set "Prefer TV Show artwork from" to "Fanart.TV (slower)" I see this issue.
I tried setting it to "TVDB/TMDb" and the issue goes away.

![screenshot001](https://user-images.githubusercontent.com/6510026/72914340-67896b00-3cf3-11ea-8db9-807a2483fc55.png)

Change back to Fanart.tv -> clear meta -> season list of a show and problem returns

![screenshot002](https://user-images.githubusercontent.com/6510026/72914461-956eaf80-3cf3-11ea-9d9e-0293f846a2fc.png)

Hopefully this helps

I guess I will not use fanart.tv as prefered source for now

let me know if i can do anything else to help you with this

thanks!

Mario

**Comment by nixgates** [comment]
Ah, that's some perfect deductions made there. 

I'll look into it now.

Seems like it may be that the fanart.tv module is either not grabbing the correct poster or is not adhering to the season.poster setting.

Thanks for your work. I'll look into it

**Comment by mgonzales71** [comment]
no problem and than you for this addon

**Comment by Woproy** [comment]
Sorry to bump an older issue, but I am also having this same problem. Everything mgonzales said is the same for me. I did the same troubleshooting, and nothing changes. 

It's kind of a bummer because I prefer Fanart.tv posters and backgrounds. It used to work. This issue started happening within the last few months, probably when this issue was created by mgonzolas. 

Thanks for any assistance, and I do love Seren!
