### ISSUE TITLE
way to filter results or edit undesireable filter maybe keyword filter option? 

### ISSUE THREAD

**Issue by mgonzales71** [nixgates/plugin.video.seren#216]
Seems someone keeps uploading files with "coldfilm" as part of the file name to numerous sites omitting the fact that the video file is Russian language but is picked up as English.

I have disabled several providers but the problem seems to be random site and video files so in a sense it could be most of them affected until someone smacks down the source uploader(s).

![firefox_2020-01-19_08-51-00](https://user-images.githubusercontent.com/6510026/72684929-9c9a8100-3a99-11ea-872d-0c28deb93578.png)

for example:

```
154221 | {'info': [], 'hash': u'791f5f495799621bb9481757ac3ccdd5563def24', 'package': 'single', 'quality': '1080p', 'release_title': u'The.outsider.s01e02.1080p.coldfilm.mkv', 'scraper': 'skytorrents', 'magnet': u'magnet:?xt=urn:btih:791f5f495799621bb9481757ac3ccdd5563def24&dn=The.Outsider.S01E02.1080p.ColdFilm.mkv', 'seeds': 0, 'provider': 'SKYTORRENTS', 'type': 'torrent', 'size': 1996}
-- | --
154221 | {'info': [], 'hash': u'15c5140de6e95664733cd49c1fc48a0b026a7318', 'package': 'single', 'quality': '1080p', 'release_title': u'The.outsider.s01e02.1080p.coldfilm.mkv', 'scraper': 'skytorrents', 'magnet': u'magnet:?xt=urn:btih:15c5140de6e95664733cd49c1fc48a0b026a7318&dn=The.Outsider.S01E02.1080p.ColdFilm.mkv', 'seeds': 0, 'provider': 'SKYTORRENTS', 'type': 'torrent', 'size': 2007}
154221 | {'info': [], 'hash': u'd938922ccfc65ec1e0111ae122048708d0dcbb81', 'package': 'season', 'quality': 'SD', 'release_title': u'The.Outsider.S01.400p.ColdFilm', 'scraper': 'bitlord', 'magnet': u'magnet:?xt=urn:btih:d938922ccfc65ec1e0111ae122048708d0dcbb81&dn=The.Outsider.S01.400p.ColdFilm', 'seeds': 1, 'provider': 'BITLORD', 'type': 'torrent', 'size': 429}
154221 | {'info': [], 'hash': u'ac4b384791f33f54cbab9477568e32686829cb7d', 'package': 'season', 'quality': 'SD', 'release_title': u'The.Outsider.S01.400p.ColdFilm', 'scraper': 'bitlord', 'magnet': u'magnet:?xt=urn:btih:ac4b384791f33f54cbab9477568e32686829cb7d&dn=The.Outsider.S01.400p.ColdFilm', 'seeds': 9, 'provider': 'BITLORD', 'type': 'torrent', 'size': 429}
154221 | {'info': [], 'hash': u'c67ea3b8d8c1f580ad7bd4e262f4917f5e341ae6', 'package': 'single', 'quality': '720p', 'release_title': u'The.Outsider.S01E02.720p.ColdFilm.mkv', 'scraper': 'bitlord', 'magnet': u'magnet:?xt=urn:btih:c67ea3b8d8c1f580ad7bd4e262f4917f5e341ae6&dn=The.Outsider.S01E02.720p.ColdFilm.mkv', 'seeds': 2, 'provider': 'BITLORD', 'type': 'torrent', 'size': 1576}
```

or 

```
{'info': [], 'hash': u'8e1b5348aa34fda43259e4aa79b9494997bb636c', 'package': 'single', 'quality': 'SD', 'release_title': u'Manifest.S02E02.400p.ColdFilm.avi', 'scraper': 'bitlord', 'magnet': u'magnet:?xt=urn:btih:8e1b5348aa34fda43259e4aa79b9494997bb636c&dn=Manifest.S02E02.400p.ColdFilm.avi', 'seeds': 1, 'provider': 'BITLORD', 'type': 'torrent', 'size': 509}
--
{'info': [], 'hash': u'd9756781b31ec61310425cdd629099a28e2d2a9a', 'package': 'season', 'quality': 'SD', 'release_title': u'Manifest.S02.400p.ColdFilm', 'scraper': 'bitlord', 'magnet': u'magnet:?xt=urn:btih:d9756781b31ec61310425cdd629099a28e2d2a9a&dn=Manifest.S02.400p.ColdFilm', 'seeds': 1, 'provider': 'BITLORD', 'type': 'torrent', 'size': 111}
{'info': [], 'hash': u'7c9ea3fe3f874276fd0566e0b0b60a2526bf0159', 'package': 'season', 'quality': 'SD', 'release_title': u'Manifest.S02.400p.ColdFilm', 'scraper': 'bitlord', 'magnet': u'magnet:?xt=urn:btih:7c9ea3fe3f874276fd0566e0b0b60a2526bf0159&dn=Manifest.S02.400p.ColdFilm', 'seeds': 2, 'provider': 'BITLORD', 'type': 'torrent', 'size': 55}

```

Bitlord and Skytorrent seem to be overrun by them but I've seen it on Torrentz2 and Torrentz2_ PiratesBay, etc

Unfortunate people fell the need to purposefully upload files with intentionally incorrect meta info *(language in this case)

maybe a keyword filter option at some point?

until then I will just manually choose sources - no rush and thanks for seren!!!!

❤️ your work!

**Comment by fugkco** [comment]
This would be great! I get the same with `OMSKBIRD`. It basically makes my autoplay feature and the openmeta addon useless.

**Comment by drinfernoo** [comment]
@fugkco It's not within the scope of Seren to make sure OpenMeta works...

Are you referring to a provider named OMSKBIRD? That's not a provider I've ever heard of... Could you be using Orion?

**Comment by fugkco** [comment]
> It's not within the scope of Seren to make sure OpenMeta works...

Sorry, misunderstanding, this is not what I was referring to. Basically because the autoplay feature has been enabled in Seren, OpenMeta essentially just invokes Seren, which makes selects the top result, which in this case is a Russian video with no English audio. I'm not asking for Seren to make OpenMeta work with Seren. OpenMeta not working properly with Seren is just a side effect of this bug.

> Are you referring to a provider named OMSKBIRD? That's not a provider I've ever heard of... Could you be using Orion?

OMSKBIRD is in the torrent name, e.g. `FAMILY.GUY.S18.1080P.WEBRIP.OMSKBIRD` (provider differs, in my case it's mostly LimeTorrents and BitLord but again it comes up with other providers too). If we could get an option to remove results based on a keyword filter, it would resolve this.

**Comment by drinfernoo** [comment]
I would consider disabling those two providers. Lime tends to take a very long time to return, and BitLord tends to give fakes and foreign copies.

You can also use Source Select to pick sources, so that you don't get "bad" ones.

**Comment by fugkco** [comment]
Yep, I'd already done that, and on the off chance other providers produce bad sources, I've been manually selecting sources. Anyway, having a manual filter would be nice as I can continually add bad keywords to the blacklist or something like that.
