### ISSUE TITLE
Randomly skips to next episode during playback

### ISSUE THREAD

**Issue by janissimsons** [nixgates/plugin.video.seren#218]
Recently, during playback Seren stops the current episode and skips to the next one. Most of the time it isn't even close to the ending, just 10 minutes into the episode and it decides to play the next one...
This is extremely annoying.

How can it be prevented? What is causing this behavior?

**Comment by nixgates** [comment]
There's actually no code in Seren to tell Kodi to stop playback.

Generally, if you are able to look at a log when the issue occurs. The fault lies in network connection dropping or the file no longer accessible at the debrid provider (timeout).

Have you by chance modified your Kodi's Advanced Settings?

If so, I would suggest reducing your playback cache. From what I've been able to see (and I could be wrong here), with a large sized cache assigned for playback, Kodi can fill this rather quickly on a decent connection and then wait until more is required. This can eventually cause a lack of activity between your device and the link allowing it to expire.

**Comment by janissimsons** [comment]
@nixgates I haven't modified Kodi advanced settings.
Where can I change the cache size for playback?

**Comment by nixgates** [comment]
If you haven't modified it before, there's nothing to reset. 

Each time I've seen this occur, it's been due to network connection failure somewhere, if you could try and get a full debug log of when the issue occurs, that will help us to identify the root cause of the issue.
