### ISSUE TITLE
Extending the available sort options

### ISSUE THREAD

**Issue by nixgates** [nixgates/plugin.video.seren#220]
I'm raising this ticket to allow an open discussion for what people would like to see available as sort options. 

I'm not entirely sure how I intend to implement a more complex sort option, but once I do it would be good to have a list of items that should be covered:

Currently includes:

- Resolution
- File Size
- Identified audio channels
- Video Encode (H.265, H.264)
- Debrid Provider
- Video Resolution

**Comment by drinfernoo** [comment]
Consider options that we currently have as on/off, like "undesirables", SD quality, 3D, and HEVC items. These could likely be included into the sort, in order to not just hide or show them indefinitely.

**Comment by xyzfre** [comment]
Sorry I know this is off-topic but do you recommend clearing all cache within Seren after updating

**Comment by drinfernoo** [comment]
@xyzfre No, there shouldn't really be any reason you *need* to clear the cache, unless you're experiencing issues already.

**Comment by xyzfre** [comment]
With this latest update I do notice a speed performance ,specially in Trakt section,,great WORK with Seren thank you for all your hard work

**Comment by powei94** [comment]
An useful option would be to have different filters for auto and manual select modes, for example sometimes streaming 4K is a hit or miss for some users so it'd be useful to be able to manually select 4k sources but only autoplay 1080p or lower ones

**Comment by brentonv** [comment]
I'm extremely happy how it currently works. The only thing I've noticed is auto play can pick up 0kb files that don't play but sorting by torrent works fine.

**Comment by drinfernoo** [comment]
@brentonv The files labeled with 0 size usually means that the site they were scraped from doesn't report filesize.

**Comment by brentonv** [comment]
> @brentonv The files labeled with 0 size usually means that the site they were scraped from doesn't report filesize.

So would an optical n to exclude these be the simplest option? It seems to be only those files that mess up autoplay, when it tries to play a 0kb file for some reason.

**Comment by nixgates** [comment]
@xyzfre please raise a different issue for that

**Comment by Cwoo0** [comment]
I think a special edition filter for films could be useful. This could include files that have extended, Directors Cut, Uncut or remastered in the file name.

**Comment by nki2bpz** [comment]
Size sort ascending/descending option for file size would be extremely useful for me. I edited the .py file to sort small to large for hevc and it made Autoplay a treat for a while till i screwed something else up

**Comment by drinfernoo** [comment]
@nki2bpz What utility is there for sorting smaller files first? This seems like it's *begging* for fakes and low-resolution/quality content to shine through.

**Comment by nki2bpz** [comment]
> @nki2bpz What utility is there for sorting smaller files first? This seems like it's begging for fakes and low-resolution/quality content to shine through.

I find my results to be the exact opposite.   I think this is mainly because its only sorting the hevc small to large. and due to seren being premium links only. Autoplay ran for a week with the first link working great every time.  I find that with hevc up top and sources sorted small to large i get episodes @  0.6g-0.75g running smooth and the quality is not compromised, a lot of episodes at 1.5g-2.0g look the same at the same resolution but have better quality audio. I am only using the tv speakers so better quality audio is irrelevant to me and not worth the increased buffering in my setup.

**Comment by nki2bpz** [comment]
> @nki2bpz What utility is there for sorting smaller files first? This seems like it's _begging_ for fakes and low-resolution/quality content to shine through.

I suppose just a refined filesize sort would be more ideal. define min and max.

**Comment by je19921** [comment]
I know this thread is older, but if it is relevant, I would really love to have a sorting (or exclusion) option to exclude HDR.
AFter troubleshooting for a longtime, I concluded that my weird cheap 4K panel is unable to correctly play HDR movies, as it makes the image stutter. This would allow me to use autoplay.

**Comment by RadicalLime540** [comment]
> I know this thread is older, but if it is relevant, I would really love to have a sorting (or exclusion) option to exclude HDR.
> AFter troubleshooting for a longtime, I concluded that my weird cheap 4K panel is unable to correctly play HDR movies, as it makes the image stutter. This would allow me to use autoplay.

Second this. I currently have max quality set to 1080p as autoplay would pick 4K HDR links that would crash Kodi (normal 4K links work fine though). The ability to filter out HDR links would be HUGELY appreciated!

**Comment by nixgates** [comment]
I feel like most have these have been covered in 2.0 so far so while I'm trying to manage a but load of tickets I'm going to close this off.

If anyone here wants something that I missed, feel free to raise an issue yourself :)
