### ISSUE TITLE
Possible to add a "save settings" feature in a future update? 

### ISSUE THREAD

**Issue by bigpoppapaul** [nixgates/plugin.video.seren#228]
Just a suggestion to add a "save addon settings" feature in a future update sometime. I find my Seren resets itself sometimes out of nowhere and then I have to go through and customize everything again. Save/restore settings option would be amazing. 

One other question too, is there any way to cause the "play next" dialogue to appear earlier? It usually comes on when there is one minute left of the playing file, but with torrents, they usually have full credits so maybe an extension to 2 minutes (or the option to change it to customize when it pops up) would be very handy. 

Anyways, the latter is a bit of wishlist item whereas the former would be very handy. The auto reset hadn't happened to me in a long time but today it did.

**Comment by nixgates** [comment]
Sure I'll add it now and should be ready for next update (not far off)

**Comment by bigpoppapaul** [comment]
Thank you, sir! Are you talking about the first suggestion? The save/restore settings option?
