### ISSUE TITLE
[Feature Request] Initiate Search through JSON-RPC

### ISSUE THREAD

**Issue by halsandr** [nixgates/plugin.video.seren#23]
Currently to search for a film/show through the JSON-RPC I have only found a way to do it in 2 requests which feels clunky and prone to error.

```http://libreelec.local:8080/jsonrpc?request=[{"jsonrpc": "2.0","id": 2,"method": "GUI.ActivateWindow","params": {"window": "videos","parameters": ["plugin://plugin.video.seren?action=moviesSearch"]}}]```

```http://libreelec.local:8080/jsonrpc?request=[{"jsonrpc":"2.0"],"id": 2,"method":"Input.SendText","params":["Bug Buck Bunny"}]```

Would it be possible to pass something into ```actionArgs``` to skip to text input and initiate search on a given string?

**Comment by nixgates** [comment]
I've added support for this in Seren 0.1.25.
This will allow you to make a request to search and supply the value in one call, therefore bypassing the text input.

**Comment by Alfiegerner** [comment]
I just wanted to do thank you for this feature. With IFTTT we can initiate search through Google home, works really well.

**Comment by halsandr** [comment]
@Alfiegerner this is my exact use case! it was possible using my previous method, but it wasn't ideal.
