### ISSUE TITLE
Seren Xbox Themes not installing

### ISSUE THREAD

**Issue by bthedorff** [nixgates/plugin.video.seren#231]
I posted this in a thread on [Reddit](https://www.reddit.com/r/Addons4Kodi/comments/fhkymu/a_question_about_serens_upnext_feature/fkdufx1?utm_source=share&utm_medium=web2x) but thought I should make an issue as well. Themes don't seem to work on the xbox version of Kodi.  I have the most up-to-date version of kodi (18.6 for xbox),seren and auromod. I tried both the bit.ly and the full url to be safe and nothing. SerpentDrago look at my log and thought it may be a bug with Seren theme installation. My original log is below.

[Https://paste.kodi.tv/wusakaqife](Https://paste.kodi.tv/wusakaqife)

**Comment by SerpentDrago** [comment]
You are installing from the url right ? not downloading the zip first then installing right ? 

from INSIDE seren , install from url then give it the url

**Comment by bthedorff** [comment]
> You are installing from the url right ? not downloading the zip first then installing right ?
> 
> from INSIDE seren , install from url then give it the url

Yes, I'm installing from the URL and not downloading the Zip file. It is basically the same way you install A4Kscrapers (in reference to just installing from the given URL) but using the theme url and in a different settings location. I did try both the shortened URL and the full URL in case that was the issue but neither worked.

**Comment by brentonv** [comment]
Seren themes work fine on Xbox. I'm using AZ2 skin and have my own minimal theme rather than the Seren default theme.

**Comment by drinfernoo** [comment]
@brentonv Have you done anything special to your Xbox, like Developer Mode or anything?

**Comment by brentonv** [comment]
No everything is standard. I was on Kodi 18.5 which recently updated to 18.6. I'll test it again now and see if there are any new issues using 18.6

**Comment by brentonv** [comment]
I'm on AZ2 skin what url do I test?

**Comment by brentonv** [comment]
I think he's trying to use this on Reddit Reaper's Gaia setup. That would be messy.

**Comment by brentonv** [comment]
No everything is standard. I was on Kodi 18.5 which recently updated to 18.6. I just tried https://bit.ly/2wmLywq and it worked fine.

**Comment by brentonv** [comment]
I think he's trying to use this on Reddit Reaper's Gaia build. That would be messy. He should try creating a new xbox profile and test it on a clean kodi install.

**Comment by bthedorff** [comment]
> I think he's trying to use this on Reddit Reaper's Gaia build. That would be messy. He should try creating a new xbox profile and test it on a clean kodi install.

No build was used, everything was installed from its official repo. Also idk if this makes a difference but I'm using Auromod.
