### ISSUE TITLE
[Request] Genres Section ListItem.DBType

### ISSUE THREAD

**Issue by Demonseeed** [nixgates/plugin.video.seren#232]
Hello nixgates! Thanks for all the hard work you do. 

I was wondering if it’s possible to give the genre items in your addon the ListItem.DBType genre. 

The reason for this is when I point a widget to it via Skin Shortcuts, this is what I get. 
![67C1F62C-8969-4E8B-9C41-931DFB0F089F](https://user-images.githubusercontent.com/29167580/78208812-30090e80-745a-11ea-9af0-7650988576b6.jpeg)

I reached out the skin developer, jurialmunkey, and he advised the addon developer needs to set the ListItem.DBType to genre so it can pull genre icons. 

Thank you!

**Comment by SerpentDrago** [comment]
in auramod it works .. i dont' know how but it does . you just set that widget type to "genre" does ... i'm guessing az2 ? not have that option for widgets ?

**Comment by Demonseeed** [comment]
Yeah, AuraMod has been my preferred skin for the past... probably a year or more and it was fantastic. I noticed it was the only skin that circumvented this issue. 

I have since moved to Arctic Horizon to test it out and try out a different look for a while. 

AH does not have the Genre aspect, that was actually what I requested jurialmunkey to make 😂

**Comment by drinfernoo** [comment]
I like to point my genre widgets (and any widgets, for that matter) at TMDbHelper now, with default players set 👌

**Comment by Demonseeed** [comment]
@drinfernoo There is only one reason I don’t do that: multiselect

**Comment by drinfernoo** [comment]
@Demonseeed What do you mean by "multiselect"?

**Comment by Demonseeed** [comment]
@drinfernoo Seren has the ability to select multiple genres as once. 

To my knowledge, TMDbHelper does not (minus Discover, but you must already know what genres you want beforehand to create it into a widget).

**Comment by drinfernoo** [comment]
Oh, of course. I don't think I've ever actually used it 😅

**Comment by Demonseeed** [comment]
I don’t use it too often, but it does come in clutch sometimes 😂
