### ISSUE TITLE
Seren Genre Icons have Stop Symbol Superimposed Over Them

### ISSUE THREAD

**Issue by JohnatStile** [nixgates/plugin.video.seren#233]
Hi,

Have noticed that the Seren genre icons have stop symbol superimposed over them. 

See picture: https://imgur.com/a/2sS7U1o
Log file: https://paste.kodi.tv/uyuhujatay

Was going to try clearing Seren cache but thought I would run it by everyone first as I like to avoid this if possible.

Running latest repo Seren, latest repo auramod on Mi Box 3.

Thanks for any help.

**Comment by drinfernoo** [comment]
Seren actually doesn't even have genre icons, or icons for any of its sections 😅

It looks like you're using AuraMOD, so I'd take it up with him: https://www.github.com/skyfsza/repository.auramod/issues/
