### ISSUE TITLE
Request - Return to streams overview when video is stopped

### ISSUE THREAD

**Issue by peno64** [nixgates/plugin.video.seren#235]
I enabled the option that when the search of all streams is done that they are shown and that I can choose which one to play.
Sometimes when I have chosen a stream, I don't find a correct subtitle and I need to select another stream. Unfortunately when the video is stopped, the list of streams isn't shown again and I have to do the search again (which is fortunately very fast because it is still cached) and then I don't see anymore which stream I had selected (I have a bad memory :-( ).
So it would be great if it would be possible to have an option when a movie is stopped that the list is shown again and preferably that the stream that was chosen to play is selected. Maybe only show this list if the movie was played less than x% if that is possible.

Anyway a great addon you have made.
Thank you.

**Comment by nixgates** [comment]
Duplicate #156
