### ISSUE TITLE
[Request] Disable context menu

### ISSUE THREAD

**Issue by brentonv** [nixgates/plugin.video.seren#236]
Hi @nixgates just wondering if you might please consider including an option to disable the context menu as each time Seren updates it automatically re-enables.

I use jurialmunkey's Arctic Zephyr 2 skin and TMDBhelper with Seren set as the default player mainly from widgets so rarely interact with the Seren add-on directly and don't require extra context menu items. 

Thanks mate!

**Comment by SerpentDrago** [comment]
seren context menu only shows up for seren items. so it shouldn't cause you any issues or extra context menu entries on tmdb helper items.. 
its installed by default for good reason as when it was optional many many many people complained for lacking features that it provided. (they didn't know to install it)

**Comment by brentonv** [comment]
Ok thanks that's good to know. I wasn't sure where additional context menu items were coming from so I just prefer to turn off what I don't use. So it's not an issue then great. Thanks again!

**Comment by SerpentDrago** [comment]
the new context menu addon being developed for seren 2.0 release will have settings to allow you to disable things.

but 2.0 is still not ready for public release

**Comment by djdirty60** [comment]
> the new context menu addon being developed for seren 2.0 release will have settings to allow you to disable things.
> 
> but 2.0 is still not ready for public release

you may have some examples for us what it will look like🥰🥰🥰🥰

**Comment by drinfernoo** [comment]
@djdirty60 It's a settings dialog for the context menu add-on, that has checkboxes to enable/disable each item.

**Comment by djdirty60** [comment]
no talk about seren 2.0 if you have an example

**Comment by drinfernoo** [comment]
@djdirty60 It will be Seren, but faster.
