### ISSUE TITLE
Seren and Mediaimport project

### ISSUE THREAD

**Issue by ntilagoa** [nixgates/plugin.video.seren#237]
Hi
Thank you for the great work on seren.
Any chance that in future seren be compatible with the mediaimport project?
https://github.com/Montellese/xbmc/wiki/Downloads

Thank you

**Comment by drinfernoo** [comment]
What is the "MediaImport Project"?

**Comment by ntilagoa** [comment]
https://forum.kodi.tv/showthread.php?tid=224794
