### ISSUE TITLE
Two Possible Feature Add Requests for Next Release

### ISSUE THREAD

**Issue by Lasakro** [nixgates/plugin.video.seren#238]
Would it be possible to add for both shows and movies:

1) An Exit option while scrolling through pages of material which would bring you back anywhere so you wouldn't have to scroll back through the pages again to exit if you wanted to explore a different Genre for example. The option I need to use now is to Kill kodi-x11 then restart, it's quicker.

2) A "Percent of Watched Before Notifying trakt to Mark as Watched" user accessible variable adjustable from like 60-100. Seems a little low right now.

Oh, BTW Senen RULES!!

**Comment by vitorp07** [comment]
@Lasakro 
It's hard to tell without knowing which device and remote control combo you are using but for no.1, 
if your remote doesn't have any button mapped for "Home" you can still usually go back to the homescreen by doing longpress on the button that you use for "back" or "previous menu"

**Comment by nixgates** [comment]
Issue 1 was covered by vitorps comments and you second request was covered in 2,0 release.

Closing off :)
