### ISSUE TITLE
Slow to show my watchlists(movies) or discover movies/TV shows

### ISSUE THREAD

**Issue by ANHBOB** [nixgates/plugin.video.seren#239]
I have the 4K firestick, no additional addons installed..only Kodi 18.6, Seren, the Crew and Fen and Trakt besides the additional stuff that"s automatically installed with those addons. I still have over 3GB free space on the Firestick. ONLY with Seren does it take around 8-10 minutes to show the movie or tv show lists....that blue spinning circle stays there forever. I have the latest update of Seren and all the other addons are up to date. Any idea or suggestions how to make it populate the lists faster??

**Comment by SerpentDrago** [comment]
Debug log please , and replicate the issue

**Comment by drinfernoo** [comment]
> no additional addons installed..

> Seren, the Crew, and Fen and Trakt besides the additional stuff

So... there are additional addons installed 😅

Free space of your device doesn't really have anything to do with loading speed, but things that would affect it are free RAM, the size of the list you're trying to view, and whether or not you're having the lists paginated (a setting in Seren controls this).

**Comment by ANHBOB** [comment]
What I meant was I have many things turned off on the firestick,, only using it for Kodi.not Plex or any other things that could be sideloaded to the firestick. I only have the 4 addons installed...no builds.
I have around 525 MB free ram by what Kodi shows...settings System info. The size of the lists is around 35 movies, no I do not have paginated turned on....I'd rather see all my movies at once than have to wait a long time for the 2nd page to load.
This even happens when I go to Discover movies...Box office top 10. There's only 10 movies to display, but before it shows the movies I have to wait almost 10 minutes to see the list....usually around 8-9 minutes.
My internet speed is 35Mbps download, 4.5Mbps upload. I have rebooted the router and modem.
Kodi 18.6, U.S.A. Seren 1.6.16.  I have no idea how to get a log file from the firestick to here, but I'll look into it.  Seren is THE only addon giving me trouble so I thought I'd post here.
