### ISSUE TITLE
Alldebrid support - migration to apiv4

### ISSUE THREAD

**Issue by Alldebrid** [nixgates/plugin.video.seren#240]
Hello,

We are the Alldebrid staff. We are contacting you today about an update regarding our API.

We will disable our old API at the end of the month. 

Documentation for the last API is here : https://docs.alldebrid.com/v4/ . This API should be the final version and should not change much in the futur.

Let us know if you need more information or any help.

**Comment by emiliodeme** [comment]
Looks like Seren needs an update for alldebrid now, it was working fine yesterday... But today it doesn't find streams anymore and returns an error when trying to reauthorize alldebrid.

**Comment by n4tur3502** [comment]
Can we get this updated please? I had to reinstall everything and cant authorize.

**Comment by drinfernoo** [comment]
Closed in 1.6.17.
