### ISSUE TITLE
Seren playing next

### ISSUE THREAD

**Issue by Arathonk** [nixgates/plugin.video.seren#241]
Recently I started using Seren with the Smart Play Popup enabled,
With the Up-Next addon not working with Seren anymore, Playing Next is the only option to auto play the next episode in order to binge watch shows. 

However it would be great if there could be an option to cancel/stop autoplay if I don't want to continue watching, could an option be added to the pop up to do so? 
Or an option to set it to stop playing by default and the pop up asking if you want to play next and if nothing selected it just stops.
I know I can set it to pause but I don't really like that option.

Also, it would be nice if the transparency of the pop up could be lowered so the show playing can still be seen through it and isn't as obstructed as it is now.

**Comment by drinfernoo** [comment]
Regarding the transparency of the dialog, it can be fully customized by using [[Themes]].

**Comment by Arathonk** [comment]
> Regarding the transparency of the dialog, it can be fully customized by using [themes](https://www.github.com/nuxgates/plugin.video.seren/wiki/Themes).

Could you explain how to edit the standard theme to have the popup more transparent?

**Comment by nixgates** [comment]
@Arathonk you can binge watch shows without having the dialog enabled. It's just a dialog, it doesn't handle any process. 

Seren makes use of the Kodi's playlists to provide the "binge like" effect so the dialog is not required.

Unfortunately stopping the playback and then starting the next one isn't really a great solution as stopping the playback clears the current playlist. While it's possible, it's a lot of work to replace an already existent stop button in the kodi gui so I see very little value in it.
