### ISSUE TITLE
Seren alldebird auth error

### ISSUE THREAD

**Issue by heyitzjesse** [nixgates/plugin.video.seren#246]
Hello
All of a sudden i was having issues finding any sources, I tried to wipe addon data and reauthorize alldebrid but its generating an error and not letting me authorize. Please see attached log. I am using latest kodi build.

https://pastebin.com/V1gjL6xT

**Comment by SerpentDrago** [comment]
AD support is currently broken in Seren , Dev is aware .  API change by AD is the reason .

**Comment by heyitzjesse** [comment]
> 
> 
> AD support is currently broken in Seren , Dev is aware . API change by AD is the reason .

Thank you much. I was pulling my hair out for no reason.

**Comment by xyzfre** [comment]
Thank you for clearing that up I was having the same issues with AD ,really appreciate all the hard work you guys do Seren Is the best

**Comment by drinfernoo** [comment]
@heyitzjesse @xyzfre, can you test 1.6.17 to see if everything is working now?

**Comment by xyzfre** [comment]
Sure give me two minutes

**Comment by xyzfre** [comment]
Yup it is working with no problems authorize and check with a TV show and getting AD Links ,thanks for the fix and a AMAZING addon Great job👍🏼👍🏼

**Comment by heyitzjesse** [comment]
Good to g o! Thank you again!

**Comment by emiliodeme** [comment]
Looks like it's still not working. I could reauthorize, it scraps some results but it won't play. Ends up saying "No playable sources found for this file".

Is it just me? I tried reinstalling Kodi from scrap and error persists, unfortunately I don't have another debrid account to test if it's associated to All-Debrid, but looks like.

Really looking forward to able to use Seren again, it's by far the best add-on for the purpose.

**Comment by xyzfre** [comment]
For me it was working fine yesterday but now it seems to skip All Debrid links and I try with multiple add-ons ,,RD it’s working fine so I’m starting to think it might be a All Debrid issue

**Comment by heyitzjesse** [comment]
Same here, even manual search it is showing sources but when you try to play , it is showing no playable sources found.

**Comment by SerpentDrago** [comment]
@heyitzjesse @xyzfre  can you guys please post full debug logs ?

**Comment by heyitzjesse** [comment]
Attached is the log, let me know if you need more.

In the following log, I am pulling up a movie ( doctor strange), that is showing no playable sources found, and after that playing a movie ( guardians of galaxy) that is playing perfectly fine. so it seems its happening randomly.

https://pastebin.com/ZNPixqbN

**Comment by heyitzjesse** [comment]
> 
> 
> @heyitzjesse @xyzfre can you guys please post full debug logs ?

Attached is the log, let me know if you need more.

In the following log, I am pulling up a movie ( doctor strange), that is showing no playable sources found, and after that playing a movie ( guardians of galaxy) that is playing perfectly fine. so it seems its happening randomly.

https://pastebin.com/ZNPixqbN

**Comment by emiliodeme** [comment]
Any news? 

Here is my log, trying to pull Scoob!
[https://pastebin.com/eie9meZt](url)

It scraps normally and give many alldebrids links, but it won't play. It tries to load and go from source to source until it says "No playable source found for this file"
