### ISSUE TITLE
No playable source found for this file - AllDebrid

### ISSUE THREAD

**Issue by emiliodeme** [nixgates/plugin.video.seren#248]
As said on a closed issue of AllDebrid new API, after the API was fixed I can't play movies, it scraps normally and when you choose to play it won't play, goes through every scraped source and in the end gives a message "No playable source found for this file".

I tried reinstalling Kodi and Seren but it won't fix. Same problem happening on three different Mi Box S and on a Windows PC.

The problem doesn't happen for TV Shows.

Here is my log, trying to pull Scoob!
[https://pastebin.com/eie9meZt](url)

Same issue was reported on reddit [https://www.reddit.com/r/Addons4Kodi/comments/gkk6zi/seren_no_playable_sources/?sort=new](url)
It's marked as solved but doesn't look like it is. Don't know if this is a A4kScrapers issue or Seren issue.
Here is another log posted on the reddit page [https://pastebin.com/tqu9rmRh](url)

Thanks for the wonderful work!

**Comment by nixgates** [comment]
Howdy, sorry about that, seems that fell through the cracks when we tested the new module.

I've just made some changes and pushed an update. When you get a chance can you have a look and let me know if it's working now?

**Comment by emiliodeme** [comment]
Hi Nix!

Don't be sorry :D, problems happen and you are doing a wonderful work!

I updated the addon manually as the 1.6.18 didn't automatically pull from repo, but the error persisted unfortunately.

[https://pastebin.com/JXugM9Dz](url)

If there is anything else I can do let me know!

**Comment by xyzfre** [comment]
Having the same issue ,TV shows play but not Movies with AllDebrid,, Hope it gets sorted soon appreciate the amazing work that goes into Seren

**Comment by nixgates** [comment]
Ok easy, I see what's happening my mistake again.

Give me an hour and I'll push out another update.

**Comment by nixgates** [comment]
Ok lads, sorry about that, new update is up, tested and single file resolving is working for All Debrid again 👍 

I'll leave this issue open for a bit just in case, but if you could confirm for me that would be great

**Comment by xyzfre** [comment]
Thank you looking forward to checking the update unfortunately I won’t be home for a couple hours but definitely as soon as I walk in I will give it a test run appreciate your response and your time and once again all your hard work

**Comment by ReaLx3m** [comment]
Not sure if i had the problem on previous versions as i havent tried any movies with them(tv shows worked ok), but i just tried few movies with AD(Scoob included), and it seems its working fine.

**Comment by xyzfre** [comment]
Just gave it a test run with Beach Bum Movie and played right away with AllDebrid ,, thank you for sorting this out much respect for all your work is amazing

**Comment by emiliodeme** [comment]
> Ok lads, sorry about that, new update is up, tested and single file resolving is working for All Debrid again 
> 
> I'll leave this issue open for a bit just in case, but if you could confirm for me that would be great

Thanks! Working fine again :)

**Comment by israelglar** [comment]
Hello, I started having this problem. It was working fine, but not everything I click is showing `No playable source found for this file`
Also using AllDebrid

**Comment by stormcloud55** [comment]
Having same issue with no playable sources with Real Debrid. Preference for RD cloud ticked in settings. Still got 71 days left. Trakt also authorised. RD authorised while VPN off then put back on again  (troypoint says this ? ) a4Scraper package installed. Using a X96 box on ethernet connection with ping @ 40  download @ 31.3Mbps upload @ 18.1Mbps  surfshark vpn ON. Turned off broadband and device then rebooted. On Kodi 18.8 I'm stuck now.....please help . Cheers Jools

**Comment by tadad01** [comment]
Just finished watching one episode and went to load the next episode and getting no playable sources. Happening across the board with anything I try to load. Real Debrid and Trakt are all current.
