### ISSUE TITLE
[REQUEST] File Size Sort Ascending

### ISSUE THREAD

**Issue by ReaLx3m** [nixgates/plugin.video.seren#249]
The current and only option for filesize sort is descending and no option for ascending.Even though it can be done atm by manually editing getSources.py, it has downside as it resets after an update of the addon and needs to be redone.
It would be nice if there would be baked in ascending/descending choice for the Filesize Sort option. It would benefit people with metered connections that like to have autoplay on.

**Comment by nixgates** [comment]
@ReaLx3m option available in 2.0
