### ISSUE TITLE
Please add non cached links option & packs

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#25]
Please can you add an option in settings to show non cached links for real debrid and allow us to add them to real debrid.

Can you also add support for season packs in real debrid.

Gaia has both of these working.

**Comment by nixgates** [comment]
Season packs with Real Debrid are supported provided RD has the file available to stream.

You can set your cache style to manual in the settings. This will show you all the identified items and you can choose to cache one should you wish. This will be performed in the background and you will be free to use Seren while it occurs.
