### ISSUE TITLE
[REQUEST] Filter movies not yet out of theater from default trakt lists. 

### ISSUE THREAD

**Issue by kmb519** [nixgates/plugin.video.seren#250]

**Comment by SerpentDrago** [comment]
there is not good accurate way to do this . also there are cases where a movie is not out in theater .. yet .. "available " .

Simply put this will NEVER happen .  If you want to only see movies with "releases" follow/like  various trakt lists that cater to that and view them inside seren 

https://trakt.tv/users/garycrawfordgc/lists/latest-releases?sort=added,asc

https://trakt.tv/users/giladg/lists/latest-4k-releases?sort=added,asc

https://trakt.tv/users/giladg/lists/latest-releases?sort=added,asc
