### ISSUE TITLE
Seren RD cloud playback appears to be broken 

### ISSUE THREAD

**Issue by SerpentDrago** [nixgates/plugin.video.seren#251]
https://www.reddit.com/r/Addons4Kodi/comments/gprd16/seren_wont_play_cloud_sources/

See that thread . 

Playback doesn't work = though a Cloud scraped source . same file in cloud plays fine with other addons such as Realizer . and with seren my files

**Comment by Cwoo0** [comment]
Any update on this? Been broken for a while now.

**Comment by SerpentDrago** [comment]
If the issue still exists in the Future Seren 2.0 release , it will be looked at then . Seren 1.x will not be worked on anymore . just have to wait . 

as far as i know only a few weird edge cases fail to play from cloud scraper

**Comment by 5ilv3r5urf3r** [comment]
Same issue here. Will play through seren my files. But won’t play from a seren scrape.

**Comment by 5ilv3r5urf3r** [comment]
2.0.9. Turned off pre-emptive termination so cloud sources can be found. It works great on some shows and then not at all on others.
