### ISSUE TITLE
Trakt progress issue

### ISSUE THREAD

**Issue by ananias47** [nixgates/plugin.video.seren#252]
Hi my friend sorry about i am writing here but i dont know where to post this

On trakt progress of the $hadow addon it is by default upside down (ascending and no descending)

**Comment by SerpentDrago** [comment]
This is the comment section for the Seren addon NOT shadow . the dev for seren has absolutely nothing to do with shadow.

**Comment by seren86** [comment]
Try flipping your TV 180 degrees.

**Comment by ananias47** [comment]
I will try it thnx
