### ISSUE TITLE
[REQUEST] Add automatic stopping of playback after X seconds when paused.

### ISSUE THREAD

**Issue by KILIM4N** [nixgates/plugin.video.seren#253]
I have my kodi set up to close itself after x minutes of inactivity, or sometimes i would set it up to shut down windows after x minutes of inactivity.
This feature is vital because most of the time i fall asleep watching videos and i want my PC to turn off by itself or at least get into sleep mode.

From my understanding, KODI power saving feature does not trigger when a video is paused, so if you pause a video in seren, your KODI and windows will stay up indefinitely, without ever entering sleep mode, at least that's how it seems to behave on my setup.

The problem is that the still watching feature of Seren  is pausing the video once you watched 3 videos (by default i think) instead of stopping playback, preventing my KODI to close/shut down and my windows to trigger sleep mode.
I often wake up with my KODI still open, paused at the end of the last episode before still watching triggered.

Possible fix : Make "still watching" stop the video instead of pause, after some inactivity ?

Thank you all for your work, love !

**Comment by nixgates** [comment]
I like the idea, I'll get it in the pipeline. 

Sorry it's taken so long to look at this request!
