### ISSUE TITLE
[Request] Option to hide "My Files" section

### ISSUE THREAD

**Issue by metaltermite** [nixgates/plugin.video.seren#255]
Please add an option to hide "My Files" in the settings, or password protect it with a PIN, or both.

Use-case: When ppl are over and watching tv they currently have the ability to go to the My Files section and just casually browse through all my files. Not good.

**Comment by SerpentDrago** [comment]
Why don't you use a good skin , and setup menus and shortcuts to the various sections you want people using . then they would have no clear / easy obvious way to directly go to the main menu of seren . 

So get a skin like AZ2 or something or Estourary mod v2.   delete the default menus for shows / movies . set widgets or  submenus or whatever to various sections and search in seren . then users wouldn't need to go Seren > whatever and not even see my files . unless they dug deep and went settings > addons  > video addons > seren . 

Setup your skin and kodi right and people wouldn't be diving directly into the seren main menu

**Comment by metaltermite** [comment]
@SerpentDrago I am using AZ2, and your suggestion is flawed because Kodi shows the parent directory in all video addons, which is an clear/obvious way to get to the root of Seren and see "My Files".

Hence the request to simply hide "My Files" via settings, or the complex solution to make it accessible with a PIN.

Yes, someone can just dig around in the settings and unhide it, but that's much more unlikely in a typical scenario (at least for me). But exploring an addon by navigating to parent directories is using Kodi exactly how it was meant to be used.

**Comment by drinfernoo** [comment]
You could "Hide Parent Items", just FYI ;)

**Comment by metaltermite** [comment]
Yeah, but then that disables the ability to navigate to any parent directory in every tree :/

**Comment by metaltermite** [comment]
As an aside, Kodi has something like this already built in _Settings > Interface > Masterlock > Master lock code and settings_, and you can specify what aspects of Kodi you want locked with a PIN, such as settings, but it doesn't apply to addon settings unfortunately out of the box.
