### ISSUE TITLE
need to press play twice

### ISSUE THREAD

**Issue by sidpapa984** [nixgates/plugin.video.seren#256]
I recently installed Seren. I'm on kodi 18.7 with confluence skin. When I select a movie and press play, scrapers initialize, torrents/hosters populate, but resolutions stay at 0. Once it finishes, it pops back to the movie list. When I press play again, I'm seeing larger numbers for torrents/hosters, the resolutions are now populated and once the progress bar finishes, a cached RD stream starts playing. TV episodes only need one play press to work. I have both movie and TV set to autoplay.

**Comment by drinfernoo** [comment]
A debug log would be required to try and diagnose. I've don't think I've ever encountered this.

**Comment by sidpapa984** [comment]
How do I get a debug log - I don't see a page in the add-on.

**Comment by drinfernoo** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by sidpapa984** [comment]
Hi,
Sorry for taking so long, it's been a long couple of weeks. Here is the link to the log.

https://paste.kodi.tv/og6raxilar

Again, thanks so much for your time and assistance.

**Comment by nixgates** [comment]
This should be resolved in 2.0 with any luck. Could I ask you to investigate and confirm @sidpapa984

**Comment by nixgates** [comment]
Closing this off due to no response. If you'd like me to open it back up, feel free to let me know!
