### ISSUE TITLE
[REQUEST] play random episode

### ISSUE THREAD

**Issue by kranix0** [nixgates/plugin.video.seren#258]
Sometimes I want to watch a show but I don't care what episode. That's especially the case when I want to quickly put something on for my kids.

It would be great to have an option to play a random episode of a show or one of its seasons. This has been a useful feature in other streaming add-ons.

And instead of queueing the next episode, Seren could queue another random episode to keep the fun going.

And maybe, the randomness could be set at the list level. So I could have a list of shows (defined in Trakt) and Seren could play a random show and an episode within it.

**Comment by seren86** [comment]
Install the context menu addon from the Nixgates repo and use "Shuffle Play".

**Comment by kranix0** [comment]
Thanks for that. I wasn't aware. I'll give it a go!
