### ISSUE TITLE
[Feature request] Download streams

### ISSUE THREAD

**Issue by jimwormold** [nixgates/plugin.video.seren#26]
Would it be possible to be able to download content rather than always streaming? Apologies if I've missed a setting somewhere (similar to the download settings in incursion).

Thanks

**Comment by nixgates** [comment]
I do not have any intentions of adding downloading to file support as this is out of the scope of Seren. If you wish to do so, you should utilize your cloud providers website to handle downloading a file. 

This may change in the future, but I don't likely see any reason to do so.
