### ISSUE TITLE
Seren Next Up Episodes not working

### ISSUE THREAD

**Issue by ShibajiCh** [nixgates/plugin.video.seren#260]
Hi, I'm unable to view any episodes in next up since few days. Thought it was trakt issue at first but it's working fine on other add ons. Plus all other features related to trakt are working fine on seren. Whenever I'm trying to load next up seren throws an error that it couldn't fetch next up. It's been happening on all my kodi installed systems. So it's not an isolated issue for me alone. Could you please look into the issue and fix it ASAP?
Thanks, Shibaji.

**Comment by drinfernoo** [comment]
Rebuild your Trakt DB.

**Comment by ShibajiCh** [comment]
Thanks it worked!

**Comment by ShibajiCh** [comment]
Actually, rebuilding Trakt DB didn't work but revoking and then
reauthorising Trakt worked.

Thank you!
