### ISSUE TITLE
Trakt rating and Seren

### ISSUE THREAD

**Issue by onlytanmoy** [nixgates/plugin.video.seren#261]
Hi Nix @nixgates hope you doing fine under the circumstances we find ourselves in. I got a request with respect to Trakt in my dear Seren add-on.
Please see below issue
trakt/script.trakt#507
The developer of the Trakt add-on has indicated that this issue is down to the fact that Seren is not sending the right info as expected by Trakt and therefore it fails to show the rating pop-up at the end. Please add code to set the window property the Trakt add-on wants to use upon completion of playback of movie.
I know some people find it silly to rate a movie after watching but I personally enjoy it so will be nice to get it working. Let me know if you need more details. TIA.

**Comment by onlytanmoy** [comment]
@nixgates note that the latest update of Fen 1.7.12 fixed this issue based on the ticket I logged https://github.com/Tikipeter/repository.tikipeter/issues/250
Kindly implement the same in Seren too.

**Comment by nixgates** [comment]
@onlytanmoy no worries, I'll get onto this for you. Will likely be a 2.0 fix though is that ok?

**Comment by onlytanmoy** [comment]
> @onlytanmoy no worries, I'll get onto this for you. Will likely be a 2.0 fix though is that ok?

Yeah sure, that's perfectly fine. Thanks Nix.

**Comment by onlytanmoy** [comment]
@nixgates hi mate, please look into this. I tested with a movie today in the new Seren 2.x, still no rating pop-up.

**Comment by xyzfre** [comment]
On my end I do not get Trakt or TMDB ratings for episodes￼ but they do show up for TV show seasons￼ using AuraMOD on Nvidia Shield ,Seren 2.0.6￼

**Comment by nixgates** [comment]
@onlytanmoy ok I'll investigate this again, we did have this tested and working so shouldn't be to hard.

**Comment by onlytanmoy** [comment]
@nixgates hi mate, quick update- I tried with the latest version of Seren, the Trakt rating pop-up is not coming up for movies alone, for TV episodes it is working fine.

**Comment by onlytanmoy** [comment]
@nixgates just commenting to keep this ticket alive lest stale bot closes it :)
