### ISSUE TITLE
[Request]Inclusion of RD History section

### ISSUE THREAD

**Issue by onlytanmoy** [nixgates/plugin.video.seren#264]
Currently Seren only got RD Torrents section.
Please include RD History section too from where I can play the videos.

**Comment by onlytanmoy** [comment]
@nixgates Hi Nix, please look into this or comment something so that this ticket remains active and doesn't get closed now that stale label has been applied 😄

**Comment by nixgates** [comment]
@onlytanmoy thanks bud! Haha sorry I'm trying to get through these issues and the old ones are making it difficult. I'll add it to the list to get put in for an upcoming update! :)

**Comment by onlytanmoy** [comment]
@nixgates Nothing to be sorry about mate, you are a star! We all love you for gifting us this amazing add-on, thank you ever so much.

**Comment by onlytanmoy** [comment]
@nixgates hi mate, just commenting to keep this ticket alive since I got the stale message from the bot :)
