### ISSUE TITLE
Error with trakt lists

### ISSUE THREAD

**Issue by jaum20** [nixgates/plugin.video.seren#265]
`SEREN: Unable to connect to Trakt`

Already tried to reactivate account. Complete log here https://anonymousfiles.io/AAd5jhgK/

**Comment by nixgates** [comment]
Looks like you were experiencing the effects of a Trakt outage. 

This ticket is from some time ago so I'm going to close it off. If you would like me to look into it again, please feel free to let me know and I'll open it up again :)
