### ISSUE TITLE
Slow loading on Android TV

### ISSUE THREAD

**Issue by HubertHoppe** [nixgates/plugin.video.seren#266]
Hello, 

From the very beginnning when I installed Seren on my Mi Box with Android TV it takes aroud 1 minute to search through available providers. Even changin between menu levels takes like 5 times longer than on PC version.

I got kodi with Seren and real debrid installed both on PC and jailbroken Iphone and on both of these devices all works so smooth, any ideas how I could fix it?

Regards
Hubert

**Comment by mathu204** [comment]
May be the device specs you need a decent device to run Kodi and addons smoothly. PC will always be much much faster you’re best bet is something like a shield or dedicated Kodi box such as an Odroid, or maybe rpi

**Comment by H4wkeye1** [comment]
Mi Box is kinda slow, the new Mi Box S is faster. Not sure you can do much beside upgrade.

**Comment by nixgates** [comment]
@HubertHoppe sorry as mentioned in the other comments, it sounds like the Mi Box can't handle the throughput required for smooth transitioning.

This would have been for 1.6.9 but hopefully with the speed increases in 2.0 this is a lot faster now. 

Closing this off as not much can be done from my side of the park :(
