### ISSUE TITLE
Seren 2.0.6 NextUp and startup errors

### ISSUE THREAD

**Issue by DaisyF8** [nixgates/plugin.video.seren#271]
Update went smooth. Now errors on restart. NextUp isn't working.

https://paste.ubuntu.com/p/JgMhW2qXyV/

**Comment by DaisyF8** [comment]
and this log a bit later with having pressed NextUp in Seren

https://paste.ubuntu.com/p/jRH6Mt6wXC/

**Comment by nixgates** [comment]
There definetely seems to be an issue with the database on your device. If you could try a rebuild that would be good.

If that fails you may need to remove the files manually. 

Please refer to #273 with details on how to remove the files

**Comment by nixgates** [comment]
Closing this issue,

Please refer to duplicate ticket #237 to track the progress

**Comment by DaisyF8** [comment]
On 2.0.8 now. Rebuild didn't solve my problem.

Full uninstall with delete settings did. Reinstalled and then the Trakt Sync took a lot longer.

Nuclear option works 😀
