### ISSUE TITLE
Seren errors on Kodi start. 

### ISSUE THREAD

**Issue by Cwoo0** [nixgates/plugin.video.seren#272]
New update seems to have broken something. I am just getting seren errors on Kodi startup now. Can't open the add-on either. Tried a fresh install of Kodi same issue. 

https://paste.kodi.tv/funenajidi

**Comment by nixgates** [comment]
@Cwoo0 this should now be resolved in 2.0.7, please try and update and let me know

**Comment by Cwoo0** [comment]
@nixgates 

It seems to have fixed the startup error and I can now open the add-on. Unfortunately I am now getting errors when syncing with trakt. 

It says unknown error when connecting to trakt after a couple minuets and then continues to sync. 

https://paste.kodi.tv/xijibaface

**Comment by nixgates** [comment]
@Cwoo0 looks like it would have been a temporary connection issue to Trakt, would you mind letting me know if the sync was able to complete successfully?

**Comment by Cwoo0** [comment]
@nixgates It seems I can now sync with trakt. I am not getting seren error popups when syncing anymore but I am not sure the sync is completing correctly. It syncs everytime I open Kodi and again when I was halfway through watching a TV show  They're are still seren errors in the log.

 https://paste.kodi.tv/aqokimuxes

**Comment by nixgates** [comment]
@Cwoo0 looks like there's still a random issue with working with your time zone for one item for some reason.

I'll have to dig into that to try figure it out. I'm sorry about that, I'll try have it sorted as quick as possible.

**Comment by Cwoo0** [comment]
@nixgates 

Unfortunately the latest version (2.0.12) is still having database issues on Xbox.

Here is a log when building the database. 
https://paste.kodi.tv/ociqugerir

Thanks so much for your hard work, it's much appreciated!

**Comment by nixgates** [comment]
@Cwoo0 can you do me a favour and grab a log with debug on? Need to see what Seren thinks your device is :)

**Comment by Cwoo0** [comment]
@nixgates 

No problem,

https://paste.kodi.tv/dagayesumi

**Comment by nixgates** [comment]
@Cwoo0 this is fixed for the next update tested on a xbox one and a series X!

**Comment by Cwoo0** [comment]
Thank you!

**Comment by nixgates** [comment]
@Cwoo0 see you've closed it so I hope that means we are working! 

Glad to help :)
