### ISSUE TITLE
[REQUEST] Pre-emptive termination (Minimum sources) - Separate sliders for both Movies and TV shows

### ISSUE THREAD

**Issue by inb4after** [nixgates/plugin.video.seren#274]
Due to the amount of 4K movie sources vs 1080p TV sources, shows have very limited sources which benefits from a lower minimum source amount. Movies are the exact opposite and benefits from a higher minimum source amount.

It would be useful to the end-user to be able to set different minimum sources for each. This way, a user could simultaneously receive more sources (scrape longer) when watching movies and receive less sources (scrape shorter) when watching TV shows, or any recombination of the previous.

The user may also wish to continue using the current system, in which case this feature implementation can cater for that usage as well: setting the same minimum source count for both hypothetical sliders.

Thank you for reading,

-inb4after

**Comment by Bulletbling** [comment]
We absolutely need this! Most tv shows are 720/1080p so my pre emotive 4K setting never applies to tv shows. I’d do 1080 pre emotive for tv shows. Venom does this very well iirc.

**Comment by inb4after** [comment]
> We absolutely need this! Most tv shows are 720/1080p so my pre emptive 4K setting never applies to tv shows. I’d do 1080 pre emptive for tv shows. Venom does this very well iirc.

Seren already has separate resolution settings for movies vs TV shows, so you can use 4K for movies and 1080p for TV shows. My suggestion was for the minimum source count for each to be separate as well.

**Comment by Bulletbling** [comment]
> > We absolutely need this! Most tv shows are 720/1080p so my pre emptive 4K setting never applies to tv shows. I’d do 1080 pre emptive for tv shows. Venom does this very well iirc.
> 
> Seren already has separate pre-emptive termination resolution settings for movies vs TV shows, so you can use 4K for movies and 1080p for TV shows. My suggestion was for the minimum source count for each to be separate as well.

This is what I meant as well. 😀
