### ISSUE TITLE
[REQUEST] Show filesize when an autoplay source is found

### ISSUE THREAD

**Issue by oathzed** [nixgates/plugin.video.seren#275]
When you get an autoplay source, it shows the file name and stuff. Can you please also show how big the file it selected is also, that's pretty important on determining the quality it selected. Thanks :)

**Comment by nixgates** [comment]
This can be done, thanks for the suggestion 👍

**Comment by nixgates** [comment]
@oathzed ready in next update 👍

**Comment by oathzed** [comment]
> @oathzed ready in next update 👍

Right on. Thanks man

**Comment by nixgates** [comment]
@oathzed all done bud!

Closing it off :)

**Comment by oathzed** [comment]
> @oathzed all done bud!
> 
> Closing it off :)

Cheers! :)
