### ISSUE TITLE
[REQUEST] A way to revert Seren to the version right before 2.0

### ISSUE THREAD

**Issue by iscriptu** [nixgates/plugin.video.seren#276]
Hi,

Been having a lot of problems with 2.0 which is understandable considering how new it is but me and probably some other people don't want to deal with them.

That combined witb the fact 2.0 doesn't support Seren Full Theme makes it a big dealbrealer for me so I'd really appreciate it if you made a backup repo for people like me to be able to revert our versions or if something like that already exists, point it out for me.

Thanks

**Comment by drinfernoo** [comment]
While I don't recommend this in **any** way, as Seren 2.0 is far more robust and with vastly improved performance, you could just install from zip if you have to.

https://github.com/nixgates/nixgates/blob/master/packages/plugin.video.seren/plugin.video.seren-1.6.19.zip
