### ISSUE TITLE
[BUG: v2.0.6] cloud files not showing up at the top in the scrape results

### ISSUE THREAD

**Issue by LoganWolverineX** [nixgates/plugin.video.seren#278]
**Describe the bug**
Unable to scrape for files in my cloud even with the “inspect cloud files on scrape” enabled for RD and PM.  Not showing at the top of the scrape results.

**To Reproduce**
1. Have the episode or show pack in your cloud. 
2. pick the show and episode you are trying to watch. 
3. Look for CLOUD in the scrape results. 

**Expected behavior**
All the videos in my cloud should be shown at the top of the results under CLOUD. 

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren version 2.0.6

**Comment by nixgates** [comment]
@LoganWolverineX issue resolved will be provided next update (maybe an hour or so now)

**Comment by LoganWolverineX** [comment]
@nixgates thanks a lot! Much wanted resolution for this bug :).

**Comment by nixgates** [comment]
@LoganWolverineX 


Update has been released, please let me know if this fixes your issue!

**Comment by LoganWolverineX** [comment]
@nixgates just tested!!! i am soooo happy!!! PM cloud inspection works 100%.  More importantly, RD cloud inspection works 110% now!!!  That was a feature that failed to resolve upon clicking!!  Both works perfect now!!! Thank you so much!!!!

**Comment by nixgates** [comment]
@LoganWolverineX yay 2/2 for your issues!

Closing off!
