### ISSUE TITLE
Trakt Collection Order 2.0.6.

### ISSUE THREAD

**Issue by nutstool** [nixgates/plugin.video.seren#279]
Trakt Collection no longer appears in alphabetical order since update to 2.0.6. Could this be fixed, please? Many thanks for your ongoing work on this fantastic add-on.

**Comment by nixgates** [comment]
@nutstool you can fix this by disabling the pagination for the trakt collection. 

Seren Settings > Interface > Paginate Trakt Collection. 

I will create a new setting to separate the sorting and the pagination.

**Comment by UghtC** [comment]
The paginate also messed up the Collection area, as there was no "next page" choice.
This fixed it eventually after a complete reinstall and then finding this issue.

**Comment by jpgadbois** [comment]
I also have this issue.  Every time I uncheck "Paginate Trakt Collection" button I get the alphabetical sort back, but at some point it automatically reverts.  Using Seren 2.0.10

**Comment by nixgates** [comment]
@jpgadbois that was due to an issue with settings not sticking. Fixed in a previous update. 

In the coming update there's now separate options for paginating collection and the sort style. :+1:

**Comment by nixgates** [comment]
Fixed in 2952f86242bad8b21ab17e5b584fe8a3039f78e2
