### ISSUE TITLE
Providers Implementation Guide

### ISSUE THREAD

**Issue by ventsislav-georgiev** [nixgates/plugin.video.seren#28]
Is there a guide anywhere on how to write providers for Seren? What are the APIs that need to be provided, how the auto-update should work etc?

**Comment by nixgates** [comment]
I'll write some documentation on the implementation now for you and add it to this repository. 
It's about time I added some FAQ's and documentation.

**Comment by nixgates** [comment]
There is now documentation in the repository wiki outlining custom providers.

You can find it here - https://github.com/nixgates/plugin.video.seren/wiki/Custom-Providers

I'll try my best to continue to write documentation for the add as I go.
