### ISSUE TITLE
[BUG: v2.0.6] Pre-Scrapping Prior to Playing Next Dialog Popup Is not working

### ISSUE THREAD

**Issue by LoganWolverineX** [nixgates/plugin.video.seren#281]
**Describe the bug**
Prior to seren version 2, after an episode reaches x%, it usually starts scrapping for links for the next episode. So, by the time it reaches the “playing next” dialog, the links for the next episodes are done scrapping. It’s not doing it in version 2.0.6. After you click on “play” for “playing next dialog”, this is when it starts scrapping. 

**To Reproduce**
1. Watch one episode until near the end until the “playing next” dialog shows up
2. Click “play”
3. Scrapping has not begun, so it starts scrapping once you click “play” for the next episode. 

**Expected behavior**
Once you reach X% watched based on configured set value, the scrapping for links for the next episode should start prior to the “playing next” dialog. 

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - seren Version 2.0.6

**Comment by nixgates** [comment]
Is this a consistent issue or temperamental? 

Could I please ask for a log for this as well. If you want to quickly gather one, enable debug logging, start an episode, fast forward to over 80% of the episode and wait for roughly 2-3 mins.

That should be enough to get me what I need to investigate further

**Comment by LN13uLL** [comment]
For now, I’ve only noticed it once because it was just one episode I was watching. Let me get you a log shortly.

**Comment by nixgates** [comment]
Ok no worries, that's better than it continually happening. 

I'll keep an eye on it

**Comment by LN13uLL** [comment]
Thanks. I will keep an eye on it myself too.

**Comment by nixgates** [comment]
https://paste.ubuntu.com/p/9FnJRwbfRN/

**Comment by nixgates** [comment]
It appears Trakt timeouts/disconnections are breaking some of the player features. 

A workaround will be implemented but a full bodied fix will be required as well.

**Comment by LoganWolverineX** [comment]
@nixgates i just encountered it not marking episode as watched after % watched. Because it doesn’t Mark it as watched, up next never updated so I had to manual sync trakt which takes some time. Hopefully it doesn’t happen often. And hopefully you’re able put in that workaround Sooner than later. It would be an annoyance if I am binging a show and it happens frequently.

**Comment by StreamAntics** [comment]
yup same as the above, I thought the issue got resolved when I updated to 2.0.9 but seems to have started again after watching a couple of episodes on the most recent update, basically what I've found is if the smart play dialogue doesn't come up it won't mark the episode as watched.

**Comment by LoganWolverineX** [comment]
> yup same as the above, I thought the issue got resolved when I updated to 2.0.9 but seems to have started again after watching a couple of episodes on the most recent update, basically what I've found is if the smart play dialogue doesn't come up it won't mark the episode as watched.

Don’t think it’s related to that option. I use select source. I think it’s related to trakt disconnection but I don’t know if it is related to pausing/rewinding/fastforwarding. So far, when I don’t pause/rewind/fastforward it marks as watched fine after % watched. It might just be coincidence.

**Comment by StreamAntics** [comment]
> > yup same as the above, I thought the issue got resolved when I updated to 2.0.9 but seems to have started again after watching a couple of episodes on the most recent update, basically what I've found is if the smart play dialogue doesn't come up it won't mark the episode as watched.
> 
> Don’t think it’s related to that option. I use select source. I think it’s related to trakt disconnection but I don’t know if it is related to pausing/rewinding/fastforwarding. So far, when I don’t pause/rewind/fastforward it marks as watched fine after % watched. It might just be coincidence.

I also use source select, but have the smart play option enabled and set to pause if nothing selected, if I select play it will scrape the next episode and allow me to select a link....on the occasions that the dialogue doesn't appear with 30 seconds remaining in the stream, it'll play to the end (not pause as it should) take me back to my next episode screen, and not update trakt, essentially telling me I didn't watch it....one the rare occasion the smart play dialogue does show, the stream will pause at the end (as I have it set) when I back out will will update my next episode as it usually should. It might very well be as you say, but based on what I'm experiencing, it seems the issues are somehow linked

**Comment by LoganWolverineX** [comment]
@nixgates I think i found some new details maybe can help you pinpoint the issue. 

Replication steps:
1.  Binge watch any tv series that has at least a few unwatched episodes.
2.  scrape and watch the first unwatched episode normally
3. after watching % watched, it will get marked as watched like normally would
4. "playing next" will then pop-up X secs before episode ends like normal
5. next episode has been pre-scrapped normally
6. start the next unwatched episode
7. this is when it goes down hill.  nothing will be connected to trakt (so it seems) after link is resolved

If i exit Kodi, then restart Kodi, everything works again 1-6.  It seems something breaks going to the next unwatched episode after the initial unwatched episode finishes.  I also opened the trakt app when it would usually show the "check-in" of the stream.  the "initial unwatched episode" gets checked-in with trakt, but it seems like the playing next unwatched episode doesn't.  

I hope this will help pinpoint the issue.  I don't think it's a trakt disconnect issue.  I will continue to see if i can find any further details if this doesn't help.

**Comment by StreamAntics** [comment]
Had quite a few error pop ups today so grabbed another log for you to look at, I'm not sure if I'm showing you the same thing each time (these logs don't mean allot to me) so let me know if I'm wasting your time with these logs @nixgates 
https://paste.ubuntu.com/p/MgrdrXbPH5/

**Comment by nixgates** [comment]
@StreamAntics logs are always good bud!

Always feel free to throw them up lol

**Comment by nixgates** [comment]
Same issue as #308

Both should be resolved in the next update

**Comment by LoganWolverineX** [comment]
@nixgates thanks again!!!  you're squashing a lot of these bugs so quickly :) 🥇

**Comment by nixgates** [comment]
@LoganWolverineX haha need to get them out of the way

The issue should be resolved now in 2.0.10 👍

**Comment by StreamAntics** [comment]
Hey @nixgates have updated to 2.0.10 and have run through a couple of episodes, so far smart play is now working as it should, and my next up is being updated as well perfect!!! and here comes the not so good part (sorry) I noticed that the data doesn't show during the scraping process anymore, and the time remaining before smart play action no longer shows, I've attached some images, hopefully those come through...
![IMG_20210106_203518_resized_20210106_084031308](https://user-images.githubusercontent.com/76900356/103742671-15566c80-5060-11eb-8ffd-90887d6ee0cc.jpg)
![IMG_20210106_203534_resized_20210106_084031747](https://user-images.githubusercontent.com/76900356/103742699-21422e80-5060-11eb-8419-c2f93536beb8.jpg)
![IMG_20210106_203534_resized_20210106_084031747](https://user-images.githubusercontent.com/76900356/103742730-2c955a00-5060-11eb-87b6-3d7c3f1ef989.jpg)

**Comment by nixgates** [comment]
@StreamAntics hmm looks like an issue with the text highlight colour. Can you try set that to something and I'll quickly check it on my end.

**Comment by StreamAntics** [comment]
reset everything to default, and seem to have appeared (strange because I haven't changed anything) but that's all good seems to be fine after doing that....will keep testing and let you know if anything comes up...Thanks @nixgates you're a legend mate!!!

**Comment by nixgates** [comment]
@StreamAntics bother I should have asked what it was on so I know where the issue was. Next time it crops up I'll catch it lol

Alright closing this off!

**Comment by LoganWolverineX** [comment]
@nixgates I would like to also confirm this is now working perfectly. Nice work!!!
