### ISSUE TITLE
[BUG] Season items not displaying number of episodes

### ISSUE THREAD

**Issue by iscriptu** [nixgates/plugin.video.seren#282]
The ones I've noticed so far are, Trakt Manager isn't working for the most part, Continue Watching (TV Shows) is using episode artwork instead of season artwork, Continue Watching (Movies) is displaying watched and unwatched movie along with in progress movies and the episode number next to the season name in season view is displaying "None Episodes".

While I have you, I highly recommend and urge you to implement SerpentDrago's SerenFull "Next Up" and "Continue Watching" dialog pop ups. They're so much better than the current ones and shouldn't be too hard to incorporate. It would make a big difference.

**Comment by nixgates** [comment]
@iscriptu 

Could you expand on what is broken in Trakt Manager, mine is working as expected. Have you updated the context menu addon to 2.0?

By Continue Watching, I believe you mean the Finish Watching menu? That would be because those items are episode objects not seasons/shows.

The (Movie) Finish Watching is does not discriminate against items that are watched or unwatched. The menu only displays items that have a resume point, regardless of watched status. 

The None episodes is odd, I'll investigate it further though and modify this ticket to suit that issue.

I'll also raise a seperate request for the change to the Next Up, Continue Watching dialogs. Though just note, I'm currently focusing on bugs so it may take a bit for me to look into that :)

**Comment by iscriptu** [comment]
I did not see an update for context menu so no but the problem I encountered was it only worked with Seren widgets. Btw, the Trakt Manager I'm referring to is the one at the bottom of the Netflix Show/Episode/Movie Information View on Auramod in case that matters. I tried it with a couple of my MovieDB widgets and it gave me a Seren error.

In regards to the Finish Watching (Shows) using Episode artwork, this is something new and pre 2.0 Seren used show/season artwork which I really liked. Perhaps something you could add to settings?

About Finish Watching (Movies), it definitely didn't behave that way before. Even movies that are marked Watched are on that list. Even after I manually marked some as watched, they remained on that list. I understand that you made it so that anything with a resume point is on that list but even after I used Trakt Manager to manually remove playback progress, they remained on the list. Something isn't working right there and it really doesn't work for widgets (had like 20 movies on my Continue Watching veruses the 6 before updating).

That's everything I have to say, I hope everything works out. Good luck!

**Comment by nixgates** [comment]
@iscriptu the context menu addon will definitely need to be updated, please make sure that has been updated to 2.0.0

The Trakt Manager is a part of the context menu addon and is only available on Seren items. If the items are TMDBHelper addon items that will need to be fixed by TMDBHelper addon to work with the new version of Seren.

**Comment by iscriptu** [comment]
I see, I hope that they do that then. Might have to pay a visit go their GitHub.

In regards to adding a setting that makes episode item using tv show/season artwork, like pre 2.0, will you consider it or something similar?

Also, I really think you should check to see if Finish Watching (movies) is working correctly because even after I removed playback progress via Trakt Manager, they remained on the list. It isn't behaving properly.

**Comment by nixgates** [comment]
@iscriptu hey bud, I'm just going to close this off as a duplicate as the other ticket has a lot more information available.

Please check back to bug #310 to check for progress :)

**Comment by SerpentDrago** [comment]
> I did not see an update for context menu so no but the problem I encountered was it only worked with Seren widgets. Btw, the Trakt Manager I'm referring to is the one at the bottom of the Netflix Show/Episode/Movie Information View on Auramod in case that matters. I tried it with a couple of my MovieDB widgets and it gave me a Seren error.
> 
> In regards to the Finish Watching (Shows) using Episode artwork, this is something new and pre 2.0 Seren used show/season artwork which I really liked. Perhaps something you could add to settings?
> 
> About Finish Watching (Movies), it definitely didn't behave that way before. Even movies that are marked Watched are on that list. Even after I manually marked some as watched, they remained on that list. I understand that you made it so that anything with a resume point is on that list but even after I used Trakt Manager to manually remove playback progress, they remained on the list. Something isn't working right there and it really doesn't work for widgets (had like 20 movies on my Continue Watching veruses the 6 before updating).
> 
> That's everything I have to say, I hope everything works out. Good luck!

The Trakt manager BUTTON in auramods Info screen , works perfectly fine and ONLY even shows up for SEREN items . it will not work or even SHOW UP on tmdb helper items . so i have no idea what your on about . 

It never has , it never will , i know i helped develop the skin . Trakt manager button feature on netflix info in auramod is ONLY for seren items . period .  and it works fine there .

**Comment by iscriptu** [comment]
It shows up on my "Recommendations" TMDBHelper widget and works. I know because I use it to add shows/movies from my "Recommendations" to my watchlist. This didn't work in Seren 2.0 though.

**Comment by SerpentDrago** [comment]
Exactly what exact path in tmdb helper does it show up . cause it absolutely shouldn't and if it did , or even ever worked when it did , that itself is the bug . 

Trakt manager button DOESN"T work on non seren items , and shouldn't show , period . 

I'd like to know the exact path in tmdb helper your  using  for that widget that supposedly shows it on info screen.

**Comment by nixgates** [comment]
@SerpentDrago its the auramod skin

**Comment by SerpentDrago** [comment]
> @SerpentDrago its the auramod skin
> 
> Edit: ah see you've already noticed that

yeh i want to know the exact path of the tmdb helper widget , so i can replicate it , as every test i do , Trakt manager button does not show up on anything other then seren widgets , as it should be :)
