### ISSUE TITLE
[BUG] text highlight color selection is not working properly. When I select a color it doesn’t change to the one I picked. 

### ISSUE THREAD

**Issue by curtyman11** [nixgates/plugin.video.seren#285]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by nixgates** [comment]
Yep I can see what's going on, the new inherit feature is displacing the actual selection.  I'll bundle this one up with the next round of fixes.

**Comment by nixgates** [comment]
@curtyman11 this should be resolved in 2.0.8

**Comment by nixgates** [comment]
@curtyman11 could you please confirm this for me?

**Comment by curtyman11** [comment]
I can confirm that it’s working now. Thankyou for fixing it.

**Comment by nixgates** [comment]
@curtyman11 thanks for raising the issue :)
