### ISSUE TITLE
[BUG] Xbox one app won’t load. Stuck on 2.06

### ISSUE THREAD

**Issue by WheelMan3** [nixgates/plugin.video.seren#287]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by nixgates** [comment]
@WheelMan3 you will need to update to 2.0.7 for xbox support. 

Try checking for updates on the nixgates repo.

**Comment by WheelMan3** [comment]
> @WheelMan3 you will need to update to 2.0.7 for xbox support.
> 
> Try checking for updates on the nixgates repo.

Says the latest update is 2.6. I’ve tried reinstalling and that didn’t work either. Love you stuff man just want to get it working somehow haha But I really do appreciate everything!

**Comment by nixgates** [comment]
All good bud! 

Latest is 2.0.7, some people have had luck disabling the Nixgates repo and re-enbaling it to force an update check. Give that a go and let me know!

**Comment by WheelMan3** [comment]
> All good bud!
> 
> Latest is 2.0.7, some people have had luck disabling the Nixgates repo and re-enbaling it to force an update check. Give that a go and let me know!

Thank you so much that got it going. Can’t thank you enough.

**Comment by nixgates** [comment]
No worries 👍 

Have a good day!
