### ISSUE TITLE
[BUG] All TV Shows not loading

### ISSUE THREAD

**Issue by Daviddew89** [nixgates/plugin.video.seren#288]
Hi Nix. 

Thank you so much for Seren and the update. Been so excited waiting for it. 

Unfortunetly I am having issues with it on a Shield TV Tube and a laptop running libreelec. Kodi Versions 18.9. Both devices are using separate trakt and real debrid accounts.

I have uninstalled and started fresh with both devices.

1. Installs fine
2. Syncs with trakt fine
3. Sync with Real debrid accepts and then throws error.

Shield TV Log:
https://paste.ubuntu.com/p/Xz8SBpQPkC/

Libreelec Laptop Log:
https://paste.ubuntu.com/p/WBBpPNccYm/

 - Kodi Version [18.9]
 

Update:

It is working with finding links etc. There are a few more errors:

1. Under Accounts the real debrid username is blank even though it's seems to have synced.

2. TV Show Widgets are causing errors. This is only after the real debrid sync.

Libreelec Log:
https://paste.ubuntu.com/p/z63SG5pbq9/

**Comment by nixgates** [comment]
@Daviddew89 mind if I ask what version of Seren you initially installed? Just trying to work out if this is an issue from pre 2.0.6 or not.

**Comment by Daviddew89** [comment]
Hi Nix.

I have been through each update you have released. Just tried 2.0.7 and same issue remains.

I should include that I have fully installed and reinstalled using 2.06.

As it stands the issue remains. I can access Next Up however so I am watching through there currently.

**Comment by nixgates** [comment]
Ok I can see this issue is related to another one, I'm going to link this issue to that one and close this off. Follow the progress over here :) 

Duplicate #273

**Comment by Daviddew89** [comment]
Thanks Nix!! You are brilliant mate. Appreciation.
