### ISSUE TITLE
[BUG] unable to download scrapers every time I type the address to add the scraper it just keeps booting back to the menu screen.

### ISSUE THREAD

**Issue by WheelMan3** [nixgates/plugin.video.seren#289]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by nixgates** [comment]
Can you please provide a log of the issue so I can see what's happening

**Comment by WheelMan3** [comment]
I am sorry I am relatively new I am unfamiliar with how to find a log file?

**Comment by WheelMan3** [comment]
> Can you please provide a log of the issue so I can see what's happening

Sorry I am relatively new, how do I find a log file?

**Comment by nixgates** [comment]
Not a problem, easiest method to do this is to install the log uploader addon from the kodi repository. 

Run that addon and it will give you a link to paste here :)

**Comment by WheelMan3** [comment]
> Not a problem, easiest method to do this is to install the log uploader addon from the kodi repository.
> 
> Run that addon and it will give you a link to paste here :)

I’m on my Xbox though. I can’t play some thing from my Xbox through my phone which I’m using for this thread if that makes sense. I’m sorry I’m making this super complicated!

**Comment by WheelMan3** [comment]
> Not a problem, easiest method to do this is to install the log uploader addon from the kodi repository.
> 
> Run that addon and it will give you a link to paste here :)

I’m not sure why but I just kept typing it in over and over again and it finally worked at like the sixth try! Thanks for the help.

**Comment by nixgates** [comment]
No worries have fun!
