### ISSUE TITLE
[BUG 2.0.6/2.0.7] Restoring From OpenWizard Causes Errors

### ISSUE THREAD

**Issue by LoganWolverineX** [nixgates/plugin.video.seren#290]
**Describe the bug**
Prior to version 2.x, backing up Kodi using OpenWizard, then restoring it had no errors.  Post 2.x release, I backed up a new backup using OpenWizard.  After restoring Kodi using OpenWizard, Seren gets all these errors.  After reinstalling over the Seren addon, it works okay again.  I recall this happening to another addon (remains unnamed), but their dev was able to make some sort of modifications where it restores okay with OpenWizard.  I can only assume it was due to updating code from python2 to phython3 (don't quote me on it).

**To Reproduce**
1. Be sure to have OpenWizard addon installed.
2. Make sure you have you have at least Seren 2.0.6 or 2.0.7 installed
3. Create a backup zip for Kodi using OpenWizard
4. Restore Kodi using OpenWizard
5.  Start up Kodi after restore is complete and it asks you to close and reopen Kodi.  Once skin finishes rebuilding, you'll see Seren throwing errors. (reinstalling Seren over the top of the addon fixes it)

**Expected behavior**
Upon restoring Kodi using OpenWizard, Seren should work without any errors

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren Version 2.0.7

Log Attached Below
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/5761212/kodi.log)

**Comment by drinfernoo** [comment]
Not really an issue for Seren, as it's OpenWizard that's modifying files here 🤔

**Comment by nixgates** [comment]
I'll look into when I get a chance but will be on the back burner for a few days while we punch out some of these other issues. 

Not forgotten, but just not critical 👍

**Comment by LN13uLL** [comment]
I really appreciate it, @nixgates !  Thanks for following up.  just wanted to make sure you were aware of it.  

i agree it is not as critical as i can just reinstall over the addon when i restore in the meantime until you're able to look into it.  there's def other bugs that are more higher priority for sure.

**Comment by LoganWolverineX** [comment]
@nixgates i was able to pull a shorter log for this issue that I think may help explain the problem or maybe not.

I know it's a low priority.  But something extra that maybe helps you out later.

Log:  
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/5826943/kodi.log)

**Comment by nixgates** [comment]
@LoganWolverineX yea I can see what's happening here. 

Looks like OpenWizard is ignoring the cache module due to its name. This needs to be fixed in OpenWizard. It should be detecting the file type to make sure its not a python module. 

From what I know, I believe OpenWizard is a dead project?

**Comment by LoganWolverineX** [comment]
@nixgates yeaaaaa... it’s a dead project... :-(

no one is wanting to takeover the addon lol. I guess it’s understandable. As it would be a pain in the arse to get it rewritten to python 3. 

It’s such a good backup tool addon. Thanks for looking at the log file. At least we know for sure now it’s openwizard that’s causing the problem. I’m assuming it will soon have more issues as other addons get updated to python3.

**Comment by nixgates** [comment]
Yea it will, the issue here is it thinks the cache.py file is the actual cache but its the logic to drive the cache

Gonna close this one off :)
