### ISSUE TITLE
[BUG] Downloads not supporting NFS directories

### ISSUE THREAD

**Issue by greenmr** [nixgates/plugin.video.seren#291]
I can't get the new download feature to work. I have several download locations I use with Venom and The Crew. One is a locally attached FAT32 USB thumb drive. Another is an external USB hard drive attached as an NFS source via my main Asus access point. A couple of others are SMB shares on Windows PCs on my LAN. All of them work fine as download targets for The Crew and Venom.

In the new Seren (2.0.6/2.0.7) settings I have tried selecting folders on each of those locations as the download target, but no matter where I try to put the downloads Seren doesn't actually perform the download even though I get a message that the download has started.

Here is what I do...

1. Search for something to download.
2. Pick a stream from the results.
3. Long press for the context menu and select "Download".
4. Click Ok on the next popup.
5. Seren pops up a message saying "Download task started".
6. I click Ok.
7. Seren just sits there doing nothing no matter how long I wait.
8. I go back to the Seren Tools menu and select "Download Manager"
9. Seren pops up a screen with no entries on it, just a menu on the right side with options "Cancel Task", "Clear Completed", and "Close"
10. Inspecting the target location with Total Commander or Windows Explorer shows that no files were downloaded and no folders were created.

If I just click on the same stream instead of trying to download it then it plays fine. There are no error messages, it just doesn't do anything after it says the the download is starting.

[Kodi log](https://paste.kodi.tv/vifemapola) for attempt to download from Seren to an SMB share.

**Comment by NoFear99354** [comment]
It's doing the same for me.

**Comment by SUroot** [comment]
I can also confirm that this is occurring on NVidia Shield TV using the latest Kodi stable. It will work when it is set to the default location, but any external device works exactly as the OP has stated.

**Comment by nixgates** [comment]
@SUroot thanks for that info, that's what I had suspected to be the case but had not been able to confirm it.

I'll make the necessary changes and get back to you with an update soon guys.

**Comment by SUroot** [comment]
> @SUroot thanks for that info, that's what I had suspected to be the case but had not been able to confirm it.
> 
> I'll make the necessary changes and get back to you with an update soon guys.

No worries @nixgates - let me know if you need me to supply anything further.

Thanks for all your hard work.

**Comment by matthewheimberger** [comment]
@nixgates I was able to get down load to SMB by editing the settings xml and using this. <setting id="download.location">smb://user:password@computername/Kodi/Downloads/</setting>

I also noticed that the default was set to userdata and not masterprofile. I believe by using userdata will map to Roaming nd not Local which is not correct path on win 10.
