### ISSUE TITLE
[BUG] Scraper Display Style - List Option Missing

### ISSUE THREAD

**Issue by sheen73** [nixgates/plugin.video.seren#292]
Scraper Display option "List" is missing. Only fancy and background option existing.
Under setting>Scraping>General - Scraper Display Style
Kodi 18.9

I use Aeon MQ8 skin and the text is sized incorrectly on fancy so I cant really see information that's why I use list.

**Comment by nixgates** [comment]
I'm not sure what you mean, Seren has only ever provided a Background or fancy?

**Comment by nixgates** [comment]
I'm closing this issue as I've not heard back from yourself @sheen73 

If you feel this is in error, please re-open the ticket :+1:
