### ISSUE TITLE
[BUG] Reporting multiple bugs/issues + Question(s)

### ISSUE THREAD

**Issue by Dealz-416LS** [nixgates/plugin.video.seren#295]
[kodi.log](https://pastebin.com/2UUd2Bwc)

**Describe the bug**
1. Recently Watched (TV) not loading, gives a Seren error.
2. My Watched Movies not updating.
3. Settings for Seren are reverting back after being changed.
4. Have to press back multiple times (3x) to return to homescreen from a homescreen widget or homescreen submenu item.
Before 2.0 I could select a homescreen widget or homescreen submenu item then hit back once 1x to return to the homescreen.
5. Rating TV Shows and Movies at the end of playback doesn’t work, the dialog box to submit a rating (Trakt) freezes/gets stuck becomes unresponsive.

**To Reproduce**
1. My Shows > Recently Watched > error
2. My Movies > My Watched Movies > not updating
3. Not sure what is causing setting to revert.
4. Homescreen widget or homescreen submenu item > press back 1x (still on same screen, screen appears to just reload) > press back 2x (Seren’s main menu - Discover Movies, Discover TV shows, My Movies etc) > press back 3x (back to the homescreen).
5. End of playback > Trakt dialog box is displayed > unresponsive not able to move left and right to choose rating or confirm rating with OK, have to press back to dismiss dialog box so unable to rate.

**Expected behavior**
1. Recently Watched items should load.
2. My Watched Movies should update to display current Trakt data.
3. Saved settings shouldn’t revert.
4. Behaviour prior to 2.0 pressing back 1x takes you back to the homescreen from a homescreen widget or homescreen submenu item.
5. Should be able to move left and right to choose rating then OK to confirm.

**Screenshots**
N/A

**Kodi & Add-on Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren Version 2.0.7
 - Arctic Horizon 0.5.55

**Additional context**
_Bug 5. additional info this issue, prior to 2.0 rating dialog worked fine intermittently, sometimes it worked other times the rating dialog box would display and be immediately unresponsive or became unresponsive after interacting with the dialog box._

_Movie rating dialog didn’t work at all before 2.0_

_In 2.0 both TV Shows and Movies dialog work but are both unresponsive when the dialog box is displayed._

**Question(s)**
What’s does the setting “Metadata Location” mean/do? Would it be beneficial to switch it to Trakt? Instead of the default TMDb.

**Comment by nixgates** [comment]
Can you please get me a log, it sounds like you background service is failing and causing issues. This is likely causing your settings to revert as well.

Some of your issues could also be related to #237 which I have a update to cover in a minute.

I'm not sure your Trakt dialog is covered under our issues but I'll investigate it.

**Comment by Dealz-416LS** [comment]
Here is the Log
https://pastebin.com/2UUd2Bwc

Quick question: 
What’s does the setting “Metadata Location” mean/do?

**Comment by Dealz-416LS** [comment]
Update 1# 

I was able to fix Issue 1 and 2 by re-building the Trakt database. 

I did force a sync with Trakt when I first experienced the bugs but I guess that wasn’t enough.

however I’m still getting Seren errors when starting Kodi or Reloading Skin.

**Comment by Dealz-416LS** [comment]
**Update 2**

My bug report 4. Which looks to be these issues #299 and #305 should be fixed in the next update according to your comment @nixgates

**Comment by nixgates** [comment]
@Dealz-416LS could I ask for a log for that specific error (reloading skin or startup)

In regards to Metadata location, this is the location Seren will try to use for it's meta data. Setting this to Trakt can provide some speed boosts as it means less data is required to be fetched (artwork only) from other meta providers.

TVDB can be slow while TMDb provides a nice all rounded experience hence the default setting 👍

**Comment by Dealz-416LS** [comment]
@nixgates 

Bugs 1. (I assume 2. as well) have happened again, I caught the moment it broke in the log. (Seren error popped up then Recently Watched TV no longer loads) 
[kodi.log1](https://pastebin.com/VnmCk9v9)

Closed and reopened Kodi
Rebuilt Trakt database to temp fix reoccurring issue above.
Confirmed I could load Recently Watched 👍
Done a skin reload
Didn’t see a Seren error popup (could have missed it).
[kodi.log2](https://pastebin.com/vkqFaamp)

Closed and reopened Kodi
Didn’t see any Seren error popup
[kodi.log3](https://pastebin.com/u3fcn2Qj)

**Comment by nixgates** [comment]
@Dealz-416LS 

Sounds like they are all the same issue which is quite possible. 

The errors in your log are the same as the issue #316

There is a fix rolling out in the next update, lets see if all your errors are fixed after this one is done

**Comment by Dealz-416LS** [comment]
@nixgates Thanks I’ll see how it goes after the next update.

**Comment by Dealz-416LS** [comment]
@nixgates I am going to go ahead and close this, currently on 2.0.9 and everything so far is fine, no Seren error pop ups or widgets etc failing to load.

Bugs 1. & 2. Not happened in 2.0.9 hopefully fixed.
Bug 3. Not experienced this in a while.
Bug 4. Fixed with 2.0.9
Bug 5. I’ll open new issue if this one persists, not sure if this a Seren issue or Trakt add-on issue.

**Comment by Dealz-416LS** [comment]
@nixgates bug 5. is a skin issue, I got help from Razzeee on the Trakt Script github and after a quick test it's confirmed as an issue with the skin I'm using.
