### ISSUE TITLE
[REQUEST] Seren Spanish Translation/Traducción al Español de Seren

### ISSUE THREAD

**Issue by XAT9393** [nixgates/plugin.video.seren#296]
Hi, sorry to bother you but I finished the translation. Uploaded it here https://github.com/XAT9393/plugin.video.seren.es

Ran into a problem because I have 0 coding knowledge. I see everything is coded in UTF-8 and spanish uses special characters in the UTF-8 C1 Controls and Latin1 Supplement.

Don't know if this is enabled or do I have to write something else in the language pack, for example

Discover Movies = Descubrir Películas 

The latin small letter I with acute is used here. But I don't know how to code it into the package. Do I need to write it as 237, 00ED or &iacute;

Currently it's not displaying in Kodi and comes up as Descubrir Pelculas.

Thank you for all your hard work!

**Comment by XAT9393** [comment]
Got it working now. Language resource available at: https://github.com/XAT9393/plugin.video.seren.es

**Comment by nixgates** [comment]
@XAT9393 you're a legend! 

Will be available in next update!

**Comment by XAT9393** [comment]
Awesome. Will probably keep a thread open for people who find errors or suggest a better or clearer translation.

**Comment by jweinreich** [comment]
Great work! but wait, how do I apply this?

**Comment by XAT9393** [comment]
Change your Kodi interface language to Spanish:
Settings>Interface>Regional>Language

Cambia el idioma de Interfaz de Kodi
Ajustes>Interfaz>Regional>Idioma

**Comment by XAT9393** [comment]
@nixgates The parent folder for the .po file is named as `resources.language.es_ES` instead of `resource.language.es_ES`
So it's not loading

**Comment by nixgates** [comment]
Shit, I'll fix this up in the next push

**Comment by XAT9393** [comment]
No worries mate. Thank you for letting me contribute! 👌🏼

**Comment by XAT9393** [comment]
Hey @nixgates don't know where else to contact you. Have been playing around with the add-on and tweaking it to run on matrix to see if I could run into some bugs. 

Was trying to load the Most Popular from Shows and got this error. Don't know if it's because it's running on Matrix or something else

https://paste.kodi.tv/wipufasuje

**Comment by nixgates** [comment]
@XAT9393 hey bud, if you are still having the issue on 2.0.10, can you please check the other tickets, if one doesn't match please raise a new one.

Your language pack is now and working so I'm gonna close this off :)

**Comment by cbecerraf** [comment]
Hey @nixgates, just wanted to point out a small issue, the strings.po file for the spanish translation has a small typo, it's missing the last 's' (string.po) so it's not working right now.

Also, I noticed that this translation would work just fine for different region spanish translations available in Kodi (es-MX for example), so it might be useful for spanish speaking people from that region to have this translation available in a resource.language.es_MX folder too

**Comment by nixgates** [comment]
@cbecerraf apparently I'm useless lol!

Ok ill fix this up today and add the second language as well. Pray tell I can spell this time
