### ISSUE TITLE
[BUG] Path for widgets missing trailing / which causes issues with back path

### ISSUE THREAD

**Issue by arcsur** [nixgates/plugin.video.seren#298]
When integrating with widgets, the path does not have a trailing slash after plugin://plugin.video.seren action path.  This causes issues with Kodi knowing how to go back.  Without the trailing / it goes to the previous screen within seren plugin and not the actual previous screen.

This issue is very apparent when using script.skinshortcuts which is integrated with many skins.  The back button does not go back to the prior screen but instead goes to the prior screen in seren addon.

The path produced when browsing the plugin with a skin using script.skinshortcuts will produce something similar to:
`plugin://plugin.video.seren?action=showGenresGet&action_args=action&from_widget=true`
Instead of a path which would allow a proper back function similar to the following:
`plugin://plugin.video.seren/?action=showGenresGet&action_args=action&from_widget=true`

Looking at the code, you already do widget detection, I would propose the following change which works without error in my testing inside modules/globals.py create_url function:

```
    def create_url(self, base_url, params):
        if params is None:
            return base_url
        if "action_args" in params and isinstance(params["action_args"], dict):
            params["action_args"] = json.dumps(params["action_args"], sort_keys=True)
        params["from_widget"] = "true" if not self.is_addon_visible() else "false"
        sep = "/" if not self.is_addon_visible() else ""
        return "{}{}?{}".format(base_url, sep, tools.urlencode(sorted(params.items())))
```

This change simply adds the path separator if this is from a widget which allows widget path back path to work correctly whilst avoiding filling the logs full of errors for inputstream adaptive path errors.

**Comment by nixgates** [comment]
Ah seems like there was a failure on my part with the string format. 

To be honest, I would have pulled my hair out catching this.

I'll make sure this is pushed with the next update.

By the way, if you get a chance, would you mind dropping me a message on reddit?

**Comment by SamDW96** [comment]
Duplicate of #298

**Comment by nixgates** [comment]
Fix applied, awaiting update

**Comment by nixgates** [comment]
@SamDW96 
Update has been released, please let me know if this fixes your issue!

**Comment by LoganWolverineX** [comment]
@nixgates i just tested this one since I noticed it and it works from widgets?  Will this be fixed for submenu / category shortcuts? I noticed this happening for submenu / category shortcuts too. I apologize if there was another bug item for that.

**Comment by nixgates** [comment]
> @nixgates i just tested this one since I noticed it and it works from widgets.   Will this be fixed for submenu / category shortcuts? I noticed this happening for submenu / category shortcuts too. I apologize if there was another bug item for that. 

Is it still an issue?

Are they fed from the skin? In theory this should apply to an item fed from the skin but I could be wrong.

**Comment by LoganWolverineX** [comment]
For submenu/category widget shortcuts, i'm still having issues with that.  i'm using the Aura skin.  the submenu shortcuts are using scripts.skinshortcuts.  Let me know if you would like a log for that.  I can provide it.

**Comment by LoganWolverineX** [comment]
@nixgates 

did a little bit more testing with this issue.  it works perfectly for the watchlist and collection for tv shows widget.  

But it doesn't work for trending for tv shows (as an example) widget.  Not sure how trending is different from watchlist and collection for tv shows.  Could it be that watchlist and collection is in "my shows" vs "discover tv shows"?  Seems like it's not working in "discovery tv shows" but it works for stuff under "my shows".  Hope that helps pin point something.

**Comment by arcsur** [comment]
@LoganWolverineX Have you tried re-creating the shortcuts?  If skin shortcuts stored the old generated path with the missing / you will get the old behaviour.  The fix changed the generated URL to include the trailing / but won't update your old skin shortcuts.

@nixgates Fix seems to be fine for me.

**Comment by nixgates** [comment]
@arcsur ah good call, skin shortcuts is likely using the old generated URLs prior to the fix if they were recently set up.

**Comment by LoganWolverineX** [comment]
Thanks @arcsur! I will give that a try! :)
