### ISSUE TITLE
TV Show artwork

### ISSUE THREAD

**Issue by mgonzales71** [nixgates/plugin.video.Seren#3]
Quick question / feature request...

But first wanted to say brilliant script and I personally am very thankful and appreciate this - been testing since I saw the post on reddit and works pretty good once I got real-debrid and trakt to register properly.

anyway back to the request for consideration...

It would be awesome for the script to set TV Show artwork (specifically clearlogo and clearart) when playing TV Shows - so I thank you for considering this feature. 

Thanks and thanks again!

Mario

**Comment by mgonzales71** [comment]
oh and was curious what omni connect is...  I can't seem to find mention of or find a download of the script script.module.omniconnect other then in your code :)  

thanks again!

**Comment by nixgates** [comment]
OmniConnect is a seperate add-on that provides multi-year RD  streaming.

It is still very very alpha at the moment so unlikely to see it anytime soon.

Fanart API is currently in the lower priority list but will be included in a future update therefore providing requested clear art.

I'm closing this issue as technically it's not an issue, but keep an eye on the updates as clear art will be provided in the near future.

**Comment by mgonzales71** [comment]
@nixgates noticed an issue with add on not handling trakt,.tv;s api.trakt.tv being down or spotty.

not many folks know about http://status.trakt.tv/  maybe you can handle trakt.tv outtage better or at the very least check api status and present to the average user what is causing nothing to show up in TV but movies seem to be "ok".

just a suggestion :)
