### ISSUE TITLE
A couple of issues since Seren 2.0 -

### ISSUE THREAD

**Issue by StreamAntics** [nixgates/plugin.video.seren#300]
Sorry to add more problems, but I have a couple issues since the  Seren 2.0 update (and now 2.0.8)

Firstly Orion no longer seems to scrape TV shows, it works perfectly when scraping a movie, but doesn't seem to activate for tv shows, was working fine prior to the 2.0 update.

And secondly I have this strange issue where I have the "enable playing next dialogue" setting enabled with a minimum of thirty seconds, and default action to pause if nothing selected, but if I let an episode run through to the very end of the stream without intervention, I get no next episode pop up 30 seconds in advance, and the stream doesn't pause at the end, like it used prior to the 2.0 update, rather it takes me back to the next up page (using auramod build) and doesn't mark the episode as watched, it acts like I didn't watch it at all.

I'm unsure if these are bugs, or some new settings I need to enable that I haven't.

Thanks!

**Comment by StreamAntics** [comment]
update: I think the issue with items not being marked of trakt may be an autowidget issue, I believe there may be an update coming in the near future to address this. so that just leaves me with the smart pop up issues and orion not scraping series problem.

**Comment by nixgates** [comment]
Orion I unfortunately can't help with, they will need to update their provider package to support 2.0

I'm currently investigating the issue with the player background monitor in a separate issue #315 

If you wouldn't mind following along on that one and if possible drop me a log there that would be most appreciated :+1:

**Comment by nixgates** [comment]
Apologies @StreamAntics the correct ticket is #281

I've added your log to that ticket, which btw,  helped greatly. Should help me get the issue sorted.

**Comment by StreamAntics** [comment]
ah excellent thanks @nixgates you're doing great mate keep up the fantastic work.

**Comment by StreamAntics** [comment]
For anyone else that's been having issues with episode torrents not scraping with Orion inside of Seren 2.0, I have had confirmation from Orion that an update has been put in place (I've tested and now working as normal) so If you are currently having that issue please update to Orion provider version 4.1.0 and that should resolve your issues
