### ISSUE TITLE
[REQUEST] Skip Intro

### ISSUE THREAD

**Issue by sathish804** [nixgates/plugin.video.seren#301]
**Is your feature request related to a problem? Please describe.** No
A clear and concise description of what the problem is. 

Please add the feature to skip the initial x number of seconds when a source starts playing like the one from Kaito based on the Seren source. 

**Describe the solution you'd like**

At the start of the video show a next up kind of dialog showing skip intro option. 
On click of the skip intro button video will auto forward by the x number of seconds configured in settings of the Seren. 
If skip intro is not selected after the x number of the seconds of the skip intro settings close the skip intro dialog. 

**Describe alternatives you've considered**

**Additional context**
![Screenshot_20210103-105216](https://user-images.githubusercontent.com/14090242/103475931-d9967b00-4db1-11eb-9973-e916424c2209.jpg)
![Screenshot_20210103-105238](https://user-images.githubusercontent.com/14090242/103475937-de5b2f00-4db1-11eb-9082-eb8285ddb5f7.jpg)

**Comment by sathish804** [comment]
@nixgates please consider this feature request for adding in Seren

**Comment by drinfernoo** [comment]
How could we know how far to skip? Every show has a different length intro, and often it's even different between different episodes.

**Comment by sathish804** [comment]
> How could we know how far to skip? Every show has a different length intro, and often it's even different between different episodes.

Thats true but a quick jump of configured number of seconds from settings say around 80 seconds will be ideal.

**Comment by drinfernoo** [comment]
Well, not necessarily. What about shows with cold opens? What about different rips that cut off or have extra time at the beginning? There's a lot of variables here.

**Comment by inb4after** [comment]
@sathish804 Test out both of these PR and see which one you like best.

**Comment by sathish804** [comment]
> @sathish804 Test out both of these PR and see which one you like best. No guarantees it will be added by Nix.

Could you please share the download link for the addon zip for the above 2 features

**Comment by inb4after** [comment]
> > @sathish804 Test out both of these PR and see which one you like best. No guarantees it will be added by Nix.
> 
> Could you please share the download link for the addon zip for the above 2 features. I liked the second option #490.

Add my repo source "https://inb4after.github.io/packages" to your file manager and install the repo zip. Then to to Seren and press update and choose the version you wish you update to. After testing you can return to official Seren in the same update menu but choosing Nixgates instead.

**Comment by sathish804** [comment]
> > > @sathish804 Test out both of these PR and see which one you like best. No guarantees it will be added by Nix.
> > 
> > 
> > Could you please share the download link for the addon zip for the above 2 features. I liked the second option #490.
> 
> Add my repo source:
> 
> `https://inb4after.github.io/packages`
> 
> ...to your file manager and install the repo zip. Then go to Seren addon, press update and choose the version you wish you update to.
> 
> After testing you can return to official Seren in the same update menu but choosing Nixgates instead.

@inb4after  I tested both the versions #489 is working. #490 is not working and throwing Seren error.

**Comment by inb4after** [comment]
> > > > @sathish804 Test out both of these PR and see which one you like best. No guarantees it will be added by Nix.
> > > 
> > > 
> > > Could you please share the download link for the addon zip for the above 2 features. I liked the second option #490.
> > 
> > 
> > Add my repo source:
> > `https://inb4after.github.io/packages`
> > ...to your file manager and install the repo zip. Then go to Seren addon, press update and choose the version you wish you update to.
> > After testing you can return to official Seren in the same update menu but choosing Nixgates instead.
> 
> @inb4after I tested both the versions #489 is working. #490 is not working and throwing Seren error.

Need a log file

**Comment by sathish804** [comment]
@inb4after please find the log here https://controlc.com/b9e2340e

**Comment by inb4after** [comment]
> 
> 
> @inb4after please find the log here https://controlc.com/b9e2340e

Is the error consistent every time?

What are your skip intro settings?

Can you test on a non-android device?

**Comment by inb4after** [comment]
> 
> 
> @inb4after please find the log here https://controlc.com/b9e2340e

NVM, I reproduced the bug, caused by having Auto Playlist Creation disabled. SkipIntro does ask for next item information similar to the other dialogs but I need to add a check to prevent this. Do you get similar errors when PlayingNext or StillWatching dialogs are enabled?

**Comment by inb4after** [comment]
@sathish804 New version is up and ready for testing. 

Navigate to the following path:

`/storage/emulated/0/Android/data/tv.wonderbox.www/files/.kodi/addons`

...and delete `plugin.video.seren-2.0.16 BetterSkipIntro` using a file manager app.

Then check for updates on my repo and go back to Seren's Update menu as before.

**Comment by inb4after** [comment]
@sathish804 V2 is up, added customizable delay to wait before opening the dialog (0-180 seconds).

**Comment by sathish804** [comment]
> @sathish804 V2 is up, added customizable delay to wait before opening the dialog (0-180 seconds).
> 
> The master version also has all my feature modifications in one place, just added both skip methods to it.

Niw it worked!! One improvement, give the option to enable and disable auto close the dialog. For some titles intro starts after x minutes current 30 seconds auto close after option won't be helpful in those cases.

**Comment by inb4after** [comment]
> > @sathish804 V2 is up, added customizable delay to wait before opening the dialog (0-180 seconds).
> > The master version also has all my feature modifications in one place, just added both skip methods to it.
> 
> Niw it worked!! One improvement, give the option to enable and disable auto close the dialog. For some titles intro starts after x minutes current 30 seconds auto close after option won't be helpful in those cases.

That's what the open dialog after x seconds is for

**Comment by sathish804** [comment]
> > > @sathish804 V2 is up, added customizable delay to wait before opening the dialog (0-180 seconds).
> > > The master version also has all my feature modifications in one place, just added both skip methods to it.
> > 
> > 
> > Niw it worked!! One improvement, give the option to enable and disable auto close the dialog. For some titles intro starts after x minutes current 30 seconds auto close after option won't be helpful in those cases.
> 
> That's what the open dialog at x seconds is for

Thank you!!  Can you make it as a separate program addon so that it can be used irrespective of the addon being used.

**Comment by inb4after** [comment]
> > > > @sathish804 V2 is up, added customizable delay to wait before opening the dialog (0-180 seconds).
> > > > The master version also has all my feature modifications in one place, just added both skip methods to it.
> > > 
> > > 
> > > Niw it worked!! One improvement, give the option to enable and disable auto close the dialog. For some titles intro starts after x minutes current 30 seconds auto close after option won't be helpful in those cases.
> > 
> > That's what the open dialog at x seconds is for
> 
> Thank you!!  Can you make it as a separate program addon so that it can be used irrespective of the addon being used. 

No can do due to time and knowledge limitations. I'm sure others already exist, for example [aenemapy's skip intro](https://github.com/aenemapy/aenemapyrepo) or [script.skip.intro](https://github.com/SLiX69/script.skip.intro).

**Comment by sathish804** [comment]
@inb4after I tried that but its not working so I asked for it.

**Comment by inb4after** [comment]
> @inb4after I tried that but its not working so I asked for it. 

Perhaps Realizer doesn't send the required title metadata to the player. Have you tested aenemapy's skip intro addon using Seren?

What about the second addon I sent?

**Comment by sathish804** [comment]
> > @inb4after I tried that but its not working so I asked for it.
> 
> Perhaps Realizer doesn't send the required title metadata to the player. Have you tested aenemapy's skip intro addon using Seren?
> 
> What about the second addon I sent?

I tried both of them with Seren only but none of them skipping the intro.

**Comment by inb4after** [comment]
> > > @inb4after I tried that but its not working so I asked for it.
> > 
> > Perhaps Realizer doesn't send the required title metadata to the player. Have you tested aenemapy's skip intro addon using Seren?
> > 
> > What about the second addon I sent?
> 
> I tried both of them with Seren only but none of them skipping the intro. 

I'm not sure how it works, but did you set the correct time to skip from and duration for each show you watch?
