### ISSUE TITLE
[BUG] Preemptive termination broken in v2

### ISSUE THREAD

**Issue by sathish804** [nixgates/plugin.video.seren#303]
**Describe the bug**
Preemptive termination in scrapping is broken.

I see that preemptive termination in scrapping is broken.

I have set preemptive termination with Minimum 4, 4k sources but it didn't on version 2.0.6. Below are the screen shots for the same.

https://iili.io/Kv8kQf.jpg

https://iili.io/Kv88B4.jpg

 

**To Reproduce**
Enable preemptive termination. 
Try to watch any movie wich meets the preemptive termination criteria. 

**Expected behavior**
Scrapping has to terminate once the preemptive termination criteria met. 

**Screenshots**

https://iili.io/Kv8kQf.jpg

https://iili.io/Kv88B4.jpg

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - version 2.0.8

**Additional context**

**Comment by henryjfry** [comment]
Are you saying it should be terminating but isnt?
Im getting the opposite problem, its terminating too early.  It therefore is not picking up a bunch of good sources because it decides it already has enough even though it hasnt yet found 5 different 4K sources.

Add in that the rescrape option doesnt appear to work means that when it does terminate too early I cant tell it to rescrape as it just returns the same results again with no actual rescrape happening.

**Comment by sathish804** [comment]
> Are you saying it should be terminating but isnt?
> Im getting the opposite problem, its terminating too early. It therefore is not picking up a bunch of good sources because it decides it already has enough even though it hasnt yet found 5 different 4K sources.
> 
> Add in that the rescrape option doesnt appear to work which means that when it does terminate too early I cant tell it to rescrape as it just returns the same results again and again, with no actual rescrape happening.

Yes its not terminating for me. May be its because you enabled Adaptive termination which might be terminating the scrapping before othet preemptive termination criteria is met.

**Comment by henryjfry** [comment]
Well I don't have any adaptive sources, at least I don't think so (nothing like Netflix or Disney+).
And I'm also pretty sure I disabled that option anyway.

I've already reverted to a pre 2.0 version though. Some other issues I was able to find workarounds for but I couldn't trust the results so I'll stick with a version I know works for now.

**Comment by sathish804** [comment]
@nixgates  I tested this issue in 2.0.13 and it's not resolved yet.
. 
![Screenshot_20210117-002445](https://user-images.githubusercontent.com/14090242/104827114-c9bf7200-585a-11eb-8fe9-a7bfc2082909.jpg)
![Screenshot_20210117-002536](https://user-images.githubusercontent.com/14090242/104827117-cfb55300-585a-11eb-8f2e-41d7c345d174.jpg)

**Comment by nixgates** [comment]
@sathish804 thanks for the settings image! This will help me recreate it! I'll work on it today :+1:

**Comment by sathish804** [comment]
@nixgates  In Version 2.0.14 in the change log I see the follwoing fix "Fixed race condition in pre-term for py3"  Is this related to this Pre-emptive termination bug? I tested it on version 2.0.15 and I see that its not terminating after meeting the pre-emptive termination criteria.

**Comment by nixgates** [comment]
@sathish804 sorry no not yet, I haven't had a chance to punch that one out and this was more an emergency fix for people with Apple TV/xbox.

Unfortunately that there is for python 3. I'm going to punch through a ton of other smaller stuff soon including this, sorry!

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
