### ISSUE TITLE
[BUG 2.0.6] Addon can't launch

### ISSUE THREAD

**Issue by PrevotYann** [nixgates/plugin.video.seren#304]
**Describe the bug**
Seren addon can't launch

**To Reproduce**
1. Launching Kodi with Auramod Skin

**Expected behavior**
Seren can't open

**Log file**
[Log](https://justpaste.it/44pwf
)
**Kodi Version (please complete the following information):**
 - Kodi Version 18.9

**Comment by nixgates** [comment]
@PrevotYann howdy, this is related to the following issue which as been resolved #287 

While that ticket is related to XBOX support the same fix was used to fix both issues. 

Please update to the latest version and you should be good to go! Worst case, re-open this ticket and let me know
