### ISSUE TITLE
[REQUEST] SOURCE SELECT - show the full name

### ISSUE THREAD

**Issue by peno64** [nixgates/plugin.video.seren#306]
**Is your feature request related to a problem? Please describe.**
I have configured seren as such that after searching it shows an overview of the found  sources. So I get the SEREN - SOURE SELECT screen.
This looks nice with the newest version, however I can't see the complete name anymore (in blue) it ends with ... and that's it. I prefer to see a complete name. Is it not possible to scroll it ir continue on a new line. There is alot of space available to do that.

**Describe the solution you'd like**
Either scoll the name or wrap it on the next line

**Comment by peno64** [comment]
This is probably a duplicate of issue  #293
Just saw that now

**Comment by Maximus97** [comment]
+1

**Comment by Nuklear92** [comment]
Having the same issue. I really hope Nix sees this and implement some sort of multi-line or horizontal scrolling. Definitely needed for those that like reading the full details on the links before choosing the right one. 🙏

**Comment by nixgates** [comment]
@peno64 Please refer to bug #293 

Closing duplicate
