### ISSUE TITLE
[BUG] TV shows won't play with the latest update 2.0.8

### ISSUE THREAD

**Issue by patel-jeel92** [nixgates/plugin.video.seren#309]
**Describe the bug**
When attempting to play a tv show, the add-on just says Building list items, starting playback and doesn't proceed to play anything. It seems like it doesn't even scrape for anything. I am running kodi 18.9 on shield tv pro 

**To Reproduce**
1. Go to Discover TV Shows --> Trending
2. Click on The Mandalorian 
3. See error. It should eventually scrape for the tv show and then start playback

**Expected behavior**
Serena should build the playlist, identify any resume points, scrape for the source and then start playback

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9 running on shield tv pro 
 - Version 2.0.8

**Comment by nixgates** [comment]
Could you please provide a debug log.

Are you attempting to play from within the addon or from TMDB helper? The building list items window is no longer present in the 2.0 except for play types like shuffling.

**Comment by patel-jeel92** [comment]
Hmm I will try generating a log. And I was attempting to play it within the add-on itself

**Comment by nixgates** [comment]
Hey @patel-jeel92 haven't heard back so I'm closing the incident off. 

If you do get a chance to get me a log please feel free to re-open this issue

**Comment by patel-jeel92** [comment]
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/5785088/kodi.log)
@nixgates I have attached the log here .
