### ISSUE TITLE
[BUG] My TV Shows in Progress Seasons show up as watched 

### ISSUE THREAD

**Issue by xyzfre** [nixgates/plugin.video.seren#310]
Every Tv Show I started watching when clicking on the Seasons it’s showing up with a check mark as watched but when I open the season I’m on the episodes are correct the ones I haven’t watched are not check off but seasons cover is check off like if I finish the season ,,trying to explain the best I can ,I’ll take some screenshots in a few ,,using AuraMOD skin on Nvidia Shield,,18.9

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by xyzfre** [comment]
![9DC968E2-CBE6-456F-9ADD-1BD4DBB16B50](https://user-images.githubusercontent.com/49699869/103485136-4580df80-4dc2-11eb-895f-a7ff63c024fe.jpeg)
For example: Dexter I’m on season 2 episode 8 on my next up it is correct as you can see in the picture above

**Comment by xyzfre** [comment]
![A07FBD63-A97D-4BD1-B4A8-60A010F0B24A](https://user-images.githubusercontent.com/49699869/103485190-9ee90e80-4dc2-11eb-9d35-4cf5000efa68.jpeg)
If I go into most popular as an example again Dexter shows up correct with the number of episodes I have left

**Comment by xyzfre** [comment]
![186E5BF1-9554-4E9B-B6BC-1AF0ECE75ABB](https://user-images.githubusercontent.com/49699869/103485223-cf30ad00-4dc2-11eb-945d-204b984d8346.jpeg)
But when I click on the season they all show up as mark watched

**Comment by xyzfre** [comment]
![9A3EE8C6-6906-44EF-8B4B-37EAE5A4A770](https://user-images.githubusercontent.com/49699869/103485249-01420f00-4dc3-11eb-83ae-7deb12571483.jpeg)
But when I open the specific season I’m on it does show the correct episodes that I haven’t watched yet and if I check a season that I haven’t watch yet it is also correct because the episodes are not marked as watched

**Comment by xyzfre** [comment]
I did check with a different add-on Fen to make sure it’s not a glitch on my end but everything shows up correct

**Comment by nixgates** [comment]
@xyzfre this is fixed for the next update :+1:

**Comment by nixgates** [comment]
@xyzfre 

Update has been released, please let me know if this fixes your issue!

**Comment by xyzfre** [comment]
First just want to say thank you for your response and looking into this,, so it did fix my in progress TV shows those when I click on the seasons they are correct The ones I haven't watch are not checked off anymore￼ ,but now I notice every show I have on my watchlist that I haven't started yet those show up with the seasons marked as watched,, I did try to rebuild database and also deleting the TraktSync.db and TraktSync.db.md5 files but it did not work,, any suggestions you want me to try￼￼￼￼￼

**Comment by xyzfre** [comment]
![image](https://user-images.git￼hubusercontent.com/49699869/103564327-50a04200-4e8c-11eb-9759-d44b326eff34.jpeg)For example Dexter As you can see it is fix it showing the correct watch info￼￼

**Comment by xyzfre** [comment]
![EF55D28E-6480-41EC-8258-EB4DD5C13F99](https://user-images.githubusercontent.com/49699869/103564991-7da12480-4e8d-11eb-91ff-815a8f21833a.jpeg)
![D57A83A0-2E4B-4ADB-B080-968275AB0779](https://user-images.githubusercontent.com/49699869/103564999-8134ab80-4e8d-11eb-927e-4740270ebbf6.jpeg)
Example these are shows on my watchlist that I haven’t started yet

**Comment by xyzfre** [comment]
Been playing around a lot with 2.0.9 and so far besides this glitch on my end with my watchlist shows￼ seasons being marked off as watched it is working amazingly great lots of respect for your work my friend Seren is a legend ￼￼

**Comment by xyzfre** [comment]
Wanted to experiment a little bit ,so ￼Just did a clean install on a different device with no Trakt authorization just to see what happens but the same issue accord when selecting a TV show all￼ seasons show up marked as watched ￼￼￼

**Comment by nixgates** [comment]
@xyzfre could you have a look at this issue with 2.0.13. I think we have this one resolved now but need to confirm

**Comment by xyzfre** [comment]
OK definitely will check as soon as I get home thanks @nixgates for your response and time￼￼

**Comment by xyzfre** [comment]
> @xyzfre could you have a look at this issue with 2.0.13. I think we have this one resolved now but need to confirm

Unfortunately the same issue and this time I did a fresh install of Seren just to make sure it's not on my end two different devices same issue ￼￼

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
