### ISSUE TITLE
[BUG] NextUp Episode Playing issue

### ISSUE THREAD

**Issue by sathish804** [nixgates/plugin.video.seren#311]
**Describe the bug**
SmartPlay dialog is only showing on the episode on which playback is started and for other videos being followed SmartPlay dialog is not showing. 

**To Reproduce**
1. Chose a TV show
2. Play any episode in the season
3. At the end of episode SmartPlay dialog shows. 
4. Click on Play button. 
5. On the Next episode before ending no SmartPlay dialog is shown. 

**Expected behavior**
SmartPlay dialog should be shown on the episodes as per the criteria from settings. 

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - version 2.0.8

**Additional context**

**Comment by StreamAntics** [comment]
I posted a similar problem with smart play, only difference I don't get a pop up at all, even on the video file played back.

**Comment by nixgates** [comment]
@sathish804 I believe this is related the the issue #315 

while you did log before that one I'm just wanting to consolidate the duplicates and have directed other tickets to that one. If you wouldn't mind following along there 👍

**Comment by sathish804** [comment]
@nixgates Sorry its not related to that bug. Its related to SmartPay. For first video played in a series is showing the SmartPay dialog and for next videos its not even though there are episodes in the series. I will update the title accordingly and will share the log with you. Please reopen this bug.

**Comment by sathish804** [comment]
@nixgates  kodi log for this issue https://controlc.com/d7b016c4

**Comment by nixgates** [comment]
@sathish804 

Apologies, I've referenced the wrong bug. 

The correct bug is #281

Thank you for your log! This will help!

**Comment by sathish804** [comment]
Yes this is the same issue.
