### ISSUE TITLE
[BUG] 2.0.8 - Can only play TV episodes once, afterwards errors.

### ISSUE THREAD

**Issue by jweinreich** [nixgates/plugin.video.seren#313]
**Describe the bug**
Weird bug on 2.0.8 where Seren will only play tv episodes once and then throw error afterwards. This behaviour happens while inside Seren addon, or TMDBh and widgets.

**To Reproduce**
1. Reboot KODI
2. Play any episode on widget or seren.
3. Stop playback.
4. Play any episode again. Seren errors. 

- Shield TV.
 - Kodi Version [18.9]
 - Version [2.0.8]

Error LOG:
https://paste.kodi.tv/ayuxegitoq.kodi

**Strangely enough, starting (scraping) any MOVIE in between will let me play another TV episode, but just once, then back to error loop.**

**Comment by roc16** [comment]
Same here. Thanks for logging the issue @jweinreich

**Comment by nixgates** [comment]
This should be resolved in the next update. Please let me know how you go in the next version when released

**Comment by nixgates** [comment]
Update has been released, please let me know if it fixes your issue :+1:

**Comment by roc16** [comment]
Thanks @nixgates this works now for me. How about you @jweinreich ?

**Comment by jweinreich** [comment]
Great confirmed working, thank you nix.

Log attached if you want to confirm it all looks healthy?
There's a persitent "ERROR: GetDirectory - Error getting include" though,  which i guess is not related to Seren,

https://paste.kodi.tv/afozohewec.kodi

**Comment by nixgates** [comment]
@jweinreich @roc16 

Great to hear guys! 

Closing it off :)
