### ISSUE TITLE
[BUG] Race condition in thread worker 

### ISSUE THREAD

**Issue by Adarma** [nixgates/plugin.video.seren#315]
**Describe the bug**
When selecting `Seren - My Shows - Next Up`, I get the following error popup in the top right corner:

```
Seren error
Check the log for more information.
```

All other Seren menus seem to work correctly. They show the expected Trakt data.
It only happens on one Kodi User Profile out of two that are set up.
It happens on the 2nd profile.

**To Reproduce**
1. Go to 'My Shows'
2. Click on 'Next Up'
3. See error

**Expected behavior**
A list of shows from Trakt.

**Kodi Version**
 - Kodi Version: 18.9
 - Seren Version: 2.0.8

**Additional context**
https://paste.kodi.tv/titemoxepi

**Comment by mLgz0rn** [comment]
Same thing is happening to me, also with latest episodes.

Seren -> my shows -> latest episodes
And since I have next up and latest episodes used in a widget I instantly get the error when kodi loads up.

It was working fine with 2.0.0.

Log: https://paste.kodi.tv/favufamebu

**Comment by StreamAntics** [comment]
As requested @nixgates here is my most recent log hope this helps
https://paste.ubuntu.com/p/Qfj6zdymD2/

**Comment by StreamAntics** [comment]
Got more recent log https://paste.ubuntu.com/p/9FnJRwbfRN/ hope this is what you're looking for @nixgates as requested from issue #300

**Comment by mLgz0rn** [comment]
@nixgates looking at the other issues you have responded to and closed, I think you might be confusing this issue with the "NextUp" feature while already playing and episode.
This is a menu problem, that happens before you play anything.
I actually think it's more likely related to #316

**Comment by nixgates** [comment]
@mLgz0rn ah does look like I've referenced the wrong ticket a few times.

The error in your log should be covered under 2.0.9 though. If you still get an error might be a new one that was waiting down the line. Could I ask for a new log to be sure?

**Comment by Adarma** [comment]
2.0.9 has not resolved the issue for me. New log:
https://paste.kodi.tv/joviyeqebe

**Comment by nixgates** [comment]
@Adarma yep I can see what's happening in your log, there looks to be a new race condition created in the thread worker. 

Will fix this up and have it out soon.

**Comment by nixgates** [comment]
@Adarma this should be fixed in the next update 👍

**Comment by nixgates** [comment]
@Adarma the issue should hopefully be resolved now in 2.0.10, if you wouldn't mind confirming?

**Comment by Adarma** [comment]
Confirmed working :+1: :
Thanks!

**Comment by sathish804** [comment]
@nixgates Its working great now!!

**Comment by nixgates** [comment]
@Adarma good to hear! Closing it off :)
