### ISSUE TITLE
[BUG: v2.0.8] Up Next Doesn't Load When Changing "Metadata Location" Option From TMDb to Trakt/TVDB 

### ISSUE THREAD

**Issue by LoganWolverineX** [nixgates/plugin.video.seren#316]
**Describe the bug**
Up Next won't load as a widget or as a shortcut/in the addon when changing "Metadata Location" option from TMDb to Trakt/TVDB.  I then get a Seren Error popup.  I have also tried to Seren and Kodi clear cache too.

**To Reproduce**
1. go to the option "Metadata Location" for Seren settings.
2. Change the option from TMDB to Trakt or TVDB
3. Reload Skin or restart Kodi to see it fail to load in a widget
4. Or go into seren addon, then go to my tv shows, then go to "Up Next" to see it fail from there

**Expected behavior**
Changing it from Trakt or TVDB should not cause Up Next to fail to load in widgets or within the addon.

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren Version 2.0.8
 - Skin:  Aura Official

Log Attached Below:
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/5762436/kodi.log)

**Additional context**
Log contains error for Up Next as a widget and opened from within addon.

**Comment by nixgates** [comment]
Fix applied, will be available next update :+1:

**Comment by LoganWolverineX** [comment]
> Fix applied, will be available next update 👍

Thanks @nixgates !

**Comment by nixgates** [comment]
@LoganWolverineX  update has just been released, please let me know if this doesn't fix the issue 👍

**Comment by LoganWolverineX** [comment]
@nixgates Thanks a lot for this fix too!!  I just tried changing TMDB to Trakt as well as TVDB.  Both works perfectly with Next Up!

**Comment by nixgates** [comment]
@LoganWolverineX awesome, closing it off!
