### ISSUE TITLE
[BUG] Stops playing in middle of episode and jumps to the next episode.

### ISSUE THREAD

**Issue by hockeymachine86** [nixgates/plugin.video.seren#319]
**Describe the bug**
Watching a tv show using Seren where it scrapes and finds a cloud (PM) source and it will stop in the middle of the video and jump to the next video.   I have changed the CDN for PM and same issue.  Does not seem to occure when utilizing Premiumize Addon with a cloud source, but does with Seren.

**To Reproduce**
1. Go to 'My TV Shows'
2. Click on 'Next Up'
3. Scroll down to 'Select TV Show'
4. See error (see log: [https://paste.kodi.tv/omejigened.kodi ](https://paste.kodi.tv/omejigened.kodi)

Occurs twice in log.  Once around "Line 532: 2021-01-03 20:24:01.936 T:1176" and again around "Line 717: 2021-01-03 20:49:26.280 T:12160" 

**Expected behavior**
Video to finish streaming and then popup 'NextUp'

**Screenshots**
N/A

**Kodi Version (please complete the following information):**
 - Kodi 18.9 / Seren 2.0.8

**Additional context**

**Comment by nixgates** [comment]
Unfortunately I'm unable to assist here as the connection to the playing file times out in Kodi. No amount of changes to Seren will fix this. Sorry I can't be of help.

Reference Lines in log
`2021-01-03 20:13:24.502 T:11780 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2021-01-03 20:13:28.985 T:10700  NOTICE: Samba is idle. Closing the remaining connections
2021-01-03 20:24:01.936 T:11767   ERROR: CCurlFile::FillBuffer - Failed: Stream error in the HTTP/2 framing layer(92)`
