### ISSUE TITLE
[BUG] Unable to authorize RD in Seren from scratch.

### ISSUE THREAD

**Issue by cgcgcgcgcg** [nixgates/plugin.video.seren#321]
I'm using a multi-skinned build which works perfectly.
After updating Seren to 2.0.8, my debrid sources did not work any more.
I deleted my authorization from the Real Debrid site, clicked on Defaults in Seren's settings, and it started giving an error (see pic).
I went to Tools and wiped addon, and it would only show that pass is copied on clipboard but no pass (Kodi doesn't implement clipboard in Linux).
I uninstalled Seren, and after reinstall the same happened.
That was on a Titan mod based skin.
I switched to a Xonfluence mod based skin and the pass was visible.
The same error occured (see pic).
If you need a full log, let me know, and I'll enable debugging and post one -it's a build so it will be bigger than usual.
![ksnip_20210104-083437](https://user-images.githubusercontent.com/38960370/103507744-88958e00-4e68-11eb-9529-9a35729e3eb7.png)

**Comment by nixgates** [comment]
@cgcgcgcgcg can you just confirm something for me, try setting your text highlight color in the interface settings.

I believe I know the issue and if after setting that and re-opening settings and authing works, I'll know how to fix it 👍

**Comment by cgcgcgcgcg** [comment]
> @cgcgcgcgcg can you just confirm something for me, try setting your text highlight color in the interface settings.
> 
> I believe I know the issue and if after setting that and re-opening settings and authing works, I'll know how to fix it +1

Thank you, changing the color (I chose gray) fixed the code.
I got the same error though after authorizing.
![ksnip_20210104-085922](https://user-images.githubusercontent.com/38960370/103509244-55a0c980-4e6b-11eb-95d8-09e5e9f54395.png)

**Comment by nixgates** [comment]
Ah yep, I've identified the issue.

I'll make sure both fixes are in the next update :+1:

**Comment by nixgates** [comment]
@cgcgcgcgcg hey mate, just consolidating some of these tickets

Please refer to #280 for further updates :)

**Comment by cgcgcgcgcg** [comment]
> @cgcgcgcgcg hey mate, just consolidating some of these tickets
> 
> Please refer to #280 for further updates :)

Thanks, a reminder that in v2.0.9 it still gives an error after authorizing Seren.

**Comment by nixgates** [comment]
@cgcgcgcgcg yep all good, I'm consolidating a few more bugs into the next update rather than pushing out heaps of small ones,

But I was able to reproduce this issue and have a fix that should solve it 100%

**Comment by cgcgcgcgcg** [comment]
@nixgates just installed v2.0.10, everything works as promised, thank you.
