### ISSUE TITLE
[BUG] Cloud sources not sorted by resolution

### ISSUE THREAD

**Issue by dazazbab** [nixgates/plugin.video.seren#322]
**Describe the bug**
Source sorting seemed inconsistent in some shows. This caused an issue for auto play since Seren play the top source automatically. I selected to group the source by resolution. However, a couple times a lower resolution source came up on top of the list. It looks like Seren sometimes is prioritizing cloudfiles source type to torrent regardless of resolution.

**To Reproduce**
A. On Seren/Settings/Sort & Filter:
1. Set Source Sorting Grouping Style to Resolution
2. Enable Secondary Filesize Sort
3. Enable Reverse Size Sort (Low to High)

B. On Seren Shows Selection
1. Do a Source Select

**Expected behavior**
Source sorting with Resolution Grouping set should bring the highest resolution on top regardless of source type. This will make sure the best quality source being played on auto play.

**Screenshots**

![IMG_5224](https://user-images.githubusercontent.com/66974089/103509792-ed81c180-4e31-11eb-83f8-5ded20dff8d7.jpg)
![IMG_5222](https://user-images.githubusercontent.com/66974089/103509803-f4103900-4e31-11eb-961a-836d60a0e6c5.jpg)
![IMG_5216](https://user-images.githubusercontent.com/66974089/103509813-f83c5680-4e31-11eb-84bd-74c5a6fdb5c7.jpg)

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9

**Comment by nixgates** [comment]
@dazazbab this has always been true for Seren and was more of a feature than a bug.

Perhaps we could add a feature to not sort cloud files to the top?

**Comment by dazazbab** [comment]
> @dazazbab this has always been true for Seren and was more of a feature than a bug.
> 
> Perhaps we could add a feature to not sort cloud files to the top

It's really not a problem if the cloud files is listed on top as long as it's not a lower quality than what's below it. Not sure how to address that. It's a nice thing to have cloudfiles in the result but not trumping higher quality results.

**Comment by dazazbab** [comment]
> @dazazbab this has always been true for Seren and was more of a feature than a bug.
> 
> Perhaps we could add a feature to not sort cloud files to the top?

And on my second screenshot you can see that the 1080p cloudfile is listed below a 720p and SD cloudfiles.

**Comment by nixgates** [comment]
Ah so looks like cloud files aren't being sorted correctly. 

That is definitely an issue! I will make sure its fixed in the next update :)

**Comment by nixgates** [comment]
@dazazbab fixed! :)

**Comment by dazazbab** [comment]
awesome!! thx!!
