### ISSUE TITLE
[BUG] No RD cloud results 

### ISSUE THREAD

**Issue by Jim22223** [nixgates/plugin.video.seren#323]
I am using the latest Seren 2.0.9
Example: Supermarket Stakeout S02E06
Seren finds the 720p file in the AD cloud but not the 1080p file in the RD-Cloud (which FEN does).

There are also no SCENERLS hoster results although the package is enabled in a4kscrappers (I checked and FEN has these results).

**Comment by nixgates** [comment]
In regards to the provider not returning results i can't help much there, your best bet is to get in touch with the dev for that package.

In regards to the cloud source, if you comment the file name you expect it to find or pack it should fetch from ill make sure it works on the next update  :)

**Comment by Jim22223** [comment]
Thank you.
According to FEN I find these two files in the cloud:
AD Cloud (found by Seren): "Supermarket.Stakeout.S02E06.Toast.the.Competition.iNTERNAL.720p.WEB.x264-ROBOTS[eztv].mkv"
RD Cloud (not found by Seren): "Supermarket.Stakeout.S02E06.Toast.the.Competition.iNTERNAL.720p.WEB.x264-ROBOTS.mkv"

The AD cloud item was cached into my account it seems but the RD cloud file isn't on my account. I have no idea where this result comes from.

**Comment by nixgates** [comment]
@Jim22223 im not sure what you mean? 

Are you sure the file isn't in your account?

If the file isn't in your cloud on RD and Seren isn't identifying it there im not sure that's an issue?

**Comment by Jim22223** [comment]
The file is not in the account. Somehow the FEN plugin seemed to query the RD Cloud directly (and the file worked). No other addons (Venom, The Crew, Gaia, etc) had this result. I only installed Kodi a few days ago and used it for comparing the different addons.
But I just tried again and it's gone... I am sorry for the troubles.

**Comment by nixgates** [comment]
@Jim22223 no worries bud! 

Good to see the RD fix is still working 👍
