### ISSUE TITLE
[BUG] Seren default action set to info and Kodi default set to info causes lockup

### ISSUE THREAD

**Issue by Navios92** [nixgates/plugin.video.seren#324]
I'm running Seren 2.0.9 on Fire Cube (2019) with Kodi v18.9 and AH skin. I can't play any TV show. Kodi loading animation keeps spinning and nothing happens. I tried playing shows from Most Popular, Trending and my Trakt watchlist, and it's the same problem. Next Up list works fine, though.

I have the same setup on my laptop and Fire Cube, but only Fire Cube has this problem.

[Here](https://paste.ubuntu.com/p/8VWd4g2pTD/) is a log file of me trying to play a show from my watchlist. Let me know if you need any other information.

**Comment by Navios92** [comment]
I should point out that I tried rebuilding the database and wiping addon data but that didn't help.

**Comment by nixgates** [comment]
@Navios92 hmm looks like you have default action set to info instead of play and Kodi or Seren is unable to handle the request. Would you mind doing me a favour and try setting your default action to platform the follow settings:

Seren settings > Default Movie Action
Seren settings > Default Episode Action

If this works I may need to run some tests to find out why that's happening.

**Comment by Navios92** [comment]
> @Navios92 hmm looks like you have default action set to info instead of play and Kodi or Seren is unable to handle the request. Would you mind doing me a favour and try setting your default action to platform the follow settings:
> 
> Seren settings > Default Movie Action
> Seren settings > Default Episode Action
> 
> If this works I may need to run some tests to find out why that's happening.

That actually fixed it! And I checked my laptop, and it turns out I had it set to Play. I changed it to Show Information and the same problem happened, so it's definitely the culprit here.

I already have Default Select Action in Kodi global setting set to Show Information. Changing the setting in Seren seems to have no effect at all, except for the problem mentioned above of course. It still shows information on first click anyway.

**Comment by MartinB1957** [comment]
I’ve has a similar problem on a couple of Firesticks - a new 4K stick and an older version, both running Kodi Leia. Strangely, some TV Show searches produce nothing, other searches produce Series & Episode lists  but Seren only loads and plays what I have already watched but won’t find (scrape) any of the ‘new’ (as yet unwatched) episodes! Pop up message says “Check Log for For Information”. I will try the ‘fix’ mentioned in previous conversation and get back to you. Sorry but my technical knowledge of how all this works is a little vague!

**Comment by MartinB1957** [comment]
Update. Alas, both my movie and TV settings are already at ‘Play’ so still having the same issue, some working, some not. The pop up error message is a Black X on a red circle and says Seren Error ‘Check the Log for more Information’. Can someone please advise how to ‘check the log’? Thank you.

**Comment by MartinB1957** [comment]
Further Update. Now unable to view/play previously watched episodes (as stated earlier).  Why trying previously viewed episodes, getting a Kodi ‘Playback Failed’ message. “One or more items failed to play. Check the log for more information about this message.”. Thank you.

**Comment by nixgates** [comment]
@MartinB1957 if you wouldn't mind raising a new issue, it sounds like your issue is a bit different. 

When you do raise the issue, would you mind providing a debug log for me :)

**Comment by MartinB1957** [comment]
PPS! Just tried a random selection of movies from various categories - all seems to be working fine! So my issues seem to only be with TV Shows?!?

**Comment by MartinB1957** [comment]
Sorry, need help/advice on raising a new issue and providing the debug log? Apologies.

**Comment by MartinB1957** [comment]
Do you need me to repeat all my comments under any new issue raised?

**Comment by jweinreich** [comment]
@MartinB1957 
We were having some TV show issues on 2.0.8 and older version. Is your version 2.0.9?
To force an update go to your addons: install from repo: long press nix repo: Verify updates.

Are you browsing your episodes directly inside Seren app or through another app/widgets?

Get to log file:
\internal\Android\data\org.xbmc.kodi\files\.kodi\temp\kodi.log
This log file will reset everytime you run kodi.

**Comment by nixgates** [comment]
@MartinB1957 you can raise a new issue by heading the issues list: 

https://github.com/nixgates/plugin.video.seren/issues

Then click the new issue button in the top right hand corner :+1:

**Comment by nixgates** [comment]
@Navios92 I'm removing this feature in 2.0 on the next update, it unfortunately conflicts to much with the kodi settings and will only cause more headaches down the line.

**Comment by Navios92** [comment]
> @Navios92 I'm removing this feature in 2.0 on the next update, it unfortunately conflicts to much with the kodi settings and will only cause more headaches down the line.

Yeah it seems easier to just leave it handled by Kodi.

**Comment by SerpentDrago** [comment]
> @Navios92 I'm removing this feature in 2.0 on the next update, it unfortunately conflicts to much with the kodi settings and will only cause more headaches down the line.

why ? why is having the option a problem ? people obviously shouldn't use seren's setting to info if they already have kodi global on info . 

the whole reason for this feature is to be able to keep kodi default to play , and ONLY use info as default for seren items . Combined with some skins ability to set the default action for home widgets / hubs . makes the perfect setup . 

Obviously if someone sets both to info its going to cause issues . 

Or nix are you saying that it causes a issue period ? no matter the setting ? 

IDK this is one of the best features of seren 2.0 .

**Comment by nixgates** [comment]
@SerpentDrago I'm not saying 100% this is an indefinite removal. 

To get this working, we need to set up JSON Rpc requests to check settings of kodi to confirm what the current setting is so we don't get lock ups for users who accidentally do both. There's unfortunayely just not enough time free time write that module up to do that at the moment.

The easiest workaround for now is to disable it to avoid more issues being raised and causing me more over head with tickets.

I will promise to revisit it when things are less chaotic. I do like the feature as its more usable than the kodi feature.

**Comment by nixgates** [comment]
Closing issue after release of 2.0.10
