### ISSUE TITLE
[BUG] No playable sources found for item (any items)

### ISSUE THREAD

**Issue by ruizitu** [nixgates/plugin.video.seren#325]
**Describe the bug**
After the update, any movie or TV show won't play, seren gives me the "No playable sources found for item". I've tried resetting seren, reintroduced my trakt and real debrid but still experiencing the same issue.

**To Reproduce**
1. Go to movies/series
2. Click on any movie/series
3. Also tried rescrape item
4. Error still shows

**Expected behavior**
When selecting a movie or TV show episode it should show the list to select the source.

**Screenshots**
None

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9.0
 - Libreelec 9.2.6

**Additional context**
Log here:
[Log](https://paste.kodi.tv/uzurujewun)

**Comment by nixgates** [comment]
@ruizitu don't seem to be able to see any attempts at playback in that log, would you mind enabling debug logging your Kodi settings and trying playing something again for me :)

**Comment by ruizitu** [comment]
> @ruizitu don't seem to be able to see any attempts at playback in that log, would you mind enabling debug logging your Kodi settings and trying playing something again for me :)

Sorry about that mate, here's a new log[Log](https://paste.kodi.tv/siwesezena)

**Comment by nixgates** [comment]
@ruizitu looking at your log, it looks like your local torrent cache database is filling in the sources and Seren is pre-terming on it. Would you mind clearing your local torrent cache database and re-running the scrape with a log?

**Comment by ruizitu** [comment]
@nixgates tried that but no luck, here's the [log](https://paste.kodi.tv/cufafevoye)

**Comment by nixgates** [comment]
@ruizitu would you mind letting me know your pre-termination setting values?

**Comment by ruizitu** [comment]
> @ruizitu would you mind letting me know your pre-termination setting values?

You are a legend! I honestly do not know how I managed to enable that! I always had it off, but I probably messed up somehow as I don't think this was caused by the update. It was set on 1 with pre-termination on. Please accept my apologies.

**Comment by nixgates** [comment]
@ruizitu no worries, I'll increase some logging in Seren to help me identify this issue in the future! We still win!

**Comment by connoch1** [comment]
I haven't been able to play anything since the recent update. Could someone tell me if preemptive termination should be on or off and what other settings could cause, no playable sources? I have trakt, RD, and have added providers.

**Comment by ruizitu** [comment]
> I haven't been able to play anything since the recent update. Could someone tell me if preemptive termination should be on or off and what other settings could cause, no playable sources? I have trakt, RD, and have added providers.

I keep it off, it finds more sources, I prefer it that way.
Try turning it off and test again.

**Comment by inb4after** [comment]
> I haven't been able to play anything since the recent update. Could someone tell me if preemptive termination should be on or off and what other settings could cause, no playable sources? I have trakt, RD, and have added providers.

If all the values are 0 and all providers are being checked during scraping, it usually means you need to re-auth debrid service.

**Comment by connoch1** [comment]
Thanks!!

**Comment by connoch1** [comment]
I have reauthorized RD and Trakt, cleared cache, and restarted my stick.

I dont know where I would look for all 0a. I'm a novice and only use the
user interface, I dont code.

But it's been down ever since the upgrade.

Thank you for your response.

Christine

**Comment by connoch1** [comment]
I have it off. Ut have tried it both on and off with no different results.

I've read that with Seren it should be off because it looks for sources in
serial so no need for it.

Thanks for your response.

Christine

**Comment by peterDijk** [comment]
I had the same after the update. Found this bug issue, noticed the `pre-termination setting`. Looked it up, indeed it was enabled. Definitely did not change any setting for months, so the update must have caused this. Turned it off, and streams work immediately. Thanks!

**Comment by connoch1** [comment]
Thanks Peter. I've uninstalled Seren on all my sticks and switched to other
addons. Seren has been very off and on since 2.x came out.

I think I'll wait until Kodi 19 comes out to try Seren again.

Appreciate your help.

**Comment by Arthur1967** [comment]
Does anyone know what my source select settings should be set at like 3-D on or off and all those fine tune settings thank you I've been unable to find complete instructions for this￼
