### ISSUE TITLE
New TV Shows list not showing up in 2.0.9[BUG]

### ISSUE THREAD

**Issue by vchunkyzv** [nixgates/plugin.video.seren#326]
**Describe the bug**
New TV Shows list giving a Seren error when trying to see it on 2.0.9. 

This was working fine on 2.0.8

**To Reproduce**
1. Go to 'Discover TV shows.'
2. Click on 'New TV Shows'

**Expected behavior**
TV show list comes up. 

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9 Leia on nvidia shield. 

**Additional context**

**Comment by jweinreich** [comment]
Confirmed here too on 2.0.9

WARNING: SEREN: We received no titles to build a list

**Comment by kodi-lover** [comment]
Confirmed for me too, was fixed in version 2.0.8 but now broken again in this new version.

**Comment by james-s-nduka** [comment]
Can confirm this is broken in the latest version.

**Comment by xyzfre** [comment]
Same here it was working in 2.0.8 but now with the latest update also get an error when trying to open New TV shows section

**Comment by nixgates** [comment]
Hey guys, this is a duplicate ticket, please refer to bug  #273
