### ISSUE TITLE
[BUG 2.0.9] My Watched Episodes Not Updated After Watching Episode

### ISSUE THREAD

**Issue by LoganWolverineX** [nixgates/plugin.video.seren#327]
**Describe the bug**
I started noticing that after watching show episodes, it's not getting updated in "My Watched Episodes".  I think this must have started happening after updating to version 2.x because it updated update prior to version 2.x.

**To Reproduce**
1. Watch any show episode until it gets marked as watched.
2. Go to "My Watched Episodes" within "My Shows"
3. Check to see if the new episode you just watched shows up or not

**Expected behavior**
After watching an episode, it should automatically update "My Watched Episodes".

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren Version 2.0.9
 - Skin: Aura Official

**Additional context**
The only way currently to fix this is to "Rebuild Database" from Trakt Sync Tools which is annoying because it takes a long time to rebuild Trakt database.  After rebulidng database, all 3 episodes I've watched after the 2.x release showed up.  I tried "Force a sync with Traktk" which is faster, but it doesn't fix it.

PS- I haven't had a chance to see if this also affects "My Watched Movies" or not because I haven't watched any movies since the update to 2.x yet.

**Comment by LoganWolverineX** [comment]
please disregard.  I think it must have been fixed in 2.0.9.  closing item.

**Comment by ShibajiCh** [comment]
Hi,
Why did you close this ticket? Please reopen it. I can confirm that I'm too facing this issue in Seren v2. 0.9. Watched episodes are not getting marked as watched in Trakt and therefore next up episodes are not appearing correctly.

**Comment by LoganWolverineX** [comment]
Ur issue is different then. I’m not seeing that issue. Episodes are getting marked as watched. 

But maybe you’re right though. If I watched it from one device. And I go to another device, “my watched episodes” should be updated properly.  It’s not syncing up to trakt. 

I will reopen. Keep in mind this issue is in relation to “my watched episodes” not updating/syncing when I go to it from other devices. My episodes do get marked as watched from seren and then synced to trakt. I always verify using a trakt app.

**Comment by LoganWolverineX** [comment]
@ShibajiCh did you try to re-authenticate Trakt from seren settings/accounts then let seren rebuild the trakt database? This step takes a while.

**Comment by ShibajiCh** [comment]
Hi,
Thanks for reopening this issue. For me if I'm watching a single episode continuously without forwarding or rewinding it then sometimes it's not scrobbling in Trakt or even if it is scrobbling it is not getting marked as watched once the episode completes. So next up episodes list is also not updating.

**Comment by Sparky7420** [comment]
I, too am facing the same issue. I have even reset seren and reauthorized trakt. It is hit or miss if it works. Same set up, lea, seren 2.0.9

**Comment by nixgates** [comment]
Please refer to issue #281

Closing as duplicate
