### ISSUE TITLE
"Continue Watching/are you still there" dialog boxes just appearing once on first show [BUG]

### ISSUE THREAD

**Issue by vchunkyzv** [nixgates/plugin.video.seren#329]
**Describe the bug**
"Continue Watching/are you still there" dialog boxes just appearing once on first show. When the "continue watching" dialog box appears at the end of the episode, you can click continue watching and it successfully takes you to the next one, but on that next show the dialog doesn't re appear at the end of the show.  

**To Reproduce**
1. Go to 'end of episode and click continue watching on dialog box'
2. wait for next dialog box to appear and notice it won't

**Expected behavior**
continue watching/are you still there dialog boxes should appear on subsequent playing episodes

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9 Leia on libreelec VM

**Additional context**

**Comment by jweinreich** [comment]
Confirmed, Playing next dialog appears only once.

**Comment by nixgates** [comment]
Please reference #308 

Closing duplicate
