### ISSUE TITLE
Certain links not working since the update. 

### ISSUE THREAD

**Issue by jimmyhall79** [nixgates/plugin.video.seren#33]
Since seren updated to 0.1.29 I've noticed 2 links not working in discover movies, recommended for you and trending. When clicked the wheel spins very briefly and then nothing, you are still on the main discover movies menu. 

I haven't checked every single link so far but tried about 5 others and they were working fine, if you'd like me to go through each one please just let me know.

**Comment by jimmyhall79** [comment]
All fine now, either you sorted it or it was maybe a trakt.tv issue? Thanks either way for all the amazing work!

**Comment by nixgates** [comment]
This was likely due to the recent trakt partial outage

Have a good one 😊

**Comment by jimmyhall79** [comment]
It was weird as the same trakt.tv lists were surfing in other addons, but anyway it's working now so who cares right lol

Thanks again
