### ISSUE TITLE
[BUG] 2.0.9 Trakt Lists Next page Not Working As intended

### ISSUE THREAD

**Issue by Bio37** [nixgates/plugin.video.seren#331]
Steps to reproduce the issue.

1: Have more Trakt liked lists than the default page item limit in Seren's Interface settings.
2: Open 'My Liked Trakt lists" press "Next Page"
Behavior: Pressing Next page returns the same results that were in page 1

Expected Behavior: Pressing Next Page should show the next results instead of displaying the same results again

**Comment by nixgates** [comment]
This sounds like an issue that was fixed in the latest update (2.0.9). Can you please confirm what version you are on?

**Comment by Bio37** [comment]
Sure can my friend. I'm on 2.0.9

**Comment by Bio37** [comment]
Might just need to rebuild ?

**Comment by Bio37** [comment]
Okay it works now for whatever reason. I must have gotten the update later
than i tought. Sorry about the misunderstanding
