### ISSUE TITLE
[BUG] v2.0.9 - Up Next Air Date Offset Issue?

### ISSUE THREAD

**Issue by LoganWolverineX** [nixgates/plugin.video.seren#333]
**Describe the bug**
I am in the US East time zone.  there's currently Monday (1/4) shows already showing up in Up next for shows that start at 8pm EST.  As of right now it's 3:30pm EST.  Do you know if anything was changed to any timezone offset in Seren 2.x?  It appears it's offset to GMT/UK time.  Before Seren 2.0, it showed up on time based on US East time zone, but now it seems to be showing 5 hours earlier.

**To Reproduce**
1. Check shows in up next
2. From US East time zone, 8pm EST shows are showing up at looks like 3pm EST.

**Expected behavior**
Example:  8pm EST shows should show up in Up Next at 8pm EST like how it was in seren 1.x.

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren 2.0.9

Hope this all makes sense. All the timezone related stuff can get so confusing.

**Comment by nixgates** [comment]
@LoganWolverineX hey mate, there was a change in Seren in the latest update that modified how we handle dates internally. 

Could you check and see if this has fixed your issue?

**Comment by LoganWolverineX** [comment]
Hey @nixgates! I’m on top of it :) haha! I installed 2.0.16 and to my amazement, everything is look great in next up in terms of when it shows up on next up :). 

Thanks a lot man! Another of my issues closed out :-).

**Comment by nixgates** [comment]
@LoganWolverineX Close em up! :joy:
