### ISSUE TITLE
[BUG] Movie title searches are in French?

### ISSUE THREAD

**Issue by somexone** [nixgates/plugin.video.seren#335]
Hi there,

You can reproduce this error by going to search > search movies > new movie search

Ever since updating to Seren 2.0 all my movie searches have come up in French. For ex if I search Toy Story I'll get results for Histoire de jeouts. This appears for everything else as well. 

I'm using macOS with Kodi 18.9 Leia. I haven't changed any language settings since updating. I will add I'm Canadian so I'm not sure if that's messing things up where our official languages are English and French but I can't see that as it was working fine and was all in English before updating. Being Canadian I know a lot of French words but I'm not fluent so I'd prefer English. If only I was bilingual :)

I am using the latest 2.0.9 and it didn't fix anything. 

This appears to be only affecting movies. All tv shows so far appear to be titled in English. While I have some movies in French and others in English. Another example is Merry Christmas Charlie Brown is appearing as Joyex Noel Charlie Brown. Star Wars Episode 3 is also showing up in French along with Batman returns just to name a couple others.

When I hit play on these titles they play using English audio but the titles for whatever reason appear in French. What's odd it isn't in every movie but there's a decent amount while before updating everything including these same movies mentioned were in English and I didn't change my setup at all so I am not sure what's going on here.

I do apologize I opened this issue on the main nixgates page but I closed it and am posting it here on the Seren page. I am new to GitHub so please forgive me. 

Thank you.

**Comment by nixgates** [comment]
@somexone have you checked your language in Kodi?

Seren now translates meta data to match the current set language for Kodi so if you could check that setting and let me know 👍

**Comment by somexone** [comment]
Hi Nix,

Yes I have checked. My Kodi language is set to US English and macOS is set to Canadian English. 

I ended up downgrading to 1.6.9 and checked the same movies and I no longer have the issue. I've disabled updates until 2.0 has matured some more. 

I do appreciate all that you do and am really loving Seren and can't wait until 2.0 has all the bugs worked out. 

I have no idea why random movies are in French. Especially when soon as I downgraded all those movies now appear in English without changing a single setting. It's very odd and I hope you can track down the issue! 

Thanks again.

**Comment by nixgates** [comment]
@somexone the old version of Seren did not attempt to translate the meta. It's a new feature in 2.0 

If you wouldn't mind dropping me a log, using the old version of Seren is fine, I wouldn't mind just cross checking the language file Kodi is using so I can try and diagnose the issue 👍

**Comment by somexone** [comment]
Oh it's new. That explains it. Very odd tho how random titles are in French. Not even all of them just completely random. 

I'd love to send you a log but I actually haven't had to give one yet so I am unsure how to generate one. I do apologize. Would I get that from Kodi itself or do I use Seren to get one?

**Comment by nixgates** [comment]
@somexone You can install an addon from the Kodi repository called log uploader. 

That will give you a link to post here so I can view it :)

**Comment by somexone** [comment]
Thank you @nixgates!

Just installed it. 

Here is the link it gave me.

https://paste.kodi.tv/zutazotoli

Good luck!! It is definitely an interesting bug. I wish I could of given you a log before I downgraded tho. Hopefully this is helpful to you tho!

**Comment by somexone** [comment]
Hi Nix,

I updated back to 2.0 due to the trakt issues. That's all working now again so thank you so much for your hard work on getting that resolved so quickly.

I've noticed my language is set to just English and region is Canada and that's when I start to see random movies in French. Can this be related to French being one of our main languages?

So I was curious and went in and changed my language to English (US) and region to US. The same movies now show up in English. 

As a Canadian I prefer to use the Canada region of course but I can live with the US setting until this is resolved. Long as it's in English I don't really mind the region. Just figured this might help you narrow the bug down.

**Comment by nixgates** [comment]
@somexone ok that makes sense then, this is TMDb providing metadata translated for the region set in kodi.

If you like, you can switch your meta provider to Trakt and that should take care of that.

**Comment by somexone** [comment]
@nixgates i would be curious as to how exactly do I change the metadata provider to trakt? 

It's working fine and everything is English with it all set to US English but I definitely prefer the region set to Canada even tho they are very similar.

**Comment by nixgates** [comment]
@somexone just in the interface settings.

You can set a preferred meta data provider :)

**Comment by somexone** [comment]
@nixgates oh wow I completely missed that option. I will keep that in mind.

It's working fine set to US English. Everything is fine except weather was changed to F and we use C but that was an easy fix. Other than that US English region is pretty much same. 

Long as all the titles and artwork is in English is my main concern and switching to the US region fixes it. 

I have no idea why the Canadian region throws up random French titles. If I was fully bilingual I wouldn't really care tbh lol. Being Canadian I do know some French though but not enough to watch a whole movie or show in it.

**Comment by nixgates** [comment]
@somexone haha i can understand that, yea unfortunately there isn't much I can do from my side :(

**Comment by somexone** [comment]
@nixgates i understand that! I am glad I at least figured out the issue.

I am fine with the US region. At end of day it is still in English which is all I wanted.

Cheers :)
