### ISSUE TITLE
[BUG] TV Shows That are Organized by Parts(Netflix) instead of Seasons in TVDB show an incorrect number of seasons.

### ISSUE THREAD

**Issue by SupernovaDML** [nixgates/plugin.video.seren#336]
You can replicate by searching for The Chilling Adventures of Sabrina both in Seren and in TVDB.

**Comment by LoganWolverineX** [comment]
This isn't a bug by Seren.  This is the fault of how the files are named.  They should be following the naming based on Trakt/TVDB.  For those, you'll either have to watch it from My Files or rename them from PM cloud after it's cached in your PM cloud.

**Comment by nixgates** [comment]
@SupernovaDML as Logan has mentioned this is a fault with the meta data coming from Trakt and not Seren.

I do intend to look at a way to maybe fix this in the future but it's a very technical job which may not be possible. 

Closing bug
