### ISSUE TITLE
[BUG] Invalid info dict passed to Kodi

### ISSUE THREAD

**Issue by BinaryAssault** [nixgates/plugin.video.seren#337]
Running Kodi v18.9 on RPI4 using LibreELEC v9.2.6
Seren v2.0.8

Each time I try to open my TV Show collection I receive the following snippet:

>ERROR: EXCEPTION: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
>2021-01-04 15:59:08.627 T:2009166704   ERROR: SEREN: Traceback (most recent call last):
>                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/list_builder.py", line 177, in _common_menu_builder
>                                                if item is not None
>                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/globals.py", line 1052, in add_directory_item
>                                                item.setInfo("video", info)
>                                            TypeError: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
>2021-01-04 15:59:08.627 T:2009166704 WARNING: Attempt to use invalid handle 1
>2021-01-04 15:59:08.636 T:2009166704 WARNING: Previous line repeats 2 times.
>2021-01-04 15:59:08.636 T:2009166704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                            Error Type: <type 'exceptions.TypeError'>
>                                            Error Contents: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
>                                            Traceback (most recent call last):
>                                              File "/storage/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
>                                                router.dispatch(g.REQUEST_PARAMS)
>                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 266, in dispatch
>                                                tvshowMenus.Menus().my_shows_collection()
>                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/indexers/trakt.py", line 71, in wrapper
>                                                return func(*args, **kwargs)
>                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 256, in my_shows_collection
>                                                self.list_builder.show_list_builder(trakt_list, no_paging=paginate, sort=sort)
>                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/list_builder.py", line 114, in show_list_builder
>                                                **params
>                                              File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/list_builder.py", line 190, in _common_menu_builder
>                                                raise e
>                                            TypeError: Failed to convert to input type to either a std::string or a std::vector<(XBMCAddon::xbmcgui::InfoLabelStringOrTuple)>
>                                            -->End of Python script error report<--

**Comment by BinaryAssault** [comment]
Any workaround for this? It prevents any of my Trakt collections from loading at all.

**Comment by nixgates** [comment]
@BinaryAssault is this still causing you grief? Apologies, been a little side tracked and haven't had a chance to really get in touch with yourself

**Comment by BinaryAssault** [comment]
Hey @nixgates ! No worries man! Still causing me grief with 2.0.13 unfortunately. Surprised no one else has complained about it. I cannot pull my Trakt collection at all. I can check my log and see if the exceptions changed or not if you'd like.

**Comment by nixgates** [comment]
@BinaryAssault i have seen on some devices that a wipe doesn't work correctly back in 1.0 so maybe try a rebuild of the trakt sync database if you havent already. 

May I ask how many items are in your collection? Is it small enough to list easily enough here?

**Comment by BinaryAssault** [comment]
The collection I have is for TV shows only; and currently it has 328 shows. I don't know how to share the list.

**Comment by nixgates** [comment]
@BinaryAssault yea if you'd like, I'll try and recreate it on my end and see if I can't make it break.

If you want you can drop it here or if you like, you can PM me it on reddit:+1:

**Comment by BinaryAssault** [comment]
Sent the info over on reddit for you. Interesting fact, on a fresh install (on W10) with a fresh build of Kodi, same error occurs for me.

**Comment by BinaryAssault** [comment]
@nixgates - I didn't fix the issue but I found out where it originated from. It seemingly is coming from 
>  #def add_directory_item(self, name, **params): 
in globals.py

This line was the last line that occurred prior to crashing:
> {u'name': u'Mini Adventures of Winnie the Pooh', 'args': u'%7B%22mediatype%22%3A%20%22tvshow%22%2C%20%22trakt_id%22%3A%2072438%7D', 'episode_count': 40, 'cast': [], 'trakt_id': 72438, 'watched_episodes': 0, 'unwatched_episodes': 40, 'season_count': 2}

I found this by jumping through the Web-PDB debugger. 

So I went to Trakt and removed that show and I can see my collection again. I googled the error a bit and see that in the past this issue has been brought up (elsewhere) when passing either a null or None here; but that isn't the case. For me it's not a big deal to just remove the show and keep on keeping on. 

Off topic, what is it you use for debugging? I am use to an IDE (non-python dev here), so the web-PDB was something different for me.

**Comment by bmsinc** [comment]
For whatever it’s worth I am having the same issue and a full add on wipe and several rebuild attempts/authorizations does not fix the problem for me. I am able to see my movie collection. Not my show collection. I had a chat about this in the discord and someone is going to put my error log here as well. But I am having the EXACT same issue as is outlined above.

**Comment by inb4after** [comment]
> 
> 
> For whatever it’s worth I am having the same issue and a full add on wipe and several rebuild attempts/authorizations does not fix the problem for me. I am able to see my movie collection. Not my show collection. I had a chat about this in the discord and someone is going to put my error log here as well. But I am having the EXACT same issue as is outlined above.

@nixgates @bmsinc Here are the logfiles for @bmsinc, who is getting the same issue :

http://paste.kodi.tv/yineqecola
https://paste.kodi.tv/kovigufiqo

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.

**Comment by bmsinc** [comment]
This issue still persists for me. 

https://paste.kodi.tv/xetekoduyo

**Comment by bmsinc** [comment]
@drinfernoo  can you please reopen this.  i still cannot access my tv show collection in the new version.  log above
