### ISSUE TITLE
[BUG] Invalid PM account enabled causes scrape exceptions

### ISSUE THREAD

**Issue by streamindemons** [nixgates/plugin.video.seren#338]
Using a 2017 shield, kodi 18.9, seren 2.0.9

First, I have my Smart Play popup set to play if nothing is selected and that does not happen. 

Upon finish of an episode in Scrubs season 9, when I go to play the next episode the scraping window pops up briefly showing "starting engines" then fades away and gives me a seren error. This can be fixed by clearing local torrent cache, but is a very weird issue. Only effects episodes in scrubs season 9 from my testing. Force stopping kodi does not fix it which I was surprised to see.

Expected Behavior: The next episode starts to play when the episode ends because of the play on nothing selected. Being able to manually scrape for the next episode without having to clear local torrent cache every time.

Here is a log (https://paste.kodi.tv/ewuvigeyul) that shows the errors, i clicked it multiple times so its a big log.

Sorry to be piling on, I know you have been working hard on this and I appreciate it greatly!

**Comment by nixgates** [comment]
@streamindemons looks like your PM auth is dead, try re-authing.

I'll a notification so there is some feedback for this moving forward

**Comment by streamindemons** [comment]
> @streamindemons looks like your PM auth is dead, try re-authing.
> 
> I'll a notification so there is some feedback for this moving forward

Yea i keep forgetting to disable that, had a trial lol. will send a new long with it disabled if the issue still happens

**Comment by streamindemons** [comment]
> @streamindemons looks like your PM auth is dead, try re-authing.
> 
> I'll a notification so there is some feedback for this moving forward

That seems to have fixed it for now, will keep this open for a day or so and update if that fixed it for good

**Comment by nixgates** [comment]
@streamindemons thanks for trying that, I'll add it to the list for the next update

**Comment by streamindemons** [comment]
> @streamindemons thanks for trying that, I'll add it to the list for the next update

If I could add one around the same thing, having AD added with no auth gives multiple "failed to connect to AD" (something along those lines) during scraping, usually about 4

**Comment by nixgates** [comment]
@streamindemons could you provide the log for that one, need to see where the errors are generated :)

**Comment by streamindemons** [comment]
@nixgates https://paste.kodi.tv/rifazowaci

there you go, exact words are "seems to basically be the same issue as the PM one, scraping stops after hitting ok on the popup

**Comment by nixgates** [comment]
@streamindemons this should be fixed now in 2.0.10

Could you please confirm for me 👍

**Comment by streamindemons** [comment]
@nixgates fixed!

**Comment by nixgates** [comment]
@streamindemons thanks bud!

Closing it off!
