### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by GoonerMagic** [nixgates/plugin.video.seren#339]
**Is your feature request related to a problem? Please describe.**
Preemptive Termination causes Seren to stop before higher quality links are found.
Eg. Found 5 4K, upto 20gb. Preemptive Termination (PT) (as per my settings, 5x4k links for Movies) halts search. If PT is turned off, it would find links 70GB+

**Describe the solution you'd like**
A minimum files size slider option in PT, separated by content (Movies \ Tv Shows), for PT to find before stopping.
EG- 
Movies, 
Minimum Resolution 4k
Minimum links 5
Minimum File size 60GB
TV Shows, 
Minimum Resolution 1080p
Minimum Links 5
Minimum File size 2GB

**Describe alternatives you've considered**
I couldn't find another solution in Seren 2.0

**Additional context**
None, but great job in Seren 2.0! Seren had been my primary add-on since release

Many thanks for taking a look at this request!

**Comment by nixgates** [comment]
@GoonerMagic this is the design of PT. 

If you really want to make sure you get all possible links, you should disable pre-termination. It's purpose is to be there for people who are not to fazed about the file size or other details. Pre-termination is a tool to say give me 1080/4k and give me x so I can be sure one works.

I'd rather not over complicate the feature as many people struggle with it already.

Apologies I couldn't help you here :(

**Comment by GoonerMagic** [comment]
Damn. That's a shame!
Perhaps if that part was set to '0" by default, anyone confused wouldn't need to worry about it.

I saw someone asking for a minimum File size filter, which would also be useful, however if that was the only option, then older movies or hard to find shows would probably return no results, after filter.

Is there any way you would reconcider?

I'm not asking this to be done immediately, I'm more than happy to wait, as I'm sure you have a lot in your plate right now after the latest release.

**Comment by nixgates** [comment]
@GoonerMagic ha, why not lol.

**Comment by GoonerMagic** [comment]
That's amazing! I really appreciate the change of heart, and I will patiently wait for whenever you have time to implement.

Cheers
