### ISSUE TITLE
[BUG] Smart play not working with Open Info/Meta

### ISSUE THREAD

**Issue by rpounds1986** [nixgates/plugin.video.seren#340]
First and foremost, great work on this update! It's nice to see a dev continue supporting and improving their work!!

Issue:

I use Open Info/Meta to add TV Shows and Movies to the library. Movies are working fine, but playing TV shows with Seren (Smart Play) just spins. If I switch to just Seren it works fine.

1. Go to TV shows
2. Click on TV show IE Game of Thrones
3. Select Season and episode
4. Select Seren (Smart Play)
5.  Spins

Expected behavior:
Start engines, source select

 - Kodi Version 18.9.0 Leia
 - Seren version 2.0.9

**Comment by nixgates** [comment]
duplicate issue

Please refer to #308
