### ISSUE TITLE
[BUG] Implement error skipping if a debrid service is down

### ISSUE THREAD

**Issue by inb4after** [nixgates/plugin.video.seren#341]
When a single debrid service is down, scraping will return an error and content will be unwatchable. However, other debrid services may still be working and scraping can be done on those instead, while skipping the dead service. 

For example, PM is currently down and scraping results in an error. Disabling PM in settings fixes this and allows scraping to start, using RD/AD. If the error was automatically detected and debrid service skipped, the user won't have to check logs and disable the service causing the error.

**Comment by nixgates** [comment]
Its actually already in the pipeline for a seperate bug. Will be available next update. Apologies for this.

**Comment by inb4after** [comment]
Glad to hear, thanks in advance! 👍

**Comment by nixgates** [comment]
@inb4after please reference bug #338 for further information 👍 

closed as duplicate
