### ISSUE TITLE
[REQUEST] Show information when you click on TV show items

### ISSUE THREAD

**Issue by iscriptu** [nixgates/plugin.video.seren#344]
Hi,

I've wanted Seren to show the TV show information when clicking on a TV show instead of showing me seasons/episodes view, like it does with widgets since last year but was told that it was impossible at the time. I know that you've already added this for episodes and movies in Seren 2.0 but it would be really awesome if you could also do it for TV shows. I hope you agree.

Thanks for reading

**Comment by nixgates** [comment]
@iscriptu this is being removed because as I did suspect last year, it's just to hard to implement. Unfortunately it conflicts with the kodi setting to much and causes lock ups. 

Please see bug #324
