### ISSUE TITLE
Watch progress gets stuck after first pause

### ISSUE THREAD

**Issue by lowersublobia** [nixgates/plugin.video.seren#347]
**Describe the bug*
Watch progress is getting stuck if you pause the video that is being played

**To Reproduce**
1. Start Video
2. Pause any time
3. Finish video 

**Expected behavior**
A check mark indicating a watched episode should appear next to title of episode , but instead the “partially watched” icon displays beside episode. When episode is selected , it asks if you’d like to resume at the time the video was paused first, even tho you unpaused and finished episode.

**Kodi Version (please complete the following information):**
 - Kodi Version is most recent stable release.

**Comment by nixgates** [comment]
Please refer to bug #281

With any luck, this should be resolved after the next update

Closing duplicate
