### ISSUE TITLE
[BUG] Trakt not Authorizing 

### ISSUE THREAD

**Issue by gio2490** [nixgates/plugin.video.seren#348]
**Describe the bug**
I decided to re-install Seren and now I am unable to authorize Trakt. I get a successful message that it has been auth, but when clicking ok I then get an error to check the log. 

**To Reproduce**
1. Seren
2.Settings
3.Providers 
4.Auth Trakt 
5. Go through auth on web browser 
6. Successful message 
7. Ok

**Expected behavior**
Trakt should authorize and account info should populate under accounts 

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Version 2.0.9
 - [LOG](https://paste.kodi.tv/hekigafito)

**Additional context**
Everything was working fine until today. Had updated to 2.0.9 and worked fine until today. 
As of today, I’ve been unable to play any shows and getting an error to check the log. 
I’ve tried to rebuild database, clear cache, clear torrent cache, update scrapers with no avail.

**Comment by nixgates** [comment]
@gio2490 howdy, something is really, really wrong with your TraktSync Database and your skins database. Some how they have both lost tables.

You might need to remove the files manually to continue, a rebuild will only error out. If you're unable to browse the files on your TV to delete the files, you can do a full wipe of your Seren install. 

I'm hesitant to tell you to do a full wipe as it doesn't tell me how this happened :( 

But the information in the log won't tell me either and you need to get back up and running.

**Comment by gio2490** [comment]
Thanks for looking into this! 

I have done a wipe of Seren and that’s when the Trakt issue started for me. On an other TV running on an Amazon Fire TV with no skin was having the same issue. 

Seems like a few others are also reporting on Reddit https://reddit.com/r/Addons4Kodi/comments/kr5yy9/seren_playback_failed/

I’ll try and do a clean install and report back in the morning.

**Comment by nixgates** [comment]
@gio2490 when you did the wipe, did you do it through Seren or a manual removal of the addon files?

**Comment by gio2490** [comment]
@nixgates sorry for the delay! I wiped the entire Kodi Addon from my device and re-installed it as new. This seemed to have fixed the issue. I have not installed a skin for the moment.

Happy to close the case as it's been resolved. Thanks as always, really appreciate what you're doing for the community!
