### ISSUE TITLE
[REQUEST] Seren will only list cached results?

### ISSUE THREAD

**Issue by rezpower** [nixgates/plugin.video.seren#349]
Maybe I have missed a setting and my Seren is not correctly configured [In this case please let me know what to do]

Seren is the best and normally I should be using ONLY seren! But for only one reason I am using other add-ons and I wish seren would also behave like them:
When I search for a movie, seren gives me results from cached content on my Premiumize account. So if there is any cashed version available seren will list them. If no cached content is found then seren propose to cache it for me on my cloud. The problem is that often there is a low quality cached version found and my only choice is to get that file. Why seren dose not list available cached files "as cached" and still propose other non cached versions so I can choose and download the version I want?

There could even be a setting to enable/disable such feature in settings. This would be a game changer for me :)

**Comment by LoganWolverineX** [comment]
in the result screen, there's an option for you to view the uncached results ones. it's below the "play" button on the right side of the screen.

**Comment by nixgates** [comment]
@rezpower as Logan pointed out, its in the source select screen :)

Closing off, request already fulfilled.

**Comment by Samgarr** [comment]
It would be nice to have option to display uncached content to result view. I propose adding two options:

- display uncached content on result view
- add option to sort by cached/uncached

**Comment by nixgates** [comment]
@Samgarr im sorry its really just one button press away on that screen and after its completed its added to the source select screen so you can select and play it so I won't be adding it to the general source list.
