### ISSUE TITLE
[REQUEST] Seren doesn't search IMDb to grab correct Season lists

### ISSUE THREAD

**Issue by dreulavelle** [nixgates/plugin.video.seren#352]
So Seren searches other websites for metadata such as Season lists. After looking into this a little bit I've noticed it doesn't display the correct amount of Seasons on some shows. For example when looking up "Chilling Adventures of Sabrina" it only displays the 2 seasons (as shown on TMDb/TVDb and others). However I've found that IMDb displays the correct amount of seasons. 

**Describe the solution you'd like**
Ability to scrape IMDb for Metadata/Season info.

**Describe alternatives you've considered**
Haven't found one yet unfortunately. Would love Seren to be my One-and-Done addon though, love your work!

**Comment by nixgates** [comment]
@dreulavelle howdy! 

Yea it was raised as an option not long ago. While its not currently being worked on, a few changes to the IMDB site made this a viable and speedy option.

I'll leave this open as adding IMDb as a meta provider is definetely on the cards :)

**Comment by dreulavelle** [comment]
Perfect! Thank you so much!

**Comment by SerpentDrago** [comment]
to better explain also . 

the reason imdb was never used for meta info , even though it tends to be the most accurate and is what the scene uses for naming of files .  Is before now , there was NOT WAY / NO proper fast way to gather that meta info .  IMDB site had to be manually scraped and their was no api , this results in LOTS of data and is very slow .  

Now a new method is been discovered and it should be a thing nix could do in the future
