### ISSUE TITLE
[REQUEST] Play local library files

### ISSUE THREAD

**Issue by Navios92** [nixgates/plugin.video.seren#353]
This was requested a few times on reddit, so I figured I'd post it here for easier tracking.

**Describe the solution you'd like**
If the movie or episode was already available in the local library, Seren could either directly play it without scraping online sources. Or scrape it first and show it on the top of Source Select menu, with an option in Settings to terminate if local sources found.

It would be also very helpful if we could have a context menu option (maybe Rescrape Item?) to force checking for online sources anyway.

**Comment by FerGitH** [comment]
Hi,

I subscribe to this request. If you could add it, it would be great, as we could have a single widgets that covers all our movies and TV shows, no matter where they are.

Thanks for you work

**Comment by drinfernoo** [comment]
Use something like TMDbHelper for this. It will play from library files first, or select a player for playback if no local file is found.
