### ISSUE TITLE
[BUG] Next page showing in Next Up (Non-paged menu)

### ISSUE THREAD

**Issue by Navios92** [nixgates/plugin.video.seren#354]
So, the option to paginate trakt lists doesn't seem to affect Next Up list. This has always been the case and I personally prefer it that way. However, Next Item is still shown in the Next Up list, which seems unnecessary.

**Comment by nixgates** [comment]
Ah ok, in regards to the next option, thanuflly it's a minor issue and will be easy to fix it up. Expect it next update.

For the paginated lists, I think it might help to change the setting to user lists as I believe thats what it covers of the top of my head. Will need to investigate further to be sure.

**Comment by Navios92** [comment]
I just noticed that Recently Watched shows list has the same problem. No pagination but Next Item shows up anyway.

I checked all lists and I can see that Paginate Trakt List option affects everything except for Next Up, Recently Watched shows and Collection (which already has its separate setting).

Thank you for your dedication and keep up the great work :)

**Comment by nixgates** [comment]
@Navios92 thanks for that! I'll fix up Recently Watched as well then close this off after the next update :)

**Comment by nixgates** [comment]
@Navios92 this is fixed in commit 2952f86242bad8b21ab17e5b584fe8a3039f78e2 (2.0.14)

Thanks for letting me know :)

**Comment by Navios92** [comment]
> @Navios92 this is fixed in commit [2952f86](https://github.com/nixgates/plugin.video.seren/commit/2952f86242bad8b21ab17e5b584fe8a3039f78e2) (2.0.14)
> 
> Thanks for letting me know :)

Everything's working as it should now. Thanks for fixing it :)
