### ISSUE TITLE
[BUG] Hide watched setting hides unwatched items

### ISSUE THREAD

**Issue by MagicFirefly** [nixgates/plugin.video.seren#356]
Version 2.0.10 and prior...
The below occurs when Hide Watched is enabled in settings. When Hide Watched is disabled, the episodes display.

My Shows > Watchlist > select a show > No episodes displayed (only two dots shown)
Discover Shows > Trending > select a show > No episodes displayed (only two dots shown)

Log: [https://paste.kodi.tv/vezodafema](https://paste.kodi.tv/vezodafema)

**Comment by nixgates** [comment]
@MagicFirefly i know it sounds silly to ask, but are the episodes marked as watched when you have hide watched disabled?

Have you watched the episodes before?

**Comment by MagicFirefly** [comment]
With Hide Watched disabled, the episodes do not appear as watched. The episodes have never been watched.

**Comment by nixgates** [comment]
@MagicFirefly all good, thanks for the info :)

Will get it fixed up soon!

**Comment by nixgates** [comment]
@MagicFirefly could I ask you if this is still an issue? I believe this was fixed a little while ago but just need some confirmation

**Comment by MagicFirefly** [comment]
@nixgates Yes. This is only for the TV shows area. In addition, there's is another issue found with Hide Watched and Hide Un-Aired Items being separate settings. With Hide Watched enabled and Hide Un-Aired Items disabled, the un-aired show titles are hidden. Would you suggest a Wipe Data and start fresh?

**Comment by nixgates** [comment]
@MagicFirefly id much rather get this sorted if you're ok to continue helping? 

There should never be a need to remove kodi to fix anything for Seren. You can do a wipe of Seren in the shortcuts section of the settings. That should do anything that a uninstall of kodi could do to fix anything. 

If you want to give that a go you're more than welcome. I can't reproduce this at all anymore so I'm having a bit of trouble fixing it lol.

If you could, perhaps you can send me a picture of your interface settings, or list them to me? I can then set them all the same and see what happens.

Also, maybe try the wipe of Seren yourself and see if that doesn't fix it. If you wipe seren you will need to set it back up from scratch though so take that in to consideration.

**Comment by MagicFirefly** [comment]
@nixgates Did the wipe, restarted Kodi. Left all settings as default. Added 4kS, RD and Trakt auths. It didn't help with the Hide Watchlist issue for My Shows/Watchlist. Keep in mind the Movies area is unaffected as well as My Shows/Next Up.

With Hide Watched enabled, I rebuilt the Trakt database to find My Shows/Watchlist contained no content at all. The show titles only display after disabling Hide Watched. The titles continue to display with Hide Watched re-enabled but there are no seasons or episodes. With Hide Watched disabled, the show titles, seasons and episodes display.

If you would like to continue to troubleshoot with a fresh start, I can do another wipe and go from there. Let me know what steps you would for me to follow after the wipe. That said, if you feel this is a one-off that does not warrant the time, I'm okay with disabling Hide Watched while in the My Shows area.

**Comment by MagicFirefly** [comment]
After adding Arctic Horizon skin, unwatched TV shows started to show up with Hide Watched enabled. When first rebuilding the Trakt database, the issue persists; however, after toggling skins it works. Because there are not many others experiencing this issue I've closed the ticket. The issue can be reproduced with a fresh install of CoreELEC and Seren on a fresh SD card with nothing else changed except for adding a Trakt authorization. If you wish to pursue this in the future, reopen the ticket and contact me.
