### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by djdirty60** [nixgates/plugin.video.seren#357]
**Describe the bug**
series remain empty

**To Reproduce**
1. Go to 'TV-Series 
2. Click on 'does not matter'
3. Scroll down to 'does not matter'

**Expected behavior**
every series I click on remains empty, no episodes or seasons appear.

**Screenshots**
![1609926177008199805792912763084](https://user-images.githubusercontent.com/13561831/103753960-fc23d080-500b-11eb-9497-90e5cf15c271.jpg)
![16099262039278639738773054299755](https://user-images.githubusercontent.com/13561831/103753991-06de6580-500c-11eb-9f49-0c3115b0c88a.jpg)

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9.0
 - Coreelec 9.2.5
 - Linux 4.9.113 aarch64

**Additional context**

**Comment by nixgates** [comment]
@djdirty60 can you check if you have the hide watched setting enabled in Seren's settings (note, not the kodi one)

This was just identified by another user, just want to confirm if it's the same

**Comment by djdirty60** [comment]
> @djdirty60 can you check if you have the hide watched setting enabled in Seren's settings (note, not the kodi one)
> 
> This was just identified by another user, just want to confirm if it's the same

issue was indeed watched episodes setting, problem solved

**Comment by nixgates** [comment]
Thanks, closing off as duplicate - #356
