### ISSUE TITLE
[REQUEST] Reverse direction option(s) for Next Up sorting

### ISSUE THREAD

**Issue by inb4after** [nixgates/plugin.video.seren#358]
Currently, sorting Next Up by "Release Date" will place the latest show episode on the left end of a widget. For watching multiple shows in release order, the user will have to scroll fully to the right each time they open Kodi to find the oldest show (which needs to be watched first). 

A reverse toggle or further options within the cycle list would ensure better customizability for the Next Up row, in both widgets and Seren itself. 

There would also be less button presses involved from Kodi starting and watching the oldest show. This can be incredibly useful when watching multiverse shows in order. 

Furthermore, if a user wishes to sort by "Recently Watched", the reverse option would allow the oldest (in terms of unwatched) show to also appear on the left of a widget, which shortens the button presses between finishing an episode of a show and watching the second oldest show (in terms of unwatched).

**Comment by nixgates** [comment]
@inb4after might I suggest the following addon https://kodi.wiki/view/Add-on:Keymap_Editor

This will allow you to bind something like a long press to the "end" button which will skip to the end of the list. Or if you're on a PC, you can already do so by simply pressing the end button on your keybaord.

**Comment by inb4after** [comment]
I understand that it's an ultra-low priority request at the current time.

However, I believe it to be an important feature, for future consideration, for three further reasons:

- Depending on the skin used, the visual aesthetic is interrupted if the wanted item is on the far right. For example, in AuraMod, a preceding item is partially cut off when the last item is highlighted. It is also more aesthetically intuitive to select/work through items from left to right if using a left side-based menu system.

- Keymapping does not provide a workaround for episodes in between the first (on the left) and the last (on the right) and user would still have to scroll / move further than necessary. 

- The keymap method also assumes the user is using a control device with 1-2 available keys (last page/next page, if needed) and even then, requires an extra keypress compared to already having the list sorted in a reverse or normal order. Specifically for AndroidTV / TV devices, it is less device-friendly/intuitive to workaround in this manner.

**Comment by inb4after** [comment]
@nixgates Sent you a message on discord, check it out when you can ☺
