### ISSUE TITLE
Nextup showing episodes a day later

### ISSUE THREAD

**Issue by hockeymachine86** [nixgates/plugin.video.seren#36]
In Seren it is showing TV Episodes air date as one day later than their actual air date.  For example, Big Bang Theory shows air date as 2/1 in Seren, but 1/31 in Trakt and TVGuide.

**Comment by mophawka** [comment]
can confirm this finding. Currently watching tonight's episode of Arrow although it is dated for tmrw on Seren under TV collections and not showing up at all on under nextup. this is a recent change in Seren. can't verify what version last worked. Using .29 atm> trakt is dated correctly. Thanks

**Comment by nixgates** [comment]
@mophawka @hockeymachine86

This issue should be resolved with update 0.1.34.
Could you please ensure you date and time and correctlly set on the device and confirm on your end?

**Comment by hockeymachine86** [comment]
Just checked and it looks like its fixed.  'The Rookie' which aires 2/19/2019 (USA CST) and it shows in the list.  Thanks!
