### ISSUE TITLE
[BUG]Seren 2.10 keep on asking for Trakt authentication even when said No

### ISSUE THREAD

**Issue by minhgi** [nixgates/plugin.video.seren#360]
**Describe the bug**
Using Kodi 18.9,  Titan Bingie Mod 1.09 skin setting, and Seren 2.10 for two different builds. One with trakt account and one without.  The one without keep on asking for Trakt authentication even when said No or reloading the skin. 

**To Reproduce**

**Expected behavior**
Previous Seren v1.16.XX stop asking for Trakt logon when saying NO. The widget row would be bypass and not need/show up on the homescreen. 

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [18.9]
 - Version [2.10]

**Additional context**

**Comment by nixgates** [comment]
@minhgi this isn't a bug so much as a new protection put in to prevent users expecting these widgets to work and not realising their trakt account is not set-up.

To stop the errors, you need to remove the widgets that point to Trakt account menus or authorise a trakt account in Seren on the device.
