### ISSUE TITLE
[REQUEST] Playlist Creation option for My Files items

### ISSUE THREAD

**Issue by sathish804** [nixgates/plugin.video.seren#361]
At the moment for the debrid cloud content from My Files section can only be played one at a time and there is no option of playing them one after the other like a play list. 

Solution

When an item is played from the My Files, populate an option for the user to create playlist for other items from the same folder like episodes in a season to play one after the other. Integration of Smart play option in to the playlist created would be a great option.

**Comment by nixgates** [comment]
Great idea! Once we are stable ill work on adding it in!

**Comment by sathish804** [comment]
@nixgates  Hi Nix, Please re-open this feature request. Its auto closed by the stale bot.
