### ISSUE TITLE
[BUG] upcoming episodes 

### ISSUE THREAD

**Issue by djdirty60** [nixgates/plugin.video.seren#362]
**Describe the bug**
https://paste.ubuntu.com/p/dnNxYtgh38/

**To Reproduce**
1. Go to 'my tv shows
2. Click on 'upcoming episode

**Expected behavior**
Do nothing 

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Version Coreelec 

**Additional context**

**Comment by djdirty60** [comment]
Fix it

**Comment by Wilson-Magic** [comment]
Don't act entitled. He would have fixed it when he got the chance if you didn't close it.

Remember, he doesn't owe you anything, stop acting like he or anybody related does.

**Comment by djdirty60** [comment]
I have found the problem, for me it is solved for now.  He can still solve the problem.  So don't really understand your problem.
