### ISSUE TITLE
[BUG] Text on link results screen is huge when using titan/binge skin

### ISSUE THREAD

**Issue by ljransom** [nixgates/plugin.video.seren#364]
**Describe the bug**
On the link results screen the text size for file names is very big. I've compared this to another skin which seems fine. The provided screenshots show the difference

**To Reproduce**
1. Select a show or movie and scrape for links using the titan/binge skin
2. Observe how big the text is

**Expected behavior**
Text should be in line with other skins. This issue was not present pre 2.0

**Screenshots**
![IMG_20210106_172755](https://user-images.githubusercontent.com/76923908/103804183-98b89380-5049-11eb-96b3-26b1e8efb5e7.jpg)
![Screenshot_20210106-180336~2](https://user-images.githubusercontent.com/76923908/103804211-a3732880-5049-11eb-8454-5d4f05877741.jpg)

**Kodi Version (please complete the following information):**
 - Kodi Version: 18.9
 - Seren Version: 2.0.10

**Additional context**

**Comment by Nuklear92** [comment]
Original issue can be found in #293 we are awaiting for @nixgates to reply back. If you want you can delete this post and keep an eye on #293 until a fix is made.

**Comment by nixgates** [comment]
@Nuklear92 yea best to keep the one issue, if you wouldn't mind posting your images and text there wi the others can see it that would be great! 

Seems an issue with some skins and not so much the default Seren addon.

Some custom themes may need to be created to support these themes as they look like they overwrite some default kodi fonts or ive messed up the fonts. Need to identify which.

**Comment by nixgates** [comment]
Sorry should have closed this before, please refer to #293
