### ISSUE TITLE
[BUG] Xbox One Building Database

### ISSUE THREAD

**Issue by bthedorff** [nixgates/plugin.video.seren#365]
**Describe the bug**
On Xbox One it will rebuild the Trakt database on start every time and every 20(?) minutes or so. If I click rebuild database from within the setting, it fails and gives an error. I can however force Trakt sync. I have a hunch it is failing to complete sync even though the notification goes away. When I open my Trakt collection, I only have 3 pages (22 total shows) when I should have more than that. 

Edit: It has also caused my Kodi to crash. Sometimes I will be watching a show, and Seren will try to rebuild the database then in the middle of it, Kodi will crash. 

**Kodi Version (please complete the following information):**
 - Kodi Version: 18.9
 - Seren Version: 2.0.10

**Additional context**
Log: https://paste.kodi.tv/cigehewecu

Edit 2:
Log 2: https://paste.kodi.tv/okeziyumox
This log has the error when I I go into settings, Trakt tools and click rebuild database. My first log didn't have that.

**Comment by McPoon** [comment]
I have the same issue on Xbox Series X.

**Comment by nixgates** [comment]
@bthedorff yep, I cannot what's happening, the datetime module strikes again. Been a few from this release.

Theres a plan in place to completely remove the use of that addon and implement a different method that should clear all these up. 

Hold tight, hopefully we get it going next update.

**Comment by bthedorff** [comment]
@nixgates Thank you! Can't wait to try 2.0! Let me know if you need anything else done on the Xbox One, any logs or anything!

**Comment by nixgates** [comment]
@bthedorff fix has been found. Just need to work out a way to identify an xbox and then there will be a fix in the next update 👍

**Comment by fairlynew** [comment]
So, is this going to happen, or..

**Comment by bthedorff** [comment]
@fairlynew Gotta be patient man. It's a one man project done in his spare time.

**Comment by nixgates** [comment]
@bthedorff this should be resolved in 2.0.11+

Could you please let me know how you go?

**Comment by bthedorff** [comment]
@nixgates Thank you for the update! Unfortunately now I am unable to access the setting to reauth Trakt. No options arrear except for Ok, Cancel and Defaults. I am not even able to navigate to them. I tried clearing cache in Seren and tried changing to the default skin, neither worked. My current skin is AeroMod. I will attach a log in case that can help you. I will also get a picture if needed.

https://paste.kodi.tv/tamoladoti

**Comment by bthedorff** [comment]
@nixgates I was able to reauth Trakt by going to Settings -> Trakt sync tools then it brought up needing to authorize Trakt and it worked from there (t least successful). I then closed out of Kodi and reopened and it says I need to reauthorize again. I attached a log in case anything is there that can help.

https://paste.kodi.tv/acuwawayew

**Comment by nixgates** [comment]
@bthedorff sorry, I do have this fixed already for another update, it was identified just after the update the went out to fix the trakt keys. I held off in case the trakt team still had issues.

Now they've let me know things are looking good ill push another out today :)

**Comment by bthedorff** [comment]
@nixgates Thanks! I'll keep an eye out for the update then report back!

**Comment by bthedorff** [comment]
@nixgates Unfortunately I am still unable access the settings menu. I also tried to add trakt by going to Trakt Sync Tools and I get an error saying Unable to contact Trakt, check the outage status. I did check and at the time everything is fully operational according to their site.

**Comment by bthedorff** [comment]
> @nixgates Unfortunately I am still unable access the settings menu. I also tried to add trakt by going to Trakt Sync Tools and I get an error saying Unable to contact Trakt, check the outage status. I did check and at the time everything is fully operational according to their site.

@nixgates I just updated to the newest version 2.0.15 (Thank you!) and unfortunately, the above is still true, Settings is still inaccessible. Except I could authorize with Trakt, but it didn't save.

https://paste.kodi.tv/alelewipij

**Comment by nixgates** [comment]
@bthedorff i know this aint great, but something is borked with your settings file. Kodi can't read it so we really aren't going to get going until we fix that. 

Unless you're able to manually browse the files on the xbox to delete the file manually, I'd suggest using the "Wipe Addon Data" option in the tools menu.

You're going to have to reset up your debrid accounts and auth trakt again, but it will get us back on track.

**Comment by bthedorff** [comment]
@nixgates So I wiped the add-on data, was able to connect to Trakt and build the database, settings worked as well. As I'm trying things out, it looks like Collections for TV Shows won't open, but everything else I've tried does, (movie collections, TV lists, Watchlist). I don't think that is a Trakt is but I did rebuild the datas and it still gives an error. Kodi crashed before I could get the log, so I will add it in shortly.

**Comment by nixgates** [comment]
@bthedorff alright well we are getting closer lol!

I'll look into the collections issue and see if we can't fix that up as well.

**Comment by 101ben1011** [comment]
Just thought I'd drop a quick note to say I have the exact same issue on series x,  Accounts seem to be authorising fine now, but the tv collections page won't open, 
Thanks for your efforts in trying to get this working on a fickle device that you don't have access to lol.

**Comment by bthedorff** [comment]
@nixgates You might want to check TV show Recently watched too. That doesn't open either, my guess is it could be the same issue. I'll add the log either way.

https://paste.kodi.tv/xeqewufahe

**Comment by bthedorff** [comment]
Hey @nixgates ,

It's been a while so I'm just checking in. Were you able to fix this issue? Any way I can help with logs or anything? I know you work on this on your free time so no rush. Just wanted to check in!

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
