### ISSUE TITLE
[BUG] my watchlist shows Seasons marked off as watched

### ISSUE THREAD

**Issue by xyzfre** [nixgates/plugin.video.seren#366]
**Describe the bug**
Every show on my watchlist when clicking on a season all seasons show up Mark as watched 
**To Reproduce**
1. Go to  My TV Shows
2. Click on Watchlist 
3. Scroll to any TV Show on Watchlist ,,Season Cover will show no check mark but once you open a season all seasons have a check mark as watched 

**Expected behavior*.  When I pick a show from my Watchlist all seasons should NOT be marked off as watched because I haven’t even started that show yet.

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi 18.9 ,AuraMod Skin ,Seren 2.0.10 Context version 2.0.0 ,,Nvidia Shield 

I have tried to rebuild data and deleting TraktSync.db and Trakt.db.md5 files and also clearing cache but no luck

**Comment by xyzfre** [comment]
![91F1359F-213A-4174-90FA-98A957A41D90](https://user-images.githubusercontent.com/49699869/103817038-f4782200-5033-11eb-90fc-ebd1fb3b3091.jpeg)
Example shows on my watchlist

**Comment by xyzfre** [comment]
![97B0A915-6334-4F8E-949A-5D6284E57E95](https://user-images.githubusercontent.com/49699869/103817073-04900180-5034-11eb-9cba-130af63cf31b.jpeg)
Example ,American horror story ,, once I open the season they show up like this and I haven’t started not one episode yet

**Comment by xyzfre** [comment]
My apologies for opening another ticket I just felt like I explained myself a little better on this one and the first issue I opened was solve ,, so this is a totally different issue thank you for all your hard work my friend Seren is a legend

**Comment by nixgates** [comment]
@xyzfre can I ask you try add 2 new shows to your watchlist? One from Serens trakt manager, one from the trakt website.

Then open your watchlist and check the results?

**Comment by xyzfre** [comment]
So I tried like you said added one show through Seren Trakt manager and one from Track website but still the same issue,

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/103839234-eee30200-505c-11eb-9257-2f7ac75980bf.MOV

And now I just notice every show that I tried in most popular ,,trending etc.. as you can see in the video when opening the season all seasons are marked as watch except for my shows that are in progress that I started watching those show up correct

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/103839537-9b24e880-505d-11eb-88a8-336c612c7602.MOV

For example Dexter is one of my shows in progress as you can see in the video it shows the correct amount of seasons that I haven’t watched ,,really appreciate you taking time to checking this out

**Comment by xyzfre** [comment]
https://user-images.githubusercontent.com/49699869/103840422-8b0e0880-505f-11eb-88ea-171f15599a0a.MOV

I can confirm I just checked like 4 different shows that are in my next up and those definitely show the correct amount of seasons that I haven’t started watching , my apologies for the poor video quality

**Comment by nixgates** [comment]
@xyzfre all good, i think I get the idea.

So doesn't seem to be an issue of the Trakt watchlist but rather shows that don't have at least one watched item :)

**Comment by nixgates** [comment]
@xyzfre actually, this still seems to be a continuation of your last issue #310

I'm going to close this ticket off, let's stick to the same ticket if we can.

**Comment by xyzfre** [comment]
Ok @nixgates Thank you for your response and all your hard work really appreciate you checking this issue￼
