### ISSUE TITLE
[BUG] Tertiary HEVC Sort Preference

### ISSUE THREAD

**Issue by cartersball** [nixgates/plugin.video.seren#376]
**Describe the bug**
HEVC sorting method is not working. In post versions with this option enabled HEVC files were sorted to the top of list for each respective resolution. In 2.0 versions the files are not sorted to the top of list.

**To Reproduce**
1. Go to settings>sort& filter
2. Click on:
Source grouping style set to resolution
Enable Secondary Filesize Sort
Enable Tertiary HEVC Preference
Enable Quatenary Low Quality Sort Method
3. Perform a scrape
4. See HEVC files not sorted to top of list

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Version 2.10

**Comment by nixgates** [comment]
Thanks I'll look into this

**Comment by nixgates** [comment]
@cartersball Fixed in 2.0.13 :+1:
