### ISSUE TITLE
Trakt lists repeating 

### ISSUE THREAD

**Issue by tayub94** [nixgates/plugin.video.seren#377]
![8006E2FC-534E-4229-9969-39039E317CB1](https://user-images.githubusercontent.com/33628733/103958078-13fe7000-5144-11eb-9018-ce074545f67a.png)

So I’m unsure if this has already been logged but it seems whenever I load a trakt menu item to do with lists like trending show lists or popular show lists, it will loop the same 5 or 6 lists and no option for a second page

**Comment by SirRickie** [comment]
Same here.

**Comment by Has3n** [comment]
Same

**Comment by nixgates** [comment]
@tayub94 this is actually a duplicate, it's being look at in bug #302

Closing this as a duplicate, please check the other bug moving forward :)
