### ISSUE TITLE
[BUG] Trakt add-on issues with Seren playing first episode of TV- Show

### ISSUE THREAD

**Issue by jweinr** [nixgates/plugin.video.seren#379]
My setup for testing this:
De-authorized trakt from Seren.
De-authorized trakt from TMDBHelper add-on.
Authorized and fully enabled syncing and scrobling in Trakt Add-On 3.2.6

Testing Trakt add-on with Seren player I'm getting this:

Trakt Add-on scrobles correctly on startup/forward/end of any movie (library .strm, web) either invoked from home screen, widget, tmdbhelper, seren app.

Trakt Add-on **will not** scroble at all on startup/forward/end of any **TV SHOW** (library .strm, web) either invoked from home screen, widget, tmdbhelper, seren app, select player seren smart, seren auto play, anything seren.

**BUT** If i let the show end and go to the next one through **Seren auto play, the next episode will scroble correctly** with Trakt-addon, and so forth.

For testing, I downloaded and did the same procedure with venom (vomits) and scrobling works fine from the first episode and on, so I'm assuming this should be a Seren bug?

Kodi 18.9
Seren 2.0.10

https://paste.kodi.tv/nekameyosu.kodi

Cheers,

**Comment by SirRickie** [comment]
I have scrobbling issues too with Trakt-Seren : when starting a movie in Seren, there is no Trakt scrobbling anymore (no notifications during playback). When movie is finished, the screen for giving a quote isn't displayed neither. Strange enough, for TV shows, scrobbling works fine. The scrobbling for movies works fine in other addons.

**Comment by jweinr** [comment]
> I have scrobbling issues too with Trakt-Seren : when starting a movie in Seren, there is no Trakt scrobbling anymore (no notifications during playback). When movie is finished, the screen for giving a quote isn't displayed neither. Strange enough, for TV shows, scrobbling works fine. The scrobbling for movies works fine in other addons.

What are you using for scrobling? Kodi trakt addon or seren's trakt function?
Make sure whatever you are using is correctly authored and configured.
The scrobling notification is part of the kodi trakt addon so look in there and make sure settings are correct.

For me the trakt addon works just fine for seren movies, but it bugs on tv series.

**Comment by SirRickie** [comment]
Trakt 3.2.6 in Seren is authorized correctly. Scrobbling in Trakt is enabled for movies and shows. Result : no scrobbling for movies, scrobbling works fine for TV shows. It works both for movies and shows on other addons (Venom, Crew). I really don't get it and how to solve it.

**Comment by jweinr** [comment]
Can you try disabling trakt functions and deauthorize you trakt account in seren settings?
Then do the opposite, disable you trakt addon completely and enable all the trakt functions in seren.
Test results with both situations.

Reminder: trakt addon and seren trakt stuff work independently from each other.
People are quite confused about this and think that the seren trakt features leverage or depend on the trakt addon, which I've concluded is incorrect.

**Comment by SirRickie** [comment]
I disabled trakt functions and deauthorized my trakt account in Seren settings, and the movies were indeed scrobbled now. I thought, yes I got it, but the disappointment returned with I started a TV show : no scrobbling now on TV shows (just like you posted). There must indeed be a bug somewhere.

**Comment by jweinr** [comment]
Welp, now the trakt addon won't scroble tv shows played by seren, at all.

Debug log:
https://paste.kodi.tv/afividataf.kodi

**Comment by drinfernoo** [comment]
You guys do know that Seren scrobbles on its own, without the Trakt add-on?

**Comment by SirRickie** [comment]
I do know. I have the following issue (Wn10, Kodi 18.9, Seren 2.0.13, Trakt 3.2.6)

- scrobbling with Seren : TV shows, scrobbling OK - Movies, no scrobbling
- scrobbling with Trakt : TV shows, no scrobbling - Movies, scrobbling OK

I tried about everything (enabling, disabling), but can't find the solution.

**Comment by jweinr** [comment]
Seren 2.0.16 scrobles correctly for TV shows and movies.
Trakt addon won't scroble at all with seren player.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
