### ISSUE TITLE
[BUG] auto subtitle

### ISSUE THREAD

**Issue by djdirty60** [nixgates/plugin.video.seren#383]
**Describe the bug**
Auto subtitle not working

**To Reproduce**
1. Go to 'movie/serie'

**Expected behavior**
the automatic subtitle download function does not work

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.9]
 - Version [2.0.10]
 - Coreelec 9.2.5
 - Linux Version 4.9.113 aarch64
 - cpu Amlogic s922x rev a

**Additional context**

**Comment by nixgates** [comment]
@djdirty60 sorry just trying to catch up on some bugs I've missed.

Is this still occurring? Do you have the a4kSubtitles addon installed?

**Comment by djdirty60** [comment]
> @djdirty60 sorry just trying to catch up on some bugs I've missed.
> 
> Is this still occurring? Do you have the a4kSubtitles addon installed?

it can't happen, you are busy too .... and unfortunately it is not working yet everything is up to date, and a4ksubtitles is installed.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
