### ISSUE TITLE
[REQUEST] TMDB movie collections

### ISSUE THREAD

**Issue by djdirty60** [nixgates/plugin.video.seren#384]
**Is your feature request related to a problem? Please describe.**
is it possible that there will be a film collection in it?  think that the films can also be loaded faster.  because there is a part in a movie folder

**Describe the solution you'd like**
a movie collection folder, as is the case in kodi's library if you have a movie with more parts

**Comment by nixgates** [comment]
@djdirty60 I'm not quite sure what you mean?

Trakt's collection can handle movies as it would shows?

**Comment by djdirty60** [comment]
No I mean, Harry Potter has 8 films now they are separate when you go to the collection of your films, but it will be in a film collection as 1 folder with 8 films.

**Comment by nixgates** [comment]
Ah I see what you're after. You're after something similar to TMDB collections. 

It might be possible but it will require reverse matching through to trakt.
