### ISSUE TITLE
[REQUEST] Watched statuses for My Files (and maybe even playback progress indicator and resume)

### ISSUE THREAD

**Issue by unkn0wn234** [nixgates/plugin.video.seren#385]
**Is your feature request related to a problem? Please describe.**
It is not related to a current problem unless I am mistaken and the request is something already in Seren that is not working for me. My Feature request is to make it so My Files in Seren can keep watched and unwatched statuses and possibly even playback progress (but just watched statuses would be more than enough) when using My Files. 
**Describe the solution you'd like**
For most people the My Files is used for cloud files (shows) that we dont want to bother with manually renaming every single episode, thus we just play it through My Files. If Seren could just leave a watched status on the files weve played through Seren it would be nice so when we come back to My Files we know the episode we left off on. 
**Describe alternatives you've considered**
Keeping progress would be nice too but im not sure how viable this is, but at the very least a watched indicator on the previous episodes would be more than enough, i would have no problem jsut skipping forward if i could easily find what episode I am on.
**Additional context**

**Comment by sathish804** [comment]
@mathu204  If you watch any file under My files will be marked with a tick mark. If you are not seeing tick mark means something to do with the skin which you are using. On my setup I see the tick marks in my files using Arctic horizon skin.

**Comment by mathu204** [comment]
> @mathu204 If you watch any file under My files will be marked with a tick mark. If you are not seeing tick mark means something to do with the skin which you are using. On my setup I see the tick marks in my files using Arctic horizon skin.

I see, I use Titan bingie mod does this mean I need to request for them
To implement something? If so can you or Nixgates let me know what it is I have to request them for? Or is there something in Seren that can be done to make it work wirh bingie mod?

**Comment by inb4after** [comment]
Do your cloud files not show up when scraping for content?

**Comment by mathu204** [comment]
> Do your cloud files not show up when scraping for content?

Depending on the show, no. For example re zero started life in another world is re zero hajimeru isekai something, bungou stray dogs, promised never land is yakusoku no never land, etc. it’s mostly just for anime

**Comment by unkn0wn234** [comment]
+1

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
