### ISSUE TITLE
[BUG] Caching item using manual cache removing items after complete

### ISSUE THREAD

**Issue by dobbo47** [nixgates/plugin.video.seren#387]
I think this may be an information and learning issue rather than a support problem. I am new to Seren but reasonably experienced with Kodi. I have inconsistent internet so I want to save all files to Premiumize Cloud first then download later. I have been successful in getting a cache to upload to Premiumize (I can see it in Transfers) but then as soon as it completed it disappears. Am I doing something wrong. If you could just list the steps please it would be great.

**Comment by nixgates** [comment]
@dobbo47 might I ask how you were caching an item to Premiumize?

**Comment by dobbo47** [comment]
Hi there

Thanks for the quick response

After searching for a TV show and selecting an option I selected Cache
Assist from the context menu and it opened a transfer in Premiumize Cloud.
There was an option to run in the background or follow.  I followed and as
you would expect the Seren screen and the Premiumize tracking on the phone
were pretty much in sync

Every time it gets to 99% and then stops.  I can't download locally because
my firestick won't write to the mounted pendrive.

We have very variable internet speeds in rural Italy and my objective is to
save everything to Premiumize Cloud and then I can download it to the
pendrive easily in the mornings using FTP.

By the way is there any advantage in adding other scrapers. I have a sub to
easynews but have never been able to get files

Kind Regards

Bob


[image: photo]
*Bob Wright*
Casale Coccinella

+44 7853 090842 | +39 345 975 2886 | bobwright47@gmail.com

www.casalecoccinella.com
<http://facebook.com/bobwright47>
<http://uk.linkedin.com/in/casalecoccinella>
<http://instagram.com/casalecoccinella> <http://twitter.com/umbriankiss>
Create your own email signature
<https://www.wisestamp.com/create-own-signature/?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=>

**Comment by nix87** [comment]
Adding Easynews to Seren isn't Nix thing as he doesn't develop and maintain providers for Seren. Easynews should be seperate provider which Seren would use. In other words someone should make Easynews provider which is compatible with Seren addon. Same as A4K Scrapers are compatible with Seren. ;)

**Comment by nixgates** [comment]
@nix87 Seren 2.0 now allows provider to implement their own settings and service modules. While there isn't a lot of setting options at the moment, I can and will expand them as required.

 @dobbo47 I'll look into it, the cache assist shouldn't remove the item afterwards from my quick glance at the code but I'll need to dig in deeper to be 100%

**Comment by dobbo47** [comment]
Awesome, thanks!

**Comment by nix87** [comment]
Great news Nix :smile: 

Honestly can't wait to use my Easynews sub in Seren like I use Real Debrid :+1:
