### ISSUE TITLE
[BUG] Next Up order not updating across devices

### ISSUE THREAD

**Issue by Liquidrag** [nixgates/plugin.video.seren#388]
**Describe the bug**
Trakt is connected and scrobbled fine but when watching on one device of a show (I have it set as recently watched) the show shows at the top of my Next Up list and widget as it should but on any of my other devices the order of shows does not update but instead, they stay the same order but the episode is updated.

**To Reproduce**
1. Go to 'Next up and watch an episode'
2. 'After watching, list refreshes properly and next unwatched episode of the show is at the top of the list'
3. 'Go to another device using the same Trakt account and refresh the Next Up is, the show episode updates to the new unwatched episode as it should but the show will be further down the list where it was originally and not at the top.'
4. No error or log reported.

**Expected behavior**
After watching an episode, "Next Up" should update and populate across all devices.

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9 on Mac, Shield Tv, and 4K Firestick
 - Seren 2.0.10

**Comment by queensryche6** [comment]
Same thing happens to me. A little bit inconsistent. Sometimes it works, others not.

**Comment by nixgates** [comment]
@Liquidrag can you please get a log of the device starting (the device that's not updating).

Please remember, Seren will sync with your Trakt account every 15 minutes so make sure enough time has passed.

**Comment by Liquidrag** [comment]
@nixgates I have 3 devices, iMac, Shield pro, and 4K Firestick. Let's say I watch the pilot of Friends on the Mac, the pilot of How I Met Your Mother on the Shield, and the pilot of Big Bang Theory on the 4K FS. Episode 2 will show up first in the queue in the "next up" on each individual device respectively but won't show up on the others, even leaving them overnight. Here's the log from my mac. I hope it helps.

https://paste.ubuntu.com/p/6ghq8ZD7nT/

**Comment by nixgates** [comment]
@Liquidrag I believe the issue has been identified, should be ok for next update. May require a rebuild of the database on each device to kick in though.

**Comment by Liquidrag** [comment]
@nixgates Thank you! I look forward to the next update.

**Comment by Liquidrag** [comment]
@nixgates Thank you and your team. The update seems to have fixed this issue.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
