### ISSUE TITLE
[REQUEST] Unfinished shows to act like Collection

### ISSUE THREAD

**Issue by Liquidrag** [nixgates/plugin.video.seren#389]
**Is your feature request related to a problem? Please describe.**
Unfinished shows used to populate the full list like collection does/did with the hide watched option enabled without having to use the "next page" option and in alphabetical order.

**Describe the solution you'd like**
For the "Unfinished shows in collection" to show the full list of unfinished shows in alphabetical order so I can use it as a widget without using the next item.

**Describe alternatives you've considered**
I set the collection as a widget with the hide watched option enabled but the widget does not recognize the hide watched and still shows the watched shows

**Additional context**

**Comment by nixgates** [comment]
Completed in 2952f86242bad8b21ab17e5b584fe8a3039f78e2

Thanks for the suggestion @Liquidrag :)

**Comment by Liquidrag** [comment]
Thank you!
