### ISSUE TITLE
Seren takes a lot of time to show episodes

### ISSUE THREAD

**Issue by toneman77** [nixgates/plugin.video.seren#39]
When starting Seren and navigating to the "Next Up" section it takes 15 minutes to show the list of episodes. In those 15 minutes nothing happens besides the spinner spinning.

debug kodi logfile: [here](https://pastebin.com/DJMBUCcH)
above log filtered for "seren": [here](https://pastebin.com/2UHqejdB)

timeline of that logfile:

- 11:30 kodi start
- 11:31 seren/next up start
- 11:34-11:43 disabled screensaver 4x
- 11:46 list of episodes is shown

(for comparison: "New episodes" in 13 clowns takes 17s on the 400MBit/s line via ethernet)

Kodi 18 on Nvidia Shield
read-debrid and trakt.tv authorized.

**Comment by nixgates** [comment]
I'm looking at moving Seren back to V1 of the TVDB API. 

This will reduce network calls near a 5th of its current amount and should dramatically increase speed.

There is also plans to have Seren cache trakt progress info long term locally to speed up almost all menus.

**Comment by drinfernoo** [comment]
If you do this, make sure not to include an option for people to use a custom TVDB key anymore, as new v1 keys can't be generated anymore. It's also likely that v1 will be completely dropped at some point, causing you to have to migrate *back* to v2 :(

**Comment by nixgates** [comment]
Testing on this suprisingly shows V1 to be significantly slower, likely because the information is downloaded in a single thread rather than split over 4. 

More testing to occur, need to start caching more trakt information and putting limits on more calls.

**Comment by nixgates** [comment]
Can you please retest this issue, I made a small change that should prevent to many shows from being called in Next Up for users with older trakt accounts.

**Comment by toneman77** [comment]
It felt quicker than before but still "minutes" instead of "seconds". The debug log was filled over and over with

> 2019-02-21 08:25:19.839 T:20828   DEBUG: CSettingsManager: requested setting (omni.port) was not found.
> 
> 2019-02-21 08:25:19.839 T:20828   DEBUG: CAddonSettings[plugin.video.seren]: failed to find definition for setting omni.port. Creating a setting on-the-fly...
> 2019-02-21 08:25:19.841 T:20828   DEBUG: CAddonSettings[plugin.video.seren]: loading setting definitions
> 2019-02-21 08:25:19.843 T:20828   DEBUG: CAddonSettings[plugin.video.seren]: trying to load setting definitions from old format...
> 2019-02-21 08:25:19.848 T:20828   DEBUG: CAddonSettings[plugin.video.seren]: loading setting values
> 2019-02-21 08:25:19.849 T:20828   DEBUG: CSettingsManager: requested setting (general.omniconnect) was not found.
> 2019-02-21 08:25:19.849 T:20828   DEBUG: CAddonSettings[plugin.video.seren]: failed to find definition for setting general.omniconnect. Creating a setting on-the-fly...

So I had to remove 100s if not 1000s of those blocks to be able to upload it to pastebin [here](https://pastebin.com/ZphNC4C3).
Hope it helps.
Let me know if I should repeat.

**Comment by drinfernoo** [comment]
@toneman77 You need to completely wipe Serenity from `Tools -> Wipe Add-on Data`.

You're using a very old version with settings conflicts.

**Comment by toneman77** [comment]
> @toneman77 You need to completely wipe Seren from `Tools -> Wipe Add-on Data`.
> 
> You're having settings conflicts due to upgrading over time.

Good idea. 

- Wiped the addon
- restarted kodi
- set up rd, trakt, providers
- restarted kodi
- triggered "up next" at 20:11
- list appeared at 20:25. so 14 minutes :/

log [here](https://pastebin.com/g2d3gnA0)

**Comment by nixgates** [comment]
@toneman77 I'm not sure how you ever are waiting minutes for any menu on Seren.

Even Next Up which is the slowest menu in Seren is only max 20 seconds for me.  We will have to look at a few things. 

I might provide you with a different custom version of seren to get some proper logging from you.

**Comment by toneman77** [comment]
> @toneman77 I'm not sure how you ever are waiting minutes for any menu on Seren.
> 
> Even Next Up which is the slowest menu in Seren is only max 20 seconds for me. We will have to look at a few things.
> 
> I might provide you with a different custom version of seren to get some proper logging from you.

Nice. I'm ready to test.

**Comment by SerpentDrago** [comment]
@toneman77  do you have this issue with anything else ? any other addons , a simple yes or no . 

can you please go to the tvdb site directly with a browser   and try browsing around ? does it load quickly ?  Can you kindly try restarting your router and modem .  I know that sounds weird but i've solved others database api loading slow issues this way before . 

Do you have any other device / pc in your home you can test to see if you get the same issue or if its just that device.

**Comment by SerpentDrago** [comment]
Also when providing a log, please provide a DEBUG log , by going into kodi setting and turning on debug , then replicating the issue

**Comment by nixgates** [comment]
@toneman77 

As @SerpentDrago requested, can you please provide a full debug log? That log you've supplied unfortunately doesn't provide much information.

**Comment by toneman77** [comment]
> @toneman77 do you have this issue with anything else ? any other addons , a simple yes or no .
> 
> can you please go to the tvdb site directly with a browser and try browsing around ? does it load quickly ? same with trakt.
> 
> Can you kindly try restarting your router and modem . I know that sounds weird but i've solved others database api loading slow issues this way before .
> 
> Do you have any other device / pc in your home you can test to see if you get the same issue or if its just that device.

www.thetvdb.com loads lightning fast.
Restarted both routers (load-balanced dual 400Mbit line) also the switch the Nvidia Shield is connected to.

- Just started kodi again 
- enabled DEBUG logging like in my very first post
- again got a bajillion "...from old format..." like in the initial post, log [here](https://pastebin.com/ZqND3NyF)
- Next up loads pretty fast. under a minute if I had to guess

Dunno what changed in the past 8 days but aside from the "old format setting" Seren's "Up Next" loads quickly now for me

**Comment by nixgates** [comment]
Thanks for getting back to me! 

Unfortunate that we didn't find the cause, but I'm just glad it's working like it should.

**Comment by toneman77** [comment]
well... sad news and I am out of options and out of ideas. that one day it worked... then it didn't. since the PC version was so quick I repeated my test on fresh installs.
- created a backup of my .kodi folder from the PC
- deleted everything on my Nvidia shield
- deleted everything on my Amazon fireTV 4k
- installed kodi fresh on the shield and fireTV
- exited kodi
- extracted the .kodi folder on the shield and fireTV
- started kodi on all **three** installation (PC, shield, fireTV)
- went into Seren, selected "My Shows" and then next up (almost) simultanuously on all 3 (with adb)

setup: (all infos from kodi's system information)
PC: 

> kodi 18.1 Git:20190217-8cfdc89 (docker container) 
> Ubuntu 16.04.3 LTS
> kernel 4.16-0-041600rc3-generic
> installed from the official PPA


firetv 4k : 

> Kodi 18.1 Git:20190217-8cfdc89
> android 5.1.1 API level 22
> kernel 3.10.61+
> installed with the Appstarter app

Nvidia Shield: 

> Kodi 18.1 Git:20190228-80b339717e 
> android 8.0.0 API level 26
> kernel 4.9.109-tegra-g2dafed3
> installed via play store

Started my test at 17:41. Results (time until I saw the titles of the episodes)
- PC: 16 seconds
- Nvidia shield: aborted when after 30 minutes nothing happend
- Amazon fireTV 4k: aborted when after 30 minutes nothing happend

to be able to upload the DEBUG logs I had to remove 6000-8000 of the "trying to load from old format" messagesfrom each of the logs:
PC: https://pastebin.com/1GDNr8t6
shield: https://pastebin.com/cXGxKD8T
firetv 4k: https://pastebin.com/0n01PKFY

**ANY** help is appreciated.

**Comment by nixgates** [comment]
@toneman77 can you check and confirm your issue is still present on the latest release of Seren?

**Comment by nixgates** [comment]
Closing issue due to no response from user.

Trakt Sync Database should have rectified this issue. Please let me know if this is not the case.
