### ISSUE TITLE
[BUG] Next up unwatched episodes Bug

### ISSUE THREAD

**Issue by StanLee01** [nixgates/plugin.video.seren#390]
**Describe the bug**
Since the new update to 2.0.10 my Next up widget doesn’t work like it suppose to. 

I selected/activated the new option found at settings-interface-advanced-show remaining unwatched season episodes in mixed lists. 

This should show me the remaining unwatched episodes of the season on Next Up. For me, this works like it should. I’m seeing the remaining episodes of that season on my Next Up Widget. 

The problem is when finishing the last episode of the season it just completes and deletes it from my Next up after the last episode of the season. It doesn’t jump to the next season. It just finishes the show, even though I’ve still got 7 seasons unwatched. 

I’m on
 - Kodi Version 18.9
 - Seren 2.0.10

**Comment by nixgates** [comment]
@StanLee01 I can't replicate this, could you let me know the name of the show and the season this occurred with?

**Comment by StanLee01** [comment]
Thanks for replying. With the new update 13 it doesn't occur anymore. So every thing works just fine. 

Great work.

**Comment by nixgates** [comment]
@StanLee01 sounds good! Closing it off :)
