### ISSUE TITLE
[BUG] Unfinished shows In Collection List

### ISSUE THREAD

**Issue by anzien7** [nixgates/plugin.video.seren#391]
"Unfinished shows In Collection" List Does not contain all of my unfinished shows, since The 2.0 update e.g. In Collection I have 42 unfinished shows, but only 32 show up. I then finished a show and now it only holds 31. It did not repopulate to 32 even after a rebuild with trakt.

I have tried clearing Seren and reinstall and rebuilt Trakt before and after update also increased page size limit to 100.

Kodi Version 18.9

**Comment by nixgates** [comment]
@anzien7 I'm not sure why it would go back up to 32 after a rebuild. 

Are you 100% certain there are 42 items not finished? May I ask where you are getting that number from?

**Comment by anzien7** [comment]
> 
> 
> @anzien7 I'm not sure why it would go back up to 32 after a rebuild.
> 
> Are you 100% certain there are 42 items not finished? May I ask where you are getting that number from?

No it still only has 31 in the list, I just thought that maybe it was a max limit but it was not, just trying to provide as much info as I can. I have 42 unfinished shows in the Collection list. this happen right after I installed Seren 2. I use that list for my widget so I noticed it straight away that a lot of shows where missing.

**Comment by mft4** [comment]
I have the same problem. Unfinished shows in collection is missing a lot of shows. I can watch them from collection but not from unfinished shows in collection.

**Comment by anzien7** [comment]
A small update. 3 more shows are now missing from the list, including the one I'm currently watching.

**Comment by lqdchkn** [comment]
I have also noticed this issue.  For me none of my collected shows show up

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
