### ISSUE TITLE
[BUG] TV show from Trakt list is marked as "watched", even if there is an unseen episode.

### ISSUE THREAD

**Issue by 12asdfg12** [nixgates/plugin.video.seren#392]
It happens every time, on the day when a new episode is aired.
After a day or two (not sure) the show status becomes 'unwatched'.
Tried to clear cache, resync with trakt, nothing changed.
This bug was also present in Seren 1.6.

There is an example:
Shameless episode 11x04 was aired today (11.01)
The episode status is 'unwatched'
Season 11 is 'unwatched'
Shameless TV show status is 'watched'

**Expected behavior**
When a new episode from a tv show is available, the watched status of the tv show must be 'unwatched'

**Screenshots**
![screenshot001](https://user-images.githubusercontent.com/48175015/104181964-5b248380-5418-11eb-8439-46d9d6f198db.png)
![screenshot002](https://user-images.githubusercontent.com/48175015/104181969-5e1f7400-5418-11eb-82da-6cef5c299f45.png)
![screenshot003](https://user-images.githubusercontent.com/48175015/104181974-5fe93780-5418-11eb-9ef9-71bf7a976020.png)

**Comment by xyzfre** [comment]
I think this relates to the same issue I’m having issue #310

**Comment by nixgates** [comment]
Seren has a update_show_statistics method that should handle this. Seems like it's not being run often enough. I'll fix this up for next update.

**Comment by nixgates** [comment]
@xyzfre can you confirm this issue is resolved in the latest update?

**Comment by 12asdfg12** [comment]
I couldn't check if the issue was resolved because a new episode for the shows on my lists hasn't been aired yet.
The next new episode will be aired tomorrow (The good doctor) and I will be able to check if the show watched status are set to off or not. I will come back with a feedback.

Thank you for solving this problem and for this great add-on.

**Comment by 12asdfg12** [comment]
I checked this morning. A new episode of "The good doctor" was aired, but the state of the tv show is still "watched". Episode and season status is "unwatched".
I'll check again in a few hours when I get home.
When should this sync process run? Maybe the problem is that my Kodi box is turned off (by hdmi check) when i turn off the tv?
Couldn't a sync be run when starting kodi or seren?

**Comment by nixgates** [comment]
@12asdfg12 a sync does run, unfortunately kodi will load most of the info for the widgets from Seren before it can complete.

If you could browse to be sure, that would be good. Otherwise, we have a rework for dates in the next update that might also fix this issue.

**Comment by 12asdfg12** [comment]
I checked again and the show status is still 'watched'. I tried to clear cache, sync with trakt, restart kodi but nothing changed.

**Comment by nixgates** [comment]
@12asdfg12 ok the only thing I can think of is its a miss handling of dates which we have a fix in the pipeline for. 

Hopefully have an update today/tomorrow for this.

**Comment by nixgates** [comment]
@12asdfg12 have you checked to make sure you don't have delay release dates set to on?

Should also be noted, that Seren takes into account the actual time that the episode is intended to air. Are we 100% that it's past the actual airing time as well?

**Comment by 12asdfg12** [comment]
1. Yes, I checked several times, the delayed release date is not set to on in settings
2. I'm 100% sure, I actually watched (in Seren) a lot of episodes on the day of the release, with the show status set to watched in Seren. These episodes also appear in "up next to watch".

**Comment by nixgates** [comment]
> 1. Yes, I checked several times, the delayed release date is not set to on in settings
> 2. I'm 100% sure, I actually watched (in Seren) a lot of episodes on the day of the release, with the show status set to watched in Seren. These episodes also appear in "up next to watch".

Super weird. Alright, well ill dive into it over the weekend and get back to you. I don't see this being an easy one to identify so might take a bit.

**Comment by 12asdfg12** [comment]
@nixgates 
I did some research, ran the query from the "update_shows_statistics" function, and found out that the bug is caused by the wrong episode_count for the show.

Here is an example:
The episode_count is 2 but it should be 3
![image](https://user-images.githubusercontent.com/48175015/105877552-ca999600-6008-11eb-84c3-bf0dce5f0c23.png)

There are 4 episodes, 1 unaired and 1 aired today:
![image](https://user-images.githubusercontent.com/48175015/105877742-f87eda80-6008-11eb-945b-44704d46bdad.png)

Today's episode is available in seren.
![image](https://user-images.githubusercontent.com/48175015/105877961-35e36800-6009-11eb-8bba-b12cb6f65b5e.png)

**Comment by nixgates** [comment]
Ah beauty, thanks for that. I haven't had a chance to deep dive into this yet so you might have just saved me a lot of time!

**Comment by drinfernoo** [comment]
Keep open.
