### ISSUE TITLE
[REQUEST] Trending vs. popular movie lists - Whats the difference? Why not merge them and clean them up from duplicate entries?

### ISSUE THREAD

**Issue by Delamain813** [nixgates/plugin.video.seren#393]
I really like the new list that are provided in the "discover movies/shows" section, but i don't understand the difference between trending movie/show lists and popular movie/show lists. Also, the lists are doubled and even trippled and a lot of them are duplicate in both the trending and popular tab, while some lists are only present in one or the other.

I would like to create a shortcut in my submenu to these lists, so having them all under one tab instead of splitting them up in trending and popular (again, i don't get the difference) and avoid any duplicates would be so nice. Just merging these lists and cleaning them up from duplicates would improve their usability a lot. Thank you! Seren 2.0 is much faster and works great so far.

**Comment by LoganWolverineX** [comment]
The popular and trending lists are pulled from Trakt. Nixgates only pulled them from their site. Trending I believe is what everyone is watching recently now. Popular is what’s been popular over a longer period of time.

**Comment by Delamain813** [comment]
> The popular and trending lists are pulled from Trakt. Nixgates only pulled them from their site. Trending I believe is what everyone is watching recently now. Popular is what’s been popular over a longer period of time.

I actually figures this out an hour ago and found a workaround to my request. I can simply like these lists individually on Trakt (links are provided in the subreddit) and then they appear in my "liked movie/show lists" and that's the shortcut i made in my submenu.

However, the problem of duplicate entries still persists, so i assume that's just a bug that might be solvable. It seems like every entry is duplicated about three times, but not exactly, some are only duplicated two times. If you guys can have a look at that, that would be awesome! Thanks

**Comment by nixgates** [comment]
@Delamain813 this isn't a bug, this is the information pulled from Trakt. 

As Logan mentioned, the Trending lists are lists that are trending with users over a period while popular is over all time, there's nothing worth doing on Seren's side.

If you would like to see a combined effort, raise the issue with Trakt.
