### ISSUE TITLE
[BUG] SEREN minor navigation issue

### ISSUE THREAD

**Issue by zemely** [nixgates/plugin.video.seren#395]
**Describe the bug**

**To Reproduce**
1. Go to '..TV Shows Collection or Watchlist.'
2. Got to any TV show season
3. Backup a level
4. It supposed to bring you back to the TV Show collection or watchlist but it brings you back one 2 levels too far, to main selection for Movies and TV shows

**Expected behavior**
It supposed to bring you back to the TV Show collection or watchlist but it brings you back one 2 levels too far, to main selection for Movies and TV shows

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Addon ver 10.0.1

**Additional context**
Minor issue, no problem, just want to report it. Sorry if I did something wrong here, this is my first time

**Comment by nixgates** [comment]
@zemely the only way I can reproduce  this is by pressing back twice in quick succession. Are you using a remote for this operation? Is it possible for you to try and use a different remote/method to go back to confirm it's not a hardware issue?

**Comment by zemely** [comment]
Thank you for your reply. I am using genuine NVidia Shield remote. I tried it on 3 different NVidia Shields and few MI Boxes. There is no other way to do it other than use BACK button. I have this issue since I got SEREN. It's not a big deal really but if you want to browse TV SHOW's seasons to see what do they have, it brings you from the season way back to the main menu with Discover Tv, Discover Movies etc instead to the Collection or Watchlist. Sorry, hate to waste your time on this. And I don't press Back fast. If you want me to check something else, please let me know and thank you for the great addon, using it 99% of the time

**Comment by LoganWolverineX** [comment]
I think the bug being discussed has been fixed from #299.  To fix this, try to recreate the menu shortcut or widget.  I had this issue, but once the widget or menu shortcut has been re-created, this fixes the problem.

**Comment by zemely** [comment]
I am assuming this reply was for NixGates, not for the users because I have no clue how to recreate short cut or widget in the SEREN. All other addons work fine with this navigation. Based on your explanation, it makes sense, the bug I mean, with missing "/"

**Comment by LoganWolverineX** [comment]
> I am assuming this reply was for NixGates, not for the users because I have no clue how to recreate short cut or widget in the SEREN. All other addons work fine with this navigation. Based on your explanation, it makes sense, the bug I mean, with missing "/"

Actually it was to you @zemely. The navigation you speaking of, is it from a widget or category/menu shortcut?  I was only chiming in because I fixed my navigation issue by recreating the shortcut/widget if it’s from navigating from a widget or shortcut.

**Comment by zemely** [comment]
Oh, OK, got it. In fact, I just tested it on one of NVidia Shield Kodi 18.9 and it works. I am confused and sorry. I do have XANAX build on this KODI, maybe it's a skin issue? The KODI that it doesn't work on has default skin, no builds and this is my main devise I use on weekends. I will double check tomorrow again. I know that it doesn't work on default skin because I even tried to use "..." to backup and it made no difference vs button. But I will double check tomorrow but I am pretty sure it doesn't work on default skin, I used this device the whole past weekend. Maybe Mr. Nixgates uses not default skin?

**Comment by nixgates** [comment]
@zemely I think what Logan is saying is, how are you navigating to the list.

By the way of your original post, it sounds like you are navigating the menus. Just to confirm, you're not attempting to browse from a widget?

**Comment by irbyjm** [comment]
I get this whenever I use "Browse Show..." on items in my Collection using context menu. Instead of dumping me into in My Shows > Collection I'm back at root.

**Comment by drinfernoo** [comment]
I imagine this is because the add-on is started directly into that directory by th context menu add-on, so there is no history to "back out" into.

**Comment by zemely** [comment]
Works fine now on New version for KODI 19. Thank you nixgates
