### ISSUE TITLE
[BUG] Persistent pop-up message: "Failed to refresh RD token, please manually re-auth"

### ISSUE THREAD

**Issue by richardsaloga** [nixgates/plugin.video.seren#398]
**Describe the bug**
I've never had an RD subscription but this message keeps popping up every 15 minutes. I asked around on Reddit and it sounds like I'm not the only one having the problem.

**To Reproduce**
Sit back, watch a flick, and observe the message popping up every 15 minutes.

**Expected behavior**
Sit back, watch a flick, and not observe the message popping up every 15 minutes.

**Screenshots**
This took me for-fuggin-ever to finally snap a pic of it...damn near broke my toe on my coffee table in the process.
![IMG_20210112_210013](https://user-images.githubusercontent.com/31358089/104405206-9f4b7d00-5519-11eb-80bb-c099e7b5862a.jpg)

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9 on LibreELEC 9.2.6

**Additional context**
Let me know if a log would be useful.

**Comment by richardsaloga** [comment]
Potentially resolved by clearing cache, I'll keep you posted.

**Comment by nixgates** [comment]
@richardsaloga this should be fixed in next update (2.0.13) :)

**Comment by richardsaloga** [comment]
Appears to be fixed. Thank you for your hard work!

**Comment by nixgates** [comment]
@richardsaloga haha its not out yet, but its likely your settings just sticked this time.

**Comment by nixgates** [comment]
fixed in 2.0.13

**Comment by CrinkleCo** [comment]
okay NEWB question... How do I update to the 2.0.13??

**Comment by drinfernoo** [comment]
@CrinkleCo 2.0.16 is the latest, and you can install it from the repo.
