### ISSUE TITLE
[BUG] Unable to authorize Trakt

### ISSUE THREAD

**Issue by ivarbrandt** [nixgates/plugin.video.seren#404]
When attempting to authorize Trakt in Settings, this message pops up:

Unable to contact Trakt
Please check Trakts outage status at:
http://status.trakt.tv

I went to that link and it says that all systems are operational at Trakt

**Comment by rudf0rd** [comment]
After multiple attempts to email the dev with no response, we had to revoke his key.  Since Jan 1, this app was responsible for 60+% of our entire API traffic.

**Comment by ivarbrandt** [comment]
Oh wow! That's insane. So I'm going to have to get my own API key? How do I do that?

**Comment by rudf0rd** [comment]
No, please, please dont do that.  The application itself is flooding our systems.  You'll need to wait for the developer to fix it.

**Comment by ivarbrandt** [comment]
Smh I'll wait. Thanks for the information.

**Comment by nix87** [comment]
> After multiple attempts to email the dev with no response, we had to revoke his key. Since Jan 1, this app was responsible for 60+% of our entire API traffic.

Seren addon heavily relies on Trakt and also addon is popular as f*** xD

**Comment by JackDinn** [comment]
Nearly 2 weeks. Wonder why Nix has been so hard to contact, he's usually pretty good.

**Comment by rudf0rd** [comment]
> > After multiple attempts to email the dev with no response, we had to revoke his key. Since Jan 1, this app was responsible for 60+% of our entire API traffic.
> 
> Seren addon heavily relies on Trakt and also addon is popular as f*** xD but for the reason. I hope Nix will fix soon what it need to be fixed.

To clarify, the meta data calls don't really matter as much since we have CDN caching for that.  Our CDN probably isn't stoked to be hit with the increased frequency though.  And there was a large rise in these calls as well.  It's harder to gauge the necessity of these calls since every users behavior differs so greatly.

The larger issue i that our servers are being hit with an inexplicable amount of last activities checks.  We did some back of the napkin math and with the amount of users this app has + the amount of these calls, it's like 1 ever few seconds per person.

**Comment by Slamious** [comment]
Nixgates please refer to line 45 of service.py. I believe this call to sync may be contributing to this issue. It tries to sync on startup even if trakt isn't authorized and eventually times out with the Unknown Trakt Error popup. I've tested "if g.get_setting("trakt.auth"):" and also "if len(g.get_setting("trakt.auth")) >1:" and they both appear to work (not sure which is better). I hope this is helpful.

**Comment by bills176** [comment]
For a couple weeks I was getting a sync error with Trakt I'm Seren. It would fail trying to sync show bookmarks. It was failing connecting to Trakt. This would keep happening but all other Trakt operations would still work. Sorry I am not real knowledgeable about Kodi logs.

**Comment by CountablyInfinite** [comment]
I have a very similar/related issue. I am not able to interact with any show in my favourites or search for anythings else.

```
2021-01-14 20:23:34.082 T:1519378656   ERROR: SEREN: Trakt returned a 403 (Forbidden - invalid API key or unapproved app): while requesting https://api.trakt.tv/search/show?query=--------------------------&extended=full&field=title
2021-01-14 20:23:34.082 T:1519378656   ERROR: SEREN: Failed to receive JSON from Trakt response - response: <Response [403]> - error - No JSON object could be decoded
2021-01-14 20:23:34.086 T:1519378656   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/home/----/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
                                                router.dispatch(g.REQUEST_PARAMS)
                                              File "/home/----/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 290, in dispatch
                                                tvshowMenus.Menus().shows_search(action_args)
                                              File "/home/----/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 404, in shows_search
                                                self.shows_search_results(query)
                                              File "/home/---/.kodi/addons/plugin.video.seren/resources/lib/gui/tvshowMenus.py", line 417, in shows_search_results
                                                for show in trakt_list
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--

```
I was not sure if this has something to do with my own trakt account first, so i tried to reauthorize it, but it shows

```
Unable to connect to Trakt.
Please check Trakt outage status at:
http://status.trakt.tv
```
Default Trakt works.
I am on 2.0.10

**Comment by drinfernoo** [comment]
@CountablyInfinite Likely most functions of the add-on will be non-functional until this issue is closed.

**Comment by bills176** [comment]
I was just noting what I saw prior to the shutdown of the API. Maybe all the failed attempts to sync show bookmarks created all the API traffic. It kept trying the whole time Kodi was open.

**Comment by drinfernoo** [comment]
Your log clearly states that it came from *after* the API key was revoked:

> `2021-01-14 20:23:34.082 T:1519378656   ERROR: SEREN: Trakt returned a 403 (Forbidden - invalid API key or unapproved app)`

No worries, it's being fixed by @nixgates.

**Comment by ajmorse1983** [comment]
Do we know when this issue will be resolved?  I was having issues with my shows not syncing so I unauthorized trakt and now I can no longer reauthorize.

**Comment by drinfernoo** [comment]
Update to 2.0.11.
