### ISSUE TITLE
[BUG] Movie menu items not working. Trending, most popular, etc. 

### ISSUE THREAD

**Issue by cbizzle14** [nixgates/plugin.video.seren#405]
When clicking on discover movies and going to most popular, trending, or any other category it returns an error. My friend has the same thing happening to him EXCEPT it's TV shows and not movies. So TV shows work me but not movies and movies work for him but not TV shows. I have attached the log below

http://paste.kodi.tv/cowukukafu

**Comment by jullienf** [comment]
I’m having the same issue.  Every time I try to access a Movie Category is give me the “Check the Log for Information” error.  The only category on the TV side it allows me to access without that error is the “most popular” category.  Even then, it is completely blank

**Comment by waffletruck** [comment]
This is not a bug of its own, per se.  It is caused by the Trakt API key being revoked as mentioned in issue #404

**Comment by anwarotti** [comment]
I have the same problem.. The only thing is working " Most Popular" Shows... And also the movies and shows i have on Favorite list. 

And also the other problem with the Trakt authorize still unable to do it.


I have two devices.. The first one is showing " Most Popular" Movies 
And the second device is showing "Most Popular" Shows

And as i mentioned the Favorite list  " Movies Only" are working... But the shows everything is empty whenever you click on any shows to view the seasons and episodes .

Yss im new in here lol...

**Comment by cbizzle14** [comment]
> I have the same problem.. The only thing is working " Most Popular" Shows... And also the movies and shows i have on Favorite list.
> 
> And also the other problem with the Trakt authorize still unable to do it.
> 
> I have two devices.. The first one is showing " Most Popular" Movies
> And the second device is showing "Most Popular" Shows
> 
> And as i mentioned the Favorite list " Movies Only" are working... But the shows everything is empty whenever you click on any shows to view the seasons and episodes .
> 
> Yss im new in here lol...

Trakt removed their api key from Seren or something like that which is why it's not working properly

**Comment by anwarotti** [comment]
> > I have the same problem.. The only thing is working " Most Popular" Shows... And also the movies and shows i have on Favorite list.
> > And also the other problem with the Trakt authorize still unable to do it.
> > I have two devices.. The first one is showing " Most Popular" Movies
> > And the second device is showing "Most Popular" Shows
> > And as i mentioned the Favorite list " Movies Only" are working... But the shows everything is empty whenever you click on any shows to view the seasons and episodes .
> > Yss im new in here lol...
> 
> Trakt removed their api key from Seren or something like that which is why it's not working properly

Are they working on that thing? Or we have to get an APi from trakt and add it manually on serens settings?

**Comment by cbizzle14** [comment]
> > > I have the same problem.. The only thing is working " Most Popular" Shows... And also the movies and shows i have on Favorite list.
> > > And also the other problem with the Trakt authorize still unable to do it.
> > > I have two devices.. The first one is showing " Most Popular" Movies
> > > And the second device is showing "Most Popular" Shows
> > > And as i mentioned the Favorite list " Movies Only" are working... But the shows everything is empty whenever you click on any shows to view the seasons and episodes .
> > > Yss im new in here lol...
> > 
> > 
> > Trakt removed their api key from Seren or something like that which is why it's not working properly
> 
> Are they working on that thing? Or we have to get an APi from trakt and add it manually on serens settings?

It is being worked on. Nix asked us to give him a day to make sure the issue is 100% fixed

**Comment by waffletruck** [comment]
> > > > I have the same problem.. The only thing is working " Most Popular" Shows... And also the movies and shows i have on Favorite list.
> > > > And also the other problem with the Trakt authorize still unable to do it.
> > > > I have two devices.. The first one is showing " Most Popular" Movies
> > > > And the second device is showing "Most Popular" Shows
> > > > And as i mentioned the Favorite list " Movies Only" are working... But the shows everything is empty whenever you click on any shows to view the seasons and episodes .
> > > > Yss im new in here lol...
> > > 
> > > 
> > > Trakt removed their api key from Seren or something like that which is why it's not working properly
> > 
> > 
> > Are they working on that thing? Or we have to get an APi from trakt and add it manually on serens settings?
> 
> It is being worked on. Nix asked us to give him a day to make sure the issue is 100% fixed

For sure. Looking forward to the fix pushing. To keep things clean, this ticket should be closed.
