### ISSUE TITLE
[BUG] Trakt is not working

### ISSUE THREAD

**Issue by luizffgarcia** [nixgates/plugin.video.seren#406]
It is not possble to authorize Trakt, or use the lists (trending, most popular)

Kodi logs show all Trakt api calls return 403, says something is wrong with the api key or the app is not authorized.

**Comment by Tikipeter** [comment]
Jesus. Read the Issue 2 below yours, titled "[BUG] Unable to authorize Trakt"
https://github.com/nixgates/plugin.video.seren/issues/404

**Comment by luizffgarcia** [comment]
> Jesus. Read the Issue 2 below yours, titled "[BUG] Unable to authorize Trakt", and then delete this issue.
> #404

Jesus, no thank you.

**Comment by drinfernoo** [comment]
It's always advised to read already open issues before opening duplicate ones 👌

**Comment by luizffgarcia** [comment]
> It's always advised to read already open issues before opening duplicate ones 👌

Thank you for your input. I have now read the other issues.

Now, for the other user, "go read the issues and then close this one", seriously...... A dog can communicate with better manners...

**Comment by drinfernoo** [comment]
Considering that's not what he said anyways, I think we're done here. Thanks for *your* input.
