### ISSUE TITLE
[BUG] Seren error: check the log for more information

### ISSUE THREAD

**Issue by CopyPastee** [nixgates/plugin.video.seren#408]
I just fresh install kodi and seren 2.0.10. on my sony android tv xf9005.

When I go to movies or series and click on trendig or most popular or anything else, a message comes to me "seren error check the log for more information"

**Comment by Has3n** [comment]
Same here, can not re-authenticate Trakt, despite its not down. Feels like Trakt has blacklisted seren?

log: https://paste.kodi.tv/umakodabex.kodi

**Comment by drinfernoo** [comment]
Correct. Check open issues before opening duplicates, please.
