### ISSUE TITLE
[BUG] Seren crashes after clicking search or browsing Error

### ISSUE THREAD

**Issue by hoIIowpoint** [nixgates/plugin.video.seren#409]
**Describe the bug**
Everything worked great until it didn't. Cannot search or browse anything. Tried everything, removing trakt, clearing caches etc, even a fresh install of Kodi and Seren with a4kScrapers. Same issue. I've ran out of options. Is it just me or is Seren down?

**To Reproduce**
1. Go to 'Seren'
2. Click on 'Either submit a search, or browse movies/tv by top rated etc'
4. Error please check log

**Expected behavior**
Should show a list of movies etc

**Screenshots**
Tried to find an easy way to dump the log but couldn't. 
Search error:
![IMG_20210114_170155](https://user-images.githubusercontent.com/77470235/104667229-7696c500-568a-11eb-96ff-7c4d35a789ed.jpg)
![IMG_20210114_170240](https://user-images.githubusercontent.com/77470235/104667236-7a2a4c00-568a-11eb-9016-c06df6aa4f8c.jpg)
![IMG_20210114_170317](https://user-images.githubusercontent.com/77470235/104667246-7d253c80-568a-11eb-9c07-8d6ef4796c23.jpg)

**Kodi Version (please complete the following information):**
 - Kodi Version [18.9] firestick tv 4k 32bit
 - Version [2.0.10]

**Additional context**
I also tried to use Kodi 19 beta 2, couldn't load the zip from repo. Checked to make sure RealDebrid is authorized. I know there is an issue with Trakt API key for browsing categories, but even the search errors out.

**Comment by drinfernoo** [comment]
Update to 2.0.11.

**Comment by hoIIowpoint** [comment]
Thanks to everyone for their hard work!

**Comment by hoIIowpoint** [comment]
I also think I'm blind.  Shows update available but doesn't update to 2.0.11.. I'm assuming I just gotta wait for repo to be updated.
