### ISSUE TITLE
[BUG] - my collection is no longer sorting by title

### ISSUE THREAD

**Issue by audinutt** [nixgates/plugin.video.seren#410]
*
my collection is no longer sorting by title either on movies or shows

**To Reproduce**
1. Go to my collection
2. Click on my collection
3. It shows in order added to collection instead of alphabetical.

**Expected behavior**
It used to sort alphabetically or by "title'

**Comment by nixgates** [comment]
Please disable collection pagination for now, this has been identified in a separate bug ticket and I'll be splitting the pagination/sort into two settings
