### ISSUE TITLE
[REQUEST] Rescrape option in source select page

### ISSUE THREAD

**Issue by Fatal-Errol** [nixgates/plugin.video.seren#412]
It will be nice to have the rescrape button available in the source select page.

This will be useful when you interrupt the scraping early or it didn't return a satisfying result.

I am also using tmdb for all my widgets so there is no rescrape option in the context menu. I had to search the item in seren (using the search in seren tmdb player option) and then navigate to the correct video just to have the rescrape context menu.

Thanks. Awesome work as always!

**Comment by nixgates** [comment]
@Fatal-Errol not a bad idea actually. Would really only be useful if you cut the scrape early and don't get the results you wanted as you can't change the settings from there but it's a simple enough feature to add so why not!

**Comment by drinfernoo** [comment]
Also, you can technically already do this with a custom theme, by adding a button with an`onclick` similar to this:

`<onclick>RunPlugin(plugin://plugin.video.seren/?action=getSources&source_select=true&seren_reload=true&actionArgs=%7B%22item_type%22%3A%20</onclick>`

**Comment by jweinr** [comment]
Yeah pretty useful idea actually having a rescrape option in context menu.

Side question: Is global context menu working at all for you outside of Seren ? I mean the description says "throughout kodi".

**Comment by drinfernoo** [comment]
@jweinr Have you... installed the context menu add-on?

**Comment by nixgates** [comment]
@jweinr its for Seren items throughout kodi (widgets and the like)

**Comment by jweinr** [comment]
@drinfernoo yes as it is a dependency for seren addon.
@nixgates Oh that clears it, it's only for Seren items. I only use tmdbh widgets and don't normally navigate inside Seren. I thought it could work for non-seren widgets.

Thanks

**Comment by jweinr** [comment]
Better yet, do it automatically and notify elegantly.
"No sources found meeting criteria, expanding search"
Or something along those lines.
