### ISSUE TITLE
[BUG] Problem syncing show bookmarks

### ISSUE THREAD

**Issue by bills176** [nixgates/plugin.video.seren#415]
**Logs**

https://paste.ubuntu.com/p/NYn3HHkJZv/

**Describe the bug**
Seren keeps trying to sync "show bookmarks" with Trakt and fails. It will keep trying as long as Kodi is open. All other Trakt operation seem to work fine. I waited until the recent Trakt problem was addressed. I am currently running 2.0.12 and this was happening with 2.0.10. 

**To Reproduce**
Seren automatically syncs at Kodi startup.

**Expected behavior**
Sync of bookmarks. I really don't use and disabling would be acceptable.

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9 20201023

**Additional context**
I did try completely uninstall (settings) to no avail. Seren still works but it looks like many pings to the API.

**Comment by nixgates** [comment]
It's likely due to the request taking to long.

I'm going to extend the timeout for this request, will be available next update :+1:

**Comment by bills176** [comment]
Sounds good but everything else seems to sync okay. It's just "show bookmarks"? I'm no expert though.

Thanks for the quick response!

**Comment by nixgates** [comment]
@bills176 yea looks like I moved that to pull all bookmark items but left the page limit of 100. This means to much information was being pulled per page and would timeout.

Simple enough, I've seen it happen before. Should be good next update if you don't mind testing when it's released :+1:

**Comment by bills176** [comment]
I can do that.
Thanks again!

**Comment by bills176** [comment]
Hi, 
I'm back. I updated to v 2.0.13. I did a restart on Kodi. Seren went and tried to update "show bookmarks" but responded unknown error failed to connect to Trakt. Looks like my problem persists.  It did return the failure message quicker than in 2.0.12. Following is my log after Kodi startup only.

**Comment by bills176** [comment]
Forgot to paste link
https://paste.ubuntu.com/p/BBssYMTGh5/

**Comment by bills176** [comment]
I closed by mistake. Fat fingers

**Comment by nixgates** [comment]
@bills176 could I ask you to let me know if this is working now? By the looks of the log, looks like Trakt has having some troubles and was returning a server error response.

**Comment by bills176** [comment]
I tried again and am getting the same error. Here is log after start up.
https://paste.ubuntu.com/p/6nd9w7kYZd/
When I force a sync in Seren, everything syncs except show bookmarks returning withe the error.

**Comment by bills176** [comment]
I tried force sync multiple times today and receive the unknown error connecting to Trakt every time on the bookmarks. If I'm the only one experiencing this, it would lead me to my install. Could it be the API?

**Comment by nixgates** [comment]
@bills176 I saw an issue that may cause what you're seeing and added another fix in 2.0.14, could you let me know if it's working now?

**Comment by bills176** [comment]
I've updated to Seren 2.0.16. I still get  unknown error connecting to Trakt when forcing a Suncorp rebuilding database. Here's the log.
https://paste.ubuntu.com/p/jTX3g5PggQ/

**Comment by bills176** [comment]
So, do I need to learn to live the messages/errors continuously popping up "syncing Trait database. Please be patient" and "error connecting to Trakt"? It gets annoying.

**Comment by bills176** [comment]
Latest log
https://paste.ubuntu.com/p/mW2g4B2XtK

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
