### ISSUE TITLE
[BUG] Sort in Trakt lists does not ignore articles

### ISSUE THREAD

**Issue by dharmaskibum** [nixgates/plugin.video.seren#416]
**To Reproduce**
1. Go to 'My Movies or My Shows -> Watchlist or My Movie or My Show Lists.'
2. Click on 'any list'
3. Scroll down to view lists
4. See error, movies or shows starting with a, an, the, etc are sorted in the a or t section

**Expected behavior**
Articles should be ignored when sorting.  For example, The Handmaids Tale should be in the H's, not the T's.

**Kodi Version (please complete the following information):**
 - Kodi Version [18.8]
 - Version [e.g. 2.12]

**Comment by nixgates** [comment]
@dharmaskibum  Thanks for that, I'll fix this up now

**Comment by nixgates** [comment]
@dharmaskibum fixed ready for next update

**Comment by nixgates** [comment]
Fixed in latest update
