### ISSUE TITLE
[REQUEST] Bring back the title Artwork Poster in the SS UI

### ISSUE THREAD

**Issue by Nuklear92** [nixgates/plugin.video.seren#417]
So, I was thinking if there's a small chance to bring back the Artwork Poster into the SS UI. I mean, I feel like there's a lot of space that could be gained from trying compact fit some of the right side boxes, like the Plot one, and down right with Play, View Uncached and Download could potentially be readjusted into a more compact size that could open up for even more right space to potentially be able to fit a medium size Artwork Poster like the old SS UI in 1.0 had. I brought an example from how the FEN Addon is doing their new SS UI which look alike to the old 1.0 UI Seren had. And also I have a horrible example I did on the go, I mean it's HORRIBLE! with capitals so be warned. But perhaps the concept of what I'm trying to express is what I mean. This is not something of a priority just to let you know, it's something that perhaps after you get all of the bugs out of the way and you have some free time to explore and desire to improve beyond what it is today, you could think about it.

**Describe the solution you'd like**
Here we go bro, this will be an ugly example so be WARNED! coming from 
1. What it looks right now

2. How FEN Addon is doing their SS UI with Artwork Poster which resembles a lot to the old 1.0 UI

3. My HORRIBLE concept of what it could look like, of course giving it your magic touches this concept is mainly of how the right button could be rearranged to open up more space and plot box could be smaller, etc.

![image](https://user-images.githubusercontent.com/76958541/104752984-5e27b880-5725-11eb-9b89-839b9d664b07.png)

![image](https://user-images.githubusercontent.com/76958541/104755399-5f0e1980-5728-11eb-91c8-437cc24d8b2c.png)

![image](https://user-images.githubusercontent.com/76958541/104755421-6503fa80-5728-11eb-95ef-29a34f6baf27.jpeg)

**Additional context**
I apologize for my horrible concept made by yours truly 🤷‍♂️🙆‍♂️. Either way that's what I have, like I said before. Don't put this as a priority over anything else, keep fixing other stuff and maybe just MAYBE... in the near future when you don't have much big fixes and  priority changes to apply into Seren. You can perhaps dig back to this request and see what you can do, lol. 

Anyone feel free to laugh at my concept "piece of art". 😅

**Comment by nixgates** [comment]
@Nuklear92 this is something that a custom theme would need to handle. Perhaps you can dip your toes into how skins work in Kodi! They are fairly simple and this wouldn't take to much to do.

If you need any guidance, feel free to message me on reddit :+1:
