### ISSUE TITLE
[BUG]still stuck with 2.0.10 not 2.0.12- auto update = on

### ISSUE THREAD

**Issue by JimiJoe** [nixgates/plugin.video.seren#419]
Ehm.. call me a noob or a weenie on a stick but https://nixgates.github.io/packages which always worked fine in kodi keeps seren at 2.0.10. Has the repo moved to a new url? @nixgates @mtaki14

**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you 
**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]
 - 

**Additional context**

**Comment by drinfernoo** [comment]
Open the context menu on Nixgates Repo and "Check for updates".

**Comment by JimiJoe** [comment]
Love you!
