### ISSUE TITLE
[BUG] Very few pages of movies in genres.

### ISSUE THREAD

**Issue by GodsLikelyMe** [nixgates/plugin.video.seren#420]
**Logs**

No log for this one

**Describe the bug**
When searching for moving in genres like in horror I only get 5 pages total. 

**To Reproduce**
Discover movies
Select genres
Choose one like horror and I only see a total of 5 pages. 
I have it set to 20 items per page.

**Expected behavior**
Don't see why it doesn't get as many pages as TMBD or other addons

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Version 2.0.12

**Additional context**

**Comment by nixgates** [comment]
@GodsLikelyMe in the interface settings, you can set your genre endpoint to be either trending or popular. Set this to popular to resolve your issue :)

**Comment by GodsLikelyMe** [comment]
Oof.. My bad. Did not realize that was for that. Sorry and thank you.

**Comment by GodsLikelyMe** [comment]
> @GodsLikelyMe in the interface settings, you can set your genre endpoint to be either trending or popular. Set this to popular to resolve your issue :)

Oof.. My bad. Did not realize that was for that. Sorry and thank you.
