### ISSUE TITLE
Trakt not staying in Seren and Filters too restrictive error

### ISSUE THREAD

**Issue by Sobersally** [nixgates/plugin.video.seren#422]
Here is my log:
https://paste.kodi.tv/wugocunesu

I am having 2 issues with Seren. Prior to updating to 2.0.12 I had an error on all my searches of:
Filters too restrictive and then once I updated to the newer version, my trakt won't stay in my Seren. If I close Seren and come back I have to go back into the accounts tab and reauthorize Trakt all over again and then I get the filters too restrictive message. If I pick yes at that point, it says I have no sources which I clearly do, and if I pick no, it takes me out of the sources page and back to my show.
Thanks for all that you do and for this wonderful addon.

Kodi version 18.9 for windows

**Comment by nixgates** [comment]
@Sobersally apologies, I'm pushing an update now to fix the settings issue.

In regards to the filters too restrictive, it means exactly that, the filters you have in place are removing all available source. Can you confirm your sort & filter settings and ensure they are correct for the sources you are trying to play.

**Comment by Sobersally** [comment]
Nixgates, thank you for your reply. I have looked at the sort and filter settings, and never had to mess with them before but can't tell which settings are creating this error. I increased the file sizes, I only have Hide 3D items checked, my source grouping style is torrents and I have Enable secondary filesize sort checked,  Am I missing something? Thanks again

**Comment by Sobersally** [comment]
I got the addon to work without the error on the sort and filter issue. However, and I am sure you are aware that every time one exits Seren, we have to reauthorize trakt. Otherwise, Seren is the best addon for Kodi! I love it .

**Comment by RichardManciniJr** [comment]
Came here to start a new issue and found this. Exact same issue.

**Comment by nixgates** [comment]
This should be fixed in 2.0.13.

You may encounter the issue once more as it finally sticks, but will good after that.

**Comment by nixgates** [comment]
@Sobersally can you please confirm is this is fixed in latest version?

**Comment by Sobersally** [comment]
Nixgates!
It works for me , where trakt is staying with the new update 2.0.13. You rock!

**Comment by nixgates** [comment]
@Sobersally sounds good! Closing it off :)
