### ISSUE TITLE
[BUG] Trakt Lists always paginated and taking 10+ minutes to load large Trakt Lists

### ISSUE THREAD

**Issue by Ebonlore** [nixgates/plugin.video.seren#424]
Trakt Lists are paginated even with the setting turned off
Trakt Lists now take forever to load (10+ minutes while it builds cache.db)  with Trakt accounts that have several hundred lists.

My cache.db is over 200MB and traktSynce.db is over 290MB now.  Previously cache was minimal and tracksync was 221MB on 2.0.10.  Plus Trakt lists didn't take 10 minutes to load and they weren't paginated.

There needs to be a way to use Trakt without having 500MB+ stored locally.  Instant load of lists was ok but is storing 200+MB worth it?

**Comment by nixgates** [comment]
I'll look into managing those a little better somehow. The amount of data consumed is not something I can control though. That is data generated for each item in the lists. All the Trakt data for those lists are currently stored locally as you can see and the extended meta is acquired on request. This amount of data would be the exact same as if you had browsed the lists. 

I will make it a priority to move list syncing to the background so this large load time of lists is reduced in the menus.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
