### ISSUE TITLE
[BUG]Finish Watching

### ISSUE THREAD

**Issue by derrgoo** [nixgates/plugin.video.seren#426]
**Logs**

Please provide debug logs to assist with your issue

First time submitting a bug report. Finish watching section. Maybe I am doing something wrong but in previous version I would open context menu and click on trakt manager and select remove playback progress and it would delete the movie from this area. Now it deletes but comes back on other devices. Before version it would remove all.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by nixgates** [comment]
Ok i can have a look at that, no worries about your empty issue before, got do something for the first time once! :)

In regards to the other devices, how quickly are you checking them? Bookmarks are synced to the local device every ~15 minutes or so.

**Comment by derrgoo** [comment]
Thank you. I checked about an hour later. By the way great feature!

**Comment by vermope** [comment]
I have the same problem..

**Comment by SirRickie** [comment]
Is there a way to delete all the movies in this area by one click ? Or do I have to delete them one by one ? Tnx.

**Comment by derrgoo** [comment]
> Is there a way to delete all the movies in this area by one click ? Or do I have to delete them one by one ? Tnx.

One at a time as far as I know.

**Comment by nixgates** [comment]
@SirRickie its one by one in Seren but there other options outside of Seren to do multiple ones.

@derrgoo was the other device on for that hour or did you start it an hour later? Note, when you first start the device, there will be stale information for the initial boot of widgets and menus until the background sync happens.

**Comment by derrgoo** [comment]
I just started it so maybe that was the reason as you exolaine. I will test again. Thank you

**Comment by SirRickie** [comment]
> @SirRickie its one by one in Seren but there other options outside of Seren to do multiple ones.
> 
> @derrgoo was the other device on for that hour or did you start it an hour later? Note, when you first start the device, there will be stale information for the initial boot of widgets and menus until the background sync happens.

Can you give me a hint how to do multiple ones outside Seren, because I would like to clear this section ?

**Comment by nixgates** [comment]
@SirRickie head over to here, this online app allows you to manually bulk clear progress markers https://sharkykh.github.io/tppm/

**Comment by nixgates** [comment]
@derrgoo how did you go with checking this?

**Comment by derrgoo** [comment]
> @derrgoo how did you go with checking this?

Working great thank you!

**Comment by nixgates** [comment]
@derrgoo good to hear! Will close this off :)
