### ISSUE TITLE
[Bug] Seren 2.0.13 Cannot retrieve source or playback

### ISSUE THREAD

**Issue by bdkbaik** [nixgates/plugin.video.seren#427]
Description: When try to play any selection, it failed to retrieve any resource

Log: https://paste.kodi.tv/udoxojimek.kodi

Version:
 - Kodi 18.9
 - Seren 2.0.13

**Comment by bdkbaik** [comment]
@nixgates just wonder, is this a bug?

**Comment by bdkbaik** [comment]
Just manage to find workaround, need to reinstall back Seren If upgrade to this version

**Comment by nixgates** [comment]
Looks like there was an issue with your provider structure. A reinstall of your providers would have likely fixed this.

I'll close this off :)
