### ISSUE TITLE
Seren 1 won't show movies at all - can't install seren 2 on Apple TV

### ISSUE THREAD

**Issue by borbak** [nixgates/plugin.video.seren#428]
For Apple TV useres the only Kodi version available is 17 or 19 (RC1).
Seren 2 only supports Kodi 18 and cannot be installed on Kodi 17/19.

Seren 1 no longs shows movies at all and thus isn't useful for Apple TV users.
Is this a bug?
If not, is there a release date for Seren 2 support for Kodi 19?

Thank you.

**Comment by nixgates** [comment]
There is, I'll be providing support in the next few days for 19 for 2.0.

If you desperately need to continue running 1.6.9, you can supply your own trakt client id and secret in Seren settings.

**Comment by borbak** [comment]
> There is, I'll be providing support in the next few days for 19 for 2.0.
> 
> If you desperately need to continue running 1.6.9, you can supply your own trakt client id and secret in Seren settings.

you are the best!! love your work.
Any way to danate??
