### ISSUE TITLE
Trakt lists not sorted correctly

### ISSUE THREAD

**Issue by drinfernoo** [nixgates/plugin.video.seren#43]
I've tested this in a fresh install of Kodi 18.0, with only Seren 0.1.31 installed and Trakt authorized.

Testing using [this Trakt list](https://trakt.tv/users/drinfernoo/lists/kids-movies?sort=title,asc), which is sorted correctly on the website (by Title, ascending), I've got a number of odd sortings [inside Seren](https://imgur.com/a/mt8dg3F). I recognize that this is a pretty large list, compared to some smaller ones... But there are also much larger lists available.

What could be causing this strange sorting?

**Comment by drinfernoo** [comment]
After looking at a few more lists, it looks like the only titles being sorted incorrectly are those that begin in "The", "T", "H", and "E", or combinations thereof, and are sorted correctly after those characters. For example, My list goes from "Rango" ->"Ratatouille" -> (He)"rcules" -> (T)"reasure Planet" -> "Recess: School's Out". It seems that something is broken in the "ignore articles" feature of Seren.

**Comment by nixgates** [comment]
This was my fault, it appears I accidentally used the strip function instead of replace.

Should be fixed next update.

**Comment by drinfernoo** [comment]
@nixgates Awesome! It took me some serious head-scratching to figure it out 👍

**Comment by nixgates** [comment]
Fixed in 0.1.34
