### ISSUE TITLE
[BUG] Cannot Open Provider Packages

### ISSUE THREAD

**Issue by Bulletbling** [nixgates/plugin.video.seren#432]
**Logs**

https://paste.kodi.tv/oqibuturah

**Describe the bug**
Will not allow me to manage provider packages. 

**To Reproduce**
Whenever I click on "Manage Provider Packages" so I can add the scrapers, it gives me an error. 

**Expected behavior**
To be able to add the a4k provider package, but I cannot get there. 

**Kodi Version (please complete the following information):**
 - Kodi Version [18.9 Leia]
 - Seren Version [2.0.13]

**Additional context**
I had to uninstall and reinstall Seren since clearing the data wouldn't fix the Trakt issue (no matter how many times I tried to activate seren on Trakt page, it wouldn't do anything; the code entry form would be blank again after I submitted the code). This issue occurred after reinstalling seren 2.0.13.

**Comment by JayDee696969** [comment]
Try changing a setting in the settings menu and hit OK. Then open Settings again. This worked for me. Or restart Kodi if it still doesnt work.

**Comment by Bulletbling** [comment]
> Try changing a setting in the settings menu and hit OK. Then open Settings again. This worked for me. Or restart Kodi if it still doesnt work.

This seemed to work for me. Weird!
