### ISSUE TITLE
Hide episode screenshot artwork

### ISSUE THREAD

**Issue by Dealz-416LS** [nixgates/plugin.video.seren#433]
Is it at all possible to hide the episode screenshot artwork (Landscape view) of unwatched episodes until after it’s been marked as watched to avoid spoilers?

**Comment by nixgates** [comment]
@Dealz-416LS you can't set it to hide/unhide on watched. 

You can disable episode fanarts (Large thumbnails) using the following setting:

Artwork > Advanced TV Artwork Settings > Episode Fanart

**Comment by Dealz-416LS** [comment]
I already have that option disabled but still see episode screenshot artwork (Landscape), that option however did work for the background Fanart so episode screenshots are removed from the background.

Is it something that could be added? 

Ability to not display episode screenshot artwork (Landscape) until the episode is marked as watched?

Question: What does the setting “Hide next item in widgets”

**Comment by Dealz-416LS** [comment]
Kodi Settings > Media Settings > Videos > (Library) ‘Show information for unwatched items’ uncheck ‘Episode thumb’
