### ISSUE TITLE
Seren v 13 - Invalid Trakt API keys, your authentication has been reset.  Please re-auth Trakt account.

### ISSUE THREAD

**Issue by cdkao** [nixgates/plugin.video.seren#434]
**Logs**

Please provide debug logs to assist with your issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by cdkao** [comment]
I'm not sure what I'm supposed to do fix this.  I get this message daily now. 

Thank you!

**Comment by drinfernoo** [comment]
Reauthorize Trakt, as the pop-up instructs.

If that doesn't fix it, you'll need to attach a debug log.

**Comment by cdkao** [comment]
I don't have a Trak

> Reauthorize Trakt, as the pop-up instructs.
> 
> If that doesn't fix it, you'll need to attach a debug log.

I don't have a Trakt account and didn't need it before so do I need to create one in order to get this working?

Thanks in advance!

**Comment by MrJardaniWick** [comment]
Same here. Would be interested in seeing what the solution is.

**Comment by cbizzle14** [comment]
I don't use Trakt either but I get that message as well. I also get unknown error connecting to trakt every time I launch Seren. Never was an issue before 2.0

**Comment by inventitken** [comment]
I also do not have Trakt, nor will I at any future date. The new version update is now trying to force people to trakt accounts with pop ups.  Looks like it begins with the invoker process that it initiates.  I have this problem on many different units, to include pc.  This was a great add-ons, but with what I'm seeing now, I will be forced to remove from my units, and my new skin build.  Very disappointed, as from what I see thus far, is that it could be avoided.  Was a good short run though.  good luck with your marriage to trakt.

**Comment by cdkao** [comment]
> I also do not have Trakt, nor will I at any future date. The new version update is now trying to force people to trakt accounts with pop ups. Looks like it begins with the invoker process that it initiates. I have this problem on many different units, to include pc. This was a great add-ons, but with what I'm seeing now, I will be forced to remove from my units, and my new skin build. Very disappointed, as from what I see thus far, is that it could be avoided. Was a good short run though. good luck with your marriage to trakt.

I agree.  What a bummer that that this is happening.  Seren will be disabled for now in my build.

**Comment by nixgates** [comment]
@inventitken @cdkao I'm not forcing the authorization to Trakt at all. Seren has always used Trakt for the initial fetching of meta data for menus.

If you don't have a Trakt account authorized, check you don't have your own keys set for Seren in your settings. If you do, make sure they are active. Seren's original Trakt API keys were revoked and new ones had to be implemented in 2.0.11.

The message may be a little general in nature and could probably do with re-wording.

**Comment by cdkao** [comment]
@nixgates Thanks for the reply.  With your recent updates, I've been getting "Invald Trakt API keys, your authenciation has been reset.  Please re-auth your Trakt account.  Like I said before, I have never had to use Trakt with Seren and it has been working great until your recent updates.  I have also tried wiping and starting Seren from scratch but I am still getting this same message.

**Comment by JayDee696969** [comment]
@nixgates. What these users are saying is true. If you dont setup Trakt, this message comes up every startup. This is tested on a fresh install of Kodi, Windows 10, with only Repo installed and Seren. No Seren settings were touched.. Heres a log.
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/5827256/kodi.log)

**Comment by nixgates** [comment]
@JayDee696969 thanks for that log, this looks simple enough to fix and it seems like the background sync is trying to sync an account when one is not authorized. I'll fix this up and try and push an emergency patch for it today.

**Comment by cdkao** [comment]
> @JayDee696969 thanks for that log, this looks simple enough to fix and it seems like the background sync is trying to sync an account when one is not authorized. I'll fix this up and try and push an emergency patch for it today.

That's so awesome!  Thank you Nixgates!

**Comment by nixgates** [comment]
@cdkao issue was pretty easy to spot, got it resolved for next update :+1:

**Comment by inventitken** [comment]
Hello.  No trakt here. its like all of your trakt settings, just ignore any input, or not.  I loved your add-on prior to your last push.  I now get a screen of annoying trakt issues, to which none are set.  I did take another look at your script file after my writing. xml settings have no effect.  I venture a guess to the .db file.  I really don't have the time to edit the .db file.  I'm not at all interested in a trakt account at anytime.  From other comments, it would appear that setting up a trakt account, still does not solve the problem.  I now have no choice but to remove all seren installs and build installs. I have to say, you did a great job with the add on, it was my 1st line up.  Sorry to see it go.  Good luck with the iron grip of trakt, for whatever reason your on that path.   
    On Sunday, January 17, 2021, 04:47:45 PM PST, nixgates <notifications@github.com> wrote:  
 
 


@inventitken @cdkao I'm not forcing the authorization to Trakt at all. Seren has always used Trakt for the initial fetching of meta data for menus.

If you don't have a Trakt account authorized, check you don't have your own keys set for Seren in your settings. If you do, make sure they are active. Seren's original Trakt API keys were revoked and new ones had to be implemented in 2.0.11.

The message may be a little general in nature and could probably do with re-wording.

**Comment by JayDee696969** [comment]
> Hello.  No trakt here. its like all of your trakt settings, just ignore any input, or not.  I loved your add-on prior to your last push.  I now get a screen of annoying trakt issues, to which none are set.  I did take another look at your script file after my writing. xml settings have no effect.  I venture a guess to the .db file.  I really don't have the time to edit the .db file.  I'm not at all interested in a trakt account at anytime.  From other comments, it would appear that setting up a trakt account, still does not solve the problem.  I now have no choice but to remove all seren installs and build installs. I have to say, you did a great job with the add on, it was my 1st line up.  Sorry to see it go.  Good luck with the iron grip of trakt, for whatever reason your on that path.  

Dude, relax. He already said hes going to fix it.

**Comment by inventitken** [comment]
Sorry for the excitement. Just that I grow concerned when an addon clearly has settings identified as setting for the problem at hand, yet the settings are ignored, and not even an edit in the  controlling file will make it behave.  After watching tv addons inject code, not in a good way, I have pause.  I know that nixgates can and will solve the problem, can see he is very talented. I'm not looking for a war on words,  so my apologizes, I should have kept my concerns private.  I have fixed the problem on all of my machines. Good luck.
    On Monday, January 18, 2021, 04:32:35 AM PST, JayDee696969 <notifications@github.com> wrote:  
 
 



Hello.  No trakt here. its like all of your trakt settings, just ignore any input, or not.  I loved your add-on prior to your last push.  I now get a screen of annoying trakt issues, to which none are set.  I did take another look at your script file after my writing. xml settings have no effect.  I venture a guess to the .db file.  I really don't have the time to edit the .db file.  I'm not at all interested in a trakt account at anytime.  From other comments, it would appear that setting up a trakt account, still does not solve the problem.  I now have no choice but to remove all seren installs and build installs. I have to say, you did a great job with the add on, it was my 1st line up.  Sorry to see it go.  Good luck with the iron grip of trakt, for whatever reason your on that path. 


Dude, relax. He already said hes going to fix it.

**Comment by nixgates** [comment]
@JayDee696969 @inventitken 

Hey guys, this issue is now fixed, thanks for reporting it :)

**Comment by nixgates** [comment]
Fixed in commit 0d398cdf19743a5904100d1e1f68a00d04388fdb

**Comment by inoculate23** [comment]
Good job guys I was about to upload my log
