### ISSUE TITLE
[BUG] Trakt Watchlist not syncing

### ISSUE THREAD

**Issue by queensryche6** [nixgates/plugin.video.seren#435]
Trakt watchlist is not syncing properly. Only some of the entries are present. It works fine on other addons.

Thanks for your hard work!

**Comment by nixgates** [comment]
There is no sync for the watch list, but it does appear to be cached. Try clearing your cache and pulling again. I'll fix this for the next update.

**Comment by queensryche6** [comment]
Already did that. Thanks, You are the best!

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
