### ISSUE TITLE
[BUG] Dependency on xbmc.python version 2.26...

### ISSUE THREAD

**Issue by kulti75** [nixgates/plugin.video.seren#437]
I use Seren on 3 devices, 2 Apple TVs and an iPad. Apple TVs are on Kodi 17.6, iPad is on Kodi 18.9. I always get the dependency error on my devices and can’t install Seren. With the latest Seren update (.13) iPad on 18.9 got fixed (I do get the Trakt popup), but still can’t install on my Apple TVs on 17.6. Anyone know an easy fix or should I wait for further updates?

**Comment by drinfernoo** [comment]
Seren does not support Krypton any longer.

**Comment by kulti75** [comment]
Thanks for the quick answer. That’s a bunmer though. I really enjoyed Seren on my AppleTVs.
