### ISSUE TITLE
[REQUEST] In Progress Media Missing? 

### ISSUE THREAD

**Issue by Nazim1981** [nixgates/plugin.video.seren#439]
Watched and unwatched contents who linked with trakt available in Seren under my movies and tv section but one basic thing Continued watching Movies & Tv Shows or Episodes are missing, how can we know what we were watching and what extent we have watched. 
Consider it in next update.

**Comment by nixgates** [comment]
@Nazim1981 could you expand on what you're requesting? I'm really not sure what it is you're after.

**Comment by Nazim1981** [comment]
In progress movies & TV Shows? The point where we resume the movie and play later from exact same point where we left, means continued media,

https://m.imgur.com/3PiQ8oe

You can see progress bar for continued content. 

How can we remember what we have played through Seren because there is no in process media option in Seren, watched status and unwatched status is there but not Watching media, Fen, Venom, tmdb all have this ability.

**Comment by nixgates** [comment]
@Nazim1981 if you've connected your trakt account, inside the "My Shows"/"My Movies" menus there is the menu "Continue watching".

This menus contains the last played point for movies/tvshows :)

**Comment by Nazim1981** [comment]
> @Nazim1981 if you've connected your trakt account, inside the "My Shows"/"My Movies" menus there is the menu "Continue watching".
> 
> This menus contains the last played point for movies/tvshows :)

Unfortunately there is NO ''Continuous Watching'' in My Movies/My Shows
[https://i.postimg.cc/nr11cNS5/image.png](url)
[https://i.postimg.cc/fy0hGjHJ/image.png](url)

**Comment by SerpentDrago** [comment]
its called "Finish Watching" 

which is a section that will show you any recent trakt bookmarks (you started watching something and then quit out )

**Comment by nixgates** [comment]
@SerpentDrago thanks! Lol even i can't remember what it's called apparently lol
