### ISSUE TITLE
[BUG] Trakt rating dialog not being displayed for movies.

### ISSUE THREAD

**Issue by Dealz-416LS** [nixgates/plugin.video.seren#440]
**Logs**
https://github.com/trakt/script.trakt/issues/519#issuecomment-762442835

**Describe the bug**
Trakt rating dialog box for movies isn't being displayed after playback due to 'resources.lib.scrobbler' not getting a title, only the year. 

All 'resources.lib.scrobbler' entries that i looked at in the log are missing movie title.

Movie title missing from below log entry.
`2021-01-18 19:24:05.221 T:20563 DEBUG: [script.trakt] resources.lib.scrobbler: Failed to scrobble movie: {'year': 2011, 'title': u''} | 98.153848588 | stop`

https://github.com/trakt/script.trakt/issues/519#issuecomment-762525494

Working just fine for Shows, title of show is present.

`2021-01-18 19:22:02.740 T:20563   DEBUG: [script.trakt] resources.lib.scrobbler: scrobble sending show object: {'year': 2008, 'title': u'Prison Break'}`

**To Reproduce**
1. Start watching a movie
2. At the end of the playback a Trakt rating dialog GUI isn't displayed.

**Expected behavior**
_Rate Movie after watching checked in Trakt settings._
At the end of a playback of a movie the Trakt rating dialog box should be displayed so that a rating can be submitted.

**Screenshots**
N/A

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren Version 2.0.13

**Additional context**
N/A

**Comment by SirRickie** [comment]
Same here. Hope this can be solved.

**Comment by StanLee01** [comment]
Same here

**Comment by onlytanmoy** [comment]
Yep, got the exact same issue.

**Comment by Dealz-416LS** [comment]
Additional Issues: 

I believe due to this issue Scrobbling of movies doesn’t work so therefore resume points and mark as watch don’t work.

**Comment by drinfernoo** [comment]
@Dealz-416LS That shouldn't be related, as that is something separate from the rating dialog implemented by `script.trakt`.

**Comment by Dealz-416LS** [comment]
@drinfernoo okay, I just thought since `resources.lib.scrobbler` Isn’t getting a Movie name for the Trakt rating dialog to work then it would also explain why everything else for movies scrobbling (Resume, Marked as Watched) also doesn’t work since there is no Movie title being sent to Trakt.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
