### ISSUE TITLE
[Filter] Keyword preference for auto play

### ISSUE THREAD

**Issue by tundrablasen** [nixgates/plugin.video.seren#441]
First of all, thank you nixgates for this great addon. if there is any way how we can tip you a beer, please let us know.

Now to my request:
I would want to use "auto play" but need to use "source select" due to several reasons:
mostly the results on top are not always the one i wanna choose. they are often the biggest with foreign language (ITA often). 

1. for tv shows i most likely always choose an Amazon Web-DL if available. Therefore i always look out for "**AMZN**" in the file name.
2. for movies i really like the results from "**Tigole**" and "**FGT**" or "**NTG**". Therefore i have a look out in the file names for these results from this groups.

so i think you get the point:
it would be great if the would be able to set certain key words (seperately for movies and tv shows) in the seren addon settings, which get considered and prefered during the autoplay process, even though the aren´t the first results. if non of the keywords are found, the old autoplay logic kicks in (cloud inspection/first item get choosen).
This would make the autoplay feature for me 10x more useful, because then i didnt need to manually choose the right release myself.
this feature should als be used during the the nextup phase when choosing the next episode for a tv show season.

This keyword preference filter could be places in the "filter" tab of the addon settings.

thanks nixgates for considering my request.

**Comment by JacopoV** [comment]
I'm glad i've looked into this one because i was about to open a ticket exactly like this one. 

I would def use autoplay if i could set some keyword to match (otherwise rollback to source select). Mine would be like "HDR,2160p" :) I do pick HDR 2160p sources if available and it's not always the first option at the top of the list 👍

**Comment by mrXoo** [comment]
Adding to this maybe the ability to filter out something’s as well like language “ITA, FRENCH, RUS” etc
