### ISSUE TITLE
[REQUEST] configurable option for Smartplay cache/expiration time

### ISSUE THREAD

**Issue by henryjfry** [nixgates/plugin.video.seren#444]
On pre 2.0 version of Seren I had modified the expiration time for smartplay to 12 hours so that when I pick up the next episode of a show I was watching last night it doesnt need to rescrape.

Ive tried making a similar modification for Seren 2.0.13 but for the life of me cant find the option in the code where it determines if a currently cached link has already expired.
It seems to currently try and rescrape after an hour or two, which is too short in my opinion.

Could the expiration time for precached/smart play links be a user configurable option?

**Comment by nixgates** [comment]
@henryjfry it's currently set to an hour. It should be noted though, playable links from debrid providers do expire and I would not recommend setting it to something as high as 12 hours. This is something more advanced that I wouldn't like to expose to most users.

If you want to manually adjust it yourself, look in:
`resources > lib > modules > helpers` 

You'll notice the cache decorator for each method.

`    @use_cache(1)`

Set the integer to what ever hour value you like.

**Comment by henryjfry** [comment]
Ok thats good to know, I did see those lines in the code but that must be some pythonic stuff i'm not too familiar with at this stage in my learning, i just figured it was like a true/false indicator.

I get why you might not want to have this as a user configurable option, for me I'm happy to rescrape on the odd occasion a RD link has expired in the interim. Cheers.
