### ISSUE TITLE
[REQUEST] Trakt2Kodi browser extension integration

### ISSUE THREAD

**Issue by titelheld** [nixgates/plugin.video.seren#447]
Hey I have found this awesome browser extension: https://panicked.xyz/trakttokodi/

Browser Extension description: Open/Play content with a compatible Kodi add-on from trakt.tv in your browser.

It would be amazing if you could support it in Seren.

They way I envision it is that one could sit on their couch browsing Trakt.tv on their laptop computer and just press the play button on the Trakt website and the movie/tv show will start to play on Kodi via Seren.

**Comment by titelheld** [comment]
this is the link to the Kodi plugin needed to support the browser extension. 

https://github.com/anxdpanic/script.trakttokodi.libconn

**Comment by drinfernoo** [comment]
That plugin only works with library content, it appears.

**Comment by titelheld** [comment]
That’s is a shame. Unfortunately I know very little about programming so I thought perhaps it would be possible.

The developer however posted in an issue thread that ‘Anyone can make an add-on to use the extension, the end-points are documented [here](https://github.com/anxdpanic/TraktToKodi-Extension/wiki/Addon-Endpoints).’ 
I thought that perhaps with these ‘endpoints’ integration into Seren would be possible.

This is the link to the issue thread: https://github.com/anxdpanic/script.trakttokodi.libconn/issues/1

**Comment by drinfernoo** [comment]
Actually, reading through the endpoints wiki page and issue you attached, it does look like it *may* be possible.

@nixgates This may be kind of cool, as it appears you set the add-on ID in the script's settings, and then it simply passes through the correct IDs in order to play, similar to the way TMDbHelper works.
