### ISSUE TITLE
[BUG] Time delay in marking videos as watched in Trakt and Up Next Dialog not working

### ISSUE THREAD

**Issue by ShibajiCh** [nixgates/plugin.video.seren#450]
Hi @nixgates ,

This issue is similar to #429. However, it's a bit different so I'm opening a new issue ticket.

Trakt scrobbles fine on video playback but after watching the video it's not marked as watched in Trakt. I noticed that this mainly happens when I continuously play a video from start to end without fast forwarding it till the end. On observing the issue keenly on several devices I found out that the watched video gets marked as watched in Trakt after a time delay of 12-15 mins once the video playback completely ends. Hence, the Next Up list is also not refreshing automatically after the playback ends and I have to refresh it manually after 15 mins to view the next episode. Prior to Seren 2.0.x it used to work perfectly.

My second issue is that I'm not getting the "Up Next" Dialog pop-up for the next episode at the end of the video.

I'm unable to understand what's causing these issues. Could you please check and advise? Thanks!

My setup details:
Kodi version 18.9
Seren version 2.0.13
Device - Nvidia Shield TV Pro / Windows 10 PC
Trakt addon is also installed separately for local video scrobbling.

**Comment by nixgates** [comment]
@ShibajiCh do you happen to have the trakt addon scrobbling as well? This will cause an issue when Seren tries to mark it watched.

I'm not sure how it could be happening that far after the show. 

The fact you're not getting the dialog makes me think something is locking Seren up in the background during playback.

Could you perhaps try disabling the Trakt addon temporarily and see if that makes a difference?

**Comment by ShibajiCh** [comment]
> @ShibajiCh do you happen to have the trakt addon scrobbling as well? This will cause an issue when Seren tries to mark it watched.
> 
> I'm not sure how it could be happening that far after the show.
> 
> The fact you're not getting the dialog makes me think something is locking Seren up in the background during playback.
> 
> Could you perhaps try disabling the Trakt addon temporarily and see if that makes a difference?

Hi @nixgates,

First of all I updated Seren to version 2.0.15. Then as per your instructions, I disabled the Trakt addon temporarily. However, the same issue still happened. The scrobbling in Trakt was fine, but once the video playback completely finished it took around 15 mins to get marked as watched in Trakt. I tested in multiple Kodi setups on different devices and the same issue happened. Therefore, I can confirm that this is an issue with Seren itself and not due to the Trakt addon running simultaneously. Prior to Seren 2.0.x also the Trakt addon used to run simultaneously and I never faced any issues.

Secondly, the up next dialog pop-up is still not showing up at the end of the video even after the recent Seren update.

Kindly advise. Thanks!

**Comment by ShibajiCh** [comment]
Hi @nixgates ,

Further to my above comments, I also noticed that after 15 mins time delay of completely playing a video I'm receiving a message from Seren that states "Unknown error connecting to Trakt", and just after receiving this error the video gets marked as watched in Trakt. That's really weird! Please advise. Thanks!

**Comment by nixgates** [comment]
I'll do a deep dive into this one today as its kind of important to look into.

I'll let you know what I find

**Comment by ShibajiCh** [comment]
> I'll do a deep dive into this one today as its kind of important to look into.
> 
> I'll let you know what I find

Thank you @nixgates! Looking forward to your findings. Thanks again!

**Comment by ShibajiCh** [comment]
Hi @nixgates,

Please find my Kodi log file here for your reference:
https://paste.kodi.tv/emuyajiwef.kodi

There are a lot of errors.
Kindly check and let me know what might be the issue.
I'm planning to install Kodi again from scratch.
Please advise! Thanks!

**Comment by ShibajiCh** [comment]
Hi @nixgates,

I re-installed Kodi from scratch on my Nvidia shield tv pro, still I'm facing the same issue. However, I'd like to let you know that this issue is only happening on NVIDIA Shield TV Pro and not on my Windows PC. On Windows PC both Trakt Scrobbling and Up Next pop up are working perfectly. So I guess this is an Android OS related bug. Also, I installed few other addons like Fen and Venom to see what happens. I observed that with Fen also I'm facing the same issue like Seren and with Venom a different issue happens, i.e. once the video playback ends Trakt starts re-scrobbling the same episode again. However, only the first time scrobbled video gets marked as watched in Trakt and nothing happens with the 2nd time scrobbled video. These issues are really weird! Could you please try to replicate these issues at your end and see what you can find out? Thanks!

**Comment by ShibajiCh** [comment]
Hi @nixgates,

Here is an updated Kodi log which I generated by **Excluding HTTP Sources from the Trakt addon**. However, the result is the same, i.e. there is a time delay of about 15 mins to mark the video as watched once the video playback ends. Just wanted to help you further.

https://paste.kodi.tv/jiladanete.kodi

Please advise. Thanks!

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
