### ISSUE TITLE
[BUG] Trakt TV show collection not loading - error generated

### ISSUE THREAD

**Issue by jastremit** [nixgates/plugin.video.seren#454]
**Logs**

link to updates log files:

https://paste.kodi.tv/gifimuyolu

**Describe the bug**
I get a Seren error when trying to access my tv shows collection. 

**To Reproduce**
1. Go to tv shows
2. Click on 'my tv shows'
3. Scroll down to 'collection'

**Expected behavior**
my trakt tv show collection should populate 

I am on Firestick 4k device running Kodi 18.7 Xanax build 2.6

**Comment by nixgates** [comment]
@jastremit can you please provide a log when raising an issue like this, can you also let me know what kind of device you are on and what version of kodi you are running. This information is actually quite important and requested in the bug template.

**Comment by jastremit** [comment]
@nixgates i uploaded logs and other info. my account was mistakenly flagged but i'm back active now. thank you and let me know if any other info is needed as i'm still receiving seren error when loading my tv shows collection

**Comment by nixgates** [comment]
> @nixgates i uploaded logs and other info. my account was mistakenly flagged but i'm back active now. thank you and let me know if any other info is needed as i'm still receiving seren error when loading my tv shows collection 

No worries, thanks for that!

One slight issue though, looks like your log is missing the error. For the log to help here, it needs to contain the error which you can get in there by recreating the error while debug logging is on :)

**Comment by jastremit** [comment]
> > @nixgates i uploaded logs and other info. my account was mistakenly flagged but i'm back active now. thank you and let me know if any other info is needed as i'm still receiving seren error when loading my tv shows collection 
> 
> No worries, thanks for that!
> 
> One slight issue though, looks like your log is missing the error. For the log to help here, it needs to contain the error which you can get in there by recreating the error while debug logging is on :)

-apologies again. i did not have debug turned on. here is the latest. i'll edit the original post as well. thank you! 

-[](https://paste.kodi.tv/gifimuyolu)

**Comment by jastremit** [comment]
> > > @nixgates i uploaded logs and other info. my account was mistakenly flagged but i'm back active now. thank you and let me know if any other info is needed as i'm still receiving seren error when loading my tv shows collection 
> > 
> > No worries, thanks for that!
> > 
> > One slight issue though, looks like your log is missing the error. For the log to help here, it needs to contain the error which you can get in there by recreating the error while debug logging is on :)
> 
> -apologies again. i did not have debug turned on. here is the latest. i'll edit the original post as well. thank you! 
> 
> -[](https://paste.kodi.tv/gifimuyolu)
> 

https://paste.kodi.tv/gifimuyolu


> 
>

**Comment by jastremit** [comment]
@nixgates just wondering if any update on the error loading my tv shows collection? is it resolved in kodi 19? thank you!

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
