### ISSUE TITLE
[BUG] Error when trying to watch movies/TV shows. Trending, most popular etc

### ISSUE THREAD

**Issue by cbizzle14** [nixgates/plugin.video.seren#455]
Xbox series X here. I can't watch anything. Can't even get past trending and the other categories. When I first launched Seren after the update it said something about rebuilding the database. I went to that in settings and still get errors. Can someone look at my log? I should state that I don't use a trakt account either

https://paste.kodi.tv/palihixopu

**Comment by MagicFirefly** [comment]
@cbizzle14 If you've using Trakt, it was down during this time.

**Comment by cbizzle14** [comment]
@MagicFirefly seems to be working now except I get the invalid keys error again along with unknown error connecting to trakt. When I first updated I didn't have that error until after trakt came back

Https://paste.kodi.tv/etaramukix

**Comment by nixgates** [comment]
@cbizzle14 hey mate, just gonna double up what I said on reddit here. Give me 5 minutes, just running up a update to fix this :)

**Comment by nixgates** [comment]
@cbizzle14 should be fixed in 2.0.16. If you wouldn't mind checking and verifying that would be great 👍

**Comment by cbizzle14** [comment]
@nixgates it's working now, no error messages at all. Thank you for working on it right away!

**Comment by nixgates** [comment]
@cbizzle14 no worries :)
