### ISSUE TITLE
[BUG] Trakt Manager from Information Page Fails

### ISSUE THREAD

**Issue by JacopoV** [nixgates/plugin.video.seren#456]
**Logs**
Log with Seren error : http://paste.kodi.tv/azuhomabey

**Describe the bug**
From TV Shows Information page (using AuraMod Netflix view), if you click the tab for Trakt Manager, Seren throws an error, preventing Trakt Manager to launch.

**To Reproduce**
1. Go to Discovery Shows
2. Go into any category which will list some shows
3. Long press on any of them and click information
4. Once the information page (this case Netflix view from AuraMod) select and click Trakt Manager
5. Notice Seren is throwing and error preventing the manager to come up

**Expected behavior**
Trakt Manager seems accessible is any other situation, so it might be possible to open it up from the described behaviour.

**Kodi Version (please complete the following information):**
 - Kodi Version : 18.9 Leia
 - OS Version : Android TV 9
 - Seren Version : 2.0.15

**Additional context**
If i'm not mistaken, the very same behaviour used to work perfectly in 2.0.13.
If i try to open Trakt Manager from the view before, without opening the Netflix view information page, it works perfectly fine.
If i apply the same behaviour on Movies instead, it works perfectly fine.

If it's a problem with the skin (AuraMod), i do apologise for this ticket :) So in that case it can be closed straight away :) 
As usual, thanks for you time and patience.
Insane work guys, really!

**Comment by nixgates** [comment]
@JacopoV howdy! Unfortunately we did run across this a few days ago and found that the manager endpoint from the skin wont work with 2.0.

I also had a chat to the dev of the skin and is no longer working on it so I don't see this being worked on any longer either unfortunately.

Wish I could offer more assistance. If anything else crops up let me know!

**Comment by JacopoV** [comment]
@nixgates damn if you're quick :) Kudos for you Nix :P |

Sounds about right :) Well nothing we can do then :) Thanks for you time and for the explanation

**Comment by nixgates** [comment]
> @nixgates damn if you're quick :) Kudos for you Nix :P 
> 
> Sounds about right :) Well nothing we can do then :) Thanks for you time and for the explanation 

Not a problem, anytime :)

**Comment by JacopoV** [comment]
@nixgates Fixed the endpoint in AuraMod. Tested with 15 shows from home widgets, Seren lists and Trakt lits :)

**Comment by nixgates** [comment]
@JacopoV mind reminding me what changes you made? I might be able to do something on my side to help ease it.

**Comment by JacopoV** [comment]
@nixgates it was actually easy. In the file DialogVideoInfo-Includes.xml, line 3678, around mid line you have :
"a%20%22show%22%2c%20%22"

just replace "show" with "tvshow" and it works. Maybe on your end on Seren, to make it easier, if "show" fails then try with "tvshow" ?

**Comment by nixgates** [comment]
@JacopoV ah! Looks like that wasn't accounted for that in the legacy support!

I'll have this fixed up for the next update! Thanks for this!

**Comment by JacopoV** [comment]
No worries, glad to have helped! Thanks 👍

**Comment by Dealz-416LS** [comment]
Experiencing this issue again, The fix above by @JacopoV worked for me in Seren 2.0.16 - Leia, but it stopped working in Seren 2.0.17 - Leia

Currently testing Matrix Seren (2.0.17+matrix.1) and the fix doesn't work on it either.

Confirming file location - `.kodi\addons\skin.auramod\1080i\DialogVideoInfo-Includes.xml`

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6177896/kodi.log)

**Comment by JacopoV** [comment]
Yeah true that @Dealz-416LS. It's broken on 2.0.17 (using Matrix atm).
My change in AuraMod is still in place (using "tvshow" instead "show") so I guess this time is on Seren.

@nixgates any chance of to look into?

Many thanks for the support

**Comment by Dealz-416LS** [comment]
> 
> 
> Yeah true that @Dealz-416LS. It's broken on 2.0.17 (using Matrix atm).
> My change in AuraMod is still in place (using "tvshow" instead "show") so I guess this time is on Seren.
> 
> @nixgates any chance of to look into?
> 
> Many thanks for the support

Episodes and Movies work just fine, Seren error is only for Shows.

Agreed, we thank you for the support!

**Comment by Dealz-416LS** [comment]
Update:
Re-tested the fix by @JacopoV in Seren 2.0.18 unfortunately it still doesn't work.

**Comment by JacopoV** [comment]
@Dealz-416LS not quite sure if related to  Seren update, but now, on AuraMod, Seren is not showing anymore the streaming service loco. Used to visualise correctly Netflix, Apple TV + and such,  but not it's mainly empty and it something is shown, it's the actual studio which produce the content, not the service.  I might open a specific ticker for it

**Comment by Dealz-416LS** [comment]
Just to confirm you mean the Studio (Network) Logo in the bottom right corner on the information screen?

I can't say I've noticed an issue with the logos.

Can you tell me a show that is missing the logo for you and I can check at my end.

**Comment by JacopoV** [comment]
Yeah that. For example, For All Mankind used to show Apple TV + but now Sony Pictures (they're actually producing the content). 
The same for Winter Soldier from Disney + . Used to have Disney + logo but now Marvel Studio

**Comment by Dealz-416LS** [comment]
Oh I understand now, I just checked the two examples you gave and they haven't changed.

For All Mankind is still Apple TV+
The Falcon n t/ Winter Soldier is still Disney+

**fyi** I no longer have the changes to the file in place since the fix no longer works, in case that has something to do with it.

**Comment by JacopoV** [comment]
@Dealz-416LS oh, would you mind to list me the Skin Helper , TMDB etc version you're running please ? Are you on Matrix? 
Many thanks

**Comment by Dealz-416LS** [comment]
Script.skin.helper.service 1.1.33
TheMovieDb Helper 4.3.1
Seren 2.0.18+matrix. 1

Yes, on Matrix 19.0

Not sure, maybe but to confirm i don't get any TMDb Helper error on start up.

**Comment by JacopoV** [comment]
So, i installed a 2 weeks old (was working backup).
Everything started working back again with :
tmdb tv shows 1.4.3
script.skin.helper.service 1.1.33
TheMovieDb Helper 4.3.1
Seren 2.0.18+matrix. 1

then 'The TVDN API v2' got updated and messed up everything again. I don't recall why i have that one honestly, and what it does

**Comment by Dealz-416LS** [comment]
I also have 1.4.3 for TMDb TV Shows, Oh so the logos are displaying correctly again?

You have TVBb API that your using? If so then yeah, I've never needed one.

**Comment by JacopoV** [comment]
Yeah, all worked before that TVBb API v2 updated. After, got messed up! I ll find a way to get rid of it! Thanks again for your time!

**Comment by JacopoV** [comment]
@Dealz-416LS It took me a while and so many tries, but i figure out the problem. I was correct when i was mentioning about the logos. It involved clearing the cache and updating Seren. I filed a bug because it's easy to reproduce and the actual data is populated in weird way : https://github.com/nixgates/plugin.video.seren/issues/595

**Comment by Dealz-416LS** [comment]
It's weird I haven't had any issues with the logos from what I've noticed when i have cleared cache etc. but there is something going on as your logos are changing, btw great work looking into the issue in 595!

**Comment by Dealz-416LS** [comment]
Update:

@JacopoV I re-tested your [fix/workaround](https://github.com/nixgates/plugin.video.seren/issues/456#issuecomment-765225923) on 2.0.19 and can confirm Trakt Manager for Shows still doesn't work. Episode and Movies still work just fine.

**Comment by JacopoV** [comment]
@Dealz-416LS I think till they will look into that, we'll have to wait =)
