### ISSUE TITLE
Having an Issue getting started with Seren.

### ISSUE THREAD

**Issue by BKAYD** [nixgates/plugin.video.seren#458]
I recently downloaded Kodi and seren for a friend and set them up with a real debrid account. I have downloaded Seren version 2.0.15. I have authorized the account on there, yet when I go to click on a movie it says 'no playable sources found' or 'seren error click the log for more information'
im not an expert at using this but Seren seems to be working for my console at home perfectly fine. Could anyone suggest any solutions?

**Comment by Wilson-Magic** [comment]
Sounds like you forgot to install providers.

**Comment by BKAYD** [comment]
How would i do this? Sorry im quite new to this.

**Comment by MagicFirefly** [comment]
Easiest way to find how to install a provider package is to do an online search for how to install Seren on Kodi. The package info is typically near the end of the install info.

**Comment by drinfernoo** [comment]
No reason for a duplicate issue.
