### ISSUE TITLE
Having trouble setting up seren

### ISSUE THREAD

**Issue by BKAYD** [nixgates/plugin.video.seren#459]
I recently downloaded Kodi and seren for a friend and set them up with a real debrid account. I have downloaded Seren version 2.0.15. I have authorized the account on there, yet when I go to click on a movie it says 'no playable sources found' or 'seren error click the log for more information'
im not an expert at using this but Seren seems to be working for my console at home perfectly fine. Could anyone suggest any solutions?

**Comment by nixgates** [comment]
@BKAYD could you provide a log? Have you installed any providers?

**Comment by nixgates** [comment]
Closing this off as it's gone a bit stale. 

If you'd like some support in the future just let me know and I'll help you out.
