### ISSUE TITLE
Local library items found but won't play

### ISSUE THREAD

**Issue by bluenote73** [nixgates/plugin.video.seren#46]
It's a great feature to check the local library in case I already have an item. But selecting a local item always fails with something like "no playable sources". I hope this can be fixed, Seren is really upping the ante.

**Comment by nixgates** [comment]
This is likely because Seren doesn't currently support direct link files from providers.

This will be adjusted soon and I'll let you know here when it should be released.

**Comment by bluenote73** [comment]
Thanks Nix, will eagerly wait on that.
