### ISSUE TITLE
[REQUEST] Source select list - make it compact and with bigger fonts

### ISSUE THREAD

**Issue by wasssu** [nixgates/plugin.video.seren#460]
Hi,

Is it possible to show the source list more compact and use maybe bigger and bold fonts?
Now it's a lot of wasted space, with a big logo on the left and a lot of empty space on top and bottom.

Thanks.

**Comment by nixgates** [comment]
@wasssu there are other themes for Seren to suit what you'd like. The default theme will remain how it is as theres more to come in the future for that window that will need the space.
