### ISSUE TITLE
[BUG] TV shows not working/error when loading

### ISSUE THREAD

**Issue by Shinzoai** [nixgates/plugin.video.seren#464]
**Logs**

![PXL_20210123_104457392](https://user-images.githubusercontent.com/77839875/105576495-fb5c9f80-5d6a-11eb-80b0-7897cf98cfc7.jpg)
![PXL_20210123_104439392](https://user-images.githubusercontent.com/77839875/105576498-00215380-5d6b-11eb-8abc-20eaa52df6cf.jpg)

Hello, 

Having a issue with my firestick where the TV shows are not showing at all. When trying to go into the start of the TV shows and choosing trending, most popular etc. it comes up with an error " check the log" and it displays nothing.

The movie section works fine and has no issues. 

I have a second firestick for another TV and the set up was the same but everything works perfectly on that one. 

I have tried deleting and reinstalling several times but I can't get it to work. 

 I have attached the pictures of the log but let me if you need anything else 

Thanks in advance

**Comment by R1chuk** [comment]
This is exactly the issue we have experienced in the last 24 hours, and can not find a way to rectify

**Comment by nixgates** [comment]
@Shinzoai I believe I have a workaround in place for this in the next update. Looks like something is off on that device and it's not returning a timezone to work with. The next update will allow devices like this to work, but it will just show times/release dates in UTC and not the local zone.

**Comment by Shinzoai** [comment]
@nixgates thanks for the info since you mentioned it might be a timezone issue on the firestick, I went into the settings and manually set the timezone and the TV shows on Seren are now working. 

Thanks for all your hard work.
