### ISSUE TITLE
[BUG] Xbox (Series) issue with a4kscrapers

### ISSUE THREAD

**Issue by McPoon** [nixgates/plugin.video.seren#467]
**Logs**
https://paste.kodi.tv/fasijasudi

**Describe the bug**
Started yesterday for me, couldn't load any shows or movies. Immediate error, won't search for links. I believe it happened after a certain update to the scrapers as it was fine before. So far I've reinstalled about 5 times, and it seems installing everything up to the point of Seren with no scraper package installed produces no errors. As soon as the package is installed, an error pops up and happens on every boot. None of my shows in Next Up will start and I can't play any movies. 

Also I cannot open the "manage provider packages' menu after installing,  it just loads forever after being clicked on.

**To Reproduce**
1. Install a4kscrapers.

**Kodi Version (please complete the following information):**
 - Kodi Version: latest on Xbox, 18.9.
 - Version: 2.0.16
 - A4kscrapers: Latest.

**Comment by nixgates** [comment]
Sorry this looks to be an issue with the provider package and not Seren. Best to check in with that dev and perhaps raise an issue on the relevant git.

If it ends up being a Seren issue, let me know and I'll happily fix it up.
