### ISSUE TITLE
Does Seren use the TVDB api and will it still work when it becomes a payed subscription and api v4 must be used?

### ISSUE THREAD

**Issue by peno64** [nixgates/plugin.video.seren#469]
This is a question, not a current issue or request.

As the titles says. Does Seren use the TVDB api and will it still work when it becomes a payed subscription and api v4 must be used?
On several  media it is reported that soon TVDB api will become paid and searching for series would become a problem then. Will this influence Seren?

**Comment by drinfernoo** [comment]
Seren doesn't use TVDB any longer, so this won't be an issue.

**Comment by peno64** [comment]
great!
