### ISSUE TITLE
Unable to use Seren, these are the errors in my kodi.log

### ISSUE THREAD

**Issue by ThirdStarr** [nixgates/plugin.video.seren#47]
I have Seren installed on a couple of my devices. I have my Real-Debrid and Traxt accounts registered to the addon, however whenever I try to use it I get the following in my kodi.log. What does this mean and how do I fix it? :

T:22835 ERROR: File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/debrid/real_debrid.py", line 277, in getRelevantHosters

2019-02-14 06:44:39.071 T:22835 ERROR: for domain, status in host_list.iteritems():

2019-02-14 06:44:39.072 T:22835 ERROR: AttributeError: 'NoneType' object has no attribute 'iteritems'

2019-02-14 06:44:39.073 T:22835 ERROR: Traceback (most recent call last):

2019-02-14 06:44:39.073 T:22835 ERROR: File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/debrid/real_debrid.py", line 277, in getRelevantHosters

2019-02-14 06:44:39.074 T:22835 ERROR: for domain, status in host_list.iteritems():

2019-02-14 06:44:39.074 T:22835 ERROR: AttributeError: 'NoneType' object has no attribute 'iteritems'

2019-02-14 06:44:39.707 T:22894 ERROR: Traceback (most recent call last):

2019-02-14 06:44:39.707 T:22894 ERROR: File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.seren/providers/LambdaScrapers/en/hosters/xmovies.py", line 57, in searchShow

2019-02-14 06:44:39.728 T:22894 ERROR: clean_title = cleantitle.geturl(title).replace('-','+')

2019-02-14 06:44:39.728 T:22894 ERROR: File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.seren/providerModules/LambdaScrapers/cleantitle.py", line 42, in geturl

2019-02-14 06:44:39.748 T:22894 ERROR: title = title.translate(None, ':*?"\'\.<>|&!,')

2019-02-14 06:44:39.748 T:22894 ERROR: TypeError: translate() takes exactly one argument (2 given)

2019-02-14 06:44:51.208 T:22999 NOTICE: SEREN: btScraper.episode.magnetdl: 0

2019-02-14 06:44:51.703 T:23056 NOTICE: SEREN: btScraper.episode.piratebay: 1

2019-02-14 06:44:52.577 T:22951 NOTICE: SEREN: btScraper.episode.katcr: 0

2019-02-14 06:44:53.776 T:22850 NOTICE: SEREN: btScraper.episode.torrentapi: 1

2019-02-14 06:44:55.204 T:23077 NOTICE: SEREN: btScraper.episode.1337x: 1

2019-02-14 06:44:55.465 T:23004 NOTICE: SEREN: btScraper.episode.bitlord: 0

2019-02-14 06:45:00.380 T:22869 NOTICE: SEREN: btScraper.episode.zooqle: 1

2019-02-14 06:45:00.585 T:22958 NOTICE: SEREN: btScraper.episode.yourbittorrent2: 0

2019-02-14 06:45:00.594 T:23034 NOTICE: SEREN: btScraper.episode.eztv: 0

2019-02-14 06:45:00.625 T:23020 NOTICE: SEREN: btScraper.episode.showrss: 0

2019-02-14 06:45:45.087 T:21674 NOTICE: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4

2019-02-14 06:45:45.099 T:21674 NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 22688 m_frames: 1418 m_frameSize: 8 channels: 2

2019-02-14 06:45:47.112 T:23598 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

Error Type: <type 'exceptions.TypeError'>

Error Contents: 'NoneType' object has no attribute '__getitem__'

Traceback (most recent call last):

File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/seren.py", line 380, in <module>

cacheAssist.CacheAssit(actionArgs)

File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/cacheAssist.py", line 37, in __init__

threads.append(threading.Thread(target=self.real_debrid_downloader(torrent_list[0], args)))

File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/modules/cacheAssist.py", line 110, in real_debrid_downloader

info = debrid.torrentInfo(magnet['id'])

TypeError: 'NoneType' object has no attribute '__getitem__'

-->End of Python script error report<--

**Comment by dejiapps** [comment]
Me too. This is what my log is showing:

17:12:53.240 T:8060   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
17:12:53.486 T:1480  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting GUI proc (6.0.15)
17:12:53.491 T:1480  NOTICE: script.tv.show.next.aired: ### no prior data found
17:12:58.547 T:5628 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.seren/?action=clearCache
17:12:58.547 T:5628   ERROR: XFILE::CFileCache::Open - failed to open source <plugin://plugin.video.seren/?action=clearCache>
17:12:58.547 T:5628   ERROR: InputStream: Error opening, plugin://plugin.video.seren/?action=clearCache
17:12:58.547 T:5628 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.seren/?action=clearTorrentCache
17:12:58.547 T:5628   ERROR: XFILE::CFileCache::Open - failed to open source <plugin://plugin.video.seren/?action=clearTorrentCache>
17:12:58.547 T:5628   ERROR: InputStream: Error opening, plugin://plugin.video.seren/?action=clearTorrentCache
17:12:58.554 T:5596 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.seren/?action=cleanInstall
17:12:58.554 T:5596   ERROR: XFILE::CFileCache::Open - failed to open source <plugin://plugin.video.seren/?action=cleanInstall>
17:12:58.554 T:5596   ERROR: InputStream: Error opening, plugin://plugin.video.seren/?action=cleanInstall
17:12:58.555 T:5628 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.seren/?action=openSettings
17:12:58.555 T:5628   ERROR: XFILE::CFileCache::Open - failed to open source <plugin://plugin.video.seren/?action=openSettings>
17:12:58.556 T:5628   ERROR: InputStream: Error opening, plugin://plugin.video.seren/?action=openSettings
17:13:15.233 T:8096  NOTICE: ES: Client  from ::ffff:10.0.0.35 timed out
17:14:10.234 T:8104  NOTICE: script.tv.show.next.aired: ### no prior data found
17:14:12.235 T:8104  NOTICE: script.tv.show.next.aired: ### starting data update
17:14:12.235 T:8104  NOTICE: script.tv.show.next.aired: ### grabbing a new country mapping list
17:14:32.539 T:8060   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
17:14:32.761 T:6352  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting GUI proc (6.0.15)
17:14:32.766 T:6352  NOTICE: script.tv.show.next.aired: ### no prior data found
17:14:34.899 T:5852   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.seren/?action=smartPlay&actionArgs=%7B%22art%22%3A%20%7B%22banner%22%3A%20%22https%3A//www.thetvdb.com/banners/graphical/5c2fd2ce36d8e.jpg%22%2C%20%22fanart%22%3A%20%22https%3A//www.thetvdb.com/banners/fanart/original/5c08541ef1589.jpg%22%2C%20%22landscape%22%3A%20%22https%3A//www.thetvdb.com/banners/fanart/original/5c08541ef1589.jpg%22%2C%20%22poster%22%3A%20%22https%3A//www.thetvdb.com/banners/posters/5c199ba9c485c.jpg%22%2C%20%22thumb%22%3A%20%22https%3A//www.thetvdb.com/banners/posters/5c199ba9c485c.jpg%22%7D%2C%20%22ids%22%3A%20%7B%22imdb%22%3A%20%22tt2356777%22%2C%20%22slug%22%3A%20%22true-detective%22%2C%20%22tmdb%22%3A%2046648%2C%20%22trakt%22%3A%2046375%2C%20%22tvdb%22%3A%20270633%2C%20%22tvrage%22%3A%2031369%7D%2C%20%22info%22%3A%20%7B%22castandrole%22%3A%20%5B%5B%22Matthew%20McConaughey%22%2C%20%22Rust%20Cohle%20%28S1%29%22%5D%2C%20%5B%22Woody%20Harrelson%22%2C%20%22Marty%20Hart%20%28S1%29%22%5D%2C%20%5B%22Michelle%20Monaghan%22%2C%20%22Maggie%20Hart%20%28S1%29%22%5D%2C%20%5B%22Rachel%20McAdams%22%2C%20%22Ani%20Bezzerides%20%28S2%29%22%5D%2C%20%5B%22Colin%20Farrell%22%2C%20%22Ray%20Velcoro%20%28S2%29%22%5D%2C%20%5B%22Taylor%20Kitsch%22%2C%20%22Paul%20Woodrugh%20%28S2%29%22%5D%2C%20%5B%22Vince%20Vaughn%22%2C%20%22Frank%20Semyon%20%28S2%29%22%5D%2C%20%5B%22Kelly%20Reilly%22%2C%20%22Jordan%20Semyon%20%28S2%29%22%5D%2C%20%5B%22Mahershala%20Ali%22%2C%20%22Wayne%20Hays%20%28S3%29%22%5D%2C%20%5B%22Carmen%20Ejogo%22%2C%20%22Amelia%20Reardon%20%28S3%29%22%5D%2C%20%5B%22Stephen%20Dorff%22%2C%20%22Roland%20West%20%28S3%29%22%5D%2C%20%5B%22Scoot%20McNairy%22%2C%20%22Tom%20Purcell%20%28S3%29%22%5D%2C%20%5B%22Ray%20Fisher%22%2C%20%22Henry%20Hays%20%28S3%29%22%5D%2C%20%5B%22Alexandra%20Daddario%22%2C%20%22Lisa%20Tragnetti%20%28S1%29%22%5D%2C%20%5B%22Tory%20Kittles%22%2C%20%22Thomas%20Papania%20%28S1%29%22%5D%2C%20%5B%22Michael%20Potts%22%2C%20%22Maynard%20Gilbough%20%28S1%29%22%5D%2C%20%5B%22Kevin%20Dunn%22%2C%20%22Ken%20Quesada%20%28S1%29%22%5D%5D%2C%20%22country%22%3A%20%22US%22%2C%20%22duration%22%3A%203600%2C%20%22episodeCount%22%3A%20%2225%22%2C%20%22genre%22%3A%20%5B%22Crime%22%2C%20%22Drama%22%2C%20%22Mystery%22%5D%2C%20%22imdbnumber%22%3A%20null%2C%20%22mediatype%22%3A%20%22tvshow%22%2C%20%22mpaa%22%3A%20%22TV-MA%22%2C%20%22originaltitle%22%3A%20%22True%20Detective%22%2C%20%22plot%22%3A%20%22An%20anthology%20series%20in%20which%20police%20investigations%20unearth%20the%20personal%20and%20professional%20secrets%20of%20those%20involved%2C%20both%20within%20and%20outside%20the%20law.%22%2C%20%22premiered%22%3A%20%222014-01-13%22%2C%20%22rating%22%3A%209.1%2C%20%22seasonCount%22%3A%203%2C%20%22showaliases%22%3A%20%5B%5D%2C%20%22status%22%3A%20%22Continuing%22%2C%20%22studio%22%3A%20%22HBO%22%2C%20%22trailer%22%3A%20%22plugin%3A//plugin.video.youtube/play/%3Fvideo_id%3DfVQUcaO4AvE%22%2C%20%22tvshowtitle%22%3A%20%22True%20Detective%22%2C%20%22year%22%3A%20%222014%22%7D%7D
17:14:34.913 T:8060   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.seren/?action=smartPlay&actionArgs=%7B%22art%22%3A%20%7B%22banner%22%3A%20%22https%3A//www.thetvdb.com/banners/graphical/5c2fd2ce36d8e.jpg%22%2C%20%22fanart%22%3A%20%22https%3A//www.thetvdb.com/banners/fanart/original/5c08541ef1589.jpg%22%2C%20%22landscape%22%3A%20%22https%3A//www.thetvdb.com/banners/fanart/original/5c08541ef1589.jpg%22%2C%20%22poster%22%3A%20%22https%3A//www.thetvdb.com/banners/posters/5c199ba9c485c.jpg%22%2C%20%22thumb%22%3A%20%22https%3A//www.thetvdb.com/banners/posters/5c199ba9c485c.jpg%22%7D%2C%20%22ids%22%3A%20%7B%22imdb%22%3A%20%22tt2356777%22%2C%20%22slug%22%3A%20%22true-detective%22%2C%20%22tmdb%22%3A%2046648%2C%20%22trakt%22%3A%2046375%2C%20%22tvdb%22%3A%20270633%2C%20%22tvrage%22%3A%2031369%7D%2C%20%22info%22%3A%20%7B%22castandrole%22%3A%20%5B%5B%22Matthew%20McConaughey%22%2C%20%22Rust%20Cohle%20%28S1%29%22%5D%2C%20%5B%22Woody%20Harrelson%22%2C%20%22Marty%20Hart%20%28S1%29%22%5D%2C%20%5B%22Michelle%20Monaghan%22%2C%20%22Maggie%20Hart%20%28S1%29%22%5D%2C%20%5B%22Rachel%20McAdams%22%2C%20%22Ani%20Bezzerides%20%28S2%29%22%5D%2C%20%5B%22Colin%20Farrell%22%2C%20%22Ray%20Velcoro%20%28S2%29%22%5D%2C%20%5B%22Taylor%20Kitsch%22%2C%20%22Paul%20Woodrugh%20%28S2%29%22%5D%2C%20%5B%22Vince%20Vaughn%22%2C%20%22Frank%20Semyon%20%28S2%29%22%5D%2C%20%5B%22Kelly%20Reilly%22%2C%20%22Jordan%20Semyon%20%28S2%29%22%5D%2C%20%5B%22Mahershala%20Ali%22%2C%20%22Wayne%20Hays%20%28S3%29%22%5D%2C%20%5B%22Carmen%20Ejogo%22%2C%20%22Amelia%20Reardon%20%28S3%29%22%5D%2C%20%5B%22Stephen%20Dorff%22%2C%20%22Roland%20West%20%28S3%29%22%5D%2C%20%5B%22Scoot%20McNairy%22%2C%20%22Tom%20Purcell%20%28S3%29%22%5D%2C%20%5B%22Ray%20Fisher%22%2C%20%22Henry%20Hays%20%28S3%29%22%5D%2C%20%5B%22Alexandra%20Daddario%22%2C%20%22Lisa%20Tragnetti%20%28S1%29%22%5D%2C%20%5B%22Tory%20Kittles%22%2C%20%22Thomas%20Papania%20%28S1%29%22%5D%2C%20%5B%22Michael%20Potts%22%2C%20%22Maynard%20Gilbough%20%28S1%29%22%5D%2C%20%5B%22Kevin%20Dunn%22%2C%20%22Ken%20Quesada%20%28S1%29%22%5D%5D%2C%20%22country%22%3A%20%22US%22%2C%20%22duration%22%3A%203600%2C%20%22episodeCount%22%3A%20%2225%22%2C%20%22genre%22%3A%20%5B%22Crime%22%2C%20%22Drama%22%2C%20%22Mystery%22%5D%2C%20%22imdbnumber%22%3A%20null%2C%20%22mediatype%22%3A%20%22tvshow%22%2C%20%22mpaa%22%3A%20%22TV-MA%22%2C%20%22originaltitle%22%3A%20%22True%20Detective%22%2C%20%22plot%22%3A%20%22An%20anthology%20series%20in%20which%20police%20investigations%20unearth%20the%20personal%20and%20professional%20secrets%20of%20those%20involved%2C%20both%20within%20and%20outside%20the%20law.%22%2C%20%22premiered%22%3A%20%222014-01-13%22%2C%20%22rating%22%3A%209.1%2C%20%22seasonCount%22%3A%203%2C%20%22showaliases%22%3A%20%5B%5D%2C%20%22status%22%3A%20%22Continuing%22%2C%20%22studio%22%3A%20%22HBO%22%2C%20%22trailer%22%3A%20%22plugin%3A//plugin.video.youtube/play/%3Fvideo_id%3DfVQUcaO4AvE%22%2C%20%22tvshowtitle%22%3A%20%22True%20Detective%22%2C%20%22year%22%3A%20%222014%22%7D%7D) failed
17:14:35.350 T:4260   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'episodeInfo'
                                            Traceback (most recent call last):
                                              File "C:\Users\HTPC\AppData\Roaming\Kodi\addons\plugin.video.seren\seren.py", line 514, in <module>
                                                episode = actionArgs['info_dictionary']['episodeInfo']['info']['episode']
                                            KeyError: 'episodeInfo'
                                            -->End of Python script error report<--

**Comment by nixgates** [comment]
Can you please in the future not attempt to put the log inside the text of the issue.

Instead please upload the full log to a text bin like pastebin, hastebin.

**Comment by dejiapps** [comment]
Of course, sorry about that.

**Comment by ThirdStarr** [comment]
Here is my kodi.log file https://pastebin.com/rxQDikeu

**Comment by dejiapps** [comment]
here is mine: [Kodi.log](https://pastebin.com/EJxfABrw)

**Comment by nixgates** [comment]
@dejiapps can you please a separate issue as your issue is different than this one and I'd like to concentrate on them separately.

@ThirdStarr do you have another device to test on? Or, alternatively can you please try to clear your Seren installation from the tools menu. Something really weird is happening there.

**Comment by ThirdStarr** [comment]
Opened Seren > Tools > Wipe Addon Data. Readded my traxt and redebrid accounts. Got "Unable to connect to file" when trying to install https://tinyurl.com/a4scrapers. Civitas scrapers installed successfully
Still getting errors [https://pastebin.com/D2tkAy5z](https://pastebin.com/D2tkAy5z)

**Comment by ThirdStarr** [comment]
Yesterday's update appears to have resolve my issue. Seren is not working for me. Thank you for all your hard work.

**Comment by nixgates** [comment]
@ThirdStarr thanks for getting back to me! 

Have a good one 👍
