### ISSUE TITLE
[BUG] Can't scrape any Tv- shows Seren 2.X

### ISSUE THREAD

**Issue by lalahlehlehh** [nixgates/plugin.video.seren#470]
**Logs**

Please provide debug logs to assist with your issue[](https://paste.kodi.tv/egarucuvor) 

**Describe the bug**
When scraping tv shows it cancels long before it's searched every provider. When searching movies it works perfectly. I do not have pre-emptive scraping on, and the timer don't reach 60 seconds. This has happened since seren 2.x . A temporary solution for me has been removing almost all providers since it can barely go through like 5-7 until it stops scraping

**To Reproduce**
1. Go to seren
2. Click on trending tv shows
3. Scroll down to grey's anatomy
4. Select season 11 episode "time stops" (or whatever tv show, it's the same issue for all)
5. It scrapes through like 5 of the 25 providers

**Expected behavior**
Go through all providers before ending scraping. 

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [18.9]
 - Version Seren 2.0.16]

**Additional context**

**Comment by lalahlehlehh** [comment]
Looks like I might have missed including the log, so pasting it here just in case:
https://paste.kodi.tv/egarucuvor

**Comment by SacriliciousQ** [comment]
I'm experiencing something similar.  Movies work as normal, but TV shows will not play.  I get an error almost instantly.  I don't see any providers being searched at all when it comes to TV shows.

Here's my info:

I had Seren working fine a few days ago, but today I'm unable to play anything on it.  The only error I get is "playback failed."

Operating System:  (Shield, so...Android 9?)

Device:  Nvidia Shield

Add-on affected:  Seren

Version of Kodi:  18.9

Version of Add-on: latest

Country:  USA

Any support services:  Real-Debrid, Trakt

Link to error log:https://pastebin.com/Yxz8Bizf

**Comment by inb4after** [comment]
> 
> 
> Looks like I might have missed including the log, so pasting it here just in case:
> https://paste.kodi.tv/egarucuvor

@lalahlehlehh Check [this section](https://paste.kodi.tv/ecacuwoqog.kodi) of your log, the scrape time was exactly 60 seconds as set in the timeout. I've tested with and without pre-emptive termination, emulating your settings and could not reproduce. I don't think this is a bug, but could be wrong.

**Comment by nixgates** [comment]
@lalahlehlehh unfortunately this appears to be a network configuration at the device rather than an issue in Seren.

Some of your installed providers are taking over 30 seconds alone to complete which would explain why you're not finding any sources. You'll need to confirm you can access the sites those providers use and make sure it can be done within a reasonable time limit.

Sorry as I can't be much more help here.
