### ISSUE TITLE
[BUG] Trakt popular recent shows not showing

### ISSUE THREAD

**Issue by sawo69** [nixgates/plugin.video.seren#471]
**Logs**

https://pastebin.com/L2BHL57b

**Describe the bug**
When selecting trakt popular shows seren closes

**To Reproduce**
1. Go to Discover TV shows
2. Click on Popular recent shows

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren Version 2.0.16

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.18.
