### ISSUE TITLE
[BUG] Error on Kodi startup, can't watch movies

### ISSUE THREAD

**Issue by cbizzle14** [nixgates/plugin.video.seren#472]
This is the same thing that was happening last week. Can't watch movies but can watch TV shows. I tried clearing Metadata but that didn't work. Log below

Https://paste.kodi.tv/itoyicekuv

**Comment by cbizzle14** [comment]
@nixgates

**Comment by nixgates** [comment]
@cbizzle14 apologies, I've been exceptionally busy the past few days. From what I can see, this was fixed by provider module in question.

Can you confirm it's working now on your end?

**Comment by cbizzle14** [comment]
@nixgates not a problem man. I had to do a complete reinstall of kodi to get the new providers. For some reason wiping seren add on data wouldn't work and the settings always remained after a reinstall of seren. But once I was able to get the new providers everything worked again.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
