### ISSUE TITLE
[BUG] Seren not loading any titles

### ISSUE THREAD

**Issue by Jayrpl** [nixgates/plugin.video.seren#473]
Seren not loading any titles for me.
Multiple errors on load-up, when I go to each category or search a TV show the resulting directory is completely empty.

here is my log:
[pastebin log](https://paste.kodi.tv/orugakumej)

**Comment by nixgates** [comment]
@Jayrpl looks like you're running an odd Android install which doesn't provide the timezone correctly.

This will be worked around in the next up date for you :+1:

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.17.
