### ISSUE TITLE
Question: How exactly is the real-debrid file selection done?

### ISSUE THREAD

**Issue by Jakobohrnell** [nixgates/plugin.video.seren#474]
I'm not sure if this kind of post is allowed, so remove if it isn't.

I'm working on my own program which integrates the real-debrid api and I'm struggling to find a consistent way of choosing the right files for instant download/streaming. Is there anyone that would be willing to help me? Seren has obviously figured it out. 
I've tried looking through the project code but can't figure it out.

**Comment by SerpentDrago** [comment]
https://api.real-debrid.com/

**Comment by Jakobohrnell** [comment]
Yeah, I've looked at that plenty obviously. But the list of file indices returned by the instant availability api call doesn't actually provide instant availability in a lot of instances. So I'm wondering if Seren does something different or not, and if so, what?

**Comment by nixgates** [comment]
@Jakobohrnell you need to make sure all the files are media files. If there are text files, nfo, etc, real debrid will zip up the download.

Also, as the api docs state, you need to select all the files in the array " you must ask all file IDs from this array on /selectFiles to get instant downloading"
