### ISSUE TITLE
[BUG] Re-watching an episode with subtitles already downloaded causes keepAlive cascade failure

### ISSUE THREAD

**Issue by inb4after** [nixgates/plugin.video.seren#476]
**Logs**

https://paste.kodi.tv/tusihaxahe.kodi

**Describe the bug**
Having both a4kSubtitles and Seren's subtitles feature enabled, re-watching an episode causes the "Cannot create a file when that file already exists" error (see log)

As a result, keepAlive fails and all dependant functions stop working (scrobbling progress, playingnext popup, trakt mark as watched)

Disabling Seren's subtitles feature (a4kSubtitles still enabled) fixes this and re-watching a previous episode works as normal again.

**To Reproduce**

1. Watch an episode with a4kSubtitles and Seren subtitle downloader both enabled
2. Playback finishes as normal
3. Watch the same episode again
4. Error appears near the start of the episode (around the time that subtitles download would kick in)

**Expected behavior**
No errors, as seen when a4kSubtitles is the only subtitle downloader enabled (Serens' disabled)

**Versions:**
 - Windows 10 Pro 64-bit
 - Kodi Version 18.9
 - Version 2.0.16

**Additional context**
It's sometimes inconsistent but keep rewatching the same episode to increase chance of error

**Comment by nixgates** [comment]
@inb4after fixed for next update :+1:

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.17.
