### ISSUE TITLE
[BUG]Can someone tell me why I get this error regularly?

### ISSUE THREAD

**Issue by mdisbrow85** [nixgates/plugin.video.seren#479]
**Logs**
https://paste.ubuntu.com/p/VF8PzqqYC3/

Please provide debug logs to assist with your issue

**Describe the bug**

Does not fetch any lists. For example I will select the trending list. It pulls a blank screen and throws an error. Happens at random and only way I can get it fixed is by starting fresh. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by MagicFirefly** [comment]
@mdisbrow85

Seren is up to version 2.0.16 as well as nixgates repository has been updated to v2. Update the repository to v2 which will also update Seren.

2021-01-14 02:36:27.887 T:4067164176  NOTICE: ADDON: plugin.video.seren v2.0.10 installed

2021-01-14 02:36:27.887 T:4067164176  NOTICE: ADDON: repository.nixgates v1.0.0 installed

**Comment by mdisbrow85** [comment]
Thanks, I’m pretty sure Seren is on the latest but I’ll double check. 

In the log line 13031 show 2.0.16

2021-01-26 02:15:00.788 T:3261035392  NOTICE: ADDON: plugin.video.seren v2.0.16 installed

**Comment by nixgates** [comment]
@mdisbrow85 looks like you have a ton of issues with your install. You might to just blow away the addon data and reset up Seren.

(Tools > Wipe Addon Data)

There are issues with your trakt auth, databases, etc. Just much easier to try start again.

**Comment by mdisbrow85** [comment]
Thank you for the quick reply. I'm just going to start with a fresh install of CoreElec.

**Comment by trkselim** [comment]
Same here 
beelink gt king pro
Coreelec kodi 19c

**Comment by drinfernoo** [comment]
The original log in this issue specifically states that Seren version 2.0.10 is installed. Update.

**Comment by nixgates** [comment]
@mdisbrow85 mind if I ask how you went with this?

**Comment by mdisbrow85** [comment]
@nixgates I actually went ahead and started with a fresh install of CoreElec. That’s the only way I’ve been able to resolve it in the past. It’s something I have issue with on nearly a monthly basis. I use a very basic set of addons so it’s pretty quick to reinstall. The next time I get the error I’ll try just wiping the addon and report back.

**Comment by nixgates** [comment]
> @nixgates I actually went ahead and started with a fresh install of CoreElec. That’s the only way I’ve been able to resolve it in the past. It’s something I have issue with on nearly a monthly basis. I use a very basic set of addons so it’s pretty quick to reinstall. The next time I get the error I’ll try just wiping the addon and report back. 

@mdisbrow85 

Ok no worries, I'll close this off for now. If it comes back feel free to re-open this or raise a new one :)
