### ISSUE TITLE
[REQUEST] Integration of SIMKL as an alternative to Trakt

### ISSUE THREAD

**Issue by sathish804** [nixgates/plugin.video.seren#480]
**Is your feature request related to a problem? Please describe.**
Please integrate https://simkl.com/ api for tracking tv, movies into Seren addon as an alternative for the Trakt.

**Describe the solution you'd like**
User should have an option to choose between SIMKL and Trakt to track their Progress.

**Comment by JayDee696969** [comment]
So what makes this any better than Trakt?

**Comment by sathish804** [comment]
> So what makes this any better than Trakt?

Its not better than trakt but features are same like trakt. Users will have an option to choose between either trakt or simkl for tracking their progress.
