### ISSUE TITLE
[BUG] Most Watched and Trending TV Shows not Working

### ISSUE THREAD

**Issue by Bulletbling** [nixgates/plugin.video.seren#482]
**Logs**

Https://paste.kodi.tv/asegutiqew

**Describe the bug**
Trending and Most Watched List are being duplicated from Next up and/or finish watching. Most of my next up shows (3 out of 4) are duplicated to the trending tv and most watched tv shows categories.

**To Reproduce**
View the categories. Started happening I think after the .16 update. 

**Expected behavior**
Trending should show trending shows and most watched should show most watched shows. Both are showing shows from my next up category (or possibly the finish watching category since both categories have the same shows). 

**Versions:**
 - Kodi Version 18.9 Leia Auramod
 - Seren version 2.0.16

**Comment by nixgates** [comment]
@Bulletbling Should be fixed for next update, apologies for that!

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.17.
