### ISSUE TITLE
[BUG] - Kodi Quits Seemingly Random (After show ends or is stopped)

### ISSUE THREAD

**Issue by biscuitgod** [nixgates/plugin.video.seren#483]
**Logs**

https://paste.kodi.tv/hukogoronu.kodi

**Describe the bug**
Having weird issue which doesn't happen all the time - Kodi will quit on me, but only after a show (not sure about movie as i haven't played any recently) is done playing or is stopped during play.   I have noticed that it seems to happen more on the first show played from startup of any watching session, but not all the time.   Issue was happening on my FireTVs, but was just able to reproduce on my clean install at my PC.   Seren is the only addon I use to play shows/movies - Nothing else installed besides skin and required addons

**To Reproduce**
1.   Start Kodi
2.   Play any show
3.   Stop show after play starts or watch until it starts
4.   Kodi then quits

**Expected behavior**
Kodi shouldn't quit.   I should be taken back to main screen and have my NextUp list updated to next episode if available.

**Screenshots**
None available

**Kodi Version (please complete the following information):**
 - Kodi Version:  18.9
 - Seren Version:  2.0.16

**Comment by Tikipeter** [comment]
Try turning OFF the language invoker in Seren and see if it fixes the issue.
It's normally the cause of this, especially when returning to the home screen after playback.

**Comment by nixgates** [comment]
@biscuitgod as tikipeter mentioned, this is the likely cause and until kodi resolve this on their end it's a unfortunate situation that affects some devices more than others.

@Tikipeter thanks for that!
