### ISSUE TITLE
[BUG] Error when trying to watch movies (ex. The Dark Knight)

### ISSUE THREAD

**Issue by Bulletbling** [nixgates/plugin.video.seren#485]
**Logs**

Https://paste.kodi.tv/azutajiseb

**Describe the bug**
Sometimes I get an error when trying to watch a movie and it doesn't get to the source search. 

**To Reproduce**
Click play on a movie and the error comes up and nothing happens. This just occurred with a very popular movie, "The Dark Knight". 

**Expected behavior**
Source search should start after clicking play movie and then I choose one to watch. 

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9 Leia
 - Seren version 2.0.16

**Comment by nixgates** [comment]
@Bulletbling could I ask you to clear your cache and try it again? Looks like an issue pulling information from Trakt.

**Comment by Bulletbling** [comment]
> @Bulletbling could I ask you to clear your cache and try it again? Looks like an issue pulling information from Trakt.
> 
> Edit: apologies, I did just have a thought on this. Could you open the trakt manager on the item and hit "Refresh Item Meta" and try again. This will clear the meta data for that item and rebuild it, hopefully that works to resolve this.
> 
> This should be resolved for the next update but hopefully this gets you around the issue while I clear up some more issues.

I’m unable to even open trakt manager on the item. This time “The Equalizer 2”.

Here’s another error log after I cleared cache, I then tried to play the movie, got an error, and then did what you said and tried opening trakt manager for the item and got another error. It won’t even open trakt manager on the movie.

https://paste.kodi.tv/arogaholim

**Comment by nixgates** [comment]
@Bulletbling shit, my apologies. I'd forgotten trakt manager uses the same endpoint of the database to gather information. 

I'll try look further into this. I might try and give you a custom version that will log out what's going on as I need to see a few things. Will let you know when I get some time :)

**Comment by Bulletbling** [comment]
> @Bulletbling shit, my apologies. I'd forgotten trakt manager uses the same endpoint of the database to gather information.
> 
> I'll try look further into this. I might try and give you a custom version that will log out what's going on as I need to see a few things. Will let you know when I get some time :)

I'll be ready to test for you when you are. 😀

**Comment by cr4m3r** [comment]
@nixgates I seem to be experiencing the same issue with two movies (both marked as watched). Clearing cache didn't solve it, and attempting to open the trakt manager on the item gives an error. 

[http://paste.kodi.tv/icanomuyuk](http://paste.kodi.tv/icanomuyuk)

update: Changing one of the movies to unwatched on trakt.tv and rebuilding the database removed the error for that one. The other movie left as watched was still unplayable/trakt manager-able. Looked for other movies marked as watched and ran into the same issue on them as well. You may already know what's going to, but thought the info may be useful if not.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
