### ISSUE TITLE
[REQUEST] Auto create cache folder if its missing on launch

### ISSUE THREAD

**Issue by absintheboy** [nixgates/plugin.video.seren#488]
I've been having an issue when restoring my kodi setup from a backup.  On first launch of Kodi after restoring I get a Seren error warning of 'no module named cache' 

[Error from log here.](https://paste.kodi.tv/volegaloca.kodi)

This error is resolved by force updating Seren from the repo.  It seems openwizard isn't backing up cached files/folders, so the one from Seren is ignored when making a backup. Force updating is obviously creating the missing files and resolves the error. Is it possible to have Seren create the required folder and files if they're missing on launch?

**Comment by nixgates** [comment]
@absintheboy this is unfortunately not an issue of Seren but an issue with the backup addon you're using. The cache folder is actually the caching module for Seren and your backup addon isn't detecting that it's a python module and not a database. 

I'll rename this module to hopefully combat this and should be available next update.

**Comment by LoganWolverineX** [comment]
@absintheboy i found a workaround for this. Use the EZ Maintenance+ Backup tool. It’s in the same repo as realizer and premiumizer. EZ backs up structure is exactly like how openwizard does it but does a complete ZIP. I think openwizard has some logic to exclude certain files. Once You have the ZIP backup created by EZ, you can still use openwizard to restore and you won’t have that issue where you have to reinstall seren from the repo.  Give that a try.

**Comment by nixgates** [comment]
@LoganWolverineX sounds about right if the EZ maintenance tools isn't filtering or is filtering correctly.

**Comment by nixgates** [comment]
Should also be noted, re-installing Seren over the top of the current install should fix the issue as a temp workaround.

**Comment by LoganWolverineX** [comment]
@nixgates thats right. From my testing, EZ isn’t filtering anything out whereas I think openwizard does. And yep, before I found this backup workaround, installing seren over the top was the temp workaround :).

**Comment by absintheboy** [comment]
Much appreciated @nixgates. Thanks for the quick response and a massive thank you for all the work you do for the community. Seren is hands down the best addon I've used in 10+ years of kodi tinkering.

And @LoganWolverineX, I appreciate the workaround, good call. 🤘

**Comment by JayDee696969** [comment]
Why not just back it up the right way by simply zipping up the addons and userdata folder in Kodi directory. Then you wouldnt have to rely on another addon that decides what to backup?

**Comment by LoganWolverineX** [comment]
> Why not just back it up the right way by simply zipping up the addons and userdata folder in Kodi directory. Then you wouldnt have to rely on another addon that decides what to backup?

Because these wizards have multi threads going to zip and unzip the backups to speed up the process. If you’re simply just zipping or unzipping them, it works too but it’s slower because it is single threaded. Also, the restore button for openwizard, has a process to delete before it restores via front end UI. So it’s doesn’t require much backend mucking around.

But, youre right, you can simply just zip and unzip backups and restores. Basically, it’s a user’s preference of workflow how they want to backup and/or restore.

**Comment by drinfernoo** [comment]
This was an issue with previous versions of OpenWizard, but should be fixed now.
