### ISSUE TITLE
Movie Ratings not showing (TV show ratings are showing though)

### ISSUE THREAD

**Issue by tsteven9** [nixgates/plugin.video.seren#49]
Ratings such as PG, PG-13, R etc. are not showing in the **Movies (Discover Movies)** section but are working fine in the **TV Shows (Discover TV Shows)** section. Would be great if it can be fixed. Thanks

**Comment by nixgates** [comment]
Thanks for pointing this out, this has been added in and will be released with next update.

**Comment by tsteven9** [comment]
You're awesome! Thank you so much :)
