### ISSUE TITLE
[REQUEST] Context Menu : Go back to root section

### ISSUE THREAD

**Issue by JacopoV** [nixgates/plugin.video.seren#491]
**Is your feature request related to a problem? Please describe.**
If navigating thru lots of pages, to get back to the root menu it takes a bit, and you have to to go back thru each page, one by one. 
Imagine you're in Movies > Popular at page 12... to go back to the section Movies you have to press several times back, passing thru all pages (unless you build a shortcut).

**Describe the solution you'd like**
In the context menu, it would be nice a shortcut "Go back to Movies", from any page.

**Describe alternatives you've considered**
Atm i've a shortcut which brings me to Kodi home and another one to open Seren. 

Thanks for your time.

**Comment by drinfernoo** [comment]
Press `Esc` or long press your "back" button.

**Comment by JacopoV** [comment]
Well, I tried long press on Android TV and goes back to home. But if you open seren section where you used to be, goes back to the page you left, not at the beginning.

**Comment by drinfernoo** [comment]
That's something Kodi just does... not sure if an add-on even can control that behavior.

**Comment by JacopoV** [comment]
Elementum context menu does that ( it has been added few weeks ago)

**Comment by nixgates** [comment]
@drinfernoo I believe what he's after is a shortcut option to be added the context menu addon. 

@JacopoV might I suggest looking at the super fav's addon? It's built to do exactly this sort of thing. If it doesn't suit your needs let me know and I'll re-open this issue.

**Comment by JacopoV** [comment]
Thanks @nixgates , i ll look into :)
