### ISSUE TITLE
[BUG] script.module.idna version 2.6 error when downloading Seren 

### ISSUE THREAD

**Issue by IG2022** [nixgates/plugin.video.seren#492]
**Describe the bug**
Unable to install Seren from Nixgates repository. When trying to Install an error message comes up saying script.module.idna version 2.6 could not be satisfied. 

**To Reproduce**
1. Install Nixgates repo from zip 
2. Go to repository and download the seren video addon 
3. Attempt to download seren addon 

**Expected behavior**
The Seren addon should be downloaded from the Nixgates repo.

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren Version 2.0.16

**Comment by cgtjr1** [comment]
I am having same issue. Doing fresh I stall of kodi and now I get that error on Seren and Venom.

**Comment by andyktaylor** [comment]
Same on Diggz repo

**Comment by QQQQQH** [comment]
I am having the same issue while trying to install Jellfin plugin for Kodi, so I think it might not be caused by Seren.

**Comment by Kalp3r** [comment]
Manual installation of [script.module.idna-2.8](https://mirrors.kodi.tv/addons/krypton/script.module.idna/) solved the issue for me.

**Comment by lukeharley92** [comment]
> Manual installation of [script.module.idna-2.8](https://mirrors.kodi.tv/addons/krypton/script.module.idna/) solved the issue for me.

Hi How do you manually install the module?

**Comment by cgtjr1** [comment]
> Manual installation of [script.module.idna-2.8](https://mirrors.kodi.tv/addons/krypton/script.module.idna/) solved the issue for me.

Yea. How do you do that. I tried and it says not available. I can manual select other dependencies

**Comment by Kalp3r** [comment]
> 
> 
> > Manual installation of [script.module.idna-2.8](https://mirrors.kodi.tv/addons/krypton/script.module.idna/) solved the issue for me.
> 
> Hi How do you manually install the module?

Save the zip file on a USB stick and install it as add-on from zip file via [Add-on manager](https://kodi.wiki/view/Add-on_manager).

**Comment by lukeharley92** [comment]
> > > Manual installation of [script.module.idna-2.8](https://mirrors.kodi.tv/addons/krypton/script.module.idna/) solved the issue for me.
> > 
> > 
> > Hi How do you manually install the module?
> 
> Save the zip file on a USB stick and install it as add-on from zip file via [Add-on manager](https://kodi.wiki/view/Add-on_manager).

Ah, what about if you are doing it on a device that you cannot plug a usb stick into?

**Comment by Kalp3r** [comment]
> 
> 
> > > > Manual installation of [script.module.idna-2.8](https://mirrors.kodi.tv/addons/krypton/script.module.idna/) solved the issue for me.
> > > 
> > > 
> > > Hi How do you manually install the module?
> > 
> > 
> > Save the zip file on a USB stick and install it as add-on from zip file via [Add-on manager](https://kodi.wiki/view/Add-on_manager).
> 
> Ah, what about if you are doing it on a device that you cannot plug a usb stick into?

I woulike like to help, however I do not know the possibilities of the device you use. Sorry.

**Comment by cgtjr1** [comment]
> > > > Manual installation of [script.module.idna-2.8](https://mirrors.kodi.tv/addons/krypton/script.module.idna/) solved the issue for me.
> > > 
> > > 
> > > Hi How do you manually install the module?
> > 
> > 
> > Save the zip file on a USB stick and install it as add-on from zip file via [Add-on manager](https://kodi.wiki/view/Add-on_manager).
> 
> Ah, what about if you are doing it on a device that you cannot plug a usb stick into?

I'm on Xbox series X. I couldn't do it that way. But I did fix it by downloading another repo that had it. As soon as I downloaded it. I went back and Seren installed immediately. See video. 

https://youtu.be/SOhXemFehok

**Comment by IG2022** [comment]
> > > > > Manual installation of [script.module.idna-2.8](https://mirrors.kodi.tv/addons/krypton/script.module.idna/) solved the issue for me.
> > > > 
> > > > 
> > > > Hi How do you manually install the module?
> > > 
> > > 
> > > Save the zip file on a USB stick and install it as add-on from zip file via [Add-on manager](https://kodi.wiki/view/Add-on_manager).
> > 
> > 
> > Ah, what about if you are doing it on a device that you cannot plug a usb stick into?
> 
> I'm on Xbox series X. I couldn't do it that way. But I did fix it by downloading another repo that had it. As soon as I downloaded it. I went back and Seren installed immediately. See video.
> 
> https://youtu.be/SOhXemFehok

Thanks for this! I'll give it a try.

**Comment by muttznutz1960** [comment]
**FireStick resolve:**
Manual install of script.module.idna-2.8 
Run Downloader and enter the following:
https://mirrors.kodi.tv/addons/krypton/script.module.idna/script.module.idna-2.8.zip
Go back into Kodi 
Install from Zip File
External Storage
Downloader
Select "script.module.idna-2.8.zip"

Seren installs!

**Comment by Pwoodlock** [comment]
Thanks @Kalp3r , installing the new version through the Addon Manager fixed the issue for me.

**Comment by drinfernoo** [comment]
This is an issue with GitHub and/or the main Kodi repository.
