### ISSUE TITLE
[REQUEST]IMDb authentication via cookie to access IMDb Watchlist, Lists

### ISSUE THREAD

**Issue by onlytanmoy** [nixgates/plugin.video.seren#494]
Hiya @nixgates trust all fine at your end :)

Please include a section in Seren 2.0 to access IMDb Watchlist, Lists.
Authentication via cookie for IMDb is possible as already implemented in a4kStreaming add-on. So, I would love to see the same in my favourite Seren.

_IMDb Authentication_
The IMDb authentication token is the value of a cookie named at-main.
It can be obtained by opening imdb.com in a browser, log in, then get it from:

(Chrome/Edge) DevTools > Application > Cookies
(Safari/Firefox) DevTools > Storage > Cookies

**Comment by RvV1979** [comment]
Yes please. Having access to imdb watch list would be a great improvement!

**Comment by onlytanmoy** [comment]
@nixgates commenting to keep this issue alive lest the stale bot closes it.
