### ISSUE TITLE
[REQUEST]  Host trakt sync database in mysql

### ISSUE THREAD

**Issue by gwilly7** [nixgates/plugin.video.seren#495]
Would be super nice to have the option to have your trakt sync database on a mysql server to help keep all installations in your house synced together better.

**Comment by nixgates** [comment]
@gwilly7 this was something I've considered for the future and good to see someone else is interested in it! 

Once there's a bit more free time I'll invest more time into looking at it!

**Comment by gwilly7** [comment]
Awesome thank you again for all that you do. I would be more than happy to help test when you are ready. I already have MySQL server set up.

**Comment by Daviddew89** [comment]
I second this. Just moved over to MySQL for my household. Having Seren using a central database will remove so much overhead between devices. Will also be available for testing if needed.

**Comment by Onkruid71** [comment]
I would love to have a MySQL option in Seren, got more devices.
