### ISSUE TITLE
Unable to scrape certain shows [BUG]

### ISSUE THREAD

**Issue by newbyp** [nixgates/plugin.video.seren#496]
**Logs**

Please provide debug logs to assist with your issue

**Describe the bug**

I am using Seren on Kodi 18.9 on a firestick. I am trying to watch a certain tv show but find that it either comes back with no playable sources or very minimal sources across many episodes. Other shows work fine but this one show doesn't. I've tried Exodus Redux as well and this does find plenty of playable sources. I much prefer Seren and wondered if this can be fixed. 

https://paste.kodi.tv/ivogakoyuc.kodi

**To Reproduce**
1. Go to next up
2. Click on the latest Law and order Special victims unit episode
3. Scroll down to 
4. See error no playable sources

**Expected behavior**
A list of playable sources similar to Exodus Redux

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by nixgates** [comment]
@newbyp this look to be more of an issue with the providers. It would be best to try and get in touch with them and work through that as from a Seren perspective, everything is working as intended.

Sorry I couldn't be of more help here
