### ISSUE TITLE
MetalliQ/Chappa'ai Player

### ISSUE THREAD

**Issue by VenomousRage** [nixgates/plugin.video.seren#5]
Is there currently a player for MetalliQ/Chappa'ai? If not, is there any plans to implement one?

**Comment by SerpentDrago** [comment]
I also would love to have a player , I have tried to make one but was unable

**Comment by drinfernoo** [comment]
> Is there currently a player for MetalliQ/Chappa'ai? If not, is there any plans to implement one?

That is out of the scope of this project. MetalliQ and Chappa'ai are both abandoned projects. Obviously players are able to be created still, but @nixgates has no affiliation with them, and thus no obligation to do so.

**Comment by SerpentDrago** [comment]
this may work , NOT my work , and untested > 

https://github.com/vitorp07/players

**Comment by VenomousRage** [comment]
> this may work , NOT my work , and untested >
> 
> https://github.com/vitorp07/players

I tried that, @SerpentDrago , but couldn't get it to populate on the list. Thanks for the thought, though.

**Comment by SerpentDrago** [comment]
we are working on it will post results another time

**Comment by VenomousRage** [comment]
Awesome. Thanks for the heads up, as well as the consideration.

**Comment by SerpentDrago** [comment]
THIS IS JUST a test , please don't give this out or expect it to always work , use this as your player zip url 

https://github.com/SerpentDrago/deepthoughtplayers

**Comment by SerpentDrago** [comment]
Please close this thread , and feel free to open a new one on that repo though

**Comment by VenomousRage** [comment]
Awesome, thanks, thanks, and will do.

**Comment by vitorp07** [comment]
@VenomousRage @SerpentDrago 
The player do work perfectly but not with MetalliQ, Chappa'ai... because their configuration is different than the one I use version.
If you tell me which fork you are using I might be able to help you, also provide which version of Seren you have installed since the addon id changed to lowercase ```plugin.video.seren``` as opposed to ```plugin.video.Seren``` in the master repo.

**Comment by VenomousRage** [comment]
> @VenomousRage @SerpentDrago
> The player do work perfectly but not with MetalliQ, Chappa'ai... because their configuration is different than the version I use.
> If you tell me which fork you are using I might be able to help you, also provide which version of Seren you have installed since the addon id changed to lowercase `plugin.video.seren` in the master repo as opposed to `plugin.video.Seren` in nixgates repo.

I've pulled the master repo and have used the updated version, as it has yet to be pushed to the nixgates repo. I'm currently using Chappa'ai,. The info that @SerpentDrago provided solved my issue, as soon as I pulled the most up to date version of the addon. Thanks for the though, though.

**Comment by VenomousRage** [comment]
> @VenomousRage just be careful, the current GitHub master branch has some bugs with Trakt that have been fixed in 0.1.12.
> 
> I haven't pushed that to the git yet. Sorry about that!

Good to know @nixgates . I expected some bugs, given the straight up disclaimer that you put in the addon itself. :P Luckily for me, I haven't experienced any issues at all.

No need to apologize, I'm the one messing around with a beta version. Keep up the good work!

**Comment by SerpentDrago** [comment]
@vitorp07  Thank you for the player url , @drinfernoo took it and updated our players on our metalliq fork . We tried for weeks  !!  

Only thing that doesn't work is poster / fanart . Everything else is working perfectly . All meta data shows !

**Comment by vitorp07** [comment]
@SerpentDrago 
All Metadata, plot ,tagline, genres, poster ,fanart...(even the fanart background during Seren's scraping) are working here, you will need to update your fork for it work properly,
Check the debug log after selecting Seren from your fork it will show you exactly why you don't get poster/fanart.

**Comment by drinfernoo** [comment]
We were unable to get the artwork to work for TV shows @vitorp07... do you know what change needs to be made in our fork to pass that information correctly?

**Comment by drinfernoo** [comment]
yeah

**Comment by drinfernoo** [comment]
@vitorp07 Yep, that's the one!

**Comment by vitorp07** [comment]
@drinfernoo Done.
