### ISSUE TITLE
Error in log : nextup & tvshow list 

### ISSUE THREAD

**Issue by kbxy88** [nixgates/plugin.video.seren#50]
I keep getting Seren error and I made sure my Trakt was active in settings. Can’t tell if this is on my end?
http://paste.kodi.tv/tavufiliye

**Comment by abbaskip** [comment]
I'm getting errors from Next Up in Seren now too. Collection seems to be working, so I don't believe it's a Trakt issue (and I reauthorised in any case).

I'll add a log later.

**Comment by kbxy88** [comment]
I dunno, even my trakt progress isn’t updating in Seren.

**Comment by nixgates** [comment]
Looks like trakt didn't send anything to your device, try clearing your cache and opening it again.

Let me know how you go.

**Comment by kbxy88** [comment]
Looks to be up and running again. Closing
