### ISSUE TITLE
Errors playing back episodes

### ISSUE THREAD

**Issue by jonaravelo** [nixgates/plugin.video.seren#51]
Hey not sure if here is the right place, but some shows I have tried to play completely do not work on Seren. Law and Order: Special Victims Unit Season 20, from episode 14 onwards.

Seren doesn't find a lot of links, but the ones it does do not play back. On other addons (13Clowns) it finds them and can play them back, although it crashes for some reason after a few minutes playing.

websites like 123moviesnet.org work fine no issues. 

Let me know if this is a bug or if it can be fixed from my end.

Thanks

**Comment by nixgates** [comment]
Apologies, this looks to be a scraper issue.

Just to confirm, you have setup your debrid providers in the settings?

**Comment by nixgates** [comment]
Closing issue due to lack of information, if you would like to re-open the issue let me know
