### ISSUE TITLE
[BUG] mark progress and episodes as watched in library when watched in Seren 

### ISSUE THREAD

**Issue by unkn0wn234** [nixgates/plugin.video.seren#510]
**Logs**
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/5919015/kodi.log)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (in my case specifically, am not sure if this would still happen but probalby would if u had a physical library file, then played with Seren through TMDBHelper context menu, though not sure why youd need to in that case)
1. Integrate local library of .strm files with TMDBHelper
2. Set Seren as default player for TMDBH, or use select player in the context menu
3. Skip through to leave progress, then back out
4. No playback progress is saved (though it is saved to Trakt/in Seren so it will resume on clicking it)

**Expected behavior**
If this isn't a bug then I guess its more of a feature request, Fen currently does this, when watching a local library file through Seren, it clearly can save playback progress, would it be possible to make it so Seren passes that back to Kodi to save in the library as well?

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Latest Seren through Repo

**Comment by nixgates** [comment]
I'm unsure how this will go, Seren gets its resume points from Trakt. My main concern is multiple addons all trying to store down Trakt resume points to local library items. 

Does the Trakt addon not support such a feature?

@unkn0wn234

**Comment by unkn0wn234** [comment]
> I'm unsure how this will go, Seren gets its resume points from Trakt. My main concern is multiple addons all trying to store down Trakt resume points to local library items.
> 
> Does the Trakt addon not support such a feature?
> 
> @unkn0wn234

Sorry sync wasn’t the right word, just mark in library when watched in Seren. Doesn’t have to change how it resumes it should still resume from trakt, I would just liie the episodes in my library to be marked as watched or progress marked, Fen currently does this. 

I can use trakt to update it but with a large library it takes a short while to update and I think it would just be better to let Seren leave a resume point and mark as watched in the library when watched in srren. Even if it doesn’t resume from the progress point it’d just be a visual thing for me personally. If the progress point can’t be marked in the library, atleast episodes marked as watched would be nice.

**Comment by JayDee696969** [comment]
Isnt this the function of the Kodi Trakt addon already?

**Comment by unkn0wn234** [comment]
The request im asking for is to just mark it in the library right after playback finishes like what Fen currently does. I do use the Trakt addon but 1-with the amount of shows and movies I have in my library it takes 2 minutes to do a sync. which isnt a big deal but 2- im only asking cause another addon has showed that it is possible

**Comment by drinfernoo** [comment]
The Trakt add-on handles this.
