### ISSUE TITLE
[REQUEST]  Don't know how to name this and not to be wrongly taken

### ISSUE THREAD

**Issue by nix87** [nixgates/plugin.video.seren#511]
Hi. 
First of all I must say this isn't request at first place and it's not my intention to push anything nor I give rights to myself for that. I even don't need reply on this . Just wanted to say I'm willing to offer to borrow premiumim Easynews account if needed when comes time for making integration between Seren and Easynews. If needed feel free to contact me whenever you want. 

I am not sure if there is just need for a seperate provider for that or there is something which should be done is Seren also so I don't know if Nix needs access or guys who are behind A4K Scrapers or some third person? I am saying this here only cause I think this is the place where everyone who are involved in Seren addon comes here to check issues. 

Have a nice day all and take care of youself. Peace.

**Comment by nixgates** [comment]
Hey sorry, not to put a dampening on what you're after as it's outside of the Seren scope and more into the provider scope which I have no affiliation with. 

Apologies :)

**Comment by nix87** [comment]
Not a problem mate, I understaind everything ;)
