### ISSUE TITLE
[BUG] Premiumize Premium Status has Expired Won't Go Away

### ISSUE THREAD

**Issue by Bulletbling** [nixgates/plugin.video.seren#512]
**Logs**

Upon request. 

**Describe the bug**

The expiry notification works as described, however after expiration I get a pop-up quite often that the premium status has expired, even after I've disabled Premiumize and then I disabled the notification for expiry and it still shows up.

**To Reproduce**
Allow subscription to expire and show the notification. 

**Expected behavior**
Expiry notification should go away upon disabling the account that is expired, or after disabling expiry notifications in the settings.

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9 Leia Auramod
 - Version 2.0.16 latest as of 2/4/21

**Comment by nixgates** [comment]
Hey @Bulletbling can you make sure you have most definitely disabled Premiumize in the account settings?

In the accounts settings, under Premiumize label, you will see the setting "Enabled Premiumize". If you wouldn't mind double checking that's not ticked. When premiumize is disabled, you shouldn't see any other settings for it in that section.

**Comment by Bulletbling** [comment]
I can confirm it is indeed disabled. Would you like a log? Didn't know if it was needed for this or not.

**Comment by Bulletbling** [comment]
> Hey @Bulletbling can you make sure you have most definitely disabled Premiumize in the account settings?
> 
> In the accounts settings, under Premiumize label, you will see the setting "Enabled Premiumize". If you wouldn't mind double checking that's not ticked. When premiumize is disabled, you shouldn't see any other settings for it in that section.

I can confirm it is indeed disabled. Would you like a log? Didn't know if it was needed for this or not.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
