### ISSUE TITLE
[BUG] Some AllDebrid sources appear when using other debrid

### ISSUE THREAD

**Issue by cgcgcgcgcg** [nixgates/plugin.video.seren#517]
2-3 people using Real Debrid and Premiumize noticed AllDebrid sources while scanning.
The easy solution is to disable AllDebrid from Seren's settings.
The weird part is some AllDebrid sources work, I guess AllDebrid has a few free sources that perhaps don't need credentials.

**Comment by drinfernoo** [comment]
Weird. Doesn't seem like an issue, though.
