### ISSUE TITLE
[BUG] Seren Fails to Resolve any RD Sources

### ISSUE THREAD

**Issue by drail99** [nixgates/plugin.video.seren#518]
**Logs**

https://pastebin.com/raw/7MbqZEPf

**Describe the bug**

Seren finds sources but fails to resolve them. It scrolls through all sources then returns "no playable sources found."
The sources are successfully added into the real-debrid cloud however and can be played in Seren later by going to the "My Files" section and accessing the real-debrid cloud.

**To Reproduce**

1. Select a Movie or Tv Show.
2. Find Sources
3. Select a Source

**Expected behavior**
It should play the file.

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 18.7 Git:20200612-e2aefdbee4 Running on Raspbian GNU/Linux 10 (buster), kernel: Linux ARM 32-bit version 4.19.97-v7+
 - Version 2.0.0.16

**Additional context**

**Comment by nixgates** [comment]
@drail99 there's two likely causes for this kind of issue, 

1. Can you double check your RD account status, make sure it's still active.
2. Also note that RD does not allow the use a VPN with their service.

If you're still having issues let me know!

**Comment by drail99** [comment]
Thank you.

1. Yes, it is active, in fact the files are added to my cloud. They can then be played from Seren by going to the RD Cloud section. Or on a computer from RD website.
2. Not using a VPN and RD works well from computer or other add ons.

**Comment by nixgates** [comment]
> Thank you.
> 
> 1. Yes, it is active, in fact the files are added to my cloud. They can then be played from Seren by going to the RD Cloud section. Or on a computer from RD website.
> 2. Not using a VPN and RD works well from computer or other add ons.

Hmm odd, ok I've got a small update due to help patch a lot of things ill add more logging for this section and see if we can't see what's happening.

Hold tight for me a bit :)

**Comment by serious96** [comment]
Hello, i got this problem too, Seren start cycling source even thought the source status is "local cache" but suddenly it play fine chosing another source, here is the log 
[https://paste.kodi.tv/initaxuson.kodi](https://paste.kodi.tv/initaxuson.kodi)

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.

**Comment by Corza626** [comment]
I'm having an issue with Seren, everything was working fine, I didn't touch anything then all of a sudden its telling me every time I click a source in source select.. " failed to resolve a playable file, would you like to select the file?"  and if I click yes an empty file selection box appears and just a cancel button on the right side.. Please can someone help me fix this with a step by step solve for this?!

**Comment by drinfernoo** [comment]
@Corza626 https://twitter.com/RealDebrid/status/1577205153458888704?s=20&t=aC3ptq1nc8POV8GxRtx6XQ

**Comment by LibertyLegion** [comment]
Hi. I can see that this bug is several years old but I've encountered the exact same problem as @Corsa626. The twitter link above doesn't open. Any chance you have a fix for this problem? Many thanks

**Comment by Grapeape516** [comment]
@LibertyLegion Real debrid twitter says they've had a lot of abusers and is now restricted to 250 searches per minute which I didn't think would effect normal users, It's broken both fen and Seren giving me the same error as you on links I was watching just yesterday:( I'll add another comment if I have any luck fixing mine

**Comment by Dazzxx** [comment]
Having the same problem with Seren. RD subscription paid. Scrapers removed and added again. Any help most welcome...

**Comment by Grapeape516** [comment]
@Dazzxx I've got mine working, but I had to uninstall Kodi and reinstall/authorise everything, Currently streaming the godfather 2 in perfect 4k :)

**Comment by stereoa** [comment]
Mine wasn't working earlier today but now is fixed

**Comment by stereoa** [comment]
> @Dazzxx I've got mine working, but I had to uninstall Kodi and reinstall/authorise everything, Currently streaming the godfather 2 in perfect 4k :) 

Mine wasn't working earlier today but now is fixed, without reinstalling

**Comment by cgwprs** [comment]
I haven't been watching anything today but yesterday Real-Debrid was down for maintenance. The Umbrella addon pushed the notification. Not sure when it came back up because I also use All-Debrid. Also, I have noticed that some DNS providers will not resolve debrid services. OpenDNS has worked the best for me but I am open to suggestions.

**Comment by Dazzxx** [comment]
> @Dazzxx I've got mine working, but I had to uninstall Kodi and reinstall/authorise everything, Currently streaming the godfather 2 in perfect 4k :)

Hi, mine is st started working so maybe RD was down. All is well in the world :) 
Thanks to everyone for all their replies!!!

**Comment by LibertyLegion** [comment]
Morning. Everything is as it should be this morning. Thanks for everyone's replies. Fingers crossed was just a RD glitch
