### ISSUE TITLE
Similar to #485 - certain shows fail to scrape/error out.

### ISSUE THREAD

**Issue by hindsight2021** [nixgates/plugin.video.seren#519]
I'm noticing a few odd behaviors in 2.0.16 - certain shows straight up fail to scrape, ends with an error (Seren error, see the logs) - similar to what they outline in issue #485 but with TV shows.

I've noticed this on SNL - last Saturday's episode (46/11), it will not populate in my next up, watchlist, as if it never aired, manually finding it in search and accessing results in error.

I can play it fine with other addons, not sure - log attached.

Same behavior in using TMDBHelper players, minus the crew.

[NShield_log_snip.txt](https://github.com/nixgates/plugin.video.seren/files/5946893/NShield_log_snip.txt)

**Comment by nixgates** [comment]
@hindsight2021 I can only see attempts from TMDBHelper in that log, can you try and see if it fails when attempting to play directly from within Seren for me?

**Comment by hindsight2021** [comment]
I would love to, but the 46th season of SNL is missing this episode in Seren when searching manually, it ends on the 2nd most recent episode (10th) so the issue does seem to resolve around Seren.

if you have something else I can test there, let me know!

**Comment by hindsight2021** [comment]
Rebuilt database again, seemed to work.
