### ISSUE TITLE
Landscape artwork issue after Update to 0.1.34

### ISSUE THREAD

**Issue by icpryde** [nixgates/plugin.video.seren#52]
So the lanscape artwork was working great before, it would show a screenshot from the episode but after the new update for .34 the artwork now shows a cut off version of the tv show poster.

Example before update:

https://i.imgur.com/56U2l5w.jpg

After update:

https://i.imgur.com/Bjhfm5P.jpg

Further if I check off "prefer fanart for landscape widgets"

I get this which is better but not the same screenshots from before

https://i.imgur.com/lsZ72Fi.jpg

Also noticed when I go into episode lists where normally i would see the screenshot for every episode it now just shows the poster, even if i change the view mode its always the same poster image.

Heres my logfile:
http://paste.kodi.tv/qozilutaxo

**Comment by mophawka** [comment]
Confirm having same issue after update on 4 different devices. After .34 update Episode artwork no longer populates

**Comment by nixgates** [comment]
I'll have a quick digg, I've probably broke something with the fanart update.

Give me a bit, I'm gonna roll out a small update within the next 24 hours to bump a few small changes, I'll try roll the fix into that.

**Comment by mophawka** [comment]
there you go! giving out ETAs again lol

**Comment by nixgates** [comment]
Haha but I really mean it this time!

Ok new process is ready to go for 0.1.35

Episode thumbnail is now set again (apparently I botched that), if it's not available, Seren substitutes the fanart so now there shouldn't be blank widget items in skins if they are shown as landscape.

Episode landscape art is now set the final value of episode thumbnail

**Comment by icpryde** [comment]
I can confirm landscape artwork is working properly now!

thank you @nixgates

**Comment by lukehansford** [comment]
Still getting this https://ibb.co/17Zs1w0
