### ISSUE TITLE
[BUG] Finish Watching doesn't show movie upon crash

### ISSUE THREAD

**Issue by Bulletbling** [nixgates/plugin.video.seren#520]
Because kodi seems to love to crash all the time (at least once or twice a day for me regardless of what I'm doing with Auramod on an Nvidia Shield), if I choose a movie from finish watching, Seren removes it from the finish watching list. Then I'll be watching the movie or trying to start the movie and Kodi will crash (kodi issues...not Seren) and when I restart kodi, the movie I was trying to watch is no longer in the finish watching list. 

It seems Seren is programmed to remove the movie and assumes that the movie will either be stopped by the user so that it can be re-scrobbled or if over a certain watched percent, do nothing since Seren has already removed it from the list once you clicked on play from finish watching. 

What's weird is that when I manually search for the movie in Seren, it won't show that it's in progress in the Auramod menu or on the poster, but when I click play, Seren will ask me via the context menu popup to resume from the point where I left off or "play from beginning" . 

Venom add-on is the one reliable one I've seen here as it doesn't remove the movie from the finish watching list until the movie is actually finished / over "x" percent. If the movie isn't finished, it then re-scrobbles, but the movie is always in finish watching until there's reason to remove it.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
