### ISSUE TITLE
[BUG] TMDb Metadata Location sending request for Original Titles instead of General Title

### ISSUE THREAD

**Issue by Nuklear92** [nixgates/plugin.video.seren#521]
**Share log file if possible**
[Kodi.Log](https://github.com/nixgates/plugin.video.seren/files/5972556/kodi.txt)

**Attention!** Before checking out log file, please read into the whole issue and check screenshots shared below to have a better idea and understanding of what this is about. Finally, check out Kodi log and see Seren sending "Original Language Title" search query being sent before scrapping begins instead of General Title when using TMDb Meta Location.

**Describe the bug**
When using default Medatada Location: TMDb. There seems to be an issue when scrapping movie titles, specially those that have a General and a "Original Title" from based on the official language or country they were filmed and produced. It's affecting mostly International films, decreasing and sometimes even failing all together to return results from torrent sources.

**To Reproduce**
1. Go to 'Any Movie from the screenshots I'll provide below'
2. Click on 'To scrape make sure you're using the default Metadata Location which is TMDb.'
3. See Results.
4. Repeat Step 2, this time before scraping the title make sure to go into Seren Settings>Interface>Metadata Location change from default TMDb to Trakt. Now, clean your Local Torrent Info cache and Re-Scrape Item.
5. See Results. 

**Expected behavior**
After doing Step 2 and then 4 you should see first hand how Metadata Location on Trakt is correctly calling for General Title instead of "Original Title" which TMDb is doing.

**Screenshots**
![Kodi_20210209_195207](https://user-images.githubusercontent.com/76958541/107463639-8d66f500-6b2c-11eb-9333-bdab564f815e.png)
![Kodi_20210209_193715](https://user-images.githubusercontent.com/76958541/107463678-a66fa600-6b2c-11eb-8f88-9b2ea20a10dd.png)
![IMG_6801](https://user-images.githubusercontent.com/76958541/107463693-ac658700-6b2c-11eb-9ad2-bccb1927a0b2.jpeg)
![Kodi_20210209_193850](https://user-images.githubusercontent.com/76958541/107463731-be472a00-6b2c-11eb-977a-c2a3a39ebd78.png)
![IMG_6802](https://user-images.githubusercontent.com/76958541/107463744-c43d0b00-6b2c-11eb-8e5d-1fe4dc97e88b.jpeg)
![Kodi_20210209_221225](https://user-images.githubusercontent.com/76958541/107464060-74127880-6b2d-11eb-85cc-0cdce09514b8.png)
![Kodi_20210209_221238](https://user-images.githubusercontent.com/76958541/107464067-77a5ff80-6b2d-11eb-9cd3-fac875572d3d.png)
<img width="1352" alt="Screen Shot 2021-02-09 at 11 19 59 PM" src="https://user-images.githubusercontent.com/76958541/107464608-ab355980-6b2e-11eb-8f58-0e76ca100f42.png">
![Kodi_20210209_222715](https://user-images.githubusercontent.com/76958541/107464676-d1f39000-6b2e-11eb-8331-8e9db8abe8db.png)
<img width="1074" alt="Screen Shot 2021-02-09 at 11 32 23 PM" src="https://user-images.githubusercontent.com/76958541/107464993-5c3bf400-6b2f-11eb-905d-6319093bfbe8.png">
![Kodi_20210209_222928](https://user-images.githubusercontent.com/76958541/107465060-842b5780-6b2f-11eb-9c2b-1ed54e1f567e.png)
<img width="1074" alt="Screen Shot 2021-02-09 at 11 36 22 PM" src="https://user-images.githubusercontent.com/76958541/107465163-c5bc0280-6b2f-11eb-90fb-678399ba0bdd.png">

### **Now Here are the correct results from General Titles using Location Metadata: Trakt**

![Kodi_20210209_194032](https://user-images.githubusercontent.com/76958541/107465322-277c6c80-6b30-11eb-9026-3eeea4e3b188.png)
![Kodi_20210209_194141](https://user-images.githubusercontent.com/76958541/107465348-2ea37a80-6b30-11eb-814d-0f49c1cf2417.png)
![Kodi_20210209_194234](https://user-images.githubusercontent.com/76958541/107465373-35ca8880-6b30-11eb-8a18-f36cdf5e5d25.png)
![Kodi_20210209_221338](https://user-images.githubusercontent.com/76958541/107465386-3d8a2d00-6b30-11eb-84b2-b6e89576c46b.png)
![Kodi_20210209_222812](https://user-images.githubusercontent.com/76958541/107465403-4549d180-6b30-11eb-9015-ad4916e28b39.png)
![Kodi_20210209_223019](https://user-images.githubusercontent.com/76958541/107465411-4b3fb280-6b30-11eb-8534-a1e298f26b37.png)

**Kodi Version (please complete the following information):**
 - Kodi Version [18.9]

**Hardware Device & Seren Build**
-Nvidia Shield TV Pro 2019
-Seren: 2.0.16, A4kScrapers Build: 2.51.0 Latest.

**Additional context**
So, I believe that the fix would be making TMDb Location Metadata to send request when scrapping begins in Movies for General Titles, instead of Original Titles which most of the time will bring out this issue. On the other hand, as you know torrent sites rarely use Original Titles from International Films they use General Titles like every other film gathered from IMDb. As well as TMDb, Trakt, etc. Even if a movie has an original title, it will always use the general title to provide info. So, this definitely has to be some sort of mistake in the code when using TMDb for Location Metadata. 

We can't keep Location Metadata from Trakt all the time, because after a while Seren start sending notifications that Trakt is suppressing info because of their heavy api rate limit. So, a fix for the TMDb metadata location needs to happen to call for general titles instead when scrapping begins.

**Comment by nix87** [comment]
I'm not sure but I think my Seren search both original and english title.

**Comment by Nuklear92** [comment]
> I'm not sure but I think my Seren search both original and english title.

Mine doesn't when using Location Metadata from TMDb which is the default location. Also, A4kScrapers Dev tried reproducing the issue and he also got the same result as me. So, there's indeed an issue with it. If I change the metadata location to Trakt it does work as it should and titles are scraped based on their general title instead of original title which is always as a secondary option most of the time not really need it. Since, torrent sites name their links based of general always.

This issue is mainly plaguing international titles which normally have an Original name based on the country's origin language, but rarely ever used on most of the popular torrent sites.

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.18.

**Comment by Nuklear92** [comment]
> This should be fixed in 2.0.18.

Finally! Thanks for the update Doc 🙏
