### ISSUE TITLE
Question/Issue: Seren Trakt vs Trakt.Script Add-on

### ISSUE THREAD

**Issue by Dealz-416LS** [nixgates/plugin.video.seren#522]
I've had this issue (Seren Trakt vs Trakt.Script) since 2.0 launched and I've been having a separate issue where watched TV shows or movies will end up in 'Finish Watching' Trakt list even though the episode was Marked as Watched, occasionally reappearing even after I’ve removed it.

I think the issue might be because i have Scrobbling turned on for both Seren Trakt and Trakt.Script, a while back i read that it should be one or the other and not both.

["That setting is so you can choose whether to allow Seren to handle it or like in your instance, allow trakt to handle it. Youre correct in that only one should handle that"](https://www.reddit.com/r/Addons4Kodi/comments/kor8y7/seren_20_public_release/ght9jnb?utm_source=share&utm_medium=web2x&context=3)

The issue is that if i disable (uncheck) Scrobbling `Seren Settings > Accounts > Trakt > Enable Trakt Scrobbling` but have it enabled in Trakt.Script `Trakt Add-on Settings > Scrobbling > Scrobble TV show episode` nothing works.

Scrobbling (Check in) doesn't work so no ability to "Resume', Episodes doesn't get marked as watched and the Rating dialog box no longer works.

The Trakt.Script Add-on worked just fine with Scrobbling/Marking episodes as Watched before Seren 2.0 when Seren didn't have the ability to scrobble/mark as watched.

If i go the other way and let Seren handle it then the Trakt.Script Add-on no longer displays the Rating dialog box but the Scrobbling/Marked as watched works.

Has anyone got Trakt.Script Add-on managing the Scrobbling/Marked as Watched with Scrobbling disabled in Seren?

**Comment by tundrablasen** [comment]
Good question. I would also want to know what Trakt I should use. Seren or the Trakt addon for Kodi.

i noticed that Seren Trakt I’d not scrobbeling when using the „my files“ tab in Seren. The Trakt addon itself is scrobbeling when using the my files in Seren (if I remember correctly)

**Comment by jweinr** [comment]
Hi, I tested this while reporting in issue #379.
My findings:
Seren own trakt scroble works fine.
Trakt add-on scroble works on other players except seren.

Since I only use seren, I just disabled trakt add-on scroble, and use the add-on for widgets and library integration.
And let seren do it's own scroble which so far has worked great for me.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
