### ISSUE TITLE
[BUG] Cloud Inspection Not Working properly for Seren 2.0.16

### ISSUE THREAD

**Issue by tundrablasen** [nixgates/plugin.video.seren#523]
I found another bug, which seems **not** to be related to YEAR Date in the filename. But maybe because its a Season Pack Torrent?
some similar bug ( #478 )  was reported as well. 

overall the cloud inspection is a hit and miss since Seren 2.0. before that i worked flawlessly as i remember. i hope this bug report helps to track the issue down. if further assitance is needed, im glad to help

**Cloud Inspection is failing in the following case as well:**

MasterChef.US.S06.1080p.HULU.WEBRip.AAC2.0.x264-QOQ[rartv]

> magnet:?xt=urn:btih:36306290f8207366bc0370af2909c9080bda7135&dn=MasterChef.US.S06.1080p.HULU.WEBRip.AAC2.0.x264-QOQ%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2730&tr=udp%3A%2F%2F9.rarbg.to%3A2930

MasterChef.US.S07.1080p.HULU.WEBRip.AAC2.0.x264-QOQ[rartv]

> magnet:?xt=urn:btih:f1d80fe7186650762e947a785efca2696ffe8acf&dn=MasterChef.US.S07.1080p.HULU.WEBRip.AAC2.0.x264-QOQ%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2840&tr=udp%3A%2F%2F9.rarbg.to%3A2890

MasterChef.US.S08.1080p.HULU.WEBRip.AAC2.0.x264-AJP69[rartv]

> magnet:?xt=urn:btih:a2cfd41f755c26c2f12dc42960e5302c8d5d8f7e&dn=MasterChef.US.S08.1080p.HULU.WEBRip.AAC2.0.x264-AJP69%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2740&tr=udp%3A%2F%2F9.rarbg.to%3A2720

Masterchef.US.S09.720p.AMZN.WEBRip.DDP2.0.x264-NTb[rartv]

> magnet:?xt=urn:btih:0ffa167be8288b689507c4632965d3561e075203&dn=Masterchef.US.S09.720p.AMZN.WEBRip.DDP2.0.x264-NTb%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2820&tr=udp%3A%2F%2F9.rarbg.to%3A2880

MasterChef.US.S10.1080p.AMZN.WEBRip.DDP2.0.x264-AJP69[rartv]

> magnet:?xt=urn:btih:55d7ef507feaf56589b766bbe52496c33ac5dd11&dn=MasterChef.US.S10.1080p.AMZN.WEBRip.DDP2.0.x264-AJP69%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2730&tr=udp%3A%2F%2F9.rarbg.to%3A2720

Files are cached in the Premiumize Cloud, but when searching with Seren 2.0.16, cloud inspections fails

![2021-02-11 20_31_05-Premiumize me, All in One Cloud-Downloading - Brave](https://user-images.githubusercontent.com/46343142/107688626-25d5b480-6ca8-11eb-959c-8bff1e0a2b5b.png)

**To Reproduce**

1. Add magnet to PM and/or RD cloud. Magnet link is listed above.
2. search for the Masterchef US show
3. go to season and episodes
4. let seren scrape for providers and cloud inspection
5. see the first link, the source type is not CLOUD (since i cached it to PM cloud)

**Expected behavior**
The show that I cached in PM and RD should show up on top specified as CLOUD under cloud type.

Kodi Version (please complete the following information):

Kodi Version 18.9
Seren Version 2.0.16
Skin: Estuary Mod v2

**Comment by JacopoV** [comment]
@tundrablasen  it seems similar to the one i filed in here : https://github.com/nixgates/plugin.video.seren/issues/528

I assume the problem, at least in this case (like in mine with Your Honor) is the fact that between the show title and season+episode, there is that "US" . If you look at my ticket, it shared the same format for naming.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
