### ISSUE TITLE
[BUG] when stopping a currently playing episode and returning to home screen, source select keeps popping up

### ISSUE THREAD

**Issue by tundrablasen** [nixgates/plugin.video.seren#524]
**Describe the bug**
whenever i am starting an episode of a show and then stopping a currently playing episode and returning to home screen, the source select option keeps popping up on the screen. just multiple presses on the "return" key on my shield TV remote, lets the source select screen disapear. if i press return just once, the source select screen keeps popping up again. i need to really hammer it.

**To Reproduce**
1. play an episode
2. stop playback and return back to home screen
3. Source select keeps popping up

**Expected behavior**
once stopped playback, no source select should keep popping up repeatedly 

**Kodi Version (please complete the following information):**
 - Kodi Version: 18.9
 - Skin: Estuary Mod v2

**Comment by drinfernoo** [comment]
Please open a new issue with a debug log if this is still an issue.
