### ISSUE TITLE
[BUG] Can't Open Trakt Manager - Error

### ISSUE THREAD

**Issue by Bulletbling** [nixgates/plugin.video.seren#525]
**Logs**

Https://paste.ubuntu.com/p/Mkfczk6kVS/

**Describe the bug**
Fail to open trakt Manager in the context menu..

**To Reproduce**
1. I selected a tv episode of The Blacklist on a seren next up widget after I finished watching it with the Fen addon, went to trakt Manager, and marked as watched. I tried then to go to trakt Manager to clear scribble progress and got "Seren Error". 

**Expected behavior**
Trakt Manager opens

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren Version 2.0.16

**Additional context**
Not just a recent issue. Has happened before occasionally.

**Comment by tundrablasen** [comment]
So you Watch it with a different addon. Fen. Why do you post a bug report in seren?

**Comment by Bulletbling** [comment]
> So you Watch it with a different addon. Fen. Why do you post a bug report in seren?

Those were the steps I took prior to the bug occurring. I'm only referring to the Trakt options within the seren addon and serena context menu.

**Comment by drinfernoo** [comment]
The Seren error in your log indicates that Fen is not passing the proper IDs to Seren for Trakt Manager to work. While not "expected", the Seren context menu items are designed to work with Seren, not other add-ons.

Also, you have a **lot** of errors in your log from... something else 😅

**Comment by Bulletbling** [comment]
> The Seren error in your log indicates that Fen is not passing the proper IDs to Seren for Trakt Manager to work. While not "expected", the Seren context menu items are designed to work with Seren, not other add-ons.
> 
> Also, you have a **lot** of errors in your log from... something else 😅

I did see there were many errors as I quickly scrolled through to Seren, but didn't look at what it was since I have been trying out this Diggz Flix build for the past day or two. It does seem to crash several times a day and now I can't even play 4k content without it going back to the Nvidia Shield screen so I'm diagnosing that one at the moment. Might just be a build that's so custom it needs constant updating since the last update was a few months ago.

So bsically, if another Addon is used with Trakt, it may cause Seren to have issues is what it comes down to. That's unfortunate. Fen needs to get that fixed.

**Comment by drinfernoo** [comment]
@Bulletbling That's not at all what I said.

Seren's context menu add-on expects certain parameters to be passed, which Seren passes to it correctly. Fen is not designed to work with Seren's context menu, so it does not pass these parameters. This is not a bug of either add-on, but simply a difference in add-on design.

**Comment by Bulletbling** [comment]
> @Bulletbling That's not at all what I said.
> 
> Seren's context menu add-on expects certain parameters to be passed, which Seren passes to it correctly. Fen is not designed to work with Seren's context menu, so it does not pass these parameters. This is not a bug of either add-on, but simply a difference in add-on design.

I see this, but why can't I still use serens trakt Manager to mark a movie as watched for instance? It shouldn't have anything to do with Fen in theory since you're just passing info to Trakt servers that I would like to mark this item as watched. What Fen does shouldn't interfere with Seren saying to the Trakt server "hey, I'd like to mark this particular movie as watched". Instead it errors out. That's the part I don't understand...the reason why it doesn't just work that way.

**Comment by drinfernoo** [comment]
@Bulletbling But how does Seren know *what* thing you're trying to mark, if Fen doesn't tell it?

**Comment by Bulletbling** [comment]
> @Bulletbling But how does Seren know _what_ thing you're trying to mark, if Fen doesn't tell it?

Because I scrolled to the movie while in the seren addon and hit menu and went to the Trakt Manager within seren. Unrelated to Fen?

**Comment by drinfernoo** [comment]
Ah, then I've misunderstood the issue.

**Comment by Bulletbling** [comment]
> Ah, then I've misunderstood the issue.

Yeah, no worries. My explanation may not have been great to start with. I just wanted to include all available information (that I had played the movie in Fen prior, realized I saw the movie so exited out of fen, and then tried to go into seren to select the movie, do the context menu, and use the Trakt manager within Seren to mark as watched).

**Comment by drinfernoo** [comment]
Please open this again with a new log attached (follow the bug report template) if it is still an issue in 2.0.17.
