### ISSUE TITLE
[BUG] invalid Trakt Api keys error message even after re authorizing

### ISSUE THREAD

**Issue by kbxy88** [nixgates/plugin.video.seren#526]
**Logs**
Debug: https://paste.kodi.tv/zoqanuwale

**Describe the bug**
I keep getting the pop up “invalid trakt api keys, your authentication has been reset. Please re-authorize your trakt account”
I’ve tried:
reauthorizing 
Wipe add on data in seren and start fresh
Fresh install of seren as well as build 

it seems to keep popping up and I have to constantly authorize. 

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren 2.0.16
- Using a Shield
- build is made on a Mac and then I use open wizard to deploy my build to shield

**Comment by drinfernoo** [comment]
OpenWizard is known to break Seren 2.x installs, to an unrecoverable state.

Your best bet is to completely uninstall Seren, making sure to clear add-on data, and then reinstall it.

**Comment by drinfernoo** [comment]
OpenWizard is known to botch Seren 2.x backups, leading to an unrecoverable state.

If you're using your own Trakt API keys in your "build", I'd recommend *not* using those, after having uninstalled/wiped/reinstalled Seren. They should not be necessary, and if you *are* using them, are likely causing your issue.

**Comment by kbxy88** [comment]
I authorized trakt inside of seren only, didn’t physically add an api key anywhere

**Comment by drinfernoo** [comment]
This seems to be a problem with using OpenWizard to restore Trakt authorization in Seren. The latest versions of OpenWizard have a fix for this.
