### ISSUE TITLE
[BUG] Fail to Load Remux Movie American Psycho - Nvidia Shield 2019 via Seren

### ISSUE THREAD

**Issue by Bulletbling** [nixgates/plugin.video.seren#527]
**Logs**
Original log showed Seren errors prior to playing the movie, but I accidentally tried again and lost that log and this new log doesn't show Seren errors. Here's another one generated so I have a feeling it's not serens fault, and if so, I apologize as I've been trying to do as much bug adding as possible for you to make Seren as best as it can be and upload anything I find while using Seren.

https://gofile.io/d/YuZei3

**Describe the bug**
I clicked on the source to play it and Seren acts like it's loading it and then I get put straight back to the Nvidia shield home screen, where there's a little widget showing kodi playing a movie, but when I click it or Kodi, Kodi will restart and take me to my home screen.

**To Reproduce**
Seems to be happening with remux videos when attempting to play from seren source select screen. 

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9 AuraMod
 - Version 2.0.16

**Additional context**
I don't 100% believe this is a Seren issue, but did see several Seren errors in the log leading up to the crash upon playing the movie so I figured I'd log it here as a bug in case it's a Seren problem, but I just don't know. If it's not, I'm curious to know what the deal is. I have an Nvidia Shield 2019 and don't recall experiencing this on my Fire Stick 4K, but then again, I haven't opened remux movies on that as far as I remember. 

I have attached images of what happens when I get to the Nvidia Shield home screen.
![IMG_20210213_225943](https://user-images.githubusercontent.com/46613939/107868248-cebf1380-6e50-11eb-9e6a-d5939332bee6.jpg)
![IMG_20210213_230307](https://user-images.githubusercontent.com/46613939/107868249-d2529a80-6e50-11eb-815b-8e072ddc0a2c.jpg)

**Comment by djdirty60** [comment]
The problem is that you have too little ram, you have the 2gb ram version that I had too, with the 3gb ram the pro no more problems

**Comment by Bulletbling** [comment]
> The problem is that you have too little ram, you have the 2gb ram version that I had too, with the 3gb ram the pro no more problems

This confuses me since it shouldn't need more ram. Kodi will only fill up as much buffer as is designated in the advancedsettings. My fire stick 4k with 1.5GB ram was able to start playing remux 4k files without crashing (it might have to buffer though first) so why the Nvidia Shield crashes immediately is beyond me.
