### ISSUE TITLE
[BUG] Scraping seems not finding already cached data from RD  or not listing at all

### ISSUE THREAD

**Issue by JacopoV** [nixgates/plugin.video.seren#528]
**Logs**

http://paste.kodi.tv/rigicecidi

**Describe the bug**
I'm experiencing two issues here, very similar i suppose, or connected.

Some TV Shows seems not able to find the cached cloud data on RD account, so while scraping is not listing the content i was expecting to. 

But if i add a torrent via magnet on RD, the links are immediately available on RD, due the cached data i suppose, but only after this operation  i _might_ see some changes on the listed content on Seren. Some other time, in the same way, it's still not listed.

I assume the second one, could it be due naming.

Some examples of content already available on RD but **not** being listed on Seren even if i manually added the magnet on RD:

- Your.Honor.US.S01E10.2160p.SHO.WEBRip.DDP5.1.x265-NTb
- Altered.Carbon.S01.2160p.NF.WEBRip.x265.10bit.HDR.DDP5.1.Atmos-TrollUHD[rartv]

Some example of content already available on RD but listed on Seren **only** if i manually added the magnet on RD:
- The.OA.S01.2160p.NF.WEBRip.x265.10bit.HDR.DDP5.1-TrollUHD[rartv]

**To Reproduce**
1) Scrape for example either Your Honor or Altred Carbon to reproduce the issue of not being listed at all.
2) Then head to a tracker and find a magnet like the one reported
3) Paste in RD and observe links turn active, in RD, immediately
4) Rescrape the item with Seren and see that it's not showing up at all
5) In case in point 1) you picked other contect, like The OA reported, the content in point 4) will be visible only at that point (i guess Seren should have been able to find that automatically if the bug is different from Your Honor or Altered Carbon)

**Expected behavior**
Seren should find the cached content on RD without manually adding a magnet, showing the data is already being cached or available.

**Screenshots**
n/a

**Kodi Version (please complete the following information):**
 - Kodi Version : 18.9
 - Seren Version : 2.0.16

**Additional context**
I ve no pre emptive stop, no size limit on content and Rargb i used often is scraped correctly (finds other stuff).

**Comment by drinfernoo** [comment]
This should be resolved in 2.0.17.
