### ISSUE TITLE
[REQUEST] Enhance Cloud Inspection By Also Searching RD My Downloads/History

### ISSUE THREAD

**Issue by LoganWolverineX** [nixgates/plugin.video.seren#529]
**Is your feature request related to a problem? Please describe.**
Fen has the ability to scrap RD's "My Downloads/History" after a hoster is unlocked and after a link is resolved for streaming as part of their cloud inspection.

**Describe the solution you'd like**
This would be a great feature to add to Seren as part of the Cloud Inspection.   This would also allow users to have the ability to resume the same link they last resolved for streaming if they plan to resume a video.  Cloud inspection would first show RD's My Downloads/History items first on top, then RD/PM/AD cloud items next.  Everything scrapped below would show up like it does now.

Hope this is doable and if you need more details, let me know.

**Comment by LoganWolverineX** [comment]
Posting so the item doesn’t get auto closed

**Comment by LoganWolverineX** [comment]
keeping this active

**Comment by drinfernoo** [comment]
Seren already has a cloud scraper, which should be finding items in your debrid cloud. Is that different from what this is asking for?

**Comment by LoganWolverineX** [comment]
Yes, i'm suggesting the ability to scrape the RD history like Fen is able to do.  Example:  when you resolve and stream a video from RD, it will show up under RD history.  If you plan to resume later, and able to scrape the RD history, you can essentially attempt to resume and resolve the same link from your RD history.

**Comment by LoganWolverineX** [comment]
ping, so it doesn't close
