### ISSUE TITLE
[BUG] Lagging when playing Dolby Vision Content with Kodi 19 and RD

### ISSUE THREAD

**Issue by skfunghk** [nixgates/plugin.video.seren#531]
**Describe the bug**
When playing Dolby Vision content with KODI 19 and RD
The streaming will lagging even the file size only around 5.3Gb
It’s fine with playing HDR10 content even file size over 40Gb
So I assume that is not the networking issue

Kodi 19 Seren RD 
Cornet playing is atoms.dv size around 5.3G

**Comment by drinfernoo** [comment]
Can you attach a debug log?

**Comment by skfunghk** [comment]
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6028919/kodi.log)

**Comment by xyloab** [comment]
Dolby Vision 5 GB lol

I mean I know it is wrote like that but still... xD

**Comment by JacopoV** [comment]
I noticed a very similar issue to, with Wanda Vision.
Around 5gb file size.
After a minute or so, it starts having issues buffering.

Android TV 9, Seren 2.0.17, Kodi 19 Matrix

**Comment by drinfernoo** [comment]
This has nothing to do with Seren. Once Seren finds the file, passes it to Kodi, and Kodi starts playing it, Seren is no longer involved with *playback*. Lagging, buffering, and general performance issues **during playback** are issues to be attributed to either your network, device, or Kodi settings.

**Comment by JacopoV** [comment]
Ok @drinfernoo , i ll keep looking into. It's just weird that i've this issue only in this situation. 
Otherwise Kodi plays perfectly with files as big as 70gb, HDR/HDR10 without any problem.
I ve to figure out why Kodi freezes with 5Gb Dolby Vision content.

**Comment by drinfernoo** [comment]
@JacopoV It's a completely different codec 🤷🏼‍♀️

**Comment by JacopoV** [comment]
Yeah @drinfernoo , it seems a Kodi/Hardware related. Now i started digging into more on Kodi's side and different users reporting issues both on Reddit and Kodi's Forum. 

Cheers mate, thanks for your time :)

**Comment by MrNo00** [comment]
> Yeah @drinfernoo , it seems a Kodi/Hardware related. Now i started digging into more on Kodi's side and different users reporting issues both on Reddit and Kodi's Forum.
> 
> Cheers mate, thanks for your time :)

same problem, is there any update on this issue?
