### ISSUE TITLE
[BUG(kodi bug)] Potential fix for kodi bug with empty FILES DB entries for resolved urls

### ISSUE THREAD

**Issue by henryjfry** [nixgates/plugin.video.seren#532]
Ok so firstly feel free to ignore this as its not really a seren issue and it likely something ive only noticed because ive been building my own rd cloud scrape/prescrape tool.

However ive recently determined that if you play something with all the correctly supplied metadata, and then stop it and play it again with the same url provided from RD, that yatse will no longer display the correct metadata. Basic stuff is still fine but cast, air dates, other stuff is all missing.

I determined that the fix is to remove the line from the FILES db table corresponding to the RD filename. When you do that the 2nd time you play the file yatse will show you all the metadata as its actually setup.

I posted something on the kodi forum which goes into greater depth:

https://forum.kodi.tv/showthread.php?tid=360704&pid=3015858#pid3015858

It does only seem to effect yatse, every piece of metadata my skin should be displaying is accounted for when yatse has issues, so I dont know what exactly the difference is there.
I think it effects seren, I've not been using seren too much recently as ive been trying to debug my own tool and this issue so ive not been wanting to have other stuff added to my RD cloud in the interim. But now ive got a fix im going to test seren and confirm if it happens.
However im pretty sure its happened with seren, i suspect its when a new listitem is played but the filename exists in the files table with no associated metadata, from the last time it was played. 
And it somehow pre-empts whatever metadata the file is actually provided with. So it wouldnt just be a file with a DBID link, but any time the same source is played on RD.  Possibly it needs the exact same URL, in which case if Seren generates a new download link every time it might be ok. Although im pretty sure there will be times when it wont.

Anyway i thought it would be worth making you aware of a potential problem and a relatively simple fix. And I'll confirm if its a problem with seren for definite.

**Comment by henryjfry** [comment]
Ok so I just confirmed that if you play the same file again in seren using the same RD source it will not display the full metadata in yatse:

This is how it should look, note the SxxExx format:
https://drive.google.com/file/d/10U5hnli9GJXWqPvH4bUskfA-cCj2bo73/view?usp=sharing

And the full info as displayed in yatse when its working:
https://drive.google.com/file/d/10cHsHFOVwYsf7jcEXE_KgvakpPFrzyrw/view?usp=sharing

And this is what you get when it plays the same file again from the same source:
https://drive.google.com/file/d/10e8UGHKylQcMY7cgg4-Vh2x-EmWkuUWI/view?usp=sharing

So it still has some metadata which yatse is getting fanart, poster, episode title.  But other populated items are not displayed, removing the file link in the FILES table fixes it.

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.17.
