### ISSUE TITLE
[BUG] Issue with Cloud Inspection

### ISSUE THREAD

**Issue by Dealz-416LS** [nixgates/plugin.video.seren#534]
**Logs**
N/A

**Describe the bug**
For a little while now I’ve noticed that Items scraped then resolved are not being found (Cloud Inspection) during subsequent scrapes.

I have `Store resolved items in cloud` Checked.

I suspect that the issue is `Automatic Cloud Removal` is not working for PM Cloud.

I have `Max Storage Space Used Before Deletion (GB)` set to 500.0 and my PM storage was at 502.39

I bumped it up to 750.0 to test, the next resolved item was successfully stored in PM cloud which was now at 505.3 and on subsequent scrapes the item was available via Cloud Inspection.

**To Reproduce**
`Store resolved items in cloud` Checked.
`Automatic Cloud Removal` Checked.
`Inspect Cloud Files on Scrape` Checked

PM cloud storage should be full (above the amount set under `Max Storage Space Used Before Deletion (GB)`

Perform a scrape and the resolved item won’t be saved to PM storage, therefore won’t be available on subsequent scrapes via cloud inspection.

**Expected behavior**
When at the max storage the oldest item(s) in PM cloud storage should be automatically deleted so that the next resolved item has space to be stored.

**Screenshots**
N/A

**Kodi Version (please complete the following information):**
 - Kodi Version 19.0 (Matrix)
 - Seren Version 2.0.16

**Additional context**
This was also an issue on Kodi 18.9 (Leia)

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
