### ISSUE TITLE
[REQUEST] Prioritize HDR in autoplay

### ISSUE THREAD

**Issue by rizreflects** [nixgates/plugin.video.seren#535]
The autoplay feature works well, however, it would be nice if it prioritised HDR in some cases. Lets say for example theres an HDR link which is 20gb, but there is also an SDR link which is 25gb. Currently, seren will go with the SDR link because its a larger file size even though HDR would be preferred. Would it be possible to add an option where Seren will priorotise HDR links before anything else? 

Many thanks, your work is highly appreciated.

**Comment by JacopoV** [comment]
Pretty much similar to this one. If that would be the case, you could just add a filter "HDR" : https://github.com/nixgates/plugin.video.seren/issues/441

**Comment by minhgi** [comment]
+1 for this HDR prority filter after 4K selection.

**Comment by Fatal-Errol** [comment]
Would this fall as an enhancement to the "order by quality" feature? something like

4k Dolby Vision
4k HDR
4k
1080p HDR
1080p
720p

and then having a way to disable HDR would add flexibility.

**Comment by drinfernoo** [comment]
Sorting is getting a pretty large overhaul for the next Seren update, and this should be possible to achieve pretty easily :+1:

**Comment by drinfernoo** [comment]
This should now be totally possible using the new sorting settings in 2.2.0 👍
