### ISSUE TITLE
[BUG] Trakt Watchlist not honoring order set in Trakt

### ISSUE THREAD

**Issue by eengert** [nixgates/plugin.video.seren#536]
This may be resolved when issue #435 is fixed, but just in case it's not related, I wanted to post this issue.  When I view the Watchlist in Seren under My Movies, it doesn't honor the sort and filter settings that I have on the list in Trakt.  So movies aren't sorted properly, and unreleased movies are being displayed (even though I've hidden them in Trakt).

Running Kodi 19 and Seren 2.0.16.  I have tried clearing cache in Seren and rebuilding the Trakt database.

**Comment by Dealz-416LS** [comment]
For your issue with sorting for Watchlist ensure you are setting the ‘default’ sorting for watchlist using the ‘Green Pencil’ icon and not the sorting via the ‘Gear icon’.

`Profile > Lists > Green Pencil icon just below Watchlist`

**Comment by drinfernoo** [comment]
I believe that for Watchlist, you actually need to change the sort within your Trakt user preferences.

**Comment by eengert** [comment]
That was it - I needed to set the default sort type for the watchlist.  I was just sorting my current view in Trakt, which isn't persistent.  Thanks for the help.
