### ISSUE TITLE
[REQUEST] Filter out x265 HEVC files

### ISSUE THREAD

**Issue by Adarma** [nixgates/plugin.video.seren#539]
The old firestick (not 4k) is unable to play x265 HEVC encoded files. Seren tries to play them, fails, but does not try another source. It shows the play symbol and title in the top right corner (estuary skin) but does not play. It stays on the menu screen. If I click the button to return to what is playing (4 triangles pointing out), it shows a play screen playing a silent black video.

I have to manually stop and source select when it happens.

Could you add an option to filter out x265 HEVC files, if it is not possible to detect that they are not playing correctly?

Thanks

**Comment by drinfernoo** [comment]
There already is a setting for this:

`Sort & Filter -> Hide HEVC Items`

**Comment by Adarma** [comment]
Thanks!

I never realized the side menu in the settings scrolled, so hadn't seen the sections below Accounts.
