### ISSUE TITLE
[BUG] Seren not always resuming from correct resume point

### ISSUE THREAD

**Issue by unkn0wn234** [nixgates/plugin.video.seren#543]
**Logs**
I'm not on my Shield at the moment I will try to add debug logs later when I can reproduce, for now here are just logs from when it happened today as I was trying to watch Coming 2 America.

EDIT: none of my logs were saved on my shield so I'll just have to reproduce it with debugging enabled anyway. I will post the logs from my shield later

Here is a log from reproducing on my computer: 
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6096042/kodi.log)

I played Coming  2 America, backed out, it showed 29% on Trakt playback progress manager, I played it again and it resumed correctly the first time. I backed out again and it disappeared from Finish Watching but it was still on the progress manager. I rebuilt database, it showed back up in Finish Watching, I played it again but it incorrectly skipped to 30 seconds.

Debug Log Situation 2 from PC: 

I play the movie to 29%, back out and exit Kodi. I restart Kodi, double check on playback progress manager and it shows 29% here:
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6096057/kodi.log)
![Screenshot 2021-03-06 152939](https://user-images.githubusercontent.com/52363082/110220021-ea866a00-7e90-11eb-9416-771c13972bd3.jpg)
Then I reopen Kodi go to Finish Watching (it was in finish watching but it didnt show any progress icon this time), it skips to 30 seconds and continues from there instead.
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6096058/kodi.log)

Debug Log Situation 3 from PC:
I played the movie to 29%, confirmed on playback progress manager. Back out and close Kodi
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6096069/kodi.log)

Then I reopen Kodi and it's disappeared from Finish Watching but still in progress manager (im refreshing the page to make sure its still there). So I go to TMDBHelper and play w/Seren as default. Im 90% sure the player has been fixed already to support resuming but correct me if im wrong in this situation. It plays w/Seren and starts from the beginning, and overwrites the progress on playback progress manager.
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6096072/kodi.log)

**Describe the bug**
So PM has been acting up and dropping stream a lot today, so I kept having to reclick the movie to play again in Seren. It should have resumed but instead half the time it would just start from the beginning. The poster did show a progress icon though so Seren/Trakt recognized there was progress in the movie. I'm not sure exactly how to reproduce as it would resume sometimes and sometimes not. But what I did notice though was when I restarted Kodi on the first resume it would never correctly resume.

**To Reproduce**
1. Play any movie (Coming 2 America)
2. Back out halfway
3a. Try to resume again w/ Automatic resume on in Seren
3b. Or back out of Kodi, start back up and resume from Finish Watching
4. Movie starts at beginning and doesn't skip to correct resume point. There was one instance where if I let it play for 30 seconds it skipped to the correct point but the rest of the times it either skipped almost immediately, or did not skip at all.

**Expected behavior**
After playing a movie that has progress saved in Trakt/Seren it should skip to the correct resume point

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 -Skin Titan Bingie Mod

**Additional context**
This happened through playing w TMDBHelper, a mixed FinishWatching widget through Autowidget, and by playing in Seren directly as well so I wasnt able to narrow it down to a TMDBHelper player, or a bug with Autowidget, bc it happened in Seren natively too.

**Comment by AshDroidG** [comment]
Can confirm Movie resume point issue. It seems to be only happening with Movies, TV Series episodes resume points are working flawlessly for me.

**Comment by unkn0wn234** [comment]
Just curious in 2.0.17 is this "Calculate resumetime at bookmark insert for movies" a fix for this issue?

**Comment by drinfernoo** [comment]
@unkn0wn234 Yes, this issue should be resolved in 2.0.17.
