### ISSUE TITLE
[BUG] Videos stop playing after a few seconds - PremiumizeMe & Trakt

### ISSUE THREAD

**Issue by Chaaaaaaaaarlie** [nixgates/plugin.video.seren#544]
**Logs**
https://puu.sh/HkBeS/05f87984cc.log

**Describe the bug**
I just did a complete reinstall of Kodi since I have this problem eversince I completely formated my pc and switched vom 18.9 to 19.
Seren is setup with premiumize and trakt. So far no other addons are installed.
Whenever I want to watch a series, doesn't matter which one, have that on every episode I tested so far, the progress time stops after a few seconds and ~2 seconds later the video freezes aswell. When I press stop to get out of the stuck video, Kodi crashes completely.

**To Reproduce**
1. Start watching a video
2. Watch it for ~4 seconds
3. progressbar stops going on
4. video playback stops
5. press "stop" to go back to the menu and Kodi crashes

**Expected behavior**
Series should just play without stopping after a few seconds.

**Screenshots**
https://puu.sh/HkBe9/1f96833b2a.mp4

**Kodi Version (please complete the following information):**
 - Kodi Version [19]
 - Version [2.0.0]

**Additional context**
Everything worked back with 18.9 🤷‍♂️

**Comment by unkn0wn234** [comment]
As of right now it's just a premiumize problem thats causing it to freeze constantly not a Seren one.

**Comment by drinfernoo** [comment]
Agreed, this isn't a Seren issue.
