### ISSUE TITLE
Seren not working

### ISSUE THREAD

**Issue by NadasEnigma** [nixgates/plugin.video.seren#545]
It was working fine a day ago and now it doesn't work, tried everything I could think of, reinstalled reauthorized etc, just gives me errors for everything at check the log file but no log file is ever created... attached images of what I could... help is greatly appreciated as this is my main app... 

![20210306_155120](https://user-images.githubusercontent.com/80180905/110224892-c88ee680-7e94-11eb-90fc-eed3c8614d09.jpg)

![20210306_154924](https://user-images.githubusercontent.com/80180905/110224891-c593f600-7e94-11eb-832d-d9c8e8590ad9.jpg)

![20210306_154901](https://user-images.githubusercontent.com/80180905/110224890-c3319c00-7e94-11eb-828f-ed12cd4c911a.jpg)

![20210306_154730](https://user-images.githubusercontent.com/80180905/110224888-c167d880-7e94-11eb-929a-353218e8f03c.jpg)

![20210306_154354](https://user-images.githubusercontent.com/80180905/110224884-bc0a8e00-7e94-11eb-950d-b09b2eba6c0e.jpg)
![20210306_154442](https://user-images.githubusercontent.com/80180905/110224885-be6ce800-7e94-11eb-8bdb-a1c564f5b344.jpg)
![20210306_154656](https://user-images.githubusercontent.com/80180905/110224887-bf9e1500-7e94-11eb-992a-eb052f860d6e.jpg)

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.

**Comment by NadasEnigma** [comment]
> Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.

Where is this bug report template? I'm new to github... also posted in issue that no log is being created that I can find anywhere so help with that would be great as I haven't been able to use seren since it started doing this... it literally worked one day and the very next having changed nothing it no longer works... I am getting a notification now of version 2.0.18 available for download but it doesn't show me that when going into the repo to update it... thanks
