### ISSUE TITLE
trakt sync

### ISSUE THREAD

**Issue by muzikherif** [nixgates/plugin.video.seren#547]
Before 2.0 it was sync trakt instantly when open lists, but now it do not, i think it should be now too, or it should auto sync lists least at start

**Comment by drinfernoo** [comment]
The Trakt Sync process runs when you authorize Trakt, and then on a schedule after that. This is the way it's always been since Trakt Sync was introduced.

If you're having issues with specific content not syncing and/or showing up correctly, please open a new issue with a debug log attached.
