### ISSUE TITLE
[BUG] Searching TV Shows gives an error on Kodi Leia

### ISSUE THREAD

**Issue by cgcgcgcgcg** [nixgates/plugin.video.seren#550]
Searching TV Shows gives an error on Kodi 18.8
Version: 2.0.16

**Screenshots**
![ksnip_20210312-022204](https://user-images.githubusercontent.com/38960370/110873231-f2536d80-82d9-11eb-8abe-026efa82c6bb.png)

**Comment by CrinkleCo** [comment]
yup I'm getting that as well! Trying to figure this out.

**Comment by derrgoo** [comment]
> yup I'm getting that as well! Trying to figure this out. 

Yes, been a couple days trying to pull tv watchlist and it only gives the first 20 shows and gives error.

**Comment by xxlren** [comment]
I've been struggling with this problem all day. It happens with TV shows, and Search by Actor. Some TV lists bring up 1 show, the others only show Error

**Comment by cgcgcgcgcg** [comment]
This might be a TMDB or Trakt issue.

**Comment by cgcgcgcgcg** [comment]
As opposed to my Matrix Seren where I can't go in my Shows library, I can in Leia, but now I get:
No playable sources.

**Comment by peno64** [comment]
The strange thing is that it isn't with all searches.
For example 
search on Game of thrones works
search on la casa de papel works
but search on the killing gives the error (same as original user reported (argument of type 'NoneType' is not iterable))

**Comment by LoganWolverineX** [comment]
hopes @nixgates checks this out soon.  i also see this error also.

**Comment by peno64** [comment]
I have a "fix" (most probably not a definite one but it makes possible to continue searching tv shows). Not that it is only for searching tv shows on name of tv show. Not by actor, year or whatever. I haven't looked at that since I never use it.
In Addons\plugin.video.seren\resources\lib\indexers\tvdb.py change the following:

    def _handle_response(self, language, item):
        result = {}
        item = self._try_detect_type(item)
        if "mediatype" not in item:
            return item

to

    def _handle_response(self, language, item):
        result = {}
        item = self._try_detect_type(item)
        if item is None or "mediatype" not in item:
            return item

and

    def _try_detect_type(item):
        if "airedSeasons" in item or "seriesName" in item:
            item.update({"mediatype": "tvshow"})
        elif "episodeName" in item:
            item.update({"mediatype": "episode"})
        return item

to

    def _try_detect_type(item):
        if item is None:
            return item
        if "airedSeasons" in item or "seriesName" in item:
            item.update({"mediatype": "tvshow"})
        elif "episodeName" in item:
            item.update({"mediatype": "episode"})
        return item

After this, restart your kodi (important) and then search works again for me.

**Comment by derrgoo** [comment]
> I have a "fix" (most probably not a definite one but it makes possible to continue searching tv shows). Not that it is only for searching tv shows on name of tv show. Not by actor, year or whatever. I haven't looked at that since I never use it.
> In Addons\plugin.video.seren\resources\lib\indexers\tvdb.py change the following:
> 
> ```
> def _handle_response(self, language, item):
>     result = {}
>     item = self._try_detect_type(item)
>     if "mediatype" not in item:
>         return item
> ```
> 
> to
> 
> ```
> def _handle_response(self, language, item):
>     result = {}
>     item = self._try_detect_type(item)
>     if item is None or "mediatype" not in item:
>         return item
> ```
> 
> and
> 
> ```
> def _try_detect_type(item):
>     if "airedSeasons" in item or "seriesName" in item:
>         item.update({"mediatype": "tvshow"})
>     elif "episodeName" in item:
>         item.update({"mediatype": "episode"})
>     return item
> ```
> 
> to
> 
> ```
> def _try_detect_type(item):
>     if item is None:
>         return item
>     if "airedSeasons" in item or "seriesName" in item:
>         item.update({"mediatype": "tvshow"})
>     elif "episodeName" in item:
>         item.update({"mediatype": "episode"})
>     return item
> ```
> 
> After this, restart your kodi (important) and then search works again for me.

It happens in search and also pulling your tv shows on Trakt which only allow 20 items and gives an error. Will this fox that also?

**Comment by peno64** [comment]
@derrgoo It it for both 18 and 19. Tried on both. I don't understand your other question. Do you have an example I can try if it works?

**Comment by derrgoo** [comment]
> @derrgoo It it for both 18 and 19. Tried on both. I don't understand your other question. Do you have an example I can try if it works?

Okay that actually worked for my issue. If you use trakt and try to pull tv watchlist you could only pull 20 and seren would error. With your fox now I can pull the full list. Search works also. Well done!

**Comment by peno64** [comment]
@derrgoo It would surprise me that this is a definite fix because I only test if a list is None that it doesn't give an error. So consider this more as a temporary work-around

**Comment by derrgoo** [comment]
> @derrgoo It would surprise me that this is a definite fix because I only test if a list is None that it doesn't give an error. So consider this more as a temporary work-around

Good fix until nixgates gets time. :)

**Comment by peno64** [comment]
If needed , I can make a zip file available so that seren can be updated temporary with this patch until the addon is updated.

**Comment by derrgoo** [comment]
> If needed , I can make a zip file available so that seren can be updated temporary with this patch until the addon is updated.

Great idea for people that can’t find the code to change.

**Comment by BlackChee** [comment]
> I have a "fix" (most probably not a definite one but it makes possible to continue searching tv shows). Not that it is only for searching tv shows on name of tv show. Not by actor, year or whatever. I haven't looked at that since I never use it.
> In Addons\plugin.video.seren\resources\lib\indexers\tvdb.py change the following:
> 
> ```
> def _handle_response(self, language, item):
>     result = {}
>     item = self._try_detect_type(item)
>     if "mediatype" not in item:
>         return item
> ```
> 
> to
> 
> ```
> def _handle_response(self, language, item):
>     result = {}
>     item = self._try_detect_type(item)
>     if item is None or "mediatype" not in item:
>         return item
> ```
> 
> and
> 
> ```
> def _try_detect_type(item):
>     if "airedSeasons" in item or "seriesName" in item:
>         item.update({"mediatype": "tvshow"})
>     elif "episodeName" in item:
>         item.update({"mediatype": "episode"})
>     return item
> ```
> 
> to
> 
> ```
> def _try_detect_type(item):
>     if item is None:
>         return item
>     if "airedSeasons" in item or "seriesName" in item:
>         item.update({"mediatype": "tvshow"})
>     elif "episodeName" in item:
>         item.update({"mediatype": "episode"})
>     return item
> ```
> 
> After this, restart your kodi (important) and then search works again for me.

Wow, thanks man... I couldn't even open my Next up or Watchlist in Seren. This fixed it.

**Comment by peno64** [comment]
See https://peno64.github.io/ to install the temporary fix. Please read the note in bold. For some reason you need to have a bit of patience to install this.

**Comment by peno64** [comment]
Oh and I also included the fi for #552

**Comment by Dealz-416LS** [comment]
> See https://peno64.github.io/ to install the temporary fix. Please read the note in bold. For some reason you need to have a bit of patience to install this.

Thanks! I took the tvdb.py from your .zip and no more errors, certain widgets, lists etc that weren't working are loading again.

**Comment by drinfernoo** [comment]
This should be solved in 2.0.17.
