### ISSUE TITLE
Finish Watching

### ISSUE THREAD

**Issue by derrgoo** [nixgates/plugin.video.seren#551]
**Logs**

Please provide debug logs to assist with your issue

**Describe the bug**

When I stop a movie before it ends I see it in finish watching which is great. But lately I see it then come back in a few hours it is gone. But when I click on that movie it does remember where I left off. Just wondering why it disappeared off my widget. Thanks.

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.
