### ISSUE TITLE
Seren will only play once i have scraped twice

### ISSUE THREAD

**Issue by andrewhulse1981** [nixgates/plugin.video.seren#554]
updated to Kodi 19 Matrix and when trying to watch anything with the Seren addon, i scrape for the sources list to come up but when i click to watch one of the sources it comes up saying unable to find playable source. But when i go back to the movie or tv episode and re-scrape it come ups with a source from the cloud and plays just fine. Seems to only do this when trying to watch a torrent source, when using a hoster source it plays fine.

**Expected behavior**
When using the Seren Addon on Kodi 18.9 it would play the source straight away with out having to re-scrape what ever i wanted to watch.

**Kodi Version (please complete the following information):**
 - Kodi 19 Matrix

**Comment by Arthur1967** [comment]
18.9 I can't get trakt shows to show but the movie section does￼￼

**Comment by drinfernoo** [comment]
Please open this again with a log attached (follow the bug report template) if it is still an issue in 2.0.17.

**Comment by Arthur1967** [comment]
I just tried it this afternoon with 19 and it's working thank you
