### ISSUE TITLE
[BUG] Seren doesn't want to play any stream with source type Torrent on kodi 19 on LibreElec Raspberry pi4

### ISSUE THREAD

**Issue by peno64** [nixgates/plugin.video.seren#558]
**Logs**

https://paste.kodi.tv/jinaminufu.kodi

**Describe the bug**
Since a couple of days kodi 19 is also available on  raspberry pi4 with libreelec.
Running Seren on it has following issue.
I made a fresh install of kodi 19 from scratch and only installed Seren on it. I configured the provider, real debrid and tract.
I also specified that Seren must search for all links (no preemtive termination, no stop after cloud sources are found, no terminate if adaptive sources are found whatsoever) and after the search is done that I can choose which stream to  play.
Streams marked with Source type Cloud (the first ones in the list) play without a problem. However streams of type Torrent don't play at all. The message "No  playable sources are found" is given. That for all Torrent streams. All this goes well on a fresh installation under windows with kodi 19. It also forks fine on that same pi4 with kodi 18.9 under libreelec.
In the log you can see following error at the end:

2021-03-18 00:24:25.496 T:1331     INFO <general>: SEREN: Failing Magnet: magnet:?xt=urn:btih:10939B13553C69DA383489BC8FE77A8BACEF4254&
2021-03-18 00:24:25.497 T:1331    ERROR <general>: SEREN: IndexError: string index out of range

                                                   During handling of the above exception, another exception occurred:

                                                   simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I traced it back to the following:

in resources/lib/debrid/real_debrid.py there is following routine:

    def _is_response_ok(self, response):
        try:
            if "error" in response.json():
                self._handle_error(response)
                return False
            return True
        except JSONDecodeError:
            return True

Here the problem occurs. This when the function is called after a call to:

response = self.session.post(url, data=post_data, timeout=5)

The response is: <Response [204]>

A bit further the following call is done:

if not self._is_response_ok(response) and not fail_check:

and it is in _is_reponse_ok that the error occurs at the instruction:

response.json()

There is a catch for JSONDecodeError which is indeed called under windows with kodi 19) but on the pi4 with libreelec and kodi 19 another error is thrown, namely:

Expecting value: line 1 column 1 (char 0)

So when I add:

        except Exception as e:
            return True

Then everything is ok again...

**To Reproduce**
1. search any movie or tv show
2. In the list of found streams, choose a stream  with type Torrent
4. The error is given

**Expected behavior**
The stream should play

**Kodi Version (please complete the following information):**
 - Kodi Version 19.0
 - Version 2.0.16+matrix.1

**Additional context**

**Comment by peno64** [comment]
My  proposed fix is:

in  resources/lib/debrid/real_debrid.py:

change:

    def _is_response_ok(self, response):
        try:
            if "error" in response.json():
                self._handle_error(response)
                return False
            return True
        except JSONDecodeError:
            return True

to: 

    def _is_response_ok(self, response):
        try:
            if response.status_code != 204 and "error" in response.json():
                self._handle_error(response)
                return False
            return True
        except JSONDecodeError:
            return True

Since response 204 means "The server has successfully fulfilled the request and that there is no additional content to send in the response payload body", no response.json() should be done and it should be handled as ok.

With this all works fine again.

**Comment by peno64** [comment]
Note also the error at  the beginning of the log file I attached in the report. At startup of kodi an error is thrown when maintenance.run_maintenance() is executed. Maybe this should also be looked at.

**Comment by drinfernoo** [comment]
This should be resolved in 2.0.17.

**Comment by peno64** [comment]
@drinfernoo 
I can confirm that the latest update of Seren indeeds solves the problem. 
Thank you
