### ISSUE TITLE
[BUG] 2.0.17 installed - Seren Still Crashes

### ISSUE THREAD

**Issue by LoganWolverineX** [nixgates/plugin.video.seren#559]
**Logs**
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6161434/kodi.log)

**Describe the bug**
I was hoping after installing 2.0.17, Seren Next up widget would stop crashing but it still crashes once in a while.  See log attached.  Usually happens more when I clear kodi cache.

**Kodi Version (please complete the following information):**
 - Kodi Version 19.0
 - Seren Version 2.0.17
 - Skin: Horizon (official)

**Comment by Mucka911** [comment]
Please try to disable reuselanguage invoker.

**Comment by LoganWolverineX** [comment]
> Please try to disable reuselanguage invoker.

Yea I have that disabled. Still either sometimes crashing kodi or next up won’t load.

**Comment by drinfernoo** [comment]
This appears to be some sort of pickling error 🤔

**Comment by LoganWolverineX** [comment]
@drinfernoo can you explain what you mean  by “pickling error”?

**Comment by drinfernoo** [comment]
@LoganWolverineX It's a Python thing... not sure why it's happening here.

**Comment by LoganWolverineX** [comment]
@drinfernoo ahhhh ok. Hopefully @nixgates  is able to figure it out.

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.18.
