### ISSUE TITLE
Downloading Locally Not Working.

### ISSUE THREAD

**Issue by mariofenech** [nixgates/plugin.video.seren#560]
I m trying to download locally from Seren but doesn't seem that its working for me..
Downloads are only showing on RD like downloads but not in the folder I set path for trough addon settings..
Am I missing something?

**Comment by drinfernoo** [comment]
You're missing a log file.

**Comment by mariofenech** [comment]
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6165011/kodi.log)

I get popup download task started but not sure why it s going to RD instead of folder

**Comment by mariofenech** [comment]
debug
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6165052/kodi.log)

**Comment by drinfernoo** [comment]
I've confirmed this as still being an issue.

**Comment by drinfernoo** [comment]
And it's been fixed in development, so should be working fine for all debrid services in next release :+1:

**Comment by drinfernoo** [comment]
This one should now be fixed in 2.1.4. Would you be able to confirm if it's working for you now?

**Comment by mariofenech** [comment]
Hi,can confirm it's working nicely including download speed,ETA etc..nicely done,thanks!

**Comment by daherlihy** [comment]
@mariofenech can you do a screen recording or something to show how you download? I can't get it to work in 2.1.4 (have reported it as a new issue), I'm hoping that I've just missed something that you may be able to bring my attention to

**Comment by drinfernoo** [comment]
@daherlihy While on the Source Select screen, you can highlight a source, and either choose "Download" (on the right, in the default theme) or open the context menu and choose "Download" from there.

**Comment by daherlihy** [comment]
Yep that's what I've been doing too and it gives me the prompts then to confirm the file to be downloaded, and then that the download task has started, but still nothing is happening anywhere.

Could it be something to do with the fact that I'm trying to download to Android devices? I notice that I can't change the download directory - I can't for instance go any any location outside of the Kodi installation folder in the Android > Data folder.

**Comment by kranix0** [comment]
Same problem on Nvidia Shield Pro with latest Kodi and Seren releases.

**Comment by daherlihy** [comment]
I've given up trying to download anything through Seren. Instead I've discovered a workaround, a different add-on to download what you've streamed from RealDebrid - its called Realizer: https://howtomediacenter.com/en/install-realizer-kodi-addon/
