### ISSUE TITLE
[BUG]All seasons displaying watched indicator & Shows missing Episode count

### ISSUE THREAD

**Issue by Dealz-416LS** [nixgates/plugin.video.seren#563]
**Logs**
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6214773/kodi.log)

**Describe the bug**
I think all these issues are related.

Bug 1. All (unwatched) seasons of a show are displayed with the marked as watched indicator. (Issue happened in 18.9 and 19.0)
Bug 2. All seasons for shows have the same year. (Issue happened in 19.0 only, worked fine on 18.9)
Bug 3. All or some shows missing episode count. (Issue happened in 19.0 only, worked fine on 18.9)

_NOTE:_ Tested with Trakt on TMDb Helper and had no issues.

There seems to be an issue with the way Seren is loading data for items.

**To Reproduce**
Bug 1. Browse to the season of any unwatched show and all seasons will be displayed as watched.
Bug 2. Browse to the season of any show and all seasons will display the same year.
Bug 3. `Seren > Dicover TV Shows > Trending (for example)` All shows missing episode count indicator (In progress shows (trakt) are okay.

**Expected behavior**
Bug 1. Browsing to the seasons view of an unwatched show should display the number of episodes for each season for skins that support it, in this case AuraMOD and Estuary.
Bug 2. Browsing to the seasons view of any show should display the correct Year in View Types that display it.
Bug 3. Browsing lists for shows should display the number of unwatched episodes in the top right corner of the artwork.

**Screenshots**
Bug 1. and 2.
All seasons displayed as watched and All season display the same Year.
![Kodi_20210327_172130](https://user-images.githubusercontent.com/54026944/112729214-f8289000-8f22-11eb-9528-0cfcbae44822.png)

Bug 3.
Virtually all shows are missing the episode count indicator. (Also happens in Estuary Skin, Shows display 0/0)
![Kodi_20210327_174155](https://user-images.githubusercontent.com/54026944/112729392-c3690880-8f23-11eb-8fe1-b2e3b39831ba.png)

Fixes/Workarounds
Bug 1. and 3. can both be fixed by going to a shows seasons view and then Force Trakt Sync.
Bug 2. can be fixed by clicking on any season then going back to the seasons view but the issue will re-occur again when navigating back to that shows seasons later.

**Kodi Version (please complete the following information):**
 - Kodi Version 19.0
 - Seren Version 2.0.18

**Additional context**

**Comment by drinfernoo** [comment]
Please attach a debug log.

**Comment by Dealz-416LS** [comment]
> 
> 
> Please attach a debug log.
Sorry was in the process of adding one, I have attached one now.

**Comment by Dealz-416LS** [comment]
Now the dates are all the same, clicking any season and then navigating back fixes this.

date is shown as 2004 for all seasons
![Kodi_20210324_163658](https://user-images.githubusercontent.com/54026944/112348276-94eaf380-8cbf-11eb-93eb-5da106a3c226.png)

clicking a season and navigating back fixes the dates
![Kodi_20210324_164315](https://user-images.githubusercontent.com/54026944/112348795-10e53b80-8cc0-11eb-8776-994ae83336e4.png)

Navigating back to the show at a later time reverts the dates back to 2004 again.

Kodi Version 19.0
Seren Version 2.0.17+Matrix.1

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6199075/kodi.log)

**Comment by Dealz-416LS** [comment]
Update:

Bug 3. is caused by this [fix/workaround](https://github.com/nixgates/plugin.video.seren/issues/570#issuecomment-805878673)

**Comment by Dealz-416LS** [comment]
Update:

Re-Tested on 2.0.19

Bug 1. All unwatched seasons of a show are being displayed with the marked as watched indicator - **Still an Issue**
Bug 2. All seasons for shows have the same year - **Fixed**
Bug 3. All or some shows missing episode count - **Still an Issue with this** [fix/workaround](https://github.com/nixgates/plugin.video.seren/issues/570#issuecomment-805878673)

**Comment by Dealz-416LS** [comment]
Update: 

Re-tested in 2.1.0 after a cache clear and database rebuild.

Bug 1. All unwatched seasons of a show are being displayed with the marked as watched indicator - **Still an Issue**
Bug 2. All seasons for shows have the same year - **Fixed in 2.0.19**
Bug 3. All or some shows missing episode count - **Still in the process of checking if the issue the [workaround](https://github.com/nixgates/plugin.video.seren/issues/570#issuecomment-805878673) fixes is already fixed, if so workaround is no longer needed.**

**Comment by drinfernoo** [comment]
Ok, I've spent some time testing these tonight.

It sounds like "bug #2" is fixed, and it does appear that way for me as well.

For "bug #3", it appears to be *caused by* a "hack" contributed by another user, in response to #570... which we're not supporting, therefore it is an invalid bug.

I **can** reproduce "bug #1"... in some instances. It appears to affect Seren *when combined with AuraMOD*. It doesn't present itself to me in two other skins (Estuary or Arctic Horizon), or in TMDbHelper... so for now I'm chalking it up to some interoperability issue between specifically AuraMOD and Seren.

If you would please open your issue again, specifically for "bug #1", that would be great. This would be in order to have something more directed to show to the developers of both Seren and AuraMOD, without the cruft of "bug 2" and "bug 3" getting in the way.
