### ISSUE TITLE
[BUG] 2.0.17 Pre emptive termination still broken 

### ISSUE THREAD

**Issue by sathish804** [nixgates/plugin.video.seren#564]
**Logs**

Please provide debug logs to assist with your issue

https://controlc.com/d88f9665

**Describe the bug**
Enabled the preemptive termination settings as per below screen shot. But preemptive termination not worked. 

**To Reproduce**
1. Enable preemptive termination
2. Play any movie 

**Expected behavior**
Preemptive termination should stop the scrapping after condition met. 

**Screenshots**
![Screenshot_20210318-231426](https://user-images.githubusercontent.com/14090242/111705208-a73cdb80-8840-11eb-9430-9a4005744046.jpg)
![Screenshot_20210318-231446](https://user-images.githubusercontent.com/14090242/111705231-adcb5300-8840-11eb-8702-c5213833b2e9.jpg)

**Kodi Version (please complete the following information):**
 - Kodi Version : 19
 - Version [e.g. 22] 2.0.17 

**Additional context**

**Comment by drinfernoo** [comment]
Please attach a debug log, as indicated by the bug report template.

**Comment by sathish804** [comment]
Log : https://controlc.com/d88f9665

**Comment by JacopoV** [comment]
Same for me. Keeps not cutting the search once the criteria have been satisfied.

Running 2.0.17 on Leia 18.9 on Android TV 9

**Comment by drinfernoo** [comment]
Can you reproduce this with Orion disabled/uninstalled? It may be an issue with Orion.

**Comment by JacopoV** [comment]
@drinfernoo if you referring to me I dunno what Orion is. Don't think I have it. If needed I can send you my log because I never got the pre emptive termination working =)

**Comment by sathish804** [comment]
> Can you reproduce this with Orion disabled/uninstalled? It may be an issue with Orion.

Tried disabling the orion as well same behavior.

![Screenshot_20210327-152034](https://user-images.githubusercontent.com/14090242/112723724-46806380-8f10-11eb-852c-f92ef29991c3.jpg)
https://controlc.com/255f3565
