### ISSUE TITLE
[BUG] 2.0.17 Resume option is showing twice

### ISSUE THREAD

**Issue by sathish804** [nixgates/plugin.video.seren#565]
**Logs**

Please provide debug logs to assist with your issue

**Describe the bug**
Hi all, on Seren 2.17 when ever I am trying to play a movie with a resume point is showing me resume option twice, this wad not the case with 2.16. 

**To Reproduce**
1. Play a movie with resume point in Seren 

**Expected behavior**
Seren has to show resume option dialog only once. 

**Screenshots**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/14090242/111705543-2d592200-8841-11eb-92c4-dea36dbadce3.gif)

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1] 19
 - Version [e.g. 22] 2.0.17 

**Additional context**

**Comment by unkn0wn234** [comment]
+1 can confirm for myself too, I have automatic on so it asks to resume with it on but I assume its still 2, the first auto, then the second asking to resume

**Comment by sathish804** [comment]
Log: https://controlc.com/d88f9665

**Comment by unkn0wn234** [comment]
For anyone else coming here to +1 or find a solution, go to Kodi Settings -> Media Settings -> Videos -> Set Default Select Action to "Resume" should be on "Play" by default. This will then respect whatever resume method you've enabled in Seren whether its Ask to Resume or Automatic.
