### ISSUE TITLE
[BUG] 2.0.17 All Geners showing same content 

### ISSUE THREAD

**Issue by sathish804** [nixgates/plugin.video.seren#567]
**Logs**

Please provide debug logs to assist with your issue

**Describe the bug**
Hi all, on Seren 2.17 when ever trying to open any gener showing the same titles. 

**To Reproduce**
1. Open different generes from discover movies section 

**Expected behavior**
Respective genre titles should be shown. 

**Screenshots**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/14090242/111706041-ea4b7e80-8841-11eb-9ebf-9f254c941e19.gif)

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1] 19
 - Version [e.g. 22] 2.0.17 

**Additional context**

**Comment by sathish804** [comment]
Log : https://controlc.com/d88f9665

**Comment by irbyjm** [comment]
Ditto: https://paste.kodi.tv/yegecebece.kodi

**Comment by Alfiegerner** [comment]
Cross posting a fix I've seen on reddit that works well for me: https://www.reddit.com/r/addons4kodi/comments/m9flla/_/grnz98l?context=1000

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.18.
