### ISSUE TITLE
New Das boot Show no artwork and won't show links

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#57]
The new Das Boot TV show has no artwork and instead has white projector symbol.

Since the latest .34 update that added artwork to the scraper page it seems if the show doesn't have artwork it won't show the scraper page and displays no links available message.

**Comment by nixgates** [comment]
Oh sod, yep, I made a boo boo!
I'll fix this and get this rolled out soon

**Comment by nixgates** [comment]
@lukehansford can you please confirm this issue is resolved as of 0.1.35

**Comment by lukehansford** [comment]
I can confirm this did indeed get fixed in 0.1.35.
I have closed the ticket.

Thankyou for the swift response for this.
