### ISSUE TITLE
[BUG] Seren only plays after a re-scrape

### ISSUE THREAD

**Issue by andrewhulse1981** [nixgates/plugin.video.seren#575]
**Logs**
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6175114/kodi.log)

**Describe the bug**
Seren has updated today and when trying to watch something in Seren i scrape the item and when i click on a link it will say "no playable resource", but then if i re-scrape the item it will find that it has added it to my real-debrid cloud and when clicking the link it works. Seems to have only started this behavior after the recent Seren update. It only seems to do this when trying to watch from a torrent link, the hoster links work fine after the first scrape.

**To Reproduce**
1. Go to Seren
2. Click on movie or episode i want to watch
3. once scraped select a link
4. See error "no playable resources"
5. right click and select Re-Scrape item on the same movie or episode
6. finds cloud file, click the cloud file link

**Expected behavior**
usually it will play the link after the first scrape

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Seren Version 2.0.17
 - OS Ubuntu 20.10

**More Info**
to fix i have tried to wipe the addon data, uninstall the addon, close Kodi, open Kodi, re-install the Seren addon and i am still getting the same issue.

Thanks

**Comment by Seldon2K** [comment]
I have the same error, rescraping does not solve the problem for me though 
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6175259/kodi.log)

**Comment by rapbit0** [comment]
I also have the same exact error, rescraping doesn't solve it for me either.

I have reinstalled Kodi and seren and set it all up again but am still experiencing the same issue

**Comment by peno64** [comment]
If you ask me, this is related to #558 
I would not be surprised if adding my test
response.status_code != 204
in  _is_response_ok would solve this error. Especially the one from the second log file.

**Comment by Seldon2K** [comment]
Wow! That solved the problem for me! @peno64. Thank you so much!
Strange thing is that 2.0.17 update was supposed to fix this issue, but in my case it seems it actually caused it. Not sure though.

**Comment by peno64** [comment]
@drinfernoo 

I note that resources/lib/debrid/real_debrid.py

was changed from:

try:
    from json.decoder import JSONDecodeError
except ImportError:
    JSONDecodeError = ValueError

to:

    try:
        from simplejson.errors import JSONDecodeError
    except ImportError:
        from json.decoder import JSONDecodeError

And that solved my problem #558 but it seems to introduce this problem #575

Maybe JSONDecodeError from both imports should be catched? Maybe one source file uses simplejson and another source file uses json?

Anyway, I would also add my test on response.status_code != 204 since 204 means there is no response and as such response.json()  should not be called in that case...

**Comment by rapbit0** [comment]
@peno64 Hm I have tried that aswell; adding your test to the method, but unfortunately that didn't solve it for me. If it is possible for you to have a look at my log file above that would be awesome! Is this enough information or would advanced debugging help? Thanks!

**Comment by rapbit0** [comment]
@peno64 Thanks so much for your help, it's working now! But I wasn't able to install your seren version. It only ever went to  72% Installation progress and then got stuck.

But what fixed it for me: I disabled "Enable preemptive termination" in the seren settings. Then some of the torrents worked,  but some did not. Checked the log, and had the exact same error message in _is_response_ok. After changing the if statement to your suggestions, it works perfectly now. Thanks so much, you saved my evening ;)

**Comment by peno64** [comment]
@rapbit0 
If you had read the text at https://peno64.github.io/ you would have seen that it takes some time to install it. I am sure that update did install. You only have to wait for a couple of minutes.

**Comment by andrewhulse1981** [comment]
> @rapbit0
> I would expect that my change does fix your problem. But I see that you have multiple errors in your log file and these don't show where the problem occurs.
> You can try to install my altered version of Seren from https://peno64.github.io/
> If that does not help then try to make a debug log. Make sure you restart kodi after setting debug on and only do the action in Seren. Otherwise there are too much thing in the log.

Brilliant!!!! I downloaded your seren zip file and replaced my real_debrid.py file with the one in your zip file and hey presto it is working. 
Thanks very much

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.18.
