### ISSUE TITLE
Seren occasionally loses a complete season of shows.  For example Chicago Fire Season 9 [BUG]

### ISSUE THREAD

**Issue by JEM11COBRA** [nixgates/plugin.video.seren#576]
**Logs**

Please provide debug logs to assist with your issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by drinfernoo** [comment]
Please fill out the bug report template when opening bug reports.
