### ISSUE TITLE
[BUG] Error when trying to scrape sources

### ISSUE THREAD

**Issue by flokii88** [nixgates/plugin.video.seren#577]
**Logs**

https://pastebin.com/hjEEMLgS

**Describe the bug**
Error showed when selecting any movie / tv show. I'm an AllDebrid user.

**To Reproduce**
1. Go to any Tv show list or movie
2. Press Enter or rescrape item

**Expected behavior**
Source list must be displayed

**Kodi Version (please complete the following information):**
 - Kodi Version [19.0.0]
 - Seren Version [2.0.17+matrix.1]

**Additional context**
Tried to uninstall then reinstall Seren, wipe cache, tried peno64 matrix fix, re-downloading providers packages

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.18.
