### ISSUE TITLE
Widget Next up

### ISSUE THREAD

**Issue by derrgoo** [nixgates/plugin.video.seren#578]
I ran a log nothing shows up. Since the last update my next up widget on multiple skins keep disappearing until I reload skin. This happens very often now. Thanks!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by JacopoV** [comment]
Are you referring to the Smart play for the next episode? If so I noticed the same issue.
It doesn't show up up till you reload the skin

**Comment by derrgoo** [comment]
The automatic play another episode is working but I am talking about a next up widget that keeps disappearing until I reload skin.

**Comment by drinfernoo** [comment]
Please fill out the bug report template when opening bug reports.
