### ISSUE TITLE
[BUG] My Shows Trakt Collection Error

### ISSUE THREAD

**Issue by jastremit** [nixgates/plugin.video.seren#579]
**Logs**

https://paste.kodi.tv/etuseripel

**Describe the bug**
I navigate to My Shows-> Collection. when I click Collection I am presented with a Seren error and my Trakt TV Show collection is not displayed. 

**To Reproduce**
1. Go to 'Seren Shows'
2. Scroll down to 'My Shows'
3. Click on 'My Shows'
5. Scroll down to 'Collection'
6. Click on 'Collection'

**Expected behavior**
I am expecting for my Trakt TV Show collection to populate in an alphabetical order. 

**Screenshots**
N/A

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9
 - Version 2.6
 - Xanax Build 2.6

**Additional context**
I am running Kodi 18.9 Xanax build 2.6 on Fire TV Stick 4k. fire OS 6.2.7.7(NS6277/3033)

**Comment by jastremit** [comment]
please lmk if I need to provide any further information. this is happening in Seren version 2.0.17. thanks

**Comment by drinfernoo** [comment]
This should be fixed in 2.0.18.
