### ISSUE TITLE
Install provider from storage (zip file)

### ISSUE THREAD

**Issue by Sunseng** [nixgates/plugin.video.seren#58]
The last version 0.1.34 seems broke install provider from external storage again (zip file), error occured. This not happen with version 0.1.30 tho.

**Comment by nixgates** [comment]
Can you expand on the issue you are having is? 

Are you trying to install a provider from a URL or from a local zip package? 

Can you please provide a full kodi log with debugging enabled so I can see what's causing the error.

**Comment by Sunseng** [comment]
Yes trying to install a provider from a local zip package. 
Here the log file []https://paste.ubuntu.com/p/qF8Wfvf8Zp/(url)

**Comment by Sunseng** [comment]
[https://paste.ubuntu.com/p/qF8Wfvf8Zp/plain/](url)

**Comment by Sunseng** [comment]
[log200219.txt](https://github.com/nixgates/plugin.video.seren/files/2884789/log200219.txt)

**Comment by nixgates** [comment]
Mind if I know what kind of OS you are attempting to do this on?

Windows, Linux, iOS, Android?

**Comment by Sunseng** [comment]
Android with Shield TV

**Comment by Sunseng** [comment]
Uhmm.. my bad i think i renamed wrongfully the local provider package zip file. Got it to install now. Thanks 🙏👍.
