### ISSUE TITLE
[BUG] Seren crashes when Kodi goes back to home screen after stopping a movie or TV show

### ISSUE THREAD

**Issue by hyzor** [nixgates/plugin.video.seren#584]
**Logs**
https://pastebin.ubuntu.com/p/kfYHKQsCjF/

**Describe the bug**
Seren causes Kodi to crash whenever you stop a movie or TV show from playing and Kodi goes back to the home screen where you have your widgets. This assumes you have a third party skin that supports home screen widgets.

I have tried Arctic Horizon and AuraMod (modded for Matrix), both causing the same type of crash. I have seen another case where the crashes were resolved by using something else other than Seren, leading me to believe Seren is causing the crashes.

It only seems to crash when Kodi wants to go straight back to the home screen after stopping the video. It does not crash if I'm playing from within Seren and it exits back to Seren. So I am thinking it is Seren and its widgets that are not playing along nicely.

**To Reproduce**

0. First you need a third party skin that supports home screen widgets. Then set up at least one Seren widget on your home screen (let's say Discover Movies -> Popular).
1. Go to your home screen (Movies section or wherever you have widgets set up)
2. Click on any movie or TV show of choice
3. Finish said movie/TV show and exit by stopping the player (Not sure if you need to actually finish it)
4. Kodi should now force exit

**Expected behavior**
The expected behavior is that it goes back to the home screen without any crashing, when you stop a movie or TV show. Finishing a movie or TV show marks it as watched via Trakt (which it currently does).

**Screenshots**
Not applicable.

**Kodi Version (please complete the following information):**
 - Kodi Version (19.0 (19.0.0) Git:20210218-f44fdfbf67). Platform: Android ARM 64-bit
 - Seren Version 2.0.18+matrix.1-local

**Additional context**
The log file posted is huge, but scroll down to the bottom and you will see an interesting part:
```
2021-03-28 15:46:07.615 T:15406   ERROR <general>: Unable to find plugin 
2021-03-28 15:46:07.616 T:15406   ERROR <general>: GetDirectory - Error getting plugin://
2021-03-28 15:46:07.616 T:7697    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://) failed
2021-03-28 15:46:07.682 T:15367   ERROR <general>: GetDirectory - Error getting include
```
It is trying to get `plugin://`, i.e. `plugin null/undefined`? Not sure what is going on here...

Also another interesting part:
```
2021-03-28 15:45:55.741 T:15386   ERROR <general>: GetDirectory - Error getting 
2021-03-28 15:45:55.755 T:7697    ERROR <general>: Control 53 in window 10025 has been asked to focus, but it can't
```
At the bottom of the log.

**Comment by irbyjm** [comment]
Do you have `reuselanguageinvoker` enabled in Seren settings? If so, can you try disabling it? In my experience it's kind of finicky.

**Comment by hyzor** [comment]
I had that enabled and disabling it did work, I think. Looks like it's causing issues for other people as well and is due to a Kodi bug. I watched several episodes now trying to trigger the crash but it looks stable for now.

But as I am writing this, after installing the Trakt addon (because I like to rate everything I watch), Kodi just crashed to my surprise. I stopped playing an episode halfway through, it went back to the home screen and then crashed. Possibly unrelated.

**Comment by hyzor** [comment]
Here is another log file with debug enabled:
https://pastebin.ubuntu.com/p/RM97RW22YQ/

I can basically trigger Kodi to crash by reloading skin (thus reloading widgets on the home screen). Judging by the log, I suspect it is either Seren or Skinvariables that is causing the crash (or the combination of the two).

**Comment by JacopoV** [comment]
I have the exact same problem. If I pause during and episode, or I completed it and go home right after, Kodi crashes.

Seren 2.0.18
Kodi 19

**Comment by sabatale** [comment]
Same here.
