### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by calieatsgreedy** [nixgates/plugin.video.seren#588]
**Logs**

Please provide debug logs to assist with your issue

seren error- check log message

**Describe the bug**
When i click links to movies or shows, it reads " seren error - check log information" i have notice that the torrents arent loading when searching for a source only host numbers change, i have uninstalled and reinstalled , i have a premium debrid account as well. 

**To Reproduce**
1. Go to 'any movie or show '
2. Click on '.to initiate search for torrent '
3. Scroll down to ' error appears after only host loading number increase '

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version [e.g. 18.7, 19.0rc1]

**Additional context**

**Comment by irbyjm** [comment]
Which debrid provider are you using? I have been seeing timeout issues to PM for about 17 hours.

**Comment by calieatsgreedy** [comment]
> https://real-debrid.com


this one? i hope that answered that lol im kinda new

**Comment by calieatsgreedy** [comment]
> Yeah, that helps!
> 
> Also, if you could--please edit your issue to have a descriptive title, what version of Seren and Kodi you are using, and if you could, attach a log using the steps provided here: https://kodi.wiki/view/Log_file/Easy

so i tried this method and can't pull the script - 

additional information i can give- 

my other seren on my other apple tv works fine ( i did not do the update on that one)

kodi version 19.0 is the version i am currently running.

**Comment by drinfernoo** [comment]
You need to attach a log file.
