### ISSUE TITLE
Possible to add the same internal database for meta info and images as Realizer

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#59]
The clear logos in Realzer load super fast for skins.

the dev has explained how he has done this.

is this possible to implement in Seren at some point as an option in the settings we can enable?

this would really help for titan and the nextflix skin and others as the logos load instant.

https://www.reddit.com/r/Addons4Kodi/comments/asgvij/fanarttv_faster_loading_clear_logos/egvc8uv/?context=3

**Comment by nixgates** [comment]
This information is already cached and refreshed every 24 hours.

Unfortunately further caching will provide neglible to no speed/increase
