### ISSUE TITLE
Seren Error. Playback failed. One ore more items failed to play. 

### ISSUE THREAD

**Issue by luckylukz02** [nixgates/plugin.video.seren#598]
I am using Kodi 19 RC1 on Libreelec. I have little choice in changing from RC1 at the moment as it is a community build for HDR on Intel NUC.

I cannot get past this error on Seren. It finds links but does not display them and errors out.

Log:
https://1drv.ms/u/s!AijkxtpRkyJMg750jvbUcWwN4BgfLg?e=50QeVA

https://paste.kodi.tv/umipepuzag.kodi

**Comment by drinfernoo** [comment]
Kodi 19 supports HDR. There is a known bug with RC1, which is also quite old. Unless there is something specific about LE that prevents it, I'd suggest updating.

**Comment by luckylukz02** [comment]
Libreelec 9 does not support HDR on Kodi 19 as of yet.

https://forum.libreelec.tv/thread/13738-intel-true-10bits-hevc-hdr-support/?pageNo=32

I have tried Libreelec 10 (Kodi 20-ALPHA1) although Seren works fine i have issues with other addons.

At the moment the choice for me is only Kodi 19-RC1 or Kodi 20-ALPHA1

Thanks

**Comment by drinfernoo** [comment]
From the LE main page, it appears that LE10 is Kodi Matrix 19... Kodi 20 is not really even on the horizon for awhile yet.

**Comment by luckylukz02** [comment]
Yes sorry for the confusion. HDR is in development for Libreelec 11 (Kodi 20)
