### ISSUE TITLE
Option to hide SD items

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#60]
As suggested in the Reddit comment.

Raising a GitHub issue for this to be implemented.

**Comment by icpryde** [comment]
Already exists, it’s in setting to turn off low quality links.

**Comment by lukehansford** [comment]
Have confirmed with the Dev before I posted this here.

The setting to turn off low quality links is from cams from mostly hosters and such and does not hide SD quality links. 

He said it can be added as a feature which is why I opened this issue.

**Comment by nixgates** [comment]
This has been added for 0.1.36
Please let me know if it doesn't work

**Comment by Lisa-Williams** [comment]
You can hack this now until v0.1.36 is released where it will be an option. Look here [https://www.reddit.com/r/Addons4Kodi/comments/a2ftnp/seren_support_megathread/ei68hux/?context=8&depth=9](https://www.reddit.com/r/Addons4Kodi/comments/a2ftnp/seren_support_megathread/ei68hux/?context=8&depth=9)

**Comment by ruegnueg** [comment]
just use the pre-emptive termination settings. they are long time available

**Comment by Lisa-Williams** [comment]
> just use the pre-emptive termination settings. they are long time available

I wonder what will happen if there are only SD quality links.

**Comment by nixgates** [comment]
Added in update 0.2.0
