### ISSUE TITLE
[REQUEST]Search Movies & TV Shows History

### ISSUE THREAD

**Issue by onlytanmoy** [nixgates/plugin.video.seren#600]
Hiya, in the Search section of the addon please include the below two
a. Search Movies History
b. Search TV Shows History
That way it will keep a record of my previous searches and I can just press it to scrape again without having to type the entire search string all over again.

**Comment by Goldenfreddy0703** [comment]
Umm..... @onlytanmoy,if you did not notice, there is an option that says Enable Search History in the addon settings.
![Search](https://user-images.githubusercontent.com/62456796/114948548-324bca00-9e1d-11eb-87e4-7785409965c8.PNG)
An enhancement i would like is icons for seren.

**Comment by onlytanmoy** [comment]
@Goldenfreddy0703 oops, my bad. Thanks for the pointer mate 👍

**Comment by Goldenfreddy0703** [comment]
Anytime
