### ISSUE TITLE
no player

### ISSUE THREAD

**Issue by Crazyshakespeare** [nixgates/plugin.video.seren#601]
I have seren 2.0.18 running successfully in kodi 19 but have notice that no player shows up in kodi. The addon seems to be working fine except the player seems to be missing. I tried to set seren as the default both in kodi and themoviedb helper but it doesnt even show up as an option....i have uninstalled and reinstalled, no luck....any ideas?

**Comment by drinfernoo** [comment]
Install players for TMDbHelper... Those aren't maintained (or supported) here, by the developer of TMDbHelper, or by Kodi though.
