### ISSUE TITLE
Firestick 4k and Playback

### ISSUE THREAD

**Issue by aceywacey** [nixgates/plugin.video.seren#602]
**Logs**
[Log](https://paste.kodi.tv/elifiwuzeb)

**Describe the bug**
When I select a video on my Firestick 

**To Reproduce**
1. Select any video, I use Trending as I want something with a lot of sources.
2. Kodi hangs on the episode list
3. Force close Kodi to use it again.

**Expected behavior**
I expect the video to play

**Kodi Version (please complete the following information):**
 - Kodi Version 19.0rc1
 - Firestick OS 6.8.2.0

**Comment by drinfernoo** [comment]
Kodi generates a log file on boot, and writes to it continuously. We'll need to see that log to diagnose.

**Comment by aceywacey** [comment]
I have updated my original comment with the log file before the crash

**Comment by drinfernoo** [comment]
Clear Seren's cache and torrent cache and try again.

**Comment by aceywacey** [comment]
I did that and it was the same result. I have also in the past uninstalled Kodi and reinstalled it. That did not make a difference either. The other addon I use plays the videos no problem, but I prefer to use yours.

**Comment by drinfernoo** [comment]
Actually, I'd recommend updating to Kodi 19.0 Stable. There are known issues with RC1, and it's a few months old at this point.

**Comment by aceywacey** [comment]
That did it thank you, I must have been using a beta build that was recommended for my Firestick. I've gone to the release build now.
