### ISSUE TITLE
[BUG] new update database error

### ISSUE THREAD

**Issue by Jaavv** [nixgates/plugin.video.seren#603]
**Logs**
[https://paste.kodi.tv/qahezagica.kodi](https://paste.kodi.tv/qahezagica.kodi)

**Describe the bug**
Seren is broken after the latest update

**Kodi Version (please complete the following information):**
 - Kodi Version 19 (Nvidia Shield)
 - plugin.video.seren 2.0.19+matrix.1

**Additional context**
Cleared cache, resynced trakt etc... didnt fix it

**Comment by drinfernoo** [comment]
Full log please.
