### ISSUE TITLE
[BUG] Trakt Watchlist not updating

### ISSUE THREAD

**Issue by hockeymachine86** [nixgates/plugin.video.seren#605]
**Logs**

link:  [https://paste.kodi.tv/ufijucayip.kodi](https://paste.kodi.tv/ufijucayip.kodi)

**Describe the bug**
Added movies to Trakt watchlist and it won't show up in Seren Trakt Watchlist.  For movies that wont show up in the watchlist that I have in Trakt; when I search for the movie in Seren and find it and go to "Trakt Manager" as a part of Seren context menu, it gives me an error (see in log)

**To Reproduce**
1. Go to Seren
2. Click on Search
3. Search Movies
4. Search for movie (.e.g F9)
5. Context Menu "Trakt Manager"
6. Get error

**Expected behavior**
Trakt manager menu comes up.  Watchlist contains movies in Trakt Watchlist

**Kodi Version (please complete the following information):**
 - Kodi Version 19.0

**Comment by drinfernoo** [comment]
Is this still an issue in 2.1.0?

**Comment by hockeymachine86** [comment]
Issue is still there on 2.1.1
Updated log: [https://paste.kodi.tv/walazexudu.kodi](https://paste.kodi.tv/walazexudu.kodi)

**Comment by drinfernoo** [comment]
I can confirm this has been fixed in dev... should be working in the next update :+1:

**Comment by drinfernoo** [comment]
This one should be fixed as of 2.1.2.

**Comment by hockeymachine86** [comment]
Fixed (I think in 2.1.2). It let's me add them to the watchlist but the watchlist won't update with what is added even thought trakt site updates.

**Comment by hockeymachine86** [comment]
Fixed in 2.1.2
