### ISSUE TITLE
Update from v2.0.18 to v2.0.19 on Kodi 18.9 generates error

### ISSUE THREAD

**Issue by nchauley** [nixgates/plugin.video.seren#606]
Greetings. After exhausting all attempts to troubleshoot this issue, I am seeking assistance for resolution (if possible):

Hardware: Nvidia Shield, Android 9
Kodi version 18.9
Kodi Skin: Aeon Tajo (based on Aeon Nox 5)

Synopsis:
After auto-update from v2.0.18 to v2.0.19, Kodi immediately threw error "Seren error check log" - error from log pasted below.
Note: Seren error is also generated immediately upon starting Kodi even before add-on is selected.
Seren settings can be accessed however any attempt to select ANY setting item e.g. Shortcuts to clear cache, wipe add-on data etc. immediately errors out so cannot clear cache or wipe add-on data within settings.
Uninstalled add-on, cleared Kodi & Nvidia cache, reinstalled add-on from repository but same error.
Changed skin to Kodi default Estuary and reinstalled - same error.

Reinstalled v2.0.18 with NO errors, all is well! Have turned off auto update.

Rather than posting entire Kodi log, here is the python error/exception thrown specific to Seren. Let me know if you need entire log:

2021-04-27 16:05:59.572 T:11249   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named urllib.parse
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/service.py", line 11, in <module>
                                                from resources.lib.common import tools
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.seren/resources/lib/common/tools.py", line 33, in <module>
                                                from future.backports.urllib.parse import (
                                            ImportError: No module named urllib.parse
                                            -->End of Python script error report<--

I also tested v2.0.19 on Kodi 19.0 (Matrix) on another box, works well, no errors however I'm not ready to migrate to Matrix just yet due to other add-on compatibility issues. Not really urgent since v2.0.18 is stable however if there is a simple fix then great but if not, I'll just wait for next version or until Matrix is a bit more stable.

Kudos to all that continue to enhance this add-on - it is fast, efficient and stable!
 
Many thanks...

**Comment by drinfernoo** [comment]
Can you attach a full log?

**Comment by nchauley** [comment]
Full log attached:
[kodi.old.log](https://github.com/nixgates/plugin.video.seren/files/6395301/kodi.old.log)

Thx again...

**Comment by drinfernoo** [comment]
Can you attempt to uninstall Seren (keep add-on data is fine), and then reinstall it from the repo?

**Comment by nchauley** [comment]
Howdy. As requested, uninstalled V2.0.18, updated Nixgates repo and reinstalled v2.0.19 - same symptoms i.e. Kodi immediately threw error "Seren error check log". Kodi log attached.
Thx again for your assistance with this however please do move on to other pressing issues if this error eludes you primarily because v2.0.18 works and v2.0.19 is stable and error free on Kodi 19.
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6412481/kodi.log)

**Comment by Sobersally** [comment]
I am having the same problem. I have uninstalled Seren, did a complete reinstall. I did a resync with traktv, I cleared the sync and resynced. I have done everything I can imagine and it still gives error message. 
here is my log
https://paste.kodi.tv/ijituzozub
Any suggestions would be awesome. I am not ready to update to Kodi V19 due to so many of my addons that won't work yet. Maybe a older version of Seren would work for me. 
Thanks

**Comment by Sobersally** [comment]
Something updated in my kodi with Seren and now it's working. Sorry for the confusion

**Comment by nchauley** [comment]
Sobersally,
 If possible, can you have a look at your "Recently Updated Addons" under Addons list in Kodi and see what was updated prior to Seren v2.0.19 working in Kodi 18.9? This will help me (and drinferno) determine cause of problem. 
Thx for you assistance!

**Comment by nchauley** [comment]
Update: 
Clean install of Kodi 18.9 resolves this issue:
* Deleted Kodi 18.9, installed Seren v2.0.19 from repo
* Installed Aeon Tajo skin
* No other add-ons installed

No error generated.

I can only speculate that there may have been a conflict with other installed add-ons or that my installed version of Kodi 18.9 was corrupted. I have noticed that some add-ons install modified versions of dependencies. My recommendation to others that experience this error is to perform a clean install of Kodi 18.9 and then install other add-ons one at a time, check Seren after each add-on install to determine if there is a conflict.

DrInferno - closing this issue. My sincere apologies for your troubleshooting effort and thx for your assistance!
