### ISSUE TITLE
[Request] Make "My Show Lists" include lists containing only "Episodes" or "Seasons" too

### ISSUE THREAD

**Issue by titelheld** [nixgates/plugin.video.seren#608]
**Describe the bug**

The "My Show Lists" folder only shows lists that contain actual "Shows" it does not show any list containing only "Episodes".

I have a lot of lists that contain only key "Episodes" from tv shows. e.g. Stargate SG-1 main story arch, Star Trek Borg related episodes, X-Files main story arch etc. these list do not show in "My Show Lists"

e.g. This list does not show up under "My Show Lists" as it ONLY contains episodes: 
https://trakt.tv/users/amazing-journey/lists/stargate-sg-1-key-episodes

It took me a while to figure out that those lists under "My Show Lists" MUST contain actual "shows" to show up. 

I think it was a good idea to filter Trakt lists by show/movie contents so that we can have two lists for "My Show Lists" and "My Movie Lists" but the fact that list containing ONLY episodes are filtered out and not showing under "My Show Lists" must be an oversight... 
At the moment the criteria for "My Show Lists" seems to be MUST include "Show"...

**Please make it so that list containing ONLY "Episodes" also show up in the "My Show Lists" folder. 

i.e. set the criteria for "My Show Lists" to MUST include "Show" OR "Episode" instead of only "MUST include "Show""**

- EXAMPLE OF "SHOW" AND "EPISODE"
- "Show" >>> https://trakt.tv/shows/stargate-sg-1
- "Episode" >>> https://trakt.tv/shows/stargate-sg-1/seasons/1/episodes/1

**To Reproduce**

1. Create a Trakt list containing only episodes
2. go to "My Show Lists" folder 
3. the Trakt list with only episodes won't show
4. now add a tv "show" to the same folder
5. go to"My Show Lists" folder
6. the list now shows up but only contains the "show" not the individual episodes added under "1."

**Expected behavior**

"My Show Lists" folder should also list lists that contain ONLY episodes. 

**Kodi Version (please complete the following information):**
 - Kodi Version [19.0rc1]
 - SEREN Version [2.0.19+matrix.1]

**Comment by drinfernoo** [comment]
My **Show** Lists.

**Comment by titelheld** [comment]
> My **Show** Lists.

I am aware that it is called "My Show Lists" but condensed shows should also be in this list i.e. list containgin only select "Episodes" from a "Show".

Adding a "My Episodes Lists" would seem odd wouldn't it?

**Comment by titelheld** [comment]
Either way it would be very welcome if this would be added in the next update as the is currently no way to list personal list containing only episodes.

And may I add that an exclusive list for only "Episodes" would pose the problem that it wouldn't list "Shows".

Perhaps a new section in the main menu of Seren named "My Lists" might be a good addition at this point.

**Comment by titelheld** [comment]
Changed to [Request] Make "My Show Lists" include lists containing only "Episodes" or "Seasons"

Because I believe the "My Show Lists" section should include all list related to TV Shows, regardless if the contain only "Episodes", "Seasons" or "Shows".

Adding multiple sections for "My Episodes Lists", "My Seasons Lists" and "My Show Lists" would make the interface feel cluttered and there is no need to sub-devide list relating to TV shows in this way.
