### ISSUE TITLE
Seren Stuck on Starting Link Resolver

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#61]
Seren gets stuck on Starting link Resolver after cancelling out of Source select screen.

This is happening on Kodi 17.3 on an older Android dual boot libraelec that has no update available.

**Comment by icpryde** [comment]
Seren isn’t designed to work with older builds, it’s essentially designed for 17.9 and up. You should either upgrade as things will only continue to get worse for you or don’t use newer addons.

**Comment by lukehansford** [comment]
The Dev has said on Reddit to another poster with the same issue who first mentioned it that he is looking into this.

**Comment by nixgates** [comment]
@lukehansford 
Can you please provide a log

**Comment by lukehansford** [comment]
It scrapes fine but it you press back to exit out of the scraper list it will freeze up Kodi at a screen with "Starting Link Resolver"

I don't think I can do a log on libraelec.

The issue was posted on addons4kodi by another user first.

**Comment by SerpentDrago** [comment]
17.6 and up , have all been tested exhaustively , to make sure you can back out of a scrape . at this time if you are having issues , we need a log . Please google how to provide a log or else no one will be able to help you . thanks

**Comment by nixgates** [comment]
@lukehansford can you please provide a log

To be brutally honest, Seren is only developed for 17.6 and further. If it's a backwards compatibility issue and can't be resolved easily it will have to noted as an incompatibility.
