### ISSUE TITLE
[BUG]Not playing anything while VPN is off

### ISSUE THREAD

**Issue by nived0999** [nixgates/plugin.video.seren#610]
**Logs**

https://paste.kodi.tv/mayosipizo

**Describe the bug**
If i tried to play anything when the VPN is off it shows seren error...but if the VPN is on seren works without anu problem..the log file when trying to play anything while VPN on is given..i tried clearing cache and re-authorizing

**To Reproduce**
1. Go to 'any movies ir series'
2. Click on 'play'
3. See error

**Kodi Version (please complete the following information):**
 - Kodi Version [19 matrix]

**Comment by s0ulslack** [comment]
This doesn't sound like a Seren issue but one with your ISP blocking content, if it was a Seren error it wouldn't play either way. Please make sure you know the difference between a bug and and error.

**Comment by drinfernoo** [comment]
Agreed, this doesn't sound like a Seren issue at all. Seren doesn't care about your VPN in any way.
