### ISSUE TITLE
[REQUEST] next episode prefer current season pack?

### ISSUE THREAD

**Issue by henryjfry** [nixgates/plugin.video.seren#611]
I had a thought that it might be a useful feature in seren to try and get the next episode for a show from the season pack the current episode is playing from?

For example if you manually scrape an episode and select an item which isn't the one smart play would select by default, the following episode could be from the same season pack if you have enabled a setting in the options?

This way if there is a problem with the default season pack seren might select it could still smart play the users preferred option?

I know you cache links and such so I think it would be something that you could implement using that data. But I'm not sure how difficult it would be as I haven't looked at your link cache code too much myself.

I've recently been watching a show and there are a particular batch of episodes which appear to have encoding issues.
So it would be useful if when I rescrape that my manual selection is somewhat persistent.

**Comment by drinfernoo** [comment]
We do have this referenced in an internal issue, so it may come eventually.

**Comment by tundrablasen** [comment]
I like that feature

**Comment by drinfernoo** [comment]
We have this mostly implemented in development, so it should be available whenever Seren gets another update :+1:

**Comment by drinfernoo** [comment]
This should be implemented now, by enabling "Prioritize the Last Resolved Show Name" in settings 👍
