### ISSUE TITLE
[BUG] "Seren Error - Check log for more info" - Happens when searching for tv shows and starting playback of movies from a clean install.

### ISSUE THREAD

**Issue by SebbeJohansson** [nixgates/plugin.video.seren#612]
**Logs**
Searching for tv show - https://pastebin.com/raw/hmHE83ke
Starting media - https://pastebin.com/raw/22wXyfWd

**Describe the bug**
"Seren Error" appears when doing either of actions and no playback or result is provided.

**To Reproduce**
Steps to reproduce the movie playback issue:
1. Go to 'Search for movie'
2. Search for a movie.
3. Select movie
4. Look for sources.
5. See error.

Steps to reproduce the search tv show issue:
1. Go to 'Search for tv show'.
2. Search for a tv show.
3. See error.

**Expected behavior**
I expect the selected source to play.

**Kodi Version (please complete the following information):**
 - Kodi Version 19.1
 - Seren Version 2.0.19+matrix.1

**Comment by drinfernoo** [comment]
Is this still an issue in 2.1.0?
