### ISSUE TITLE
Thumbnails with clear art

### ISSUE THREAD

**Issue by derrgoo** [nixgates/plugin.video.seren#613]
Just wondering why seren thumbnails are not showing evenly. Sometimes the picture is too off compared to other add ons. The clear art works great just the picture doesn't seem to want to line up in widgets. Nkt sure how to classify.

**Comment by drinfernoo** [comment]
Maybe some screenshots or more information? There are issue templates for a reason 🤦🏽‍♂️

**Comment by derrgoo** [comment]
I don't know how much detail I can give when reporting thumbnails but yes pictures below. Thanks for reminding me. 

These two are from Seren

![image](https://user-images.githubusercontent.com/63697905/118986234-5ca71f00-b9a9-11eb-85cc-41be4bf755eb.jpeg)

![image](https://user-images.githubusercontent.com/63697905/118986254-62046980-b9a9-11eb-98af-327e5762e095.jpeg)

From another addon 

![image](https://user-images.githubusercontent.com/63697905/118986292-6b8dd180-b9a9-11eb-9aff-b48e4eef2fcf.jpeg)

**Comment by drinfernoo** [comment]
Are you talking about the image being a bit cropped for "Kung Fu"? The one for "The Resident" is obviously a different image entirely, but "Big Sky" and "Shark Tank" look exactly same to me, but "Shark Tank" doesn't have a clearlogo in either of Seren's screenshots.

**Comment by derrgoo** [comment]
Yes- You can see that Seren are not fitting in the widget properly. Kung fu is a good example of how they often look. They are cut off so this is what I am wondering if it can be fixed so they fit properly like the other add on?

**Comment by drinfernoo** [comment]
So this doesn't really have anything to do with clearlogo then 😅

The thumbnails are just whatever artwork is returned by the artwork service 🤷🏼‍♀️ If the service returns artwork that doesn't fit the box, there's not really anything that can be done about that.

**Comment by derrgoo** [comment]
Understood thanks
