### ISSUE TITLE
[REQUEST]Use regional ratings instead of US MPAA

### ISSUE THREAD

**Issue by adamosborne83** [nixgates/plugin.video.seren#614]
Just wondering if the above would be possible?

I am from the UK, and was wondering if it would be possible to have the rating pulled from UK,

For example
18,15,12A,12,

Cheers

**Comment by drinfernoo** [comment]
Ratings in Seren are provided by Trakt, which only provides them in the MPAA format. As far as I know, there isn't any metadata provider that provides them differently.
