### ISSUE TITLE
[BUG] File Size Limit filter removes all hosters 

### ISSUE THREAD

**Issue by lowersublobia** [nixgates/plugin.video.seren#616]
Super simple bug no need for a log, 

If any file size filters are set on Seren , then all hoster links will be filtered out. I think it has something to do with the hoster file size showing 0.0 as opposed to 0.0 ‘GB’ . 

Considering the minimum filesize is 0.0 GB , I believe Seren has an issue with hosters since they’re filesizes doesn’t include ‘GB’ , just the number which is almost always 0.0. 

Kodi version 18.9

**Comment by drinfernoo** [comment]
Set your minimum file size to 0, or disable holsters, basically. Unfortunately, they just don't return a file size in order to use as a reliable filtering method.

**Comment by lowersublobia** [comment]
?? I don’t mean to come off as rude but how is the issue closed lol ?

I have set the minimum filesize to 0 as I said before , but because hosters don’t put ‘’GB’’ beside their filesize, which is almost always 0, Seren just filters them out.
I don’t want to disable hosters, I’d like to keep them in unison with my filters.

**Comment by drinfernoo** [comment]
I may have misunderstood. We'll keep it open for now.

**Comment by drinfernoo** [comment]
We've actually identified this as a legitimate bug in development 👍

**Comment by drinfernoo** [comment]
This should now be fixed in 2.1.1.

**Comment by lowersublobia** [comment]
Awesome !!
