### ISSUE TITLE
[BUG] RD expiration after reauthorization

### ISSUE THREAD

**Issue by TheDiggler** [nixgates/plugin.video.seren#619]
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6642664/kodi.log)

After updating to Seren 2.1.0 yesterday everything appeared to work but all of the sudden started getting RD expired errors.  I cleared Seren cache and reauth RD but after a few scrapes I start get RD expired.  The log above is from Seren errors after I uninstalled, deleted all Seren folder and reinstalled/auth RD.

**Comment by JacopoV** [comment]
+1 here. Every 2/3 scraping, RD needs to be reauthorization

**Comment by sinanawad** [comment]
+1, seems most people on the subreddit are facing the same issue since the update.

**Comment by Logs22** [comment]
I'll throw my log in too, http://paste.kodi.tv/enuboxecij

Never hurts to have more than 1

**Comment by YaYaTurre** [comment]
same

**Comment by cgcgcgcgcg** [comment]
I had expiry notification disabled in Seren settings before latest update and still no issue after updating.

**Comment by TheDiggler** [comment]
> I had expiry notifications disabled in Seren settings before latest update and still no issue after updating.
> ![ksnip_20210613-014136](https://user-images.githubusercontent.com/38960370/121790511-b1c10400-cbe8-11eb-973e-e7c52f1fec95.png)

I just tried it, turned notifications off and reauth RD.  Worked for 2 scrapes but on the the 3rd it can't find any links for anything.

**Comment by talondnb** [comment]
> > I had expiry notifications disabled in Seren settings before latest update and still no issue after updating.
> > ![ksnip_20210613-014136](https://user-images.githubusercontent.com/38960370/121790511-b1c10400-cbe8-11eb-973e-e7c52f1fec95.png)
> 
> I just tried it, turned notifications off and reauth RD. Worked for 2 scrapes but on the the 3rd it can't find any links for anything.

Same issue here, turned it off but still broke.

**Comment by Syrah-NL** [comment]
Same issue here. Also, turning off notifications doesn't work either (not only does it not find any links, it also keeps spamming the notification)

**Comment by cgcgcgcgcg** [comment]
A friend with this issue went to Seren settings > Accounts, clicked on the Defaults button, and reauthorized RD & Trakt, and the pop up vanished.

**Comment by talondnb** [comment]
> A friend with this issue went to Seren settings > Accounts, clicked on the Defaults button, and reauthorized RD & Trakt, and the pop up vanished.

For how long? As above, most of us have reauthed fine but the error pops up again after a few.

**Comment by SUroot** [comment]
@drinfernoo referred to this issue in a previous issue, so I'm just putting my name down here too. Same issue on latest Seren on Kodi 18.9

Re Auth works temporarily. Enough to scrape and watch. Luckily I also have alldebrid running no issues

**Comment by bolemo** [comment]
Same issue here since two or three days, v2.1.
Tried deleting token from real-debrid then reauthorizing, restarted, reinstalled same version, etc… no luck.

**Comment by Chucknorris1975** [comment]
Running Kodi 19.1 on an  Android box. Have tried every fix put on the subreddit but issue still remains.

**Comment by SUroot** [comment]
> Running Kodi 19.1 on an Android box. Have tried every fix put on the subreddit but issue still remains.

@Chucknorris1975 I'm running Kodi 18.9 on an android box. I find if I re-auth realdebrid then force close Kodi itself, when I reload it and check, realdebrid states it's premium and works for a little while. It's a long winded work around but it works for me temporarily.

**Comment by Madddcow** [comment]
Same experience here and it only started yesterday or the day before.  Forcing an update to Seren fixes it temporarily but the issue keeps coming back. Kodi 18.9 on FireTV 2nd gen.

**Comment by bcg33478** [comment]
Ditto!

**Comment by sym0nd0** [comment]
Same, on two devices.

**Comment by drinfernoo** [comment]
Ok everyone, a fix is being worked on. We've had enough confirmations to know that it's an issue, and it is replicable, so a fix should be incoming hopefully soon.

**Comment by TheDiggler** [comment]
> Ok everyone, a fix is being worked on. We've had enough confirmations to know that it's an issue, and it is replicable, so a fix should be incoming hopefully soon.

That's great!  Thanks!

**Comment by SUroot** [comment]
> Ok everyone, a fix is being worked on. We've had enough confirmations to know that it's an issue, and it is replicable, so a fix should be incoming hopefully soon.

Is there a beta repo for testing? Happy to test of needs be.

**Comment by drinfernoo** [comment]
@SUroot No, there isn't. It's a closed testing group.

**Comment by JacopoV** [comment]
Thanks @drinfernoo!

**Comment by pbengt** [comment]
Thank you Diggler, at least I know it’s being addressed as I tried everything because Seren is favorite. Using 19.1 and have all the previous listed expired problems.

**Comment by CaptainSweatpants** [comment]
> Thank you Diggler, at least I know it’s being addressed as I tried everything because Seren is favorite. Using 19.1 on Shield and have all the previous listed expired problems.

Yeah I’m in the same boat. 19.1 on a ShieldTV pro. No “fixes” or workarounds work for me either. Kodi/SEREN is pretty dead for me until this is resolved. Glad its been acknowledged and is being worked on though. Hopefully we get a fix soon.

**Comment by Syrah-NL** [comment]
You can still use Wako on your phone to select the videos you want to play. If you have Wako connected to your RD it will find all the HQ sources. That's what I'm using until this is resolved.

**Comment by npmstart-pray** [comment]
I'd be particularly happy if Seren were to integrate Orion automatically: I'm of a mind the RD Auth issues would largely evaporate.
There are details on their Developers page [https://panel.orionoid.com/](url)

**Comment by drinfernoo** [comment]
@npmstart-pray RD authorization would still be needed to resolve the links provided by Orion... so I don't think that would be the silver bullet you think it would.

**Comment by npmstart-pray** [comment]
for those of us who already subscribe to RD and Orion, it might be just
fine.

**Comment by drinfernoo** [comment]
@npmstart-pray Have you tried it? Orion does not resolve links, so I, again, imagine it wouldn't work the way you think it would.

**Comment by Plasmadog** [comment]
Is it just me, or has anyone else noticed Trakt authorization is also expiring regularly since the 2.1.0 update? Is there any chance the proposed fix might address this?

**Comment by SUroot** [comment]
> Is it just me, or has anyone else noticed Trakt authorization is also expiring regularly since the 2.1.0 update? Is there any chance the proposed fix might address this?

My trakt is working fine tbh. Just RD for me. Though I'm on Kodi 18.9 on Android Shield TV

**Comment by Madddcow** [comment]
I’ve been having issues with Trakt and Seren for a loooooong time i.e. they’ll sync fine for awhile but then suddenly I’ll realise it hasn’t been syncing for the past week or two.

**Comment by sinanawad** [comment]
Right???? I thought it was me.. I need to force sync all the time.

**Comment by talondnb** [comment]
Rolled back to 2.0.19 for now so I’m good for the weekend until a fix comes out. 👍🏼

**Comment by Chucknorris1975** [comment]
> Rolled back to 2.0.19 for now so I’m good for the weekend until a fix comes out. 👍🏼

How does one go about doing that?

**Comment by talondnb** [comment]
Firstly, be aware that there is no support on previous versions.

- Go to https://github.com/nixgates/nixgates and grab the previous version for your version of Kodi, copy to your kodi instance via SMB
- Uninstall Seren and reboot kodi
- Install from zip the file you downloaded
- It will be a fresh install so proceed to treat it as such and configure t suit

I also disabled auto-updates on the rolled back version until I get notified from this thread that a fix is out then I’ll simply upgrade via the latest repo.

**Comment by TeslaObsucra** [comment]
> Firstly, be aware that there is no support on previous versions.
> 
>     * Go to https://github.com/nixgates/nixgates and grab the previous version for your version of Kodi, copy the zip to your kodi instance via SMB (e.g. Downloads folder)
> 
>     * Uninstall Seren and reboot kodi
> 
>     * Install from zip the file you downloaded
> 
>     * It will be a fresh install so proceed to treat it as such and configure to suit
> 
> 
> I’ve also disabled auto-updates on the rolled back version until I get notified from this thread that a fix is out then I’ll simply upgrade via the latest repo.

Talon,  I do not see previous versions of Seren available at this location.  I only see th most recent.   Is there another trusted link for the zip?

**Comment by drinfernoo** [comment]
This should now be fixed in 2.1.1.

**Comment by talondnb** [comment]
> > Firstly, be aware that there is no support on previous versions.
> > ```
> > * Go to https://github.com/nixgates/nixgates and grab the previous version for your version of Kodi, copy the zip to your kodi instance via SMB (e.g. Downloads folder)
> > 
> > * Uninstall Seren and reboot kodi
> > 
> > * Install from zip the file you downloaded
> > 
> > * It will be a fresh install so proceed to treat it as such and configure to suit
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I’ve also disabled auto-updates on the rolled back version until I get notified from this thread that a fix is out then I’ll simply upgrade via the latest repo.
> 
> Talon, I do not see previous versions of Seren available at this location. I only see th most recent. Is there another trusted link for the zip?

Not sure what you mean, they’re all listed as that is the archive of previous versions. Anyway the issue looks to have been patched as per last post. And I don’t get why my workaround was downvoted so I’ve deleted my posts.

**Comment by cphilpotts** [comment]
> This should now be fixed in 2.1.1.

This new update now won’t let me authorize RD at all. RD accepts the code but the screen in seren just stays on the code.

**Comment by cphilpotts** [comment]
> > This should now be fixed in 2.1.1.
> 
> This new update now won’t let me authorize RD at all. RD accepts the code but the screen in seren just stays on the code.

Here’s my log 

https://paste.kodi.tv/alidosasuf

**Comment by Madddcow** [comment]
I found the same thing EXCEPT that after exiting/restarting Kodi, I did the authorisation and whilst the same thing happened (i.e. the Seren authorisation staying onscreen), at some point the authorisation “stuck”. 

However, I’m just trying to watch a show right now and Seren just keeps producing errors and won’t play anything at all…..

**Comment by Madddcow** [comment]
Movies seem to play fine but TV shows won’t play at all.

**Comment by staza** [comment]
I did not reauthorize my RD account since Seren, after the update, kept the previous authorization. Now the account stays as premium in Seren but after a couple of episodes it looses communication with RD (no playable sources, error connecting to my files in rd, error connecting to RD premium services etc.) still indicating premium though, in accounts. When i restart kodi the circle starts over again (latest windows 10 with latest updates and latest kodi). Actually it is the same as before only now the account stays premium while before it was changing to expired. I don't think it is an authorization problem as with every restart seren works fine for a couple of hours.
I hope this helps.

**Comment by SUroot** [comment]
I took the update and everything seemed fine for a few hours. Then I started getting the expired notification again

**Comment by Chucknorris1975** [comment]
Same. What I found was to completely delete Seren and reinstall it from the repository, then set it up as normal. So far it seems to have fixed my issues.

**Comment by SUroot** [comment]
> Same. What I found was to completely delete Seren and reinstall it from the repository, then set it up as normal. So far it seems to have fixed my issues.

Cool. I'll give that a go when I have a little time.

**Comment by Madddcow** [comment]
I ended up having to completely uninstall Seren (and its config files) and then install/configure from scratch. 

However, my preferences keep being reset to default (including losing my Trakt, Real-Debrid and All Debrid authorisations)….and this is a real pain in the ass. Anyone know how I can stop this from happening?
