### ISSUE TITLE
Default Select action setting - openinfo

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#62]
Is it possible we can get a setting to change the default select action from play to Openinfo so we can have the new Openinfo be opened by default when we select a movie or show in Seren.

You can set the default select action under Kodi settings but then this affects all your addons and not all are supported by openmeta/Openinfo.

**Comment by SerpentDrago** [comment]
Just link a widget or directly use openmeta / openinfo

**Comment by drinfernoo** [comment]
That is way outside the scope of Seren.

**Comment by nixgates** [comment]
Apologies, I agree that this is outside the scope of Seren. 

Please look at contacting your skin developer and requesting this from them.
