### ISSUE TITLE
[BUG] Real Debrid Auto Assist Caching not working with 2.1.0 Update

### ISSUE THREAD

**Issue by ameliegill1** [nixgates/plugin.video.seren#622]
**Logs**

Will provide when uploaded

**Describe the bug**

Since upgrading to 2.1.0, auto-caching a non-cached torrent using Real Debrid does not work and ends in No playable sources found and then Seren error.

**To Reproduce**

Play an episode with no cached torrents or hosters. See error.

**Expected behavior**

Caching with Real Debrid should occur and then episode played

**Screenshots**
N/A

**Kodi Version:**
 - Kodi Version 19.1
 - Seren Version 2.1.0

**Additional context**
N/A

**Comment by SoreTissue** [comment]
I thought I was having this issue too but on further inspection, for me anyway, it was only happening when my RD account was showing as expired ( #619 ). Once I cleared cache and/or restarted Kodi and my RD account was showing as Premium this issue went away.

In fact, what it was doing when RD showed as expired was finding torrents, but no cached torrents and activated the cache assist but then couldn't cache them. Once RD was showing as premium, it was finding already cached items.

Maybe this is what's happening for OP too.

**Comment by drinfernoo** [comment]
This should now be fixed in 2.1.1.
