### ISSUE TITLE
[REQUEST] Version rollback

### ISSUE THREAD

**Issue by talondnb** [nixgates/plugin.video.seren#624]
With the recent code push affecting RD integration it would have been nice to have a working version to roll back.

Typically in the addon settings there are other versions available to select to install but Seren seems to only overwrite previous versions.

**Comment by drinfernoo** [comment]
Only add-ons which maintain multiple versions in their repo offer that ability (and it still overwrites the currently installed version).

If you wish to rollback, you'll need to [download the zip](https://github.com/nixgates/nixgates) and install it manually, but understand that no support is offered to previous versions (hence why they are not as easily accessible).

The RD issue (#619) is being fixed, and a release will come soon that will solve it.

**Comment by talondnb** [comment]
> Only add-ons which maintain multiple versions in their repo offer that ability (and it still overwrites the currently installed version).
> 
> If you wish to rollback, you'll need to [download the zip](https://github.com/nixgates/nixgates) and install it manually, but understand that no support is offered to previous versions (hence why they are not as easily accessible).
> 
> The RD issue (#619) is being fixed, and a bugfix release will come soon that will solve it.

Rollback to 2.0.19 doesn't appear to work, I get this when attempting to install the last working file:

2021-06-16 16:17:02.080 T:9324    ERROR <general>: CAddonInstallJob[plugin.video.seren]: The dependency on xbmc.python version 2.26.0 could not be satisfied.

**Comment by drinfernoo** [comment]
That error is caused by trying to install the Leia version of the add-on.

**Comment by talondnb** [comment]
> That error is caused by trying to install the Leia version of the add-on.

It was this commit here: https://github.com/nixgates/plugin.video.seren/tree/2e526cbdb4d3fa12078bb76946c92af8704aa27d

**Comment by talondnb** [comment]
@drinfernoo, any other suggestion on how I can roll back?

**Comment by drinfernoo** [comment]
In my first reply, I sent a link that contains all of the existing archived version zips... Is that not enough?

**Comment by talondnb** [comment]
That link only has previous repos. I tried a few of the ones in the commit history but when browsing the downgraded repo, none showed video add-ons anymore. Am I approaching this wrongly?

**Comment by drinfernoo** [comment]
Ah, I've just realized that all the archived Matrix versions were removed... I'll restore them, but remember that there will be no support given for those versions.

**Comment by talondnb** [comment]
> Ah, I've just realized that all the archived Matrix versions were removed... I'll restore them, but remember that there will be no support given for those versions.
> 
> EDIT: Also, a bugfix release will be coming, like... _any_ time.

Thanks. And yes, I can appreciate there being no support on previous versions.

Also, I appreciate the bugfix coming but I feel I should be able to rollback to keep things going until then. I do recognise if this option was more readily available it would potentially create more work for you guys (which BTW is greatly appreciated).
