### ISSUE TITLE
[BUG]All seasons displaying marked as watched indicator.

### ISSUE THREAD

**Issue by Dealz-416LS** [nixgates/plugin.video.seren#625]
**Logs**
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6214773/kodi.log)

**Describe the bug**
All seasons of a show that hasn't been watched at all are displayed with the marked as watched indicator. (Issue happened in 18.9 and 19.0)

_NOTE:_ Tested with Trakt on TMDbHelper and had no issues, I wasn't able to replicate.

**To Reproduce**
Browse to the season of any unwatched show and all seasons will be displayed as watched.

**Expected behavior**
Browsing to the seasons view of an unwatched show should display the number of episodes for each season for skins that support it.

**Screenshots**
For both shows below, all seasons are marked as watched but I've not watched either show.
![Kodi_20210616_024803](https://user-images.githubusercontent.com/54026944/122152239-e509ca00-ce58-11eb-8eb2-266325003420.png)
![Kodi_20210616_024849](https://user-images.githubusercontent.com/54026944/122152248-e935e780-ce58-11eb-9f9b-e6b5b466c4eb.png)

After a Trakt Sync the issue is fixed as you can see all seasons now show episode count indicator.
![Kodi_20210616_025825](https://user-images.githubusercontent.com/54026944/122152351-0d91c400-ce59-11eb-9fcf-2379f7eb7980.png)

_NOTE_ Trakt Sync only applies to shows seasons that have been viewed prior to the Sync. 

**Kodi Version (please complete the following information):**
 - Kodi Version 19.1
 - Seren Version 2.1.0
 - Auramod Version 1.0.35

**Additional context**
[Comment](https://github.com/nixgates/plugin.video.seren/issues/563#issuecomment-861996410) by @drinfernoo 

I can reproduce "bug 1" in (#563)... in some instances. It appears to affect Seren when combined with AuraMOD. It doesn't present itself to me in two other skins (Estuary or Arctic Horizon), or in TMDbHelper... so for now I'm chalking it up to some interoperability issue between specifically AuraMOD and Seren.

If you would please open your issue again, specifically for "bug #1", that would be great. This would be in order to have something more directed to show to the developers of both Seren and AuraMOD, without the cruft of "bug 2" and "bug 3" getting in the way.

**Comment by drinfernoo** [comment]
Ok ,we've got this fixed in development... finally! It should be working correctly in the next update.

**Comment by drinfernoo** [comment]
This should now be fixed in 2.1.1.

**Comment by Dealz-416LS** [comment]
Confirming this issue is fixed, checked the seasons of several shows.
