### ISSUE TITLE
Seren  addon 

### ISSUE THREAD

**Issue by Greg0059** [nixgates/plugin.video.seren#629]
I have done a full clean of seren and kodi 19.1 matrix.  And clean and check for bugs in 4k Firestick and I did a power disconnection to my  device . And did went through and re did all my settings real debrid Trakt included.  And I play something clear all the cache files and went pack couple hours and all seren settings had been to default.  So it is a program error in the main repo and or in seren addon.

**Comment by drinfernoo** [comment]
Please follow the bug report template, provided all required information, or your issue is considered invalid.
