### ISSUE TITLE
[BUG]Trakt keeps dropping authorisation 

### ISSUE THREAD

**Issue by Chucknorris1975** [nixgates/plugin.video.seren#630]
**Describe the bug**
Running Matrix 19.1 on android box, Auramod, Seren 2.1.1. 

I've authorised RD and Trakt but Trakt will drop authorisation after 15 or so min and I'll get an error in Seren. When I fo into Accounts I notice that's Trakt is not authorised again.

**Comment by Mrtigger84** [comment]
Same here. Running 19.1 and 2.11. Had same issue with 2.10. Also all settings wipe back to factory, eg file size limit removed, autocache preferences back to alldebrid default.

Have done a full wipe and fresh reinstall with just basic settings. Anywhere from 10-30 minutes into watching stream just stops, cannot find any results for anything and all settings are default again. 

This happens across multiple boxes, various brands

**Comment by drinfernoo** [comment]
Please follow the bug report template, provided all required information, or your issue is considered invalid. Also please attach a debug log so we can further assist
