### ISSUE TITLE
[BUG]Trakt keeps deauthorising (error log included)

### ISSUE THREAD

**Issue by Chucknorris1975** [nixgates/plugin.video.seren#631]
**Describe the bug**
I keep getting a Seren error and that a log was created. When I check my Accounts, Trakt has authorization removed. I'll re authorize, and maybe 15 min later I will get the same error message and Trakt will again have authorization removed. RD has no issues.

**To Reproduce**
1. Start Kodi
2. See error
3. Reauthorize Trakt
4. Browse Movie list or TV show lists, or sometimes be in the middle of watching something when error comes back

**Expected behavior**
No errors

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 19.1 org.xbmc.kodi
 

**Additional context**
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6682343/kodi.log)

**Comment by confever** [comment]
not only trakt, but also real debrid too. using kodi 19.1 and latest seren from 2.0.2 repo

**Comment by deanwethers** [comment]
@Chucknorris1975 are all your accounts under the "accounts" tab getting reset after a while Or is it only trakt? I have a similar issue that just started yesterday but all of my accounts are getting wiped out and the menu is set back to default with RD and premiumize disabled and no trakt account after I play a few episodes

**Comment by Chucknorris1975** [comment]
Only Trakt. RD used to get reset before this last update, but doesn't now.

**Comment by drinfernoo** [comment]
@Chucknorris1975 Can you reproduce this with a clean install? If so, get a debug log. Trakt isn't deauthorized... it's getting an error 500, which happens when the server is down.

**Comment by Chucknorris1975** [comment]
> @Chucknorris1975 Can you reproduce this with a clean install? If so, get a debug log. Trakt isn't deauthorized... it's getting an error 500, which happens when the server is down.

Clean install as in uninstall and reinstall kodi and addons or just uninstall and reinstall addons only?

**Comment by drinfernoo** [comment]
Uninstall everything that isn't Kodi.

**Comment by Chucknorris1975** [comment]
Got it. Won't be until tomorrow sometime.

**Comment by Chucknorris1975** [comment]
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6708734/kodi.log)
Trakt and RD both seem to lose authorization.

**Comment by drinfernoo** [comment]
This should be fixed in 2.1.2.
