### ISSUE TITLE
Seren re-adds movies to Finish Watching after playback progress is cleared [BUG] 

### ISSUE THREAD

**Issue by ivarbrandt** [nixgates/plugin.video.seren#633]
I'm running Kodi 18.9 on a NVIDIA Shield TV Pro. 

I had 4 movies in the Finish Watching section whose playback progress I wanted to clear. I manually cleared the playback progress for them and initially, the movies were removed from the section. But then later then they came back as if I didn't clear the playback progress at all. The watched point in the movies was identical to where they were before I cleared the playback progress. At first I thought it was something else because I did it through a widget run by Autowidget. Then I tried the same thing through Seren's menus and the same behavior ensued.

There is quite a few Autowidget erros in the log. The Seren errors are near the bottom.

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6682696/kodi.log)

**Comment by maxpower742** [comment]
Can confirm I'm having the same issue.

**Comment by drinfernoo** [comment]
@ivarbrandt, would you open an issue for AutoWidget regarding those errors? I thought I had fixed that one in a recent update, but I must've missed something.

**Comment by drinfernoo** [comment]
@ivarbrandt How are you resetting progress? You should be doing it from the Seren-added `Trakt Manager -> Remove Playback Progress` context menu option.

**Comment by ivarbrandt** [comment]
Yes I'll open an issue for the AutoWidget errors.

That's exactly how I did it. I tried clearing the cache and it didn't work. It made it so that every time I tried to get back into the Finish watching section, Seren would throw an error. It wouldn't even open the finish watching folder. Finally I rebuilt the database and that fixed the error.
