### ISSUE TITLE
[UI] Source Select very small fonts in AuraMod Skin

### ISSUE THREAD

**Issue by Nuklear92** [nixgates/plugin.video.seren#637]
I installed recently AuraMod and automatically noticed that the fonts are super tiny in the Source Select window compared to Arctic Horizon and Arctic Zephyr 2 Skins. Is there a possibility of increasing the fonts just a bit more when used with this skin perhaps matching similar size as Arctic Horizon's look in the screenshot below;

**AuraMOD Skin Source Select font size**

![image](https://user-images.githubusercontent.com/76958541/123164933-91dbdc80-d441-11eb-8c9d-9fcc71bf1d73.png)

**Arctic Horizon Skin Source Select font size**

![image](https://user-images.githubusercontent.com/76958541/123165045-b9cb4000-d441-11eb-9e5c-bc1628882285.png)

It might not seem like a big deal when watching the screenshot but in actuality when viewing from a distance in the TV, font looks barely readable.

**Comment by drinfernoo** [comment]
This is why custom themes are supported. Not every skin defines the same size fonts, and it is *extremely* difficult to maintain a custom add-on window which supports multiple skins.

This is technically a skin issue, where AuraMOD would need to adjust the sizing of it's fonts to agree with other skins 🤷🏼‍♀️

**Comment by Nuklear92** [comment]
Oh, I understand. No worries then, thanks for the information. 🙂
