### ISSUE TITLE
[REQUEST] Context Menu option to delete torrents from Debrid Cloud

### ISSUE THREAD

**Issue by Nuklear92** [nixgates/plugin.video.seren#638]
Pretty much self explanatory, this is a little option Add-ons like **FEN** have had for quite a while when going into **My Services - Premium: Real-Debrid, Premium: Premiumize, etc.** as well in third party Apks like **Syncler - Debrid Manager** and I would like for Seren to adopt a similar option as well within **Context Menu**. An option for users to be able to press and hold to open **Context Menu** and have one or two options that says something like **Clear or Clean ALL** or **Select File/s and Delete from Cloud** within the Seren menu known as **My Files - Real-Debrid, Premiumize, etc**. Instead of users having to separately go into the proprietary Debrid website we use and manually having to do it from there, we could have an easy shortcut option through Seren via the **Context Menu** for use to keep our Debrid cloud clean from stuff we might had already watched, etc. 

### Here's the option within Syncler's Debrid Manager

![Syncler BETA_20210625_112651](https://user-images.githubusercontent.com/76958541/123450602-e8b0f580-d5aa-11eb-9f5f-bb27253224de.PNG)

### Here's the option within FEN Add-on when opening Context Menu while in My Services aka My Files in Seren

![Kodi_20210625_102625](https://user-images.githubusercontent.com/76958541/123450977-42b1bb00-d5ab-11eb-8352-f0a647c0a364.PNG)

### Lastly here's Seren Add-on while in My Files no options to clean out downloaded torrents

![Kodi_20210625_102848](https://user-images.githubusercontent.com/76958541/123451244-8c020a80-d5ab-11eb-83a4-45145b1cfcea.PNG)

**Comment by Nuklear92** [comment]
Commenting to remove Stale tag.

**Comment by drinfernoo** [comment]
@Nuklear92, can you reopen this issue at https://www.github.com/SerenKodi/context.seren/issues/?

**Comment by Nuklear92** [comment]
Done.
