### ISSUE TITLE
[BUG] Next page button showing watched movie/tv show

### ISSUE THREAD

**Issue by Nuklear92** [nixgates/plugin.video.seren#639]
I'm still not sure if this is a bug/glitch or a feature. I had been noticing this ever since Seren 2.0 came out but never reported it since I thought this could had been related to a bugged installation of Seren, etc. However, I've reinstalled Kodi and Seren a few times ever since 2.0 version was released and regardless of clean install of Seren, I've always noticed this as you'll see on the two clips I recorded below. In the Movies section in any list I click on there's a limit of titles displayed until you see the Seren Next page button, once I hover on it I always see that movie I've watched months and months ago. It never changes or rotates to a different movie, so I'm guessing it might be some sort of bug/glitch related which is way I'm reporting this. Also, if I go into the TV Shows section and go into any list and scroll over and hover the Seren Next Page button I see this show I'm already caught with and same thing it never rotates or change to another show. Before or prior Seren 2.0 I don't remember ever seeing this issue, the Seren Next Page button was always in blank or said something like click to next page. 🤷‍♂️ I really don't have any logs for this honestly, because it doesn't show as there any errors it just shows this movie and show in specific every time I hover on the Next Page button. Perhaps this could be something related to Trakt and Seren having some sort of weird glitch in that Next Page button area of the code, I'm not sure. Hopefully, you could take a look and see if you can reproduce this in your end. 

Here's the two clips showing the issue happening:

**This is in the Movies section, any list you click on, even watchlist**

https://streamable.com/a8x663

**This is in the TV Shows section, same situation any list you click on even watchlist**

https://streamable.com/taxb9n

**Comment by drinfernoo** [comment]
Yeah, seems so far we've had reports of "Jumanji: The **Next** Level", "Baruto: Naruto **Next** Generations", and "Star Trek: The **Next** Generation" 🤔

**Comment by drinfernoo** [comment]
We figured out that this was actually only happening in skins where TMDbHelper was providing service monitor lookups, as it was finding a "false positive" title match with the word "Next". We have change our label to "Next page" in order to avoid this, and it'll be included in the next update.

**Comment by Nuklear92** [comment]
@drinfernoo Thanks, I thought that issue wouldn't have any fix by now. 😅

What about the other fix from R.D #634 is it fixed for next update as well? 🤔

**Comment by drinfernoo** [comment]
Keep discussion about other issues in their own topic, please.

**Comment by Nuklear92** [comment]
Got it, sorry.

**Comment by drinfernoo** [comment]
This one should now be fixed in 2.1.4.

**Comment by Nuklear92** [comment]
> This one should now be fixed in 2.1.4.

Seems to be fixed so far! I'll keep an eye on it for the next couple of days, you can close this for now. 👍
