### ISSUE TITLE
Trakt sync of watchlist. Many movies missing

### ISSUE THREAD

**Issue by JackDinn** [nixgates/plugin.video.seren#640]
Kodi 19.1
Seren 2.1.1
Nvidia shield

This is my current trakt watchlist
![img](https://i.imgur.com/AEQpLt8t.png)

This is all that Seren can sync from that trakt watchlist
![](https://i.imgur.com/hNKeoU8t.png)

I have deleted all cache's, rebuilt the trakt database, re-started kodi. Iv done everything i can think of to try and force it to sync the other missing films but it wont :(

If i search for the movies that are missing from the watchlist sync in seren they are visible BUT if i try to use the "context menu/Trakt manager" on them i get a seren error.

I have tested with another kodi addon and it works fine, it pulls all the watchlist movies in fine.

Log:- https://pastebin.com/WDD8tSNh

You can test with these 2 movies:-
https://trakt.tv/movies/avatar-2-2022
https://trakt.tv/movies/dune-2021

**Comment by drinfernoo** [comment]
I forgot to say what is the actual issue here:

Since those movies are unaired, they are being hidden in your Watchlist, because you have the "Hide unaired items" setting enabled (by default). Searching does not respect that setting (for the specific example of searching for a movie which isn't out yet, so you can add it to your watchlist).

The bug which is fixed in the coming update is so that you don't get an error in this situation, but you can disable that setting to get around it for now.

**Comment by drinfernoo** [comment]
This should be fixed in 2.1.2.

**Comment by JackDinn** [comment]
> because you have the "Hide unaired items" setting enabled (by default).

O, right. I have never had to tinker with that particular setting before and i probably thought it only applied to TV shows, but yes, you are right. I have updated Seren and changed that setting and its all looking 100%.

Thank you :+1:

**Comment by JackDinn** [comment]
It does work but every time i use kodi the seren setting ""Hide unaired items"" is ticked again, by itself. I keep unticking it, but it won't stay that way. All other settings are fine.

**Comment by drinfernoo** [comment]
That... simply shouldn't happen. There's nothing in Seren that would cause that to turn back on.

**Comment by JackDinn** [comment]
It's definitely happening. Are you sure the setting is not getting saved (wherever the Seren settings are stored ?) I could check it and see if that particular setting is getting saved.

**Comment by JackDinn** [comment]
Ok i assume its here :-
`.kodi/userdata/addon_data/plugin.video.seren/settings.xml`

ATM its correct, set to false because iv just unticked it.
`<setting id="general.hideUnAired">false</setting>`

when it changes back to being ticked again, i shall check what this file says for this setting.

**Comment by drinfernoo** [comment]
Kodi saves settings in `special://userdata/addon_data/whatever.addon.here/settings.xml` for any add-on that has settings.

Seren does set some of these settings, but there is nowhere in Seren's code where we manipulate that one. Usually it is for storing authorization tokens and such for debrid services and Trakt.
