### ISSUE TITLE
[BUG] Global Context Menu error

### ISSUE THREAD

**Issue by Arathonk** [nixgates/plugin.video.seren#641]
**Describe the bug**
The Global Context Menu got an update today, now it won't work, when I try to use one of the options it gives me an error. 

**To Reproduce**
Try any of the options in the Global Context Menu

**Expected behavior**
Global Context Menu options should work 

**Screenshots**
-

**Kodi Version (please complete the following information):**
 - Kodi Version 18.9.0
 - Seren Version 2.1.1
 - Global Context Menu Version 2.1.0

**Additional context**
-
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6744121/kodi.log)

**Comment by drinfernoo** [comment]
Can't do anything about it without knowing the error 🤷🏼‍♀️

**Comment by Arathonk** [comment]
I have no idea how to get you that information..

**Comment by drinfernoo** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by Arathonk** [comment]
> https://kodi.wiki/view/Log_file/Easy

I added the log under additional context.

**Comment by drinfernoo** [comment]
This should be fixed by version 2.1.1 of the context menu add-on.

**Comment by Arathonk** [comment]
> This should be fixed by version 2.1.1 of the context menu add-on.

When will that update arrive? It did not happen before yesterday's update, is there a way to downgrade for now?
