### ISSUE TITLE
[REQUEST]Add "Recently Watched" as a supported sorting type (Trakt)

### ISSUE THREAD

**Issue by Dealz-416LS** [nixgates/plugin.video.seren#642]
**Is your feature request related to a problem? Please describe.**
Personal Trakt lists are unable to be displayed with the default sorting "Recently Watched" which can be set on the Trakt website but isn't supported by Seren.

Currently supported sort types.

```python
        supported_sorts = [
            "added",
            "rank",
            "title",
            "released",
            "runtime",
            "popularity",
            "votes",
            "random",
            "runtime",
            "percentage",
        ]
```

**Describe the solution you'd like**
Add support for the sorting type "Recently Watched" so that when it's set by default on Trakt, Seren can display it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Dealz-416LS** [comment]
Not stale, active feature request.

**Comment by drinfernoo** [comment]
Also, this is something that has been worked on in development. Sorry for the delay, but hopefully this one will make it into an update soon.

**Comment by drinfernoo** [comment]
These should be added in 2.1.5, can you check?

**Comment by Dealz-416LS** [comment]
Confirming this is working and also updated, Thanks!
