### ISSUE TITLE
Settings reset after undetermined amount of time

### ISSUE THREAD

**Issue by cphilpotts** [nixgates/plugin.video.seren#643]
**Describe the bug**
Set up Sort Order and all API keys which appear to save initially but are removed a short time later. Other settings stay as set. 

**To Reproduce**
1. Changes settings
2. Watch show
3. Return to settings to find values reset

**Expected behavior**
Settings should remain as set

**Kodi Version (please complete the following information):**
 - Kodi Version 19.0.0
 - Seren version 2.1.2

**Additional context**
Log file 
https://paste.kodi.tv/ivibekufer

**Comment by drinfernoo** [comment]
Does this happen every single time you watch something? Is it reproducible? We've seen a few issues like this reported, but have never been able to *make* it happen, and thus can't find where to fix it.

**Comment by cphilpotts** [comment]
> Does this happen every single time you watch something? Is it reproducible? We've seen a few issues like this reported, but have never been able to *make* it happen, and thus can't find where to fix it.

I'm not sure if watching something is causing it or if something else in the background is. I just notice it after watching something and before watching the next. But it is every time.

**Comment by drinfernoo** [comment]
So, you can change a setting (*only* happening with sorting and API settings?), watch something, and they get reset?

**Comment by drinfernoo** [comment]
I'm totally unable to replicate this... I did a fresh install of Seren (wiped add-on data, then reinstalled version 2.1.2 from the repo, followed by a reboot of Kodi). I then authorized my RD, installed providers, and set many settings regarding sort and filtering.

I then continued to play many items with no adverse effects. I simply cannot make it happen.

**Comment by xPhonee** [comment]
Hi

I have a similar problem. Seren settings would reset  as I open Kodi and afterwards as I watch a show. In the middle of the movie it would stop playing and all Seren settings are reset. I have to add all the accounts again and change the scraping options and everything's

I tried to fresh install Kodi and only Seren addon and it still does the same.

It only started happening after an update

Kind regard
L

**Comment by drinfernoo** [comment]
Not a single developer on our team has been able to replicate this situation.

We come from various platforms, with different viewing habits, different debrid services, and with different providers enabled...

I just can't think this is anything more than a fluke... maybe disk corruption or cosmic rays? 😅

**Comment by cphilpotts** [comment]
> Not a single developer on our team has been able to replicate this situation.
> 
> We come from various platforms, with different viewing habits, different debrid services, and with different providers enabled...
> 
> I just can't think this is anything more than a fluke... maybe disk corruption or cosmic rays? 😅

Im sure some steps aren't related but here's what I've done now step by step:
1) uninstalled seren
2) rebooted Kodi
3) reinstalled seren
4) rebooted Kodi
5) setup the following settings
  - Authorized Trakt
  - Authorized RD
  - Added Fanart API
  - Added TVDB API
  - Added TMDB API
  - changed movie play style to Source Select
  - changed Maximum file sizes in Sort & Filter
  - changed Sort from Torrent to Resolution
  - changed preferred cloud location to Real Debrid
  - changed next up sort style to Recently Watched
  - installed providers
6) rebooted Kodi
7) Real debrid was turned off again so re-authorized RD
8) rebooted Kodi again
9) attempted to play show and get error that no debrid accounts were found
10) authorized RD for a third time
11) attempt to play show and still no debrid account found
12) Cleared cache
13) authorized RD again
14) watched show
15) left it alone for 2 hours. Came back and settings are still ok (for now) but now RD is no longer authorized. Premium status says "Invalid" but I still have 100 days left.

**Comment by drinfernoo** [comment]
@cphilpotts When you uninstall Seren, are you also making sure to remove its add-on data?

**Comment by drinfernoo** [comment]
Have you enabled "Reuse Language Invoker"? It should be off by default, but  that may also cause issues.

**Comment by cphilpotts** [comment]
> @cphilpotts When you uninstall Seren, are you also making sure to remove its add-on data?

Yes. I remove add on data when I uninstall.

**Comment by cphilpotts** [comment]
> Have you enabled "Re-use Language Invoker"? It should be off by default, but  that may also cause issues. 

I haven't touched that setting.

**Comment by cphilpotts** [comment]
> > Have you enabled "Re-use Language Invoker"? It should be off by default, but  that may also cause issues. 
> 
> I haven't touched that setting. 

This was enabled by default. I've disabled it to see if that helps.

**Comment by cphilpotts** [comment]
So far so good overnight
