### ISSUE TITLE
Trakt authorization keeps getting reset

### ISSUE THREAD

**Issue by deanwethers** [nixgates/plugin.video.seren#644]
**Describe the bug**
I authenticate trakt and then upon a reload skin or refresh of kodi it completely erases my trakt info and prompts me to authorize it again. I can't get it to stay authorized now on 2.1.2. Real debrid is now perfect however...
**To Reproduce**
1. Go to seren settings/accounts
2. Click authenticate trakt
3. Refresh or restart kodi
4. See trakt unauthorized prompt

**Expected behavior**
Trakt to stay authorized.

**Screenshots**
![image](https://user-images.githubusercontent.com/84949476/124339950-5b0b7200-db77-11eb-98c2-7555645b0fd4.jpeg)
![image](https://user-images.githubusercontent.com/84949476/124339988-97d76900-db77-11eb-8158-8a477a129b92.jpeg)
**Kodi Version (please complete the following information):**
 - Kodi Version 19.1

**Additional context**
This just started occurring after updating to 2.1.2

**Comment by drinfernoo** [comment]
Please attach a debug log.

**Comment by StanLee01** [comment]
Today I had this exact same prompt twice. When I tried to reauthorize it through the Seren settings (ignoring the prompt), it said it completed the authorization, but when I looked into the settings, nothing happened, it was empty. But when I authorized it through the prompt, it worked. 

I'll send a log when it happens again.

**Comment by StanLee01** [comment]
It didn't happen again for me. So I think it's fixed or it was something else that caused it.

**Comment by drinfernoo** [comment]
We've got a special version of `settings_cache.py` for you to try out, which *may* fix it, and if it doesn't it has a **lot** of extra logging included that may help us track down the issue for everyone.

[settings_cache.zip](https://github.com/nixgates/plugin.video.seren/files/6796909/settings_cache.zip)

Can you please download this file, and unzip it (or copy the `settings_cache.py` file inside) to `special://addons/plugin.video.seren/resources/lib/modules/settings_cache.py`? Make sure to either do this with Kodi **not running**, or reboot Kodi afterwards.

If you have any more issues (besides a very long log file), please upload the log again. You'll most likely have to send the whole file, as it will probably be too long for a paste service.

**Comment by drinfernoo** [comment]
It would actually be really great if you could also test these two files... I've packaged this zip so that you can unzip it into `special://addons`, and it should put them where they belong.

[plugin.video.seren.zip](https://github.com/nixgates/plugin.video.seren/files/6804848/plugin.video.seren.zip)

Hopefully we should not have any more issues with settings getting broken after the changes in those files, including the one from my previous comment.

**Comment by drinfernoo** [comment]
So the fixed files I sent here over my last couple comments were actually the bulk of what went into 2.1.3, and given that those probably fixed this, I'm going to close it.
