### ISSUE TITLE
[REQUEST] Enhancement showing found streams

### ISSUE THREAD

**Issue by peno64** [nixgates/plugin.video.seren#648]
I like Seren very much because it shows in the window with found streams alot of information and especially the file name. Something that is found in not many other addons.

However I have two issues with it. 

1) something the file name is truncated. Which is a real shame because there is much more space on screen but it is not used. And when you position on a stream, the seren icon is also shown which also takes place...

2) Sometimes a chosen stream is not good because there is no matching subtitle for it. Then I have to stop the stream and select another. Unfortunately, Seren does not reposition on the stream that was chosen before and as such I don't remember which one I had chosen...

So two changes are proposed here.

1) The width adapted to show more of the title

2) Show an incrementing number

Please try following changes I made. They work really great for me and it would be fantastic if they were incorporated in Seren itself such that I don't have to make the changes when a new version comes out:

sourceSelect.py: https://paste.kodi.tv/rixabozoma
source_select.xml: https://paste.kodi.tv/bahuqazoqu.kodi

Thank you

**Comment by drinfernoo** [comment]
For what it's worth, this is exactly why Seren supports custom themes!

For more information on how to create, package, and distribute them, check out https://www.github.com/nixgates/plugin.video.seren/wiki/Themes 👍

**Comment by peno64** [comment]
Thank you. That would help for my changes in source_select.xml but what about the change I must do in sourceSelect.py to get the incrementing number?

**Comment by drinfernoo** [comment]
I do believe you could use `Container(1000).Position` for that... I haven't tested it, but that should give the position in the list.
