### ISSUE TITLE
No Playable Source found 

### ISSUE THREAD

**Issue by syedrazackimran** [nixgates/plugin.video.seren#649]
**Describe the bug**

**To Reproduce**
1. Movies or TV Shows
2. No Playable Source found for item

**Expected behavior**

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 19.1
 - Version [2.1.1]

**Additional context**

I real real-debrid and https://www.premiumize.me/ both getting same error.

**Comment by drinfernoo** [comment]
You need to provide **much** more information for this to be considered a valid issue.

What are you trying to get sources for? Have you installed providers? Have you authorized your debrid provider(s)?

Are you using a VPN? Did you pay your internet bill?

Have you checked your log file to see if anything else is going awry?

It is pretty common for things to not find any playable sources... but the most common reason is that there **aren't any**.
