### ISSUE TITLE
[BUG] Seren Error all of the sudden whenever trying to access tv show season

### ISSUE THREAD

**Issue by Nuklear92** [nixgates/plugin.video.seren#650]
**Describe the bug**
So far this is only happening with the TV Show, **Superman & Lois**. Whenever you try to access the first and only current Season as you'll see on the clip down below it triggers a Seren error. From what I can recall this wasn't happening a few days ago which I remember opening the show season normally. 🤷‍♂️

**Video Clip on how to Reproduce**

https://streamable.com/u2unyn

**Expected behavior**
Would be opening the Season and displaying all the Episodes available.

**Screenshots**
Here's the error log I'm getting whenever trying to access the Season.

![image](https://user-images.githubusercontent.com/76958541/125632684-e4b9cd8b-a0cc-4279-8833-4d5e32acfbae.png)

**Comment by drinfernoo** [comment]
Gonna need a log file. You should know this by now.

**Comment by Nuklear92** [comment]
@drinfernoo http://paste.ubuntu.com/p/c69BVVvVxs/

**Comment by drinfernoo** [comment]
We've hopefully got this one fixed for the next update :+1:

**Comment by drinfernoo** [comment]
This should be fixed in 2.1.5, can you check?

**Comment by Nuklear92** [comment]
Yeah, this one seems to be working fine as of now. 👍
