### ISSUE TITLE
[BUG] Rebuilding Trakt Database reoccuring notification + Trakt error

### ISSUE THREAD

**Issue by krzysztofwinnik** [nixgates/plugin.video.seren#652]
**Describe the bug**
For a longer time I am experiencing an annoying, reoccuring notification approx. 4 times per hour. The notification says: "Rebuilding Trakt Sync Database, please be patient" and it shows also during playback.  
On top of that, when I use a shortcut in Seren's settings to manually rebuild Trakt db, the addon throws an error. Clearly something is wrong (see attached log), but except for the annoying notification, all Trakt lists / watched status / wishlists etc seem to work just fine.
Earlier I had no such experiences with Trakt and Seren - everything worked fine.
Clear install and Trakt re-auth do not solve the problem.

**To Reproduce**
1. Go to Settings
2. Click on Shorcuts -> Rebuild Trakt Database
3. Confirm (dialog window)
4. Seren syncs with Trakt... iterates through movies, series... 3-4 minutes
5. I get an error 

**Expected behavior**
Once my db is rebuilt it syncs with Trakt in the background without frequent notifications.

**Screenshots**
n/a

**Kodi Version (please complete the following information):**
 - Kodi Version: CoreElec 19.2 rc

**Additional context**
n/a
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6836243/kodi.log)

**Comment by QwertyWu** [comment]
I have the same issue

**Comment by cgcgcgcgcg** [comment]
This worked for a friend with the same issue:
`Go to https://trakt.tv/oauth/authorized_applications and Revoke access to Seren, then open Seren > Settings > Accounts, click on Defaults, and OK, restart the build and authorize debrid & Trakt.
After that, database sync will start, if not restart again the build.`

**Comment by QwertyWu** [comment]
Excellent - Thank you.

**Comment by krzysztofwinnik** [comment]
I'll give it a try tomorrow and let you know. Thank you anyway!

**Comment by krzysztofwinnik** [comment]
Ok, I tried the solution suggested by @cgcgcgcgcg with no luck in my case. I even revoked access to Seren for all other apps (assuming there might be some kind of conflict) and authorized Seren as the only app to connect with Trakt.
The result is as I described it earlier - the initial bulid process seems to work fine... (100% shows sync, 100% collection sync etc.) and just in the end I get an error "Something went wrong... please see the log". After that I still get those annoying notifications during playback telling me that Seren tries to rebuild the db. Except for that all my Trakt related lists work fine, watched statuses work fine as well and so do next episodes. 

Since the reason of the bug remains unknown, perhaps a temporary solution would be to introduce "disable notifications during playback" feature in the next Seren update? What do you think @drinfernoo?

**Comment by drinfernoo** [comment]
This one should now be fixed in 2.1.4. Would you attempt a database rebuild, and confirm if it's working for you now?

**Comment by krzysztofwinnik** [comment]
The latest update fixed the issue. Thank you @drinfernoo!
