### ISSUE TITLE
[REQUEST] Prioritise sources that have a matching synced subtitle available

### ISSUE THREAD

**Issue by JonL1** [nixgates/plugin.video.seren#654]
It would be great if there was an option to search for a matching synced subtitle for the sources available instead of starting a stream and then hoping to find a synced subtitle just to realise none is available and have to start the whole process again.

For quick open(no source selection) it should prioritise sources that have a matching subtitle.

The process would be:

**Quick Open**

1) Select a media you want to view.
2) Retrieve sources
3) Retrieve subtitles available for sources
4) Match sources with subtitles
5) Prioritise sources with synced subtitles
6) Download subtitle and play

**Source Selection**

1) Select a media you want to view.
2) Retrieve sources
3) Retrieve subtitles available for sources
4) Match sources with subtitles
5) Show sources with an icon next to it if it has a synced subtitle
6) Order source by synced subtitle plus rest of order fields
7) Select source
8) Download subtitle and play

**Comment by peno64** [comment]
That would be a great enhancement. Something that is build in a4ksubtitles I guess. But then a4ksubtitles should already be called when all streams are shown and its result should then be used to sort the list.
I made a Windows application which is doing that when the list is on screen. This by making a small change to the seren addon to write the list to a file and the Windows application then uses it to find the best matching subtitle.
But it would indeed be great of this would be a buikd-in feature of Seren. Something no other addon has I think.
