### ISSUE TITLE
[BUG] Seren source quality isnt set properly for hosters

### ISSUE THREAD

**Issue by henryjfry** [nixgates/plugin.video.seren#655]
"ListItem.Property(quality)" and by extension the "quality" setting for a link currently isnt being set for hosters, it seems to always default to 1080p

I've had a look in "getsources.py" and for hosters there doesnt appear to be an equivalent piece of code to the torrents quality setting.

Adding the following into "def _get_hosters(self, info, provider):"

```
                release_title = source['release_title'].lower()
                quality = source_utils.get_quality(str(release_title))
                source['quality'] = quality
```

In this section:

```
            for source in sources:
                source['type'] = 'hoster'
                source['release_title'] = source.get('release_title', title)
                source['source'] = source['source'].upper().split('.')[0]
                source['size'] = source.get('size', '0')
                source['info'] = source.get('info', [])
                source['provider_imports'] = provider
                source['provider'] = source.get('provider_name_override', provider_name.upper())
```

Fixes that.

**Comment by drinfernoo** [comment]
Maybe you should make a PR, then?

**Comment by henryjfry** [comment]
Yeah the whole PR system is a bit of a ballache what with having to clone a repo and or figure out how to delete whatever outdated repo you already have.

But ive done that now:
https://github.com/nixgates/plugin.video.seren/pull/656

**Comment by drinfernoo** [comment]
Having a PR with a proper diff significantly reduces the amount of "ballache" developers and maintainers have to go through trying to figure out where to put proposed code changes (however minor), and allows them to easily test your changes by checking out your branch.

**Comment by 123Venom** [comment]
Tank the one hoster gets my vote

**Comment by drinfernoo** [comment]
@henryjfry It is true that there is really one one hoster provider available anymore... The only provider package I've ever seen for Seren only includes SCENERLS at this time, and the developer has stated that it is likely to be removed at some point in the near future.

**Comment by drinfernoo** [comment]
Considering that even SCENERLS has been removed from the common provider package, I think it's safe to actually close this one. If anyone ever puts together a package that includes hosters again, this may be something that needs looking at, but considering this was always an issue with hoster providers simply not supplying the required data, I would lean towards Seren just removing the size support for them in general.
