### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SirRickie** [nixgates/plugin.video.seren#658]
**Describe the bug**
Each time when starting Kodi, it gives me a Seren error. It says : unknown error connecting to Trakt. Everything works fine though, I guess. Can this be fixed ?

**Kodi Version 
 - Kodi Version 18.9
 - Seren 2.1.3

**Additional context**
![New Image](https://user-images.githubusercontent.com/60318531/126873647-1313deae-5192-4eb8-8dcc-2cf446477ab1.jpg)

Trakt error

**Comment by drinfernoo** [comment]
Looks like something odd is happening with our update checker 🤔 You can turn off the option to check for updates for the time being, and that should work around it. We'll probably be removing that feature in a coming update.

**Comment by SirRickie** [comment]
Tnx. Sorry, but where can I find that option to check for updates ?

**Comment by peno64** [comment]
I had this a couple of days also with the latest update of Seren. I revoked the trakt authorization and then reauthorised trakt in Seren and the  problem was solved.

**Comment by SirRickie** [comment]
> I had this a couple of days also with the latest update of Seren. I revoked the trakt authorization and then reauthorised trakt in Seren and the problem was solved.

I did that too, I revoked and reauthorised, but it didn't help.

**Comment by drinfernoo** [comment]
This doesn't have anything to do with Trakt 🤔

**Comment by drinfernoo** [comment]
@SirRickie `Seren Settings -> Interface -> Notify me about available updates`

**Comment by SirRickie** [comment]
Tnx, got it. Error is gone now.

**Comment by drinfernoo** [comment]
This will no longer be an issue in the future, as we've removed the update checker for the next update.
