### ISSUE TITLE
[BUG] no subtitle results when using seren

### ISSUE THREAD

**Issue by ShlomiD83** [nixgates/plugin.video.seren#660]
Hi,
I'm using an addon called "All Subs" and I can't get results when searching only TV shows (Movies search just fine).
I don't have that issue with other video addons.

win 10 x64
Kodi 18.9
Latest seren version.

Kodi Log https://controlc.com/2d4c0941
please advise.

**Comment by drinfernoo** [comment]
This sounds like an issue with your "All Subs" add-on. I'd try and ask the developer of that add-on, as we don't have anything to do with that.

**Comment by ShlomiD83** [comment]
I've mentioned that "All Subs" works perfectly with other video addons, the problem is with Seren.
