### ISSUE TITLE
[BUG] Trakt code disapear

### ISSUE THREAD

**Issue by dynamic2** [nixgates/plugin.video.seren#667]
When u try to connect to trakt the code to connect to it is disapaering instant 

Steps to reproduce the behavior, for example:
1. Go to 'settings'
2. Click on 'accounts'
3. Click on 'Auth trakt'
4. Popup comes whit code and disapear instant

 - Operating System
 - Kodi Version 18.9
 - Seren Version 2.1.4

**Comment by dynamic2** [comment]
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/6981456/kodi.log)

**Comment by drinfernoo** [comment]
Wow... you have a **lot** of add-ons installed. I count **67** video add-ons, which seems like a bit of overkill, don't you think? 🙄 

In any case, it does appear you're getting an invalid (unauthorized) session from Trakt... and it looks like it's also failing to copy the OAuth code to the clipboard, which may be what's actually causing the dialog to close.

We'll take a look at this one.

**Comment by MikeTosen** [comment]
if it was previously authorized - first retract the authorization and then authorize it again

**Comment by dynamic2** [comment]
if i go back to v 2.1.1 i could see the code after update to 2.1.4 i cant 

ps the 67 video addons are just for testing porpose haha i actualy use 3 or so

**Comment by drinfernoo** [comment]
@dynamic2 There were some changes to that bit of code in a relatively recent update, so we'll look into it.

**Comment by AcemanCW** [comment]
I am having the same problem as OP, running kodi 19 on an Nvidia Shield. Happened in both 2.1.3 and 2.1.4. Only a handful of addons installed.
For me it is part of a bigger issue, not being able to connect to Trakt anymore.

**Comment by drinfernoo** [comment]
This should be fixed in 2.1.5, can you check?

**Comment by dynamic2** [comment]
omg sorry didnt saw the reply but no dont see the code yeah i see it like 0.1 second then disapear.

log says:
ERROR: SEREN (-1): Failure to copy to clipboard, 
                [Errno 2] No such file or directory
