### ISSUE TITLE
[BUG] Track Failed to sync activity: Show bookmarks

### ISSUE THREAD

**Issue by zambux** [nixgates/plugin.video.seren#673]
**Describe the bug**

it as done it from de start of seren 2.x
it gives error wen sync shows bookmarks

**Log**

https://paste.kodi.tv/delayelajo.kodi

**To Reproduce**

Steps to reproduce the behavior, for example:

1.Go to Seren
2.Click on Tools
3.Click on Trakt Sync Tools
4.Click on Rebuild Database
5.After the rebuild completes, it gives an error "There were issues when processing the synchronization with trakt"

**Expected behavior**

The sync with trakt should not fail, and it should not go into a rebuild database loop every few minutes.

**Environment**

 - CoreELEC (official): 19.2-Matrix_rc3
 - Kodi Version 19.1
 - Seren Version  2.1.4

**Comment by drinfernoo** [comment]
From everything in your log, this appears to be an issue with your own network.

**Comment by zambux** [comment]
strange because only star to make after 2.x

**Comment by Tikipeter** [comment]
I also have a couple of users with the same current issue of `HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out` affecting their trakt interactions. Don't know what to make of that.

**Comment by drinfernoo** [comment]
This definitely seems like either a network or Trakt.tv issue to me.
