### ISSUE TITLE
[QUESTION/BUG] Why do some Genres not have almost anything in them/ Where did you get these from?

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nixgates/plugin.video.seren#674]
**Describe the bug**
Genres like Anime, None, Short, ect have nothing in them. 

**Log**
https://paste.kodi.tv/uwaduvibux

**To Reproduce**
Not really Anything to Reproduce tbh

**Expected behavior**
See Genres like tmdb helper Genres 

**Environment**

 - Windows 10 Pro
 - Kodi Version [19.1]
 - Seren Version [2.14]

**Screenshots and Additional Context**
![image](https://user-images.githubusercontent.com/62456796/130165850-cfc477c2-56a2-4bc7-b077-edd0212f1666.png)
Anime Section: 
![image](https://user-images.githubusercontent.com/62456796/130166057-7e934825-5035-46dc-81da-182bb62f6229.png)
Shart Section :
![image](https://user-images.githubusercontent.com/62456796/130166217-7627ca50-9e18-49ed-a8e7-e5916097c3f1.png)
Mini Series Section : 
![image](https://user-images.githubusercontent.com/62456796/130166515-5e5943db-03b3-4b35-9501-228c47161016.png)
ect....

Question: Where did you get these genres, Do you think they can be updates soon or let tmdb handle them?
Did you make these? 

I like your Genres category but they are never updated and i think they should be updated or hosted off of tmdb or trakt api. I've always wondered about this for a long time and i wanted to ask today on why. Thank you

**Comment by drinfernoo** [comment]
They come directly from Trakt.

The default setting is for these lists to show "Trending" content... but there may not be anything "trending" in "Anime" or "Short", according to Trakt.

Change the `Interface -> Base List Type for Genres` setting to "Popular" and you'll see much more content in those lists.

**Comment by Goldenfreddy0703** [comment]
Thank you for telling me cause i was wondering about this for a long time and its been bugging me ever sense

Again, thank you
