### ISSUE TITLE
[BUG] Repeated attempts to sync Trakt database & Next Up synching being inconsistent

### ISSUE THREAD

**Issue by FloydHaddocks** [nixgates/plugin.video.seren#675]
Hey - as the title says, the Trakt database won't complete a sync & tries to resynch every 10-15 minutes. I stopped using the addon about a month ago because of the issue, but keep trying to fix it because it's my favourite.

I have revoked Trakt authentication because the synch message cuts across every other addon I use, but every week or so I reauthorise to see if anything has changed. Recently Next Up has been consistent with some errors when I resynch - eg Ted Lasso show S02E01 as next up when Trakt has it fully watched. There's a couple of others that show a different episode from Trakt 

I get the same bug on two different devices - a windows 10 machine where the log comes from & a Hisense Android TV - I can dig out the model if that's relevant. It's the latest version of Android TV though.

**Log**

[kodi.old.log](https://github.com/nixgates/plugin.video.seren/files/7024500/kodi.old.log)
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/7024503/kodi.log)

**To Reproduce**

it just happens, every time I use Kodi with Trakt authorised in Seren

**Expected behavior**

database to sync successfully & correctly populate Next Up

**Environment**

 - Operating System
 - Kodi Version 19.1
 - Seren Version  2.1.4

**Screenshots and Additional Context**

If applicable, add any other context or screenshots about the problem here.

**Comment by ssjjbb11** [comment]
I too am having the exact same issue. Kodi 19.1 xenon plus 6.1 build. Has there been any workarounds yet?

**Comment by FloydHaddocks** [comment]
From what I can see, it is probably some shows in Trakt lists that have data that has an error in it. The only show I've seen as confirmed is "New Orleans Street Outlaws" or something. But that one isn't in any of my lists, so there's at least one more show/movie that's causing the problem. But I've got hundreds of shows & movies in my Trakt lists & working out what's causing the problem needs multiple logs as data points to compare. I tried deleting some of my show lists that I don't use much, but it didn't work - so I don't know where to next.

**Comment by ssjjbb11** [comment]
Well thank you for that information that does make sense, now to figure out
how to fix it lol

**Comment by drinfernoo** [comment]
This should be fixed in 2.1.5, can you check?

**Comment by ssjjbb11** [comment]
Thank you for the update I am not at home right now but as soon as I get
home I will check and I will get back to you.

**Comment by drinfernoo** [comment]
@FloydHaddocks, is this still an issue?

**Comment by ssjjbb11** [comment]
No it seems like it's synced up w/ Trakt database after the update and that
was it it did not continue doing it. I only watched TV for a little bit
last night though, yet I am off tomorrow so I will test it some more and
follow up with you if It's still an issue.
I really appreciate you reaching out to me. Have a great day.
Scott

**Comment by drinfernoo** [comment]
@ssjjbb11, are you @FloydHaddocks?

**Comment by ssjjbb11** [comment]
No, I'm not.

**Comment by FloydHaddocks** [comment]
> @FloydHaddocks, is this still an issue?

Not for me, thanks - you sorted it out when you found "A History of Ancient Britain" was causing issues. I just didn't want to close the thread while other people were using it it. I'm going to close it now. Thanks for sorting this issue out.
