### ISSUE TITLE
[BUG] Automatic Background Metadata Refresh feature introduced in 2.1.0 NOT working 100% after 2.1.4 Update

### ISSUE THREAD

**Issue by Nuklear92** [nixgates/plugin.video.seren#677]
This is an ongoing issue I have been paying close attention ever since the last update 2.1.4 build. Let me tell you a little backstory, prior 2.1.4 update. The feature that I personally was most pleased for was background meta refresh which was introduced back in 2.1.0 build. This feature made wonders to Seren, specially for a user like me which spend much time editing and helping out filling missing metadata information from websites like TMDb from time to time which Trakt keeps a close connection to it to provide updated meta and content to it's users using their platform for tracking movies & shows. It was refreshing seeing Seren each day or pretty much at different intervals daily make those little background updates to keep everything up-to-date with the latest meta info and nothing out of date like it did prior that feature being introduced.

**EDITED!** 👇

Everything was working great, until 2.1.4 update was released and then I stopped seeing that brief busy spinning wheel in the top left corner which I learned that it indicated a quick background meta refresh was happening. further more, I started noticing Artwork, missing episodes, plot, release date changes, etc. **Not** updating/refreshing anymore like it did in previous builds. The feature "somehow" works sometimes within the Movies section, as miraculously I had noticed it updating some poster artworks and missing plot and trailers but rarely frequent like when the feature was working at it's 100%. On the TV Shows section is where the feature is almost never working anymore. I said "Almost". Because, I noticed that for example a TV Show episode is released today and shown within the **Next Up** section without having official Episode thumbnail, 2 or more days can pass and that Episode within the Next Up will **NOT** update metadata, it could be missing Plot, Artwork, among other meta info. and I noticed that **IF** I decide to watch that Episode after it's watched and I directly navigate to the TV Show, Season, then that Episode with the missing Artwork, etc. will appear there with the updated info. **HOWEVER**, If let's say, I navigate to that same Season and the next episodes are missing thumbnail artwork, or even missing episodes altogether. Then the upcoming episodes are released Seren will **KEEP** the same old cached images of FanArt, missing Episodes will still be missing despite being new ones already within TMDb, Trakt official website. and I'll have to manually do a manual **Refresh Item Metadata** or due **Rebuild Database** quite often which are temporary measures of "fixing" this, because the situation lays down to Seren not keeping stuff Up-To-Date regularly and these issues start to pop-up again after a while with random shows or content in general. I previously never had to use these "Refresh Item Metadata or Rebuild Database" when this feature was working at it's 100% from 2.1.1 until 2.1.3, because everything was always updated with the latest metadata edits from TMDb and Trakt websites respectively.

I apologize for the really long explanation, but since I know the logs won't show much of an issue, I had to explain first hand my experience and findings after being on the look out for this issue on the past two weeks or more.

** Debug Log:** https://paste.kodi.tv/udufuwopex

**To Reproduce**
Very time consuming, requires to pay very close attention, leave released in-progress tv show episodes without artwork thumb and other missing meta info without being touched or watched. However, I have three small clips I recoreded during my testing of this issue which I'll share below.

**Expected behavior**
Prior 2.1.4 build the expected behavior was, background meta refresh kept everything up-to-date with the latest artwork posters, season posters, episode thumbnail, missing plot, casts, trailers, crew members, etc.

**Environment**

 - Nvidia Shield TV Pro 2019, Android TV: 9
 - Kodi Version: 19.1
 - Seren Version: 2.1.4

**Screenshots and Additional Context**

This first clip was from an Ep. that was released on the 19th of August, I left it untouched until the 26th and as you'll see I had to manually do a Refresh Item Metadata in order for that episode to grab the updated missing Meta & Artwork.

https://streamable.com/3bkc0p

This second clip is from an Episode which was released yesterday 26th of August and already had updated thumbnail from TMDb and Trakt website, But since Seren already had the cached image of FanArt it kept it that way and as you'll see I had to do a manual refresh as well. 

https://streamable.com/ogmloy

This third clip is from another show which It had it's premiere of Season 2 yesterday the 26th as well. as you'll see within the Next Up it's still showing a FanArt thumbnail as the image and was cached by Seren and never updated afters a bunch of hours of is release regardless of TMDb and Trakt already had updated info and Artwork. Again, had to do a manual Refresh Item Metadata. 

https://streamable.com/8hokf7

This fourth clip is from another tv show which the latest Episode was released on the 26th and today is the 28th at the time of the release the Episode already had a thumbnail update from TMDb and Trakt website. Seren, kept the old cached FanArt thumb and never updated as you'll see. I had to perform another Refresh Item Metadata.

https://streamable.com/nhjdix

Here's the fith and last clip I would share, which further proves that the feature isn't working at all. This Episode was released on the 29th of august, time of the release it didn't had any artwork thumbnail so Seren displayed FanArt, day after 30th TMDb updated Episode thumbnail followed by Trakt website. It's September 1st two days after the release and I had to do a manual Item Metadata Refresh, something I wouldn't had to do prior 2.1.4 because Seren constantly kept everything up-to-date with the latest meta and artwork changes from TMDb and Trakt servers using that Background Meta Refresh feature in 2.1.0.

https://streamable.com/2cgmnf

**Comment by Dealz-416LS** [comment]
My experience so far with the current version of Seren (2.1.4) is that artwork, backdrops (episode screenshots) specifically don't update until after a restart kodi.

Prior to this version of Seren as soon as the episode is watched the backdrop would be displayed if available or I'd use the skin 'refresh' button at the top menu to refresh the screen, restarting Kodi was not necessary.

FYI I do have the setting in Kodi that hides episode artwork thumbs till the episode has been watched to avoid spoilers.

Seren doesn't update air dates, skin refresh (same as above) or Kodi restart doesn't work. I was unaware of aired episodes as they was not shown in Next Up due to the air dates not being updated. I had to manually refresh item metadata to get the dates to update.

**Comment by Nuklear92** [comment]
Can also confirm the air dates issue as well not updating which is all tied to the background metadata refresh. Prior 2.1.4 these things weren't an issue as everything was always up to date. 

This is a very important feature to have working as sometimes there's a lot of edits and changes that happen on TV Show seasons, episodes and Movies. Specially when there's a release date change, typos that get fixed from TMDb and then grabbed from Trakt website but Seren still shows old cached info that sometimes mess up the Next Up in the case of TV Shows or Movies that probably had an updated release date from TMDB, Trakt and Seren still shows a wrong date, missing Trailers when there's already one available within TMDb and Trakt websites.

**Comment by Dealz-416LS** [comment]
AHS S10 was missing 6 episodes, Seren wasn't automatically updating the metadata for this show's season.

I was advised to wait for a Trakt sync to happen as Seren does this every 13-17 mins, I waited long enough for this sync to happen 2-3 times but even after restarting Kodi Seren had still not updated this show's season.

In the end I had to do a manual item metadata refresh on the season and that immediately resolved the issue.

All 6 missing episodes including 1 that aired today were now shown, a couple of updates back this wouldn't have been necessary.

**Comment by Nuklear92** [comment]
> AHS S10 was missing 6 episodes, Seren wasn't automatically updating the metadata for this show's season.
> 
> I was advised to wait for a Trakt sync to happen as Seren does this every 13-17 mins, I waited long enough for this sync to happen 2-3 times but even after restarting Kodi Seren had still not updated this show's season.
> 
> In the end I had to do a manual item metadata refresh on the season and that immediately resolved the issue.
> 
> All 6 missing episodes including 1 that aired today were now shown, a couple of updates back this wouldn't have been necessary.

Just more proof that I'm not crazy. 🤷‍♂️ I mean, for some this seems like nonsense and you should just use the addon as it is. But, how can you use the addon as it is, when simple things like these doesn't work all the time. Meaning the user needs to be on top of every single TV Show, Movie, etc. and check if everything is up to date or nothing is missing like, episodes among other medatada there being Artwork, release dates, and other edits that happen almost daily multiple times during the day from TMDb website which is the main source of metadata info from Trakt website. 

If you ask me, I would expect in every single small Trakt syncs that happens in the "background" regularly in Seren which doesn't seem to be the case at least with the latest 2.1.4 build. To also have a complete metadata refresh/update same as what Trakt does daily from TMDb website with TV Shows, Movies, etc. gathering and updating new missing episodes, plots, artwork, cast/crew for episodes even if we don't actually have the need to see it. It's all part of the overall medatada combo. Or better yet, if it's something that requires too much resources to do that often aside from a simple Trakt sync. Could be something that happens separately every 5 or 12 hours, it won't happen that often but it will still keep everything up to date, from the Daily metadata updates that happen within the official Trakt website.

**Comment by Dealz-416LS** [comment]
Just thought I'd report on my additional experience with this issue.

Evil Season 2 Seren is displaying E1-9 
![Kodi_20210920_105638](https://user-images.githubusercontent.com/54026944/133985393-9de22019-0c1e-48dd-9896-e155dec7d17b.png)

But on Trakt there is E1-13
[Evil - S2](https://trakt.tv/shows/evil/seasons/2)

Seren is missing 4 episodes from this season one of which (E10) aired today which isn't displayed at all as it's completely missing and isn't being automatically updated.

I also noticed Y: The Last Man was displaying 2 episodes in Next Up which was odd so i had a look and the episode that just aired (E4) is being displayed twice in Seren.
![Kodi_20210920_105457](https://user-images.githubusercontent.com/54026944/133985977-5b64527b-7d72-420f-9b3e-df1a0acd1be8.png)

Only shown once on Trakt
[Y: The Last Man - S1](https://trakt.tv/shows/y-the-last-man/seasons/1)

Hasn't been updated to remove the duplicate episode to match Trakt.

It's strange because even prior to the `Major re-work of metadata updates and merging` in 2.1.0 (which worked perfectly for automatically updating shows etc) I never had these issues with newly aired episodes being completely missing or parts of a season being missing :confused:

Also not sure why but Y: The Last Man E4 (duplicate episode) was being shown twice on Next Up, not sure if it's due to the episode being dupe.
![Kodi_20210920_112903](https://user-images.githubusercontent.com/54026944/133988916-ae346b79-708d-4ab9-90b3-2d686d46ee4f.png)

Anyways... Evil - S2 missing 4 episodes, I was able to fix by doing a manual `Item Metadata Refresh` on the Season, however that solution didn't work with Y: The Last Man, not sure Y (sorry had too :rofl:) instead i had to `Rebuild Database` although i probably should have tried the `Force a sync with Trakt` option first.

**Comment by Nuklear92** [comment]
Geez! This is definitely becoming more and more a serious situation. Thanks for the documentation on your experience. I really hope this issue post has been looked at by the Developers of Seren by now. 🤷‍♂️ 

This is definitely now a priority issue that needs to be fixed in my opinion since it's literally now crossing the line towards interfering with the user's addon experience. This shouldn't be the case at all, users shouldn't had to be on to of doing manual "Rebuild Databases" these often because once in a while after doing one issues of missing released episodes among other metadata aren't being successfully refresh/update in the background. 🤦‍♂️

**Comment by drinfernoo** [comment]
Sorry for the delay in answering... This one has been fixed in development too, we believe. You should start seeing better results after the next release.

**Comment by Nuklear92** [comment]
> Sorry for the delay in answering... This one has been fixed in development too, we believe. You should start seeing better results after the next release.

💙 thanks Doc for the input! I'll definitely gonna give it a test once the next update is out.

**Comment by drinfernoo** [comment]
This should be fixed in 2.1.5, can you check?

**Comment by Nuklear92** [comment]
> This should be fixed in 2.1.5, can you check?

Definitely, it might take like 1-2 days to fully have an honest feedback. However, if I find any activity before 24hours I'll definitely let you know. You can leave this open I'll be sure to close it as soon as I have a proper answer. Thanks again for the update, Doc. 👍

**Comment by drinfernoo** [comment]
While something is likely going on here, after further investigation, responses **from** TMDb are returning no artwork for these items, in @Nuklear92's case, and that behavior is consistent (albeit odd) across other add-ons as well.

TMDb is acting inconsistently, but it doesn't seem to be a Seren issue.
