### ISSUE TITLE
RD - "Failure to resolve source" on all movies & TV

### ISSUE THREAD

**Issue by xsy77** [nixgates/plugin.video.seren#678]
Hi guys,

Fresh install of Kodi on a RPi4.

Followed the instructions to the letter but when I try and play anything, the sources just seem to skip until the end whereby it says it cant play it.

Tried everything I can think of:

- Re-authorised many times

- Re-authorised without VPN

- Cleared caches

- Re-installed

I confirm:

- my RD account is active and not expired.

- I can see the sources in my RD account history that Seren is trying to play.

- Another RD based add-on works flawlessly on the same build.

Redacted Log: [https://pastebin.com/S77rRiqK](url)

Specs:

Kodi 18.7 installed via Retropie

RPi4 4GB

Seren 2.1.4

I've read through various threads with similar symptoms to this but the comments are all fixed in X.XX which are all older builds than I have or to re-auth RD/clear cache etc which I have tried.

Any advice please?

**Comment by Cesarrf2021** [comment]
Hi, same issue using nvidia shield and RI PI 4

**Comment by Cesarrf2021** [comment]
> Hi, same issue using nvidia shield and RI PI 4

Ignore, started working again, after a few days broken

**Comment by xsy77** [comment]
> > Hi, same issue using nvidia shield and RI PI 4
> 
> 
> 
> Ignore, started working again, after a few days broken

Still not working for me sadly

**Comment by drinfernoo** [comment]
It looks to me like this is a failure on RD's part. They were doing server maintenance for a few days... which would cause this.

Try revoking and reauthorizing RD again.

**Comment by drinfernoo** [comment]
@xsy77, is this still an issue?
