### ISSUE TITLE
[REQUEST] Adding the option to have transparent icons for genres.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nixgates/plugin.video.seren#681]
**Describe the feature you'd like**

Adding the option to have transparent icons for genres instead of black icons.

**Describe alternatives you've considered**

Using Auto Widget and editing each of your genre icons one by one in Adobe Photoshop

**Additional context**
I love what you guys did with Genres and i think i will be using these instead of my costume tmdb helper ones, the only problem is that these icons are not transparent and i think you guys should add an option for that.

**Add any other context or screenshots about the feature request here**
Example with transparent icons:
![image](https://user-images.githubusercontent.com/62456796/131336738-7338fccb-9a06-4efb-9eaf-19b67ab6a783.png)
-This is an example of what im looking for and i would love to see transparent icons in seren.

Example without transparent icons:
![image](https://user-images.githubusercontent.com/62456796/131336947-7063a473-c6ce-4f2d-a55d-bcfe3419db06.png)
-You guys did your best on these and i appreciate these alot but i wish there was an option to make them transparent so that i could use these with skins that match up with there theme in the future.

**Comment by drinfernoo** [comment]
You know... I meant for these to be transparent but forgot to fix them before release 😅

**Comment by Goldenfreddy0703** [comment]
Hey if you like, i can try to find these icons in the addon and photoshop them to make them transparent for you and send a you link to them.

Would you like me to do that for you?

**Comment by drinfernoo** [comment]
@Goldenfreddy0703 If you feel like doing that, I'll review them 👍

**Comment by Goldenfreddy0703** [comment]
Nice, im already working on them right now so they should be done in a few min.

**Comment by Goldenfreddy0703** [comment]
[genres.zip](https://github.com/nixgates/plugin.video.seren/files/7076841/genres.zip)
Hey so i just got finished with all the Genres so i hope these help and satisfy your requirements.

**Comment by Goldenfreddy0703** [comment]
![next](https://user-images.githubusercontent.com/62456796/131343568-53f4f620-23c8-4583-a7a4-8d67349189c2.png)
Oh i almost forgot the Next.png icon, i hope this helps too just in case.

**Comment by Goldenfreddy0703** [comment]
Hey @drinfernoo sorry for bothering you and i know your probably busy but were you able to review these icons?

**Comment by drinfernoo** [comment]
They look pretty good from.the ones I did look at. We'll probably use them 👍

**Comment by Goldenfreddy0703** [comment]
Nice thank you very much!!!

**Comment by drinfernoo** [comment]
These were added in 2.1.5 😁
