### ISSUE TITLE
[BUG] Playing a show from a playlist widget with Titan Bingie Mod skin throws an errors when there is only 1 episode left to watch

### ISSUE THREAD

**Issue by patel-jeel92** [nixgates/plugin.video.seren#684]
**Describe the bug**
I am using Titan Bingie Mod skin and have a In progress TV Show widget on the home screen. When I click on this, TMDB Helper routes the call to seren because its my default player. For TV Shows that only have 1 episode left to watch, seren throws an error and refuses to play the item.

**Log**
Will try to get this.

**To Reproduce**

Steps to reproduce the behavior, for example:
1) Have in progress media widget on the home screen 
2) Select a tv show which has one remaining episode left 
3) Attempt to play the media using (seren smart play player- configured in tmdb helper) 

**Expected behavior**

TV Shows with one episode remaining should play without errors 

**Environment**

 - Operating System
 Android TV
 - Kodi Version 
 19.1
 - Seren Version
 2.1.4

**Screenshots and Additional Context**
Seren Settings for Playback:
- Auto playlist creation (ON)
- Force Auto Episode Resume (ON)
- Movie Play Style (Auto Play)
- Episode Play Style (Auto Play) 
- Smart Play Display Style (Fancy)

**Comment by drinfernoo** [comment]
Does this also happen if you play using Seren? If not, then this is an issue with the player for TMDbHelper.

**Comment by patel-jeel92** [comment]
Do you mean directly from the seren plugin? Or do you mean using Play with Seren player without the smart select?

**Comment by drinfernoo** [comment]
Playing directly through Seren.
