### ISSUE TITLE
[Question] This is not a bug but i've noticed something in your files, Why is there an Adult icon???

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nixgates/plugin.video.seren#687]
Ok so again, this is not a bug nor a feature request just by the title. 

Ok so i was editing genres with autowidget addon cause i did not like seeing the background of seren genres in the background but i've noticed something when i was looking through the genres. I saw a genre icon that said "adult.png" and i was like "ok maybe seren had an adult section" so i looked on movies and tv shows genre and saw that there was no adult section so i was like "ok maybe there is an option in the config" to unlock that section. 
There wasn't...

Ok so here's my question: Why is there an Adult.png icon and were you guys planning to have a secret nsfw section in your addon??????
![adult](https://user-images.githubusercontent.com/62456796/133356645-69547769-5c5a-4b11-8706-765eef834a80.png)

Please explain cause i would really like to know the details and how an adult icon was in the genres folder. 😂
![image](https://user-images.githubusercontent.com/62456796/133356950-a7508d65-3cea-4d7f-8423-7d61c57f8fe3.png)

**Comment by drinfernoo** [comment]
It was part of the icon pack that I used when making icons for Seren, and just copied it in.

**Comment by Goldenfreddy0703** [comment]
oh i thought it these icons were made cause i never seen some of these icons before. Thank you for telling me.

**Comment by drinfernoo** [comment]
@Goldenfreddy0703 They were made... by someone else 😅

With a couple exceptions for missing ones, they come from the Arctic Zephyr icon set in the official repository.
