### ISSUE TITLE
[BUG] Context menu not available when long-clicking in on episode

### ISSUE THREAD

**Issue by coldspark29** [nixgates/plugin.video.seren#688]
**Describe the bug**

In Movies, My Movies or My Series you can long-click on the movie/episode and then have the context menu to choose sources etc. This doesn't work in the normal Series section. I always have to start watching it, then go into My Series -> Finish watching and there the context menu appears.

**To Reproduce**

Steps to reproduce the behavior, for example:
1. Go to Series
2. Choose any series
3. Long-click on the episode
4. No context menu appears

**Expected behavior**

Context menu should appear like everywhere else

**Environment**

 - Operating System
 - Kodi Version: LibreELEC 10.0
 - Seren Version: 2.1.4

**Comment by drinfernoo** [comment]
You're likely using a skin which combines the season/episode views, like Arctic Horizon for example. Those skins can't show the context menu in that situation, due to limitations on the Kodi skin engine... so you'll have to enter the season first.

**Comment by coldspark29** [comment]
Yeah, that must be the reason. Pity.
