### ISSUE TITLE
Debug log spammed by "trying to load setting definitions from old format..." messages

### ISSUE THREAD

**Issue by toneman77** [nixgates/plugin.video.seren#69]
I produced debug logs for another issue earlier and when my log was full of the message:
`CAddonSettings[plugin.video.seren]: trying to load setting definitions from old format...`
I got the suggestion to wipe the addon data. Since then I forgot to turn of debug logging and again saw this message even tho i was sure I wiped and setup Seren fresh only days ago so I tried to reproduce:

Started kodi with debug log enabled at 16:47, wiped the data via the tools menu in seren then exited kodi. Log [here](https://pastebin.com/1EAdWBnj)

Started kodi again, set up everything again minutes later and the debug log is again full of this block:
```
2019-03-01 16:56:04.622 T:3066   DEBUG: CAddonSettings[plugin.video.seren]: loading setting values
2019-03-01 16:56:04.627 T:3066   DEBUG: CAddonSettings[plugin.video.seren]: loading setting definitions
2019-03-01 16:56:04.628 T:3066   DEBUG: CAddonSettings[plugin.video.seren]: trying to load setting definitions from old format...
```
1574 times in 90s just from opening Seren and selecting "up next". 

Cut log [here](https://pastebin.com/zcWwn78x) because pastebin.ca has a 512k limit.

**Comment by toneman77** [comment]
to make sure it is not my Nvidia shield i tried to reproduce it in an isolated environment and set up a blank new ubuntu docker container with current leia from the official PPA.
- enabled debug logging
- added the repo
- installed seren
- set up trakt and real-debrid
- opened seren and selected "up next"

1533x
`DEBUG: CAddonSettings[plugin.video.seren]: trying to load setting definitions from old format...`

the log is over 1MB... so i had to remove quite a few to be able to upload it here:
[part1](https://pastebin.com/QQEcE5UA)
[part2](https://pastebin.com/W9yhsYx4)

**Comment by nixgates** [comment]
Unfortunately this is an issue with Kodi and not Seren.

Until the Kodi team fix the issues with the new settings format Seren will continue using the old one.

There is currently an open issue on the XBMC github in regards to this. 
https://github.com/xbmc/xbmc/issues/15252 #

**Comment by nixgates** [comment]
I've reduced this as much as I can within Seren, we are unfortunately going to have to wait until/if Kodi patches/changes this behavior.
