### ISSUE TITLE
[BUG] Seren prompting error log while link is being streamed

### ISSUE THREAD

**Issue by Nuklear92** [nixgates/plugin.video.seren#691]
**Describe the bug**
This has been happening since last week or so for me personally. Sometimes I'm streaming a link from a TV Show or Movie, mainly TV Shows. And out of nowhere I'm seeing a prompt in the top right corner saying there was an error that occurred with Seren. I have the log which I will share, since I just got it a while ago while I was watching an Episode.

**Log**

https://paste.kodi.tv/upagomaxoy

**To Reproduce**

There's not a precise way to reproduce the error it just happens randomly, not every time you're watching episodes but sometimes. Hopefully the log I provided even though it's not a Debug one will still provide more info to ping point what's causing this.

**Environment**

 - Nvidia Shield TV Pro 2019
 - Kodi Version [19.1]
 - Seren Version [2.1.4]

**Comment by Nuklear92** [comment]
@drinfernoo I closed this by mistake could you please reopen it again. My apologies.

**Comment by drinfernoo** [comment]
This looks like a Trakt server error. Not a Seren issue, just wait for Trakt to resolve their issues.

**Comment by Nuklear92** [comment]
@drinfernoo Oh, I see thanks for the input. I had no clue which is why I decided to open a ticket. 🙂
