### ISSUE TITLE
[Question] Was it easy to code viewtypes in your addon?

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nixgates/plugin.video.seren#695]
Hey there, sorry to bother but I wanted to know if it's easy to code viewtypes like how you guys made custom viewtypes for seren. I want to edit an anime addon called Kaito which was a fork of seren and I wanna try adding custome viewtypes to the addon. I don't know how to code very well but I want to give it a try but I don't know where to start or edit when it comes to editing the addon and adding the option to have custom viewtypes. 

Is it ok if you guys can show me how you guys added custom viewtypes to your addon?

**Comment by drinfernoo** [comment]
We set it at https://github.com/nixgates/plugin.video.seren/blob/master/resources/lib/modules/globals.py#L1446

The docs for `xbmcplugin.setContent(...)` can be found at https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcplugin.html#gaa30572d1e5d9d589e1cd3bfc1e2318d6

This method needs to be called at some point before `xbmcplugin.endOfDirectory(...)`, basically.

**Comment by Goldenfreddy0703** [comment]
Thank you so much for telling me this.
