### ISSUE TITLE
[BUG] trakt intermittent issues loading/syncing

### ISSUE THREAD

**Issue by trowieuk** [nixgates/plugin.video.seren#696]
Started having issues a few days ago, at first nothing that required trakt would work, then most worked but others didn't... currently next up, upcoming episodes and watchlists won't load. Can't rebuild trakt database either.

Log - 
https://paste.kodi.tv/rumijijuru.kodi

 - Windows 10 21H1 19043.1237
 - Kodi Version 19.1
 - Seren Version 2.1.5

**Comment by irbyjm** [comment]
I was getting these 401 errors from TraktSync a few days ago, I suggest reauthenticating Trakt from the Settings menu.

**Comment by trowieuk** [comment]
> I was getting these 401 errors from TraktSync a few days ago, I suggest reauthenticating Trakt from the Settings menu.

I've tried, it says successfully disconnected from trakt but still shows my account, is there anyway to force it to disconnect on trakt.tv instead?

**Comment by drinfernoo** [comment]
@trowieuk No, since Trakt.tv can't modify settings on your local device. All revoking on the website will do is cause more issues when Seren tries to operate with an invalid key.

**Comment by drinfernoo** [comment]
I agree that this looks like you need to reauthorize. A 401 response means "Unauthorized".

Revoke Trakt from the settings, making sure to press "OK" to close the settings dialog, and then open it again to reauthorize.

**Comment by trowieuk** [comment]
Okay, I'll keep trying to reauthenticate then. It says it's disconnected from trakt but doesn't change anything when I open again. Weird that next up works and others don't though. Will keep trying, thanks both!!
