### ISSUE TITLE
[BUG] Error when trying to do a “Remove Playback Progress”

### ISSUE THREAD

**Issue by Nuklear92** [nixgates/plugin.video.seren#697]
**Describe the bug**
As the title says, Seren is throwing an error whenever you try to remove playback progress by going into **Context Menu - Trakt Manager - Remove Playback Progress** this wasn't an issue in prior builds from current 2.1.5.

**Log**

https://paste.kodi.tv/wamesehevi

**Environment**

 - Nvidia Shield Pro 2019
 - Kodi Version [19.1]
 - Seren Version [2.1.5]

**Screenshots and Additional Context**

![image](https://user-images.githubusercontent.com/76958541/136218767-c22beb0a-750f-4939-939b-0b7b72fed6d0.jpeg)
![image](https://user-images.githubusercontent.com/76958541/136218793-ddc7905e-0e9a-4c09-b671-42162079c6b7.jpeg)

**Comment by drinfernoo** [comment]
Is this still an issue in 2.1.7?

**Comment by Nuklear92** [comment]
It's fixed in the current build. Thanks! 😃
