### ISSUE TITLE
[BUG] Trakt code not displayed for authorizing trakt. 

### ISSUE THREAD

**Issue by patel-jeel92** [nixgates/plugin.video.seren#698]
**Describe the bug**

After removing trakt authorization and attempting to re auth trakt, the dialog window that shows up to input the code at trakt.tv/activate does not show the trakt code. The code field is empty

**Log**

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/7307455/kodi.log)

**To Reproduce**

Steps to reproduce the behavior, for example:
1. Go to 'Account' and then Revoke Trakt authorization
2. Click on 'Authorize Trakt'
4. See dialog window with no trakt code

**Expected behavior**

The trakt code to be visible

**Environment**

 - Operating System - Android
 - Kodi Version - 19.1
 - Seren Version - 2.1.6
 

**Screenshots and Additional Context**

**Comment by patel-jeel92** [comment]
![20211007_173043](https://user-images.githubusercontent.com/20840348/136484902-c9038748-bc8a-456b-83aa-3dd6eb2eba78.jpg)

**Comment by patel-jeel92** [comment]
That I haven't tried.

**Comment by drinfernoo** [comment]
In that case, it seems like this is a skin issue.
