### ISSUE TITLE
Kodi crash when installing repo

### ISSUE THREAD

**Issue by Jezze83** [nixgates/plugin.video.seren#7]
I have latest libreelec installed. When i choose install from zip file, choose repo zip, kodi just restart. It wont install repo. What logs you need,kodi crash log or what?

**Comment by nixgates** [comment]
Any logs you can provide would be great as I don't have much to go on at the moment.

**Comment by nixgates** [comment]
It has been nearly a month since I've had any information. I'm closing this ticket.
