### ISSUE TITLE
[BUG] Error when clicking on Quick Resume Show from Context Menu

### ISSUE THREAD

**Issue by Nuklear92** [nixgates/plugin.video.seren#700]
**Describe the bug**
 Every time I hit on Quick Resume Show from any TV Show title there's an error. I don't recall having this issue in prior builds. 

**Log**

https://paste.kodi.tv/fewalibaja

**To Reproduce**

Steps to reproduce the behavior, for example:
1. Go to 'Any lists for TV Shows'
2. Click on 'Long Press to open Context Menu from any title'
3. Scroll down to 'Quick Resume Show, click'

**Expected behavior**
TV Shows would automatically start scraping the Episode you're currently ON instead of having to click on the title, then Season, then Episode.

**Environment**

 - Nvidia Shield TV Pro 2019
 - Kodi Version [19.2]
 - Seren Version [2.1.6]

**Comment by drinfernoo** [comment]
Is this still an issue in 2.1.7?

**Comment by Nuklear92** [comment]
It's fixed In the current build. Thanks! 😃

**Comment by Nuklear92** [comment]
I'll double check, and give you a feedback.

**Comment by Nuklear92** [comment]
Just tested and it's working now in 2.1.8. Thanks! 🙂
