### ISSUE TITLE
Can't resume playback

### ISSUE THREAD

**Issue by TrillaG** [nixgates/plugin.video.seren#706]
Still not getting that option that pops up to ask whether to resume or start from beginning. Fresh install, Kodi 19.2, Seren 2.1.6.

**Comment by TrillaG** [comment]
https://paste.kodi.tv/atisezitoj.kodi

**Comment by TrillaG** [comment]
This bug still hasn't been fixed. I've been using Fen for a while now because of this exact issue. I posted my log, why did nobody attempt to solve this?

**Comment by drinfernoo** [comment]
Just because there wasn't a response doesn't mean nobody attempted to fix it... nobody on the testing team has been able to reproduce it, as far as I know of. I'll remove the stale label, but I'm not sure what the fix will be.

**Comment by TrillaG** [comment]
Okay yes, please keep this open. There are definitely others who have the same problem, as somebody else posted about it, and who knows how many have the problem who didn't post. I think it's important enough to keep trying to fix.
