### ISSUE TITLE
TV artwork displaying image for incorrect language

### ISSUE THREAD

**Issue by kbxy88** [nixgates/plugin.video.seren#71]
My widgets that I have pointed to Seren - trakt - finish watching and another is Seren - Trending , some of the titles come up foreign language on the widgets artwork itself.

I am using an fanart API in Seren settings if that helps
I’m on 18.1 
I’m not sure if this is a Seren or Skin error(Bingie Mod) and if a log would help
http://imgur.com/2vYviwK
http://imgur.com/lqwSqhO
‘La Mule’

**Comment by nixgates** [comment]
Apologies, Seren wasn't filtering for language codes with TVDB.

I have appended this fix and it will be included in 0.1.36

**Comment by nixgates** [comment]
Resolved in update 0.2.0
