### ISSUE TITLE
[REQUEST] Update get_kodi_database_version for kodi 20

### ISSUE THREAD

**Issue by peno64** [nixgates/plugin.video.seren#711]
I know, kodi 20 (Nexus) is still in development. But curious people already want to try it...
So I updated my kodi 19 version to the latest kodi 20 nightly build and everything works fine, except one small thing in Seren:

The function get_kodi_database_version checks on kodi version to determine which database version to use and this fails on the new kodi 20. But the kodi team has already stated what this version will be: the same as for kodi 19. See https://kodi.wiki/view/Databases

I made a manual change for this and as such Seren works fine under kodi 20

So please already make this change also in your next  update.

Thank you

**Comment by drinfernoo** [comment]
Once Kodi 20 builds are in RC status, we'll start looking at supporting them.

**Comment by TheN00r** [comment]
how would I go about doing this manually? I guess adding version 20 with database version 120 to globals.py is part of it, but what else is required?

**Comment by jakkerson** [comment]
> how would I go about doing this manually? I guess adding version 20 with database version 120 to globals.py is part of it, but what else is required?

https://github.com/nixgates/plugin.video.seren/pull/775

**Comment by drinfernoo** [comment]
This should be fixed in the next update :+1:

**Comment by drinfernoo** [comment]
This should now be working in 2.2.0 👍
