### ISSUE TITLE
Trakt Sync Issue[BUG]

### ISSUE THREAD

**Issue by adamosborne83** [nixgates/plugin.video.seren#712]
Hey this is a bit of a strange one, so please bare with. 
Of you think a log is warranted then, as you know I will try....

So here is the issue...... I'm using Kodi 19.2 with Auramod, on FireCube.
I use MDBlist.com to create my own Trakt lists for genres I like, and have it to randomly refresh every 12 hours to trakt, I then point my genre widget to my list in seren to let's say Horror, so I never see the same movies in my Widget line up.

BUT when MDBlist updates and in turn makes my trakt update, my list stays the same in my widgets in the same order, even though it has changed on Trakt and even if I go through seren My Movies and My List, it has changed their too.

At first I thought this was a skin issue, so I tried it with TMDB and had my widget pointed at the same trakt list, and when I refreshed mdblist it updated trakt AND tmdb picked it up and changed too.

Does this make any sense at all?

Cheers as always and apologies.

**Comment by adamosborne83** [comment]
Http://paste.ubuntu.com/GdgsTGkG98/

I refreshed the skin again and Sci-fi and Horror still show the same movies, even though trakt has changed.

**Comment by adamosborne83** [comment]
http://paste.ubuntu.com/p/GdgsTGkG98/

**Comment by adamosborne83** [comment]
Http://paste.ubuntu.com/p/5xF6ZWwcbs/

**Comment by adamosborne83** [comment]
Hope 1 of those 2 show you what I mean.

**Comment by drinfernoo** [comment]
Do you see the outdated lists if you browse into Seren and find the list directly, after they should've updated?

**Comment by adamosborne83** [comment]
> Do you see the outdated lists if you browse into Seren and find the list directly, after they should've updated?

Hey, thanks for your reply.
I should had closed this tbf, as I think this is more of an Auramod issue than Seren, as you are correct when I use Seren directly it has the updated list (mdblist.com updates every 8hours) but Auramod does not seem to do this, although I does update over night. 

Odd, but just one of those things I guess.

**Comment by drinfernoo** [comment]
We did find a weirdness in Seren that may cause these lists to be cached longer than they're supposed to... If you feel like it's fixed, that's great! We'll still push through our fix in a future release, which should make it more reliable.

**Comment by drinfernoo** [comment]
> even more odd that even when I use openwizqrd to clean cache, it still doesn't refresh to what is currently being displayed in Trakt,

Considering OpenWizard is unsupported and hasn't been updated to handle Seren's caches correctly in a while, I'm not sure I can even recommend using it 🤷

**Comment by adamosborne83** [comment]
> 

Ahhhh, I knew it wasn't supported anymore, but didn't realise the cache aspect for Seren, what would you recommend?

**Comment by adamosborne83** [comment]
Just an FYI too, I cleared cache using tools in Seren and then reloaded widgets on home screen and it updated with the current trakt list!
