### ISSUE TITLE
[BUG] Original Titles Not showing

### ISSUE THREAD

**Issue by jibay442** [nixgates/plugin.video.seren#713]
When choosing "Show original titles" in setting>interface>advanced, the titles of japaneses movies and animes dont work.
Thanks
I add a screenshot were you can find square form instead of title for "バケモノの子, Bakemono no ko" :

![seren](https://user-images.githubusercontent.com/43931525/140612118-5539029a-6173-4307-9c6d-132e0367c83c.png)

**Comment by drinfernoo** [comment]
This appears to actually be a skin issue. Your skin doesn't include a font which can display Unicode characters.

Seren is passing them correctly, but since your skin can't display them, they show up as squares.
