### ISSUE TITLE
Multiple sources found, but seren does not play any source

### ISSUE THREAD

**Issue by dezai2** [nixgates/plugin.video.seren#718]
Multiple sources found when I select any movie / TV show, but seren does not play any source- it simply scrolls through each one. When I stop the process, a 'no playable source' prompt appears

https://paste.kodi.tv/sebolodanu)

Steps to reproduce the behavior, for example:
1. Go to any Movie or TV episode
2. Select Movie / episode 
3. Seren searches providers and displays multiple sources
4. Select source (usually the first one)
5. Seren scrolls through the various source, but does not start playing them
6. Eventually I stop the process. 'No playable source found for item' is displayed

**Expected behavior**
Selected source should start playing

**Environment**

 - LibreELEC 9.2.6
 - Kodi 18.9 
 - Seren 2.1.8

**Comment by drinfernoo** [comment]
This appears to be a timeout when contacting Premiumize... likely they had server issues at the time or your network is blocking the connection for some reason.

Have you tried reauthorizing PM?

**Comment by dezai2** [comment]
Yes- That's the first thing I tried. Also cleared my cache

**Comment by sheen73** [comment]
Having same issue on my system. Windows 10, premiumizme. Clearing cache and syncing tracks sometimes helps. I reauthed premiumizme too and no luck. It’s been like this for a few weeks and not sure what’s changed.

**Comment by swright1234** [comment]
Same problem. Only torrents are populated but none play. 

Kodi 19.3
Seren 2.1.8
Nvidia shield
Reauthorized PM

**Comment by drinfernoo** [comment]
This has actually been identified as an issue with PM's servers and is being investigated by PM. Hopefully there will be a resolution soon.

**Comment by drinfernoo** [comment]
I haven't seen this in a while now, and PM is apparently working again.
