### ISSUE TITLE
Add Network TV Menu Item

### ISSUE THREAD

**Issue by pencey** [nixgates/plugin.video.seren#72]
Tv Networks list in "Discover Shows". I realize you can do this with Trakt lists, but I was hoping to get more variety in "Discover" at some point. Thank you for everything so far!

**Comment by nixgates** [comment]
Added for 0.1.36 :)

**Comment by Mastacc** [comment]
The "Discover TV shows" is kind of poor in general. If it's possible for a new source of "New TV Shows" to be used it would be appreciated. The one in Seren that pulls from trakt shows nothing worthwhile, and the imdb list that other addons use is much better. The current one is missing HUGE new shows and instead is populated with stuff that is mostly very obscure. Wouldn't be problem if I could find a custom trakt list with new shows, but I haven't been able to find one.

**Comment by nixgates** [comment]
@Mastacc 
What I can look at is adding a new menu for something closer to most popular in the past 12 months?

**Comment by Mastacc** [comment]
Yea that would be amazing. The popular list that's there atm probably isn't going to change in a long time, if ever.

**Comment by nixgates** [comment]
Added in update 0.2.0
