### ISSUE TITLE
[BUG] Impossible to navigate on an Android box within "Manage provider Packages"

### ISSUE THREAD

**Issue by bdeman** [nixgates/plugin.video.seren#721]
**Describe the bug**

The bug within Android (in my case a Firestick 4k), makes it impossible to navigate with the given remote within this "manage package settings" menu.

**To Reproduce**

Have **a4kscrapers** installed.

Steps to reproduce the behavior, for example:
1. Go to tool settings
2. Go to providers
3. Go to Manage provider packages
4. Go to Manage package settings.
5. if followed above steps, you cant navigate further within this screen (with the firestick remote), you do hear the interaction/navigation sounds, but nothing gets selected.

**Expected behavior**

Being able to navigate and interact.

**Environment**

 - Operating System
 - Kodi Version 19.1
 - Seren Version 2.1.8

**Comment by drinfernoo** [comment]
This should be working now in 2.1.9, but the case should only really present itself if there is a problem with providers in the first place. Gonna close this one.
