### ISSUE TITLE
[BUG]Cloud Files & PM

### ISSUE THREAD

**Issue by Dealz-416LS** [nixgates/plugin.video.seren#726]
**Describe the bug**

Anyone else finding the saving of resolved items and automatic cloud removal inconsistent or just not working?

For a while some resolved items are saved to PM, some are not. I removed everything recently from My Files and so far nothing I've resolved for the last 2-3 weeks has saved so doesn't work at all at the moment.

I've also noticed that resolved items are shown in PM transfers but after playback it's removed and doesn't go to My Files.

**Log**

**To Reproduce**

Enable `Store resolved items in cloud` in Accounts

Scrape and start a show/movie, after playback the file will likely not be in your cloud.

When your cloud is full or at the limit set new files are no longer saved as oldest aren't automatically removed.

**Expected behavior**

Everything you watch (resolved item) is saved to PM cloud, oldest are removed to make room for newest.

**Environment**

 - Kodi Version 19.3
 - Seren Version 2.1.9

**Screenshots and Additional
N/A

**Comment by Dealz-416LS** [comment]
Not stale, still experiencing this.

**Comment by Dealz-416LS** [comment]
Not stale, still experiencing this.

**Comment by Dealz-416LS** [comment]
Not stale, still experiencing this.

**Comment by npmstart-pray** [comment]
With Kodi v19.4 and Seren v2.2.1 and RD - Working fine here.

**Comment by drinfernoo** [comment]
@Dealz-416LS Is this still an issue?

**Comment by drinfernoo** [comment]
Closed at request of user.
