### ISSUE TITLE
[BUG] Selecting a movie/episode causes Kodi to crash

### ISSUE THREAD

**Issue by DualityKyle** [nixgates/plugin.video.seren#727]
After searching for content, actually attempting to play/scrape the item causes Kodi to crash to desktop.

I am able to easily replicate this, as I have attempted so play something 3 separate times this morning and Kodi crashed each and every time.

I am running:
Fedora 35
Kodi 19.3
Seren 2.1.9

Debug log attached:

[kodi_crashlog-20211223_102621.log](https://github.com/nixgates/plugin.video.seren/files/7769914/kodi_crashlog-20211223_102621.log)
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/7769917/kodi.log)

**Comment by drinfernoo** [comment]
There's a few things going on here. First of all, Seren isn't yet compatible with Python 3.10, which is what's running. Second and thirdly, there's an issue with the RD cache. Those two might be solved by clearing your cache and torrent cache, and reauthorizing RD

**Comment by DualityKyle** [comment]
I remember you mentioning about 3.10.

I've gone ahead and switched to the flatpak for Kodi and it seems to be working fine now, so I'll just keep using the flatpak going forward. You can close out this issue.

**Comment by DualityKyle** [comment]
Sorry to revive an old, closed issue, but I sawz changedlog 2.2.2 and noticed the pytz update.

Decided to give it a go on a non-flatpak install and it works now (Fedora 36 with python 3.10.7). Does this mean Python 3.10 support has arrived with this version?

**Comment by drinfernoo** [comment]
For the most part, yes. We currently test our codebase against 3.9 and 3.10, having stopped testing against 2.7 in the ramp up towards dropping Kodi Leia support in Seren 3.0.0.

Kodi on some Linux systems still has some issues with Python 3.10.x, but they're unrelated to Seren... Unfortunately, there hasn't been a certain fix figured out yet, but there's a chance it'll start working in Nexus 🤷
