### ISSUE TITLE
[BUG] Not loading second page of a liked Trakt list because invalid response from omdb for an specific movie 

### ISSUE THREAD

**Issue by baruchin** [nixgates/plugin.video.seren#730]
Seren is not loading the second page of an specific Trakt [list](https://trakt.tv/users/garycrawfordgc/lists/latest-releases?sort=added,asc) because omdb is giving an invalid response for a movie. "The b**** who stole Christmas" being the culprit.

Here's the log.
https://paste.kodi.tv/uqebumusoy

To reproduce, just like the list on Trakt to get it on the Trakt liked list section on Seren. Click on the list, and go to next page. That will give the Seren error.

**Comment by drinfernoo** [comment]
Actually, digging into this a bit further, the real culprit for the error in your log was "South Park: Post COVID". "The Bitch Who Stole Christmas" was *also* giving an error response, but the South Park movie was giving a improper XML response from OMDB (the XML was not well-formed, and this unparsable).

We're looking at covering both of these instances to cover any further issues with OMDB.

**Comment by drinfernoo** [comment]
@baruchin Looks like the OMDB developer has actually fixed this on their end :+1: In the case that it happens, we've implemented fixes to properly handle these types of responses as well. Should be in next release.

**Comment by baruchin** [comment]
Those are great news. Thank you.
