### ISSUE TITLE
[BUG] Real is authorized in settings, but I cannot play any movie or serie

### ISSUE THREAD

**Issue by sinker442** [nixgates/plugin.video.seren#731]
When I click on a movie, this comes up. 
I tried new install in kodi 18.9 and 19.3 same thing.
![IMG_20220104_115243](https://user-images.githubusercontent.com/97093056/148041505-429f6ead-044b-4cbe-9520-b2e2bc997977.jpg)

**Comment by drinfernoo** [comment]
Install providers.
