### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 0adbylad** [nixgates/plugin.video.seren#733]
**Describe the bug**

**Log**

Please attach or link to and uploaded log file here.
Log files are required, and debug logs are preferable.
See the Kodi wiki for information on [how to get a log file](https://kodi.wiki/view/Log_file/Easy).

**To Reproduce**

Steps to reproduce the behavior, for example:

**Expected behavior**

**Environment**

 - Operating System
 - Kodi Version [e.g. 18.9, 19.1]
 - Seren Version [e.g. 2.1.3]

**Screenshots and Additional Context**

If applicable, add any other context or screenshots about the problem here.

**Comment by 0adbylad** [comment]
seren rebuilding trakt sync database please be patient
So ive had to above error for sometime and ive tried many ways to work round it, i followed you advice here[ ](https://www.reddit.com/r/Addons4Kodi/comments/o6273i/serenrebuilding_trakt_sync_database/)
Did a complete uninstall and brand new instal checking all version were up to date 
Before i even open the addon i get an error report[
](https://paste.kodi.tv/leparareqi)
Im on a Nvidia Shield  model number P2571 version 9
Kodi v19.3 (Matrix)
and as you can see the latest version of Seren 2.1.9

**Comment by 0adbylad** [comment]
https://paste.kodi.tv/leparareqi

**Comment by 0adbylad** [comment]
drinfernoo any joy?

**Comment by drinfernoo** [comment]
I think you need to clear your cache (from `Settings -> Shortcuts`), and reauthorize Trakt.

**Comment by 0adbylad** [comment]
Ill try it
Thank you
