### ISSUE TITLE
Authorize Premiumize not working on Seren

### ISSUE THREAD

**Issue by krazh64** [nixgates/plugin.video.seren#734]
**Log**

https://paste.kodi.tv/iqoyidekem

**To Reproduce**

I can't authorize Premiumize on Seren, I get an error, an no activation code popup window. It just says to check the log.

**Environment**

 I got Kodi Matrix, the latest Seren version, running on a new nvidia shield pro

**Comment by drinfernoo** [comment]
We haven't been able to reproduce this... it could have been a one-off server issue from PM, or possibly a corruption in your settings file 🤔 Could you try again?

**Comment by EekNL** [comment]
I'm having the same issue. I have the feeling this started after renewing my Premiumize account for 2 years with a Black Friday deal. All 3 (identical) CoreElec installs with Seren are affected by this.

CoreElec 19.3 - Matrix with Seren 2.1.8 on Odroid N2's.

I think it started more then a month ago with an API error, I then wiped all devices from my Premiumize account. Now i get an error when i try to authorize with Premiumize in Seren, telling me to check the logs. (Seren error, check the logs for more information)

The relevant portion is showing me the following:

`2022-01-09 21:57:47.129 T:5914     INFO <general>: SEREN (-1): Seren, Running Path - {'action': 'authPremiumize'}
2022-01-09 21:57:47.264 T:5914    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'expires_in'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.seren/seren.py", line 20, in <module>
                                                       router.dispatch(g.REQUEST_PARAMS)
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/modules/router.py", line 676, in dispatch
                                                       Premiumize().auth()
                                                     File "/storage/.kodi/addons/plugin.video.seren/resources/lib/debrid/premiumize.py", line 57, in auth
                                                       expiry = int(token["expires_in"])
                                                   KeyError: 'expires_in'
                                                   -->End of Python script error report<--

2022-01-09 21:57:47.652 T:5914     INFO <general>: Python interpreter stopped
`

I thought it might have to do with my Premiumize account, so i wiped Seren's configuration and went back to "Authorize Premiumize" without changing any other setting first, and it immediately gives me the same error. I also tried to start Authorization with Real Debrid, which did not give me an error ( I don't have a Real Debrid account, so i coulnd't complete that process )

**Comment by EekNL** [comment]
I've managed to fix my problems by disabling my OpenVPN service in CoreElec and re-authorize Premiumize. After enabling OpenVPN again everything kept working.

**Comment by krazh64** [comment]
I uninstalled the whole Kodi, and reinstall everything and it's working
fine now.
