### ISSUE TITLE
[FEATURE REQUEST] Adding a Skip Intro button for TV Shows. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nixgates/plugin.video.seren#737]
**Describe the feature you'd like**

I would like to have a skip intro button like what Netflix includes and i think it would be a great idea to add.

**Describe alternatives you've considered**

I honestly do not have any alternative unless there is an addon out there that skips your video for an amount of seconds at the beginning, Only problem with that is the alternative addon would not know if your watching a tv show or movie. 

**Additional context**

Reason why i think adding a Skip Intro button for TV Shows is that i think it would be easier for the user cause on some tv shows, they don't provide bookmarks and i think its necessary to add this feature.

**Comment by drinfernoo** [comment]
In the meantime, there is "TV Show Skip Intro" by @aenemapy.

**Comment by Goldenfreddy0703** [comment]
Oh I didn't even know that, Thank you so much.

 One big question i have is does the script tvskipintro detect if its a movie, youtube video, or tv show and could you disable it for youtube videos or movies?

**Comment by drinfernoo** [comment]
@Goldenfreddy0703 I haven't ever used it, but I'm pretty sure you have to set it up for each thing you watch, as there isn't any database or record available of how long intros last (or where in the episode they are, like in the instance of shows with cold opens).
