### ISSUE TITLE
[REQUEST] Add information provider

### ISSUE THREAD

**Issue by simieski** [nixgates/plugin.video.seren#739]
Would it be possible to add a new information provider for Seren such as imdb or Rotten Tomatoes. In particular the ratings provided by Trakt and tmdb are not as good in my opinion. It would be really nice to have the options available when using the Universal Movie Scraper?

**Comment by drinfernoo** [comment]
If using an OMDB key, these should already be filled.

**Comment by Goldenfreddy0703** [comment]
Hey there, I'm actually having an issue with this as well on the artic zypher 2 resurrection skin. On TV Shows, I can't seem to get ratings from tmdb or others. I only get Information on trakt. On movies, they seem fine but on TV Shows, I'm have trouble with it.

**Comment by Goldenfreddy0703** [comment]
Actually nevermind. Turns out i was having a skin bug. It just was not showing on the front page.
