### ISSUE TITLE
[BUG] Seren uses wrong trakt database on profile switch

### ISSUE THREAD

**Issue by jac4e** [nixgates/plugin.video.seren#743]
**Describe the bug**

When using two profiles, the database of the first logged in profile after system/kodi start is shown on all profiles, even after force trakt sync and rebuild database.

**Log**

This is a non-debug log, will get a debug log when I have the time.

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/8174433/kodi.log)

**To Reproduce**

1. Get fresh kodi install
2. Create a second profile
3. install and setup seren with a trakt account on the first profile
4. log into second profile
5. enable seren and required addons
4. install and setup seren with a different trakt account on the second profile
6. reboot
7. log into any profile
8. navigate to seren -> my shows -> next up
9. log out, then log into the other profile
10.  navigate to seren -> my shows -> next up
11. observe how the other profiles trakt list is shown
12. force sync with trakt / rebuild database
13. again, observe how the other profiles trakt list is shown

**Expected behavior**

Each profiles trakt database should be populated with the data from their respective trakt accounts

**Environment**

 - LibreELEC x86 10.0.1
 - Kodi 19.3.0
 - Seren 2.1.9

**Comment by ShibajiCh** [comment]
Hi @jac4e,

I'm facing this same issue too.

Thanks and Regards,
ShibajiCh.
