### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ewawowa** [nixgates/plugin.video.seren#744]
Films would last 10 ish mins then close down the whole Kodi app. Deleted Kodi and reinstalled and then tried to reload Seren. 
Showing most of the parts in the repository are not available. 
![16472044340856671055256672965128](https://user-images.githubusercontent.com/61378481/158078613-9c412bea-59da-400b-b573-9a8fd414e2d3.jpg)

 - Operating System
 - Kodi Version [ 19.3]
 - Seren Version [ 2.1.9]

**Comment by drinfernoo** [comment]
If you're still experiencing this, please open a new issue with the requested information in the template.
