### ISSUE TITLE
[BUG]  "Seren Error, check logs" - Please Help

### ISSUE THREAD

**Issue by Buzzwhouse111** [nixgates/plugin.video.seren#747]
**Seren was working perfectly, however I can no longer watch anything on it.  When attempting to, an error message pops up : Seren Error, check logs**

I have tried clearing the cache, re-authorising trakt and rebuilding the database but i've still got the same issue. 

**Log**

https://paste.kodi.tv/ilulezunic

**To Reproduce**

Steps to reproduce the behavior, for example:
Reboot Kodi Box
Navigate to Seren Addon
Search for a show / film and select it
It starts fetching the streams then it suddenly stops and shows "Seren Error, check logs"

**Environment**

 - Operating System
 - Kodi Version [18.9]
 - Seren Version [2.1.9]

**Comment by drinfernoo** [comment]
The error in your log indicates that you were trying to install providers... which is a completely different action to how you describe replicating it 🤔

**Comment by Buzzwhouse111** [comment]
agh, sorry about that how about this one? https://paste.kodi.tv/ogesozixip
