### ISSUE TITLE
Seren Trakt next up etc not working

### ISSUE THREAD

**Issue by Arathonk** [nixgates/plugin.video.seren#748]
I've used Seren in combination with Trakt for years, always using the Next Up function to view episodes.
Starting today it stopped working, I tried updating Seren and re-authorize and rebuild Trakt but nothing works.

Log: https://paste.kodi.tv/anebopizis

**Comment by drinfernoo** [comment]
Can you try rebuilding the Trakt database again? Shouldn't need to reauthorize, but turn on debug logging, rebuild, and then send that new log if it's still doing it.

**Comment by Arathonk** [comment]
> Can you try rebuilding the Trakt database again? Shouldn't need to reauthorize, but turn on debug logging, rebuild, and then send that new log if it's still doing it.

New log after rebuild of database: https://paste.kodi.tv/bopacemufu

Just so you know I mean the pop up for next up right, to play next episode. That one is not showing and after an episode ends next episodes don't play. I have enabled it in settings though.

**Comment by npmstart-pray** [comment]
You have to login to the trakt website, accept the new ToS, revoke auth, reauth and then rebuild watched lists. Seren works fine - Trakt is where the stoppage is.

**Comment by derrgoo** [comment]
Thanks for this tip! I logged in and noticed that right away. Hope that helps. Seren has been giving me cannot connect to trakt often.

**Comment by Arathonk** [comment]
> You have to login to the trakt website, accept the new ToS, revoke auth, reauth and then rebuild watched lists. Seren works fine - Trakt is where the stoppage is.

Did that, but it doesn't help.. I still get no pop up asking what to do with next episode, no next episode plays automatically.

**Comment by npmstart-pray** [comment]
I saw someone on Reddit mention that Trakt has made some changes to their API in the past 24h - might help with the db issue. 
As far as Up Next not working...I'd say remove/reinstall that addon and see what happens, but I'd be prepared to wipe/rebuild.

**Comment by drinfernoo** [comment]
@npmstart-pray Seren does not use "Up Next" anyways.

**Comment by Arathonk** [comment]
> @npmstart-pray Seren does not use "Up Next" anyways.

Yes I'm talking about Seren's Next Up function with the smart dialog. So is there an fix? Because I tried everything mentioned in this topic.

**Comment by npmstart-pray** [comment]
Perhaps I’m mistaken as to what OP’s talking about, but I get a pop up in the corner of my screen when binge watching a series that gives me the option to “Play (next episode) Now” or “Close”. 
Is that not supposed to happen in Seren?

**Comment by Arathonk** [comment]
> Perhaps I’m mistaken as to what OP’s talking about, but I get a pop up in the corner of my screen when binge watching a series that gives me the option to “Play (next episode) Now” or “Close”. Is that not supposed to happen in Seren? Sent from nowhere near my ready room with my new tricorder
> […](#)
> On Apr 22, 2022, at 09:23, drinfernoo ***@***.***> wrote: ﻿ @npmstart-pray Seren does not use "Up Next" anyways. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

That is supposed to happen, there are two different things, an addon called "Up Next" which is not what I'm asking about. And the function within Seren called "Next Up", which is an smart dialog asking to olatly the next episode or to stop, it also has an still watching function. The Next Up function is not working anymore for me, it had been working right for years.

**Comment by Arathonk** [comment]
@drinfernoo do you have any idea on what to do? Thx.

**Comment by drinfernoo** [comment]
Do you have "Auto Playlist Creation" enabled in Seren's "Playback" settings?

**Comment by Arathonk** [comment]
> Do you have "Auto Playlist Creation" enabled in Seren's "Playback" settings?

I do yes.

**Comment by npmstart-pray** [comment]
> > Perhaps I’m mistaken as to what OP’s talking about, but I get a pop up in the corner of my screen when binge watching a series that gives me the option to “Play (next episode) Now” or “Close”. Is that not supposed to happen in Seren? Sent from nowhere near my ready room with my new tricorder
> 
> > […](#)
> 
> > On Apr 22, 2022, at 09:23, drinfernoo ***@***.***> wrote: ﻿ @npmstart-pray Seren does not use "Up Next" anyways. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.
> 
> 
> 
> That is supposed to happen, there are two different things, an addon called "Up Next" which is not what I'm asking about. And the function within Seren called "Next Up", which is an smart dialog asking to olatly the next episode or to stop, it also has an still watching function. The Next Up function is not working anymore for me, it had been working right for years. 

Apologies for my confusion. 
I went looking for what you're talking about, (can't believe I've not tried to use it - I mean, it's right there on the 'My shows' submenu) and it seems to be working correctly on my setup.

**Comment by drinfernoo** [comment]
@Arathonk I can't quite make heads or tails of what you're saying here now... too many responses muddying it up.

You're saying that when you are watching a show, the "Playing Next" dialog never shows up? Does the next episode play, or do you just get returned to the menu?

**Comment by Arathonk** [comment]
> @Arathonk I can't quite make heads or tails of what you're saying here now... too many responses muddying it up.
> 
> You're saying that when you are watching a show, the "Playing Next" dialog never shows up? Does the next episode play, or do you just get returned to the menu?

Haha understandable.

Yes the dialog never shows and the next episode doesn't play, it just kicks me back to the menu.

**Comment by Arathonk** [comment]
It's still not fixed.
