### ISSUE TITLE
Metadata in Info window

### ISSUE THREAD

**Issue by jfk88** [nixgates/plugin.video.seren#749]
How can I set what kind of metadata show up on the Info window? I first thought it was skin related but it looks like Seren grabs only "Genre", "Tagline" and "Premiered" (from TMdB).

**Comment by drinfernoo** [comment]
Your skin determines what information is shown on its info window. Seren grabs what should ideally be nearly complete metadata information from a combination of Trakt, TMDb, TVDB, and even OMDB, where appropriate and applicable.
