### ISSUE TITLE
PI3 : ERROR: error: can't start new thread

### ISSUE THREAD

**Issue by ratmole** [nixgates/plugin.video.seren#75]
https://github.com/nixgates/plugin.video.seren/blob/90285e7abcb8cb35267f032050a17ad8884ac561/resources/lib/indexers/tvdb.py#L11

consider  
`threading.stack_size(64*1024)`
there are multiple errors in pi3 in Next Up without it 
`ERROR: error: can't start new thread`

**Comment by nixgates** [comment]
Seems Next Up is pulling more threads than the PI can handle. 

I'll add in a low-end device support setting which will unfortunately slow down the menu a bit, but will also reduce issues with threads not starting.

**Comment by nixgates** [comment]
Edit: 
Sorry I just realised you have mentioned changing the stack size for the threads. 
I have a few PI's lying around and I'll run them through the mill and see how it holds up

**Comment by akuiraz86** [comment]
I was experiencing this issue with my raspberry pi 3b ... inserted the suggested fix by ratmole and now next up loads perfectly!  btw am running OSMC

**Comment by nixgates** [comment]
This has confirmed to be a big help to low end devices and as such has been added for the next update.

**Comment by nixgates** [comment]
Issue should be resolved after 0.2

Please check and confirm
