### ISSUE TITLE
[SUPPORT] Re-authenticate Trakt errors 

### ISSUE THREAD

**Issue by heimdall47** [nixgates/plugin.video.seren#750]
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/8457795/kodi.log)

I have been getting errors on Seren to re-authenticate Trakt for the last many days. Tried to reinstall seren,        re-authenticate Trakt and rebuilt database but nothing works. Please help. Is it a bug. Kodi log is attached 
 
Environment:
Nvidia Shield Pro 2017
Kodi 19.4
Seren 2.1.9

**Comment by drinfernoo** [comment]
There have been ongoing Trakt issues: https://twitter.com/traktapi/status/1514602500090826762?s=20&t=5zTRRaXRnFOuIPa-7jlRbA

This isn't a Seren issue, but a Trakt one.
