### ISSUE TITLE
[BUG] Unknown error connecting to Trakt

### ISSUE THREAD

**Issue by ShibajiCh** [nixgates/plugin.video.seren#751]
**Describe the bug**

Hi,

I have faced this issue earlier as well and I'm facing it again now. I reported this issue earlier via ticket #450.

When I watch an episode completely till the end without stopping in the middle, the episode should get marked as watched in Trakt, but it doesn't. The Trakt scrobbling happens fine while watching the episode, and after the scrobbling ends nothing happens. Instead after about 15 mins or so I get an error popup which shows "Unknown error connecting to Trakt" and immediately the episode gets marked as watched in Trakt. I've tried scrobbling using both Seren's inbuilt Trakt scrobbler and also using the separate Kodi Trakt addon, but same thing happens. Atleast, while using the separate Trakt addon I can see the Up Next window pop up at the end of the video, whereas using Seren's inbuilt Trakt scrobbler even that window doesn't pop up. This issue sometimes happens with movies as well. I'm at wits end what to do. Please advise.

**Log**

https://paste.kodi.tv/wukuquqewa

**Environment**

 - Android 11
 - Kodi Version 19.4
 - Seren Version 2.1.9
 - Device: Nvidia Shield TV Pro

Thanks and Regards,
ShibajiCh.

**Comment by drinfernoo** [comment]
This *looks* like an issue with the overall internet connection... Are you using a VPN or mobile connection?

**Comment by ShibajiCh** [comment]
Hi @drinfernoo,

No, I'm not using VPN or mobile connection. I'm on a 300 Mbps broadband connection and my Nvidia Shield TV Pro is connected via LAN cable to the router.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @drinfernoo,

I think I've figured out the issue. It was happening because I changed some settings in Seren, like the "Start scrobbling after seconds" to 30 seconds instead of the default 180 seconds and also "Minimum scrobble percentage before marked watched" to 90% instead of the default 80%.

I found the solution in the below page as shown in the following screenshot:

https://forum.kodi.tv/showthread.php?pid=1931093

![IMG_20220412_123354](https://user-images.githubusercontent.com/65297828/162900528-97969e03-e13f-45fd-90bf-6d01e963ed41.jpg)

The reason for the issue as mentioned in the post was as follows:

"That's a timeout. Might want to try again, check your internet connection on the device or setup a startup delay.
It has some problems when the network is not available at startup on some systems."

So Nvidia Shield TV Pro seems to be one such system.

I hope many people like me might see this issue ticket and get the solution.

Thanks for all the help and the amazing addon "Seren"! 🙂

Thanks and Regards,
ShibajiCh.

**Comment by ronfrankhill** [comment]
I am getting the issue on a android TV box but I didn't interfered any of the settings in mentioned by the other user above.

**Comment by ShibajiCh** [comment]
> I am getting the same issue on a android TV box but I didn't interfered with any of the settings that was mentioned by the other user above. I was assuming at time it was because of trakt servers. When they had the issue with the API Slowness and 503 error but they indicated that they corrected issue. I even disabled scrobble to see if it will resolve the issue but it didn't.

Hi @ronfrankhill,

I've found a solution to this issue. You need to create and enter your own Trakt API key in Seren settings, as the default Trakt API key in Seren is getting overloaded with multiple requests to Trakt. I've tried this solution and it works fine for me.

Thanks and Regards,
ShibajiCh.

**Comment by ronfrankhill** [comment]
> > I am getting the same issue on a android TV box but I didn't interfered with any of the settings that was mentioned by the other user above. I was assuming at time it was because of trakt servers. When they had the issue with the API Slowness and 503 error but they indicated that they corrected issue. I even disabled scrobble to see if it will resolve the issue but it didn't.
> 
> Hi @ronfrankhill,
> 
> I've found a solution to this issue. You need to create and enter your own Trakt API key in Seren settings, as the default Trakt API key in Seren is getting overloaded with multiple requests to Trakt. I've tried this solution and it works fine for me.
> 
> Thanks and Regards, ShibajiCh.

Base on my understanding trakt.tv had implemented a fix over 24hrs ago. What you have to do is reauthorize trakt again in Seren. After that you go into tools in Seren for trakt and rebuild or re-sync your trakt. When completed then close Seren and your build. Restart your build or Seren. Everything should be alright. Do that to all your add-ons before you close your build with Seren. I hope that help. I didn't have the issue again at that time.

**Comment by ShibajiCh** [comment]
Hi @ronfrankhill,

That Trakt API fix only worked for the 500 error. Mine was a different one, error 429. The solution to which I have mentioned above. Also, I tried revoking and re-authenticating Trakt before that, but it didn't resolve my issue. After using my own Trakt API key the problem got resolved.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @drinfernoo,

Even though I thought this issue was completely resolved, but still I'm facing the same Trakt sync problem with watched episodes from time to time. Could you please look into it and kindly advise?

Here's my updated Kodi log:
https://paste.kodi.tv/qayiyibamu

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @drinfernoo,

I think the Trakt sync issue where a watched video is not getting marked as watched in Trakt is related to the a4kSubtitles addon, as reported in an old post here in Reddit:

https://www.reddit.com/r/Addons4Kodi/comments/o7hv09/managed_to_stop_the_trakt_issues_with_seren_on_my/?utm_medium=android_app&utm_source=share

It seems if while playing a video if I don't use the a4kSubtitles addon to download a subtitle then the mark as watched in Trakt works fine.

Could you please investigate further and kindly advise?

Thanks and Regards,
ShibajiCh.

**Comment by drinfernoo** [comment]
> Hi @drinfernoo,
> 
> I think the Trakt sync issue where a watched video is not getting marked as watched in Trakt is related to the a4kSubtitles addon, as reported in an old post here in Reddit:
> 
> https://www.reddit.com/r/Addons4Kodi/comments/o7hv09/managed_to_stop_the_trakt_issues_with_seren_on_my/?utm_medium=android_app&utm_source=share
> 
> It seems if while playing a video if I don't use the a4kSubtitles addon to download a subtitle then the mark as watched in Trakt works fine.
> 
> Could you please investigate further and kindly advise?
> 
> Here's my updated Kodi log: https://paste.kodi.tv/alevocepaz
> 
> Thanks and Regards, ShibajiCh.

Not only is there not anything in your log to indicate such an issue being related to a4kSubtitles, the only issues I am seeing in it seem to be related to your internet connection in general, like for example:
```python
2022-04-26 23:32:15.852 T:32377    INFO <general>: SEREN (20): https://torrentgalaxy.mx/torrents.php?&search=banshee+S03E09&nox=1&sort=seeders&order=desc failed - Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 699, in urlopen
                                                       httplib_response = self._make_request(
                                                   ConnectionResetError: [Errno 104] Connection reset by peer
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                   urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.seren/providerModules/a4kScrapers/request.py", line 150, in _request_core
                                                       response = request(None)
                                                   requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

Also, I've [seen that thread before](https://www.reddit.com/r/Addons4Kodi/comments/o7hv09/comment/h31xezd/?utm_source=share&utm_medium=web2x&context=3), and my diagnosis is the same as it was then. I think that whatever's going on here is still related more to your own connection to the internet than anything else.

**Comment by ShibajiCh** [comment]
Hi @drinfernoo,

That's fine, but since so many people are having issues with a4kSubtitles, I guess it's not an isolated issue. However, if I'm not using a4kSubtitles then everything seems to be working fine in Seren. I've even modified my above post and updated it with a new log. You're the expert here, but there's definitely some compatibility issue between Seren's Trakt sync and a4kSubtitles. Nevertheless, thanks for your valuable time and for this amazing addon!

Thanks and Regards,
ShibajiCh.
