### ISSUE TITLE
Looks like something wrong with 'hide watched' function

### ISSUE THREAD

**Issue by muzikherif** [nixgates/plugin.video.seren#752]
Seren showing my tv shows watchlist empty whereas i have shows in my trakt watchlist.With movies watchlist and other list works normal.I m tried force sync and rebuilding database.I didn't get why its happening? Could you help me please? 

[kodi.log](https://github.com/nixgates/plugin.video.seren/files/8492843/kodi.log)

 - Android 11
 - Kodi 19.4
 - Seren 2.1.9

**Comment by tundrablasen** [comment]
Trakt API was down the last days. Works normal now. So your issue should be resolved now.

**Comment by muzikherif** [comment]
> Trakt API was down the last days. Works normal now. So your issue should be resolved now.

Before the server problems i had the same problem and i m still have

**Comment by tundrablasen** [comment]
Have to tried to delete everything, kodi fully delete. And re install everything from scratch. 

I just did that this morning and everything works.

**Comment by muzikherif** [comment]
> Have to tried to delete everything, kodi fully delete. And re install everything from scratch.
> 
> I just did that this morning and everything works.

i thought it does not change the situation so i wasn't did it before but now you change my mind and i made a fresh installation from begin and it solved issue, thanks for changing my mind

**Comment by muzikherif** [comment]
> Have to tried to delete everything, kodi fully delete. And re install everything from scratch.
> 
> I just did that this morning and everything works.

Actually now i m awared after i m changing some options from interface showing empty again.But i found the source of problem, option 'hide watched' which is open by default.Interestingly by default it shows my watchlist but after changing some other settings then 'hide watched' option begin to be problem and i can't see my watchlist(also my shows not marked as watched in trakt), there should be something wrong about this function, at least in my case

**Comment by drinfernoo** [comment]
Watchlist shows things that you *want* to watch, not things you have watched. Seems you're confused on what the watchlist is for.

**Comment by muzikherif** [comment]
> Watchlist shows things that you _want_ to watch, not things you have watched. Seems you're confused on what the watchlist is for.

I know, i didnt want to mean it, i want to mean in my TV shows watchlist which is showing empty when i enable hide watched items, it doesn't have any shows watched before.

**Comment by drinfernoo** [comment]
"Hide Watched" hides items you have already watched, regardless of where they are in the add-on... That seems pretty self-explanatory.

**Comment by muzikherif** [comment]
> "Hide Watched" hides items you have already watched, regardless of where they are in the add-on... That seems pretty self-explanatory.

Normally it should do like you said but i m saying it is hiding my unwatched tv show watchlist.Thats the problem what i want to explain from begin anyway
