### ISSUE TITLE
[REQUEST] alphabetical or recently added sorting for (Trakt) Watchlist.

### ISSUE THREAD

**Issue by tundrablasen** [nixgates/plugin.video.seren#753]
I don’t know what the currently sorting logic is but Newslettern added items to the Trakt Watchlist are shown last in Seren. 

Can that be changed to alphabetically or recently added?

**Comment by drinfernoo** [comment]
Trakt sorting is based on what the website is set to sort as.

Specifically, you can set the sorting method for Watchlist in your user settings on Trakt.

**Comment by tundrablasen** [comment]
Thanks I will check that
