### ISSUE TITLE
[BUG] Issue with Inspect cloud files on scrape

### ISSUE THREAD

**Issue by ShibajiCh** [nixgates/plugin.video.seren#754]
**Describe the bug**

Hi, This issue was already mentioned in Issue ticket #118 and seems to have been resolved at that time. However, it's happening again now.

I noticed that if I have an individual file whether it's a Movie or TV Show then the cloud scraping feature seems to be working fine. Nevertheless, if I have an entire season cached on my cloud then Seren doesn't seem to scrape it from the cloud. I'm using Real Debrid.

Here is a log file:

**Log**

https://paste.kodi.tv/enuxomahum

**Environment**

 - Operating System: Android 11
 - Kodi Version: 19.4
 - Seren Version: 2.1.9
 - Device: Nvidia Shield TV Pro

Thanks and Regards,
ShibajiCh.

**Comment by drinfernoo** [comment]
You know what, I can confirm this. At least using RD, and *some* season packs. Movies and episodes I have in my cloud are scraped just fine, but not all season packs. I tried with season packs from two different shows, and one was picked up, while the other wasn't 🤷‍♂️

It may be worth taking a look into the cloud scraper to see where it's being missed, but it's unlikely to happen for the next update of Seren.

**Comment by ShibajiCh** [comment]
Hi @drinfernoo,

Thanks for your reply!
Hope to see this issue get fixed soon in a future update.

Thanks and Regards,
ShibajiCh.

**Comment by dpetka2001** [comment]
For me it doesn't scrape anything at all from my RD cloud. Not only season packs, but single file movies and episodes as well.
I don't know if this is only related to RD maybe. Can someone with Premiumize or AllDebrid confirm if this is happening?

**Comment by dpetka2001** [comment]
So without knowing anything about this project and clearly from a user experience point of view, i have the impression that the problem is with the way this addon scrapes RD cloud storage. I also tried Fen and it also has the same problem. Then i tried Ezra and that one manages to scrape files on cloud storage just fine. Not trying to offend anyone, just my observations as a mere simple user.

**Comment by dpetka2001** [comment]
Please disregard what I said in my previous posts. It was a misconfiguration problem on my account in terms of the minimum quality I had chosen in filtering results. If I ever have a similar problem in the future, I will open a new issue. Let me clarify that I did not try with seasons as the OP mentioned. Just single files in my cloud storage.
