### ISSUE TITLE
Setting to change frequency of Trakt refresh. Seems to run about every 15 minutes as default. Can't locate anywhere to change it.[REQUEST]

### ISSUE THREAD

**Issue by Frbdb** [nixgates/plugin.video.seren#756]
**Describe the feature you'd like**

A clear and concise description of what the requested feature is.

**Describe alternatives you've considered**

**Additional context**

**Comment by drinfernoo** [comment]
It does run every 13-19 minutes, and there isn't a setting for it, because any more often is more likely to cause issues with Trakt.

**Comment by Frbdb** [comment]
Thanks for the reply. Actually, I was thinking far less often. Upon opening Seren or after six or so hours. Oh well, I'll get used to the notifications. BTW - I just installed it yesterday. Very pleased it!

**Comment by Frbdb** [comment]
S/B pleased with it.
