### ISSUE TITLE
[BUG]Trakt sync never seems to complete...constant "Rebuilding Trakt Sync database, please be patient" messages/errors

### ISSUE THREAD

**Issue by Madddcow** [nixgates/plugin.video.seren#757]
**Describe the bug**
As of today, every 15 mins or so, I'm seeing the "Rebuilding Trakt Sync database, please be patient" message.  This is followed by the error message "There were issues when processing the synchronization with Trakt, please check the log."

I don't think the Trakt sync is completing and the issue seems to occur when syncing movie bookmarks.  I've revoked Trakt authentication multiple times, cleared Seren's cache multiple times, purged Seren's Trakt db file multiple times, restarted Kodi multiple times, rebooted my Shield Pro etc.....but the messages/errors continue to occur every 15 mins or so and it's only Seren that's experiencing this issue.  There are never errors when Venom or The Oath sync to Trakt.

**Log**
Debug log is attached.
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/8532090/kodi.log)

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Perform a forced Trakt sync OR Rebuild database from within Seren's Trakt Sync Tools.

**Environment**
 - Nvidia Shield Pro 2019
 - Kodi Version 19.4
 - Seren Version 2.1.9

Here's my traktSync.db and settings.xml file.
[Archive.zip](https://github.com/nixgates/plugin.video.seren/files/8532338/Archive.zip)

**Other Relevant Information**
The same issue is now happening on my MacBook Pro install of Kodi, and I've never had the problem before today.

**Comment by wasssu** [comment]
I’m having the same problem, same errors.

**Comment by Arathonk** [comment]
Happens here as well.

**Comment by xyzfre** [comment]
Same here but I'm noticing a lot of add-ons are showing the same error on my end started yesterday

**Comment by cgcgcgcgcg** [comment]
Same, hope it's not just a show in my collection -this was mentioned on a past issue-, that would mean I'd have to delete all and add one by one to find the culprit.

**Comment by Madddcow** [comment]
> Same, hope it's not just a show in my collection -this was mentioned on a past issue-, that would mean I'd have to delete all and add one by one to find the culprit.
I really wouldn't be keen on doing this...I've got over a hundred shows in my collection. However, from the log it appears as though the issue is with movie bookmarks, not shows? I could be completely wrong, though.

**Comment by cgcgcgcgcg** [comment]
I checked Trakt API twitter and it mentioned a fix was pushed on 22nd of April.
https://twitter.com/traktapi/status/1514682311337394178
I just reauthorized Seren, Rebuilt Database, and the 15 minute pop up was gone.

**Comment by drinfernoo** [comment]
This should be fixed by Trakt now.

**Comment by Arathonk** [comment]
> This should be fixed by Trakt now.

Yes fixed, however it often hangs a lot of time on some of the databases when rebuilding.

**Comment by drinfernoo** [comment]
The databases can be quite large, and "hangs a lot of time" is pretty common, unfortunately.
