### ISSUE TITLE
[BUG] seren crushes when playing movie from widget 

### ISSUE THREAD

**Issue by Tarek-Depp** [nixgates/plugin.video.seren#759]
** kodi close by it self  when I play a movie from widgets**

Steps to reproduce the behavior, for example:
1. Go to 'choose a movie from widget using any skin has widget option  '
2. Click on 'the selected movie'
3. The movie will run untilthe time  1:11
4. Kodi will close by it self.

*

**Comment by drinfernoo** [comment]
Please provide a log file.
