### ISSUE TITLE
Random shows in “finish watching”

### ISSUE THREAD

**Issue by kbxy88** [nixgates/plugin.video.seren#76]
This is something weird that I’ve noticed. I have a widget setup pointing to Seren - My movies - finish watching.
I notice sometimes random movies appear on there that I don’t actually start watching. Recently something was added and normally I’ll just play it and scrub to the end to remove it. This time I can’t play it because it has no playable sources.

I’m running 18.1 , both Titan Mod skin & Auramod.
Movie: Benjamin Blumchen

I went on my trakt account and can’t even search for this either. I’ve tried selecting “Mark as watched” but it seems it needs me to physically watch it to remove. 
Any suggestions?

**Comment by nixgates** [comment]
In trakt manager of the context menu you can remove playback history for the item. That will remove the item from that list.

As to random movies popping up I've never had this issue, I'll try some test but I'll need more information.

If you wouldn't mind replying to this again as soon as a random movie/episode pops up Ill the meta details for it.

**Comment by nixgates** [comment]
In trakt manager of the context menu you can remove playback history for the item. That will remove the item from that list.

As to random movies popping up I've never had this issue, I'll try some test but I'll need more information.

If you wouldn't mind replying to this again as soon as a random movie/episode pops up Ill the meta details for it.

**Comment by kbxy88** [comment]
Will do , thx for pointing out where to remove playback history
