### ISSUE TITLE
[REQUEST] SIMKL support

### ISSUE THREAD

**Issue by Metigoth** [nixgates/plugin.video.seren#764]
Please, add simkl support. 
It is like trakt. https://simkl.com/
API documentation 
https://simkl.docs.apiary.io/#

**Comment by npmstart-pray** [comment]
Oh yes please; I'd like this as well.

**Comment by drinfernoo** [comment]
Duplicate of #480 and #670.

**Comment by npmstart-pray** [comment]
"Unlikely to be added."  Phooey.
