### ISSUE TITLE
[BUG] "Next Up" and "Recent Episodes" errors out and says to check log

### ISSUE THREAD

**Issue by Liquidrag** [nixgates/plugin.video.seren#765]
**Describe the bug**

When going to "Next Up" and "Recent Episodes" it gives an error. The database has been fully built from trakt and other sections pull up lists fine. I have tested on a fresh install of Kodi 19.4 and the latest version of Seren.

**Log**

(https://paste.kodi.tv/awarexomey.kodi)

Steps to reproduce the behavior, for example:

after rebuilding the database from trakt, go to MyShows>Next Up/Recent Episodes and it errors out

**Expected behavior**

Episodes from my watchlist that airs next should populate

**Environment**

 - OSX Big Sur 11.6.5 and Nvidia shield pro 9.0.2 
 - Kodi Version 19.4
 - Seren Version 2.1.9

**Screenshots and Additional Context**

If applicable, add any other context or screenshots about the problem here.

**Comment by bigpoppapaul** [comment]
I am having an identical problem. 
Problem happens on Windows 10 and 7
Kodi Version 19.4
Seren Version 2.1.9
Latest Auramod for Matrix

Log: https://pastebin.com/4kryeRDy

**Comment by bigpoppapaul** [comment]
I have the same issue. 
Windows 7 _and_ 10
Kodi 19.4
Seren 2.1.9

I had it initially, then it went away for a while, now it's back again but this time ONLY the Next Up doesn't work. 

https://pastebin.com/4kryeRDy

**Comment by Liquidrag** [comment]
Seems to have worked itself out. Possibly something on trakt’s end.
