### ISSUE TITLE
Force view type for skins

### ISSUE THREAD

**Issue by fiddelsticks** [nixgates/plugin.video.seren#767]
**Describe the bug**

**Log**

Please attach or link to and uploaded log file here.
Log files are required, and debug logs are preferable.
See the Kodi wiki for information on [how to get a log file](https://kodi.wiki/view/Log_file/Easy).

**To Reproduce**

Steps to reproduce the behavior, for example:

**Expected behavior**

**Environment**

 - Operating System
 - Kodi Version [e.g. 18.9, 19.1]
 - Seren Version [e.g. 2.1.3]

**Screenshots and Additional Context**

If applicable, add any other context or screenshots about the problem here.

**Comment by fiddelsticks** [comment]
Force view types will not work in Aeon Nox: Silvo skin.  they stay default.  If you set them different in the add-on it still stays the same as default. the nox skin has many options.  You can choose the option and the lets say movies section.  set the view for the first page.  once it loads the second page its back to the default view.  and its not even what I have seen in the add-on. per say  the view is poster.

**Comment by drinfernoo** [comment]
You either need to lock the view in your skin, or find the ID for the view and set them manually in Seren's settings, under the `Use Custom View IDs (Advanced)` setting.
