### ISSUE TITLE
Watchlist showing all items [question/request]

### ISSUE THREAD

**Issue by baxter300** [nixgates/plugin.video.seren#77]
Is it possible to filter out movies which don’t have a release date, or have one later than the current year from the watchlist?

**Comment by nixgates** [comment]
In next public release, Hide Un-Aired Episodes has been changed to Hide Un-Aired Items.

This now also applies to Movies, Seasons, Shows, Episodes

**Comment by baxter300** [comment]
Sounds great, will that include movies that don’t have a planned release date?

**Comment by nixgates** [comment]
@baxter300 this will also affect movies that don't have a planned release date.

If a episode/show/season/movie is identified as unaired or the release/airdate can't be identfied it is considered as not aired.

Could you confirm that the changes have covered everything for you?

**Comment by baxter300** [comment]
@nixgates confirmed that as of .2.30 movies with a future date are hidden, however ones with no planned release date seem to still be getting through

**Comment by nixgates** [comment]
@baxter300 hmmm... Ok I'll dig in a little further, would you mind providing me with an example so I can test

**Comment by baxter300** [comment]
@nixgates Yeah sure, do you just need some example movies or a whole list?
Here are some I’m seeing it with: McClane, The Gentlemen, The Crooked Man, The Hitman’s Wife’s Bodyguard, Escape From Pretoria, Mad Max: The Wasteland, Now You See Me 3

**Comment by bluenote73** [comment]
Hey Nix, also looking for something like this functionality. In my case I'd really like to not be presented with films that are more than likely only going to come back with CAMs or similar crap quality.  It'd be fantastic if you could figure out a way to filter out anything that isn't released on DVD/Netflix.  Failing that, filtering out anything that's still in theaters would be a half measure that would be appreciated.  If you'd rather I submit this as a separate request please say so, in that case sorry for hijacking :)
Seren is awesome, and has really changed my viewing experience so thanks.

**Comment by baxter300** [comment]
Hey @Nixgates any update on this one? We’re the titles enough for you to investigate or did you need access to the specific Trakt list?

**Comment by baxter300** [comment]
Hey @nixgates is this still something being looked at or is it more likely something wrong on my end?

**Comment by nixgates** [comment]
@baxter300 i think this should actually be covered in 2.0.

If not let me know!

**Comment by baxter300** [comment]
Seems to be closed to me, will close now
