### ISSUE TITLE
[BUG] Setting whole shows as UNwatched fucks up on trakt

### ISSUE THREAD

**Issue by TapMeDead** [nixgates/plugin.video.seren#770]
Description says it. If we try to set a previously watched show as unwatched using Seren, it doesn't do anything, -the hourglass will turn for 1½ seconds, then disappears without setting items unwatched at all

I am thinking Seren is overwhelming Trakt with API requests, trying to set X number of episodes as unwatched. There needs to be a timer/delay involved.

And before you ask why, I rewatch shows and movies, and to keep track, I have to set the whole show as unwatched to get it into the Progress window like normal.

**Comment by drinfernoo** [comment]
Sounds like something we'll need a log for to investigate.

**Comment by TapMeDead** [comment]
@drinfernoo -or you could just do the same thing, try to mark a previously watched show as unwatched heh.

**Comment by TapMeDead** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/99356645/168947234-e0853f47-ed07-483d-84ac-ed9768f9930d.png)
![Screenshot_2](https://user-images.githubusercontent.com/99356645/168947242-218f1dac-8a8e-4360-81b8-0d8dd01cfba1.png)


https://paste.kodi.tv/oquzasaxaw.kodi

**Comment by TapMeDead** [comment]
And as I said in the OP, Trakt bans me from setting anything as watched, for a long period of time, after doing that. So if this is happening to everyone using Seren, your addon will get banned for this, after a while, I've seen it before.
@drinfernoo

**Comment by drinfernoo** [comment]
I'll look at the log when I get a chance, but that context item is unlikely to do anything for you. You need to use the "Trakt Manager" item, and then "Mark as Unwatched".

**Comment by TapMeDead** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/99356645/169137580-42aa9392-69b1-492f-aff0-90a79b8461ed.png)

@drinfernoo I need you to tell me which button that would be then, because none of these options say "set show as unwatched on Trakt" :) -there is only the option to "set as unwatched" on each episode, the option is missing if you click the show cover, or even seasons, "set as unwatched" is only avail. if you click an episode. That isn't right if you ask me :)
Maybe change this issue post from "bug" to "enhancement request" please?

**Comment by TapMeDead** [comment]
@drinfernoo that screenie is the Trakt Manager, after clicking the show cover

**Comment by drinfernoo** [comment]
You know what, this is actually already handled in our development branch! The current public release does not show "Mark as Unwatched" in the Trakt Manager (for shows or seasons), but the next version will :+1:

**Comment by TapMeDead** [comment]
@drinfernoo Thanks, closing this thread then, many thanks for your time and knowledge my friend. Looking forward to this update, its the little things that make things better, right :)

**Comment by TapMeDead** [comment]
@drinfernoo yep already checked it out and everything :) Thanks for the headsup too.
