### ISSUE TITLE
[REQUEST] More sci fi movies please

### ISSUE THREAD

**Issue by TapMeDead** [nixgates/plugin.video.seren#771]
There are only around 120 movies in the "Science Fiction" genre search in Seren. Feels like the list is cut short by something, something that is not like that in most other genres. Could you look at this when you have  5 min spare please? sci fi is my fave genre, and I've watched almost all of the ones coming up in Seren hehe

**Comment by whambulancePilot** [comment]
Set your Base List Type for Genres to `Most Popular` instead of `Trending` in Seren's general category settings. There is way more than 120 items when you are not on `Trending`.

...and you can also search and like Trakt Lists.
https://trakt.tv/search/lists?query=sci-fi

**Comment by drinfernoo** [comment]
For what it's worth, the next version will have that set as the default 👍
