### ISSUE TITLE
[BUG] Kodi crashes when going to Seren tools

### ISSUE THREAD

**Issue by MixedMatched** [nixgates/plugin.video.seren#772]
**Describe the bug**

When trying to go to the tools section of Seren, Kodi encounters a segfault and crashes.

**Log**

Console output:
> ➜  ~ kodi
/usr/bin/kodi: line 186: 22435 Segmentation fault      (core dumped) ${KODI_BINARY} $SAVED_ARGS
Crash report available at /home/ads/kodi_crashlog-20220518_210550.log

[Full log](https://gist.github.com/MixedMatched/5743cb2d760fb072b7f52fb989deacf0)

**To Reproduce**

1. Do a fresh install of Kodi from the Manjaro community repo
2. Add Nixgates repo to file sources, and install the repo
3. Install Seren
4. Go to Seren's tools section

**Environment**

 - Manjaro KDE
 - Kodi 19.4-5 from the Manjaro Community repo
 - Seren 2.1.9

**Comment by drinfernoo** [comment]
This appears to be an issue with the Python version used on your system (Python 3.10) not supporting a particular call in Kodi's Python API. I'd recommend installing Python 3.9 instead, as that is the highest version used by Matrix at this time.
