### ISSUE TITLE
[BUG] Seren not Syncing with Trakt

### ISSUE THREAD

**Issue by TheCookieMonster70** [nixgates/plugin.video.seren#773]
**Describe the bug**

Seren not syncing with Trakt.

**To Reproduce**

Steps to reproduce the behavior, for example:
1. Go to  Trakt rebuild database
2. Errors out

**Comment by bigpoppapaul** [comment]
Same issue, not with mine but with a family members system. 
Interestingly, mine syncs just fine, theirs starts, times out with a "synchronization issue" and keeps restarting every few minutes. 
Have tried clearing cache, disconnecting from Trakt, reauthorizing and then rebuilding database. Also attempted the wipe data and starting Seren from scratch. 

Nvidia Shield running 19.4 and the Seren 2.1.7 

https://pastebin.com/AWHj3Fpd

**Comment by cgcgcgcgcg** [comment]
Same issue wuth @bigpoppapaul since yesterday on my already installed Seren.
Tried a clean Kodi Seren only install using Flatpak on Arch Linux.
After installing Seren rebuilding database seemed ok, but on next restart -this log-, it started rebuilding the database again.
See line 1040.
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/8793049/kodi.log)

**Comment by jakkerson** [comment]
Fix here:

https://github.com/nixgates/plugin.video.seren/pull/774

**Comment by bigpoppapaul** [comment]
> Fix here:
> 
> #774

Thank you for the response. Implemented it. However, it seems there is something else going on here. It definitely stayed up longer before failing due to the longer timeout, but still failed in the end. That being said, it was syncing for a good 10-12 minutes, which is crazy. He watches only a few more shows than I do and mine is done in 2 minutes or less and successfully. I'd seen in a thread months ago that maybe certain shows' metadata was causing these problems, maybe that's still the issue.

**Comment by jakkerson** [comment]
> > Fix here:
> > #774
> 
> Thank you for the response. Implemented it. However, it seems there is something else going on here. It definitely stayed up longer before failing due to the longer timeout, but still failed in the end. That being said, it was syncing for a good 10-12 minutes, which is crazy. He watches only a few more shows than I do and mine is done in 2 minutes or less and successfully. I'd seen in a thread months ago that maybe certain shows' metadata was causing these problems, maybe that's still the issue.

Would be interesting to see if after implementation the issue is still a timeout or something else. Could you retry and post a log please? Im sure that would help the addon devs too.

**Comment by bigpoppapaul** [comment]
> > > Fix here:
> > > #774
> > 
> > 
> > Thank you for the response. Implemented it. However, it seems there is something else going on here. It definitely stayed up longer before failing due to the longer timeout, but still failed in the end. That being said, it was syncing for a good 10-12 minutes, which is crazy. He watches only a few more shows than I do and mine is done in 2 minutes or less and successfully. I'd seen in a thread months ago that maybe certain shows' metadata was causing these problems, maybe that's still the issue.
> 
> Would be interesting to see if after implementation the issue is still a timeout or something else. Could you retry and post a log please? Im sure that would help the addon devs too.

Sure, here is the debug log AFTER the extended timeout implementation. I couldn't sit there and watch to see if it failed or not as I was busy, but when I returned to it, it was no longer syncing. 
https://pastebin.com/8HAxpwFA

**Comment by jakkerson** [comment]
> > Would be interesting to see if after implementation the issue is still a timeout or something else. Could you retry and post a log please? Im sure that would help the addon devs too.
> 
> Sure, here is the debug log AFTER the extended timeout implementation. I couldn't sit there and watch to see if it failed or not as I was busy, but when I returned to it, it was no longer syncing. https://pastebin.com/8HAxpwFA

Hi, thank you but I think pastebin took it down? Its a page not found link now.

**Comment by cgcgcgcgcg** [comment]
> > > Fix here:
> > > #774
> > 
> > 
> > Thank you for the response. Implemented it. However, it seems there is something else going on here. It definitely stayed up longer before failing due to the longer timeout, but still failed in the end. That being said, it was syncing for a good 10-12 minutes, which is crazy. He watches only a few more shows than I do and mine is done in 2 minutes or less and successfully. I'd seen in a thread months ago that maybe certain shows' metadata was causing these problems, maybe that's still the issue.
> 
> Would be interesting to see if after implementation the issue is still a timeout or something else. Could you retry and post a log please? Im sure that would help the addon devs too.

Still have my clean Kodi with just Seren:
1st log, I open Kodi and just manually rebuild the database. No issues as quick as before.
[kodi1.log](https://github.com/nixgates/plugin.video.seren/files/8794308/kodi1.log)

2nd log, I just open Kodi and try 4 movies, no sign of forced rebuilding of the database.
[kodi2.log](https://github.com/nixgates/plugin.video.seren/files/8794309/kodi2.log)

**Comment by jakkerson** [comment]
> 

Log 1 looks correct, all synced up and completed.

Log 2 as you say has not synced yet but there is no issue with that as the log points out here:
`2022-05-30 00:12:05.278 T:262      INFO <general>: SEREN (-1): Seren, Running Path - {'action': 'syncTraktActivities'}
2022-05-30 00:12:05.297 T:262      INFO <general>: SEREN (-1): Activities endpoint called too frequently, skipping sync
2022-05-30 00:12:05.297 T:262     ERROR <general>: SEREN (-1): Activities Sync Failure: Unable to connect to Trakt or activities called too often
2022-05-30 00:12:05.297 T:262     DEBUG <general>: SEREN: Processing Time -      2ms - TraktSyncDatabase.sync_activities
2022-05-30 00:12:05.297 T:262     DEBUG <general>: 
                                                   
2022-05-30 00:12:05.297 T:262     DEBUG <general>: SEREN: Processing Time -     19ms - syncTraktActivities`

Seren is not syncing due to the rate limiting on the api calls, it will sync just give it some time, everything else looks good to me.

**Comment by bigpoppapaul** [comment]
> > > Would be interesting to see if after implementation the issue is still a timeout or something else. Could you retry and post a log please? Im sure that would help the addon devs too.
> > 
> > 
> > Sure, here is the debug log AFTER the extended timeout implementation. I couldn't sit there and watch to see if it failed or not as I was busy, but when I returned to it, it was no longer syncing. https://pastebin.com/8HAxpwFA
> 
> Hi, thank you but I think pastebin took it down? Its a page not found link now.

Looks like they did, didn't know that was a thing now. 

Here it is: 
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/8794330/kodi.log)

**Comment by jakkerson** [comment]
> > > > Would be interesting to see if after implementation the issue is still a timeout or something else. Could you retry and post a log please? Im sure that would help the addon devs too.
> > > 
> > > 
> > > Sure, here is the debug log AFTER the extended timeout implementation. I couldn't sit there and watch to see if it failed or not as I was busy, but when I returned to it, it was no longer syncing. https://pastebin.com/8HAxpwFA
> > 
> > 
> > Hi, thank you but I think pastebin took it down? Its a page not found link now.
> 
> Looks like they did, didn't know that was a thing now.
> 
> Here it is: [kodi.log](https://github.com/nixgates/plugin.video.seren/files/8794330/kodi.log)

Thank you.

Looking through the log i see the call for rebuilds and I see missing items getting added and the job completing. I dont see any errors or issues at all in the log. What issues are you seeing on screen?

**Comment by drinfernoo** [comment]
@jakkerson A similar fix was actually already made in our development branch recently.

This issue should be fixed as of the next release.

**Comment by bigpoppapaul** [comment]
> > > > > Would be interesting to see if after implementation the issue is still a timeout or something else. Could you retry and post a log please? Im sure that would help the addon devs too.
> > > > 
> > > > 
> > > > Sure, here is the debug log AFTER the extended timeout implementation. I couldn't sit there and watch to see if it failed or not as I was busy, but when I returned to it, it was no longer syncing. https://pastebin.com/8HAxpwFA
> > > 
> > > 
> > > Hi, thank you but I think pastebin took it down? Its a page not found link now.
> > 
> > 
> > Looks like they did, didn't know that was a thing now.
> > Here it is: [kodi.log](https://github.com/nixgates/plugin.video.seren/files/8794330/kodi.log)
> 
> Thank you.
> 
> Looking through the log i see the call for rebuilds and I see missing items getting added and the job completing. I dont see any errors or issues at all in the log. What issues are you seeing on screen?

I had to leave my brother's place. I will take a look over the next few days and see if it keeps retrying to build the database like it was previous to the fix. Thanks for all your input.

**Comment by drinfernoo** [comment]
This should be fixed, by way of modifying the timeout, in 2.2.0 👍
