### ISSUE TITLE
[BUG] reuselanguageinvoker Incorrect in addon.xml for default of settings.xml 

### ISSUE THREAD

**Issue by jakkerson** [nixgates/plugin.video.seren#776]
reuselanguageinvoker is set to <reuselanguageinvoker>false</reuselanguageinvoker> at https://github.com/nixgates/plugin.video.seren/blob/master/addon.xml#L18 despite https://github.com/nixgates/plugin.video.seren/blob/master/resources/settings.xml#L463 stating the default is "Enabled"

Toggling fixes the issue but the issue is clearly a bug on a fresh install.

**Comment by drinfernoo** [comment]
This one should be addressed in the next update of Seren. Thanks for bringing it to our attention 👍

**Comment by drinfernoo** [comment]
This should be fixed as of 2.2.0 👍
