### ISSUE TITLE
[BUG]Orion scrapers error

### ISSUE THREAD

**Issue by Safeduck00** [nixgates/plugin.video.seren#779]
**Describe the bug**

When Orion scrapers are enabled, playback fails. 

**Log**

http://paste.kodi.tv/xefosageca

**To Reproduce**

Steps to reproduce the behavior, for example:
1. Integrate orion
2. Click on an item to scrape autoplay or source select does not matter
3. See error

**Expected behavior**

Playback begins or returns source list. 

**Environment**

 - Operating System -  Nvidia Shield
 - Kodi Version 19.4 Kodinerds Mavenbuild
 - Seren Version 2.2.0

**Screenshots and Additional Context**

Disabling Orion providers resolves the issue. 

Thanks!

**Comment by drinfernoo** [comment]
Sounds like an Orion error.

**Comment by Safeduck00** [comment]
Okay thanks for checking it out.
