### ISSUE TITLE
Trakt stuff missing from Seren

### ISSUE THREAD

**Issue by tsteven9** [nixgates/plugin.video.seren#78]
Hello. I noticed that all my Trakt stuffs (collection, progress, lists...) are non existent in Seren. Usually there's two directories with My TV Shows and My Movies but I can't seem to find them anywhere. Thanks.

**Comment by baxter300** [comment]
Hope it’s ok for me to chime in here, I think if you authorise your Trakt account within Seren and then exit the addon and go back in you should see My Movies/My Shows

**Comment by tsteven9** [comment]
> Hope it’s ok for me to chime in here, I think if you authorise your Trakt account within Seren and then exit the addon and go back in you should see My Movies/My Shows

Hey there :) I tried that but no positive results :( Thanks for the tip tho!

**Comment by nixgates** [comment]
Seems like it's to do with Kodi caching the menus. I've disabled this for the next update which should resolve this issue.

In the interim, please make sure your Trakt account is successfully authorized (your account name should show in the settings menu) and restart kodi.

If this fails to work try re-authorizing Trakt again.

**Comment by nixgates** [comment]
@tsteven9 if you wouldn't mind answering a question, are you running Seren on SPMC?

**Comment by nixgates** [comment]
Closing this issue due to no response from user.

If you would like this issue re-opened please let me know.
