### ISSUE TITLE
[BUG] Most authentications not working on Fire Stick, simply brings up an error

### ISSUE THREAD

**Issue by Depressomane** [nixgates/plugin.video.seren#781]
**Describe the bug**

Whenever I try to run Seren on my Fire Stick, I am unable to authenticate with anything but Trakt. An example in the logifle is below with Real-Debrid. 

**Log**

https://pastebin.com/X4DstRgm

**To Reproduce**

Steps to reproduce the behavior, for example:
1. Go to Settings
3. Click on Accounts
4. Scroll down to "Authorize with Real-Debrid", and click on it.
5. "Seren Error: See log for more information". 

**Expected behavior**

I expected to be able to authenticate on another device with the code on the screen just like Trakt and other applications.

**Environment**

 - Fire OS
 - Kodi 19.4
 - Seren Version 2.1.9

**Comment by drinfernoo** [comment]
Update to Seren 2.2.1, and see if that helps.

**Comment by Depressomane** [comment]
Updated to Seren 2.2.1, and the same exact error happens in the log. 

https://pastebin.com/g1vYX8Cg

Pasted to show the different time and that 2.2.1 is loaded.

**Comment by XSWG88** [comment]
Try a clean install by wiping addon data. I noticed that if you trigger one function when another hasn't been completed, you'll get general errors. Like clearing cache when you tried to clear last Trakt sync date prior to that finishing.
