### ISSUE TITLE
Change info language

### ISSUE THREAD

**Issue by orenavrahami** [nixgates/plugin.video.seren#782]
Please add the ability to change information from English to other languages .
This is the best addon on kodi but its one of few that has not got  info language  change  option .
Regard
oren

**Comment by drinfernoo** [comment]
Seren attempts to gather metadata information in the "User Interface Language", as set in Kodi's language settings.

We fall back to English if there isn't metadata available for the item in that language, and only TMDb gives foreign language metadata with any reliability.

Try changing your user interface language, and also make sure the "Metadata Location" in Seren's settings is set to TMDb.

**Comment by orenavrahami** [comment]
Thank you for replying.
I have  followed  your instruction but unfortunately nothing has change.
I did change  the metadata location to "trakt" and  Finley got to change to my language but than had no providers results ,
Changed again to tmdb and got results again.
Go figure 😊
If you are able to fix it 
it would be great and if not i thank you anyway .
Regards
Oren
