### ISSUE TITLE
Seren now only returns errors on multiple devices after v2 update

### ISSUE THREAD

**Issue by Madddcow** [nixgates/plugin.video.seren#785]
**Describe the bug**

Seren just returns errors when trying to play anything

**Log**
http://paste.ubuntu.com/P/639WNGBD37/

I've been away for a couple of days and found that Seren updated on all of my various devices; now none of them work.

Any way to fix the problem?  I've tried uninstalling/reinstalling Seren and that hasn't worked.

**Comment by Madddcow** [comment]
Ok, I've found that the problem is related to Orion integration with Seren.  As soon as I removed the Orion integration, Seren works again on my devices.

drinfernoo, are you able to fix Seren so that it'll work with Orion? Orion sources are fantastic.

**Comment by drinfernoo** [comment]
Your log link doesn't work. In any case, Orion needs to fix their provider so it'll work with Seren.
