### ISSUE TITLE
Unable to get hosters

### ISSUE THREAD

**Issue by Arthur1967** [nixgates/plugin.video.seren#788]
bug**
I use package 2.36 and up until a couple weeks ago I could get hosters But lately I haven't been able to get them is there a setting that I have wrong 19.4 on a 4K fire stick

**Log**

Please attach or link to and uploaded log file here.
Log files are required, and debug logs are preferable.
See the Kodi wiki for information on [how to get a log file](https://kodi.wiki/view/Log_file/Easy).

**To Reproduce**

Steps to reproduce the behavior, for example:

**Expected behavior**

**Environment**

 - Operating System
 - Kodi Version [e.g. 18.9, 19.1]
 - Seren Version [e.g. 2.1.3]

**Screenshots and Additional Context**

If applicable, add any other context or screenshots about the problem here.

**Comment by drinfernoo** [comment]
You're using a very old (January 2021) provider package, and the included hoster providers probably don't work anymore. Without a log, there's nearly no way to tell, but I know that all of the hoster providers have been removed from a4kScrapers (around 9-12mo ago) because they quit working.

**Comment by Arthur1967** [comment]
Thought that might be the problem I’ll just use the Newest package I sure
wish they would include hosters with it though thanks
