### ISSUE TITLE
Sort by date collected for trakt movie collection not working

### ISSUE THREAD

**Issue by pgpold** [nixgates/plugin.video.seren#789]
It keeps sorting trakt movie collection alphabetically even though sort by date collected is selected.  Sort by date collected is working for trakt tv show collection.

**Comment by XSWG88** [comment]
Try turning off the paginate checkbox for the items that are in your collection. I noticed that it broke the sort alphabetically option for the collection but unchecking the box fixed the issue.

**Comment by pgpold** [comment]
This should be reopened as this issue is still ongoing even in the current updated version.   Sort by date collected is not working for both movies and tv shows and only sorts alphabetically even with the other option.  Paginate is already off.
