### ISSUE TITLE
[REQUEST] Invert SmartPlay button text color for skins using a light button background color

### ISSUE THREAD

**Issue by eengert** [nixgates/plugin.video.seren#791]
Would it be possible to detect the button background color of the skin and invert text color as necessary?  I'm using a new skin called Arctic Horizon 2.  There are options in the skin to define the highlight color (which determines the background color of elements such as buttons) and to invert text color (changes highlighted/focus text color to dark).  With a light button background color, the Play and Close button text in the SmartPlay dialog is not visible.

![IMG_1168](https://user-images.githubusercontent.com/33561812/173082774-dea98b10-e960-436b-be7b-00f6b339d02c.jpeg)

**Comment by drinfernoo** [comment]
Just change the highlight color in Seren's settings, and it'll be that color in Seren's windows.
