### ISSUE TITLE
Library Integration 

### ISSUE THREAD

**Issue by ruegnueg** [nixgates/plugin.video.seren#8]
As great as your addon is, I'll never abbandon the kodi library, it's way faster browsing it then trough any addon 😉 and way more convenient than using Trakt lists. And yeah I could use widgets and custom skin menus etc. but still the library tops it all. 

So I'll wait and hope this feature comes. 

But as I said, great work.

**Comment by nixgates** [comment]
I'll look into it, but with the way Seren works it may not be possible or may be slightly slower than other add-ons.

**Comment by SerpentDrago** [comment]
@nixgates Don't worry about Library integration , This job is best handled by a Metalliq fork thats almost ready for release , fully working in 17 and 18 .  Smartplay and normal play players are already fully working . Library integration also

**Comment by ruegnueg** [comment]
which fork? I tried awhile ago wraith and metalliq and it was never as good as a native library integration from the addons itself, auto update shows etc 🤔

**Comment by jorritsmit** [comment]
I would like to know as well. I have added some functionality to the first metalliq (two sync trakt) and would like to integrate that somewhere

**Comment by jorritsmit** [comment]
You are right
