### ISSUE TITLE
[REQUEST] Folder Scraping Feature

### ISSUE THREAD

**Issue by sathish804** [nixgates/plugin.video.seren#800]
**Describe the feature you'd like**

Please implement the Folder scraping option in the addon to scrape the sources from the WebDav configured.

**Describe alternatives you've considered**

As of no no alternatives found.

**Additional context**

Debrid services like RD and Premiummize has WebDav feature which can be configured as a Media Source and can be accessed as a folder from Kodi. If the Debrid account already has a Torrent cached to their account then this feature would make scraping lighting fast.

**Comment by npmstart-pray** [comment]
I've not had need to dive into this functionality recently added by RD, but I can see how it might come in handy. Maybe this will get reopened.
