### ISSUE TITLE
Play Next

### ISSUE THREAD

**Issue by Rookie-Farmer** [nixgates/plugin.video.seren#801]
Not sure if this is a bug, or a setting I am missing or what, but here is my situation.

I have 2 deployments that act differently even though the settings are seemingly similar (I did a stare and compare of every setting, and they match)

1)  Installed on an NVIDIA Shield device.
 - When I am using the "Next Up" list, and I watch an episode of a show that has additional episodes available, it will play the next episode **of that show**

2) Installed on a Windows 10 PC
 - When I follow the same steps above, instead of playing the next episode of that show, it plays the **next show** in the "Up Next" list.

Ideally I would like them both to act like the first deployment, but wondering why the 2 would act different?

**Comment by whambulancePilot** [comment]
On your windows PC, you must have "Play next video automatically" enabled in Kodi's player settings. 

It's either that or you are using "Play from Here" from the context menu because there is no code in Seren that could such a thing.
