### ISSUE TITLE
[BUG] Cannot download from source any more

### ISSUE THREAD

**Issue by nutstool** [nixgates/plugin.video.seren#803]
There was previously an option for downloading from the source on Seren but this seems to have disappeared, despite the fact you can still choose your downloads location in the settings. Is there something I'm missing or has this option in Seren been removed and the downloads location in settings is now redundant?

**Comment by drinfernoo** [comment]
The button to download was removed, but you can still do it by opening the context menu (right-click, long press, or `c`) on a source.
