### ISSUE TITLE
Seren: Updates 

### ISSUE THREAD

**Issue by ronfrankhill** [nixgates/plugin.video.seren#804]
When will Seren be updated again? It has been over a month. I use it a lot for trakt. Seren is great 😃👍 but it would be great if it receive updates on it once a month to make sure that everything is running perfectly.
The reason that l asked is that it's not showing Roswell New Mexico S4 Ep 5 in the TV section for Next. That episode aired on 11 July. Maybe other users might have that issue for different TV series.

**Comment by drinfernoo** [comment]
Seren does not need an update just to show new episodes. You could try rebuilding your database, but if it isn't showing, there may be a different issue.

Aside from that, there has never been a schedule for releases, and I don't see anything coming down the line anytime specifically soon.
