### ISSUE TITLE
[REQUEST] Add support for stremio addons

### ISSUE THREAD

**Issue by I-Do-Ketamine** [nixgates/plugin.video.seren#807]
**Describe the feature you'd like**

Add support for stremio addons without the need for any debrid services.

**Describe alternatives you've considered**

It should be similar to how torrentio is implemented into seren. The goal should be to return "clean links" (https) links from stremio addon user provides.

**Additional context**

There are some really good stremio addons that could bring seren to the next level.

**Comment by PodTT** [comment]
I was asking for support for stremio addons as providers for seren
