### ISSUE TITLE
[Question] Are Genres supposed to be here?

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nixgates/plugin.video.seren#809]
**Summary** (I had too much time making this)
![Genres](https://user-images.githubusercontent.com/62456796/180501812-fc5c70ae-58f5-47ba-9b5c-1fe33ff3e5d9.png)
**Discover TV Shows - Genres Before**
![Genres TV Shows](https://user-images.githubusercontent.com/62456796/180501830-758035e2-f74a-488f-b1d5-ae0e4a9a23f1.png)
**Discover Movies -Genres After**
![Genres Movies](https://user-images.githubusercontent.com/62456796/180501836-3fb74144-e61c-44f9-b902-9798167897e4.png)

Hey there, sorry for bothering you but when i was working on new icons for Seren and i couldn't help but notice something about a specific menu item and was wondering if this was supposed to be this way or was just a placement error by mistake. I noticed the category menu "Genres" in Discover Movies and Discover TV Shows were in different placements where one was before "Years" and the other was after "Years."

Was this a placement error by mistake or was it supposed to be this way? 😂

**Comment by Goldenfreddy0703** [comment]
Btw, i made some icons for seren so if anyone would like to use them, feel free too. 
[Seren Icons - Coloured.zip](https://github.com/nixgates/plugin.video.seren/files/9170028/Seren.Icons.-.Coloured.zip)
[Seren Icons - White.zip](https://github.com/nixgates/plugin.video.seren/files/9170030/Seren.Icons.-.White.zip)

**Comment by drinfernoo** [comment]
They're just in a different order 🤷

**Comment by Goldenfreddy0703** [comment]
> They're just in a different order 🤷

True, I wanna know if it's a placement error by mistake or if was it supposed to be this way.

**Comment by drinfernoo** [comment]
I guess it's a "mistake", but there's no set order for how the menus are supposed to be... As long as they work, is there an issue?

**Comment by Goldenfreddy0703** [comment]
On no, I was just wondering sense I took the time to make a meme about it. There is no issue and we could fix that with autowidget. 

Thank you for telling me tho.
