### ISSUE TITLE
Seren theme for Arctic Horizon 2

### ISSUE THREAD

**Issue by ambulancePilot** [nixgates/plugin.video.seren#811]
Just wondering if anyone has any plans or intention of creating a theme for the results screen that works with Arctic Horizon 2?

When I was using the first Arctic Horizon, I enjoyed the associated Seren theme.

Thanks and good work with the previous updates!

**Comment by drinfernoo** [comment]
The default theme works fine in AH2. If you're looking for a theme that *looks like* AH2, then you may want to have a look at https://github.com/nixgates/plugin.video.seren/wiki/Themes. That hasn't been updated in some time, and I know that the 2.2.0 release in particular broke a few of the properties and IDs, but it may give you an idea of where to start.

**Comment by RED-DRAGON81** [comment]
I have the same issue and it was posted on Reddit I thought I tagged drinfernoo https://www.reddit.com/r/Addons4Kodi/comments/t4io7i/seren_scraping_themes_updated/?utm_medium=android_app&utm_source=share

**Comment by Goldenfreddy0703** [comment]
Hey sorry i didn't see this sooner but here is a Seren theme for Arctic Horizon 2. It was the original theme from auramod but modified to work with Arctic Horizon 2. 

Hope this helps
https://github.com/Goldenfreddy0703/seren.theme.ah2

**Comment by RED-DRAGON81** [comment]
> 

Would this work with auramod or no if not what would need to be changed to make it work as the only issue is what I showed in the screenshot

**Comment by Goldenfreddy0703** [comment]
I don't think so cause I only modified Artic Horizon 2 but I could possibly make it work work auramod, just need to modify some stuff.

**Comment by Goldenfreddy0703** [comment]
> what I showed in the screenshot

The labels so that the information can show up.

**Comment by RED-DRAGON81** [comment]
> > what I showed in the screenshot
> 
> The labels so that the information can show up.

That would be great I tried to see what changed in seren to see if I could just copy the change to make it work but I know nothing about this stuff lol

**Comment by Goldenfreddy0703** [comment]
@RED-DRAGON81 , This is just a little per-release i made for Auramod so give that a try by installing the .zip file. 

`Seren -> Tools > Open Settings Menu -> Theme Manager -> Interface > (themes section) Install Theme ->  Browse`

[Aura Mod.zip](https://github.com/nixgates/plugin.video.seren/files/9273836/Aura.Mod.zip)

**Comment by Goldenfreddy0703** [comment]
Ok guys, i have gone ahead and the theme compatible with AuraMod. 

Artic Horizon 2 Theme
https://github.com/Goldenfreddy0703/seren.theme.ah2

AuraMod Theme
https://github.com/Goldenfreddy0703/seren.theme.auramod
