### ISSUE TITLE
[REQUEST] filter MKV

### ISSUE THREAD

**Issue by djdirty60** [nixgates/plugin.video.seren#812]
Good day

Is it possible that the MKV files can be filtered, related to DV?

**Comment by drinfernoo** [comment]
If you filter out MKV files, you'll be missing **far** more than just DV, since it is likely the most commonly used container for video files.

Filter out DV instead.

**Comment by djdirty60** [comment]
I mean that the MKV dolby vision file doesn't work on kodi via the shield, hence the question for filtering the MKV because the rest does work to play dolby vision
