### ISSUE TITLE
[BUG] Seren scrape movies with the "Translated Title" not the "Original Title"

### ISSUE THREAD

**Issue by psp2111-ADSLGATE** [nixgates/plugin.video.seren#813]
**Describe the bug**

Seren scrape movies with the "Translated Title" instead of the "Original or English Title" which cause no or low result while scraping. Because most torrents sites use "Original or English Title" as file name.
I use Arabic as interface language for Kodi, as you know Seren change the metadata language to match kodi interface language. (a feature I really love about Seren).
it is only seems to affect Movies section of Seren with "Translated Title", TV show section works just fine while scraping for sources.
I tried other languages quickly like Dutch and Japanese same behavior with no or low result.
I also tried to change metadata location, same behavior with TMDb and Trakt. (TVDB didn't find any "Translated Title" so it is my temporally fix for the bug).
"Show original titles" does not fix the Bug. It only Display the "Original Title" of the movie.

**Log**

I will provide it if needed. 

**To Reproduce**

Steps to reproduce the behavior, for example:
clean Seren cache before trying this 
1- go to Seren settings make sure the Metadata location set to TMDb or Trakt. Make sure "Show original titles" is off.
2- Go to kodi settings and change interface language to any language (I recommend Dutch because it will give the best example)
3- Go to Movies Section in Seren and try any movies with "Translated Title".
    - I recommend to go to Animation and try "Moana" (will give you one link with translated title "Vaiana" in Dutch). 
    
 

**Expected behavior**

When the movie has a Translated Title, Seren should fallback to the Original Title of the movie for scraping sources.

**Environment**

 - Windows + Coreelec
 - Kodi 19.4
 - Seren 2.2.1

**Screenshots and Additional Context**

I will provide it if needed.

**Comment by psp2111-ADSLGATE** [comment]
can anyone confirm or reproduce this bug?
or is it cause by Seren or A4Kscrapers?

I really want to use TMDb as metadata to show up info in AH2 player osd while using arabic as interface language.

**Comment by SET19724** [comment]
I have this in libreelec.
Seren search by translated titles in Polish language.
After change Kodi language to English then i have sources if not changed big zero.

**Comment by psp2111-ADSLGATE** [comment]
> I have this in libreelec+PC. Seren search by translated titles in Polish language. Even with option use orginal titles. After change Kodi language to English then i have sources if not changed big zero.
> 
> ----EDIT Quick fix what i found in metadata use TVDB provider but with that option i don't have description about movie in my language ;). But search works i wait for fix by Seren

Thank you for replying.

Yeah I know about using TVDB as a metadata provider and I mention it in the post as temporarily fix while you can use what ever language for your Kodi interface.
downside for this is you dont get any info translated to your language for movies, but you will get some for TV Shows.

The best work around I found so far is to use TMDb Helper with seren as a main player. then change the metadata language to whatever you want in TMDb Helper settings. after down that use TMDB Helper as a main addon instead of seren + TMDb Helper is way faster than seren in term of loading widgets and menus.

only downside of TMDB HELPER is doesn't fallback to english if no info available for your language.
