### ISSUE TITLE
[REQUEST] Make the addon find better quality trailers

### ISSUE THREAD

**Issue by TapMeDead** [nixgates/plugin.video.seren#815]
**Describe the feature you'd like**

Better than 720p trailers when we ask to watch a trailer from the Information window

**Describe alternatives you've considered**

**Additional context**

720p was 10 years ago, Seren should give us 1080p if available, 720 is very nearly unwatchable on systems set up for 1080.

**Comment by psp2111-ADSLGATE** [comment]
That YouTube addon fault not Seren. if want more than 720p resolution from YouTube you need to enable "MPEG-DASH"
 
Go to "Kodi add-on repository" and install "YouTube addon" from Video Add-ons and "InputStream Adaptive" from VideoPlayer InputStream.
after that go to YouTube addon Settings and enable "use MPEG-DASH" and change video quality to whatever you want.
1080p Trailers should work now.

Note: you don't need to add your own API Keys for YouTube if you just want to play the trailers.

**Comment by TapMeDead** [comment]
@psp2111-ADSLGATE Thank you, did not know that we can do this ourselves. You rock!
