### ISSUE TITLE
[REQUEST] Smart Play display style option for use of external addon Up Next

### ISSUE THREAD

**Issue by titelheld** [nixgates/plugin.video.seren#819]
**What?**

An option to use the external addon Up Next to manage the display style and other settings for next episode/still watching notifications.

**Where?**

Settings>Playback>Smart Play>Smart Play Display Style>(Options: Fancy, Background Task, **Up Next**)

**Why?**

I recently tried out the Gaia addon and found this option in its settings and thought it would be a great addition to a future Seren release. Just as with a4ksubtitles having both Up Next and Seren installed at the same time leads to double notifications/setting set in one addon affecting the setting of the other. (Not sure why this is exactly but I assume Seren uses a integrated version of Up Next)
As the Play Next addon allows for more episode specific setting than Seren (display duration based on episode length etc.) as well as using a visually more pleasing notification style, this change would help Seren users better customize their Kodi experience to their likening.

**Comment by lennon1997** [comment]
I managed to make this work by setting pre-emptive scraping to on the smart play to fancy, then set the timeout to 10 seconds and switch smart play from fancy to background task and the seren next up window should stay hidden while the external next up display will show and function correctly. 

Hope this helps anyone with this issue out!
