### ISSUE TITLE
[Feature Request] Uncached source selection for cache assistant

### ISSUE THREAD

**Issue by Zblorg** [nixgates/plugin.video.seren#82]
Hi,
~~a very useful feature would be to allow us to chose which link the cache assistant puts in our debrid account.~~ Turns out you can already.

Would also be nice to be able to cache uncached torrents even when some are available as sometimes the ones already cached are not suitable (files too big, quality too small, wrong language).

**Comment by lukehansford** [comment]
This would be a great feature.

I find many times some TV show season lack a decent source cached on real debrid. 

I go to the Rarbg (TorrentAPI) site and find a Blu-ray season pack that just needs caching and in less than 24 hours it is cached. 

If this feature is added can it be made so it caches the entire season pack when you cache it as currently I believe with the current cache assist function it will only select the episode you are scraping when it adds the season pack to real debrid to be cached. 

It would be much more helpful if it added the entire season pack for that show.

**Comment by nixgates** [comment]
@lukehansford this is already implemented at the moment, with the new changes to RD's API and public release of 0.2 all caching to RD servers now selects all media files within the item.

**Comment by lukehansford** [comment]
That is really good. If we can get the option to be able to see non cached links and cache them that would be great. It would also have the benefit of more cached links on RD for everyone and we won't need visit the Torrent site and copy the magnet link into real debrid.

Maybe a context menu option where we can select one item to cache at a time such as a season pack and being able to see the seeds for each torrent file before we select it.

**Comment by nixgates** [comment]
The idea moving forward is to add a "More orrents button to the source selection interface. 

This will allow auto play users to experience Seren in an automated fashion while allowing users who wish to be more vigilant with their source selection to ability to manually select and cache items they prefer.

A new GUI interface will need to be built for this, changes to the source selection window will need to added as well and changes to cache assist module will be required.

**Comment by lukehansford** [comment]
Sounds a great way because you will be able to see what Seren has found cached first and if you don't like any of the cached links you can go ahead and cache your own.

**Comment by megavectra** [comment]
Is it or would it be possible to have movie and tv titles include the year of release?

**Comment by kmb519** [comment]
Nix,

Perhaps just adding a shortcut on the enhanced context menu to launch cache assist manually?

**Comment by nixgates** [comment]
Added in 2.0

Closing
