### ISSUE TITLE
[BUG] Episodes in "Black Hole"

### ISSUE THREAD

**Issue by TapMeDead** [nixgates/plugin.video.seren#821]
**Describe the bug**

-
--- TV Show episodes seem to wander into a black hole between "Upcoming Episodes" and "Next Up" categories.
-
**Log**

Please attach or link to and uploaded log file here.
Log files are required, and debug logs are preferable.
See the Kodi wiki for information on [how to get a log file](https://kodi.wiki/view/Log_file/Easy).
-
--- There is no log of this issue as it is just a minor observation.
-
**To Reproduce**

Steps to reproduce the behavior, for example:
1. Go to '...'   - 
-
--- Well to reproduce it, you need to be awake, keep an eye on upcoming episodes, and of course actively be observing for this issue several times every day, because the episodes will disappear for a few hours, maybe up to 6 hours or so?
-
**Expected behavior**

-
--- If an episode says airing on Sunday, when it's Sunday it should actually just wander straight from Upc. Eps into Next Up instantly.
(this might have something to do with time zones but at this time, its 2pm Copenhagen Time, it shouldn't be zone related anymore)
(I am looking more for an explanation than a "fix it" response, just curious how this works and why)
-
**Environment**

 - Operating System Windows 10
 - Kodi Version [e.g. 18.9, 19.1] V 19.4
 - Seren Version [e.g. 2.1.3] Serven V 2.2.1

**Screenshots and Additional Context**

If applicable, add any other context or screenshots about the problem here.

**Comment by drinfernoo** [comment]
A debug log would be best here, I think. That'll give us a detailed look at everything that's going on behind the scenes.
