### ISSUE TITLE
Ratings.

### ISSUE THREAD

**Issue by TapMeDead** [nixgates/plugin.video.seren#824]
Just a question.
Where does Seren grab the Ratings from on the information page?
They are all completely off, and I keep finding older movies with very few voters on them.
If these are from Trakt it seems like people rating movies on Trakt are doing what they can to create the wrong ratings.
The ratings can be too high, I mean crappy indie movies with 6.9 rating and there is literally no acting in the actors, for example.
They can also be too low, but the carrying factor is, they are almost never correct, at least not what I'd expect them to be.

I guess I'm suggesting grabbing the ratings from IMDB or elsewhere if at all possible. At least those ratings are in the general area of being correct.

**Comment by drinfernoo** [comment]
Seren gets ratings (and all other metadata) from a variety of sources, including Trakt, TMDb, TVDB, and OMDB (I may even be missing one), before collating them into a single object.

I'm not sure off the top of my head which service is prioritized for ratings, but the numbers being "too high" is not Seren's fault. If you didn't think the movie deserved its rating, rate it yourself and move on, I think.

**Comment by TapMeDead** [comment]
@drinfernoo Thanks for the reply. I know it's not Seren's fault when the ratings don't fit the movies. But it is kind of Seren's fault if the ratings are grabbed from somewhere where the website "ideology" of voters are to manipulate the ratings.

I thought Seren was primarily Trakt for info searching, and Trakt is just weird with their rating system, and the voters there seem to work hard to give false ratings. That is all I meant.
