### ISSUE TITLE
Smartplay Seems to be Broken 

### ISSUE THREAD

**Issue by lennon1997** [nixgates/plugin.video.seren#825]
Hello, 
Seren SmartPlay feature seems to have been broken sometime within the last couple weeks. The first episode I select to play will work without issue but while Seren searches for the next episode in the playlist I get the aforementioned error popup. When the first episode ends, instead of playing the next item in the paylist it just hangs forever on the screen that shows which file and source it has found. I've checked and confirmed that this error happens on a fresh install of Kodi as well as on another device I own (Mac OS). My main device is running on Windows. I'll provide the respective logs below.

Windows Log: https://pastebin.com/jpNFkeVq
MacOS Log: https://pastebin.com/3Lq9b8Vc

Just a heads up that Kodi doesn't seem to shutdown properly on my Mac so the logfile ends a bit earlier than the Windows log.

Please let me know if any more information is required and I'll be happy to supply it.

Edit: I've just asked my father to try to replicate the issue on his setup (Nvidia Shield) and his is working absolutely fine so I'm not sure why I'm getting this issue on two separate devices possibly something having to do with my Trakt account?

Thank you.

**Comment by lennon1997** [comment]
I did give reauthorizing my RD account a try after doing a clean install of Kodi and it continued to produce the same issue. I'll keep giving it a go every now and then and see if that kicks it back into a working state. 

What's odd is that my father and I are both using the same RD account on the same network and his is working without issue.

**Comment by lennon1997** [comment]
Not sure what the issue was or why it was happening on two of my devices, but I think I have an idea of what was happening. I restored my setup from a backup and noticed I was also getting an error when trying to wipe Seren addon data. I instead Manually deleted all Seren related folders from my user data folder. After doing so and reinstalling Seren along with all of the reauthorizations everything seems to be working properly.

Thanks for the support.

**Comment by drinfernoo** [comment]
Sure, could've been an odd file corruption or "stuck" setting 🤷 Glad it's working now 👍
