### ISSUE TITLE
[REQUEST] Write a Jellyfin plugin

### ISSUE THREAD

**Issue by jclsn** [nixgates/plugin.video.seren#826]
**Describe the feature you'd like**

I would really like to have a Seren plugin for Jellyfin. It would offer provide the capability of using Debrid services on many different devices - even your phone.

**Comment by drinfernoo** [comment]
Seren can already use Debrid services on many devices, including phones... I don't see how Jellyfin helps that situation 🤔

**Comment by jclsn** [comment]
Well, Seren is the only reason that I still use Kodi. I would like to have an easier method. First I thought about writing a webOS app for my LG TV with the same functionality, but it would be nice to make it portable, where Jellyfin would come into play. Maybe there are better ways. Seren is the best in what it does, but Kodi as a platform is a disadvantage. It is buggy and no new features are being added. 

Maybe the best solution would really be a web app, which you can then easily port to webOS, Android etc. What do you think?

**Comment by drinfernoo** [comment]
Sure, but that's entirely out of the scope of this project.

**Comment by npmstart-pray** [comment]
...but they're free to fork it to make it do what they want, where they want.

**Comment by jclsn** [comment]
Well, Seren relies on Kodi libraries. I guess it would be easier to start from scratch. A web app should be written in Javascript or some derivative anyway.

**Comment by npmstart-pray** [comment]
You've got some reverse engineering to do, then...

**Comment by jclsn** [comment]
Well not really. Reverse engineering would be a trying to understand a black box. I am playing around with the Alldebrid Rest API atm. Maybe I will try soon.

**Comment by npmstart-pray** [comment]
"Playing around" with making various software work together is exactly the same as hardware, getting it to function as desired/expected. Either way, you still need all the right components and an understanding of how and why they work together (or not).

**Comment by jclsn** [comment]
Sure, but it is still not reverse engineering. I would also not fork the Seren code, since it is too tightly bound to Kodi. Rather take Jellyfin as a basis for the web layout and fill it with using the TMDB and IMDB APIs etc

**Comment by drinfernoo** [comment]
We have now gone so far as to prove that this isn't the appropriate place for this issue, as it and the surrounding conversation are now firmly proven to be outside of not only Seren's scope, but Kodi's as well.
