### ISSUE TITLE
[Feature request] Cancel button when scraping

### ISSUE THREAD

**Issue by Baardmans** [nixgates/plugin.video.seren#83]
Sometimes, when scraping for sources, the final source to be scraped takes a while.
It would be good to be able to cancel this process and have it play a stream that's already been found.

Thanks in advance!

**Comment by pencey** [comment]
Doesn't pressing the back button work for this? B on my shield remote does this!

**Comment by Baardmans** [comment]
Dan, I feel so stupid right now... Thanks @pencey!
