### ISSUE TITLE
[BUG] Premiumize API error: An unknown error occurred when scraping

### ISSUE THREAD

**Issue by CEV-A** [nixgates/plugin.video.seren#837]
**Describe the bug**

On a fresh install of Kodi and Seren, I get an error when scraping for sources. It says "Premiumize API error: An unknown error occurred". But the Premiumize sources still show up in the source select menu.

**To Reproduce**

1. Go to a movie or TV show episode (I used Andor S01E07)
2. Scrape
3. See error when it's searching through the list of providers (just before source select)

**Expected behavior**

No error

**Kodi Version**

 - Kodi Version 19.4
 - Seren Version 2.2.3
 - Nvidia Shield 9.1.1

**Additional context**

Log: https://paste.kodi.tv/ibakexisiq

- I've tried clearing cache in Seren, clearing local torrent cache, reauthorizing, wiping addon data and fresh install of Kodi, still get the same error

**Comment by CEV-A** [comment]
Reddit users are saying they have the same issue with Premiumize, it might not be the fault of the new Seren updates, sorry about the issue if that's the case:

https://www.reddit.com/r/Addons4Kodi/comments/ymcl3c/seren_premiumizeme_api_error/

https://www.reddit.com/r/Addons4Kodi/comments/ym8ilr/no_sources_or_lack_of_in_fenezraumbrella_with/

**Comment by MikeTosen** [comment]
Also getting this error,  seren 2.2.3 and premiumize
