### ISSUE TITLE
[BUG] quick resume show play last watched episode

### ISSUE THREAD

**Issue by phantom9s** [nixgates/plugin.video.seren#838]
**Describe the bug**
After the last update, click "Quick Resume" to show and play the last watched episode instead of the unwatched episode.

**To Reproduce**
go to any tv show 
use context menu to quick resume show

**Expected behavior**
Play the unwatched episode instead of the last watched episode.

**Kodi Version (please complete the following information):**
 - Kodi Version 19.4
 - Version 2.2.3

**Comment by drinfernoo** [comment]
Please attach a full debug log for further investigation.

**Comment by nixgates** [comment]
@phantom9s is this still an issue?

Looks like we haven't heard back in a while.

**Comment by phantom9s** [comment]
after Seren 3.0 update it didn't happen thank you for the hard work
