### ISSUE TITLE
[BUG] Trakt scrobble not saving resume point

### ISSUE THREAD

**Issue by MikeTosen** [nixgates/plugin.video.seren#839]
Watching and episode and stopping in the middle use to save a resume point, that does not happen anymore. 

**To Reproduce**
1. Play any movie or series episode.
2. After the srobble start point stop the movie/episode.
3. No resume point is saved, movie/episode starts from the beginning. 

**Expected behavior**
Once stoped it should save a resume points, if you select the same movie/series, it should resume from the point where you stopped.

**Kodi Version (please complete the following information):**
 - Kodi Version 19.4
 - Version 2.2.3

**Here is a full log.**
https://paste.ubuntu.com/p/ZcX2Z3M4Sr/

**Comment by drinfernoo** [comment]
Please attach a full debug log for further investigation.

**Comment by AnthonyA1223** [comment]
I can confirm I've experienced this bug aswell, Kodi 19.4 , seren 2.2.3 running on Android TV.

**Comment by MikeTosen** [comment]
> My initial guess is that Trakt may need to be reauthorized, or that your device may need a reboot.
> 
> Please attach a full debug log for further investigation.

Is the log I attached sufficient?

**Comment by Eman2108** [comment]
Me too. Installed 2.2.3. Resume point not saved when episodes or movies stopped after the 180 seconds scrobble threshold. Cleared seren settings, and re-authorised Trakt and real debrid. Resume point still not being saved.

**Comment by drinfernoo** [comment]
We've got some fixes coming in the next major release that should help with this.

**Comment by MikeTosen** [comment]
Ok, so just to confirm - this is not in 2.2.4 ?
As the problem is still the same as in 2.2.3.

**Comment by MikeTosen** [comment]
Don't worry - just read the changelog for 2.2.4 ...

**Comment by npmstart-pray** [comment]
> Our next (planned) major release is to be 3.0.0

Will that make Seten kodi v20 compatible?

**Comment by drinfernoo** [comment]
That hasn't been addressed directly yet, and probably won't be a major feature in 3.0.0, but hopefully we'll get there in the near future.

**Comment by drinfernoo** [comment]
@MikeTosen Can you confirm this is fixed in 3.0.0?

**Comment by MikeTosen** [comment]
It seems to be working just fine now 👍😁
Thanks for all the hard work and effort

**Comment by MikeTosen** [comment]
It seems to be working just fine now 👍😁
Thanks for all the hard work and effort
