### ISSUE TITLE
[feature request] hide season 0 / specials

### ISSUE THREAD

**Issue by Baardmans** [nixgates/plugin.video.seren#84]
The title says it all I think, but this would be a good feature to have, for me at least : )

Thanks in advance!

**Comment by nixgates** [comment]
Added and will be released with next public update

**Comment by nixgates** [comment]
Feature now available in Seren 0.2

**Comment by Baardmans** [comment]
@nixgates, thanks, works like a charm! With the update I also finale see watched indicators on my home screen widgets! 👍🏻
