### ISSUE TITLE
mdblist 

### ISSUE THREAD

**Issue by ronfrankhill** [nixgates/plugin.video.seren#843]
Is it possible for you to add mdblist API key ( https://mdblist.com ) to settings. Please.

**Comment by drinfernoo** [comment]
We won't be adding mdblist.com integration.

If you'd like to see lists from there inside Seren, you can create them at https://mdblist.com/mylists/, sync them to Trakt, and access them inside Seren from the `My Movies/Shows -> My Lists` section(s).
