### ISSUE TITLE
[BUG] repeatable Seren bug crashes to desktop 

### ISSUE THREAD

**Issue by Disdamn** [nixgates/plugin.video.seren#845]
**Describe the bug**
Searching for "Somebody Feed Phil" or presence of "Somebody Feed Phil" in watch list inside Seren crashes Kodi to desktop with no error log within 5-15 seconds 

**To Reproduce**
1. Go to search TV Shows
2. Search for "Somebody Feed Phil" 
3. After search completes. Wait 5 to 15 seconds and Kodi will crash to desktop with no error log

Alternative Steps to Reproduce 
1. Go to Trakt.tv and add "Somebody Feed Phil" to your watch list. 
2. Inside Seren force a sync with Trakt and then go to your tv watchlist
3. Wait 5-15 seconds and seren will crash Kodi to desktop with no error log

**Expected behavior**
No crash

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 19.4
 - Nvidia Shield Pro

**Additional context**
Fresh install after running into the same error with 19.3

**Comment by drinfernoo** [comment]
Please attach a full debug log as required in the bug report template.

**Comment by Disdamn** [comment]
> Please attach a full debug log as required in the bug report template.

Sorry, I'm still learning the details of Seren and Kodi. 


How do I attach a log if the error does not generate a log? I can empty the log file, reproduce the error and the log file will still be empty.

**Comment by drinfernoo** [comment]
https://kodi.wiki/view/Log_file/Easy

**Comment by nixgates** [comment]
@drinfernooi think this was a known issue with kodi's autocomplete wasn't it? 

The search function shouldn't be able to crash Kodi in theory.

@Disdamn how did you go with your log?

**Comment by drinfernoo** [comment]
@nixgates No log... so no way to now 🤷

That bug with Autocompletion *should* be fixed in recent versions though.

**Comment by nixgates** [comment]
@Disdamn as this issue has become a bit stale and not reproducible on our end, I'm going to close it off.

It you like you are welcome to re-raise the issue and we will continue looking into it :)
