### ISSUE TITLE
Slooooow

### ISSUE THREAD

**Issue by pdjaecf641** [nixgates/plugin.video.seren#848]
When is Seren going to release the major update? I've seen it teased in other issues here and I'm still waiting for Seren to support Easy News. What's taking so long?

**Comment by drinfernoo** [comment]
> When is Seren going to release the major update?

Depending on the context of when Internet historians find this issue, sometime between soon™ and never™...

We've been working diligently to get out a new major update, but things take time.

> What's taking so long?

Adding new features and fixing bugs takes time. Testing those features and fixes takes time. Triaging bug reports takes time. Everything takes time.
