### ISSUE TITLE
Resume Points still acting oddly.

### ISSUE THREAD

**Issue by TapMeDead** [nixgates/plugin.video.seren#852]
I am not sure if its a bug yet, but for a few days it seems like some resume points are not being created properly, and Seren has always had a bit of an issue with actually resuming from resume points.

So for now, I just want to point out that it feels like there is a bug in that system still.

I see this with both movies and shows, mostly shows though. Sometimes Seren saves no resume point, other times it does save one, and the indicator on the episode will be there and everything, yet Seren does not register to actually move to the resume point after starting to play.
https://logpaste.com/ElsoC2D2

**Comment by drinfernoo** [comment]
We've done a lot of fixes to this hunk of code that should help. Here's looking forward to 3.0.0 👍

**Comment by npmstart-pray** [comment]
> We've done a lot of fixes to this hunk of code that should help. Here's looking forward to 3.0.0 👍

Will it (Seren v3.0.0) be ready for the kodi v20 release?

**Comment by drinfernoo** [comment]
@TapMeDead, is this working fine for you now in 3.0.0?

**Comment by TapMeDead** [comment]
@drinfernoo yep much better. Resume points and using them all works so far :)
I haven't flipped through settings, are there some news I need to check out?
Thanks for asking by the way :)

**Comment by nixgates** [comment]
@TapMeDead im just gonna close this one off, but @drinfernoo can fill you in any new settings :)

Good to hear its all running smooth!
