### ISSUE TITLE
[BUG] Seren popup comes up in other addons.

### ISSUE THREAD

**Issue by TapMeDead** [nixgates/plugin.video.seren#855]
Been using loonatics Empire while this trakt issue is active. But every now and then, a Seren Log file warning pops up, even when I haven't touched Seren at all and just went straight into LE to watch movies.
I think to remember this same warning coming up in Magic Dragon as well.
Not sure what Seren would be doing behind the curtains, while other addons are active?
Anyway, attaching a screenshot of the warning popup, and my log file.
Time was 23:04 when I started typing this message, the popup came up somewhat around 23:01 my time.
https://logpaste.com/mI2LyV7j
![Screenshot_1](https://user-images.githubusercontent.com/99356645/208267679-800e1fe9-8afa-4482-951b-2b02de953c52.png)

**Comment by drinfernoo** [comment]
Seren continuously runs a service, which updates the Trakt database (among other things) every 13-17 minutes.

The error messages are due to issues with Trakt over the last few days.

**Comment by npmstart-pray** [comment]
> The error messages are due to issues with Trakt over the last few days.

Four days. Or is it 5?  1/90th of year or thereabouts. Hopefully we'll be able to stream again with Seren before Christmas if they decide that their systems are solid enough to reactivate their API. 

Meanwhile, over at Simkl:
![image](https://user-images.githubusercontent.com/18369734/208341273-8d042fa4-c174-4063-8489-c311a1adb336.png)

It's time to consider backup, wouldn't you agree, Doc?

**Comment by TapMeDead** [comment]
@drinfernoo 
> Seren continuously runs a service, which updates the Trakt database (among other things) every 13-17 minutes.
> 
> The error messages are due to issues with Trakt over the last few days.

Seren should not be doing things when we're not in Seren. And even if it was necessary, maybe lay in a failsafe, so that when trakt is down for prolonged time, we really only need to see that Seren Log file warning one time in each session.
I am not trying to teach you programming, not my job, but as a normal user, we expect certain things, and we don't expect Seren messages while in other addons right? hehe.
Especially when trakt has issues, your programming needs failsafes, because as it is now, we get 10-15 trakt warnings in every movie we watch, from the addon we're in, and then 6 times a Seren warnings as well? naahh man, that aint right, right? :)
