### ISSUE TITLE
Max retries error on logs

### ISSUE THREAD

**Issue by luizffgarcia** [nixgates/plugin.video.seren#856]
Hey guys, i could not find this error in the current issues.

Seren is not working at all for me right now, for days actually, the logs say "max retries exceeded" for api.trakt.tv" so i am guessing there is something wrong with trakt? Or is this something related to serens key to trakt?

**Comment by npmstart-pray** [comment]
Trakt has had their APU shut down for almost 5days at this point because of a data/server crash. They're busy bringing it back, but we should be upset they didn't have a speedy backup system in place.

**Comment by luizffgarcia** [comment]
> Trakt has had their APU shut down for almost 5days at this point because of a data/server crash. They're busy bringing it back, but we should be upset they didn't have a speedy backup system in place.

Oh that explains it, thanks!

**Comment by luizffgarcia** [comment]
Closing
