### ISSUE TITLE
[BUG] Finish Watching not syncing with Trakt

### ISSUE THREAD

**Issue by freedom85uk** [nixgates/plugin.video.seren#857]
When I watch a TV Show or a Movie the progress is not being synced with Trakt and is not appearing in the "Finish Watching" section within Seren. I have done the following:

1. Rebuild/force sync Trakt.
2. Re-install Seren
3. Made sure Seren is on the latest version (2.2.4)
4. Tried another skin. 
5. Revoke Trakt

I've also noticed that sometimes it shows as playing trakt and then when I stop it on Kodi it continues the progress on Trakt still

Thanks, Luke.

**Comment by drinfernoo** [comment]
Please update to Seren 3.0.0 and see if this is still an issue.
