### ISSUE TITLE
All TV show categories such as Trending and my shows have stopped loading 

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#86]
All the TV show categories have stopped loading since yesterday.

All the movie categories are working fine including movie Trakt Watchlist.

**Comment by lukehansford** [comment]
It looks like it is just all the my shows sections.

**Comment by nixgates** [comment]
Trakt had an outage yesterday, please try clearing your cache and re-attempt to load the menus.

Trakt appears to have resolved the issue on their end now.

**Comment by lukehansford** [comment]
The issue is still hapening. 

The my shows sections are having trouble loading such as collection, next up and even the trending TV shows section.

It looks like an issue with TVDB.com

It's only affecting the TV show sections. I can load Trakt fine such as movie lists and watchlist. 

Here's a log 

https://paste.kodi.tv/egimolosec

**Comment by nixgates** [comment]
From what I can see in the log you are experiencing some network issues on your end: 

> NewConnectionError('<urllib3.connection.HTTPConnection object at 0x807b9450>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

> CCurlFile::Stat - Failed: Timeout was reached(28) for https://image.tmdb.org/t/p/w500/svIDTNUoajS8dLEo7EosxvyAsgJ.jpg

> Failed: Timeout was reached(28) for http://thetvdb.com/banners/fanart/original/5c30ff2071f03.jpg

Can you please try and restart your router and device.

Some of your connections are going through but also some look to be timing out or dropping.

From what I can see, TVDB and Trakt are both up and operational.

**Comment by lukehansford** [comment]
Could it be related to the cloudflare issue?

Had no issues untill today.

Trakt is working great on other add-ons such as Gaia and on all the movie section s it loads perfectly including my Trakt movie latest releases list and watchlist. 

Could it maybe be tvdb and a cloudflare peering issue.

**Comment by lukehansford** [comment]
I can load both of those artworks instantly

**Comment by nixgates** [comment]
Can you please do the following temporarily disable your skin, clear your cache and turn off your device. Restart your router, turn on your device and try to navigate to a TV show menu in Seren using the default Kodi skin.

**Comment by lukehansford** [comment]
I have been using the default skin.

I have cleared the Kodi cache, Seren cache and even used reapers wizard to clear the cache.

Have restarted router and device many times. 

It shows a continuous loading icon for any of the TV show sections including Trending and Next Up.

Here is a fresh log file

https://paste.kodi.tv/vucugekuco

**Comment by lukehansford** [comment]
I have done another fresh install and still doesn't work.

All other Kodi add-ons are working for tv shows

**Comment by lukehansford** [comment]
I have installed Kodi 18.1 on my phone and it still does not load which rules out the firestick 4K.

Looks like tvdb or some other service is being blocked or the specific API or URL that Seren is using.

**Comment by lukehansford** [comment]
Changing up address does not fix it either. So strange that the only thing being blocked in the TV sections surely that must mean it is tvdb?

**Comment by lukehansford** [comment]
It is working on WiFi on my phone but not on Firestick 4K.

Could it be something just affecting this device?

**Comment by lukehansford** [comment]
I have created a TVDB API key and put that into Seren and it still won't load the TV sections.

Surely they are coded the same as the movie sections. 

I'm using a Firestick 4K and Kodi 18.1

I can't understand why it would stop working overnight.

Its working on Kodi on my android phone.

**Comment by nixgates** [comment]
@lukehansford 
I suggest at this point you try the new development branch, you can download a zip with this URL
https://github.com/nixgates/plugin.video.seren/archive/Development.zip

Let me know if the updates included in the development branch help to alleviate your issues

**Comment by lukehansford** [comment]
It has started to work again.

It must of been a trakt or server issue.

Thank you for all your help with this.
