### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by agoodz** [nixgates/plugin.video.seren#862]
**Is your feature request related to a problem? Please describe.**
There is no resolveURL under manage dependencies in Kodi after installing Seren. That is what I use in order to connect to real-debrid.

**Describe the solution you'd like**
Implement resolveURL install for Kodi when downloading Seren.

**Comment by nixgates** [comment]
Seren has its own inbuilt resolver and doesn't use ResolveURL or URLResolver.

Just setup the debrid provider inside Seren's settings and it will work.

Make sure to read a guide on setting up Seren if you have any further issues. 😊
