### ISSUE TITLE
[BUG] Settings are now empty after 3.0 update.

### ISSUE THREAD

**Issue by ndeering5** [nixgates/plugin.video.seren#863]
Unable to see any settings when opening the settings menu.

1. Click 'Tools'
2. Click on 'Open Settings Menu'

Same for:
1. 'Video Add-ons'
2. 'Seren'
3. 'Configure'

There is now nothing when clicking open.

Kodi 19.3

**Comment by nixgates** [comment]
Cant seem to recreate this issue, I've performed a clean install on a machine and updated an unclean version today and both have been fine.

It almost sounds like the installation failed in some way and the settings file is corrupt.

Might I ask what kind of OS you're running on? (Android, Linux, Windows)

**Comment by ndeering5** [comment]
Looks like it was a corrupt install. Uninstalled and reinstalled and it is working. This can be closed, thank you.

**Comment by nixgates** [comment]
Great news! Thanks for checking back and letting me know!
