### ISSUE TITLE
Shuffle play[BUG]

### ISSUE THREAD

**Issue by JOHNNYFLASH2002** [nixgates/plugin.video.seren#868]
Shuffle play behaving like play from random.  Playing episodes in order after first is chosen. Instead of shuffling in random  episodes

**Comment by drinfernoo** [comment]
That should be fixed by updating `context.seren` to 3.0.1 :+1:

**Comment by nixgates** [comment]
@JOHNNYFLASH2002 

Howdy! 

I've confirmed this is resolved now so I'm going to close this off. 

If you find for any reason its not just let us know and we can re-open this issue.
