### ISSUE TITLE
Error Contents: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by nullpat** [nixgates/plugin.video.seren#874]
I searched TV Shows > Foundation > Season 2 > Trakt Manager > Refresh Item Metadata
and now every time I try to go under Foundation I just get the pop up saying there's an error, can't select a season, luckily I just finished the last episode of season 1 and season 2 is unreleased. I wanted to refresh season 2 data to check release date, not sure if thats relevant or not. Log is below
[kodi.log](https://github.com/nixgates/plugin.video.seren/files/10336192/kodi.log)

**Comment by drinfernoo** [comment]
Please update to at 3.0.0. Your log indicates you're running version 2.1.9, which is quite an old version at this point.
