### ISSUE TITLE
[BUG] Trakt and Seren up-next not syncing

### ISSUE THREAD

**Issue by ajclarke90** [nixgates/plugin.video.seren#879]
**Describe the bug**
Trakt watchlist and Seren Up-next no longer seem to be syncing. 

**To Reproduce**
1. Go to Seren Up-Next
2. Compare with Trakt Up-next

**Expected behavior**
These should match. I've tried rebuilding the trakt database on Seren, and removing auth and reauthing. Nothing seems to fix. It also seems that a show I have "hidden" from my up-next on Trakt is also still showing. Some shows do update if I watch an episode. 

**Screenshots**
![seren](https://user-images.githubusercontent.com/4687383/211009465-d0b296ee-8add-4d41-b89b-78acac000cdd.png)
![trakt](https://user-images.githubusercontent.com/4687383/211009480-c0e4b1a7-743d-4d63-b620-dfb71f900b7e.png)

**Kodi Version (please complete the following information):**
 - Kodi Version 19.5 Matrix
 - Seren Version 3.0.0

**Comment by nixgates** [comment]
@ajclarke90 Did you happen to reset Penny Dreadful?

Note in the image above the episode is marked as watched on the Trakt website (purple tick button). If it has been watched it won't show up in Seren's next up.

**Comment by ajclarke90** [comment]
Aah indeed, that is the case. So I assume that the up next on Seren's side isn't taking it from the up next on Trakt, but instead looking for unplayed episodes in the series. That's a shame. I'll just have to manually search for things I'm re-watching, I assume that with that being said as well, is why WEstworld S4 still appears even though I've removed it from up-next on Trakt. 

Appreciate the quick reply,

**Comment by nixgates** [comment]
Ah not entirely sure what you mean, but to remove something from the Next Up list, it either needs to be marked as hidden or the show completely marked as not watched. 

We are however looking into integrating the re-watch feature of Trakt so should hopefully all work soonish. We are just concentrating on bug fixes after the new release :)
