### ISSUE TITLE
Survivor - Season List is Wrong

### ISSUE THREAD

**Issue by Mastacc** [nixgates/plugin.video.seren#9]
Go to Survivor in TV Shows, and the season list is completely wrong. They're basically all in the wrong order. For example, the 30th season is listed as season 39 when there are only 37 seasons released.

I'm not sure if trakt's Survivor page is just wrong or if it's a strange bug since all other shows I've seen are correct. Perhaps other shows are also wrong, but this is the only one that I've noticed.

**Comment by dm2912** [comment]
survivor is an ongoing problem with all kodi add ons. For years even trying to play an episode of survivor caused covenant, incursion, exodus and anything else to crash completely. Theres something really badly up with the survivor meta on both trakt and tvmd

**Comment by Mastacc** [comment]
The season list is in the right order on the Exodus forks. I assume it's because on Trakt the seasons aren't listed as "Season 1", "Season 2" but instead "1: S1Name", "2: S2Name" which makes it bug in seren or something. Never had a problem before.

**Comment by nixgates** [comment]
The issue is Seren alphabetical sorts seasons. 
I'll add a sort to season lists to sort by season number and still display the season title.

**Comment by nixgates** [comment]
As of 0.1.22 Seren now lists seasons by season number but also retains the season name

Development git has been updated and repo will receive update within the next 24 hours should no major issues arise.
