### ISSUE TITLE
Some items unplayable not all

### ISSUE THREAD

**Issue by trowieuk** [nixgates/plugin.video.seren#90]
Never had this issue with previous version. Some work, some don't. Including ones that worked before new update.

![screenshot000](https://user-images.githubusercontent.com/45860444/56070505-043fd500-5d80-11e9-9810-e830c45b3514.png)

00:00:18.849 1:2204 ERROR: Traceback (most recent call last): 00:00:18.849 1:2204 ERROR: File "C:\ Users \TROW1E \AppData \Roaming \Kodi \addons \plugin.video.seren \seren.py", line 193, in <module> 00:00:18.850 1:2204 ERROR: if len(source_results) > 0: 00:00:18.850 1:2204 ERROR: TypeError: object of type 'NoneType' has no len() 00:00:18.945 T:11300 ERROR: PlayMedia could not play media: plugin://plugin.video.seren/?action.getSources&source_select=true&actionArgs=%713%22episodelnfo%22%3A%20%713%22art%22%3A%20%7B%2

**Comment by nixgates** [comment]
Issue resolved in Seren 0.2.8
