### ISSUE TITLE
I don't know where else to go for help

### ISSUE THREAD

**Issue by DFergFLA** [nixgates/plugin.video.seren#908]
I am new to Seren and pretty new to Kodi.

I installed Seren a few days ago and got it working no problems.  It was easy and wonderful.  Then my Kodi install got messed up.  Not  Seren but I ended up uninstalled Kodi and all the setting.  I went to users\userid\appdata\roaming and made sure the Kodi directory was completely gone.

Now I can't get Seren to work.  I can't configure a provider.  I am using the same provider I did the first time.  http://bit.ly/a4kScrapers
When i enter that and click "ok"  I am expecting the screen "Seren: Custom sources install' with the option to install..  What I get is.. nothing... I get nothing... I put in the web address and then nothing.  Then Seren says there is no provider.   

I have no idea what to do.

**Comment by npmstart-pray** [comment]
Seren needs you to subscribe to a Debrid service to work correctly. RealDebrid and Premiumize are paid services that find and stream links to you, negating the need for a VPN. RealDebrid is about $0.10 per day (USD)

**Comment by drinfernoo** [comment]
@nomstart-pray **Do not** suggest that users take issues like this to the Kodi forum, please. You will only be greeted with derision, as they vehemently protest even the faintest whisper of third-party add-ons in their midst.

@DFergFLA If you haven't added a debrid account, you'll need to do that. If you have, and are still having issues, please open a proper bug report, using the template, and including a log.

**Comment by npmstart-pray** [comment]
> @nomstart-pray **Do not** suggest that users take issues like this to the Kodi forum, please. You will only be greeted with derision, as they vehemently protest even the faintest whisper of third-party add-ons in their midst.
> 
Just to be clear, I was musing that the problem might be found on the forum from an official addon. I know how they feel about us, and I share your disdain.
