### ISSUE TITLE
Audio Stream Question

### ISSUE THREAD

**Issue by Lasakro** [nixgates/plugin.video.seren#909]
How do I permanently disable Audio Stream "English- Commentary by Cast, ..."? When I select the normal one "[Unknown]- DTS-HD Master Audio ..." then Set as default for all media the newly applied default doesn't stick. I would just like to gut it out of Seren, soak it in gas and burn it.

**Comment by drinfernoo** [comment]
This has nothing to do with Seren. Set your audio and subtitle settings in Kodi.

**Comment by Lasakro** [comment]
So that is Player > Language & Player > Subtitles set to "User Interface Language.

That's so obvious how could I have missed that :)
But it works. I apologize for pointing my finger so quick to Seren. Love this code. I appreciate your speedy assistance.
