### ISSUE TITLE
issue with seren starting tv shows 

### ISSUE THREAD

**Issue by Fuckuptheworld13** [nixgates/plugin.video.seren#92]
im getting a popup when starting a tv show saying "one or more items failed to play check the log for more info" but it only happens when i have the kodi settings default select action to show info under media setting on this issue never happened to me before

**Comment by trowieuk** [comment]
try providing the log...

**Comment by nixgates** [comment]
@Fuckuptheworld13 could you please update to 0.2.8 and check if the issue is still occuring?

**Comment by nixgates** [comment]
I've identified an issue, can you please confirm two things for me?

Are you trying to play the item from the information screen?
Are you on Kodi 18.1?

**Comment by drinfernoo** [comment]
@nixgates Sounds like that's the exact issue.

**Comment by nixgates** [comment]
Pending Update, hopefully live in an hour or so

**Comment by nixgates** [comment]
@Fuckuptheworld13 could you please update and confirm issue is now resolved 👍

**Comment by Fuckuptheworld13** [comment]
@nixgates yea is working now thanks bro u r BEST! appreciate! your hard work
