### ISSUE TITLE
Seren "Locked User Account - Contact Trakt Support"

### ISSUE THREAD

**Issue by Jsalas424** [nixgates/plugin.video.seren#921]
**Describe the bug**
Am getting the error message on Kodi per the subject line:

Seren "Locked User Account - Contact Trakt Support"

**To Reproduce**
1. Have an existing Trakt config that never threw this error
2. Revoke Trakt Privelage, reauthorize with your trakt account, error banner pops up again.

**Expected behavior**

My Trakt history stops syncing on July 9th, I've seen this pop up with increasing frequency since then. 

**Kodi Version (please complete the following information):**
 - Kodi Version 19.4.0
 - Seren Version 3.0.

**Comment by drinfernoo** [comment]
> Locked User Account - Contact Trakt Support
