### ISSUE TITLE
[REQUEST] Include Watchlist in NextUp

### ISSUE THREAD

**Issue by veinoffeeling** [nixgates/plugin.video.seren#922]
There is a feature in Fen that is really nice, that it lists shows you haven't started yet, but have in your Watchlist, in the NextUp list. This is really helpful for when a new show hasn't started yet, but you don't want to have to remember to constantly check.

It would be fantastic if this could be integrated into Seren, as it is the only feature that has me bouncing between Fen and Seren.

Thank you so much devs for this amazing addon!

**Comment by drinfernoo** [comment]
That won't be being implemented. Watchlist is for shows you plan to watch, and Next Up is for shows you have started but not completed.

**Comment by veinoffeeling** [comment]
yikes... ok...
