### ISSUE TITLE
Seren freeze with 0.2.8 version

### ISSUE THREAD

**Issue by Jezze83** [nixgates/plugin.video.seren#93]
With latest seren version, kodi freezes no matter what kodi version is installed. Freezes whole system when try enter seren menu and even when trying install from nix repo. Reddit have thread for that and other users have same problem. How to solve this @nixgates ?

**Comment by nixgates** [comment]
Please manually update to 0.2.8, I don't know how this could have been caused but I can't replace it in the latest update.

**Comment by nixgates** [comment]
Sorry, I just noticed you said you had 0.2.8 installed 

Could you please provide a debug log up until the freeze?

**Comment by nixgates** [comment]
Able to replicate on a Linux device but appears working on Windows. Please give me some time to check what's happening

**Comment by Jezze83** [comment]
At the moment i dont have any version installed because i manually deleted seren and i cant install any version because kodi freezes. Im running libreelec with pc.

**Comment by nixgates** [comment]
Issue with repository should now be resolved.

Thank you for reporting it
