### ISSUE TITLE
Seren for Omega Error Message 

### ISSUE THREAD

**Issue by rogermae** [nixgates/plugin.video.seren#934]
**Describe the bug**
Error type: < class ' sqlite3.OperationalError'>
Error Contents: bo such table: files

**To Reproduce**
Once Kodi loads, error message pops up

**Expected behavior**
Clean load with no error messages 

**Screenshots**
![20240406_123921](https://github.com/nixgates/plugin.video.seren/assets/36041288/d03328da-cd42-4571-967f-f035a5347cc8)
![20240406_124044](https://github.com/nixgates/plugin.video.seren/assets/36041288/c32c85b7-d390-4464-9a9b-0288bbdc8c10)

**Kodi Version (please complete the following information):**
 - Kodi Version: Omega

**Additional context**
None

**Comment by Omarscomin** [comment]
This might help you:

https://www.reddit.com/r/Addons4Kodi/s/wpWRZwvoEj

**Comment by rogermae** [comment]
Thanks this helps.
