### ISSUE TITLE
Seren does not work on the newly released kodi version 21 (Omega)

### ISSUE THREAD

**Issue by peno64** [nixgates/plugin.video.seren#935]
**Describe the bug**
Seren does not work on the newly released kodi version 21 (Omega)
When kodi starts, an error is shown and the following is logged in kodi.log:

plugin.video.seren\resources\lib\modules\globals.py", line 633, in get_kodi_database_version
                                                       raise KeyError("Unsupported kodi version")

**To Reproduce**
Just start kodi 21 and install Seren

**Expected behavior**
No error should be shown

**Screenshots**

**Kodi Version (please complete the following information):**
 - Kodi Version 21.0

**Comment by peno64** [comment]
Probably the only thing that must be changed is editing plugin.video.seren\resources\lib\modules\globals.py and add on line 632 the following:

        elif self.KODI_VERSION == 21:
            return "131"

See https://kodi.wiki/view/Databases

**Comment by ReK42** [comment]
Created a PR with that fix

**Comment by test01203** [comment]
Can you fix the bug? and release an update?

**Comment by Arthur1967** [comment]
Find the diggz repo he has seren for omega, which solves the problem until someone here fixes it

**Comment by Arthur1967** [comment]
I've had it from a long time ago and I can't seem to find it now but I got it saved on my USB luckily so you just have to find it somewhere![image](https://github.com/nixgates/plugin.video.seren/assets/69996032/f7b2f0c2-1856-4f76-ac3b-0fb83ce8ce32)

**Comment by Arthur1967** [comment]
https://diggz1.me/diggzrepo

**Comment by Arthur1967** [comment]
Hopefully that helps until someone here fixes it

**Comment by Arthur1967** [comment]
https://github.com/Arthur1967/plugin.video.seren that will work on Omega

**Comment by drinfernoo** [comment]
This has been fixed as of `3.0.1`.
