### ISSUE TITLE
Section "Unfinished shows in colection" is showing all shows

### ISSUE THREAD

**Issue by denimnani** [nixgates/plugin.video.seren#95]
The section "Unfinished shows in colection" is showing all shows even the complete ones.
In the version 0.1.35 this section worked fine, only shows series that actually have episodes to watch.
At this point I don't know in which version this stop to work properly.
:)

**Comment by lukehansford** [comment]
Same here

**Comment by nixgates** [comment]
Fixed pending Update

**Comment by denimnani** [comment]
Fixed, (0.2.22)
You are a machine :)
