### ISSUE TITLE
New error message near end of TV episodes in 0.2.15

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#96]
There is a new error message that has just started showing near the end of TV show episodes in the latest update 0.2.15.

It states 'no sources found for next item in playlist'
'Clearing current playlist'

I got the error on both the latest episodes of The Blacklist and American Gods when I played them from Next Up just before the end of the episode where I believe it would pre-scrape the next episode but obviously as they are the latest episodes there is no next episode available. 

This also triggered the Up Next add-on to show the prompt asking if I wish to play the next episode which has not aired yet till next week. 

I believe with the recent changes made to unaired episodes there has been a bug created where it is adding unaired episodes to playlists and then it is trying to pre-scrape links near the end of an episode as it normally does but obviously there won't be any links for episodes that have not aired yet.

Also on another note is it possible to make unaired episodes show as a different colour such as red as currently they show the same as aired epsiodes in season menus. The only way to see the difference is to look at the date. 

Did they not used to look different untill the latest updates?

**Comment by nixgates** [comment]
Fixed Pending Update
