### ISSUE TITLE
Creating playlist slower in latest update & time before scraping starts

### ISSUE THREAD

**Issue by lukehansford** [nixgates/plugin.video.seren#98]
I have noticed in update 0.2.15 when you select a TV show episode it is much slower and taking longer to create a playlist and the time before it starts scraping links. 

I'm specifically talking about the time you select the episode to play untill it begins the scraping process.

Wonder if it's possible speeds this up at all. 

If you watch alot of TV shows this is quite noticeable.

**Comment by denimnani** [comment]
I had a similar issue in the past,
I solved by wiping the addon data and setting up again.

**Comment by lukehansford** [comment]
This time delay has only started in the same update that added the Trakt syncing

**Comment by nixgates** [comment]
Issue has been identified and a workaround is ready for next public release

**Comment by nixgates** [comment]
Issue resolved in version 0.2.30
